### PR TITLE
fix: Volatile datasource ordering in dashboard export

### LINKED ISSUE #19478: Export Dashboard - Data Sources Ordering Is Volatile
When using the `export_dashboards` command on the CLI, everything is working great but I noticed that sometimes the order of the datasources changes in the list with no updates. I'm attempting to use the export functionality to git version my dashboard definitions and a reordering of my datasources with no changes ends up causing noise in my diffs.

#### How to reproduce the bug

1. Create dashboard with multiple data sources
2. Export dashboard
3. Make a tweak to the dashboard but dont change anything in the data sources
4. Export again and diff the files

Step 3/4 might need to be repeated a couple times as I don't know that it happens every time.

### Expected results

The export outputs should not be volatile, if I dont change a data source then there should be no diff when exporting multiple times. Exporting multiple times produces the same result always.

### Actual results

I have 2 tables in my data sources list and they switched positions without any changes.

#### Screenshots

An example of a dashboard with 1 chart. Changing the chart name from "AOV" to "AOV - New" caused a huge diff between the original and new export.

Screen Shot 2022-03-31 at 3 06 52 PM
Screen Shot 2022-03-31 at 3 07 26 PM
Screen Shot 2022-03-31 at 3 07 09 PM

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

I'm wondering if using a [set in the export_dashboards](https://github.com/apache/superset/blob/ab3770667c0b11043b177838f8c2eddd717fcfcc/superset/models/dashboard.py#L370) method is causing the list reordering in inconsistent ways.

I'm happy to help implement a change! Let me know if you think thats the issue or if something else might be causing it.

### PR DESCRIPTION
**Pull request by pnadolny13**
### SUMMARY

When using the export_dashboards command on the CLI the order of the datasources in the json is inconsistent so if you're trying to use git versioning theres a big diff from reordering. This PR implements sorting so this no longer happens.

Resolves: https://github.com/apache/superset/issues/19478

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

NA

### TESTING INSTRUCTIONS

I tried editing https://github.com/apache/superset/blob/f91f83d011b4c83576f5fff76d502f5616f2972d/tests/integration_tests/cli_tests.py#L76 like:

```python
    json_content = json.loads(contents)

    # check that datasources are ordered consistently
    assert json_content.get("datasources")[0].get("__SqlaTable__").get("database_id") == 1
```

to assert the order of the datasource ids but none of the existing dashboard fixtures have multiple datasources and I couldnt figure out how to add one with multiple datasources. So I didnt include the change to the test, if theres a way to stage a multi-datasource dashboard in the tests then I can gladly add a new test to do that!

To manually test prior to this PR:

1. Create multiple datasources in your Superset instance
2. Create a chart with each datasource
3. Add both charts to a dashboard
4. Export the dashboard using the CLI
5. Make a copy of the exported file
6. Export again and do a diff on the new vs copied file (you might need to export a few times before it changes because the ordering is random)

Following this PR there should never be a diff in the datasources if nothing changed.

### ADDITIONAL INFORMATION

- [x] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by rusackas** [comment]
@pnadolny13 are you able to rebase this PR so it's mergeable, and we can get this across the finish line? 

CC @betodealmeida in case anything has changed in this realm since the PR was opened.

**Comment by michael-s-molina** [comment]
Rebased

**Comment by mdeshmu** [comment]
Any update on this?

**Review by rusackas — APPROVED** [review]
Seems OK to me, so I'll stamp it. Can you think of any concerns here @michael-s-molina? Thanks for the rebase, btw ;)

**Comment by michael-s-molina** [comment]
> Can you think of any concerns here @michael-s-molina?

No concerns. I was just wondering if the same ordering problem can happen with other entities. If that's the case, maybe a solution that account for all entities, and not only datasources, would be better to deal with `git diff `problems. @betodealmeida probably has more context than me to evaluate the proposal.

**Pull request merged**
