### PR TITLE
fix: Duplicated plugin registration

### PR DESCRIPTION
**Pull request by michael-s-molina**
### SUMMARY
This PR removes the duplicated plugin registration that generates the following type of warning:

```
Item with key "deck_arc" already exists. You are assigning a new value.
Item with key "deck_arc" already exists. You are assigning a new value.
Item with key "big_number" already exists. You are assigning a new value.
Item with key "box_plot" already exists. You are assigning a new value.
```

The duplicate registration was necessary when those pages belonged to different React apps. Now, they belong to the same app which makes the registration unnecessary.

The registration should happen only once when the [application initializes](https://github.com/apache/superset/blob/3a0391bbb9138f1a3dab4d3c10d08e5520a4274d/superset-frontend/src/views/App.tsx#L45).

### TESTING INSTRUCTIONS
1 - Open any dashboard
2 - Check that the warnings are not there anymore

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by john-bodley — APPROVED** [review]

**Comment by alephpt** [comment]
Still seeing this problem in 5.0.0. Any advice?

**Comment by rusackas** [comment]
~~OMG THANK YOU. That's been nagging at me forever!~~

LOL, the new comment made me think this was a new PR. This is annoying, and is still an issue. Feel free to file a GitHub issue, or dig into this PR to see what changed since then and investigate a new fix. It'd be appreciated.

**Comment by mistercrunch** [comment]
Came here with the same idea -> ~~OMG THANK YOU. That's been nagging at me forever!~~

**Comment by michael-s-molina** [comment]
There are only 2 places in master calling `setupPlugins()`:


[src/views/App.tsx](https://github.com/apache/superset/blob/48699a71946fd5981dba1f6d2cfabd0315137889/superset-frontend/src/views/App.tsx#L46)
[src/embedded/index.tsx](https://github.com/apache/superset/blob/48699a71946fd5981dba1f6d2cfabd0315137889/superset-frontend/src/embedded/index.tsx#L48)

@Vitor-Avila @rusackas You might want to check if this call is required for Embedded.

**Comment by Vitor-Avila** [comment]
> There are only 2 places in master calling `setupPlugins()`:
> 
> [src/views/App.tsx](https://github.com/apache/superset/blob/48699a71946fd5981dba1f6d2cfabd0315137889/superset-frontend/src/views/App.tsx#L46) [src/embedded/index.tsx](https://github.com/apache/superset/blob/48699a71946fd5981dba1f6d2cfabd0315137889/superset-frontend/src/embedded/index.tsx#L48)
> 
> @Vitor-Avila @rusackas You might want to check if this call is required for Embedded.

@rusackas are you aware if that's necessary? I'm not sure

**Comment by mistercrunch** [comment]
Both these calls probably shouldn't be module-scoped ...

**Pull request merged**
