### PR TITLE
feat: Add a new database driver for Amazon DynamoDB

### PR DESCRIPTION
**Pull request by passren**
### SUMMARY

There is no database driver for Amazon DynamoDB so far. I developed a Python DB API 2.0 (PEP 249) client for Amazon DynamoDB and did some work to be compatible with Superset. My Project is [here](https://github.com/passren/PyDynamoDB). The latest version is 0.4.2 which have already supported Superset connector.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

image

### TESTING INSTRUCTIONS

Add the unit test for db_engine_spec of pydynamodb.
For the setup in the Superset, please refer to the doc in my project.
https://github.com/passren/PyDynamoDB/wiki/5.-Superset

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [X] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by passren — COMMENTED** [review]
This is a new database driver for AWS DynamoDB

**Review by nytai — APPROVED** [review]
LGTM

**Comment by villebro** [comment]
Thanks for this work @passren, awesome work! It would be nice if you could follow up by adding an entry to the [docs](https://github.com/apache/superset/tree/master/docs/docs/databases) to make it more discoverable for other users.

**Comment by villebro** [comment]
> Thanks for this work @passren, awesome work! It would be nice if you could follow up by adding an entry to the [docs](https://github.com/apache/superset/tree/master/docs/docs/databases) to make it more discoverable for other users.

Whoops, I didn't notice you already had a PR open for this, thanks! #22145 (updated the PR description to cross reference this PR)

**Comment by passren** [comment]
> > Thanks for this work @passren, awesome work! It would be nice if you could follow up by adding an entry to the [docs](https://github.com/apache/superset/tree/master/docs/docs/databases) to make it more discoverable for other users.
> 
> Whoops, I didn't notice you already had a PR open for this, thanks! #22145 (updated the PR description to cross reference this PR)

@villebro, my bad. I forgot to update the docs with this PR. So created the new PR to do that. Thanks for your caring. :D

**Pull request merged**
