### PR TITLE
forcing fixed width fonts on ace editor (fixes #9095)

### LINKED ISSUE #9095: SQL Lab editor cursor position is incorrect in Safari
When I type a SQL query in SQL Lab with the latest version of Safari Version 13.0.5 (15608.5.11), the cursor doesn't lineup with where I'm actually typing.

### Expected results

I expect the cursor to remain at the end of the line while I'm typing.

### Actual results

The cursor slowly starts to fall behind in Safari as I type.

#### Screenshots

A video of the issue may be watched at https://s3.amazonaws.com/bradgessler/Screen-Recording-2020-02-06-at-10.29.14-Z2v0KXdYZrAp.mov

#### How to reproduce the bug

1. Using the latest version of Safari, go to `/superset/sqllab`
2.Begin typing a query, keep typing at least 40 chars
3. Observe the cursor fall behind

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

This use to be an issue in Firefox and Chrome, but before submitting this bug I verified this is no longer a problem in those browsers.

### PR DESCRIPTION
**Pull request by rusackas**
### CATEGORY

Choose one

- [X] Bug Fix
- [ ] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY
Adds some CSS to force fixed width fonts onto the ace editor (sql editor) so Safari knows where to place the cursor. 

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

before ("SELECT" is kerned/tracked too far, cursor is too far inward
Screen Shot 2020-02-20 at 5 07 23 PM

after ("SELECT" is fixed-width, cursor is at the end of the text as expected)
Screen Shot 2020-02-20 at 5 06 55 PM

### ADDITIONAL INFORMATION

- [x] Has associated issue: Fixes #9095
- [x] Changes UI (barely... minor font tracking)
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by etr2460 — APPROVED** [review]
lgtm!

**Review by willbarrett — APPROVED** [review]
Nice! That looks easier than expected.

**Comment by lilila** [comment]
I still have the same problem. It used to be only on Safari but now I am experiencing the same issue with Chrome :/ .

**Comment by villebro** [comment]
@lilila which version are you on? AFAIK this bug is on `0.36.0rc1` but should be fixed on `master` and the upcoming `0.36.0rc2`.

**Comment by WenQiangW** [comment]
> @lilila which version are you on? AFAIK this bug is on `0.36.0rc1` but should be fixed on `master` and the upcoming `0.36.0rc2`.
I still have the same problem on `0.36.0rc1` with chrome ， 
fixed on `fixes #9095) #9183`? ,but  my file is same with this fixed file 
image

**Comment by bradgessler** [comment]
This doesn't fix the issue in 0.36.0. There's another CSS rule taking precedence (top) over these changes made by this patch (bottom):

Screen Shot 2020-05-05 at 10 39 53

The `font-family` attribute on the bottom should be the rule that is applied, but the `font` attribute from the `.ace_editor` class up top is taking precedence. When I disable the rule that's taking precedence, the editor works correctly.

**Comment by ksandvik** [comment]
Could this be fixed, thx?

**Comment by mapshen** [comment]
I am surprised that over one year later, I will still have to rely on your fix @bradgessler to get it working...

**Pull request merged**
