### PR TITLE
Ditching travis config in favor of Github Actions

### PR DESCRIPTION
**Pull request by craig-rueda**
### CATEGORY

Choose one

- [ ] Bug Fix
- [ ] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [x] Build / Development Environment
- [ ] Documentation

### SUMMARY
Disabling Travis in favor of GitHub Actions.

### CODE REVIEW

**Review by villebro — APPROVED** [review]
🔥

**Review by willbarrett — APPROVED** [review]

**Review by dpgaspar — APPROVED** [review]
kill it!

**Review by rusackas — APPROVED** [review]

**Comment by rusackas** [comment]
ding dong the witch is dead

**Comment by rusackas** [comment]
much rejoicing

**Comment by craig-rueda** [comment]
Thanks to @ktmud for doing most of the leg work here!!

**Pull request merged**
