### PR TITLE
fix: Database import error with a new field

### PR DESCRIPTION
**Pull request by codemaster08240328**
### SUMMARY
Updated V1 database extra schema to make import works with `allows_virtual_table_explore` field.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by yousoph** [comment]
This is looking good to me on the ephemeral env! 🎉

**Review by rusackas — APPROVED** [review]
LGTM!

**Pull request merged**
