### PR TITLE
chore: upgrade cypress to use retries

### PR DESCRIPTION
**Pull request by eschutho**
### SUMMARY
upgrades cypress to v 5.0 in order to use the new retries features. Also added back a known flaky offender to see if there's any improvement. 

### TEST PLAN
cypress tests pass, with potentially some retries. 

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by nytai — APPROVED** [review]
this is great and should help relieve some of the frustration with contributing

**Comment by eschutho** [comment]
retrigger FOSSA check.

**Comment by nytai** [comment]
@eschutho I think you just need to rebase your branch to include in the latest fixes. I don't think CI is configured to run with a merge strategy.

**Comment by mistercrunch** [comment]
`explore/AdhocFilters.test.ts` failed too, but I disabled that one on `master`, rebasing should fix that issue.

Personally I'd advise to also disable the whole `License` Github action as #10925 can re-enable it as it lands. 

We've been suffering from flaky test/broken build for too long now. I vote for disabling all that fails and start clean.

**Comment by eschutho** [comment]
rerunning checks

**Comment by eschutho** [comment]
rerun for FOSSA

**Comment by eschutho** [comment]
@mistercrunch I'll continue to keep an eye on any tests that are failing after this and see which need to be fixed or disabled.

**Pull request merged**
