### PR TITLE
ci: make presto hive tests to cover only chartData and sqljson

### LINKED ISSUE #17750: CI is extremely flaky when running Presto/Hive tests
These tests are the same ones that run against other analytics DBs, but for some reason when we run them against Presto/Hive we get false positives (or are they false negatives? 🤔) at a much greater rate. These tests also seem to take much longer to run, which may be related.

If we can get to the bottom of this it will massively improve the experience of contributing to Superset.

#### How to reproduce the bug

Run CI a few times.

### Expected results

CI should pass if the PR hasn't introduced any bugs.

### Actual results

It fails a lot. Often multiple times in a row, with different tests.

### Additional context

I want to start putting together a list of the tests that have failed, to see if there is some sort of pattern. Feel free to add new entries to this list (only if you are certain that it really is a false positive!). Please also link to a relevant line of the GitHub Action where the test failed.

- [ERROR tests/integration_tests/dashboards/filter_state/api_tests.py::test_delete_not_owner](https://github.com/apache/superset/runs/4524150250?check_suite_focus=true#step:8:2363)
- [ERROR tests/integration_tests/security_tests.py::TestRolePermission::test_admin_permissions](https://github.com/apache/superset/runs/4525283552?check_suite_focus=true#step:8:2420)

### PR DESCRIPTION
**Pull request by amitmiran137**
### SUMMARY
there have been a few attempts already to avoid the flakiness of the presto hive tests
in addition, we know that the original intention of that workflow was to test out the engine part of presto and hive
therefore we can just limit the tests the chart/data and sql_json API's which are executing the data querying part of superset

https://github.com/apache/superset/pull/17772
resolves https://github.com/apache/superset/issues/17750

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by amitmiran137** [comment]
Presto/Hive tests are running only 2 suites of tests now chartData nd sql_lab.
for some reason a single test is failing, can @apache/superset-committers

**Comment by etr2460** [comment]
are there database creation/api tests we should include here too?

**Comment by amitmiran137** [comment]
> are there database creation/api tests we should include here too?

Can you explain a bit why you think it is related?

**Comment by etr2460** [comment]
I wanted to make sure that any tests that might hit the presto/hive connectors get run here. For example, a test that adds custom configuration options to a database (and passes them on to the db engine). some examples of the configs:
image

there's also the db impersonation that i believe is unique on a db engine level. Ideally we would be testing all these config options on every db engine, but for now hive and presto is a start

**Comment by amitmiran137** [comment]
@etr2460  can you point the relevant tests that you want to be covered here?
we can easily **mark** them on the same technique 
you can even at the marks yourself and commit to this branch, but lets address this painpoint as soon as possible

**Review by etr2460 — APPROVED** [review]
i don't know the specific ones (not super familiar with the backend) so i'll stamp to unblock here. @bkyryliuk @villebro and @john-bodley would probably be the ones who know most about the backend to tag other tests. but this seems like a decent step (and could allow us to make these tests required for PRs too)

**Comment by amitmiran137** [comment]
Hive and presto bottle tests bottle neck shrink to 6-7 minutes  ✌️

**Comment by bkyryliuk** [comment]
> i don't know the specific ones (not super familiar with the backend) so i'll stamp to unblock here. @bkyryliuk @villebro and @john-bodley would probably be the ones who know most about the backend to tag other tests. but this seems like a decent step (and could allow us to make these tests required for PRs too)

just noticed the comment, I think we can enable presto / hive tests later on for the cases that are critical or if we will notice breakages.

**Pull request merged**
