### PR TITLE
test: Adds storybook to Dropdown and DropdownButton components

### PR DESCRIPTION
**Pull request by michael-s-molina**
### SUMMARY
- Breaks `Dropdown` component into `Dropdown` and `DropdownButton`
- Adds storybook to both components
- Moves both components to their own folders

### TEST PLAN
1 - Execute all tests.
2 - All tests should pass.

@rusackas @junlincc 

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by geido — COMMENTED** [review]
Hey, great one @michael-s-molina! Just one thought, should't we use this chance to move the component from the common directory to the main components directory?

**Comment by michael-s-molina** [comment]
> Hey, great one @michael-s-molina! Just one thought, should't we use this chance to move the component from the common directory to the main components directory?

@geido I was planning to do this after we organize all components in their own folder. Maybe in a single PR.

**Comment by geido** [comment]
> @geido I was planning to do this after we organize all components in their own folder. Maybe in a single PR.

I see. I think I prefer doing it bit by bit and that's the approach that I am following when I work on a component inside the common dir. Let's discuss this tomorrow.

**Review by geido — APPROVED** [review]

**Review by yardz — APPROVED** [review]

**Review by rusackas — APPROVED** [review]
LGTM!

**Comment by junlincc** [comment]
manually tested. lgtm

**Pull request merged**
