### PR TITLE
feat(python): add purge Event logger database

### PR DESCRIPTION
**Pull request by jplanckeel**
### SUMMARY
An example to add purge for Event Logger in Database, because today Logs tables is not purged and grow to infinity.

Is not perfect, ! :warning: warning this PR can slow down Superset Interface if you have a lot of element in logs table.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
image

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by jplanckeel** [comment]
After test we need an index on dttm column for table logs ;)

**Comment by aminvielledebatAtBedrock** [comment]
Ping @eschutho @geido please (i don't know if you are the good persons to ping, but we found nobody in the CODEOWNERS :'-(). 
Do you think this kind of purge could be a good idea ? 

If not, we will manage it in our own superset config code.

:pray:

**Review by dpgaspar — COMMENTED** [review]
Thank you for your contribution. I do agree that the log table should be prunned. I think this should be done on a beat async celery task

**Comment by aminvielledebatAtBedrock** [comment]
Ping @jplanckeel, do you think these changes could be done on our way ?

**Comment by jplanckeel** [comment]
Hello, prune log is already integrate ton superset ? https://github.com/apache/superset/blob/master/superset/tasks/scheduler.py#L99 

We need only configure scheduler in config.py ?

**Comment by jplanckeel** [comment]
i create a new PR with the new solution to prune logs table with celery task https://github.com/apache/superset/pull/21873/files

thank for your reponse ;)

**Comment by dpgaspar** [comment]
@jplanckeel closing this in favour of the new PR

**Pull request closed without merging**
