### PR TITLE
[Presto] Handle uncaught exception in get_create_view

### PR DESCRIPTION
**Pull request by etr2460**
### CATEGORY

Choose one

- [x] Bug Fix
- [ ] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY

Resolves a bug introduced in https://github.com/apache/incubator-superset/pull/8213 where calling `get_extra_metadata` would result in a 5xx because of an uncaught exception. To fix, i've moved the query execute and all the polling inside the try/except block.

### TEST PLAN

select a presto table in sql lab, see the metadata (like latest partition) load successfully

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### REVIEWERS
@betodealmeida @john-bodley @graceguo-supercat @villebro

### CODE REVIEW

**Review by villebro — COMMENTED** [review]
Moving `execute` and entourage inside `try-catch` makes sense and LGTM. However, while we're at it.. I know this is slightly out of scope for this PR, but I assume the exceptions being thrown from `cursor.poll()` and `cls.execute()` can be made more specific? I checked the source for `PyHive`, and `poll()`raises `ProgrammingError` when there is "no query yet" (https://github.com/dropbox/PyHive/blob/master/pyhive/hive.py#L408), which I assume is what the original PR was catching. So I'm guessing the exception causing the 500 from `execute` is something else. To avoid catching something that shouldn't be caught here, it would probably be good to be more specific with the exact exception being thrown, and how those are handled.

**Comment by john-bodley** [comment]
I agree with @villebro. We currently have `pylint` warnings disabled on a per file basis (we should go through and systematically remove these) as `pylint` would complain about catching a broad exception here.

**Comment by etr2460** [comment]
I agree that this isn't an ideal solution, but @betodealmeida is really the one with context here. I'll let him chime in on what he was trying to catch with the `Exception` and then update the PR accordingly

**Comment by etr2460** [comment]
@villebro and @john-bodley I've addressed comments

**Review by john-bodley — APPROVED** [review]

**Review by villebro — APPROVED** [review]

**Pull request merged**
