### PR TITLE
Fix the bug of chord diagram shows incorrect flow from target to source

### PR DESCRIPTION
**Pull request by liutgnu**
The original bug report is (#3342)

### CODE REVIEW

**Comment by mistercrunch** [comment]
Mmmh. We probably need a database migration script to flip things up in people's charts.

**Comment by liutgnu** [comment]
@mistercrunch Thanks for your comment. I believe the script should do more than just flip one's charts in silence, user should be notified before any flip and can determine whether a chart should be processed. My concern is, whether it's really necessary to introduce such a script since it may cause more complexity or we can just notify the users to update their charts manually.

**Comment by mistercrunch** [comment]
I think it's ok to flip the chart metadata along with flipping the behavior. The chart should just stay the same, and the logic aligned.

**Comment by octaviancorlade** [comment]
Maybe I misunderstood what would be "flipped", but flipping the `source` and `target` in a chord chart will actually change what the chart is displaying unless the matrix that it represents has the same sums by columns and by rows.

For instance, in a chart to visualize the number of passengers flying between different airports, the total number of people leaving from airport A does not (always) equal the total number of people flying from all the other airports to airport A.

**Pull request closed without merging**
