### PR TITLE
chore: Enhance Omnibar

### PR DESCRIPTION
**Pull request by geido**
### SUMMARY
This PR:

- Makes the Omnibar appear on the Dashboards' list with _cmd + k_ or _ctrl + k_
- Clears up the search when the Omnibar is closed
- Disables autocomplete
- Closes the Omnibar when clicking outside

https://user-images.githubusercontent.com/60598000/129581716-efc4100b-2156-4db6-bac6-1a9e68d25c2c.mp4

### TESTING INSTRUCTIONS
1. Open the dashboards' list
2. Press _cmd + k_ or _ctrl + k_ on your keyboard
3. Search for dashboards and move with the arrows through the results
4. Close the Omnibar by pressing ESC
5. Reopen the modal and observe that the latest search input and options are gone

### ADDITIONAL INFORMATION

- [x] Has associated issue: #16198 
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by michael-s-molina** [comment]
The arrow navigation is conflicting with the mouse hover. In this example, I hovered an element with the mouse (dark gray) and then navigate to another option using the arrow keys (light gray). When I pressed Enter the mouse hovered option was selected.

https://user-images.githubusercontent.com/70410625/129615418-15ff5dd0-0943-4c43-b9d0-3cd85e40bf5b.mov

**Comment by geido** [comment]
@michael-s-molina to be honest that looks like an edge case. I will check whether there is even a solution for that. However, this problem not related to my changes.

**Comment by michael-s-molina** [comment]
> However, this problem not related to my changes so I would get these changes merged in first if there isn't any problem related to the PR itself.

@geido I think we can improve the criteria to split the PRs. I completely understand that sometimes we have reviews that suggest new features or completely different matters to the PR's intentions. On the other hand, we want to avoid a bureaucratic process where all that matters is the changed lines and the context is irrelevant. In my comment above, if you have caught that problem during your tests you probably would have added the fix in this PR, so to me, it belongs to the same context. We can do it in a separate PR but the fragmentation of the context is also something we need to consider when deciding if we should split the PRs. Getting the changes merged should be balanced with the overhead of filling new issues, collecting screenshots, and reloading the context in a follow-up review.

**Comment by geido** [comment]
Hello @michael-s-molina . I totally agree with your comment. However, this doesn't appear to be such a case. It is clearly an edge case, definitely unrelated to the intent of my PR and shouldn't be blocking the priority items that are instead intended in this PR. If you would like to work on that case, please feel free to do so. Thank you

**Comment by geido** [comment]
@michael-s-molina I totally agree with your point. We shouldn't be bureaucratic and lose the context. I didn't want to convey that with my response. For this issue specifically, I was considering what you have reported as an edge case and I didn't it think would be a problem tackling it separately. 

I had a look anyway and found out that the Omnibar plugin that we are using comes with several limitations. I couldn't find a working solution so far, other than rendering the dropdown as a custom component.

I have suggested before to go for a full refactor of this component and just build our own Omnibar. This would be much faster than tackling each case individually and would give us much more freedom.

I advocate that we take that direction and I'll happy to take that work on me.

**Comment by michael-s-molina** [comment]
> I have suggested before to go for a full refactor of this component and just build our own Omnibar. This would be much faster than tackling each case individually and would give us much more freedom.
>
> I advocate that we take that direction and I'll be happy to take that work on myself.

@geido Agreed. Thanks for the explanation!

**Review by michael-s-molina — APPROVED** [review]

**Review by pkdotson — APPROVED** [review]
LGTM! I agree with you guys about the refactor of this component somewhere down the road. But I think this solution works for now.

**Pull request merged**
