### PR TITLE
feat(sqllab): Add keyboard shortcut helper

### PR DESCRIPTION
**Pull request by justinpark**
### SUMMARY
This commit adds keyboard shortcut helper button to display keyboard shortcut list.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

https://github.com/apache/superset/assets/1392866/59b5789e-72de-4914-9138-760ee099b052

### TESTING INSTRUCTIONS
Go to SQL Lab and click shortcut button

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [ ] Required feature flags:
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by justinpark** [comment]
@kasiazjc could you help the design review?

**Comment by eschutho** [comment]
@justinpark This is really cool!

**Comment by yousoph** [comment]
Not sure if this is due to this PR or not, but when I first go to SQL Lab on the ephemeral, the tabs don't load: 
image

After refreshing it works fine... 🤔

**Comment by kasiazjc** [comment]
@justinpark thank you for working on this, definitely a needed feature! I have a few suggestions:

- I would switch the columns on action and shortcut - it is easier to scan the text and look for keywords that way, and we do not have to worry about truncation if there are more than 2 shortcuts 
image
 - I changed shortcut fontsize to 12px - 14px seemed to be overly cluttering the modal 
 - I think this feature is not needed to be available at all times - people will probably quickly learn shortcuts and only open the modal to refresh the memory, so I would suggest moving it to the "..." dropdown with autocomplete, as this bar has a bunch of buttons already 

What do you think?

**Comment by justinpark** [comment]
> * I would switch the columns on action and shortcut - it is easier to scan the text and look for keywords that way, and we do not have to worry about truncation if there are more than 2 shortcuts
> 
> image
> * I changed shortcut fontsize to 12px - 14px seemed to be overly cluttering the modal
> * I think this feature is not needed to be available at all times - people will probably quickly learn shortcuts and only open the modal to refresh the memory, so I would suggest moving it to the "..." dropdown with autocomplete, as this bar has a bunch of buttons already
> 
> What do you think?

@kasiazjc Thanks for the suggestion! I made the layout change and menu location as you suggested.
Screenshot 2023-10-11 at 10 39 04 AM

Screenshot 2023-10-11 at 9 14 29 AM

**Comment by justinpark** [comment]
> Not sure if this is due to this PR or not, but when I first go to SQL Lab on the ephemeral, the tabs don't load:

I don't find the issue.
I believe that's caused by the previous ephemeral cache.
Please re-create ephemeral test environment and test again if you concern about it.

**Comment by kasiazjc** [comment]
> > * I would switch the columns on action and shortcut - it is easier to scan the text and look for keywords that way, and we do not have to worry about truncation if there are more than 2 shortcuts
> > 
> > image
> > * I changed shortcut fontsize to 12px - 14px seemed to be overly cluttering the modal
> > * I think this feature is not needed to be available at all times - people will probably quickly learn shortcuts and only open the modal to refresh the memory, so I would suggest moving it to the "..." dropdown with autocomplete, as this bar has a bunch of buttons already
> > What do you think?
> 
> @kasiazjc Thanks for the suggestion! I made the layout change and menu location as you suggested. Screenshot 2023-10-11 at 10 39 04 AM
> 
> Screenshot 2023-10-11 at 9 14 29 AM

Thank you for the quick changes, this looks great!

**Review by kasiazjc — APPROVED** [review]
design LGTM

**Review by eschutho — APPROVED** [review]

**Pull request merged**
