### PR TITLE
chore: Help user to find the input fields in the dataset editor

### PR DESCRIPTION
**Pull request by lyndsiWilliams**
### SUMMARY

The following editable text areas are now more intuitive to their editable functionality:
- The "Label" and "SQL expression" columns in the Metrics tab
- The "Column" column in the Columns tab

I changed the `EditableTitle` components into `TextControl`/`TextAreaControl` components where applicable. This leaves the input box borders showing at all times instead of just when the user clicks the area.

#### BEFORE:
- Metrics tab 
  metricsTabBefore
- Columns tab
  columnsTabBefore

#### AFTER:
- Metrics tab
  metricsTabAfter
- Columns tab
  verticallyAlignedRows

### TESTING INSTRUCTIONS

- Observe the described changes in the Edit Dataset model under the "Metrics" and "Columns" tabs.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by betodealmeida — APPROVED** [review]
So much better!

**Comment by eschutho** [comment]
Looks great @lyndsiWilliams. Let's see if @yousoph or a designer have any feedback. Things look a little top aligned on the columns screen, but then the trashcan looks middle aligned for example, now that the row is deeper.

**Comment by lyndsiWilliams** [comment]
> Looks great @lyndsiWilliams. Let's see if @yousoph or a designer have any feedback. Things look a little top aligned on the columns screen, but then the trashcan looks middle aligned for example, now that the row is deeper.

Good call and I agree, maybe the "Sync columns from source" button can be moved to the bottom with the rest of the buttons to fix this? Although I'm not sure if it's important to keep that button at the top.

**Comment by jess-dillard** [comment]
@lyndsiWilliams Agree with @eschutho, let's vertically center align all the row elements. I think the "Sync columns from source" button should stay at the top, though, as there's already a lot of buttons at the bottom and will make it harder for the users to scan.

**Comment by lyndsiWilliams** [comment]
@jess-dillard @eschutho Great feedback, thank you! I've vertically aligned the rows in the columns tab in [`this commit`](https://github.com/apache/superset/pull/17824/commits/d9a2fad01fce0b200724ae7e2f68126bbb52e449). Here's a screenshot of the updated styling, which I've also added to the PR's summary.
verticallyAlignedRows

**Pull request merged**
