### PR TITLE
chore(dashboard): Remove DRILL_TO_DETAIL feature flag

### PR DESCRIPTION
**Pull request by codyml**
### SUMMARY

This PR removes the `DRILL_TO_DETAIL` feature flag, as this feature is no longer in development.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

Before (w/o feature flag):
Screen Shot 2022-10-20 at 5 45 34 PM

After (w/o feature flag):
Screen Shot 2022-10-20 at 5 42 12 PM

### TESTING INSTRUCTIONS

- Without the feature flag on, make sure the Drill to Detail contextual menu and chart header dropdown menus appear on dashboards.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by geido — APPROVED** [review]

**Review by michael-s-molina — APPROVED** [review]
LGTM

**Comment by codyml** [comment]
@kasiazjc

**Comment by kasiazjc** [comment]
thanks for the env @michael-s-molina 🙏 

I found a few things to check/fix: 
- there is gray overlay under the modal missing (that we do for example for visualization modal in Explore) - I only just noticed that it is also the case for view as a table, can we add it? Dashboard is pretty overwhelming and  because of that it's hard to focus on the modal
- in the table, when I scroll down on one page, and go to the next one the scroll position is retained - it should go to the top instead
- in the table, when I go to another page, for a few seconds I cannot scroll it as it’s frozen and the scroll bar on the right does not show up, after a few seconds it starts working again

**Comment by michael-s-molina** [comment]
> in the table, when I go to another page, for a few seconds I cannot scroll it as it’s frozen and the scroll bar on the right does not show up, after a few seconds it starts working again

This one might be tricky. I think this is caused by tables with many columns which would require horizontal virtualization. If that's the case, then we'll be able to fix it in the future with the work @eric-briscoe is doing with the table component.

**Comment by codyml** [comment]
Thanks @kasiazjc, was able to reproduce these issues and @michael-s-molina that makes sense about the table element.  Since these don't sound blocking let's try to fix them in future PRs, and @jinghua-qa feel free to go ahead with QA testing on this PR as-is.  Thanks!

**Comment by jinghua-qa** [comment]
/testenv up FEATURE_DRILL_TO_DETAIL=true DASHBOARD_CROSS_FILTERS=true

**Comment by jinghua-qa** [comment]
I found some issue:
1,  drill to details by is block by the tooltip when chart width is small
 step 1, go to slack dashboard
 step 2, right click for Weekly Threads on date
Expected results
user can open drill to details by

Actual results
drill to details by is block by the tool tip

https://user-images.githubusercontent.com/81597121/199626216-d011bc34-5267-4b5d-84ad-0f59ac2e7d87.mov

2, Drill to details by time dimension show filter error in time series bar chart
step 1, go to video games sales dashboard
step 2, right click on a data in the Rise & Fall of Video Game Consoles time series area chart in a line
step 3, open drill to details by {time dimension}

Expected results
show data table with {time dimension}

Actual results
show filter error

https://user-images.githubusercontent.com/81597121/199626543-fc0b7ab1-4aca-474e-9608-786979dc5307.mov

3, [D2D] pivot table drill to details by time dimension return no row
Repro steps
step 1, go to birth name dashboard and open Pivot Table v2
step 2, in explore, change the row to be time column ds
step 3, save the chart in dashboard
step 4, open drill to details by time dimension in dashboard

Expected results
open data details with time dimension

Actual results
return no row

https://user-images.githubusercontent.com/81597121/199626656-ffc4fa90-0221-44bb-8634-a0d37492f37b.mov

4, drill to details by country return no row for world map
Repro steps
step 1, go to world bank's data dashboard
step 2, go to china and right click, open drill to details by china

Expected results
open detail data with clearable filter china

Actual results
return no row
Screen Shot 2022-11-02 at 5 33 18 PM

**Comment by michael-s-molina** [comment]
/testenv up FEATURE_DASHBOARD_CROSS_FILTERS=true FEATURE_DRILL_TO_DETAIL=true

**Comment by codyml** [comment]
Closing as we're actually going to leave the FFs in for now.

**Pull request closed without merging**
