### PR TITLE
feat(Explore): Viz gallery component tweaks

### PR DESCRIPTION
**Pull request by suddjian**
### SUMMARY

- Separates the viz gallery code from the explore control/modal code
- Tweaks to thumbnail layout: use grid to set space-between and remove strange tall thumbnail containers
- Sort categories (alphabetically + "Other" at the end)
- Instead of showing the modal on the Add Slice page, show the contents of the viz gallery directly (Explore still uses the modal)
- Fixed a minor bug where after clicking the X, you'd be stuck in a category. The search box would still be focused and you could type in it but it wouldn't search.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

On the Add Slice page
Screen Shot 2021-07-01 at 4 47 44 PM

The viz type control in Explore
Screen Shot 2021-07-01 at 4 48 11 PM

### TESTING INSTRUCTIONS

1. Go to Add Slice
2. Go to Explore and change the slice
3. Search, hit the X, and type again

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by michael-s-molina** [comment]
@suddjian Some suggestions:

- Increase the padding of the left panel
- Make the top and bottom padding of the right panel the same as the left and right ones
- Decrease the width of the "Choose a dataset select"
- Change the search behavior as described in https://github.com/apache/superset/pull/15399

**Comment by junlincc** [comment]
Thanks @suddjian for the amazing work!! 
@michael-s-molina We may need your help to take over the remaining UI tweaks from this project later on ;)  we can work on the padding and positioning etc together!

**Comment by mihir174** [comment]
@suddjian this looks awesome! i have a few design questions-
- are the description and the examples are each 50% of the modal?
- what's the interaction for seeing more examples in that section? is it a carousel?
- are the examples images or links to actual charts?

**Comment by suddjian** [comment]
@mihir174 I recommend using the ephemeral environment to check out the behaviors

- Yes, 50%
- The examples list scrolls sideways. We had planned to use a carousel and/or "click to expand" functions, both of which are available in AntD, but we'll need to do some work to upgrade AntD before those will work properly. Decided to go with the simple option for now.
- It's just plain images, though you can right click to open an image in a new tab.

**Comment by mihir174** [comment]
> @mihir174 I recommend using the ephemeral environment to check out the behaviors
> 
> * Yes, 50%
> * The examples list scrolls sideways. We had planned to use a carousel and/or "click to expand" functions, both of which are available in AntD, but we'll need to do some work to upgrade AntD before those will work properly. Decided to go with the simple option for now.
> * It's just plain images, though you can right click to open an image in a new tab.

Ok awesome, my initial reaction is that the carousel looks oddly placed when there's no description/ a short description. Another question - what's the default state of the description + examples section when no selection has been made?

**Comment by suddjian** [comment]
It opens to the initially selected chart. In the New Chart page, the default is the Table, same as before.

**Review by pkdotson — APPROVED** [review]

**Comment by pkdotson** [comment]
code looks good to me!

**Pull request merged**
