### PR TITLE
feat(Select): [cosmetic] support allowTopOptions for select component

### PR DESCRIPTION
**Pull request by stephenLYZ**
### SUMMARY

Currently,  the select component will place the selected option in front of the dropdown options by default, which is a convenient interaction. However, in some scenarios, the user may not want to do this( https://github.com/apache/superset/issues/15972), so we can add an option to control this behavior.

### before
image

### after
image

### ADDITIONAL INFORMATION

- [x] Has associated issue: https://github.com/apache/superset/issues/15972
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by michael-s-molina** [comment]
@stephenLYZ @jinghua-qa One of the core requirements during the Select development was to standardize the behavior throughout the application. The previous component had so many configuration options that it seemed that we had a bunch of different selects throughout the application. Every time the user interacted with it the behavior was different. Having said that, I wonder what's @jess-dillard and @rusackas opinion on this particular requirement.

**Comment by stephenLYZ** [comment]
@michael-s-molina @geido Thanks for the explanations! I also
agree keeping the behavior consistent. btw, I am curious  why single-select component would keep selected option on top. It is a bit different from other site. Maybe scroll to selected option could be better? Since after each selection of value will lead to the reorder of the list, if the list is very large there maybe some performance issues.

**Comment by michael-s-molina** [comment]
> @michael-s-molina @geido Thanks for the explanations! I also agree keeping the behavior consistent. btw, I am curious why single-select component would keep selected option on top. It is a bit different from other site. Maybe scroll to selected option could be better? Since after each selection of value will lead to the reorder of the list, if the list is very large there maybe some performance issues.

We chose to keep the select option on top to preserve the same behavior between the different types but also because the component is paginated, which means that all the results won't be available at a given point. Imagine a Select with the names of people and when you open it, only the names that start with A are available but the selected value is Sarah. In terms of performance, the virtualization and pagination helps, we tested with more than 100k values and saw no problem.

**Comment by jess-dillard** [comment]
@stephenLYZ I agree with @michael-s-molina and @geido that we should keep the pattern consistent throughout the application. Michael's pagination use case makes sense as a reason to keep the current behavior (selected values appear first in the dropdown list). @stephenLYZ, I am curious what use cases you have in mind to support why this might not be the best behavior.

**Comment by rusackas** [comment]
Thanks for the PR @stephenLYZ. It does solve the issue reported. However, in the end, I agree with the general consensus of the thread: consistency is king. While the use case cited in the bug report does NOT require pagination, and I can see the reasoning for keeping the selected value in-place in that use case, I still tend to agree that we should not have different behaviors of Select components in the application. If we change our minds later, we can re-open this PR and rekindle this project (also adding it to Storybook if we do). In the meantime, I think we can close this. I think we can also close the original issue, but I'll take that up on that thread separately.

**Comment by stephenLYZ** [comment]
@rusackas Yeah. I think that makes sense. So let me close it.

**Pull request closed without merging**
