### PR TITLE
Allow MetricsControl to aggregate on a column with an expression

### PR DESCRIPTION
**Pull request by michellethomas**
In the new MetricsControl, selecting a column with an expression would fail because it's just using the column name which doesn't exist in the underlying table (only in our metadata). This would add the expression (if there is one) inside the aggregation.

@john-bodley @GabeLoins @mistercrunch

### CODE REVIEW

**Comment by GabeLoins** [comment]
@michellethomas do we need to do something like this for druid as well?

**Comment by michellethomas** [comment]
I'm not totally sure if you can use a dimension spec (column expression) within a postagg in druid. When I looked through the druid metrics code I didn't see anywhere we were using DruidColumn expression or dimension_spec properties, so it doesn't look like we are doing this now. But I'm not totally sure.

Maybe John or Max know?

**Comment by mistercrunch** [comment]
I'm not 100% but I'm pretty sure Druid postaggs have to be made out of metrics.

Your PR LGTM, I'd be great to have a unit test that was failing before and succeeding now. For example we could have a new expression in the "births" dataset that would be called `first_letter` as `substr(name, 1, 1)` and do a count distinct of that or something.

**Comment by michellethomas** [comment]
@mistercrunch I didn't see a lot of tests for this section of the code. Did you have thoughts on where to add tests for this (viz_tests maybe?)?

**Comment by mistercrunch** [comment]
All examples get executed as integration test, so if you add a new example chart that cover this use case it should fail before your PR, succeed after

**Comment by michellethomas** [comment]
@mistercrunch added tests, thanks for the suggestion!

**Comment by mistercrunch** [comment]
LGTM

**Comment by john-bodley** [comment]
Note I believe this only supports one level of indirection, i.e., I'm not certain whether one can create another dimension which leverages `num_california` in your example.

**Comment by john-bodley** [comment]
@mistercrunch what are your thoughts about having metrics reference other metrics, or should metric expressions be valid SQL?

**Comment by mistercrunch** [comment]
Valid SQL was always the assumption, for simplicity and clarity. `MetricsControl` kind of changes the model a bit though as one might expect to see computed dimensions in there. I don't think people would expect to see `MetricsControl`-generated metrics inside the dropdown though.

**Pull request merged**
