### PR TITLE
chore: Auto focus the viz gallery select

### LINKED ISSUE #16008: [gallery]highlight "Select a dataset" to indicate field is required
even after interacting with the new viz gallery many times, I still hopeless find myself keep missing the first step of selecting a dataset when creating a new chart. compared to the left panel and the main viz area, "Choose a dataset" takes up very little space and is located in a less prominent area. 
User, namely me, had to go back to the dropdown after selecting a viz and trying to click "CREATE NEW CHART" but find the button is disabled. 

Screen Shot 2021-08-01 at 3 41 29 PM

One thing we can do, by looking at other BI tools, is to highlight this area or to provide some sort of visual indicator to grab users' attention when they first land on the modal. feel free to be creative but make sure to take in product consistency as consideration.  @michael-s-molina 🙏
 
Screen Shot 2021-08-01 at 3 41 40 PM

### PR DESCRIPTION
**Pull request by michael-s-molina**
### SUMMARY
Fixes https://github.com/apache/superset/issues/16008

@junlincc @rusackas @jinghua-qa

### AFTER SCREENSHOTS OR ANIMATED GIF
https://user-images.githubusercontent.com/70410625/127892207-f97ac7ea-5344-4003-a008-7662d0343aab.mov

### TESTING INSTRUCTIONS
See the original issue for instructions.

### ADDITIONAL INFORMATION
- [x] Has associated issue:
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by geido — APPROVED** [review]
LGTM!

**Review by pkdotson — APPROVED** [review]
LGTM!

**Review by junlincc — APPROVED** [review]
Product sign-off! thanks!!

**Pull request merged**
