### PR TITLE
fix: Updates the selected values when changing the native filter type, column or default value

### LINKED ISSUE #16813: [Native Filter] change filter column did not update the column value on dashboard
After change the filter column to another, i still see the old values of the old filter, and also when one of the filter changed, my other filter got clear.

### Expected results
1. After one of the filters is being edited by column change, previous selected filter values on dashboard should be cleared. 
2. Selected filter values on dashboard of the unchanged filter(s) should remain the same. 

### Actual results

1, when change to new column, that filter value also did not update - opposite of expected result
2, other filter got clear - opposite of expected result 

#### Screenshots

https://user-images.githubusercontent.com/81597121/134547600-8c6a386b-c328-4c07-9aaf-fbe7d842ad07.mov

#### How to reproduce the bug

1.  Create at least 2 native filter and select some value to apply
2. Edit one of the filters by changing the column 
3. Save and go back to the dashboard

### Environment

(please complete the following information):

- browser type and version:
- superset version:  2021.38.1 
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by michael-s-molina**
### SUMMARY
Fixes https://github.com/apache/superset/issues/16813

@junlincc @jinghua-qa

### AFTER VIDEO
https://user-images.githubusercontent.com/70410625/134696888-b54cc158-c7ba-41ca-aee5-da86c6bf4778.mov

### TESTING INSTRUCTIONS
Check the original issue for instructions.

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by geido — APPROVED** [review]
LGTM! Thanks for the fix!

**Review by jinghua-qa — APPROVED** [review]
LGTM!

**Comment by sadpandajoe** [comment]
🏷️ 2021.38

**Pull request merged**
