### PR TITLE
test: rename column names for birth_names dataset

### PR DESCRIPTION
**Pull request by ktmud**
### SUMMARY

Rename `sum_girls` to `num_girls` and `sum_boys` to `num_boys` in the example `birth_names` dataset as they are kind of confusing when used in combination with adhoc metrics.

Snip20201216_4

Must wait for: https://github.com/apache-superset/examples-data/pull/7

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

N/A

### TEST PLAN

CI and local visual verification

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by junlincc** [comment]
thanks for making the change. 
for transparency -  mihir and i had some confusion while auditing the table viz control panel by mistaken `sum_girls` as a aggregated field.

**Review by junlincc — APPROVED** [review]
LGTM! Thank you ktmud! 
Screen Shot 2021-01-08 at 2 09 56 PM

fyi: @adam-stasiak you may wanna update test cases accordingly

**Comment by robdiciuccio** [comment]
Looks like this introduced a regression with example dashboards. @junlincc let's ensure PRs are code reviewed before being approved.

**Comment by ktmud** [comment]
I wouldn't categorize this as a regression, at most an inconvenience for developers. I personally would nuke examples database all the time whenever a new example dashboard is added.

We were aware of the risk of breaking the example dashboard, but decided to take the risk. It would be a little weird to write a db migration or anything special processing just for this when most production deployments wouldn't load the examples to begin with. 

Maybe better documentation next time.

**Comment by junlincc** [comment]
@robdiciuccio i don't consider this as a regression neither, it's an improvement. As I added in the comment, those column names are not clear which mislead users to read the chart.  And i actually did the code review as well, I understood all the changes in 11 files.

**Comment by robdiciuccio** [comment]
Definitely seems worthy of a mention in UPDATING.md at the very least, as use cases for example dashboards are clearly different for different organizations.

**Comment by junlincc** [comment]
sure. 
i also suggest an organization to read through PR's description and details to understand the changes and risks, before merging a PR into their fork.

**Pull request merged**
