### PR TITLE
test: Added some Cypress tests for Native Filters

### PR DESCRIPTION
**Pull request by adam-stasiak**
### SUMMARY

I added pack of tests for native filters feature.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by adam-stasiak** [comment]
@villebro I added step for adding new dashboard before suite.

**Review by villebro — APPROVED** [review]
This is great work @adam-stasiak ! Code looks good and test cases comprehensive.

**Review by pkdotson — APPROVED** [review]
LGTM once you fixed merge conflicts!

**Comment by junlincc** [comment]
@adam-stasiak would you mind fixing the test and get this PR through as your final task, thanks? 🙏

**Comment by junlincc** [comment]
thank you @adam-stasiak, for pushing it through the finish line and all your great work!

**Pull request merged**
