### PR TITLE
fix: Ignore database extra fields when saving

### PR DESCRIPTION
**Pull request by michael-s-molina**
### SUMMARY
Ignore database extra fields when saving. This is a fix for a regression that prevented the saving of databases or the creation of new ones. The client is sending more data than it should, and this fix ignores this extra data for now. We should definitely fix the client side to send only the necessary information to the API.

@eschutho I know that you are working on this modal. Can you make this modification? After that, you can undo this hotfix.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Screen Shot 2021-05-04 at 9 55 53 AM

@rusackas @villebro @dpgaspar @junlincc @eschutho 

### TEST PLAN
1 - Execute all tests
2 - All tests should pass

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by dpgaspar — APPROVED** [review]
Looks good to me has a quick fix. We should eventually fix the database modal so that it does not send the `allows_*` extra fields to the backend.

**Review by villebro — APPROVED** [review]
Thanks for investigating and fixing this @michael-s-molina! I agree with Daniel, let's get this in asap but aim to do a more proper follow-up once the dust settles.

**Comment by villebro** [comment]
FYI @eschutho I checked that this was working prior to #14436 and broke after that one, so there appears to have been something in the refactor that introduced this.

**Comment by eschutho** [comment]
Thank you for catching @michael-s-molina. We also reverted the PR and here's the fix: https://github.com/apache/superset/pull/14470

**Pull request merged**
