### PR TITLE
update SqlaTable model to reflect actual table unique constraint

### LINKED ISSUE #8316: Include schema on sqlatable's unique constraint
On a project that I'm working on we have different schemas on the same database (postgres) and all schemas have the same ddl. 
Since the SqlaTable model has a unique constrain on the fields "database_id" and "table_name" we can't import the tables.

The solution would be to add the "schema" field to the existing unique constraint of the SqlaTable model.
To prevent having several tables with the same name and database on the list endpoint of the tablemodelview I would also add the schema to the list_columns

### PR DESCRIPTION
**Pull request by nytai**
### CATEGORY

Choose one

- [ ] Bug Fix
- [x] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY

Small PR to better reflect what was introduced with this migration: https://github.com/preset-io/incubator-superset/blob/master/superset/migrations/versions/b4456560d4f3_change_table_unique_constraint.py

### TEST PLAN

- Table creation works (with unique names and same names, but different schemas)

### ADDITIONAL INFORMATION

- [x] Has associated issue: Fixes #8316 
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by etr2460 — APPROVED** [review]
makes sense to me, thanks for cleaning this up!

**Comment by mistercrunch** [comment]
Also makes sense to me, but there may be intricacies (?) @john-bodley FYI

**Review by john-bodley — CHANGES_REQUESTED** [review]
Sorry this wont work for a number of reasons. See https://github.com/apache/incubator-superset/pull/5449 for details. 

The TL;DR is i) a migration is required and the unique key length exceeds the MySQL maximum, and ii) the schema can be NULL though different dialects handle NULL values differently and uniqueness from our perspective a unique (schema, table) tuple is not always guaranteed.

**Comment by craig-rueda** [comment]
Closing for now, as per @john-bodley

**Pull request closed without merging**
