### PR TITLE
fix(chart): scrollbar keep flusing on and off

### PR DESCRIPTION
**Pull request by justinpark**
### SUMMARY

This bug introduced by #20282 
After resize target element has scrollbars, the chart keeps flushing scrollbars on and oft.
It because keeps re-calculate the element's size due to the content size is different with/without scrollbars.

This commit replaces the resize observe element with the parent element (which has no scrollbars) and then calculate the chartPanel element from onResize handler.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

After:

https://user-images.githubusercontent.com/1392866/233742823-90c0ec40-997f-4341-8560-40a7e7ff68fe.mov

Before:

https://user-images.githubusercontent.com/1392866/233742847-88d0bb9c-4abd-4334-8303-6c8c014e7ffd.mov

### TESTING INSTRUCTIONS
Open a chart explore
Resize window width smaller
check the chart scroll

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by rusackas — APPROVED** [review]
Awesome! This might actually close out a lot of GitHub Issues if we're lucky! THANK YOU!

**Comment by michael-s-molina** [comment]
I fixed the Frontend CI error [here](https://github.com/apache/superset/pull/23784/files#diff-73c6424e4e29bec177cd5c97f785865635844097ab9a2a1e2f94408f6a2cdeec).

**Comment by justinpark** [comment]
> I fixed the Frontend CI error [here](https://github.com/apache/superset/pull/23784/files#diff-73c6424e4e29bec177cd5c97f785865635844097ab9a2a1e2f94408f6a2cdeec).

@michael-s-molina the CI error came from [here](https://github.com/apache/superset/pull/23778/files#diff-58ba2786e06a5568043a6f7c00d255688791e3c7265a485aed8576cb1d094559L81) and I already fixed with replacing mock.

**Review by michael-s-molina — APPROVED** [review]
LGTM

**Comment by eschutho** [comment]
Hi @justinpark we're seeing some regression with this ticket when running reports, or viewing a chart in standalone mode. Do you have time to put up a quick fix for this issue?

**Pull request merged**
