### PR TITLE
fix: Revert #10970 to fix filter_box edit control

### LINKED ISSUE #11047: PR #10970 breaks the filter box control
When you pull  #10970 and run `docker-compose up --build` and go to Filter Box visualization in the control panel, the filter configuration popup will not open.

### Expected results

Filter configuration popup to open.

### Actual results

Filter configuration popup does not open.

#### Screenshots

image

#### How to reproduce the bug

1. Clone incubator-superset
2. `git reset --hard e4e78b66fa82acbe8e5bc425d697ff11b4a0cc3f`
3. `docker-compose up --build`
4. Wait for the `superset_init` to complete
5. Open http://localhost:8088
6. Go to data > datasets > birth_names
7. Change the visualization type to filter box
8. Under Filters configuration, click (+) icon to add a filter
9. Try to edit the filter
10. See browser console producing 

### Environment

(please complete the following information):

- superset version: `e4e78b66fa82acbe8e5bc425d697ff11b4a0cc3f`
- python version: `Python 2.7.17`
- node.js version: `v12.18.3`
- npm version: `6.14.6`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

The filter box plugin works with the previous commit to master 41dfcd4834cb0db76d8aeffb28f55b90d79dccd6

### PR DESCRIPTION
**Pull request by graceguo-supercat**
This PR is to reverts apache/incubator-superset#10970 to fix the edit control in filter_box.
please see [issue reported here](https://github.com/apache/incubator-superset/issues/11047).

cc @etr2460 @zuzana-vej @mistercrunch

### CODE REVIEW

**Review by nytai — APPROVED** [review]

**Review by etr2460 — APPROVED** [review]

**Comment by graceguo-supercat** [comment]
Thanks for everyone's quick response!

**Comment by mistercrunch** [comment]
Apologies as the person who broke this.

@rusackas any idea why emotion's `<ThemeProvider>` doesn't provide all the way down the tree into that `Popover` component?

**Comment by rusackas** [comment]
> Apologies as the person who broke this.
> 
> @rusackas any idea why emotion's `<ThemeProvider>` doesn't provide all the way down the tree into that `Popover` component? I really want to prevent this from happening again...

I haven't figured it out 100% yet, but the appearance to me is that `<Popover>` uses some Jquery-ish DOM manipulation to tack the actual popover elements directly onto the `<body>` tag, and it's effectively outside the scope of React's jurisdiction. I've fixed it in numerous other cases by adding a `<ThemeProvider>` component within the `<Popover>`. For example `AdhocFilterEditPopover` includes:
```
<Popover id="filter-edit-popover" {...popoverProps}>
        <ThemeProvider theme={theme}>
          <Tabs ...
```
That prevents the breakage, but it does feel a bit ugly. I haven't found a good way to make it more foolproof.

**Comment by mistercrunch** [comment]
Oh that's brittle. Seems like we need to move 100% away from `Popover` onto antd equivalent, or towards a `SafePopover` that wraps the bootstrap one. Could be done in two steps...

**Comment by mistercrunch** [comment]
It does feel like more regressions in Popovers waiting to happen.

**Pull request merged**
