### PR TITLE
fix(maps): Move Overseas department and regions closer to France mainland

### PR DESCRIPTION
**Pull request by qleroy**
feat(maps): add drom closer to mainland France

### SUMMARY
The notebook repositions the overseas departments and regions of France (DROM) closer to mainland.
The file france.geojson is generated from the notebook.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Before (only France metropolitan departments): 
france_before

After (DROM included):
france_after

### TESTING INSTRUCTIONS

Execute the notebook to observe that France DROM are effectively moved closer to mainland so that it can be display in a single map.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by qleroy** [comment]
The relevant bit of code because there is no diff for notebook on github

```python
france_copy = france.copy()
reposition(france_copy, france.name=='Guadeloupe', 57.4, 25.4, 1.5, 1.5)
reposition(france_copy, france.name=='Martinique', 58.4, 27.1, 1.5, 1.5)
reposition(france_copy, france.name=='Guyane française', 52, 37.7, 0.35, 0.35)
reposition(france_copy, france.name=='La Réunion', -55, 62.8, 1.5, 1.5)
reposition(france_copy, france.name=='Mayotte', -43, 54.3, 1.5, 1.5)
```

**Comment by qleroy** [comment]
I also fixed two metropolitan names (errors natural earth data),
that were fixed by hand in the superset repo so a re-run of the notebook would have overwritten the fix.

- Seien-et-Marne => Seine-et-Marne
- Haute-Rhin => Haut-Rhin

```python
 def replace_name(df, old, new):
    if old in list(df.name):  
        index = df[df.name == old].index[0]
        df.at[index, 'name'] = new
replace_name(france, 'Seien-et-Marne', 'Seine-et-Marne')
replace_name(france, 'Haute-Rhin', 'Haut-Rhin')
```

**Comment by rusackas** [comment]
This is awesome! So happy we're fixing maps the _right_ way now!

**Review by mistercrunch — APPROVED** [review]
LGTM

**Comment by rusackas** [comment]
> @rusackas do I include this in this PR or in a separate one ?

A separate one would be ideal, I think :) Then after I see how you sorted that out, maybe one of us can do the same for the Italy Regions... then there will be no exceptions!

**Review by rusackas — APPROVED** [review]
Finally got a chance to pull and run the notebook... everything looks great!

**Comment by qleroy** [comment]
@rusackas  I did the follow up here #27014

**Comment by ThomasG77** [comment]
FYI, similar recipe using mapshaper (pure CLI approach) https://gist.github.com/ThomasG77/e20c52a39c581bab6a9e42e87d15b9e2 (in French, can translate if needed).

**Pull request merged**
