### PR TITLE
Adding explicit include for version_info.json

### PR DESCRIPTION
**Pull request by craig-rueda**
### CATEGORY

Choose one

- [x] Bug Fix
- [ ] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY
My prior MANIFEST.in PR switched to using a "whitelist" approach when adding things to the `/static/assets` folder. One file that was missed was the `version_info.json` file which is dynamically generated during the package installation process by `setup.py`. 

This PR adds an explicit include for said file.

### REVIEWERS
@mistercrunch

### CODE REVIEW

**Review by mistercrunch — APPROVED** [review]

**Comment by khtruong** [comment]
Do we also need an explicit include for the package.json file? We are seeing issues in our environment where that is missing as well.

**Comment by DiggidyDave** [comment]
Correct, that's my read also... the `package.json` fallback will never be found if it is not also whitelisted.

**Comment by craig-rueda** [comment]
Yep, so it actually depends on the tests that are being run -

**JS tests** will require `package.json`, however they are run directly from the `assets` folder (pre pip install) 
**Py tests** will run after installing (pip) and don't require package.json to run (hence the green Travis build).

In the end, the goal of this pr is actually to restore `version_info.json` to the resulting installed package. It's also advisable to NOT include `package.json` in deployed software where it can be accessed publicly.

**Comment by DiggidyDave** [comment]
Right, I'm just pointing out that the try/except block falls back to a condition that will _always_ cause a secondary exception with the not-whitelisted fallback file is not found.

**Comment by khtruong** [comment]
I am a little confused. Should we or should we not have the exception block?

**Comment by mistercrunch** [comment]
Ooops, just realized I merged without reading the new comments, my GH had not refreshed the page or something and updates shoed after merge.  Let's keep the conversation going here and I'm happy following up with another PR

**Comment by mistercrunch** [comment]
I think more generally we may need to restructure the JS `src/`-related folders and static folders independently. Images and CSS should be handled by webpack, and only what is needed by Superset as an app should make it under `static/`. The python package should not serve "internals" like `package.json` or `src/`...

Now about the version info, there are some challenges there, recent work around poetry brings the question back or where the version number should live. https://github.com/apache/incubator-superset/issues/8063

**Comment by khtruong** [comment]
How should we deal with tests? There is a comment in config.py that states that it falls back to "package.json" to get the version string when unit tests are running. We initially saw this problem from an automated test run.

**Comment by mistercrunch** [comment]
https://github.com/apache/incubator-superset/pull/8157 is building upon this, including `superset/assets/package.json` as the single source of truth for version in the package, but leaving it out of `static/`

**Pull request merged**
