### PR TITLE
fix: show run button when time series column is updated.

### LINKED ISSUE #16319: [time series table] Run button did not light up or show when change time series column settings
Run button did not light up or show when change time series column settings

### Expected results

Run button will light up or show when change time series column settings to remind user to click and show effect

### Actual results

Run button did not light up or show

#### Screenshots

https://user-images.githubusercontent.com/81597121/129859621-f051094f-bc49-4e1e-ad6b-e4c5432b74f1.mov

#### How to reproduce the bug

1. open time series table
2. change setting in time series column
3. See error

### Environment

(please complete the following information):

- superset version: latest master
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context
This issue is reproducible when dnd on, dnd off, dnd on+dnd hybrid on

### PR DESCRIPTION
**Pull request by pkdotson**
### SUMMARY
This fix ensure that the state change is detected when collection control is updated. 

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

https://user-images.githubusercontent.com/17326228/130167636-4ee163e4-7a05-4dd1-a8ef-1121ebd1c042.mov

### TESTING INSTRUCTIONS
Go to time series chart and add a metric in the time series column. Add some metric properties and ensure that run button state is updated.

### ADDITIONAL INFORMATION

- [ x] Has associated issue: Fixes https://github.com/apache/superset/issues/16319
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by junlincc** [comment]
LGTM!  i assume it works in dnd and dnd hybrid as well? is it possible to remove this "+" and replace it with the ghost button?in a different pr of course.

**Comment by pkdotson** [comment]
> LGTM! i assume it works in dnd and dnd hybrid as well? is it possible to remove this "+" and replace it with the ghost button?in a different pr of course.

Yep it work with dnd and dnd hybrid as well. Yes I'll do that separate.

**Review by rusackas — APPROVED** [review]
LGTM!

**Pull request merged**
