### PR TITLE
fix(sqllab): remove set state on component update lifecycle

### PR DESCRIPTION
**Pull request by justinpark**
### SUMMARY
Since the legacy TabbedSqlEditor component uses `UNSAFE_componentWillReceiveProps` lifecycle method to update the state for `editorQueries` and `dataPreviewQueries`, which **only** consumes in the result panel.
This can also violate the maximum update depth exceeded in some point. 

This commit deprecates `UNSAFE_componentWillReceiveProps` implementation and moves to the SouthPane connector where it actually needs.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Before:
Screen Shot 2022-10-11 at 11 00 46 AM

Screen Shot 2022-10-10 at 4 34 19 PM

After:
No errors

### TESTING INSTRUCTIONS
- Turn off `SQLLAB_BACKEND_PERSISTENCE`
- Go to SqlLab and open a tab
- Modify the localState of `redux.sqlLab.tables` (remove the table data associated to the current queryEditor id) from the array) in order to trigger the following setState update during lifecycle period.
 
https://github.com/apache/superset/blob/52d33b05fdb93b4e7a897641ae4e167528756829/superset-frontend/src/SqlLab/components/TabbedSqlEditors/index.jsx#L213-L216

- Refresh the page and check the console

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API
cc: @ktmud

### CODE REVIEW

**Review by ktmud — APPROVED** [review]
LGTM

**Comment by ktmud** [comment]
Can you add more details on how to reproduce this max-depth-call-stack error?

**Comment by justinpark** [comment]
> Can you add more details on how to reproduce this max-depth-call-stack error?

@ktmud I updated the step to reproduce

**Comment by EugeneTorap** [comment]
LGTM! Can we merge it?

**Pull request merged**
