### PR TITLE
refactor: Migrates legacy Sunburst charts to ECharts and removes legacy code

### PR DESCRIPTION
**Pull request by michael-s-molina**
### SUMMARY
As part of the [4.0 approved initiatives](https://github.com/orgs/apache/projects/292/views/1), this PR removes the legacy Sunburst chart by:

- Removing old plugin references throughout the codebase
- Updating unit tests
- Updating E2E tests
- Updating the example dashboards

### TESTING INSTRUCTIONS
1 - Make sure all legacy Sunburst charts were converted to Sunburst v2
2 - Make sure legacy Sunburst is not available anymore in the viz picker

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by john-bodley — APPROVED** [review]

**Comment by john-bodley** [comment]
@michael-s-molina I was wondering if the title of the PR "refactor: Removes the legacy Sunburst chart" should be updated? A non-informed reader may recoil thinking that you're simply removing the legacy chart, whereas in actuality you're actually migrating all their legacy charts to the ECharts equivalent and annexing all the legacy code.

**Comment by michael-s-molina** [comment]
> @michael-s-molina I was wondering if the title of the PR "refactor: Removes the legacy Sunburst chart" should be updated?
> 
> A non-informed reader may recoil thinking that you're simply removing the legacy chart, whereas in actuality you're actually migrating all their legacy charts to the ECharts equivalent and annexing all the legacy code.

Good call out. I changed the PR title to "refactor: Migrates legacy Sunburst charts to ECharts and removes legacy code"

**Review by justinpark — APPROVED** [review]

**Review by geido — APPROVED** [review]

**Comment by yousoph** [comment]
Is Sunburst v2 going to be renamed to "Sunburst" in the viz picker since there will be only one?

**Comment by michael-s-molina** [comment]
> Is Sunburst v2 going to be renamed to "Sunburst" in the viz picker since there will be only one?

@yousoph Good call. Renamed.

**Pull request merged**
