### PR TITLE
chore(docs): Move ::: onto its own line to fix caution formatting

### PR DESCRIPTION
**Pull request by sfirke**
### SUMMARY
Tried to fix this in #28236, it didn't work, trying again.  I'm modeling the fix on the caution block on the page https://raw.githubusercontent.com/apache/superset/master/docs/docs/quickstart.mdx which renders correctly.

### CODE REVIEW

**Review by mistercrunch — APPROVED** [review]

**Comment by mistercrunch** [comment]
Do you run `yarn run start`? It works super well for me and updates the pages instantly as I save files.

**Comment by sfirke** [comment]
I haven't - sounds like I should, thanks for the tip!  My current dev setup leaves a lot to be desired, I need to improve it...

**Comment by mistercrunch** [comment]
Oh yeah it's super neat - starts a process that monitors and auto-refreshes, you don't even need to `cmd-r` to refresh the page, otherwise you're flying blind!

**Comment by rusackas** [comment]
Just "yarn start" to be pedantic ;)

**Pull request merged**
