### PR TITLE
refactor: icon to icons for listviewcomponent

### PR DESCRIPTION
**Pull request by pkdotson**
### SUMMARY
this pr refactors the listview icon and and cardview icon to the new icons component

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
before 
Screen Shot 2021-06-27 at 5 26 08 AM

after
Screen Shot 2021-06-30 at 4 33 35 AM

### TESTING INSTRUCTIONS
got to any of the listviews to view card and list icons

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by michael-s-molina** [comment]
> @michael-s-molina Ephemeral environment creation is currently limited to committers.

😢 @rusackas?

**Comment by michael-s-molina** [comment]
@pkdotson The alignment is a little bit up after the change. This problem is happening in more than one place when the new icon component is being used. Maybe we can find a global solution for this?

**Comment by michael-s-molina** [comment]
Another thing is that the icon is not centralized inside the button or the button should have more height.
Screen Shot 2021-06-30 at 7 28 44 AM

**Review by michael-s-molina — APPROVED** [review]

**Review by rusackas — APPROVED** [review]
LGTM. Thanks for the alignment tweak.

**Pull request merged**
