### PR TITLE
fix: avoid while cycle in computeMaxFontSize for big Number run forever when css !important rule applied

### PR DESCRIPTION
**Pull request by Gwitchr**
### SUMMARY

adding custom CSS to a dashboard with a bigInt chart would activate a while loop that didn't ever finished, which somehow wasn't caught by the surrounding ErrorBoundary cause the whole app crashed before running out of memory (my guess) 

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

https://user-images.githubusercontent.com/22302890/168395532-ef3dc781-3415-4a76-82fa-23d796395bde.mov

### TESTING INSTRUCTIONS

1. Create a Dashboard.
2. Access it on edit mode.
3. Click on the three ellipses on the top right corner > **Edit CSS**.
4. Add below CSS code to it:
```
.header-line {
font-size: 170px!important;
}
```
5. Add a Big Number Chart to the Dashboard.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by stephenLYZ** [comment]
Thanks for the fix! It looks like the codecov didn't pass, so I'm guessing we might need to add some branch tests for this function.

**Comment by villebro** [comment]
IIRC, @kgabryje already fixed a related problem in #19688 - I wonder if this additional check is still needed?

**Comment by kgabryje** [comment]
Thanks for tagging me Ville! My fix doesn't cover the scenario presented by @Gwitchr, so I think this should go in.
I just wonder if we could break the loop quicker - instead of decrementing to below 0, maybe we could do a check like "if the size for font size x is the same as the size for x-1, return x". Wdyt?

**Comment by kgabryje** [comment]
Also, it would be great to implement binary search for optimal font size instead of decrementing by 1 to improve performance, but that's definitely out of scope of this PR 🙂 

Anyway, is the proposal from comment above is not viable or would require a large refactor, let's merge this fix (which is great!) and iterate on this later

**Review by rusackas — APPROVED** [review]

**Comment by kgabryje** [comment]
Replaced by https://github.com/apache/superset/pull/20173

**Pull request closed without merging**
