### PR TITLE
fix: Capitalization / Sentence case under Settings

### PR DESCRIPTION
**Pull request by codemaster08240328**
### SUMMARY

Based on capitalization guide from superset, we need to convert `Row Level Security` into `Row level security` under settings menu. 

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

After Updates:

image

### CODE REVIEW

**Comment by rusackas** [comment]
This is correct that according to the [guidelines](https://github.com/apache/superset/wiki/Capitalization-Guidelines), `Row Level Security` should become `Row level security` - however we might as well get ALL of the items in that menu to follow the same rules. I think they should be:
* List users
* List roles
* Row level security
* Action log
* Annotation layers
* CSS templates _(note CSS should probably be all caps)_
* Alerts & Reports _(remains capitalized because it's a page name, as it appears in the nav)_
* Profile
* Info
* Logout

@mihir174 @ kasiazjc please feel free to check my math on the above.

**Review by rusackas — CHANGES_REQUESTED** [review]
I'm a little nervous about this approach here. I don't think we need new utils to parse and change the case of items, especially if that will be implemented to handle each string differently. It seems this PR goes the route of "if it's this string, make it sentence case. If it's that string, make it title case". Rather than making string transformations based on cases, can we just find and change the actual string at the source?

**Comment by rusackas** [comment]
See also [this PR](https://github.com/apache/superset/pull/17135) where the last couple of these were made uppercase to match. We should just edit those `title` attributes there for this PR.

**Comment by rusackas** [comment]
@dpgaspar do you recall offhand where the `List Users` and `List Roles` are set, and/or how we might override them? I'm assuming they're in a FAB Jinja template, or in a database somewhere. We want to make them sentence case (e.g. `List users` and `List roles`) per our design guidelines.

**Comment by dpgaspar** [comment]
> @dpgaspar do you recall offhand where the `List Users` and `List Roles` are set, and/or how we might override them? I'm assuming they're in a FAB Jinja template, or in a database somewhere. We want to make them sentence case (e.g. `List users` and `List roles`) per our design guidelines.

The most straightforward way, would be overriding the role model view class from FAB, but unfortunately for the user's we have multiple classes to override (basically one per auth method). So we would need to override all these: https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/security/views.py#L255.

We have an ongoing PR on FAB https://github.com/dpgaspar/Flask-AppBuilder/pull/1801 for adding a CRUD view around the security APIs, a better long term path would be to leverage that and build the UI around those. IMO

**Comment by rusackas** [comment]
@codemaster08240328 let me know if you think the advice from Daniel above is actionable. If not, we'll hand this PR to Design and Product and see if we want to merge it (moves toward capitalization standards, but adds an inconsistency) or hold off (not to capitalization standards, but is at least consistent)

**Comment by rusackas** [comment]
To do: Should we be concerned about localization?

**Comment by rusackas** [comment]
Closing this PR for now... we can reopen later if we (perhaps with @dpgaspar's help) figure out how to make the FAB changes so that things are actually consistent stem-to-stern.

**Pull request closed without merging**
