### PR TITLE
refactor: Remove reactable arc

### PR DESCRIPTION
**Pull request by kgabryje**
### SUMMARY
This PR replaces the last 2 use cases of `reactable-arc` with `react-table` (EstimateQueryCostButton and DisplayQueryButton).

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Before:
image

After:
image

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [x] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by kgabryje** [comment]
@rusackas @etr2460 Can you please take a look?
I'd appreciate if someone could make sure that EstimateQueryCostButton works properly - I couldn't find a database in my test data that would allow me to use that functionality.

**Comment by rusackas** [comment]
@betodealmeida are you able to confirm if the query cost estimate still works as expected with this change?

**Comment by junlincc** [comment]
totally unrelated, but can we add some spacing between the pill and the copy/paste icon?

**Comment by kgabryje** [comment]
@junlincc Done 
image

**Comment by betodealmeida** [comment]
@kgabryje the query cost estimation returns data like this:

```[
            {
                "Output count": "904 M rows",
                "Output size": "354 GB",
                "CPU cost": "354 G",
                "Max memory": "0 B",
                "Network cost": "354 G",
            }
        ]
```

Can you test by hardcoding the response from the backend? Let me know, if not I can pull your branch and take a look.

**Comment by kgabryje** [comment]
Thanks @betodealmeida, I hardcoded the data and it looks like this:
image
So I think it works well and this PR is ready to merge.

**Review by rusackas — APPROVED** [review]
LGTM! Thanks for the additional help testing, @kgabryje and @betodealmeida!

**Pull request merged**
