### PR TITLE
feat: add sort_by_metric for charts with single metric

### PR DESCRIPTION
**Pull request by maloun96**
### SUMMARY
Add sort_by_metric flag for charts with single metric

Related: #12674 

## legacy-plugin-chart-heatmap
heatmap

## legacy-plugin-chart-sunburst
sunburst

## legacy-plugin-chart-force-directed
force-directed

## legacy-plugin-chart-chord
chod

## legacy-plugin-world-map
country-map

### ADDITIONAL INFORMATION

- [ ] Has associated issue: #12674 
- [x] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [x] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by junlincc** [comment]
@maloun96 thanks for the PR and dedicated work, Victor! when I pulled for testing, changes are not showing, did I miss something?

**Comment by maloun96** [comment]
> @maloun96 thanks for the PR and dedicated work, Victor! when I pulled for testing, changes are not showing, did I miss something?

@junlincc You have to link locally all the plugins with `npm link`

**Comment by junlincc** [comment]
LGTM functionality wise. We should tweak UI when we implement drag and drop query, will also need special treatment for sort-by single metric. 

Screen Shot 2021-02-11 at 3 46 56 PM
https://www.figma.com/file/JWaGztdhZS0kS5ruG7x9tB/Control-Panel?node-id=195%3A36068

**Review by ktmud — APPROVED** [review]
LGTM

**Comment by ktmud** [comment]
Merging to unblock #13100

**Pull request merged**
