### PR TITLE
feat(dashboard): Hide chart header controls in reports

### PR DESCRIPTION
**Pull request by kgabryje**
### SUMMARY
If report is running, hide the slice header controls (filters badge, 3 dots options menu etc.).
To determine if report is running, we check if `standalone` query param is equal to `DashboardStandaloneMode.REPORT`

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Before:
image

After:
image

### TESTING INSTRUCTIONS
1. Open a dashboard - chart header controls (filters badge, 3 dots for menu etc.) should be visible
2. Run a report -chart header controls should not be visible

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by john-bodley** [comment]
@kgabryje I think having the filter indicators et al. in the render report or alert is actually helpful to the reader as it indicates which charts are impacted by the filters. Without them the results could more easily* be misinterpreted.

\* Note even currently these can still be misinterpreted given it's not overly evident (without hovering) which filters are impacting said chart.

**Comment by kgabryje** [comment]
> @kgabryje I think having the filter indicators et al. in the render report or alert is actually helpful to the reader as it indicates which charts are impacted by the filters. Without them the results could more easily* be misinterpreted.
> 
> * Note even currently these can still be misinterpreted given it's not overly evident (without hovering) which filters are impacting said chart.

Yeah that was our thinking that the filters badge is not very helpful as you can't even see the filters bar in the reports.
It's a fair point though that it might be useful to know if a chart is impacted by any filter at all.
@yousoph do you have an opinion on this?

**Comment by yousoph** [comment]
Yeah, part of the thought process was also to not make the filters indicator look clickable in the screenshot where they aren't actually clickable. 

Perhaps separately we need a clearer way to communicate filters information to the users in reports, that could also better prompt to open the dashboard link to see full filters details?

**Comment by john-bodley** [comment]
@kgabryje do you think—given that this feels like a UX regression—that we close this current PR and collectively try to formulate a solution (if possible) which better indicates which filters are being applied in the context of reporting?

**Pull request closed without merging**
