### PR TITLE
fix(dashboard-css): make to stay custom css when reload

### PR DESCRIPTION
**Pull request by prosdev0107**
### SUMMARY
Dashboard CSS disappears

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
BEFORE:
The dashboard custom css is disappeared when reloaded.
AFTER:
The dashboard custom css stay when reloaded.

### TESTING INSTRUCTIONS

**How to reproduce the bug**
1. create a dashboard
2. Edit CSS and save, for example with: 

```body {   background-color: black; }```

3.The background appears normally but when you reload the page it is not there and the CSS is gone

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by rusackas** [comment]
Unit tests seem to be failing on some styling expectation. Can you check to see if those are working locally?

**Review by diegomedina248 — APPROVED** [review]

**Comment by rusackas** [comment]
> I am wondering if it should has the test of rendering the custom css in HeaderActionsDropdown.test.tsx.

Ideally all `fix:()` PRs will have a good test to make sure that whatever's fixed doesn't regress again. If we can add that test in this PR to make sure styles are properly persisted, that'd be fanastic!

**Comment by prosdev0107** [comment]
@rusackas 
That test was already added.

**Review by rusackas — APPROVED** [review]
Thanks for the followup. LGTM!

**Comment by sadpandajoe** [comment]
🏷️ preset:2022.11

**Pull request merged**
