### PR TITLE
Fix: node version to 8.12.0

### PR DESCRIPTION
**Pull request by kk580kk**
Problem: node version is v4  but not v8
Steps to fix : copy from officially node js dockerfile from  https://github.com/nodejs/docker-node/blob/526c6e618300bdda0da4b3159df682cae83e14aa/8/stretch/Dockerfile

now node version is v8.12.0

PS: origin dockerfile didn't check the node version after run install command, that easily cause some problems.

### CODE REVIEW

**Comment by mistercrunch** [comment]
Can we just find an image that has a recent node baked in?

**Comment by kk580kk** [comment]
@mistercrunch maybe we can't , we already base on Python:3.6 
this image helps us to build  on stable Python environment.

**Comment by kk580kk** [comment]
@mistercrunch  i don't know but maybe someone maintain a image that have python and node , and this group of version suit our project.
But official node and official python didn't do this.

The only way I know  is  base one of them and install other requirements.

**Comment by kk580kk** [comment]
@mistercrunch  i don't know but maybe someone maintain a image that have python and node , and this group of version suit our project.
But official node and official python didn't do this.

The only way I know  is  base one of them and install other requirements.

**Comment by kk580kk** [comment]
In My company , we used to build frontend in a independent docker environment, then the others only developed base on the result ( a min.js , already compressed) . the min.js don't need any node environment.

**Comment by mistercrunch** [comment]
I'm not super knowledgeable with Docker, but from my understanding you can layer different things to bake an image. Can we just reuse a nodejs layer on top of a base Linux distro that uses python3.6?

**Comment by kk580kk** [comment]
@mistercrunch O~~~k~~~~ I will build a nodejs image base on python3.6

**Comment by kk580kk** [comment]
@mistercrunch  Is this changes suit you thoughts?

**Comment by mistercrunch** [comment]
I think this PR contains more than what you intended to put in it (69 files got changed)

**Comment by kk580kk** [comment]
@mistercrunch  I created a new pull request https://github.com/apache/incubator-superset/pull/6387

**Pull request closed without merging**
