### PR TITLE
chore: Change chart_is_fav to chart_is_favorite

### PR DESCRIPTION
**Pull request by nikolagigic**
### SUMMARY
Change chart_is_fav to chart_is_favorite

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by nytai — COMMENTED** [review]
We should probably update instances of this filter in the frontend too, so we don't break any pages between commits.

**Comment by nikolagigic** [comment]
> We should probably update instances of this filter in the frontend too, so we don't break any pages between commits.

what other instances on the front-end are there?

**Review by rusackas — APPROVED** [review]
LGTM. @nytai I'm not seeing any other instances of this either... are we missing something?

**Comment by nytai** [comment]
Oh never mind, I thought you were doing `dashboard_is_fav` as well, so the files changed looked low

**Review by nytai — APPROVED** [review]

**Comment by rusackas** [comment]
Converting to draft, awaiting merge of #12060 first.

**Comment by rusackas** [comment]
@nikolagigic Maybe you want to give the same treatment to `dashboard_is_fav` on this PR too, whilst we're waiting?

**Comment by nikolagigic** [comment]
> @nikolagigic Maybe you want to give the same treatment to `dashboard_is_fav` on this PR too, whilst we're waiting?

will do

**Review by rusackas — APPROVED** [review]
LGTM

**Pull request merged**
