### PR TITLE
fix: force data load on import examples

### PR DESCRIPTION
**Pull request by eschutho**
### SUMMARY
This attempts to fix some errors that we're seeing in current builds from pre 2.1 to master of ephemerals and docker tarball testing for releases. Some tables aren't loading into sqlite because the table is locked, so I'm passing in the force flag to reload the data if it was unsuccessful

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Before:
Sales_Dashboard

After:
Sales_Dashboard

### TESTING INSTRUCTIONS
Ephemeral environments should succeed in loading example data

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by eschutho** [comment]
I'll write some tests for this once I confirm that the fix is working here.

**Review by Antonio-RiveroMartnez — APPROVED** [review]

**Review by rusackas — APPROVED** [review]
We might need to hit up github support to better understand WHY this works, but if it DOES work, then LGTM :)

**Comment by rusackas** [comment]
Would you rather I merge or close https://github.com/apache/superset/pull/23893 ?

**Comment by eschutho** [comment]
> Would you rather I merge or close #23893 ? I should probably just close it... I'll wait for this to merge though.

Either way @rusackas. Thanks for that fix, I pulled it in here b/c it was the only way that I could test if this worked. :)

**Comment by sebastianliebscher** [comment]
Hi @eschutho, while working on https://github.com/apache/superset/pull/25564 I noticed the following:

The check `if: needs.config.outputs.has-secrets` returns true in both cases when the variable has any content. So even if jobs have the check, they will run anyway.

The solution could be either to check `if: needs.config.outputs.has-secrets == 1` or don't set `has-secrets` when there are no secrets.

**Comment by eschutho** [comment]
> Hi @eschutho, while working on #25564 I noticed the following:
> 
> The check `if: needs.config.outputs.has-secrets` returns true in both cases when the variable has any content. So even if jobs have the check, they will run anyway.
> 
> The solution could be either to check `if: needs.config.outputs.has-secrets == 1` or don't set `has-secrets` when there are no secrets.

Hi, yeah I saw your comment in the other PR, too, thanks! This was a fix that @rusackas and I brought in to fix some CI failures, but we weren't sure the absolute need for it. If it works to remove the check like in #24464 then that seems to be a good fix, if you think that will work.

**Pull request merged**
