### PR TITLE
chore(helm): bumping app version to 4.0.2 in helm chart

### PR DESCRIPTION
**Pull request by lodu**
appVersion: 4.0.1 -> 4.0.2
chart version: ~~0.12.12 -> 0.12.13~~  0.12.13 -> 0.12.14

### CODE REVIEW

**Comment by joshkoeneHawking** [comment]
👍

**Comment by Jarxinho** [comment]
Hello @craig-rueda @dpgaspar @villebro 

I hope you're doing well. When can we expect the 0.12.13?

Best regards

**Comment by Jarxinho** [comment]
@craig-rueda @dpgaspar @villebro bump

**Comment by debggr** [comment]
bump

**Comment by rusackas** [comment]
Not sure. @craig-rueda is listed as the maintainer in the file, but @villebro also keeps an eye on this stuff. PING :)

**Comment by PrincipeAgustin** [comment]
Any updates?

**Comment by arm-moodys** [comment]
Hello, do we know when this change will go into master?

**Comment by lodu** [comment]
In the meantime a new chartVersion was released so now its 0.12.13-> 0.12.14

**Comment by arm-moodys** [comment]
Is there a date for when this PR will be merge? All the checks have passed. It would be very helpful to get the new changes from 4.0.2 available on the Helm chart.

**Comment by debggr** [comment]
> Is there a date for when this PR will be merge? All the checks have passed. It would be very helpful to get the new changes from 4.0.2 available on the Helm chart.

+1

**Comment by lodu** [comment]
@arm-moodys @debggr fyi: you can use the current chart with 4.0.2 by changing [this line](https://github.com/apache/superset/blob/f4094829c2c1d9edf70147ae1f8fe59aaa1fa927/helm/superset/values.yaml#L188) in your Values file to the relevant container tag (4.0.2 or 4.0.2-dev or probably).
Won't work when there is a major change in the Helm chart between releases tho.

**Comment by arm-moodys** [comment]
> @arm-moodys @debggr fyi: you can use the current chart with 4.0.2 by changing [this line](https://github.com/apache/superset/blob/f4094829c2c1d9edf70147ae1f8fe59aaa1fa927/helm/superset/values.yaml#L188) in your Values file to the relevant container tag (4.0.2 or 4.0.2-dev or probably). Won't work when there is a major change in the Helm chart between releases tho.

Thanks again, this worked.

**Comment by lodu** [comment]
closing this since 4.1.0 is released. I will make a PR for that.

**Pull request closed without merging**
