### PR TITLE
chore(docs): custom and built-in event logging class at the same time

### PR DESCRIPTION
**Pull request by wiktor2200**
### SUMMARY

There was lack of documentation for using built-in DB based event logger along with custom JSON logger so I've added that.

### ADDITIONAL INFORMATION

- [x] Has associated issue: https://github.com/apache/superset/issues/15548
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by villebro** [comment]
Thanks for this contribution @wiktor2200. In the interest of keeping the documentation as compact and to-the-point as possible, I'm unsure if we need to document how to extend the `DBEventLogger` (most Superset admins should know this). However, it could be a good idea to mention in the docs that when using a custom event logger, events will no longer be populated in the `logs` table, and that one will need to extend the `DBEventLogger` class to do this.

Ping @srinify for thoughts on this?

**Comment by wiktor2200** [comment]
I totally agree, it's not rocket science to add it, but it's worth to mention that using custom will stop logging to `logs` table and info that it could be quite easily added.

**Comment by wiktor2200** [comment]
Hi @villebro! I've updated this doc file as you suggested. Removed additional part, leaving only notice about running custom classes simultaneously. Please take a look.

**Review by villebro — APPROVED** [review]
LGTM, thanks for iterating on this!

**Pull request merged**
