### PR TITLE
feat(color): color consistency enhancements

### PR DESCRIPTION
**Pull request by stephenLYZ**
### SUMMARY

In the current world, we have this problem:
• SharedLabelColors are calculated when the dashboard loads, but only for the visible tab(s)
• SharedLabelColors are only "reserved" if the label is used twice or more in the VISIBLE charts at load time.
• This means if a label is used once at load time, and then used by another chart when a hidden tab is loaded, the color will be inconsistent.

Current solution by @rusackas and @geido :
• When loading the initial dashboard, make ALL labels use reserved colors... not just those that are used more than once. In other words, assume that ALL colors will be shared/reused.
• Then, when you change tabs, any labels that are used the second time (or more) will already be in the SharedLabelColors 
• When loading/exposing a hidden tab, you might see a new series/label for the first time. These should also be added to SharedLabelColors, in case a third or subsequent tab uses those.

Module Diagrams:
untitled@2x

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by geido** [comment]
@stephenLYZ thanks for this! 
I tested it and I found that when setting up custom label colors, they only work for the first tab now, but not the other one. Have a look at the screenshots. I forced Michael to be yellow in the metadata

Screenshot 2022-09-21 at 14 28 11

Screenshot 2022-09-21 at 14 28 18

**Comment by stephenLYZ** [comment]
> @stephenLYZ thanks for this! 
> 
> I tested it and I found that when setting up custom label colors, they only work for the first tab now, but not the other one. Have a look at the screenshots. I forced Michael to be yellow in the metadata
> 
> 
> 
> Screenshot 2022-09-21 at 14 28 11
> 
> 
> 
> 
> 
> Screenshot 2022-09-21 at 14 31 11
> 
> 
> 
> 

Good catch! This is a case that I have missed, I only dealt with the case of changing the color scheme.

**Comment by geido** [comment]
@stephenLYZ as I work on the E2E I report here any issue that I encounter. 

I just found an issue with already rendered charts under a hidden tab. If you first visit the tab and let the chart load, then move away to another tab, add a custom label color and go back to the tab with the chart, you will see that the custom label color isn't applied. 

https://user-images.githubusercontent.com/60598000/192529879-db758eff-e290-4973-a39e-e4edc9365da2.mp4

Same thing happens with changing the color scheme

https://user-images.githubusercontent.com/60598000/192530373-a55553ce-6289-4887-8947-26de4be503ca.mp4

**Comment by geido** [comment]
@stephenLYZ the above happens also for main tabs. If you go to tab B, then go to tab A, change scheme, go back to tab B and you will see the color scheme isn't applied.

I also found an even weirder bug where if you change the color scheme from tab B, it picks different colors than if you did change it from tab A.

**Comment by geido** [comment]
@stephenLYZ not sure if this is all about the same issue, but when changing color scheme, it works for a nested tab in the initial dashboard tab, but it is not applied correctly to the second tab. As you can see the label colors for "Anthony" are different

https://user-images.githubusercontent.com/60598000/192785479-c6bd1910-22cc-485e-b536-8ce06b5caa84.mp4

**Comment by stephenLYZ** [comment]
@geido It looks like I can't reproduce in my local. I actually fixed this issue in the 'Chart.jsx' file:

image


https://user-images.githubusercontent.com/11830681/193212693-da333241-40a3-412a-85b9-db9f686532e1.mov

**Comment by geido** [comment]
> @geido It looks like I can't reproduce in my local. I actually fixed this issue in the 'Chart.jsx' file:
> 
> image
> 
>  2022-09-30.3.11.25.mov

@stephenLYZ you are looking at nested tabs as I explained in my latest comment. You should be looking at the main tabs as well. Please follow the steps of my video. As I recommended, you can use my E2E tests to verify whether your changes are working as they are expected to https://github.com/apache/superset/pull/21622

**Comment by geido** [comment]
> @geido It looks like I can't reproduce in my local. I actually fixed this issue in the 'Chart.jsx' file:
> 
> image
> 
>  2022-09-30.3.11.25.mov

@stephenLYZ I can reproduce this pretty consistently with the "Tabbed Dashboard" that is available as a sample dashboard in the E2E testing env. I suggest that you try your changes using my E2E tests PR https://github.com/apache/superset/pull/21622 where the above issues should be apparent immediately.

**Review by geido — APPROVED** [review]
LGTM! The CI needs some love

**Review by geido — CHANGES_REQUESTED** [review]
Hello @stephenLYZ after testing your latest changes again I found a problem.
It seems that the colors are not assigned in the right order. "Anthony" should use the first color available from the Lyft Colors scheme but it isn't.

Also, the colors are assigned differently whether the chart was already rendered or not. Look at "Bangladesh" in my video. When it was **not** rendered it was correctly assigned the first color of the Lyft Colors scheme. However, after it was rendered and after re-applying the Lyft Colors, it "Bangladesh" picked a different color.

https://user-images.githubusercontent.com/60598000/194026176-2e26d0a5-866c-4a72-8337-a031b20ddce3.mp4

**Review by geido — APPROVED** [review]
All tests are passing now!

**Comment by geido** [comment]
Adding @jinghua-qa for an upmost confirmation from QA. Let's hold for her feedback before merging

**Comment by jinghua-qa** [comment]
I found an issue that if a series in different charts in the same dashboard, then it is not consistent for the color on that series
here how i reproduce this issue:
step 1: Run this sql query and create dataset: 
SELECT * FROM
(SELECT 'a' as color, 1 as val
UNION
SELECT 'b', 1
UNION
SELECT 'c', 1
UNION
SELECT 'd', 1
UNION
SELECT 'e', 1
UNION
SELECT 'f', 1
UNION
SELECT 'g', 1
UNION
SELECT 'h', 1
UNION
SELECT 'i', 1
UNION
SELECT 'j', 1
UNION
SELECT 'k', 1
UNION
SELECT 'l', 1
UNION
SELECT 'm', 1
UNION
SELECT 'n', 1
UNION
SELECT 'o', 1
UNION
SELECT 'p', 1
UNION
SELECT 'q', 1
UNION
SELECT 'r', 1
UNION
SELECT 's', 1
UNION
SELECT 't', 1
UNION
SELECT 'u', 1
UNION
SELECT 'v', 1
UNION
SELECT 'w', 1
UNION
SELECT 'x', 1
UNION
SELECT 'y', 1
UNION
SELECT 'z', 1
) as _view
ORDER BY COLOR
step2: create 3 charts using the same dataset:
chart 1: metrics: count(*), dimension: color
chart 2:metrics: count(*), dimension: color, filter: color in a, b, c
chart 3:metrics: count(*), dimension: color, filter: color in d, e, f
add 3 charts to same dashboard
step 3: create native filter for color name, then apply filter with color name a, e

Expect:
chart 1: a, e show different color
chart 2, a show same color with chart 1, series a
chart 3, e show same color with chart 1 series ec

Actual:
chart 2 series a show same color as series e
Screen Shot 2022-10-12 at 11 54 40 PM

**Comment by stephenLYZ** [comment]
@jinghua-qa Thanks for reporting this issue. This is a bug once we enter the dashboard from explore. I have fixed it and maybe we can add some e2e tests for the native filter scene in the future. cc @geido

**Review by geido — CHANGES_REQUESTED** [review]
I am sorry but I found another issue :(

If you look at the video you will see that the label "Daniel" changes color when you set a custom label color "Anthony". I am not sure why this happens but it is causing all sorts of weird behaviours when removing custom label colors. The colors should be deterministic. If you add a custom label color, it should not affect the colors of all the other labels, but only that of the target label.

https://user-images.githubusercontent.com/60598000/195610879-1218f271-f0db-4637-bef0-7c9c9611edb3.mp4

**Comment by stephenLYZ** [comment]
> 

The problem may have existed before. I will fixed this in this PR.

**Review by geido — APPROVED** [review]
Tentatively re-approving as all new test scenarios are passing. @jinghua-qa another look from your side would be very appreciated!

**Review by jinghua-qa — APPROVED** [review]
LGTM

**Pull request merged**
