### PR TITLE
Disable user access request

### PR DESCRIPTION
**Pull request by timifasubaa**
The request access feature isn't fully implemented and it can potentially be misleading to users who click the access request button and expect to gain access eventually. This PR makes the access request button optional via a feature flag that allows it by default. 

If you set the flag to false, you'll no longer see the image below whenever you don't have access to any of the slices in a dashboard. 
no_access_

Instead, you'll see all the slices and an error message for any one you don't have access to. Like in the image below. 
screen shot 2018-02-11 at 11 13 09 pm

@john-bodley @michellethomas  @mistercrunch

### CODE REVIEW

**Comment by mistercrunch** [comment]
You may want to disable the ModelView as well

**Comment by timifasubaa** [comment]
@mistercrunch Done

**Comment by mistercrunch** [comment]
Let's flip it off by default.

**Comment by timifasubaa** [comment]
Done

**Comment by timifasubaa** [comment]
Ah, true. I'll do it that way instead.

**Comment by maver1ck** [comment]
Do you have idea how does it join with https://github.com/apache/incubator-superset/issues/4352 ?

**Comment by timifasubaa** [comment]
@maver1ck  This PR only gives different deployments the the option to remove the ability to request access from users. It doesn't change whether gamma has access to dashboards it created.

**Pull request merged**
