### PR TITLE
bugfix [AdhocFilter] when option is number,isValid failed

### PR DESCRIPTION
**Pull request by rzlmma**
when option is number, the  number type has no attribution of length, so the function returned false.  But this is error, so i fix it.

### CODE REVIEW

**Comment by john-bodley** [comment]
cc: @GabeLoins

**Review by gabe-lyons — CHANGES_REQUESTED** [review]
I'm wondering how an adhoc filter can gain a comparator of a type other than string? That is not possible to my knowledge. Maybe we should fix that instead

**Comment by rzlmma** [comment]
hello,  see the picture. why the type of the comparator is number?
wx20180622-094652 2x

**Comment by GabeLoins** [comment]
I'm not able, to reproduce, for me the type of adhocFilter is always a string:

image

**Pull request closed without merging**
