### PR TITLE
feat: Add Czech Republic country map.

### PR DESCRIPTION
**Pull request by martinspudich**
### SUMMARY

Add Czech Republic country map

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [X] Changes UI
- [ ] Includes DB Migration (follow approval process in https://github.com/apache/superset/issues/13351)
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by rusackas** [comment]
Hi! These need to be added to the Jupyter notebook (which might be a one-line edit, adding the country name), as the geojson files and TS files are generated from there. If we don't do that, these files won't be maintained, and may be overwritten.

**Comment by martinspudich** [comment]
@rusackas Hi, I add 'czech republic' to Jupyter notebook.

**Review by mistercrunch — APPROVED** [review]

**Comment by rusackas** [comment]
> Hi, I add 'czech republic' to Jupyter notebook.

Thanks! There's another PR I probably ought to merge first... gimme a little while here...

**Review by rusackas — APPROVED** [review]

**Comment by RIS3cz** [comment]
No Czech Republic map in v 4.0.2. Why?

**Comment by sfirke** [comment]
4.0.2 is a patch/bugfix release, it only pulls in cherries that fix bugs.  This is considered a feature and so will be in the 4.1.0 release, which should be cut this week for testing.  Please stayed tuned to the 4.1.0 Release Candidate voting period during which you can test out 4.1.0 RC1 and make sure this works how you expect.

**Comment by RIS3cz** [comment]
> 4.0.2 is a patch/bugfix release, it only pulls in cherries that fix bugs. This is considered a feature and so will be in the 4.1.0 release, which should be cut this week for testing. Please stayed tuned to the 4.1.0 Release Candidate voting period during which you can test out 4.1.0 RC1 and make sure this works how you expect.

Dear @sfirke, well, when I think about the versions and I know the way it works with the releases, I can understand it. But when I think in the way of common sense and practical usage, I do not understand why in the same time Krymea has returned back to Ukraine (which is another matter and I do not comment) at same time the suvereign countries, members of the EU, Czechia and Slovakia, being previously Czechoslovakia have not managed to be added to the countires folder of superset-frontend. I believe it will be repaired in close future. Thank You.

**Pull request merged**
