### PR TITLE
fix(dashboard): Fix scroll behaviour in DashboardBuilderSidepane

### PR DESCRIPTION
**Pull request by EugeneTorap**
Fix wrong scroll behaviour in `CHARTS` tab on DashboardBuilder

### BEFORE

https://user-images.githubusercontent.com/29536522/182790268-5a25504a-db20-4658-94cc-147e89698346.mov

### AFTER

https://user-images.githubusercontent.com/29536522/182790485-6b356690-5d2b-40d5-b4d8-71498704adb7.mov

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API
@michael-s-molina @kgabryje @lyndsiWilliams

### CODE REVIEW

**Comment by EugeneTorap** [comment]
@michael-s-molina @kgabryje @lyndsiWilliams @hughhhh Can you review it?

**Review by kgabryje — APPROVED** [review]
Tested, works great! Thank you for fixing that

**Pull request merged**
