### PR TITLE
chore: bump superset-ui to 0.18.18

### PR DESCRIPTION
**Pull request by villebro**
### SUMMARY
Bring in the following PRs from `superset-ui`:
- https://github.com/apache-superset/superset-ui/pull/1445
- https://github.com/apache-superset/superset-ui/pull/1416
- https://github.com/apache-superset/superset-ui/pull/1440
- https://github.com/apache-superset/superset-ui/pull/1447
- https://github.com/apache-superset/superset-ui/pull/1448

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by zhaoyongjie — APPROVED** [review]
LGTM

**Comment by john-bodley** [comment]
@villebro the PR title should read "chore: bump superset-ui to 0.18.18".

**Comment by villebro** [comment]
> @villebro the PR title should read "chore: bump superset-ui to 0.18.18". 
> 
> 

Whoops, thanks for catching that!

**Comment by sadpandajoe** [comment]
🏷️ 2021.44

**Pull request merged**
