### PR TITLE
fix(docs): CSP mods to re-enable Algolia search

### PR DESCRIPTION
**Pull request by rusackas**
### SUMMARY

Saw a few CSP issues in here, so I got everything that was throwing errors. This should fix the site search, but might fix other random things too :)

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by sfirke — APPROVED** [review]
LGTM!

**Review by geido — APPROVED** [review]

**Comment by rusackas** [comment]
It looks like the site didn't update at all... I'm going to have to take this up with ASF infra (again).

**Comment by sfirke** [comment]
Bah. Thank you and good luck! 🤞

**Comment by rusackas** [comment]
Actually, I think it's our CI that didn't trigger/run correctly... it looks like the change was not pushed over to the other docs repo that's actually hosted.

**Comment by rusackas** [comment]
I take it back. CI was fine. Published an INFRA ticket here: https://issues.apache.org/jira/browse/INFRA-25701

**Pull request merged**
