### PR TITLE
Allow bigint to be used as time column in Presto

### PR DESCRIPTION
**Pull request by betodealmeida**
##### SUMMARY

We have a table in Presto where the temporal column is a `BIGINT`, representing a unix timestamp. This allows us to use it as a temporal column in the explore view.

##### TEST PLAN

Previous query:

```sql
SELECT COUNT(*) AS "count"
FROM "superset"."logs"
WHERE "dttm" >= '2019-03-27 00:00:00'
  AND "dttm" <= '2019-04-03 00:00:00'
ORDER BY "count" DESC
LIMIT 10000;
```

Now:

```sql
SELECT COUNT(*) AS "count"
FROM "superset"."logs"
WHERE "dttm" >= to_unixtime(from_iso8601_timestamp('2019-03-27T00:00:00'))
  AND "dttm" <= to_unixtime(from_iso8601_timestamp('2019-04-03T00:00:00'))
ORDER BY "count" DESC
LIMIT 10000;
```

##### ADDITIONAL INFORMATION
 

    [ ] Has associated issue:
    [ ] Changes UI
    [ ] Requires DB Migration. Confirm DB Migration upgrade and downgrade tested.
    [x] Introduces new feature or API
    [ ] Removes existing feature or API
    [ ] Fixes bug
    [ ] Refactors code
    [ ] Adds test(s)

##### REVIEWERS

@xtinec @DiggidyDave @datability-io @khtruong

### CODE REVIEW

**Review by xtinec — APPROVED** [review]
LGTM

**Comment by john-bodley** [comment]
@betodealmeida I don't think this change is valid as a `BIGINT` could represent an epoch timestamp in either seconds or milliseconds. Due to this ambiguity one would need to specify either `epoch` or `epoch_ms` for the `python_date_format`.

Note as part of SIP-15 I plan to add date-time inferencing for non-temporal fields, i.e., string like and numeric which both support multiple date-time encodings.

**Comment by mistercrunch** [comment]
Maybe on `fetch_metadata` we could try and do smart auto-detection based on a sample of the data

**Comment by john-bodley** [comment]
@mistercrunch please see [SIP-21](https://github.com/apache/incubator-superset/issues/7656) which proposes a solution to this.

**Pull request merged**
