### PR TITLE
chore: bump sankey and pivot table chart to 0.17.43

### PR DESCRIPTION
**Pull request by ktmud**
### SUMMARY

Bump superset-ui chart plugins to bring in:

- https://github.com/apache-superset/superset-ui/pull/1089
- https://github.com/apache-superset/superset-ui/pull/1092

cc @serenajiang @kgabryje 

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

See related PR

### TEST PLAN

CI

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by ktmud** [comment]
image

@robdiciuccio This test seems to be a little flaky. I've seen it temporarily failing for multiple PRs. Do you know what could be the cause?

**Review by villebro — APPROVED** [review]
Code LGTM (did not test pulled in changes)

**Comment by robdiciuccio** [comment]
> image
> 
> @robdiciuccio This test seems to be a little flaky. I've seen it temporarily failing for multiple PRs. Do you know what could be the cause?

https://github.com/apache/superset/pull/14497

**Pull request merged**
