### PR TITLE
fix: timestamp bug for chart-powered-query

### PR DESCRIPTION
**Pull request by AAfghahi**
### SUMMARY

This fixes a bug when x-axes are turned on for chart powered queries. 

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

https://user-images.githubusercontent.com/48933336/185489900-ef15e3c3-1300-4efe-8eaf-5952d9950012.mov

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by eschutho — APPROVED** [review]
we're working on a longer-term fix for this. 🙏

**Comment by AAfghahi** [comment]
@eschutho yeah all these conditionals make me sad :(

**Pull request merged**
