### PR TITLE
feat(celery): upgrade celery and its dependencies packages

### PR DESCRIPTION
**Pull request by Musa10**
### SUMMARY
Upgrading celery packages after a lot of bugs in using cache like memory leakes, backend keep requesting async-event api, that have been occured using basic celery configs, and fixed using celery v5.3.6

### TESTING INSTRUCTIONS
Test cache and charts loading with memory usage when loading a dashboard

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [x] Required feature flags:
     GLOBAL_ASYNC_QUERIES:TRUE
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by villebro — APPROVED** [review]
Very cool, thanks for the PR @Musa10 I wasn't aware that Celery moves so quickly; here's the changelog: https://docs.celeryq.dev/en/stable/changelog.html#version-5-3-6. Lots of things have indeed changed since 5.2.2, and I get the feeling 5.3.6 is indeed more stable than 5.2.2, despite those yanked 5.3.2-5.3.4.

**Comment by villebro** [comment]
@dpgaspar @betodealmeida @john-bodley with all these nice improvements in 5.3.6 vs 5.2.2, do you think we should also set the lower bound to 5.3.6, rather than just bump the lock files?

**Comment by villebro** [comment]
Btw, I assume this issue is still unresolved.. 🙁 https://github.com/celery/celery/discussions/7276

**Comment by john-bodley** [comment]
@Musa10 currently your PR only impacts the frozen requirements—typically used for CI—hence if you simply `pip install` Apache Superset (without first installing the frozen dependencies) you’re likely not really “bumping” Celery.

In order to ensure Celery is upgraded for all situations you should increase the lower bound in the `setup.py` file.

**Review by dpgaspar — APPROVED** [review]

**Pull request merged**
