### PR TITLE
fix: ISO code of Île-de-France in france_regions.geojson

### PR DESCRIPTION
**Pull request by AurelienC**
### SUMMARY
Change the value of ISO for Île-de-France from "FR-IDF\t" to "FR-IDF"

### CODE REVIEW

**Comment by rusackas** [comment]
Thank you for this, but if you don't make a change in the jupyter notebook, the geojson you've changed here will be overwritten next time someone runs the notebook. 

Hopefully this helps, but if not, I'd be happy to update it:
https://preset.io/blog/how-and-when-and-why-to-update-apache-supersets-country-maps/

**Review by mistercrunch — APPROVED** [review]

**Comment by mistercrunch** [comment]
Oops disregard my approval I had not seen @rusackas ' comment

**Review by rusackas — CHANGES_REQUESTED** [review]
Blocking here just to make sure the Jupyter notebook gets updated :D

**Comment by AurelienC** [comment]
Thanks, I will have a look!

**Pull request closed without merging**
