### PR TITLE
Fix add chart page translation not work

### PR DESCRIPTION
**Pull request by auxten**
### CATEGORY

Choose one

- [x] Bug Fix
- [ ] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY
the `chart/add` page translation not work, because of:
1. language pack not loaded before render template
2. translator in `preamble.js` only try to get language pack from node `id="app"`

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
before:
image

after:
image

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [x] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by auxten** [comment]
So, any question? further work?

**Comment by willbarrett** [comment]
@dpgaspar can you give this a look?

**Comment by willbarrett** [comment]
Maybe @rusackas would be interested too?

**Comment by auxten** [comment]
No one would give it a look, so sad

**Comment by cdmikechen** [comment]
@auxten sad, too...
另外想咨询下你们也在使用superset做一些本地化的工作吗？

**Comment by JunlinC** [comment]
🏷localization

**Review by mistercrunch — APPROVED** [review]

**Comment by mistercrunch** [comment]
Please rebase!

**Comment by auxten** [comment]
> Please rebase!

done

**Pull request merged**
