### PR TITLE
chore: Renamed changed/created_on to changed/created_at

### PR DESCRIPTION
**Pull request by john-bodley**
### SUMMARY

As part of [[SIP-27] Proposal for Paranoid Deletes](https://github.com/apache/incubator-superset/issues/8639) with the addition of paranoid deletes it seems that, per the SIP, the [`sqla-paranoid`](https://github.com/jeanphix/sqla-paranoid) package would be useful which provides the `deleted_at` column. 

Currently for various audit tables have `changed_on` and `created_on` yet these refer to timestamps as opposed to dates and the tendency is to use `_at` for timestamps and `_on` for dates ([example](https://rubyonrailsthrissur.wordpress.com/2011/04/11/created_at-and-created_on/)). To ensure consistency with `sqla-paranoid` I thought there would be merit in renaming the various `changed_on` and `created_on` columns to `changed_at` and `created_at` respectively. 

I probably should have dug a little further before actioning on this PR as it seems that the auditability comes from FAB which explicitly defines the `changed_on` and `created_on` columns which are used in the `ab_user` table. I'm uncertain how people feel about this change. Note as a work around I needed to make the `AuditMixinNullable` not inherit from `flask_appbuilder.models.mixins.AuditMixin`.

Thoughts @bkyryliuk, @dpgaspar, @villebro, et al?

Note as a side note the `mypy` checks are failing when deprecating the `flask_appbuilder.models.mixins.AuditMixin`. Irrespective of whether we go ahead with said change it's highlighted a number of previously silenced (due to inheritance) typing issues which should be resolved.

### TEST PLAN

CI and manual testing.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [x] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by bkyryliuk** [comment]
@john-bodley I just briefly looked into the https://github.com/jeanphix/sqla-paranoid and it feels to me that reimplementing it could be more straightforward vs migrating superset dbs to follow it's convention. There are only couple hundred lines.

**Comment by john-bodley** [comment]
@bkyryliuk I agree it’s not much work to reimplement, though I do sense `_at` is more accurate than `_on` and thus adheres to other systems.

**Comment by john-bodley** [comment]
@dpgaspar what are your thoughts from a FAB perspective about introducing a breaking change which renames the audit columns from `_on` to `_at`?

**Comment by bkyryliuk** [comment]
> @bkyryliuk I agree it’s not much work to reimplement, though I do sense `_at` is more accurate than `_on` and thus adheres to other systems.

yep, agreed. curious to learn how hard would it be to do this rename in the FAB. It could be a good topic to discuss in slack.

**Comment by villebro** [comment]
I'm not familiar with `_at` vs `_on`, but if it is indeed established convention, I think it's a good change, but I'd prefer to see it happen via FAB. Wrt reimplementing vs using `sqla-paranoid`, I find reimplementing a better alternative in this case, as it doesn't seem to be a very actively maintained project.

**Comment by john-bodley** [comment]
Closing per @bkyryliuk and @villebro's feedback.

**Pull request closed without merging**
