### PR TITLE
chore: revert bignumber.js patch for charts and reapply the original bignumber.js change to SQL editor in an opt-in fashion

### PR DESCRIPTION
**Pull request by xtinec**
##### SUMMARY
This PR does the following:
- Revert "Fix rendering regression from the introduction of bignumber (#6937)"
- Consume the bignumber.js reversion by updating the version of `superset-ui-connection`
- Re-apply the bignumber conversion change (originally from https://github.com/apache/incubator-superset/pull/6591) in `actions/sqlLab.js` (`/results` and `/sql_json` endpoints) where it is needed and make sure the existing unit tests for this still pass.
- Revert "Fix deck.gl form data (#6953)" b/c form data now returns snake_cased properties for deck vizzes.
##### TEST PLAN

- Manually verified that bignumber.js related React runtime warnings in SQL editor (i.e. expecting a number but getting an object) disappeared
- Sanity check in charts and dashboards
##### ADDITIONAL INFORMATION
 

    [ ] Has associated issue:
    [ ] Changes UI
    [ ] Requires DB Migration. Confirm DB Migration upgrade and downgrade tested.
    [ ] Introduces new feature or API
    [ ] Removes existing feature or API
    [ ] Fixes bug
    [x] Refactors code
    [ ] Adds test(s)

##### REVIEWERS
@kristw @williaster @soboko 
cc @betodealmeida @mistercrunch

### CODE REVIEW

**Review by williaster — APPROVED** [review]
I don't have as much context on the Deck.gl changes so probably good for someone else to review that. The big number + `@superset-ui` changes lgtm tho 👍

**Comment by mistercrunch** [comment]
I also have little context on this and this looks a bit scary. Quick reverts are cool, but long standing reverts are dangerous, I dug in and 95 PRs have been merged since #6937, some of these could have built upon assumptions on top of #6937 ...

**Comment by xtinec** [comment]
@mistercrunch planning on pushing ahead. We're going to do a bug bash in staging with this change. There has been a lot of rendering regressions in charts and dashboards since the introduction of `bignumber.js` usage in `superset-ui-connection` in Jan. These regressions are in the core areas of the entirety of Superset. We discussed with the airbnb folks and decided we should do this reversion. 

My thought is addressing the root cause of the past regressions outweighs the possibility of regressing the recent 95 PRs. We'll hopefully uncover any regression to these recent PRs in our bug bash.

**Comment by betodealmeida** [comment]
+1

Go for it, though I agree with Max, we should test some of the things that were added in between. I've had 2 fixes for the time filter that were related to this, eg.

**Pull request merged**
