### PR TITLE
Allow charts to be scrollable

### PR DESCRIPTION
**Pull request by khtruong**
Some charts were not scrollable and prevented users from viewing their entire charts. I set the overflow-x property on the chart container component. This also allows charts to be scrollable on dashboards.

### CODE REVIEW

**Comment by khtruong** [comment]
👀 @xtinec @betodealmeida @kristw @williaster

**Review by kristw — DISMISSED** [review]

**Comment by mistercrunch** [comment]
Historically we've been setting this on the CSS of the charts that are expected to overflow. Have you tested that no unwanted scrollbars appears for all chart types in all contexts?

To minimize the potential impact here I'd do it only on the CSS of the charts that require this.

Is this not working?
https://github.com/apache-superset/superset-ui-plugins/blob/master/packages/superset-ui-legacy-preset-chart-nvd3/src/NVD3Vis.css#L20

**Review by mistercrunch — CHANGES_REQUESTED** [review]
Let's sort out what I pointed out before merging

**Comment by kristw** [comment]
Umm, on second thought @mistercrunch is right. Usually the scrolling logic happens within the chart itself.

**Comment by khtruong** [comment]
> Historically we've been setting this on the CSS of the charts that are expected to overflow. Have you tested that no unwanted scrollbars appears for all chart types in all contexts?
> 
> To minimize the potential impact here I'd do it only on the CSS of the charts that require this.
> 
> Is this not working?
> https://github.com/apache-superset/superset-ui-plugins/blob/master/packages/superset-ui-legacy-preset-chart-nvd3/src/NVD3Vis.css#L20

The div is not assigned a class name for some reason. So then the css rule is not applied to this plain div. I will dig into why the div is not getting assigned.

**Comment by williaster** [comment]
+1 the chart class.

**Comment by khtruong** [comment]
Looks like there is a bug in our release version but this is fixed in the latest master. Going to double check before closing this PR.

**Comment by khtruong** [comment]
> Looks like there is a bug in our release version but this is fixed in the latest master. Going to double check before closing this PR.

Yup, this was the case. Closing PR.

**Pull request closed without merging**
