### PR TITLE
make pivot table number easier to read

### PR DESCRIPTION
**Pull request by yileic**

### CODE REVIEW

**Comment by yileic** [comment]
@xrmx  thank you so much for reviewing!

**Comment by mistercrunch** [comment]
Related:
https://github.com/airbnb/superset/issues/2099

Formatting should be based off the metric's d3format attribute

**Comment by RajkumarKadari** [comment]
Hi  
I tried with different d3 js formats but it's looking data same default format so any options to specify Number Format for Pivot Table visualization type.

**Comment by mistercrunch** [comment]
I mean we should use the formatter defined by the user here:
https://github.com/airbnb/superset/blob/master/superset/models.py#L1064

When configuring a metric you can define how you want it to be formatted, and we should use that. It has to be done on the JS side.

**Pull request closed without merging**
