### PR TITLE
feat(dashboard): add toast feedback to dashboard actions

### PR DESCRIPTION
**Pull request by kgabryje**
### SUMMARY
This PR adds new toast messages as a feedback to user actions in Dashboard.

1. Success toast when user refreshes a chart
2. Success toast when user refreshes a dashboard
3. Success toast when user sets a refresh interval for dashboard
4. Success toast when user edits dashboard properties in Edit mode

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

https://user-images.githubusercontent.com/15073128/150378408-ff0b8711-66ef-404f-b4cb-0692b3b6591c.mov

### TESTING INSTRUCTIONS
Perform the actions listed in summary and verify that success toasts show up

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

CC @yousoph @rusackas 
https://app.shortcut.com/preset/story/35386/dashboards-system-feedback

### CODE REVIEW

**Comment by rusackas** [comment]
@jess-dillard / @kasiazjc if you feel like taking a look to validate from the design side, you can check the ephemeral environment link above. :)

**Comment by jess-dillard** [comment]
@rusackas Looks good to me!

**Review by michael-s-molina — APPROVED** [review]
LGTM

**Pull request merged**
