### PR TITLE
Fix markup broken since cache related changes

### PR DESCRIPTION
**Pull request by mistercrunch**
@graceguo-supercat I mentioned this when we spoke today. It needs to be bundled along other caching-related changes

### CODE REVIEW

**Comment by hughhhh** [comment]
🚢

**Comment by john-bodley** [comment]
@mistercrunch I believe this PR may have introduced a regression. We now see `No data` for a query where the table no longer exists, whereas previously we would have seen something of the form, 
```
line 5:9: Table <cluster>.<schema>.<table> does not exist
```
 which is more informative.

**Comment by michellethomas** [comment]
Also seeing the general `no data` message when we previously would have seen `line 10:7: Column '<column name>' cannot be resolved` which is helpful in debugging the problem.

**Comment by mistercrunch** [comment]
We should add a unit test that covers that proper error message.

**Comment by john-bodley** [comment]
@mistercrunch would you mind proving more context for the reason of this PR so we can further debug and provide a fix with the appropriate unit tests.

**Pull request merged**
