### PR TITLE
fix: Add Omnibar Feature Flag

### PR DESCRIPTION
**Pull request by hughhhh**
### SUMMARY

Adding feature flag for users to enable omnibar in their environment

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by willbarrett — APPROVED** [review]
LGTM once tests pass.

**Comment by ktmud** [comment]
If the feature is already added, could you link the PR where it was added? Thanks!

**Comment by ktmud** [comment]
Is it #6745 ?

**Comment by hughhhh** [comment]
@ktmud yea that's the initial feature PR

**Pull request merged**
