### PR TITLE
[dashboard v2] tests!

### PR DESCRIPTION
**Pull request by williaster**
This PR adds a ton of tests for the new dashboard app. I have a few more todo (enumerated below), but wanted to make a PR to start getting an idea of coverage.

@graceguo-supercat

TODO

- [x] fix old Dashboard tests
- [x]  add reducer tests
- [x] add action tests

### CODE REVIEW

**Comment by williaster** [comment]
ping @graceguo-supercat

**Comment by williaster** [comment]
javascript tests are passing 🎉 we might need to rebase the `dashboard-builder` branch on master to fix the `py36-sqlite` + `py36-postgres` tests

**Comment by graceguo-supercat** [comment]
I only see filters related tests for `componentDidUpdate`. We should also test dashboard's default_filters are pre-populated.

**Comment by williaster** [comment]
abandoning because of a weird git state. see #5066

**Pull request closed without merging**
