### PR TITLE
docs(databases): Update pinot.mdx to incorporate username and password based connection.

### PR DESCRIPTION
**Pull request by raamri**
### SUMMARY

Updating the documentation to incorporate the username and password based sql for connecting to Apache Pinot.

### TESTING INSTRUCTIONS

N/A.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by sfirke** [comment]
Hi and thanks for this!  I thought "I know someone shared this in Slack, I'll compare them" -- and then I realized I think that was you 😁 

In your Slack config it began simply `pinot://`, here you have `pinot+http` -- is that +http needed?  And in Slack you ended it `&verify_ssl=true` instead of a trailing slash.

**Comment by sfirke** [comment]
Looks like linting check failed due to:
>  Error: Please format your PR title to match: `^(build|chore|ci|docs|feat|fix|perf|refactor|style|test|other)(\(.+\))?(\!)?:\s.+`!

Can you change the PR title to begin `docs(databases): ` ?

**Comment by raamri** [comment]
Hi @sfirke sfirke! Updated the PR title and the doc based on your suggestions.
1. verify_ssl=true is actually needed.
2. +http is not needed. Adding that would also do no harm though. Still, removing it.
Thanks!

**Review by sfirke — APPROVED** [review]
Looks good to me!

**Comment by sfirke** [comment]
thanks @raamri !

**Pull request merged**
