### PR TITLE
build: use GitHub Actions concurrency groups to cancel workflows

### PR DESCRIPTION
**Pull request by sebastianliebscher**
### SUMMARY
This PR removes custom scripts to cancel running GitHub Actions workflows and replaces them with the built-in functionality [concurrency groups](https://docs.github.com/en/actions/using-jobs/using-concurrency#overview).

This will cancel all running workflow jobs for PRs only. In case it is not a PR, this won't cancel running jobs as `run_id` is unique.
```
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true
```

Partially reverts https://github.com/apache/superset/pull/12090

---

In case we want to cancel running jobs for commits to master or release tags also, it can be modified to:
```
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
```

https://docs.github.com/en/actions/learn-github-actions/contexts#github-context

### TESTING INSTRUCTIONS
You can see the cancelled workflows for the first commit:
image

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by villebro** [comment]
@sebastianliebscher nice work, looking forward to reviewing this once it's out of draft state!

**Comment by sebastianliebscher** [comment]
ping @villebro

**Comment by mistercrunch** [comment]
LGTM, let's rebase and merge it!

**Review by rusackas — APPROVED** [review]

**Comment by mistercrunch** [comment]
Thank @sebastianliebscher for the idea/code, took over here -> https://github.com/apache/superset/pull/26945 closing this one

**Pull request closed without merging**
