### PR TITLE
chore: Improves the native filters bar layout

### LINKED ISSUE #14973: [native-filters]expanding filter bar should push top-level tabs along with main dashboard to the right
https://user-images.githubusercontent.com/67837651/120715264-3ab59e00-c479-11eb-9ed0-aa98238b1b85.mov

Screen Shot 2021-06-03 at 2 35 29 PM

@michael-s-molina @villebro 🙏

### LINKED ISSUE #15002: [native-filters]make filter bar top section sticky on scroll
Screen Shot 2021-06-04 at 6 01 28 PM

### PR DESCRIPTION
**Pull request by michael-s-molina**
### SUMMARY
Improves the native filters bar layout.
- Makes the filter bar header stick to the top while scrolling
- Fixes the filter bar rendering when closing the filters after scrolling
- Moves the filter bar scroll from the panel to each tab
- Adjusts the padding of the header and filters
- Increases the padding and spacing of Filter Sets elements 
- Replace react-sticky with CSS to increase performance
- Adjusts the tests
- Renames the modal

Fixes https://github.com/apache/superset/issues/14973
Fixes https://github.com/apache/superset/issues/15002

@villebro @rusackas @kgabryje @junlincc 

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
https://user-images.githubusercontent.com/70410625/121681083-b7a3d180-ca90-11eb-8ba8-ddd913819d34.mov

https://user-images.githubusercontent.com/70410625/121681039-aa86e280-ca90-11eb-9ace-12dfee3cb9e0.mov

### TESTING INSTRUCTIONS
See before/after videos for instructions.

### ADDITIONAL INFORMATION
- [x] Has associated issue:
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by villebro** [comment]
The expand arrow here looks slightly lonely after the "Superset" header has scrolled out of view:
1) unscrolled (looks ok):
image

"Superset" header out of sight (looks lonely):
image

It might look better if it scrolled together with the nearby chart, and only got stuck after the whole "Superset" header has scrolled out of view.

**Comment by kgabryje** [comment]
Wow, that looks SO much better than before! Thanks for that change. Could we move the "expand" icon up when filters are collapsed? I don't think it should change it's position that much compared to when the filter bar is expanded

**Comment by villebro** [comment]
When the "Superset" header has scrolled out of view, a grey area is exposed on the bottom. This grey space could potentially show additional native filters that are now hidden (we should be able to show "p" (partly exposed) and even "q" (fully hidden) here:
image

**Review by villebro — APPROVED** [review]
LGTM - what an incredible improvement to the native filter experience! 🎉

**Comment by akramovoybekjon147-netizen** [comment]
Does this fix cover the horizontal filter bar layout as well, or only the vertical filter bar? Looking at the diff, the sticky behavior seems to be implemented specifically for the vertical FilterBar/Header components via CSS + the new useElementOnScreen hook — it's not clear it applies when the filter bar orientation is set to horizontal. Would be great to have the header stick to the top while scrolling in horizontal mode too, since it currently scrolls out of view with the rest of the page.

**Pull request merged**
