### PR TITLE
build(helm): Helm-docs + fix Helm chart release

### PR DESCRIPTION
**Pull request by Yann-J**
### SUMMARY

This PR implements 2 improvements to the releasing of Helm chart:
- Support for running [helm-docs](https://github.com/norwoodj/helm-docs) to generate a README for the chart, automatically generated from the `Chart.yaml` and annotated `values.yaml`. It will be enforced both as a `pre-commit` check, as well as a CI check.
- Fix the helm `chart-releaser` action which seems broken due to missing dependency on the bitnami chart repo (which prevented the release of the updated chart from #21806 ) - this may need some trial & error to confirm a successful release.

This PR includes a (useless) bump of the chart version to force the CI to go through a Helm release.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

See [generated Chart](https://github.com/one-acre-fund/superset/tree/helm-docs/helm/superset) `README`:

image

### TESTING INSTRUCTIONS

- For the `helm-docs` pre-commit:
  - Check out project
  - Update pre-commit (`pre-commit install`)
  - Make some chart update (e.g. bump up the version in `Chart.yaml`) and stage the change
  - Try to commit. Git should raise an error complaining that a pre-commit check has failed
  - Run `pre-commit run helm-docs` to force execute the helm-docs generation, stage the resulting change and commit again
- For the chart releaser fix: merge the PR and hope for helm chart v0.7.6 to be released!

### ADDITIONAL INFORMATION
- [x] Has associated issue: #21806 (merge failed to release)
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by craig-rueda — APPROVED** [review]

**Comment by Yann-J** [comment]
Hmm, struggling a bit to set up `helm-docs` in CI, because of https://github.com/actions/runner-images/issues/6283

Should be OK now with latest commit, let's see when CI completes...

**Comment by Yann-J** [comment]
Alright @craig-rueda after much tweaking I have the CI now fairly clean!

I finally opted not to run a separate Github action to check for `helm-docs`, since I see that CI will anyway run all the `pre-commit` checks, so these alone are enough. It was slightly harder than it should be, because of the above mentioned issue that makes using `brew` a bit harder on Github machines.

There is still a CI failure with one of the cypress e2e tests, but I can see it's a known [flaky test](https://dashboard.cypress.io/projects/ukwxzo/analytics/flaky-tests/5201715e-e599-44ed-3368-c24dfbd9d03b-be408a3c-4249-d66a-22a1-010d2436d341), and is very unlikely to be related to the changes in this PR.

Note that since this would (hopefully) be the first successful helm chart release since #20722 this should also force the metadata refresh in [artifacthub](https://artifacthub.io/packages/helm/superset/superset), and enable the 'verified publisher' badge.

**Comment by craig-rueda** [comment]
Awesome, thanks for this! Ready to merge?

**Comment by Yann-J** [comment]
Yes I think we're good!

**Comment by Yann-J** [comment]
Perfect, chart succesfully released, and the [artifacthub page](https://artifacthub.io/packages/helm/superset/superset) now has icon, docs, and Verified badge!

image

**Pull request merged**
