### PR TITLE
feat(chart): Added Latvia to countries map

### PR DESCRIPTION
**Pull request by maleksan**
### SUMMARY
Added Latvia to countries map

### SCREENSHOTS
New map in Country Map viz:
image

Updated notebook:
image
image

### TESTING INSTRUCTIONS
Clone the repo and go to its root directory. Run the following shell commands:

cd superset-frontend && npm install
npm run plugins:storybook

### CODE REVIEW

**Comment by villebro** [comment]
Thanks for this @maleksan ! Could you add a screenshot to the description showing the map in action?

**Comment by maleksan** [comment]
> Thanks for this @maleksan ! Could you add a screenshot to the description showing the map in action?

Added. Please add this new LV map into the next release.

**Comment by villebro** [comment]
> > Thanks for this @maleksan ! Could you add a screenshot to the description showing the map in action?
> 
> Added. Please add this new LV map into the next release.

Hi, I mostly meant showing a screenshot of the new map in Superset, not the notebook. Also, if you don't mind, please add the notebook changes to this PR so it's up to date.

**Comment by maleksan** [comment]
> > > Thanks for this @maleksan ! Could you add a screenshot to the description showing the map in action?
> > 
> > 
> > Added. Please add this new LV map into the next release.
> 
> Hi, I mostly meant showing a screenshot of the new map in Superset, not the notebook. Also, if you don't mind, please add the notebook changes to this PR so it's up to date.

- Sorry, there will be no opportunity to make a build to demonstrate this to you in the near future.
- Notebook changes added.

**Comment by villebro** [comment]
> * Sorry, there will be no opportunity to make a build to demonstrate this to you in the near future.
> * Notebook changes added.

@maleksan I spun up test env and verified that the chart works as expected and added a screenshot to the description.

**Review by villebro — APPROVED** [review]
Thanks for adding this! 🇱🇻

**Comment by maleksan** [comment]
@villebro,
is it possible to add this feature into the nearest Superset release?

**Comment by villebro** [comment]
@maleksan I believe this is included in the current 2.1.0 release candidate that's up for vote

**Pull request merged**
