### PR TITLE
fix: Race conditions with setupExtensions

### PR DESCRIPTION
**Pull request by geido**
### SUMMARY
Fixes an issue for which the setupExtensions would cause unwanted race conditions when extending components.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
N.A.

### TESTING INSTRUCTIONS
All tests should pass

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by michael-s-molina — APPROVED** [review]
LGTM. Can we get also get @eric-briscoe or @samtfm approval before merging it?

**Review by rusackas — APPROVED** [review]
We have too many apps!!! But that's another problem. Thanks for this!!

**Comment by rusackas** [comment]
We should probably rename `superset/superset-frontend/src/profile/components/App.tsx` if that's not yet another React app. It's a little disingenuous ;)

**Review by jinghua-qa — APPROVED** [review]
deployed to a preset workspace and tested preset extension and feature flag related feature, did not find any issue. LGTM!

**Pull request merged**
