### PR TITLE
feat(build): uplift Storybook to v8

### PR DESCRIPTION
**Pull request by hainenber**
feat(build): uplift Storybook to v8

### SUMMARY

Uplift Storybook used in `superset-frontend` to latest version as of now (v8). I ran `npm run storybook build-storybook plugins:build-storybook plugins:storybook` and check most stories are OK except for a few stories seemingly to fail before the Storybook uplift

- `legacy-chart-plugins-legacy-preset-chart-nvd3-pie--basic`
image

- `legacy-chart-plugins-legacy-plugin-chart-paired-t-test--basic`
image

### TESTING INSTRUCTIONS

All stories executed by `npm run storybook` and `npm run plugins:storybook` must be successful.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by rusackas — APPROVED** [review]
Thanks for this. I do see some broken and misbehaving stories, but as far as I can tell, they look like the same ones we got as a byproduct of bumping to Storybook 7. I don't see anything materially different. Hopefully we can fix some of these stories over time and make the world a better place. In the meantime, this looks like progress to me!

Just looks like it needs a new npm lock file to be mergeable.

**Comment by hainenber** [comment]
The lockfile is synced now :D

Hopefully no new pkg change incoming 😝

**Comment by hainenber** [comment]
Yikes, looks like my attempt at reconcilating the lockfile didn't work. 1 moment please 🎶

**Comment by hainenber** [comment]
PR is merge-able now :D

**Comment by rusackas** [comment]
I think this is good to move forward, but we'll need a code owner review (probably due to the Metadata Bar component) from @michael-s-molina @kgabryje or @geido to merge this.

**Comment by hainenber** [comment]
hi Superset folks, anything I can do to have this merged?

**Comment by rusackas** [comment]
Pinging those three folks again on Slack... hopefully we can get a code owner stamp soon.

**Review by michael-s-molina — APPROVED** [review]

**Pull request merged**
