### PR TITLE
docs: Small typo fix in Athena connection docs

### PR DESCRIPTION
**Pull request by lamielle**
### SUMMARY
Small typo fix in Athena connection docs

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by etr2460 — APPROVED** [review]
Nice catch, thanks for the fix!

**Comment by lamielle** [comment]
> Nice catch, thanks for the fix!

No problem!  Was just reviewing some docs for setting up Athena and noticed the typo.  Let me know if you need anything else before this can be merged.

**Comment by etr2460** [comment]
Nope, had to rerun CI (unfortunately we've had some flakey Cypress tests lately) but it should be good to merge now.

Note that you won't see the update in our docs site until we do another docs site deployment. I'm actually not sure if we have a regular cadence for that, maybe @srinify or @pkdotson knows?

**Comment by lamielle** [comment]
Makes sense @etr2460, thanks for the quick turnaround on getting this merged!

**Pull request merged**
