### PR TITLE
chore(🤖): bump python "flask==2.3.3"

### PR DESCRIPTION
**Pull request by mistercrunch**
Updates the python "flask" library version. 

Generated by @supersetbot 🤖

### CODE REVIEW

**Review by dpgaspar — COMMENTED** [review]
Looks like push and pop were deprecated and removed on 2.3.0: https://flask.palletsprojects.com/en/2.3.x/changes/#version-2-3-0

https://github.com/pallets/flask/pull/4682

**Comment by mistercrunch** [comment]
Trying to get gpt to fix this one...

**Comment by mistercrunch** [comment]
@dpgaspar I fix the failing test wdyt!?

**Review by dpgaspar — APPROVED** [review]
LGTM

**Pull request merged**
