### PR TITLE
fix: trying to fix LOAD_EXAMPLES in ephemeral envs

### PR DESCRIPTION
**Pull request by mistercrunch**
title ^^^

Using `workflow_dispatch` to trigger using ` gh workflow run ephemeral-env.yml --ref eph_env_fix`

### CODE REVIEW

**Comment by mistercrunch** [comment]
first try logs: https://github.com/apache/superset/actions/runs/10493768010/job/29068509569

**Comment by rusackas** [comment]
Is this one of those cases where we have to merge it to see if it works?

**Comment by mistercrunch** [comment]
Yeah it's confusing, I think it runs the main branch's corresponding action, not the one from this PR/branch

**Comment by michael-s-molina** [comment]
@mistercrunch Please check https://github.com/apache/superset/pull/29993

**Comment by mistercrunch** [comment]
> Please check https://github.com/apache/superset/pull/29993 as it fixed the load examples problem in ephemeral envs.

done-im-done

**Comment by mistercrunch** [comment]
Closing for now, might re-start from here if issues with eph-envs show up again. Really hard to work on this stuff in the GHA / missing-secrets-locally context. Though next time I might try a `supersetbot` approach

**Pull request closed without merging**
