### PR TITLE
fix(charts): Time range filters are not being applied to charts that were overwritten

### PR DESCRIPTION
**Pull request by Antonio-RiveroMartnez**
### SUMMARY
When `GENERIC_CHART_AXES ` FF is on and we overwrite a chart, any filter coming from the dashboard is not saved (it gets removed since its marked as `isExtra`). However, removing such filter doesn't have to mean we delete the original temporal filter if any, otherwise the dashboard wont be able to filter the chart again.

This PR keeps the original `adhoc_filters` from the slice so when calling the PUT API it doesn't get removed. So any call to  `api/v1/dashboard/{db_id}/charts` is consistent even after you overwrite the chart.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Before:
error

After:
test

### TESTING INSTRUCTIONS
1. Make sure `GENERIC_CHART_AXES` FF is ON
2. Create a chart and add it to a dashboard.
3. Add a time range filter to the dashboard and apply any value.
4. Click on the chart title to access it in the Chart Builder menu.
5. Overwrite the chart (no changes are needed).
6. Go back to the dashboard, and apply any time range filter.
7. The filter must keep working after overwriting the chart

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [X] Required feature flags: `GENERIC_CHART_AXES`
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by eschutho — APPROVED** [review]
LGTM!

**Review by geido — APPROVED** [review]

**Comment by justinpark** [comment]
@Antonio-RiveroMartnez There's a regression from this change.
With this change, user cannot remove the applied adhoc_filters. (Please see the following video. It keeps reverting back the filter option)

https://github.com/apache/superset/assets/1392866/497db3a0-6f72-45d4-800f-fd77da478da9

**Comment by Antonio-RiveroMartnez** [comment]
Hey @justinpark thanks for letting me know. I will have a look as soon as possible 😎

**Pull request merged**
