### PR TITLE
[DISCUSS] - Moves the SQL Lab menu before Charts

### PR DESCRIPTION
**Pull request by michael-s-molina**
### SUMMARY
Moves the SQL Lab menu before Charts to make it workflow-oriented. Generally, the most common workflow is:
1. to connect with database in Data, Persona: Data scientist. 
2. to explore raw data, cleanup and restructure data if needed, prepare data for exploration by creating virtual datasets in SQL Lab, etc, Persona: Data scientist 
3. to explore, slice, and dice data, and to create charts for a dashboard in Explore(Chart); Persona: Data analyst
4. to view and edit dashboard in Dashboard Persona: Business analyst/business users.

The other possibility is to reorder the objects by usage, and the order would be the opposite. Dashboards -> Charts -> SQL Lab -> Data. This argument may seem counterintuitive to DS, as DS spends the majority of their time handling data. But the number of dashboard consumers is way larger than dashboard creators in large enterprises.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Screen Shot 2021-07-27 at 1 53 24 PM

Screen Shot 2021-07-27 at 3 56 43 PM

@junlincc @rusackas 

### TESTING INSTRUCTIONS
- Login to Superset
- Check the main menu

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by john-bodley** [comment]
@michael-s-molina would you be able to document the motivation for the change?

**Comment by ktmud** [comment]
Please make sure PR description has enough context.

**Comment by graceguo-supercat** [comment]
In airbnb, SQL users and Dashboard creation users are overlapped but not same group of people. Many users come to superset only for SQL Lab.  This change is minor, but still might make them feel inconvenient and confused. Could you provide more reason for this change? thanks!

**Comment by michael-s-molina** [comment]
@john-bodley @ktmud I'll check with @junlincc and @rusackas about the change and provide more context in the PR's description.

**Comment by junlincc** [comment]
Hi @john-bodley 
We are trying to clearing some low-hanging fruit that previously discussed with Cartel, and approved in SIP-34. 
Menu items in the top nav bar historically were not arranged in any particular order. We re-ordered the nav menu once last year and re-organize items in the sub menu as first step.  

In the research with Cartel, the designer suggested that we can either arrange it by user's work flow, which is 1. to connect with database in **Data**, Persona: Data scientist. -> 2. to explore raw data, cleanup and restructure data if needed, prepare data for exploration by creating virtual datasets in **SQL Lab**,  etc, Persona: Data scientist -> 3. to explore, slice and dice data, and to create charts for dashboard in **Explore(Chart)**; Persona: Data analyst ->4. to view and edit dashboard in **Dashboard** Persona: Business analyst/business users. 
The other idea is to reorder the objects by usage, and the order would be the opposite. Dashboards-> Charts->SQL Lab->Data. This argument may seems counterintuitive to DS, as DS spend majority of their time in handling data. But the number of dashboard consumers is way larger than dashboard creators in large enterprises. 

Given the current order, Data -> Charts -> Dashboards -> SQL lab, it seems to be less disruptive if we reorder by workflow.


We also did some user research in-house to validate our assumption, it's not directly related but could use it as a support document.  

https://docs.google.com/presentation/d/182UJeK4y-BhcYkWJWYTJSA-O2_2LOXDYoAANi76-uBQ/edit#slide=id.g9743bec153_1_113

**Comment by michael-s-molina** [comment]
Thanks for your comment @junlincc!

@john-bodley @ktmud @graceguo-supercat I updated the PR's description with Junlin's comments. We are trying to establish the most suited workflow for the majority of organizations using Superset. 

Do you agree with the change?

**Comment by ktmud** [comment]
Personally I think it'd make more sense to order by usage than workflow:

1. **Most users don't need the full workflow:** even for Data Scientists, they seldom work through the whole workflow in one go---IMO having the full workflow in the right order is less important than having easiest access to the most used steps in the workflow.
2. **Different users have different workflows:** "Data -> SQL Lab -> Chart -> Dashboard" is just _one_ workflow of _some_ Data Scientists. Some more frequent workflows are:
   1. "Chart -> Dashboard"---for Data Scientists who only use pre-configured and shared datasets (which is probably something Superset should encourage), in which case one may argue the Data tab should be hidden into "Settings" (like [Redash](https://redash.io/help/user-guide/getting-started) does).
   2. "Dashboard -> Chart -> SQL Lab"---for dashboard viewers who are also interested in how the underlying data were computed. This is somewhat similar to Looker's "Browse -> Explore -> Develop".
3. **The order is less important in the main menu:** while having the right order is important in some places, it's not like users can return to previous steps by clicking on the main menu.
4. **Home page already orders content by usage:** it's better be consistent than not.

I went back and checked, [SIP-34](https://github.com/apache/superset/issues/8976) actually re-arranged the menu by usage order (Dashboards -> Charts -> SQL Lab -> Data). There must be some reason behind that---hope it was in line with what I described above.

**Comment by junlincc** [comment]
@ktmud i agree. those routes you mentioned are validated in our research as well. 
I personally don't have a strong preference of arranging the order by "Dashboards-> Charts -> SQL lab -> Data" or the other way around, as long as SQL lab is being placed in AN order. I know that this module was added separately and organically before without any design thinking. 
Looks like we have reached an agreement here. I'm happy to change in order to move this PR forward :)

**Comment by michael-s-molina** [comment]
@junlincc @ktmud Thanks for your comments.

@junlincc @ktmud @srinify @john-bodley @graceguo-supercat 
Can we proceed and make the change to follow [SIP-34](https://github.com/apache/superset/issues/8976) order?
Dashboards -> Charts -> SQL Lab -> Data

**Comment by ktmud** [comment]
I think both "Dashboards -> Charts -> SQL Lab -> Data" and "Dashboards -> Charts -> Data -> SQL Lab" make sense and don't have a strong preference of either.

The former is in line with the order by usage, but although `SQL Lab` may be more frequently used than `Data` overall, a lot of users almost never use either. For users do use SQL Lab directly from the main nav, it's a very separate workflow and they tend to use it a lot. So Keeping it as the last item also makes sense.

**Comment by junlincc** [comment]
@michael-s-molina please reopen the PR and proceed the change with below order. 
Dashboards -> Charts -> SQL Lab -> Data

thanks for everyone's discussion

**Comment by michael-s-molina** [comment]
> @michael-s-molina please reopen the PR and proceed the change with below order.
> Dashboards -> Charts -> SQL Lab -> Data
> 
> thanks for everyone's discussion

@junlincc I opened a [follow-up PR](https://github.com/apache/superset/pull/15929) to preserve the original description and screenshots of this PR. Both PRs are referencing each other.

**Comment by ktmud** [comment]
Before we go, I'd also like to vent out something that has been brewing in my mind for a while. I've noticed many times that whenever there is a disagreement in UX changes, there is the argument that "we are doing this for the broader Superset community/the majority of Superset users", or the so-called "business users". To me, this argument feels counterproductive.

As shown above, there can be many more substantive arguments about either side of each choice. Even if you made a decision with your version of "the majority of users" in mind, it's possible that there are the other side of the coin or some deal-breaking edge cases not factored into the decision-making process. We raise our concerns based on what _our users_ tell us (and years of experience of dealing with real Superset users), too. It's quite discouraging to have to defend these concerns as if they were only of the interest of a small group.

Let's focus on the substance and make sure all future PRs have logical and thorough reasoning clearly stated BEFORE they are up for review. "We think this is better for new/most users" is not good enough.

**Comment by junlincc** [comment]
I agree we should have a better flow for communicating and implementing UI/UX changes, and we will make sure it happens soon. 
FYI This change may seem recent, but the actual research that was done to support this change happened last year, 80% of our datapoint is actually collected from airbnb users last year, and if not all, most of the interviewee agreed with changing the order, and the research summary is in 
https://docs.google.com/presentation/d/182UJeK4y-BhcYkWJWYTJSA-O2_2LOXDYoAANi76-uBQ/edit 
2 Preset designers and I each talked to 6-7 users, connected by @zuzana-vej.

@graceguo-supercat @ktmud @john-bodley @willbarrett @kristw

**Pull request closed without merging**
