### PR TITLE
fix: timer component, fixes #10849, closes #11002

### LINKED ISSUE #10849: Timer in SQL Lab and Explore doesn't work
The timer in SQL Lab doesn't work. When you run the query 1st time, it shows some number (unsure if accurate). When you run a query 2nd time the value on the timer doesn't change. 

### Expected results
The timer should reset every time user hits the "RUN" button, and start counting again from 0. 

### Actual results

Timer is stuck.

#### Screenshots

Step 1: Running 1st query: (timer has some result, which looks inacurate, the query took longer than 0.67 sec
sqllab-timer-bug
Timer detail:
Screen Shot 2020-09-11 at 5 55 40 PM

Step 2: Change to different SQL Lab tab and run 2nd query: 
step1
Timer detail:
Screen Shot 2020-09-11 at 5 56 02 PM

See query is running - timer value doesn't change
step2
Timer detail:
Screen Shot 2020-09-11 at 5 56 08 PM

Query finished and returned result - timer is still displaying same value as before hitting RUN button:
steap3
Timer detail:
Screen Shot 2020-09-11 at 5 56 13 PM

#### How to reproduce the bug

1. Go to SQL Lab
2. Click on RUN query
3. See the timer and whether it changes
4. Run query again, see the timer and whether it changes

### Environment

- superset version: `latest`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by ktmud**
### SUMMARY

Fixes #10849 introduced by #10455 . Closes #11002 .

I did testing locally. Will add some integration tests shortly.

cc @nytai @graceguo-supercat @etr2460 @tanmaylaud 

### ADDITIONAL INFORMATION

- [x] Has associated issue: see SUMMARY
- [x] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by nytai — APPROVED** [review]
lgtm, thanks for reasoning through this

**Comment by graceguo-supercat** [comment]
Thanks for the quick fix! i tested locally and it is working good. I will close the revert PR and favor this !

**Comment by zuzana-vej** [comment]
Yay thanks @ktmud

**Review by graceguo-supercat — APPROVED** [review]
LGTM

**Comment by ktmud** [comment]
@nytai @graceguo-supercat Just did a little more refactoring and added a Cypress test for this bug. I also tested it with the buggy `master` branch and the test case consistently fails. Lmk if it still looks good.

**Comment by nytai** [comment]
looks even better to me! 😄

**Comment by ktmud** [comment]
The Cypress test keeps failing in CI. Skip it for now to unblock merging.

**Pull request merged**
