### PR TITLE
Skip flaky cypress dashboard test

### PR DESCRIPTION
**Pull request by mistercrunch**
This one has been biting us for a while. Let's disable for now.

### CATEGORY

Choose one

- [X] Build / Development Environment

### CODE REVIEW

**Comment by graceguo-supercat** [comment]
what is error when it failed? i will watch this issue and try to fix test.

**Comment by mistercrunch** [comment]
I think I just see a timeout. Yes, let's actually fix the unit test!

**Comment by graceguo-supercat** [comment]
@mistercrunch I saw 2 failed build:
https://travis-ci.org/apache/incubator-superset/builds/534229656
https://travis-ci.org/apache/incubator-superset/builds/534083200
And saw these 2 are failed from same error. So I made a PR to fix this error: #7552.
I will still keep watching for any other error message.

**Comment by mistercrunch** [comment]
Superseded by #7552

**Pull request closed without merging**
