### PR TITLE
[cli] force update perms on superset init

### PR DESCRIPTION
**Pull request by mistercrunch**
I set up a new environment today, while I kept my `superset_config.py` that happen to contain `os.environ['SUPERSET_UPDATE_PERMS'] = '0'`.

This prevented `superset init` from creating the right perms, which can be confusing, so this here forces `superset init` to disregard `SUPERSET_UPDATE_PERMS`

👀 @john-bodley

### CODE REVIEW

**Comment by john-bodley** [comment]
@mistercrunch any reason you wouldn't have `SUPERSET_UPDATE_PERMS` = `True`  in this case?

**Comment by mistercrunch** [comment]
That would work too if you mean `os.envrion['SUPERSET_UPDATE_PERMS'] = '1'`

**Comment by john-bodley** [comment]
[Here](https://github.com/apache/incubator-superset/blob/64459efebda88cc147eacb14308d2b3e587899ef/superset/utils.py#L773) is the logic for parsing the environment variable.

**Comment by mistercrunch** [comment]
@john-bodley the code I added here is in that same method. What this does is if running `superset init`, that method always returns `True`

**Comment by john-bodley** [comment]
Agreed, I guess what I'm saying is I'm not certain whether we want to always ensure that `superset init` overrides the logic of the `SUPERSET_UPDATE_PERMS` environment variable or whether one should run it via, 
```
SUPERSET_UPDATE_PERMS=1 superset init
```
as defined [here](https://github.com/apache/incubator-superset/blob/master/docs/installation.rst#flask-appbuilder-permissions). Note the default return value of `get_update_perms_flag` is `True` is the environment variable is undefined.  

I also don't know what the precedence is of whether setting environment variables in config files is recommended. Historically it seems we only read from them to augment the configuration.

**Pull request closed without merging**
