### PR TITLE
fix: Bar chart order

### PR DESCRIPTION
**Pull request by geido**
### SUMMARY
The goal of this PR is to fix the order of the Bar chart

### BEFORE

https://user-images.githubusercontent.com/60598000/154296688-96327e55-73d1-42f6-a41e-7137fce73b8b.mp4

### AFTER

https://user-images.githubusercontent.com/60598000/154297218-6815a418-793c-49a2-b66b-08b6abaf981c.mp4

### TESTING INSTRUCTIONS
1. Open the sample Total Sales per Market (Grouped by Genre) Bar chart
2. Add a sort by metric
3. Make sure the order is correct

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by jinghua-qa** [comment]
I found an issue that the when i put different sort by values, the order still stay the same. For example, i use sort by sum(na_sales )and sum(eu_sales), the series are in the same order, and it is not in the order of what i selected.
Screen Shot 2022-02-18 at 12 53 02 AM
Screen Shot 2022-02-18 at 12 53 45 AM

I think the current behavior on master is making more sense, when i select sort by sum(na_sales), the bar series show in order sum. 
For example sort by sum(na_sales)
Screen Shot 2022-02-18 at 1 11 17 AM
Screen Shot 2022-02-18 at 1 13 08 AM

**Review by jinghua-qa — COMMENTED** [review]
I think the sort by is not correct in the bart, but the sort by work on the data table. I am expecting the order of the bar is same as the order of the data table

**Comment by geido** [comment]
@jinghua-qa I think there is a bit of confusion around the original issue. I agree with you that my method here isn't following the order in the data panel and that looks incorrect. Is there an actual problem that you are identifying with the sorting on master right now, or am I trying to fix a problem by creating one? 🤦

**Pull request closed without merging**
