### PR TITLE
build(cypress): Fix issue with cypress code-coverage plugin when running locally

### PR DESCRIPTION
**Pull request by robdiciuccio**
### SUMMARY
This PR:
- Updates `@cypress/code-coverage` plugin to latest version
- Reverts failing test assertions introduced in https://github.com/apache/incubator-superset/pull/11613
- changes the code coverage reporting format as a workaround for the following issue when running locally:

```
CypressError: `cy.task('coverageReport')` failed with the following error:
> Cannot read property 'loc' of undefined
```

Refs: 
https://github.com/cypress-io/code-coverage/issues/216
https://github.com/istanbuljs/istanbuljs/issues/572

### TEST PLAN
Run Cypress locally

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by robdiciuccio** [comment]
Code coverage reporting output:

Screen Shot 2020-11-13 at 1 14 49 PM

This appears after each test file, but getting this to run after the suite was heading into a rabbit hole, so deferred for now.

**Review by Kamh1234566 — APPROVED** [review]

**Comment by ktmud** [comment]
I think this just disabled code coverage report for https://codecov.io/

**Comment by ktmud** [comment]
Can you try

```js
  "nyc": {
    "reporter": ["text-summary", "json"]
  }
```

**Review by ktmud — APPROVED** [review]

**Comment by mistercrunch** [comment]
Side note, have you all noticed that cypress' reported line numbers are off? Somehow the sourcemap must be wrong for cypress.

**Pull request merged**
