### PR TITLE
Pypi has a 60mb package size limit, and we're over

### PR DESCRIPTION
**Pull request by mistercrunch**
* removing india country map which is 12MB+
* removing src/ in general, keeping the countries folder which has geo
data

### CODE REVIEW

**Comment by kristw** [comment]
I saw that you previously excluded all the large thumbnails. 

```
recursive-exclude superset/static/images/viz_thumbnails_large *
```

These large thumbnails were recently moved to vis-specific folders under `src/visualizations` so the exclusion rule above does not get rid of the thumbnail images. I wonder if that is the reason why the package size becomes larger. Just trying to see if there is a workaround that you don't have to delete India.

**Comment by mistercrunch** [comment]
Oh, all of `superset/static/assets/src` except for `superset/static/assets/src/visualizations/CountryMap/` is now excluded. 

It's a bit confusing, but it's a mixed set of `recursive-exclude` AND `recursive-include`

**Review by hughhhh — APPROVED** [review]
🚢

**Comment by aboganas** [comment]
We should put maximum limit on the size of country maps, something like 400kb. I don't think we need most details on country maps especially that it usually used to represent provinces or states. 

If you wan't, I can try on my spare time reduce the size of Json maps and add more countries

**Comment by mistercrunch** [comment]
Agreed, a few other things:
* we could gzip the files, de-gzip on the client
* should move the files to `static/data/geo` or something like that, then that needs to be in the manifest, really shouldn't be in `src/` ...
* that's more complicated, but we've been talking about how it should live in the database instead, @betodealmeida and I have been speaking about having some sort of GeoShape-related models

**Review by ghost — COMMENTED** [review]
Please stop sending me emails

**Pull request merged**
