### PR TITLE
chore(style): Enforce optional chaining

### PR DESCRIPTION
**Pull request by rusackas**
### SUMMARY
Just saw [this](https://github.com/apache/superset/pull/21232#pullrequestreview-1089724190) comment on a PR today. I see and write comments like this all the time, so let's just make it a rule!

This PR turns on enforcement around optional chaining. It also fixes the 58 or so errors that resulted. 

This rule does NOT have an auto-fix option, so I did all these by hand. Please check my work!

### TESTING INSTRUCTIONS

Linting should not fail, CI should pass.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by EugeneTorap** [comment]
LGTM! @rusackas can you fix CI errors?

**Review by villebro — APPROVED** [review]
This PR gave me great satisfaction, thanks for making this a rule! ❤️

**Review by michael-s-molina — APPROVED** [review]
LGTM. Really great improvements to code readability!

**Review by stephenLYZ — APPROVED** [review]
LGTM!

**Pull request merged**
