### PR TITLE
fix: dashboard import validation

### PR DESCRIPTION
**Pull request by dpgaspar**
### SUMMARY

Adds a missing validation to import dashboards when a low privilege user imports a dashboard that already exists.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by rusackas — APPROVED** [review]

**Review by betodealmeida — APPROVED** [review]
Thanks for fixing this!

**Pull request merged**
