### PR TITLE
[country_map] use Albers USA projection

### PR DESCRIPTION
**Pull request by mistercrunch**
## before
screen shot 2017-11-27 at 10 39 07 pm

## after
screen shot 2017-11-27 at 10 37 51 pm

Also added ability to set number formatting a new spectrum color scheme.

### CODE REVIEW

**Comment by mistercrunch** [comment]
@williaster @michellethomas

**Comment by michellethomas** [comment]
lgtm

**Comment by mjdepalma** [comment]
While I love the new USA map format, I'm sorry to report that it does not appear to work.  I've confirmed that a chart which previously worked fine with the old map no longer shows any data with these changes.   The data is a simple map containing ISO-3166-2 region codes and values (US-GA, US-CT, etc.)  Reverting this change fixes the problem for me.   I've attached a .csv containing sample data that can be used to replicate the problem.   Just import and set query to user_region with metric sum_pageviews.  If there's anything else I can provide to help - just let me know.

[country_map_usa_sample_data.csv.gz](https://github.com/apache/incubator-superset/files/1583300/country_map_usa_sample_data.csv.gz)

**Comment by mjdepalma** [comment]
Submitted problem as issue #4112

**Pull request merged**
