### PR TITLE
Fix dockerfile nodejs version to 8.12.0

### PR DESCRIPTION
**Pull request by kk580kk**
refer to: https://github.com/apache/incubator-superset/pull/6303

### CODE REVIEW

**Comment by zhaoyongjie** [comment]
@kk580kk  please do not change base image.

**Comment by kk580kk** [comment]
@zhaoyongjie ...

@mistercrunch tell me to change dockerfile simply ,  I don’t know who is in charge

**Comment by mistercrunch** [comment]
I think we should use trusted sources as an image sources. @kk580kk I'm sure you understand that pointing to someone's personal repository for a docker image has bad security implications.

**Comment by kk580kk** [comment]
@mistercrunch there no public official base (any trusted sources) images have node js and python both.
Either write in dockerfile or write in base image can finish this job.

**Comment by kk580kk** [comment]
Is there any official docker account in superset project , that can build a base images for this .

**Comment by kk580kk** [comment]
I don't think use apt instead of specific version of Environmental is good , it maybe not works as some one change apt package to a newer one. 
But it works now ,fine .....

**Pull request closed without merging**
