### PR TITLE
feat: add classNames for apply and clearAll buttons for superset filters

### PR DESCRIPTION
**Pull request by Nithin-George-Philips**
### SUMMARY
Added className for applyAll and clearALL Button in filterBar
This is to move the sticky buttons from the top to the bottom making it intuitive to different customers.
Custom css can be used to move the buttons as well as change the UI associated with the buttons.
### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

Screenshot 2021-11-26 at 2 28 25 PM

### TESTING INSTRUCTIONS
Sample css template to get above UI
 ```
.filter-action-buttons {
  position: absolute;
  z-index:1;
  bottom: 4px;
  right: 4px;
}

.filter-clear-all-button{
  color: #0098F3;
  border: none;
  font-weight: 400;
  text-transform: lowercase
}

.filter-apply-button{
    background-color: #0098F3;
    color: white;
}
.ant-select {
  margin-bottom: 6px;
}
```

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by villebro** [comment]
Thanks @Nithin-George-Philips - great idea. Would you mind sharing an after screenshot with associated customization instructions so others can try it out. Also, if #17505 is redundant, I suggest closing that one.

**Comment by Nithin-George-Philips** [comment]
@villebro I have provided a screenshot as well as a custom css template to obtain the same.

**Review by kgabryje — APPROVED** [review]
Good idea, thanks for the contribution! 🙂

**Review by villebro — APPROVED** [review]
Thanks - LGTM

**Comment by optymystycpryme** [comment]
@Nithin-George-Philips Can you provide the code necessary to move the Apply Filters/Clear All buttons to the top of the field above the filter options? It seems that by default, they are at the bottom of the form.

**Pull request merged**
