### PR TITLE
[celery] Bump celery to 4.3.0

### PR DESCRIPTION
**Pull request by dpgaspar**
### CATEGORY

- [X] Enhancement (new features, refinement)

### SUMMARY
New celery 4.3.0 ships with the following interesting features:

- Kumbu > 4.3.0 support for redis TLS using `rediss`
- Bump the minimum eventlet version to 0.24.1
- Added the new :setting:`task_acks_on_failure_or_timeout` setting
- **New Result Backend**: Added the S3 result backend
- Fix memory leak

and many others

### Note

This PR also bumps (on requirements-dev) Redis to 3.2.1 this a major release change.

Breaking changes on 3.0.0
https://github.com/andymccurdy/redis-py/blob/master/CHANGES#L94

### ADDITIONAL INFORMATION
- [X] Introduces new feature or API

### CODE REVIEW

**Comment by dpgaspar** [comment]
alembic migration problem, multiple heads?

**Review by mistercrunch — APPROVED** [review]

**Comment by dpgaspar** [comment]
alembic problem could be due to this: https://github.com/apache/incubator-superset/commit/97ffb762d0216e745fb1d946b4b1a4beeb66bfdf#diff-ea63ff796b95e70035bc31e812b14822

no?

**Comment by mistercrunch** [comment]
I see "kombu.exceptions.VersionMismatch: Redis transport requires redis-py versions 3.2.0 or later. You have 2.10.6" in the build logs

**Comment by dpgaspar** [comment]
Right, I see it

**Review by mistercrunch — APPROVED** [review]

**Pull request merged**
