### PR TITLE
Upgrade table chart plugin to 0.12.13

### PR DESCRIPTION
**Pull request by ktmud**
### CATEGORY

- [x] Bug Fix

### SUMMARY

Bump table chart plugin to fix table chart time column formatting.

### TEST PLAN

See https://github.com/apache-superset/superset-ui/pull/340

### ADDITIONAL INFORMATION

- [x] Has associated issue: https://github.com/apache-superset/superset-ui/pull/340
- [x] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### REVIEWERS

@graceguo-supercat @kristw @michellethomas

### CODE REVIEW

**Review by michellethomas — APPROVED** [review]

**Comment by ktmud** [comment]
Job actually failed before of Travis had too many requests to [GitHub example data](https://github.com/apache-superset/examples-data/) repo: https://travis-ci.com/github/ktmud/incubator-superset/jobs/317148046

cc @michellethomas

**Comment by ktmud** [comment]
Reopen to trigger travis.

**Comment by graceguo-supercat** [comment]
travis build is successful but github didn't get update build status. I just try close and reopen this PR to see if this can help.

**Comment by ktmud** [comment]
OMG, it passed!!!!!!!

**Pull request merged**
