### PR TITLE
fix(window): unavailable localStorage and sessionStorage

### PR DESCRIPTION
**Pull request by frassinier**
### SUMMARY

If you tweak your web browser settings a little bit and embed Superset into an iframe, you could encounter an issue with unavailable local storage and/or session storage.
Using the web browser API must be surrounded by try-catch blocks.

More info in this great article 
- https://blog.tomayac.com/2022/08/30/things-not-available-when-someone-blocks-all-cookies/

### TESTING INSTRUCTIONS
- Go on Edge, for example
- Block 3rd-party cookies
image
- And try to visit an embedded Superset
- 💥 

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by eschutho — APPROVED** [review]
Thanks @frassinier for the fix! This LGTM.

**Comment by frassinier** [comment]
@eschutho any chance to trigger cy tests again from your side? 
I think it's not matching the branch protection rules?

**Comment by rusackas** [comment]
Oops, sorry @justinpark / @john-bodley - I got a little trigger-happy there. Please do review, and let us know if this needs course correction.

**Comment by justinpark** [comment]
LGTM

**Comment by eschutho** [comment]
it's all good.. thanks @rusackas!

**Pull request merged**
