### PR TITLE
[feature] Allow min/max value for the sparkline in time series table

### PR DESCRIPTION
**Pull request by kristw**
- User can set a fixed y-min/max
- User can choose to display y-axis for the sparkline
- Refactor and extract Sparkline logic from `time_table` into `SparklineCell`

debug-time-series-table-4

@williaster @graceguo-supercat

### CODE REVIEW

**Comment by kristw** [comment]
Add an option to show bounds

debug-time-series-table-2

**Comment by williaster** [comment]
@kristw this looks great! One thought about the reference lines/showing the bounds, do you think it'd be useful to label them? Something like the following but just the number for min / max

image

The tricky thing with this would be the padding to accommodate the label, so might not be worth it 🤔 would be nice to have better support for that tho.

**Comment by kristw** [comment]
Done

image

**Comment by williaster** [comment]
WOW! 🙉 

this will also be really useful (possibly more so!) without setting ymin/max bounds too

**Comment by kristw** [comment]
debug-time-series-table-4

**Pull request merged**
