### PR TITLE
fix: Add user filtering to changed_by. Fixes #27986

### LINKED ISSUE #27986: Showing list of all the users name to other users
### Bug description

If any users login to the superset they can able to see the list of all the other users who didn't created or modified the dashboard 

In superset 3.0.1, we have 'Created BY' column on all menu that will populate all the users name who have access to Superset. We tried to pass default value, unfortunately we couldn't so we are showing incorrect values to the users

### How to reproduce the bug

Create users
And assign any basic role to the user and login with the new users
you can view the list of user on 'Owner' Column and 'Modified Column'

### Screenshots/recordings

image
image

### Superset version

4.0.0

### Python version

3.9

### Node version

16

### Browser

Chrome

### Additional context

_No response_

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### PR DESCRIPTION
**Pull request by marre**
### SUMMARY
The EXTRA_RELATED_QUERY_FILTERS option only affected the "owner" field, this PR changes it to also apply to the "modified by" field.

This option is currently used in a superset installation where a superset user should not be able to list other superset user names. Without this PR a superset user can list the names of other users in the "modified by" field.

Fixes #27986

[Documentation](https://github.com/apache/superset/blob/4.0.2/superset/config.py#L1643-L1665) of the `EXTRA_RELATED_QUERY_FILTERS`:
```
# Extra related query filters make it possible to limit which objects are shown
# in the UI. For examples, to only show "admin" or users starting with the letter "b" in
# the "Owners" dropdowns, you could add the following in your config:
```

Example `superset_config.py` with EXTRA_RELATED_QUERY_FILTERS configured to hide all users:
```
# Hide all users
def user_filter(query):
    from sqlalchemy.sql import false
    return query.filter(false())

EXTRA_RELATED_QUERY_FILTERS = {
    "user": user_filter,
}
```

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

Before:  
image

After:  
image

### TESTING INSTRUCTIONS

1. Add the EXTRA_RELATED_QUERY_FILTERS above to your superset_config.py file
2. Click on "charts" to get the list of all charts
3. Click on the "owner" drop-down, only your name should be visible
4. Click on the "modified-by" drop-down, only your name should be visible (before this patch all users were visible) 

### ADDITIONAL INFORMATION

- [x] Has associated issue: #27986 
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by marre** [comment]
Adding a link to the PR that introduced this feature for "owner" and "group".
https://github.com/apache/superset/pull/22526

**Comment by marre** [comment]
@dpgaspar : I think I have corrected the formatting. Would be nice if you can start the workflows again.

**Comment by rusackas** [comment]
CI running 🤞

**Comment by marre** [comment]
@rusackas : Added missing newline to get ruff linter happy

@dpgaspar would love to get a new CI run...

**Comment by marre** [comment]
Would love to get some feedback if this PR is considered for merging. Or if I can improve it in some way.

**Comment by marre** [comment]
Updated branch with master to resolve merge conflict

**Comment by marre** [comment]
Updated the "summary" of this PR with a better description and added "testing instructions"

**Comment by rusackas** [comment]
Running CI again :)

**Comment by marre** [comment]
Anything else I can do to get this approved/merged?

**Comment by bcook-konza** [comment]
This looks awesome @marre - we would also greatly benefit from this. We'll be crossing our fingers for approval soon and we'll be willing to help if any additional work is needed

**Review by rusackas — APPROVED** [review]

**Comment by rusackas** [comment]
Done! Thanks for your contribution!

**Comment by marre** [comment]
Thanks!

In what release will it be included in?

**Comment by sadpandajoe** [comment]
@supersetbot label 4.1

**Comment by bruno-santos-6** [comment]
@marre, thank you! However, you mentioned that this would fix the 'Modified By' field issue, but the only field currently removing the list of users is 'Owner'.

Example for the 'Owner' field:
image

Example for the 'Modified By' field

image

Is there some configuration that I'm missing?

from sqlalchemy.sql import false

  # Hide all users
  def user_filter(query):
      return query.filter(false())
        
    EXTRA_RELATED_QUERY_FILTERS = {
        "user": user_filter,
        "changed_by": user_filter
    }

**Comment by sadpandajoe** [comment]
@supersetbot unlabel 4.1

**Comment by marre** [comment]
@sadpandajoe Would really love to have this in 4.1...

@bruno-santos-6 What version of superset are you testing with?

Just pulled latest from superset/superset (master branch)

# Without EXTRA_RELATED_QUERY_FILTERS

Without EXTRA_RELATED_QUERY_FILTERS configured:

Owner:
image

Modified-by:
image

# With EXTRA_RELATED_QUERY_FILTERS

Added this to my superset_config.py:
```
def user_filter(query):
    from sqlalchemy.sql import false
    return query.filter(false())

EXTRA_RELATED_QUERY_FILTERS = {
    "user": user_filter,
}
```

Started with:
```
export SUPERSET_CONFIG_PATH=./superset_config.py
superset run -p 8088 --with-threads --reload --debugger --debug
```

Owner after:
image

Modified-by after:
image

**Comment by marre** [comment]
Noticed that I had a typo in the first sentence of the description. I wrote "modified-by" where I intended "owner" and vice-versa. Corrected in description.

**Comment by bruno-santos-6** [comment]
@marre  You are right, I deployed Superset using Helm on Kubernetes, and the latest version of Superset available in the official chart is 4.0.1. I will try to apply version 4.0.2

**Comment by marre** [comment]
You have to either grab it directly from github from master branch or wait for a release where this PR will be included in. I hope it will be in 4.1.0 as it was once tagged with 4.1, but that tag has been removed. So I really don't know when this will be included in a release.

**Pull request merged**
