### PR TITLE
fix(explore): metrics caret not expanding in datasource panel

### LINKED ISSUE #12233: [Explore]Data panel Metrics section should expand on click the caret
Current behavior
1. Data panel shows first 50 columns in Columns section, and the section is open by default; Users have to scroll down to get to the Metrics section 
2. Metrics section is closed by default; Users click the caret to open Metrics section 
3. Section opens below but it is not expanded visibly; users have to scroll down to see Metrics list  
4. After scrolling down to view metrics, repeat the action, section now expands

Expected 
Data panel Metrics section should expand after the first click on caret without user scrolling down. 

https://user-images.githubusercontent.com/67837651/103448009-2b22f680-4c48-11eb-962c-36b74bb4f864.mov

### PR DESCRIPTION
**Pull request by geido**
### SUMMARY
This fixes an issue with the Antd Collapse being duplicated and it makes the "Columns" and "Metrics" sections expanded by default in the Datasource panel.

Closes #12233 

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
After:
Age-distribution-of-respondents

### TEST PLAN
1. Explore a chart
2. Expand the Metrics in the Datasource panel
3. Make sure both "Columns" and "Metrics" sections are expanded and can be collapsed independently.

### ADDITIONAL INFORMATION

- [x] Has associated issue: #12233 
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by geido** [comment]
@junlincc @rusackas

**Comment by junlincc** [comment]
thanks for the fix @geido!  can we keep the column section open while the metrics is expanded?

**Comment by geido** [comment]
I am not sure I understand @junlincc. The Columns section is closed as soon as the Metrics section is expanded.

**Comment by geido** [comment]
@junlincc the "one at a time" option was there in the original implementation, just not working properly. This is what this PR fixes. Having both opened requires a different approach and a different implementation which I would not recommend.

**Comment by ktmud** [comment]
+1 on keeping them both opened if users choose so. In the future we may even allow users to drag a column to the metric section to create a metric.

**Comment by geido** [comment]
@ktmud @junlincc I removed the accordion and set the two sections open by default. Have a look, please. Thank you

**Comment by riahk** [comment]
Is it possible to update the screenshot/recording with change noted above?

**Review by rusackas — APPROVED** [review]
Code LGTM. @junlincc will do a quick QA pass before we merge.

**Review by pkdotson — APPROVED** [review]
LGTM! Thanks for updating!

**Comment by rusackas** [comment]
Verified locally... looking good! You're off the hook, @junlincc

**Pull request merged**
