### PR TITLE
[SQL Lab] Adds autocomplete on table names and auto-add to schema bro…

### LINKED ISSUE #7059: [SQL Lab] autocomplete table names, auto-add to schema browser
Currently, autocomplete in SQL Lab's editor is limited to table and column names that have been added to the schema browser.

To that, we should add autocomplete for:
* schema names
* table names that are in the active database / schema

On the event of using a table name from autocomplete, we should add this new table to the schema browser for reference. From that point the column names from that added table should become "auto-completable"

### PR DESCRIPTION
**Pull request by enricoberti**
…wser

Closes #7059

### CODE REVIEW

**Comment by enricoberti** [comment]
20190326_autocomplete 2019-03-26 16_38_00

**Comment by kristw** [comment]
CI is failing.

**Comment by enricoberti** [comment]
@kristw mmm, all the ones that fail they do with "ERROR: could not install deps", so i'm not sure it's related to the commit.

**Comment by mistercrunch** [comment]
You'll have to rebase your branch. This issue was around a Python dependency that went missing.

**Comment by mistercrunch** [comment]
Can you please add some unit tests to make sure coverage goes up upon landing this? The coverage report should appear when the build goes through after fixing the python lint issues.

**Comment by mistercrunch** [comment]
Superseded by https://github.com/apache/incubator-superset/pull/7633, closing

**Pull request closed without merging**
