### PR TITLE
Make table view filters configurable

### PR DESCRIPTION
**Pull request by jeffreythewang**
I'm open to discussion on this, but I think the table view default filters should be configurable in some way, since usage of SQL Lab views can vary.

(I also think the UX functionality of the boolean filter field is unintuitive, but that's a separate change.)

@mistercrunch

### CODE REVIEW

**Comment by mistercrunch** [comment]
I agree that the CRUD filter is pretty awful. The goal of the original PR was to remove the clutter related to SQL views.

I'm hoping we can use move away from FAB's crud for this view soon, but in the meantime I'm not sure how to deal with the clutter.

Maybe we need 2 different ModelView classes which lead to 2 different menu items one for views and one for table.

**Comment by john-bodley** [comment]
@jeffreythewang you may also need to update this logic: https://github.com/apache/incubator-superset/blob/master/superset/connectors/sqla/models.py#L892.

**Comment by jeffreythewang** [comment]
@john-bodley I just realized this filter is being applied. If I'm reading this correctly, this means that non-admins are not able to view or edit datasources created via SQL Lab. Is that intentional?

**Comment by jeffreythewang** [comment]
My bad. I realized we do an additional permissions check internally that runs through [that](https://github.com/apache/incubator-superset/blob/master/superset/connectors/sqla/models.py#L892) `default_query` when editing tables. However, I can see some issues with applying that filter to the underlying `default_query` when the intention was just to remove clutter from the table list. Is there a particular reason why the filter exists there as well as in the URL params?

**Pull request closed without merging**
