### PR TITLE
Use metrics and columns "Verbose Name" in visualization

### PR DESCRIPTION
**Pull request by ArijanaBrlek**
Instead of metric and column names, verbose names are shown for all visualization objects. The metric or column name is only shown if there is no verbose name. Also, verbose names are used for drop-down options on the explore page.

### CODE REVIEW

**Comment by ArijanaBrlek** [comment]
This PR implements the feature described in #[2813](https://github.com/airbnb/superset/issues/2813)

**Comment by fabianmenges** [comment]
I noticed that the "Time Column" does not show the verbose name, it probably should be consistent across all column selects.

**Comment by mistercrunch** [comment]
I'm don't think that the assumption that the `coalesce(verbose_name, non_verbose_name)` is unique is safe. If we agree that it isn't a safe assumption, the approach here is flawed. 

Originally I was picturing sending a mapping of non verbose to verbose name to the frontend, and having some utility method(s) there to replace the strings where they are displayed. `form_data` and dataframe series name would stay unchanged.

**Comment by jerryhall** [comment]
Where does one include the verbose/non-verbose names? If it's in the slices, here's an example of one of my active slices:

`{"having": "", "viz_type": "pivot_table", "slice_id": 53, "where": "prem_city_ps = 'LOS ANGELES'", "since": "100 year ago", "groupby": ["prem_council", "master", "lic_app"], "metrics": ["count"], "pandas_aggfunc": "sum", "datasource": "9__table", "filters": [], "granularity_sqla": "abc_rpt_date", "time_grain_sqla": null, "until": "now", "columns": ["class_parent", "class_label"]}`

**Comment by mistercrunch** [comment]
Here's a different approach
https://github.com/airbnb/superset/pull/2921

**Comment by mistercrunch** [comment]
This got addressed in another PR. Thank you for raising the issue and proposing a path to solution though!

**Comment by raelmiu** [comment]
@mistercrunch Where was this addressed? Your reference does not solve this for all visualisations, and I'm not finding another one?

**Comment by markokole** [comment]
(despite being a closed and old thread)
I edited chart properties and under metrics/label I changed to my text. 
Example from "COUNT(assist)" I changed it to "Number of assists".
After rerunning the query I see the custom text when hovering over a bar.

**Pull request closed without merging**
