### PR TITLE
fix: All values being selected in Select

### LINKED ISSUE #25178: Filter selects all available options (not just the one you select) when filter is set with "dynamically search all filter values" option
Hello, I've been experiencing the following issue regarding filters.

#### How to reproduce the bug
Having a filter added on the left hand side panel with the option "dynamically search all filter values" activated:
1. Start typing in the filter field to search a specific value. The search must narrow the values to **only one coincidence**.
2. Click on the value to filter the information and show only that result.

### Expected results

Filtering the information to show what corresponds to the value I chose from the filter field.

### Actual results

It automatically selects all values as if I had clicked the "Select All" option.

#### Screenshots

image
image
image

### Environment

- browser type and version: Brave 1.57.57
- superset version: 2.1.0
- python version: Python 3.8.16

### PR DESCRIPTION
**Pull request by michael-s-molina**
### SUMMARY
Fixes https://github.com/apache/superset/issues/25178.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

https://github.com/apache/superset/assets/70410625/dc1c856b-2070-41da-9ee1-12a00b7a0e30

https://github.com/apache/superset/assets/70410625/c93134b4-dff2-4e1f-b0a6-2cf72a10bc5e

### TESTING INSTRUCTIONS
Check the original issue for instructions.

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by kgabryje — APPROVED** [review]
LGTM

**Comment by Vitor-Avila** [comment]
thank you so much, @michael-s-molina!!!

**Review by geido — APPROVED** [review]

**Comment by sadpandajoe** [comment]
🏷️ preset:2023.35

**Comment by sadpandajoe** [comment]
@michael-s-molina we've seen a few issues with the dropdown component, would adding component tests for that component be helpful in the future if we make another dropdown change to ensure everything is working normally?

**Comment by michael-s-molina** [comment]
> @michael-s-molina we've seen a few issues with the dropdown component, would adding component tests for that component be helpful in the future if we make another dropdown change to ensure everything is working normally?

@sadpandajoe Adding tests is always helpful but keep in mind that the `Select` component is the most tested component of Superset with more than 50 tests. Many bugs come from components that wrap that component and change its core logic such as the `SelectFilterPlugin`.

**Pull request merged**
