### PR TITLE
upgrade to react-bootstrap v0.33.1

### PR DESCRIPTION
**Pull request by suddjian**
### CATEGORY

Choose one

- [x] Bug Fix
- [ ] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY

Motivation: There is a bug where if you mousedown inside a modal, drag outside, and then mouseup, the modal closes. This is irritating when trying to edit text inside a modal, as you'll often drag the mouse out of bounds when selecting text. The bug was fixed in react-bootstrap v0.33.

Migrating to 0.33 means dealing with some breaking changes, in spite of being a "minor" version. I've done a thorough search and fixed all that I could find (mostly to do with changes to the `<Panel>` contract.

I also ended up fixing a few instances where propTypes were incorrectly defined.

As much as I would like to upgrade to react-bootstrap v1.0, that proved too daunting a task for now, with many breaking changes. Perhaps this work can bring us closer to that point.

### TEST PLAN

I'd appreciate it if a reviewer could run the branch and look for any UI issues.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### REVIEWERS
@rusackas

### CODE REVIEW

**Comment by suddjian** [comment]
CI passed but it looks like Travis didn't get the message through to GitHub.

**Comment by rusackas** [comment]
> CI passed but it looks like Travis didn't get the message through to GitHub.

Same thing happened to me on another PR. Not sure if there's an official/effective way to kick that into gear.

**Comment by villebro** [comment]
Something weird going on with Codecov and Travis, they don't seem to be triggering like they should lately.

**Comment by villebro** [comment]
@suddjian I restarted CI, let's see if this fixes it.

**Review by rusackas — APPROVED** [review]
Code LGTM! I'll give it a trial run and click around at things in case I spot anything weird.

**Pull request merged**
