### PR TITLE
chore: change case for upload selection

### PR DESCRIPTION
**Pull request by pkdotson**
### SUMMARY
Change case and sentence structure for upload selection in the dropdown.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
before
Screen Shot 2022-03-03 at 1 05 35 PM

after
Screen Shot 2022-03-03 at 1 09 50 PM

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by AAfghahi — APPROVED** [review]
What is a columnar

**Comment by pkdotson** [comment]
> What is a columnar

a columnar file formats store data by column, not by row. CSV, TSV, JSON,  are traditional row-based file formats

**Review by eschutho — APPROVED** [review]
Much better!

**Comment by sadpandajoe** [comment]
🏷️  preset:2022.9

**Pull request merged**
