### PR TITLE
ci: use git submodules for (securely) using third party Github Actions

### PR DESCRIPTION
**Pull request by TobKed**
### SUMMARY

The idea was to improve GitHub Actions after ASF changed the rules and only allow
actions hosted in-organization.

IMHO using git submodules is more clean way to use external github actions.
I based my opinion this on the discussion:
https://lists.apache.org/x/thread.html/r435c45dfc28ec74e28314aa9db8a216a2b45ff7f27b15932035d3f65@%3Cbuilds.apache.org%3E

and how it was solved in:
 -  Apache Airflow: https://github.com/apache/airflow/pull/13514
 - Apache Beam: https://issues.apache.org/jira/browse/BEAM-11569
 
 List of repositories added as git submodules with their revisions:
 - [`EndBug/latest-tag@latest`](https://github.com/EndBug/latest-tag)
 - [`morrisoncole/pr-lint-action@v1.4.1`](https://github.com/morrisoncole/pr-lint-action)
 - [`trilom/file-changes-action@v1.2.4`](https://github.com/trilom/file-changes-action)
 - [`styfle/cancel-workflow-action@0.6.0`](https://github.com/styfle/cancel-workflow-action)
 - [`apache-superset/cached-dependencies@b90713b`](https://github.com/apache-superset/cached-dependencies)
 - [`unsplash/comment-on-pr@v1.2.0`](https://github.com/unsplash/comment-on-pr)

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by TobKed** [comment]
I need to add proper `git checkout`

**Comment by TobKed** [comment]
cc @ktmud @potiuk @ashb

**Review by potiuk — APPROVED** [review]
Nice! This is the recommended way which I think all Apache Projects should adopt. It has only benefits and no drawbacks:

* inner working of submodules is such actions are automatically linked via their long hash commit -- recommended [security practice](https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions)
* no change to the current workflow of people (submodules are only needed for CI - you only need submodules if you want to update to newer version of the actions
* GitHub has full support for review for submodules. When action is updated, reviewer will see diff of incoming changes that can be reviewed as usual (also part of security guidelines to review changes to actions rigorously)
* no 3rd-party code in superset repo

There are no drawbacks that I am aware of.

**Review by mik-laj — APPROVED** [review]
@amitmiran137  @ktmud Can you look at it?

**Comment by ktmud** [comment]
This is great. Thanks for making this change!

**Comment by ktmud** [comment]
We actually used @potiuk 's  [potius/cancel-workflow-runs](https://github.com/potiuk/cancel-workflow-runs) for the `cancel_duplciates.yml` job. But I can make the updates in another PR.

**Comment by potiuk** [comment]
FYI. I do recommend to migrate it as well, however my action was allow-listed by INFRA so you can use it directly ;)

**Pull request merged**
