### PR TITLE
fix: Adding extra metrics issue after chart configuration

### PR DESCRIPTION
**Pull request by codemaster08240328**
### SUMMARY
If we set the alignment on some columns, then start adding new metrics, the metrics throw an error and things break.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
BEFORE:
 
image (2)

AFTER:
[[DEV] Explore - birth_names - 16 June 2022 - Watch Video](https://www.loom.com/share/99ae4c8bbceb43f2bea601836bf43d35)

### TESTING INSTRUCTIONS
1. Create a Table Chart aggregating data.
2. Add some Columns and Metrics.
3. Execute your Chart.
4. Save it.
5. Try to add/remove Metrics from it.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by diegomedina248 — APPROVED** [review]
LGTM code wise, let's spin an env to test

**Review by rusackas — APPROVED** [review]
LGTM, thanks for the fix! If it's possible to add a regression test for this (perhaps using Cypress), that would be a nice follow-up

**Comment by rusackas** [comment]
> LGTM code wise, let's spin an env to test

I successfully tested the branch locally. Lookin' good!

**Comment by sadpandajoe** [comment]
🏷️ preset:2022.23

**Pull request merged**
