### PR TITLE
fix(fe/src/dashboard): optional chaining for possibly nullable parent attribute in LayoutItem type

### LINKED ISSUE #30418: Dashboard Filter 'useFilterScope' Error
### Bug description

The bug is that when interacting with the filters in an embedded dashboard, the filters will be replaced with an `Unexpected Error` message. The user is forced to refresh the dashboard, losing the state of their filters prior to the error.

image

**Steps to reproduce**
1. Load an embedded dashboard
2. Interact with the filters without clicking `Apply Filters`
3. After a certain amount of interactions, the filters will show the above error

I could not reliably find a way or pattern to trigger this error. It may take a minute or two of selecting, deselecting, updating some filter options before seeing the error.

The browser console displays the following TypeError related to the `useFilterScope` function.

image

### Screenshots/recordings

_No response_

### Superset version

4.0.2

### Python version

3.10

### Node version

16

### Browser

Chrome

### Additional context

_No response_

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### PR DESCRIPTION
**Pull request by hainenber**
fix(fe/src/dashboard): optional chaining for possibly nullable parent attribute in LayoutItem type

### SUMMARY

Add null checks via optional chaining for `parent` attribute of `LayoutItem` type. This has been done in the past, this PR is to roll out for remaining usages and re-type the attribute to be Partial.

Fixes #30418 

### TESTING INSTRUCTIONS

CI should all pass

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by hainenber** [comment]
Change in `package-lock.json` is due to Dependabot's version bump without running `npm ci` by itself.

**Review by justinpark — APPROVED** [review]

**Comment by Stanhoucke** [comment]
Hello, could this PR be considered for the next release (I don't have permission to add labels)? I don't see it in the latest release, 4.1.1. This looks like a non-breaking change to me and think it should be appropriate for a patch or minor release.

For further context on the impact of this change, please refer to the issue I raised at the end of September [here](https://github.com/apache/superset/issues/30418).

Thanks

**Comment by sfirke** [comment]
@sadpandajoe what do you think about this PR as a candidate for 4.1.2?  I didn't want to add it to the board without your input.  Not urgent, if you have a way to bookmark it for consideration in 4.1.2 this doesn't need a fast response.

**Comment by sadpandajoe** [comment]
> @sadpandajoe what do you think about this PR as a candidate for 4.1.2? I didn't want to add it to the board without your input. Not urgent, if you have a way to bookmark it for consideration in 4.1.2 this doesn't need a fast response.

@sfirke feel free to add things to the board as things that are fixes could go in when we cut the release.

**Comment by sfirke** [comment]
Thanks @sadpandajoe !  FYI @Stanhoucke I added it to the 4.1.2 project board here: https://github.com/orgs/apache/projects/437/views/1  It should get evaluated at the 4.1.2 cutting and if appropriate, cherried into the release.

**Comment by Stanhoucke** [comment]
That's great, thanks @sfirke

**Pull request merged**
