### PR TITLE
docs: fix line break in Apache Druid page

### LINKED ISSUE #25033: docs: Fix line break formatting in Apache Druid page
Line break is missing after the description of each component of the connection string

image

### PR DESCRIPTION
**Pull request by giuliotal**
### SUMMARY
Added line breaks and highlighted using code formatting each keyword of the connection string

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Before:
image

After:
image

### ADDITIONAL INFORMATION
Fixes #25033

### CODE REVIEW

**Comment by mdeshmu** [comment]
ping @sfirke !

**Comment by giuliotal** [comment]
@mdeshmu  replaced line breaks (which required trailing white spaces) with a bullet list

image

The alternative is to use raw HTML, preferred a bullet list for clarity

**Review by sfirke — APPROVED** [review]
LGTM

**Review by villebro — COMMENTED** [review]
LGTM, thanks for the fix

**Pull request merged**
