### PR TITLE
[SQL Lab] Introduced ALLOW_SQL_MAX_ROW_OVERRIDE config to allow users…

### LINKED ISSUE #6666: Allow users to opt out for limit on select queries
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.29.0rc4

### Expected results
Some ways a user can opt out the limit. Like if user adds their own limit like `LIMIT 9999999`, it won't be replaced by the default hard limit.

Hard limit is applied unless user provides a **different** limit.

### Actual results
Hard limit is always applied unless user provides a **lower** limit

### Steps to reproduce
Run a select query like `select 1` or `select 1 LIMIT 9999999` in Presto, you will see in the backend that the actual query is `select 1 LIMIT 1000000`.

### PR DESCRIPTION
**Pull request by enricoberti**
… to specify a higher limit than SQL_MAX_ROW

This also modifies the behavior of `DEFAULT_SQLLAB_LIMIT`: `SQL_MAX_ROW` will be used if `DEFAULT_SQLLAB_LIMIT` has a greater value than `SQL_MAX_ROW` and `ALLOW_SQL_MAX_ROW_OVERRIDE` is set to False

For example:
`SQL_MAX_ROW = 10`
`ALLOW_SQL_MAX_ROW_OVERRIDE = True`
`DEFAULT_SQLLAB_LIMIT = 5`
allows users to specify a limit greater than 10

This commit also introduces a safety net for wrong configurations, like
`SQL_MAX_ROW = 10`
`ALLOW_SQL_MAX_ROW_OVERRIDE = False`
`DEFAULT_SQLLAB_LIMIT = 100`
In this case SQL Lab will display a default limit of 10

Also, as a nit, changed the limit input type from text to number

Closes #6666

### CODE REVIEW

**Comment by michellethomas** [comment]
hi, there's been some conversation in [this PR](https://github.com/apache/incubator-superset/pull/6942) about the SQLLab limit configuration settings. It seems like it would be good to get some alignment on how we want to handle the sqllab limit configs. CC: @john-bodley

**Comment by john-bodley** [comment]
Per @michellethomas comment I think there’s merit in trying to consolidate some of this logic. Personally I think there’s merit in not over expanding the number of configurations for defining SQL limits.

**Comment by enricoberti** [comment]
@michellethomas @john-bodley thanks for reviewing this! I do agree with the fact less configuration is better, but I was not sure historically how much this SQL_MAX_ROW is enforced or critical to companies. I'm all up fro simplifying and just allow everybody to override it from the editor.
@mistercrunch @xtinec what do you think?

**Comment by mistercrunch** [comment]
You can see the python linting errors here https://travis-ci.org/apache/incubator-superset/jobs/512118073

**Comment by enricoberti** [comment]
@mistercrunch thanks! removed the linting errors but the conceptual question still stands :)

**Pull request closed without merging**
