### PR TITLE
[SIP-36] Migrate setupApp.js to setupApp.ts

### PR DESCRIPTION
**Pull request by etr2460**
### CATEGORY

Choose one

- [ ] Bug Fix
- [x] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY
This is an example PR for migrating a JS file to TS. I performed the following steps:
1. Rename the file from `setupApp.js` => `setupApp.ts`
1. Install typedefs for imported libraries (ex `npm install @types/jquery` or add `// @ts-ignore` if no valid typedefs exist
1. Type function arguments to their expected values
1. Address all eslint warnings and errors

### TEST PLAN
CI, confirm that previous behavior is still correct. In this case, check changing locales still works and that checkboxes work in CRUD Views

### ADDITIONAL INFORMATION

- [ ] Has associated issue: #9101
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### REVIEWERS
to: @nytai @graceguo-supercat @kristw @rusackas

### CODE REVIEW

**Comment by graceguo-supercat** [comment]
Since you are making migration to ts, could you add unit test for every new component? The overall test coverage seems keep going down.

**Comment by etr2460** [comment]
That's a good point, any thoughts about how to test this file? The dependence on jquery makes me a bit uncertain about how to test....

**Comment by graceguo-supercat** [comment]
i want to remove jQuery usage from superset-frontend... is it possible? https://www.sitepoint.com/jquery-document-ready-plain-javascript/

**Comment by nytai** [comment]
I reimplemented the menu in react, so it's possible to fully deprecate jquery. The react menu hasn't been propagated to all the pages, yet. I was hoping to progressively roll it out by replacing all the server rendered pages, however if someone wants to speed up jquery deprecation that's available.

**Review by nytai — APPROVED** [review]
lgtm, +1 on jquery deprecation

**Comment by etr2460** [comment]
++ on jquery removal as well. I don't think that's in scope for this PR though...

**Review by kristw — APPROVED** [review]

**Review by graceguo-supercat — APPROVED** [review]

**Pull request merged**
