### PR TITLE
Druid dashboard import/export. 

### PR DESCRIPTION
**Pull request by bkyryliuk**
Reviewers:
* @mistercrunch 
* @vera-liu 
* @ascott 

Testing:
* unit tests are done
* testing done on staging

### CODE REVIEW

**Comment by bkyryliuk** [comment]
@mistercrunch  - please take a look

**Comment by mistercrunch** [comment]
Lgtm

**Comment by bkyryliuk** [comment]
thanks !

**Comment by mistercrunch** [comment]
This broke the build, reverting. We can bring it back when fixed

**Comment by bkyryliuk** [comment]
@mistercrunch  - my fault, will check this out.

**Pull request merged**
