### PR TITLE
Decimal is a valid numeric type

### PR DESCRIPTION
**Pull request by hajdbo**
This will allow automatic creation of sum__ and avg__ metrics

### CODE REVIEW

**Comment by xrmx** [comment]
Does the following format make codeclimate happy?

```
num_types = (
    'DOUBLE', 'FLOAT', 'INT', 'BIGINT', 'LONG', 'REAL', 'NUMERIC', 'DECIMAL'
)
```

**Comment by hajdbo** [comment]
@xrmx your suggested formatting is 80 chars long. Codeclimate wanted 79 max, so I adapted.

**Comment by hajdbo** [comment]
Unsure why the build did not pass. Seems like a timeout on the tests. Will try again.

**Comment by mistercrunch** [comment]
There was a transient travis issue, I restarted the build and it worked. Merging now. Thanks for the PR!

**Pull request merged**
