### PR TITLE
refactor: Removes the deprecated KV Store feature

### PR DESCRIPTION
**Pull request by michael-s-molina**
### SUMMARY
As part of the [4.0 approved initiatives](https://github.com/orgs/apache/projects/292/views/1), this PR removes the deprecated KV Store feature and its related assets such as the API endpoint, the `keyvalue` table, and the `KV_STORE` and `SHARE_QUERIES_VIA_KV_STORE` feature flags.

The previous value of both feature flags was `False` and now the feature is permanently removed.

### TESTING INSTRUCTIONS
CI should be sufficient for merging this PR. We'll do a complete testing of 4.0 after all approved proposals are merged.

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by villebro — APPROVED** [review]
Good riddance! LGTM

**Comment by john-bodley** [comment]
@villebro I think this might be more nuanced than simply removing feature flags as there's no clear migration plan away from previous shared SQL Lab links which users likely perceive as somewhat persistent in nature. That said I'll be stoked when we finally remove this logic for good.

We (Airbnb) are discussing how best to proceed with preserving these semi-permanent URLs for a finite period.

**Comment by villebro** [comment]
@john-bodley One idea that came to mind - maybe you could just introduce a new namespace into the new kv store, migrate all existing legacy links to it and add the (now to be removed) endpoint to your local app extension that serves from the new kv store? If being able to serve these ancient links post 4.0 is important that is..

**Comment by john-bodley** [comment]
@villebro I _think_ what you proposed is similar to what I proposed [here](https://github.com/apache/superset/pull/26377#pullrequestreview-1805353134) in relation to the removal the deprecated redirect endpoint, apart from the local app extension, i.e., having us define and manage the lifecycle of the deprecated RESTful HTTP endpoint.

**Comment by john-bodley** [comment]
@michael-s-molina note that both the `KV_STORE` and `SHARE_QUERIES_VIA_KV_STORE` feature flag is currently deemed [in development](https://github.com/apache/superset/blob/3a7d76cece4408c8e80862ab9db3a38eaaafdc8c/RESOURCES/FEATURE_FLAGS.md?plain=1#L24) as opposed to deprecated. I'm not certain (per the [Semantic Versioning]([https://github.com/apache/superset/wiki/Semantic-Versioning) wiki page) whether i) these feature flags need to be first marked as deprecated and/or if there removal is deemed a breaking change given that (per the wiki):

> These features are considered **unfinished** and should only be used on development environments.

**Comment by michael-s-molina** [comment]
> I'm not certain (per the Semantic Versioning wiki page) whether i) these feature flags need to be first marked as deprecated and/or if there removal is deemed a breaking change given that (per the wiki):

Technically, given the they never left the `in development` status, we don't need to deprecate them as they never became official in the first place.

**Comment by michael-s-molina** [comment]
Closing in favor of https://github.com/apache/superset/pull/26450

**Pull request closed without merging**
