### PR TITLE
change fabmanager babel tools to pybabel

### PR DESCRIPTION
**Pull request by roganw**
[defect of fabmanager babel-extract](https://github.com/airbnb/superset/pull/2986)

### CODE REVIEW

**Comment by mistercrunch** [comment]
I almost feel like waiting for the next FAB release on this one.

**Comment by xrmx** [comment]
@mistercrunch since it's just documentation this looks like an easy workaround until it's fixed and released in fab though.

**Comment by RoganW** [comment]
@mistercrunch  It's worthwhile to keep consistent with using FAB commands .

But it has happened that translations extract from `__` were overwritten(revert):
[rebuild translation files](https://github.com/airbnb/superset/pull/2651)

**Comment by RoganW** [comment]
@mistercrunch  The fix was merged into FAB, which will release 1.9.1 today. [fix babel-extract command](https://github.com/dpgaspar/Flask-AppBuilder/pull/511)
Thank you!

**Pull request closed without merging**
