### PR TITLE
chore: fix typo

### PR DESCRIPTION
**Pull request by etr2460**
### SUMMARY
Noticed this while reading code

### TEST PLAN
CI
### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

to: @pkdotson

### CODE REVIEW

**Review by nytai — APPROVED** [review]
thx!

**Review by ktmud — COMMENTED** [review]
It seems this is also not wrapped in i18n

**Comment by etr2460** [comment]
yeah, i was doing this from the web editor, so didn't want to dig in that much. But if it's already imported in the file, then i can add i18n too

**Comment by etr2460** [comment]
i18n added!

**Pull request merged**
