### PR TITLE
fix(explore): Fix datasource switch for table chart

### LINKED ISSUE #21531: [chart power query] An error message occurs when user saves a chart using chart power query
#### How to reproduce the bug

- Go to SQL lab
- Run a query
- Hit the "Create chart" button
- Hit the "Save" button, and save the chart
- See the error

### Expected results

All controls remain filled in, no errors appear after saving a chart using chart power query

### Actual results

User sees an unexpected error after saving a chart using chart power query, see the video below

https://user-images.githubusercontent.com/90777564/191276272-e2cff763-0fc2-4585-b99a-d77053a73a00.mp4

### Environment

latest master

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by codyml**
### SUMMARY

Another casualty of #21315 was datasource switching for table chart: after that PR, switching between datasources wouldn't preserve any columns.  As a side-effect, saving charts based on SQL queries instead of datasets would fail, as the save process involves switching from the query datasource to the newly-created dataset.  This PR fixes the issue, which was specifically caused by #21315 turning `chartState.options` from an object into an array (see #21484).

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

Before:

localhost_9000_explore__form_data_key=O3JVAVF3-mFhHkTJ8F3xoCyHzxNRoottQ-ZJcNMIx1KOzPpJ8ueK6R88J-zJyptf datasource_id=1 datasource_type=query

After:

localhost_9000_explore__form_data_key=gHVMJ2BnjkTUap0aWTVz-ocYbMr5xFS3xE1sV1c8x1gdIsAPqErF4pzNNsWhFqz3 datasource_id=1 datasource_type=query

### TESTING INSTRUCTIONS

- Create a Table chart from a dataset in Raw mode and try switching datasets.  Ensure that columns that exist on both datasets are preserved.
- Create a Table chart in Raw mode from a query and try saving it.  Ensure that all control values remain unchanged after save.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by eschutho — APPROVED** [review]

**Comment by jinghua-qa** [comment]
I found an issue that, when create chart with a result have time column, it seems like the time column will become number in explore, and user can not create time-series related charts
master:
Screen Shot 2022-09-21 at 4 36 16 PM
in this pr:
Screen Shot 2022-09-21 at 4 39 23 PM

**Comment by mayurnewase** [comment]
fixes: #21531

**Comment by codyml** [comment]
> I found an issue that, when create chart with a result have time column, it seems like the time column will become number in explore, and user can not create time-series related charts
> master:
> Screen Shot 2022-09-21 at 4 36 16 PM
> in this pr:
> Screen Shot 2022-09-21 at 4 39 23 PM

@jinghua-qa Looking into this now, thanks!

**Comment by jinghua-qa** [comment]
I am able to reproduce in master for this issue, i try another dataset "Video Game Sales', when use chart-power-query, year open as # in explore and if open the dataset directly, year is a time column in the dataset. So i think this issue is not related to this PR and i will file issue seperately
Screen Shot 2022-09-23 at 12 48 53 AM
Screen Shot 2022-09-23 at 12 48 32 AM

**Comment by jinghua-qa** [comment]
However when i deployed pr changes to the preset workspace and test, i saw error msg for chart save ( but the chart is actually saved)

Screen Shot 2022-09-23 at 1 08 22 AM

**Review by stephenLYZ — APPROVED** [review]
Thanks for the fix. It would be nice if we can add some tests.

**Comment by jinghua-qa** [comment]
Have tested in a workspace with recent superset master and it is working fine, the issue for the time column because string is not related to this PR. LGTM

**Comment by codyml** [comment]
> Thanks for the fix. It would be nice if we can add some tests.

@stephenLYZ Thanks for the review!  I have adding tests for this case on my list, am going to tackle it separately.

**Pull request merged**
