### PR TITLE
fix(filters): Adds a fix for saving time range adhoc_filters

### LINKED ISSUE #30582: Time Range filters from dashboard are not being added to query b for mixed time series
### Bug description

Hi everyone, 

I have found a bug regarding adhoc_filters_b for mixed time series chart. Following are the details. Please let me know if you require more information.

**Description:**
The bug occurs when you have a mixed time series chart inside a dashboard and the time range filter from the dashboard does not apply to both queries of the mixed time series chart.

**Reproduction:**

1. Create a dashboard.
2. From the dashboard, create a mixed time series chart using the cleaned_sales_data example dataset.
3. Name the chart what you want.
4. Add order_date to x axis. Max(sales) for Query A metric and Avg(sales) for Query B metric. Also add a filter for dealsize with all the options to both queries.
5. Save the chart and go back to the dashboard.
6. Create a time range filter in the dashboard. I used last 30 years as default value since the data is old.
7.  Go to edit chart from the dashboard.
8. Change time grain and save the chart.
9. Go back to the dashboard and view the query on the chart.
10. The second query will not have the time range filter from the dashboard i.e. no order_date filter in the WHERE clause.

**Expected behavior**
The time range filter from the dashboard should apply to both queries of the mixed time series chart.

Here is the pull request for the fix.

**PR:** https://github.com/apache/superset/pull/30581

### Screenshots/recordings

image

### Superset version

master / latest-dev

### Python version

3.10

### Node version

18 or greater

### Browser

Chrome

### Additional context

_No response_

### Checklist

- [ ] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [ ] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### PR DESCRIPTION
**Pull request by ObservabilityTeam**
…aveModalActions.ts

### SUMMARY

The bug occurs when you have a mixed time series chart inside a dashboard and the time range filter from the dashboard does not apply to both queries of the mixed time series chart. If you compare the changes, the previous code would only take care of the adhoc_filters key. The changes make sure that all the adhoc filters keys of the regex /^adhoc_filters/ receive the adhoc time range filter. In case of mixed time series there are two keys namely, adhoc_filters and adhoc_filters_b.

### TESTING INSTRUCTIONS

For manual testing, here is the [link](https://github.com/apache/superset/issues/30582) of the issue with reproduction steps. You can verify the fix by following them.

### ADDITIONAL INFORMATION

- [x] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by michael-s-molina** [comment]
@ObservabilityTeam could you fill the PR template with a proper description? Can you also add tests for the fix?

**Comment by ObservabilityTeam** [comment]
> @ObservabilityTeam could you fill the PR template with a proper description? Can you also add tests for the fix?

**Comment by ObservabilityTeam** [comment]
> @ObservabilityTeam could you fill the PR template with a proper description? Can you also add tests for the fix?

Yes, it will be looked into soon.

**Comment by ObservabilityTeam** [comment]
I have added a test for the fix. The PR description has also been updated. Please let me know if you require anything else, thanks

**Review by michael-s-molina — APPROVED** [review]

**Pull request merged**
