### PR TITLE
[explore] improved filters

### LINKED ISSUE #274: Sql Metric Expression which uses % has % duped in tableView query
I created a sql metric with the expression:

```
CAST(strftime("%s", max("timestamp")) AS INT)
```

When I used this metric to create a table view the values were not being populated. Looking into the JSON I found the query had duplicated the `%`:

```
query: "SELECT "serviceName" AS "serviceName", CAST(strftime("%%s", max("timestamp")) AS INT)
 AS latest_date FROM "testResults" WHERE timestamp >= '2016-03-29 15:57:43.000000' AND timestamp <= '2016-04-05 15:57:43.000000' GROUP BY "serviceName" ORDER BY 
CAST(strftime("%%s", max("timestamp")) AS INT) DESC LIMIT 50000 OFFSET 0"
```

Current end result is this column ends up displaying a 0 for each entry

### PR DESCRIPTION
**Pull request by mistercrunch**
img
* datasource config elements to allow to applying predicates when
  fetching filter values
* more filter operators [>, <, >=, <=, ==, !=, LIKE]
* spinner while loading values when changing column
* Remove the need to escape/double `%` in LIKE clauses
* make `==` and `!=` use a free form, non-multi Select component
* refactor / simplify

net negative on number of lines of code (-20)!

@vera-liu @ascott @bkyryliuk 
fixes https://github.com/airbnb/superset/issues/274

### CODE REVIEW

**Comment by kkalyan** [comment]
Thanks, @mistercrunch, this would be a great enhancement!

**Comment by mistercrunch** [comment]
ping

**Comment by silashundt** [comment]
many souls pine in fervent silence and desperation for this patch to land.

**Comment by vera-liu** [comment]
LGTM

**Pull request merged**
