### PR TITLE
fix(dashboards): exported datashboard - dataset duplication

### LINKED ISSUE #27780: Charts based on Virtual Datasets Names in `UTF-8`
### Bug description

As title says - one you have multiple charts based on different virtual datasets (named in UTF-8) in your dashboard, you not able to export it propertly as next virtual dataset transforms into `ROOT_folder/datasets/-.yaml`, which is already choosen.

### How to reproduce the bug

I might not really understand how to create everything required by steps, however I hope my explanations are clear.

1) Crete few virtual datasets (more than one) nand give them a non-latin name (initialy was used cirillic)
2) Create charts based on this virtual datasets
3) Create Dashboard and place charts to it.
4) Export Dashboard (via api)
5) Import Exported File to another Superset instance 

Observe:
- missing charts / missing datasets
- in addition to missing charts, some charts seams missing for dashboard (like area is gray, but once you update charts it appearse where it belongs.)

### Superset version

3.1.1

### Additional context

I have solved it locally by adding transliteration for names by useing `transliterate` package, but it might be not proper way to fix it. 

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### PR DESCRIPTION
**Pull request by butuzov**
Resolves https://github.com/apache/superset/issues/27780

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
These are two exported (same) sashboards, one before patch, one after. I didn't introduced translit as I initialy resolved this business issue in my case (as it require support for additional package and not guaranted to trasliterate corectly name), but chnged to simpler solution (just keeping id in exported file). 

photo_2024-03-29_15-41-10

### TESTING INSTRUCTIONS
I tried to describe it within ticket

### ADDITIONAL INFORMATION

- [x] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by butuzov** [comment]
I see errors, and will back to this PR once i get local tests running, so i can incorporate ID change.

**Comment by rusackas** [comment]
Running CI 🤞

**Comment by butuzov** [comment]
> Running CI 🤞

Its going to fail. I am unable to push one more changed test, as i run into some weirld github ssh key issues. I beg a pardon for this.

**Comment by butuzov** [comment]
I guess we can contonue with tests. I solved my issue and pushed changed test.

**Comment by butuzov** [comment]
ping @rusackas

**Comment by rusackas** [comment]
Running CI again. Would still love a review from @betodealmeida / @eschutho

**Pull request closed without merging**
