### PR TITLE
fix(frontend/generator): fix failed Viz plugin build due to missing JSDOM config and dep

### LINKED ISSUE #29995: Viz Plugin is not building anymore
### Bug description

When I just follow the basic process to create a plugin, the build process is not working anymore. I did following the README steps, and the error always prompt:

npm ci
npm run build
npm warn deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm warn deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm warn deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm warn deprecated har-validator@5.1.5: this library is no longer supported
npm warn deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm warn deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm warn deprecated left-pad@1.3.0: use String.prototype.padStart()
npm warn deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm warn deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm warn deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm warn deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm warn deprecated @boost/core@1.18.7: Package has been deprecated. Core has been split into multiple stand-alone packages. https://github.com/milesj/boost

added 1431 packages, and audited 1432 packages in 21s

110 packages are looking for funding
  run `npm fund` for details

68 vulnerabilities (47 moderate, 17 high, 4 critical)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

> keyward-chart-01@0.1.0 prebuild
> rimraf {lib,esm,tsconfig.tsbuildinfo}

> keyward-chart-01@0.1.0 build
> npm run build-cjs && npm run build-esm && npm run ts-types

> keyward-chart-01@0.1.0 build-cjs
> babel src --extensions ".ts,.tsx,.js,.jsx" --copy-files --out-dir lib

Successfully compiled 7 files with Babel (398ms).

> keyward-chart-01@0.1.0 build-esm
> BABEL_OUTPUT=esm babel src --extensions ".ts,.tsx,.js,.jsx" --copy-files --out-dir esm

Successfully compiled 7 files with Babel (284ms).

> keyward-chart-01@0.1.0 ts-types
> tsc --build

> keyward-chart-01@0.1.0 postbuild
> npm run test

> keyward-chart-01@0.1.0 test
> jest

 FAIL  test/plugin/transformProps.test.ts
  ● Test suite failed to run

    The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/configuration#testenvironment-string.
    Consider using the "jsdom" test environment.

    ReferenceError: window is not defined

      17 |  * under the License.
      18 |  */
    > 19 | import { ChartProps, supersetTheme } from '@superset-ui/core';
         | ^
      20 | import transformProps from '../../src/plugin/transformProps';
      21 |
      22 | describe('KeywardChart01 transformProps', () => {

      at Object.<anonymous> (node_modules/@superset-ui/core/lib/utils/logging.js:24:17)
      at Object.<anonymous> (node_modules/@superset-ui/core/lib/utils/index.js:45:39)
      at Object.<anonymous> (node_modules/@superset-ui/core/lib/index.js:13:14)
      at Object.require (test/plugin/transformProps.test.ts:19:1)

 FAIL  test/plugin/buildQuery.test.ts
  ● Test suite failed to run

    The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/configuration#testenvironment-string.
    Consider using the "jsdom" test environment.

    ReferenceError: window is not defined

      17 |  * under the License.
      18 |  */
    > 19 | import { buildQueryContext, QueryFormData } from '@superset-ui/core';
         | ^
      20 |
      21 | /**
      22 |  * The buildQuery function is used to create an instance of QueryContext that's

      at Object.<anonymous> (node_modules/@superset-ui/core/lib/utils/logging.js:24:17)
      at Object.<anonymous> (node_modules/@superset-ui/core/lib/utils/index.js:45:39)
      at Object.<anonymous> (node_modules/@superset-ui/core/lib/index.js:13:14)
      at Object.require (src/plugin/buildQuery.ts:19:1)
      at Object.require (test/plugin/buildQuery.test.ts:19:1)

 FAIL  test/index.test.ts
  ● Test suite failed to run

    The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/configuration#testenvironment-string.
    Consider using the "jsdom" test environment.

    ReferenceError: window is not defined

      17 |  * under the License.
      18 |  */
    > 19 | import { t, ChartMetadata, ChartPlugin } from '@superset-ui/core';
         | ^
      20 | import buildQuery from './buildQuery';
      21 | import controlPanel from './controlPanel';
      22 | import transformProps from './transformProps';

      at Object.<anonymous> (node_modules/@superset-ui/core/lib/utils/logging.js:24:17)
      at Object.<anonymous> (node_modules/@superset-ui/core/lib/utils/index.js:45:39)
      at Object.<anonymous> (node_modules/@superset-ui/core/lib/index.js:13:14)
      at Object.require (src/plugin/index.ts:19:1)
      at Object.require (src/index.ts:20:1)
      at Object.require (test/index.test.ts:19:1)

Test Suites: 3 failed, 3 total
Tests:       0 total
Snapshots:   0 total
Time:        0.588 s
Ran all test suites.

### How to reproduce the bug

Create the plugin with YO, follow the steps and then:

# keyward-chart-01

This is the Keyward Chart 01 Superset Chart Plugin.

### Usage

To build the plugin, run the following commands:

```
npm ci
npm run build
```

### Screenshots/recordings

_No response_

### Superset version

master / latest-dev

### Python version

Not applicable

### Node version

18 or greater

### Browser

Chrome

### Additional context

_No response_

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### LINKED ISSUE #30297: Test suite failed to run - Custom Plugins
### Bug description

Hi,

I get the following error after generating and trying to build a custom visualization plugin (without making any code changes). I'm following [the official tutorial from Preset](https://www.youtube.com/watch?v=LDHFY9xTzls). 

```
 FAIL  test/plugin/buildQuery.test.ts
  ● Test suite failed to run

    The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/configuration#testenvironment-string.
    Consider using the "jsdom" test environment.
    
    ReferenceError: window is not defined

      17 |  * under the License.
      18 |  */
    > 19 | import { buildQueryContext, QueryFormData } from '@superset-ui/core';
         | ^
      20 |
      21 | /**
      22 |  * The buildQuery function is used to create an instance of QueryContext that's

      at Object.<anonymous> (node_modules/@superset-ui/core/lib/utils/logging.js:24:17)
      at Object.<anonymous> (node_modules/@superset-ui/core/lib/utils/index.js:45:39)
      at Object.<anonymous> (node_modules/@superset-ui/core/lib/index.js:13:14)
      at Object.require (src/plugin/buildQuery.ts:19:1)
      at Object.require (test/plugin/buildQuery.test.ts:19:1)
```

### How to reproduce the bug

Follow the exact steps taken in [Building Custom Viz Plugins in Superset](https://www.youtube.com/watch?v=LDHFY9xTzls) with the latest repository:

```
# Install yo
npm i -g yo
cd superset-frontend/packages/generator-superset
npm i
npm link

cd /tmp
mkdir my-plugin
cd my-plugin/
yo @superset-ui/superset
```

At this point, when running `npm ci && npm run build`,
you'll receive the error:

```
src/plugin/controlPanel.ts:22:3 - error TS6133: 'sections' is declared but its value is never read.

22   sections,
     ~~~~~~~~
```

This is where the expected output diverges from the tutorial; `npm ci && npm run build` should succeed with no errors or warnings, despite no code changes being made.

But anyway, for testing purposes, I don't care if `sections` isn't used; so I set `"noUnusedLocals": false` in `tsconfig.json`. 

Now when I rerun `npm ci && npm run build`:

```
 FAIL  test/plugin/buildQuery.test.ts
  ● Test suite failed to run

    The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/configuration#testenvironment-string.
    Consider using the "jsdom" test environment.
    
    ReferenceError: window is not defined

      17 |  * under the License.
      18 |  */
    > 19 | import { buildQueryContext, QueryFormData } from '@superset-ui/core';
         | ^
      20 |
      21 | /**
      22 |  * The buildQuery function is used to create an instance of QueryContext that's

      at Object.<anonymous> (node_modules/@superset-ui/core/lib/utils/logging.js:24:17)
      at Object.<anonymous> (node_modules/@superset-ui/core/lib/utils/index.js:45:39)
      at Object.<anonymous> (node_modules/@superset-ui/core/lib/index.js:13:14)
      at Object.require (src/plugin/buildQuery.ts:19:1)
      at Object.require (test/plugin/buildQuery.test.ts:19:1)
```

### Screenshots/recordings

N/A

### Superset version

master / latest-dev

### Python version

3.10

### Node version

18 or greater

### Browser

Not applicable

### Additional context

I'm running Ubuntu 22.04, and my exact Node version is 20.13.1. It's also probably worth mentioning I used the Basic Chart type. Again, I followed the exact steps specified in Preset's official tutorial, which involved no code changes; I can't think of any reason this issue should occur.

Also, if anyone is having the same issue and looking for a workaround, the easiest I've found is to just edit `buildQuery.test.ts` (under the `tests` directory), remove the existing test case, and add in one that will always succeed (my apologies if there's an easier way to do this, I'm not familiar with jest):

```
describe('2a', () => {
  test('my test case', () => {
    expect(true).toBe(true); // Always expect true
  });
}); 
```

Thank you.

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### PR DESCRIPTION
**Pull request by hainenber**
fix(frontend/generator): fix failed Viz plugin build due to missing JSDOM config and dep

### SUMMARY

Fixes #29995
Fixes #30297 

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

AFTER
image

### TESTING INSTRUCTIONS

Follow instructions in `howtos.mdx` in `Creating a simple Hello World viz plugin` section and confirms that `npm run build` is successful

### ADDITIONAL INFORMATION

- [x] Has associated issue: 29995
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by villebro** [comment]
Thanks for fixing this @hainenber ! @rusackas do you have time to validate this? If not I can try to carve out some time for it next week..

**Comment by rusackas** [comment]
@villebro sadly it's not likely... I have a couple days PTO, and other things cooking.

Thank you @hainenber for continuing to help us with this. As always, we're appreciating your help around here immensely.

For anyone who's interested, I'm thinking it might be time to step away from the generator. My two cents is that we really just need a sample plugin in the repo, which would be testable in CI/Storybook, but not actually instantiated in Superset. Then whenever we bump packages, change components, mess with controls, we'll know more about what we're breaking, and The "how to build a plugin" tutorial would basically be "copy the directory, and change these files:" This is obviously SIP stuff... but I'm dropping it here anyway... because it's Friday :P

**Review by rusackas — APPROVED** [review]
LGTM based on the diff. I haven't had time to run it yet, but don't want to block it.

**Comment by hainenber** [comment]
I have no idea why E2E tests are failing though. Seems to be a bit flaky these days, judging from recent commits in `master` branch :D

**Comment by rusackas** [comment]
Closing and reopening to kick CI. A lot of the CI issues have been fixed, so a rebase might help if we can't get this to pass in a couple of retries.

**Pull request merged**
