### PR TITLE
docs(translations): we no longer need/build .mo files

### PR DESCRIPTION
**Pull request by rusackas**
### SUMMARY

It looks like this step is no longer needed, as in fact the .mo files are gitignored as of #7539

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by mistercrunch** [comment]
Are you sure it's not needed anymore? I think the idea in https://github.com/apache/superset/pull/7539 was to not store them in the repo, but maybe still needed in CI (?) I haven't touched that in years so I really don't know but I'd double check that edits flow through without running this. BTW the same command is referenced in CONTRIBUTING.md too, could remove from there as well. I'm also surprised it's nowhere in CI either.

**Comment by rusackas** [comment]
> Are you sure it's not needed anymore? I think the idea in #7539 was to not store them in the repo, but maybe still needed in CI (?) I haven't touched that in years so I really don't know but I'd double check that edits flow through without running this. BTW the same command is referenced in CONTRIBUTING.md too, could remove from there as well. I'm also surprised it's nowhere in CI either.

I'm not sure at all, actually... I'm probably wrong, so I'll mark this as a draft and seek more discussion here.

I just found this in UPDATING.md:

> - The repo no longer contains translation binaries (`.mo`) files. If you
  want translations in your build, you now have to run the command
  `babel-compile --target superset/translations` as part of your builds

**Comment by mistercrunch** [comment]
Yeah I pulled your branch to see, but that command (`babel-compile --target superset/translations`) has errors:

```
error: superset/translations/es/LC_MESSAGES/messages.po:17180: placeholders are incompatible
error: superset/translations/es/LC_MESSAGES/messages.po:17185: placeholders are incompatible
error: superset/translations/es/LC_MESSAGES/messages.po:17190: placeholders are incompatible
error: superset/translations/es/LC_MESSAGES/messages.po:17200: placeholders are incompatible
error: superset/translations/es/LC_MESSAGES/messages.po:17473: placeholders are incompatible
error: superset/translations/es/LC_MESSAGES/messages.po:19061: placeholders are incompatible
error: superset/translations/es/LC_MESSAGES/messages.po:19192: unknown named placeholder 'table'
error: superset/translations/es/LC_MESSAGES/messages.po:19954: placeholders are incompatible
error: superset/translations/es/LC_MESSAGES/messages.po:19965: placeholders are incompatible
error: superset/translations/es/LC_MESSAGES/messages.po:20213: positional format placeholders are unbalanced
error: superset/translations/es/LC_MESSAGES/messages.po:20362: placeholders are incompatible
error: superset/translations/es/LC_MESSAGES/messages.po:20367: placeholders are incompatible
error: superset/translations/es/LC_MESSAGES/messages.po:20428: positional format placeholders are unbalanced
error: superset/translations/es/LC_MESSAGES/messages.po:20567: positional format placeholders are unbalanced
error: superset/translations/es/LC_MESSAGES/messages.po:20574: placeholders are incompatible
error: superset/translations/es/LC_MESSAGES/messages.po:20598: positional format placeholders are unbalanced
error: superset/translations/es/LC_MESSAGES/messages.po:20605: positional format placeholders are unbalanced
error: superset/translations/es/LC_MESSAGES/messages.po:20610: positional format placeholders are unbalanced
error: superset/translations/es/LC_MESSAGES/messages.po:20620: placeholders are incompatible
```

**Comment by rusackas** [comment]
> Yeah I pulled your branch to see, but that command (`babel-compile --target superset/translations`) has errors:

Right... it still builds the `.mo` files, but the warnings are because a lot of the translations are VERY wrong or out of date.

**Comment by qleroy** [comment]
Is this misleading that the init scripts for running the Docker containers do not contain ```pybabel -d superset/translations``` ?

The [docs](https://superset.apache.org/docs/installation/configuring-superset) nor the [config.py](https://github.com/apache/superset/blob/master/superset/config.py) file mentions that it is **required** to compile the messages.mo files in order for the translations to take effect.

I opened this #26738  issue
and suggests to add the compilation command somewhere in the init scripts so that the messages.mo files exist in a fresh Docker install.

**Comment by qleroy** [comment]
I confirm that the compilation is needed for the CI otherwise all FAB translations are ignored!

**Comment by mistercrunch** [comment]
It would be easy and nice to add something in `scripts/` that does all the steps, and the docs can reference that single entry point.

**Comment by rusackas** [comment]
Thanks for the clarification folks... more to do on this front, but this PR is clearly a misfire. Onward and upward!

**Pull request closed without merging**
