### PR TITLE
build(cypress): Use new pull_request_target event for cypress secret sharing

### PR DESCRIPTION
**Pull request by robdiciuccio**
### SUMMARY
Updates e2e test Github Actions workflow to use the [pull_request_target event](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/) in order to work around the [secrets sharing limitation](https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets#using-encrypted-secrets-in-a-workflow) for forked repos. Also adds concurrency via multiple `containers`.

Alternate approach to https://github.com/apache/incubator-superset/pull/11729

### TEST PLAN
e2e test workflow should run with a populated `CYPRESS_RECORD_KEY` value from the upstream repo's secrets.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by craig-rueda — APPROVED** [review]

**Comment by robdiciuccio** [comment]
My suspicion as to why Cypress is not running on this build is that the the new [pull_request_target](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#pull_request_target) event "runs in the context of the base repository of the pull request, rather than in the merge commit" and "only workflows defined in the commit on the base repository are run." 

So, theoretically, the updated workflow will run once merged to master. If it doesn't behave as expected, we can revert and try something else. This also makes it more difficult to Cypress workflow changes in PRs, but it seems to be the only workaround for the secrets sharing limitation.

**Comment by mistercrunch** [comment]
We can't merge if it's beige though :(

**Comment by robdiciuccio** [comment]
Ok, unclear how to get rid of that "expected" cypress test at this point. I'll try closing the PR and reopening.

**Comment by robdiciuccio** [comment]
Note that [Cypress did run on the last commit](https://github.com/preset-io/incubator-superset/actions/runs/382022160), but it not reflected in the CI status.

**Pull request closed without merging**
