### PR TITLE
chore: Add home link to navbar

### PR DESCRIPTION
**Pull request by agatapst**
### SUMMARY
This PR adds new element to the top navbar - HOME link redirecting to the homepage. 

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Navbar before:
image

Navbar after: 
image

### TEST PLAN
First, run command ```superset init``` to create default roles and permissions (navbar varies for different types of users, but home link should be seen by every user.) Then verify manually by visiting some application page. 

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [x] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

cc @junlincc @rusackas

### CODE REVIEW

**Comment by junlincc** [comment]
@eugeniamz

**Review by willbarrett — APPROVED** [review]

**Comment by etr2460** [comment]
I'm curious, isn't this redundant when you consider the `Superset` logo also goes to the welcome page? @junlincc what was the design/product rationale around this change?

**Comment by willbarrett** [comment]
@etr2460 it's possible to override the URL and logo in Superset, so this provides an additional way to get to the Superset home page when that configuration is leveraged.

**Comment by nytai** [comment]
@etr2460 this is in case someone has the `LOGO_TARGET_PATH` flag set, there's no other way to navigate to the home screen.

**Comment by junlincc** [comment]
@etr2460 
currently, Preset and other companies that forked Superset, don't have any direct entry points to go back to the landing page/home page within the product. since the logo usually takes users to the workspaces or their own company home page.

**Comment by etr2460** [comment]
Thanks for the clarification! Maybe we only show the new menu option if the `LOGO_TARGET_PATH` is set then?

**Comment by agatapst** [comment]
@junlincc thanks for your reply
@etr2460 that's good idea, thanks for the tip!

**Review by nytai — APPROVED** [review]

**Review by etr2460 — APPROVED** [review]
lgtm, thanks for addressing my comment!

**Review by rusackas — APPROVED** [review]

**Pull request merged**
