### PR TITLE
chore: remove unused methods with invalid models.Query usage

### PR DESCRIPTION
**Pull request by S-YOU**

### CODE REVIEW

**Comment by xrmx** [comment]
Is the current code broken for you? It looks like it's not needed.

**Comment by S-YOU** [comment]
@xrmx current code is 
`from superset.models import core as models`
but `Query` is not in core.py, but in sql_lab.py

That file is part of the test code, not under coverage, so may be less important.

**Comment by xrmx** [comment]
I see, maybe we can just remove the unused methods instead?

**Comment by S-YOU** [comment]
@xrmx, removed. I didn't realized they are not actually used.

**Pull request merged**
