### PR TITLE
fix(sqllab): flaky json explore modal due to over-rendering

### PR DESCRIPTION
**Pull request by justinpark**
### SUMMARY
This commit reopens #26156, which resolves the issue detailed in https://github.com/apache/superset/issues/26276 by excluding the changes in 'QueryAutoRefresh/index.tsx' and 'reducers/sqlLab.js'.
This commit also reverses the changes introduced in #18934. Now that the issue of overrendering due to redux has been resolved, it also effectively addresses the problem outlined in issue #26755.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

Before:

https://github.com/apache/superset/assets/1392866/8d81ba78-7142-438c-8c5c-b5049ef6ea94

After:

https://github.com/apache/superset/assets/1392866/c2023683-47f1-4a45-97c0-c14e4d7b6469

### TESTING INSTRUCTIONS

Go to SQL Lab and run a query contains a json blob
Select a table in order to execute a table preview query
Click `Results` tab before the table preview query ends and then click the JSON column to open the JSON modal
Check the JSON modal persists while the async query status is updating

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by justinpark** [comment]
cc @gaurav7261

**Review by mistercrunch — APPROVED** [review]
This looks solid overall, well covered by tests too.

**Comment by rusackas** [comment]
@justinpark any reason not to merge this?

**Pull request merged**
