### PR TITLE
fix: uuid generation for mysql fixed

### PR DESCRIPTION
**Pull request by iercan**
### SUMMARY
UUID generation fixed according to suggestion of @betodealmeida 

### ADDITIONAL INFORMATION

- [X] Has associated issue: #12728 #12202 
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by ktmud — APPROVED** [review]
Thanks for making the PR and thanks @betodealmeida for digging up the fix!

**Comment by iercan** [comment]
@betodealmeida

**Review by villebro — COMMENTED** [review]
Does this require using `utf8mb4` charset for the metadata database when on MySQL? If so, we should probably add that in the documentation.

**Comment by iercan** [comment]
@villebro Our superset metastore already use utf8mb4. So to be sure I run below query with another database that have latin1 charset and It didn't give any error.

`SELECT UNHEX(REPLACE(CONVERT(UUID() using utf8mb4), '-', '')) from <anytable> limit 10;`

**Comment by villebro** [comment]
@iercan ok perfect, thanks for confirming!

**Review by villebro — APPROVED** [review]

**Comment by villebro** [comment]
FYI tagging this for Superset v1.0.1

**Comment by iercan** [comment]
@villebro I will also test with UPDATE query and inform result.

**Comment by iercan** [comment]
> @villebro I will also test with UPDATE query and inform result.

It worked as well

**Pull request merged**
