### PR TITLE
fix(explore): Collapse padding (cosmetic)

### LINKED ISSUE #12634: Explore control panel minor cosmetic issues
Hey all, here are just a few tweaks to the explore control panel to make things look nicer 

I compiled all the correct icons for explore here for reference/use. You can export them as SVGs if needed!
https://www.figma.com/file/JWaGztdhZS0kS5ruG7x9tB/Control-Panel?node-id=813%3A47391

### 1. Horizontal padding around input fields 

Currently, the input fields are indented on the left
Screen Shot 2021-01-20 at 3 13 34 PM

The input fields should be aligned with the section headers like this (with 8px padding on both the left and right) - 
Screen Shot 2021-01-20 at 3 18 09 PM

### 2. Caret icons

The fields section and control panel have different caret icons
Screen Shot 2021-01-20 at 3 18 55 PM

They should be the same one from the Superset design system - 
Screen Shot 2021-01-20 at 3 20 48 PM

Here's the link to the correct icon - 
https://www.figma.com/file/JWaGztdhZS0kS5ruG7x9tB/Control-Panel?node-id=813%3A47391

### 3. Alignment of icons within input fields 

The f(x) icon is vertically off-center a tiny bit
Screen Shot 2021-01-20 at 3 31 47 PM

Here's a spec - 
Screen Shot 2021-01-20 at 3 35 28 PM

### 4. Icons in fields/dataset panel
Screen Shot 2021-01-20 at 3 37 12 PM
These are a bit inconsistent, the correct set is in the Figma link at the top

cc: @junlincc

### PR DESCRIPTION
**Pull request by geido**
### SUMMARY
It reduces the paddings left and right of the Collapse in the Explore control panel.

### BEFORE
b4

### AFTER
Screen Shot 2021-05-10 at 18 59 40

### TEST PLAN
1. Open a chart in Explore
2. Observe the padding-left and right of the control panel

### ADDITIONAL INFORMATION

- [x] Has associated issue: #12634
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by geido** [comment]
@junlincc @rusackas

**Comment by junlincc** [comment]
thanks for the PR, can we specify what has been changed in this PR? @geido thanks!

**Comment by geido** [comment]
Hello @junlincc there isn't much else to say apart from what the title already conveys. I changed the padding of the Collapse :)

**Comment by geido** [comment]
@junlincc @rusackas I have just noticed that the paddings are bigger in the "Customize" section as well. The same thing is for the Dataset panel. How do we want to approach this? Should we change the Collapse padding everywhere or should we go case by case?

Screen Shot 2021-05-10 at 14 58 40

**Comment by michael-s-molina** [comment]
@geido Maybe you should change the PR description because if you use the words "fixes <PR number>", it will close the original issue when this PR is merged but this is only a partial fix 😉.

**Comment by geido** [comment]
So are we keeping it at 16px? If so, we can basically discard this PR

**Comment by Steejay** [comment]
Lets keep it to 16px. Chatted w prod designer @mihir174 about this yesterday.

**Pull request closed without merging**
