### PR TITLE
docs: update docker compose instructions

### PR DESCRIPTION
**Pull request by mdeshmu**
### SUMMARY

Address bugherd task 69 & 73

cc: @sfirke @rusackas 

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by sfirke — APPROVED** [review]

**Comment by sfirke** [comment]
@mdeshmu I see this failed a check 😕

**Comment by mdeshmu** [comment]
@sfirke pre-commit failure is not related to this PR.

`tests/unit_tests/db_engine_specs/test_clickhouse.py:66: error: Argument 1 to "NewConnectionError" has incompatible type "str"; expected "HTTPConnection"  [arg-type]`

**Comment by sfirke** [comment]
Thanks for looking into the failed check!  Unfortunately merging is blocked by CI rules until that unrelated thing is fixed.  Either of us can close and re-open when we think that part of the build has been fixed, to re-trigger CI checks.

And thanks for sending these multiple PRs, that's a great contribution 🙏

**Comment by sfirke** [comment]
@john-bodley before I write the same thing on the four different PRs, are you looking for the link to BugHerd or some other reference?

**Comment by mdeshmu** [comment]
This is ready to merge

**Pull request merged**
