### PR TITLE
docs: adding Chinese tutorial for Superset

### PR DESCRIPTION
**Pull request by yangxifi**
Users from China, after the installation of superset, often have a strong demand for Chinese, but the online tutorials are more scattered, not easy to find, more have to slowly spend time exploring, more time consuming. Therefore, based on the previous installation of superset experience, summed up a Chinese tutorial, users according to this tutorial, about 10 minutes to complete the Chinese setting, expected its helpful for users from China

### CODE REVIEW

**Comment by yangxifi** [comment]
@zhaoyongjie I have modified the format, please help to review it again,thank you very much

**Comment by john-bodley** [comment]
@yangxifi thanks for the PR. Historically we haven't had language specific tutorials, and though—without doubt—it would help Chinese speakers, it increases the footprint of the documentation we need to maintain.

I would love @rusackas, @sfirke, @zhaoyongjie, et al. opinion on this but I was wondering whether there's a better way for making our documentation more inclusive? I was thinking using a tool/plugin like [Google Translate](https://translate.google.com/) would be a more desirable outcome.

**Comment by yangxifi** [comment]
> @yangxifi thanks for the PR. Historically we haven't had language specific tutorials, and though—without doubt—it would help Chinese speakers, it increases the footprint of the documentation we need to maintain.
> 
> I would love @rusackas, @sfirke, @zhaoyongjie, et al. opinion on this but I was wondering whether there's a better way for making our documentation more inclusive? I was thinking using a tool/plugin like [Google Translate](https://translate.google.com/) would be a more desirable outcome.

Well, I hope so, thank you for your reply

**Comment by rusackas** [comment]
> @yangxifi thanks for the PR. Historically we haven't had language specific tutorials, and though—without doubt—it would help Chinese speakers, it increases the footprint of the documentation we need to maintain.
> 
> I would love @rusackas, @sfirke, @zhaoyongjie, et al. opinion on this but I was wondering whether there's a better way for making our documentation more inclusive? I was thinking using a tool/plugin like [Google Translate](https://translate.google.com/) would be a more desirable outcome.

I know there are people using Superset in a lot of languages. I would love an effort to make the documentation *globally* inclusive, but I think we need to find a good way to automate it. Right now, documentation is falling out of date and/or incomplete in many places. Maintaining one language is hard, and I don't think we should multiply the problem (yet). If anyone has a way to automate translation (maybe a CI process that runs markdown files through GPT for translation?) I'd be more open to that.

**Pull request closed without merging**
