### PR TITLE
Add artifacthub metadata manifest

### PR DESCRIPTION
**Pull request by Yann-J**
This PR adds a metadata definition file to the Github Pages website root, in the format expected by https://artifacthub.io (see format here: https://github.com/artifacthub/hub/blob/master/docs/metadata/artifacthub-repo.yml).

ArtifactHub will read this metadata manifest when it will scan the Github Pages Helm chart repository we already expose at http://apache.github.io/superset/index.yaml , and to make the chart visible in ArtifactHub with the verified badge.

### CODE REVIEW

**Comment by Yann-J** [comment]
FYI, artifacthub page for the published chart: https://artifacthub.io/packages/helm/superset/superset

**Comment by Yann-J** [comment]
Hmm I'm not sure where these come from, my IDE didn't show these when I committed... I'll try to revert these.

The ID is tied to the Superset organization I created in Artifact hub, not to an individual.

I'm currently the owner of that org but I can relinquish it to you @craig-rueda  - I think you might need to create an account there first.

**Comment by Yann-J** [comment]
Cleaned up github actions + invite sent to artifacthub!

**Comment by Yann-J** [comment]
FYI @craig-rueda it seems you have not yet accepted the invite on artifacthub... just checking if you've received the email? The invite seems right since it's been able to get your name from your account id...

image

**Comment by craig-rueda** [comment]
Ok, I'm in

**Comment by craig-rueda** [comment]
I don't see any admin options in there though. Just the option to "leave" the org

**Comment by Yann-J** [comment]
Hey @craig-rueda is there anything else you need from me on this one?

**Comment by Yann-J** [comment]
FYI I think you might need to select the right context in your control panel in order to see the org-level settings:

image

**Review by craig-rueda — APPROVED** [review]

**Pull request merged**
