### PR TITLE
Remove ConsoleLog

### PR DESCRIPTION
**Pull request by betodealmeida**
### CATEGORY

Choose one

- [ ] Bug Fix
- [ ] Enhancement (new features, refinement)
- [X] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY

This PR removes `--console-log` from the CLI (similar to https://github.com/apache/incubator-superset/pull/7421), but update the docs with instructions of how to use it through the `FLASK_APP_MUTATOR`.

### TEST PLAN

Ran command in docs, verified the browser console logging handler works.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### REVIEWERS

@mistercrunch @rjurney

### CODE REVIEW

**Comment by mistercrunch** [comment]
Oh I moved #7421 and didn't realize this PR here was a superset of it :( sorry about that...

**Comment by betodealmeida** [comment]
@mistercrunch no worries, I just updated this.

**Comment by betodealmeida** [comment]
Ping @rjurney

**Review by rjurney — APPROVED** [review]
lgtm

**Pull request merged**
