### PR TITLE
feat(pdf-support)!: Added download Dashboard and Chart as PDF support

### LINKED ISSUE #25446: Download Dashboard as PDF #feature
### Motivation

Superset Supports downloading Dashboard as an Image. It does not have an option to download the Dashboard as a PDF. 

### Proposed Change

We can use [this](https://www.npmjs.com/package/dom-to-pdf) npm package to add PDF download support.

### New or Changed Public Interfaces

- NA

### New dependencies

- [dom-to-pdf](https://www.npmjs.com/package/dom-to-pdf)

### Migration Plan and Compatibility

- NA

### Rejected Alternatives

- NA

### Supporting Images / Screenshots
- After the change the UI will look like this.
image

### PR DESCRIPTION
**Pull request by Yaswanth-Perumalla**
### SUMMARY
Superset Supports downloading Dashboard, and Chart as an Image. It does not have an option to download the Dashboard or Chart as a PDF.
I have added this support using the [dom-to-pdf](https://www.npmjs.com/package/dom-to-pdf) npm package.

### BEFORE
image

### AFTER 
| Dashboard | Dashboard Chart | Explore |
| --- | --- | --- |
| Dashboard | Chart | Explore |

Closes [#25446](https://github.com/apache/superset/issues/25446) 

### TESTING INSTRUCTIONS
- Create a dashboard and check if you have the option to download the Dashboard and Chart as a pdf

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [x] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by michael-s-molina** [comment]
Thanks for the PR @Yaswanth-Perumalla. I believe @kasiazjc will request that the Download becomes a sub-menu with 2 options similar to Share. 

@kasiazjc Should we also be more specific and use `JPG` instead of `image`? Like:

Download -> JPG
Download -> PDF

I imagine we can have other image types such as PNG.

**Comment by kasiazjc** [comment]
> @Yaswanth-Perumalla We also need to keep consistency and add the PDF option to dashboard charts and Explore.
> 
> By the way, dashboard charts already have the Download submenu. @kasiazjc We may want to standardize the nomenclatures and make sure the menus are consistent between Dashboard, Dashboard charts, and Explore.
> 
> Dashboard:
> 
> Screenshot 2023-10-03 at 10 40 59
> Dashboard charts:
> 
> Screenshot 2023-10-03 at 10 36 48
> Explore:
> 
> Screenshot 2023-10-03 at 10 41 26

Thank you @Yaswanth-Perumalla! And @michael-s-molina for all of the suggestions, I agree with pretty much all of them 🙏🏻

So:

1. It would be great if download pdf and image would follow the patterns that Michael mentioned - so both would be in "Download >"'s  submenu with icons 

2. Agree we could be more specific what kind of image it is, so "Download as JPG" would definitely work 

3. To make it all consistent we could have a specific order in which the items are displayed in the menu, and I would suggest for it to be:

- Export to .CSV 
- Export to Excel 
- Export to JSON 
- Download as PDF
- Download as JPG 

We would just skip the options from the order if it's not available. 

I know that the last two bullet points are not a part of the task, but if you can work on it @Yaswanth-Perumalla, that would be great! If not - let me know :) Thank you!

**Comment by kasiazjc** [comment]
> Thanks @kasiazjc.
> 
> > To make it all consistent we could have a specific order in which the items are displayed in the menu, and I would suggest for it to be:
> > Export to .CSV
> > Export to Excel
> > Export to JSON
> > Download as PDF
> > Download as JPG
> 
> This works for me. I only have one small suggestion to remove the dot from .CSV as the others are also extensions.

oh, good point! I'll edit my comment :)

**Comment by justinpark** [comment]
@Yaswanth-Perumalla 
I would like us to style the page to be printer-friendly and use the print-to-PDF option, which produces more accurate PDFs.

@kasiazjc how do you think of this opinion?

**Comment by Yaswanth-Perumalla** [comment]
Hi @justinpark @michael-s-molina,
I've come across some failed checks, and I suspect that they might be due to an outdated `package-lock.json` file. To address this, I've updated the `package-lock.json` by running `npm install` on my local machine. However, I've noticed that the same checks are still failing. Can you please assist me in identifying the issue?

**Comment by fisjac** [comment]
@Yaswanth-Perumalla this looks great, I'm currently working on an adapted version of the work that you've done to export a non-rasterized pdf output. I wanted to inform you so that we're not stepping on each others' toes.

**Comment by mdeshmu** [comment]
@fisjac please link your PR with one so that folks can know the status of implementation. Thanks for taking this up.

**Comment by aimmon** [comment]
I have a question. The photos downloaded from the Dashboard charts are a bit blurry and not high-definition. If I want to achieve high-definition, I don't know how to modify the code, or I need to use algorithms or deep learning algorithms to make the images high-definition. However, this comes at a high cost
@kasiazjc 
Thanks.

**Comment by marituhone** [comment]
@Yaswanth-Perumalla  @kasiazjc  i don't still get download pdf option am using version 4.0.0,what configuration should i amend to achive this

**Comment by fisjac** [comment]
@marituhone the pdf feature is accessible in the master branch, but was not included in the 4.0.0 release

**Comment by techieravishah** [comment]
Any idea, by when this will feature will be available in the 4.0.0 version?

**Pull request closed without merging**
