### PR TITLE
feat(translations): Turkish translation files added

### PR DESCRIPTION
**Pull request by coteli**
### SUMMARY

Turkish language translation files created and added. Many UI elements have been translated.

I noticed some mistakes in the pull request I opened earlier, number #27237. Therefore, to avoid complications, I closed that request and opened a new one after making the necessary corrections.

I apologize to those affected by the faulty pull request and thank them for their understanding.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

English
Turkish

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by rusackas** [comment]
@mistercrunch seems like the auto-labeler didn't find it's config here, and didn't add all the i18n labels like it did on this PR's predecessor. Not sure if you happen to know why.

**Comment by geido** [comment]
Hello @coteli thanks for the PR! CI needs a bit of love, some linting required.

**Comment by rusackas** [comment]
You can run the [pre-commit hooks](https://superset.apache.org/docs/contributing/hooks-and-linting/) to fix the linting issues

**Comment by coteli** [comment]
> You can run the [pre-commit hooks](https://superset.apache.org/docs/contributing/hooks-and-linting/) to fix the linting issues

I run pre-commit hooks and all checks have passed. I hope it works, thanks for helping. 
Ekran Resmi 2024-02-28 20 57 43

**Comment by geido** [comment]
Hello @coteli there was a problem with a unit test on master that is affecting this PR. Please, pull fresh master and push back, it should solve the issue. Thank you

**Comment by coteli** [comment]
> Hello @coteli there was a problem with a unit test on master that is affecting this PR. Please, pull fresh master and push back, it should solve the issue. Thank you

Hello @geido, thank you for your advice. I synced my branch with apache:master.

**Comment by rusackas** [comment]
Thanks! Running CI 🤞

**Review by geido — APPROVED** [review]

**Comment by geido** [comment]
@rusackas this might need your stamp

**Review by mistercrunch — APPROVED** [review]

**Review by rusackas — APPROVED** [review]

**Pull request merged**
