### PR TITLE
feat: Add headers for DatabaseModal

### PR DESCRIPTION
**Pull request by hughhhh**
### SUMMARY

Updated DB modal with headers and alerts

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

Screen Shot 2021-05-14 at 5 11 50 PM

Screen Shot 2021-05-14 at 5 11 25 PM

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by eschutho — APPROVED** [review]
lgtm!

**Comment by eschutho** [comment]
🏷 hold:testing!
@hughhhh if you want to create an ephemeral env, I'll do a visual pass as well.

**Comment by Steejay** [comment]
Screen Shot 2021-05-17 at 3 13 08 PM
 can we align these edges

**Comment by Steejay** [comment]
Looks good to me @hughhhh

**Review by betodealmeida — APPROVED** [review]

**Pull request merged**
