### PR TITLE
fix(other): column name in created content on profile page

### PR DESCRIPTION
**Pull request by jinghua-qa**
### SUMMARY

fix column name in created content on profile p

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

Before:
Screen Shot 2021-10-07 at 11 34 51 PM

After:

Screen Shot 2021-10-08 at 11 12 53 AM

### ADDITIONAL INFORMATION

- [x] Has associated issue: Fixes https://github.com/apache/superset/issues/16845
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by geido — CHANGES_REQUESTED** [review]
Hello @jinghua-qa. It's great that you are contributing! There is a problem with this change though. As you can see from your screenshot the date is gone. This is because you need to change the `mutator` function as well, which takes care of populating the date. 

Specifically:

https://github.com/apache/superset/blob/a99f845481cd26be56cd0db6b623279db9a27d24/superset-frontend/src/profile/components/CreatedContent.tsx#L55

To be changed with `created`

https://github.com/apache/superset/blob/a99f845481cd26be56cd0db6b623279db9a27d24/superset-frontend/src/profile/components/CreatedContent.tsx#L56

To be changed with `_created`

The same goes for the other `mutator` function in this file.

**Review by zhaoyongjie — APPROVED** [review]
LGTM

**Review by geido — APPROVED** [review]
LGTM! Awesome job!

**Comment by tenglong3158** [comment]
The column name should be the modification time, not the creation time, is that right? @zhaoyongjie @jinghua-qa

**Comment by ad-m** [comment]
@tenglong3158 you might be interested in https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-a-permanent-link-to-a-code-snippet to simplify code references.

**Comment by tenglong3158** [comment]
Thank you @ad-m ! I'll revise the comment now.

**Pull request merged**
