### PR TITLE
fix(dashboard): Filters panel height

### LINKED ISSUE #15347: [cosmetic][native filter] native filter panel is not long enough in dashboard fullscreen mode
## Screenshot

Screen Shot 2021-06-23 at 10 29 12 PM

## Description
native filter panel is not long enough in dashboard fullscreen mode

### PR DESCRIPTION
**Pull request by geido**
### SUMMARY
It fixes an issue with the Filters panel height not taking the full view height in "Full-screen" mode. Additionally, it fixes an issue for which the panel appeared cut at the bottom while the page was still loading.

Fixes #15347 

### BEFORE
123208296-ab961780-d473-11eb-8c32-dfd920683b4f

### AFTER
Screen Shot 2021-07-13 at 16 34 44

### TESTING INSTRUCTIONS
1. Open a Dashboard with native filters enbabled
2. Observe the left side panel and make sure it takes the full height when loading
3. Click on the dots menu far right and enable the "Full-screen" mode
4. Observe the left side panel and make sure it gets the full height

### ADDITIONAL INFORMATION

- [x] Has associated issue: #15347 
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by geido** [comment]
@jinghua-qa @junlincc @rusackas

**Comment by michael-s-molina** [comment]
This will break the filter bar height in some scenarios:
- Introduce a scroll when it's not required
- Mess with the filter bar height calculation when scrolling


https://user-images.githubusercontent.com/70410625/125475424-5bcb7664-2b0e-4fb4-80e3-d47b139c2577.mp4



The key to fix this is to consider the full-screen state in the `offset` variable:

Screen Shot 2021-07-13 at 11 57 00 AM

**Review by michael-s-molina — CHANGES_REQUESTED** [review]
See comment above.

**Comment by geido** [comment]
Thanks for spotting these issues. Those looked like very safe changes but I was obviously underestimating them! Let me go back to this

**Review by michael-s-molina — APPROVED** [review]
LGTM

**Pull request merged**
