### PR TITLE
feat: remove drill

### PR DESCRIPTION
**Pull request by blcksrx**
### SUMMARY
there is no `sqlalchemy-drill`  that exists in the **PIPY** packages, For installation the correct command is:
```
pip install git+ https://github.com/JohnOmernik/sqlalchemy-drill
```
And this makes become **untrusty**  and **unsafe** to install it, especially using it on the **Apache Licence** Projects

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [x] Removes existing feature or API

### CODE REVIEW

**Comment by cgivre** [comment]
Please do not remove Drill.  As a co-author of the dialect, we can get it pushed to Pypi if that's the issue. 
Thanks,

**Comment by cgivre** [comment]
The Drill sqlalchemy dialect is now available on Pypi with the following command:

```
pip install sqlalchemy-drill
```

Here's the direct link: https://pypi.org/manage/project/sqlalchemy-drill/releases/

**Comment by villebro** [comment]
Thanks @cgivre !

**Comment by cgivre** [comment]
@villebro 
Would you mind closing this issue?
Thx

**Pull request closed without merging**
