### PR TITLE
fix(explore): Reset values in TextControl only when datasource changes

### PR DESCRIPTION
**Pull request by kgabryje**
### SUMMARY
Due to recent changes in #12782 regarding resetting control values when datasource changes, debounce in TextControl component stopped working properly. This was caused by comparing `props.value` with `state.value` and setting `state.value` to `props.value` if they were not equal. Because of using 0.5s debounce, props and state values were always unequal when user typed a new value. This PR fixes the issue by adding a comparison of props and state datasource and updating value only when datasources are not equal.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Before: see https://github.com/apache/superset/issues/13191
After:
https://user-images.githubusercontent.com/15073128/108376726-8ebab080-7203-11eb-8ef2-f3ef73aab2f3.mov

### ADDITIONAL INFORMATION

- [x] Has associated issue: fixes https://github.com/apache/superset/issues/13191
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

CC: @villebro @junlincc 
@nikolagigic @mayurnewase please help review this PR, thanks! (from junlin)

### CODE REVIEW

**Comment by junlincc** [comment]
tested locally, LGTM! ✅ Thank you for the fix!

**Review by villebro — APPROVED** [review]
LGTM, thanks for fixing 👍  The fact that a few simple and seemingly unrelated changes caused a regression like this makes me think we'd need to rethink how these components are structured.

**Comment by ktmud** [comment]
Also related #11985

**Comment by ktmud** [comment]
Hi @junlincc @pkdotson @villebro @kgabryje  , going back to the original PR (#12782 ) that introduced this bug, I don't think `TextControl` should be included in the controls that reset values when users change datasource. Because most of the time, the input value in `TextControl` is not datasource specific---i.e. they are not related to columns and metrics. 

I'm going to remove the reset logic in my [control refactoring PR](https://github.com/apache/superset/pull/13221) if you don't mind.

**Comment by junlincc** [comment]
@ktmud I do mind but go ahead

**Comment by junlincc** [comment]
@ktmud remove it all or just text input?

**Comment by ktmud** [comment]
@junlincc Just the text control. As discussed in https://github.com/apache/superset/pull/12782#issuecomment-770119750 , the reset logic should be only applied to controls that depend on datasource columns/metrics.

**Comment by junlincc** [comment]
@ktmud
i am curious when users change dataset, do they also change chart type as well? 
do users create new chart by clicking +button, or from the explore view by changing dataset and chart type.

**Pull request merged**
