### PR TITLE
docs: add a FAQ about asset recovery from UI

### PR DESCRIPTION
**Pull request by mdeshmu**
### SUMMARY

Address bugherd task 35

cc: @sfirke @rusackas 

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by mdeshmu** [comment]
pre-commit failure is not related to this PR.

`tests/unit_tests/db_engine_specs/test_clickhouse.py:66: error: Argument 1 to "NewConnectionError" has incompatible type "str"; expected "HTTPConnection"  [arg-type]`

**Comment by john-bodley** [comment]
@mdeshmu would you mind providing links to the issues you mentioned to aid with context?

**Review by sfirke — APPROVED** [review]
LGTM!

**Comment by sfirke** [comment]
@john-bodley do you mean the referenced BugHerd issue?  It's at https://www.bugherd.com/projects/334204/tasks/35, let me know if you'd like me to add you to the BugHerd tracker if you're not already on there.

**Comment by mdeshmu** [comment]
This is ready to merge

**Comment by sfirke** [comment]
thanks for all the docs PRs @mdeshmu !

**Pull request merged**
