### PR TITLE
style(explore): clarify ambiguously named "sort by" field

### PR DESCRIPTION
**Pull request by sfirke**
### SUMMARY
Users sometimes don't understand the field with the ambiguous name "Sort By".  For instance, in https://github.com/apache/superset/issues/30238 someone expected it would govern the order of the bars along the axis.  Other times they think it will sort the order of series on a dimension field.  These two kinds of sorting have more clearly-named fields; this "Sort By" sorts the underlying data which is relevant only in the case where a row limit or series limit is reached.

This PR renames that field from "Sort By" to "Data Limit Sort By".

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
**BEFORE**
image

**AFTER**
image

### CODE REVIEW

**Review by rusackas — APPROVED** [review]
LGTM. It's an improvement for sure, but I wonder if there are any other label choices... the wording feels awkward even if clearer :) I'm a little stumped ¯\\\_(ツ)_/¯

**Comment by sfirke** [comment]
I hear you @rusackas, I went back and forth... of the Copilot suggestions, the other contenders I liked were "Pre-Render Sort By" and "Truncation Sort By" -- do you like one of those better?

**Comment by michael-s-molina** [comment]
I'm also not sure about Data Limit Sort By... Maybe `Data Sort By` or `Query Sort By`? I'm ok with you don't find a better name for it.

**Comment by sfirke** [comment]
I like `Query Sort By`, that makes it clear it's a backend thing.

**Comment by rusackas** [comment]
> I like `Query Sort By`, that makes it clear it's a backend thing.

Sort Query By?

**Comment by sfirke** [comment]
I updated the label text to `Sort query by`.

And I updated the tooltip.  This sorts the query result which affects data download + drilling so doesn't matter only in the case that a limit is reached -- another reason that your suggestions are better than the original idea.

**Comment by sfirke** [comment]
This one Cypress test keeps failing with a vague error message. Is there a way to tell if there is a Cypress test that is failing because this label changed or if it's just flaky?

**Pull request merged**
