### PR TITLE
chore: correct a typo

### PR DESCRIPTION
**Pull request by dl57934**
chore: typo persistance -> persistence

### SUMMARY

correct a typo persistance -> persistence

### TESTING INSTRUCTIONS

helm values.yaml comment change so don't need testing

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by sfirke — APPROVED** [review]

**Comment by sfirke** [comment]
This seems to need code owner review from one of three people so I can't merge it, but looks good to me - thank you!

**Review by rusackas — APPROVED** [review]

**Comment by rusackas** [comment]
It seems you need to bump the helm version. I think you can do this by running the pre-commit hooks. 

Superset uses Git pre-commit hooks courtesy of [pre-commit](https://pre-commit.com/). To install run the following:
```
pip3 install -r requirements/development.txt
pre-commit install
A series of checks will now run when you make a git commit.
```
Alternatively it is possible to run pre-commit by running pre-commit manually:
```
pre-commit run --all-files
```

**Review by mistercrunch — APPROVED** [review]

**Comment by dl57934** [comment]
> @mistercrunch unless there's a better command to bump the helm charts, we should copy-paste your CI failure logs about pre-commit to this GHA as well. I can do it sometime, if you're not in the mood to do so :)

**Comment by dl57934** [comment]
> @mistercrunch unless there's a better command to bump the helm charts, we should copy-paste your CI failure logs about pre-commit to this GHA as well. I can do it sometime, if you're not in the mood to do so :)

**Comment by mistercrunch** [comment]
Looks like this need an approval from @dpgaspar or @villebro to be merged

**Review by dpgaspar — APPROVED** [review]

**Pull request merged**
