### PR TITLE
[sql-lab] only scroll the result set table

### LINKED ISSUE #2231: [sql-lab] results table ui bug
make results action buttons and search input field fixed even if results table needs to scroll left/right.

- move the `overflow:auto` rule from the parent div to the table container div.

fixed:
sql-table-scrolling-fixed

currently:
sql-table-scrolling

### PR DESCRIPTION
**Pull request by ascott**
before:
sql-lab-table-scrolling-before

after:
sql-lab-table-scrolling

fixes: https://github.com/airbnb/superset/issues/2231

todos:
- [ ] make table header fixed

@airbnb/superset-reviewers

### CODE REVIEW

**Comment by mistercrunch** [comment]
I think there was a related requirement to keep the headers on top. We may want to have a wrapper around the Table component that adds this as an extra prop "fixedHeaders"

**Comment by mistercrunch** [comment]
Oh now I'm noticing that the proportion of the page dedicated to viewing data is overall much smaller after the change. There should be a way to first scroll until the headers are at the top of the page, and then only scroll within the dataset.

**Comment by ascott** [comment]
with this change i'm trying to duplicate the airpal ui where only results are scrollable. 

agreed that the table headers need to remain fixed before merging this in.

airpal-ui

i remember in an earlier prototype you had added a toggle to resize the results pane and sql editor, we could add that back in as well so users can make the results area larger if they want.

**Comment by ascott** [comment]
closing this in favor of two smaller PRs. one for the quick formatting win, and another next week for the refactored table component.

**Pull request closed without merging**
