### PR TITLE
Minor improvements to SQL Lab UI

### PR DESCRIPTION
**Pull request by kristw**
### Several improvements to the SQL Lab UI

- Adjust the vertical position of caret in the tab and reduce padding on the right
- Improve vertical alignment of x and arrow in Select control
- Separate table dropdown from database and schema because it is not mandatory and also behave differently. Add more description of what it actually does.
- Move the collapse button in the front. Wrap table names in backticks (\`\`)
- Align the x button and data types 

sqllab-left-editor

- Align the icons and text in the dropdown menu

sqllab

- Remove word "for" and use ":" instead to shorten. Also wrap table name in backtick, similar to the schema on the left side.

superset_and_superset

- Add new table on top instead of bottom. To avoid user not seeing new table added when the current table(s) exceed the screen.

superset_and_superset-2

@williaster @graceguo-supercat @conglei

### CODE REVIEW

**Comment by williaster** [comment]
These look great! 🙌 

I'll 👀 more closely, my only high-level thought for now is about the "See table Schema" change. I thiiiink if you don't add a table, you can't actually query it in the SQL lab editor which is why it was labeled "add table". If that's true I wonder if "add table to workspace" or something would be a better label? Just a thought.

**Comment by kristw** [comment]
I can query without adding a table. Only `database` and `schema` are required.

superset

**Comment by williaster** [comment]
ah got it 👍 (sorry I should have just checked that before flagging)

**Review by williaster — APPROVED** [review]
LGTM 💯 ✨

**Pull request merged**
