### PR TITLE
chore(Dashboard): Highlight errored filters on the left pane of the Native Filters form plus several enhancements

### PR DESCRIPTION
**Pull request by geido**
### SUMMARY
This PR introduces several enhancements to the native filters form and some new functionalities:

- It shows [untitled] on the left pane when no name is entered. This is consistent with other parts of the platform
- It shows an error indication on the left pane when an error is generated on the fly or on save. This drags the attention of the user to the right filters where an action is required
- It restructures a little bit the form using the Antdesign `Form.Item` wherever possible. However, the constraints of this implementation are huge and I advocate for a full refactor _asap_

### AFTER

https://user-images.githubusercontent.com/60598000/136043592-7eaa2ca3-475a-40e0-87a7-35a40691d1c2.mp4

### TESTING INSTRUCTIONS
1. Open a Dashboard with native filters enabled
2. Fill in the form and observe the behavior when an error is generated

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by geido** [comment]
@mihir174 @junlincc @rusackas the proposed layout with a red title with a red icon indicator is tentative. Feel free to come up with better suggestions and I'll be happy to change accordingly. Thank you!

**Comment by michael-s-molina** [comment]
Thanks for the feature @geido. Some points:
- When creating a new filter, the name is "New Filter" and not "[untitled]". I liked your idea, so it should start as "[untitled]"
- If you generate an error in a saved filter, like deleting its name, and cancel, the error shows when reopening
- The error icon position will conflict with the drag icon that is being implemented [here](https://github.com/apache/superset/pull/16154). Maybe position it on the right side?
- Should we make the error icon the same as the trash icon?

**Comment by geido** [comment]
Hey @michael-s-molina thanks for your feedback! I implemented what you suggested above and updated the video in the description

**Review by michael-s-molina — APPROVED** [review]

**Review by kgabryje — APPROVED** [review]
The code looks great and I wasn't able to break anything.
1 suggestion - maybe we should disable the save button when there are errors in the form? Currently nothing happens when I click it when there are errors, but there is no indication that the button is unclickable. 
image

PR approved, it's up to you if you want to implement disabled save button in this PR, in another... or not at all 🙂

**Pull request merged**
