### PR TITLE
fix(native-filters): Fix required filters

### PR DESCRIPTION
**Pull request by simcha90**
### SUMMARY

This PR fix CR notes for native filters from here: https://github.com/apache/superset/pull/15506#issuecomment-875420917

1. Remove error message in required filters in filter bar
2. Fix bug when reopens FiltersConfigModal with existed value it's not marked as checked

https://user-images.githubusercontent.com/56388545/124783840-076d9f80-df4e-11eb-90c5-f49bfb9e19aa.mov

3. On the way fix Range filter that doesn't apply default value in next flow:
a. Create Select Filter
b. Switch it's type to Range Filter

4. Removes reset form functionality because of 2 reasons:
a. When form saved or closed now it destroys Ant form, so no need reset it
b. It applies reset before form closed, and it can mess some form fields before it closed

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by michael-s-molina** [comment]
Bug 1: Error adding a filter with a default value:

https://user-images.githubusercontent.com/70410625/124803955-20ffee80-df30-11eb-8679-1823e5d2043d.mp4

Bug 2: Time range filter is not being validated on the filter bar:

https://user-images.githubusercontent.com/70410625/124804561-cf0b9880-df30-11eb-9a66-ecdefb094a29.mp4

**Comment by simcha90** [comment]
@michael-s-molina Hi thanks for review, I fixed bugs that you found and pushed fix 👍

**Comment by junlincc** [comment]
thanks for addressing our comments @simcha90 really appreciate it!

**Comment by michael-s-molina** [comment]
The "Value is required" is still appearing...

https://user-images.githubusercontent.com/70410625/124915291-c0bc8b80-dfc7-11eb-8435-266221f93e94.mp4

**Comment by simcha90** [comment]
@michael-s-molina ooops my miss, sorry, I pushed fix, can you please look one more time, thanks :)

**Comment by simcha90** [comment]
👍 my miss I will look on this on Sunday, thanks!

**Comment by michael-s-molina** [comment]
> 👍 my miss I will look at this on Sunday, thanks!

Ok @simcha90. Let me know when it's ready for review.

**Comment by simcha90** [comment]
@michael-s-molina I fixed, also on the way I fixed some other related bugs when tested this functionality, I updated them in description, thanks

**Review by michael-s-molina — APPROVED** [review]
Thank you for the fixes @simcha90

**Comment by junlincc** [comment]
@simcha90 really appreciate the quick fix! 
cc @adam-stasiak

**Pull request merged**
