### PR TITLE
[feature] Mapbox Polygon support

### PR DESCRIPTION
**Pull request by prasar-ashutosh**
***Mapbox Polygon support***

This pull request is an attempt to implement the feature: https://github.com/apache/incubator-superset/issues/2675

**Background**
We are using superset with Druid in our project at Dataspark, Singtel, Singapore. We needed Mapbox with Polygon support in our project. So we have attempted to solve this problem using react-map-gl , deck.gl and d3. The new visualization is called "Mapbox with Polygon".

**Usage**
- Create a new slice
- Select the datasource as : "birth_france_by_region"
- Select the visualization type : *Mapbox with Polygon* and click on "create a new Slice"
    screen shot 2018-01-30 at 5 52 30 pm
- In the Query section , select the DEPT_ID under "Codes of region/province/department" and select a metric.
- Click on Query. Zoom in/out to adjust if needed. hover around the map to see the details.
screen shot 2018-01-30 at 6 10 01 pm

**Features**
The visualisation supports the following filters/selectors
1. Time
   screen shot 2018-01-30 at 6 00 16 pm  
2. Query
   screen shot 2018-01-30 at 6 01 07 pm  
3. Options
    - GeoJosn : select the geojson layer
    - RGB color sheme : select the Color scheme
    - Map Style : Select the map style
    screen shot 2018-01-30 at 6 03 02 pm
4. Viewport
     screen shot 2018-01-30 at 6 05 50 pm
5. SQL
    screen shot 2018-01-30 at 6 12 21 pm

6. Filters
   screen shot 2018-01-30 at 6 12 50 pm

### CODE REVIEW

**Comment by xrmx** [comment]
Please rebase instead of pushing other people commits

**Comment by prasar-ashutosh** [comment]
Thanks for the suggestion. Will create a new clean pull request and close this one.

**Comment by xrmx** [comment]
@prasar-ashutosh no need to open a new PR please, just update the branch and force push it

**Comment by prasar-ashutosh** [comment]
Sorry i deleted the old fork and branch, will have to create a new one.

**Pull request closed without merging**
