### PR TITLE
fix: Show affected charts when interacting with the filters

### PR DESCRIPTION
**Pull request by michael-s-molina**
### SUMMARY
Shows the affected charts when interacting with the filters in a uniform manner. See before/after videos.

@kgabryje @junlincc @rusackas 

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
https://user-images.githubusercontent.com/70410625/125299067-27f77a00-e2ff-11eb-9648-423d7dc172f0.mp4

https://user-images.githubusercontent.com/70410625/125517061-f18a778e-417c-4439-a450-cab5287159d9.mp4

### TESTING INSTRUCTIONS
See before/after videos.

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by junlincc** [comment]
Click interaction is harder to discover for first time users, but we can just add onboarding steps. 
Your call as long as we have consistency. I just need to update the docs :)

**Comment by michael-s-molina** [comment]
@kgabryje @junlincc @rusackas I inverted the behavior. Now the affected charts are displayed on hover. I'm also dispatching the actions using Lodash `debounce` to avoid unnecessary renders and the blinking effect. I updated the video.

**Review by suddjian — APPROVED** [review]
LGTM, nice work!

**Review by kgabryje — APPROVED** [review]
LGTM!

**Pull request merged**
