### PR TITLE
refactor(frontend): migrate 6 Enzyme-based tests to RTL, part 2

### PR DESCRIPTION
**Pull request by hainenber**
refactor(frontend): migrate 6 Enzyme-based tests to RTL, part 2

### SUMMARY

Remove an unused function and associated tests found when conducting Enzyme-to-RTL migration.

Also migrated a few Enzyme tests to RTL.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

N/A

### TESTING INSTRUCTIONS

GH checks with flying colors! :D 

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by justinpark — CHANGES_REQUESTED** [review]
withAsyncVerification is being used as a custom override logic. Please exclude it from deletion

**Comment by hainenber** [comment]
> withAsyncVerification is being used as a custom override logic. Please exclude it from deletion

Got it. I've reverted its deletion.

**Review by mistercrunch — APPROVED** [review]
LGTM!

**Review by kgabryje — APPROVED** [review]

**Comment by mistercrunch** [comment]
@justinpark , mind lifting the hold around your requested changes?

**Comment by hainenber** [comment]
hello fellas, anything I can do to have this merged? I'm about to have part 3 now :D

**Comment by rusackas** [comment]
Pinging @justinpark on Slack... hopefully we can get this through :D

**Review by justinpark — APPROVED** [review]

**Pull request merged**
