### PR TITLE
Fix more click incompatible changes around underscore/dashes

### PR DESCRIPTION
**Pull request by hajdbo**
as discussed in #6193

### CODE REVIEW

**Comment by hajdbo** [comment]
Cypress failed
Error: No such command "load-test-users".
ERROR: InvocationError for command '/home/travis/build/apache/incubator-superset/superset/assets/cypress_build.sh' (exited with code 2)

**Comment by mistercrunch** [comment]
I think the build may need both your changes AND https://github.com/apache/incubator-superset/pull/6201

**Comment by mistercrunch** [comment]
Mmmh, actually we might need to roll back and use `click<7.0`, go back to underscores.

**Comment by hajdbo** [comment]
The click<7.0 fix has been implemented, so I will close this PR.

**Pull request closed without merging**
