### PR TITLE
chore(deps): bump urijs and xss

### PR DESCRIPTION
**Pull request by villebro**
### SUMMARY
Bump a few JS deps:
- `xss` to latest version `1.0.10`
- `urijs` to latest version `1.19.8`

### TESTING INSTRUCTIONS
CI + manual testing

### ADDITIONAL INFORMATION

- [x] Has associated issue: #18879 (partially addresses the ticket)
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by etr2460** [comment]
looks like the frontend build is failing :'(

**Comment by villebro** [comment]
Unfortunately `npm audit fix` broke stuff. I reverted that and just bumped those two packages, will look at running `npm audit fix` in a separate PR.

**Comment by etr2460** [comment]
>Unfortunately npm audit fix broke stuff. I reverted that and just bumped those two packages, will look at running npm audit fix in a separate PR.

not sure if running `npm audit fix` is worthwhile tbh, see https://overreacted.io/npm-audit-broken-by-design/ and a specific quote:
>[](https://overreacted.io/npm-audit-broken-by-design/#what-next)It doesn’t help that npm audit fix (which the tool suggests using) is buggy. I ran npm audit fix --force today and it downgraded the main dependency to a three-year-old version with actual real vulnerabilities. Thanks, npm, great job.

**Review by etr2460 — APPROVED** [review]
lgtm, thanks!

**Pull request merged**
