### PR TITLE
chore(explore): added tooltips to timepicker

### PR DESCRIPTION
**Pull request by zhaoyongjie**
### SUMMARY

The new timepicker introduce date expression function, so need some online help.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

image

### TEST PLAN

Tested on latest Firefox

### ADDITIONAL INFORMATION

- [x] Has associated issue: https://github.com/apache/superset/issues/12302
- [x] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by junlincc** [comment]
@mihir174 we will need a better UI for timepicker advanced tooltip. can you provide design support in 2 steps, 1. giving some lightweight suggestions to ship this asap 2. incorporate design system guidelines for long term 
thanks! 🙏

**Review by junlincc — COMMENTED** [review]
can we keep the tooltip open, click outside to close so that user can refer to the content. later when we have the documentation ready, we should add link to the icon. lastly, can we use the same info icon with grey background? 
(that whole thing just looks so ugly i can't stand it. 🤦🏾‍♀️) @mihir174

**Comment by mistercrunch** [comment]
i18n! Let's wrap everything we can in `{t('i18n')}`

**Comment by mistercrunch** [comment]
That's a huge tooltip! I'm wondering if we should link out to a new documentation page. Tooltip could say something like `Superset supports powerful date/time expressions. For example [show a few examples], click to see learn more in the Superset documentation.`

**Comment by mihir174** [comment]
@zhaoyongjie 
If there's a page with the syntax info in Superset docs, we should link to that. If that doesn't exist yet, I think staying in context and having the huge modal makes sense for now. 

For the tooltip:
1) i think it would be better if the tooltip didn't cover the inputs - then the user could type while keeping the mouse hovered on the tooltip icon to refer to the syntax
2) @junlincc a persistent tooltip breaks a lot of UI patterns and will be inconsistent. i think if the tooltip doesn't obscure the inputs, users should be able to refer to the content easily
3) here's the correct tooltip icon - https://www.figma.com/file/ToYikUoHLg7fhIBUPZtZb0/Superset-Design-System?node-id=968%3A125277 
4) tooltip icon color should be Grey-4 (B2B2B2)

**Comment by junlincc** [comment]
@srinify Srini, can either Robert or Daniel expedite getting documentation ready for this new feature? all description is written in [feat(explore): time picker enhancement](https://github.com/apache/superset/pull/11418) 🙏

**Comment by zhaoyongjie** [comment]
@mihir174 
Thank you for pointing these out. I changed the tooltip style again. please check the tooltip screenshot.

cc @junlincc 

image

**Review by junlincc — COMMENTED** [review]
tested again, good enough for now. ✅ 
one suggestion: Reset scroll position on popover reopen. 
This is a nice to have, probably not worth too much time doing at this moment. 


@graceguo-supercat @villebro can you both take a look and approve this change? we would like to get it in ASAP. 🙏

**Review by graceguo-supercat — APPROVED** [review]
LGTM. Thanks for the extra work, to make a perfect time picker!

**Comment by graceguo-supercat** [comment]
FYI, I saw Superset had many docs here:
https://superset.apache.org/docs/miscellaneous/issue-codes#issue-1001
we can also share time picker cheatsheet there.

**Comment by zhaoyongjie** [comment]
make time picker syntax to the `miscellaneous` section

cc: @junlincc

**Pull request merged**
