### PR TITLE
use full name for data sources

### PR DESCRIPTION
**Pull request by yileic**
Use full name for datasource, so that users are more clear about which database and which table they are using

screen shot 2017-03-22 at 1 41 43 pm

### CODE REVIEW

**Comment by yileic** [comment]
@mistercrunch @xrmx

**Comment by mistercrunch** [comment]
what does it look like when overflowing?

**Comment by yileic** [comment]
you mean when the name is too long? It looks like the following and it will have a horizontal scrolling bar in the drop down.
overflow
overflow_scroll_to_right

**Comment by yileic** [comment]
Is it acceptable, since it has a scroll bar? @mistercrunch

**Comment by mistercrunch** [comment]
We have some long database names and I'm afraid it will make the important information unreadable, can you bump the width of the component?

**Comment by yileic** [comment]
I feel the component is already a bit too wide visually. Would something like '[table name] in [database name]' instead of '[database name].[table name]' help? Thank you so much for your attention!

**Pull request closed without merging**
