### PR TITLE
Using yarn instead of npm install

### LINKED ISSUE #3115: Cannot build latest fails with gulp sourcemap error
Make sure these boxes are checked before submitting your issue - thank you!

- [ * ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ * ] I have reproduced the issue with at least the latest released version of superset
- [ * ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
Latest HEAD

### Expected results
npm install would install superset

### Actual results
npm ERR! fetch failed https://registry.npmjs.org/gulp-sourcemaps/-/gulp-sourcemaps-1.7.0.tgz

### Steps to reproduce
clone repository
`cd incubator-superset/superset/assets`
`npm install`

### PR DESCRIPTION
**Pull request by mistercrunch**
Also bumping npm and node versions.
fixes https://github.com/apache/incubator-superset/issues/3115

### CODE REVIEW

**Comment by j-zhou-au** [comment]
I also cannot build from a fresh checkout. May I know how to use "yarn" to build? Thanks!

**Comment by teamsoo** [comment]
@j-zhou-au were you able to build using either yarn or npm?

**Comment by j-zhou-au** [comment]
I can build using yarn now. My commands are as follows following
mistercrunch <https://github.com/mistercrunch> 's reply:

# assuming $SUPERSET_HOME as the root of the repo
cd $SUPERSET_HOME/superset/assets

# firstly install yarn with stable Nodejs:

sudo npm cache clean
sudo npm install -g n
sudo n stable

# install yarn, a replacement for `npm install` that is faster and more
deterministic

npm install -g yarn

# run yarn to fetch all the dependencies

yarn

# run build
yarn run build
cd $SUPERSET_HOME
python setup.py install

The building works now and when I run test with:
sh run_specific_test.sh
I meet errors despite most tests being "ok". One of the error messages is
like follows:

======================================================================
ERROR: test_database_schema_hive (tests.model_tests.DatabaseModelTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/work/superset/tests/model_tests.py", line 42, in
test_database_schema_hive
    db = make_url(model.get_sqla_engine().url).database
  File "/home/work/superset/superset/models/core.py", line 571, in
get_sqla_engine
    return create_engine(uri, **params)
  File
"/home/anaconda3/envs/py35/lib/python3.5/site-packages/sqlalchemy/engine/__init__.py",
line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File
"/home/anaconda3/envs/py35/lib/python3.5/site-packages/sqlalchemy/engine/strategies.py",
line 51, in create
    entrypoint = u._get_entrypoint()
  File
"/home/anaconda3/envs/py35/lib/python3.5/site-packages/sqlalchemy/engine/url.py",
line 131, in _get_entrypoint
    cls = registry.load(name)
  File
"/home/anaconda3/envs/py35/lib/python3.5/site-packages/sqlalchemy/util/langhelpers.py",
line 208, in load
    return impl.load()
  File
"/home/anaconda3/envs/py35/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py",
line 2258, in load
    return self.resolve()
  File
"/home/anaconda3/envs/py35/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py",
line 2264, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File
"/home/anaconda3/envs/py35/lib/python3.5/site-packages/PyHive-0.4.0-py3.5.egg/pyhive/sqlalchemy_hive.py",
line 11, in <module>
    from pyhive import hive
  File
"/home/anaconda3/envs/py35/lib/python3.5/site-packages/PyHive-0.4.0-py3.5.egg/pyhive/hive.py",
line 22, in <module>
    import sasl
  File
"/home/anaconda3/envs/py35/lib/python3.5/site-packages/sasl-0.2.1-py3.5-linux-x86_64.egg/sasl/__init__.py",
line 15, in <module>
    from sasl.saslwrapper import *
ImportError:
/home/anaconda3/envs/py35/lib/python3.5/site-packages/sasl-0.2.1-py3.5-linux-x86_64.egg/sasl/
saslwrapper.cpython-35m-x86_64-linux-gnu.so: undefined symbol:
_ZTVNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE

**Comment by teamsoo** [comment]
@j-zhou-au thanks for the instruction. I'll update the result soon.

**Pull request merged**
