### PR TITLE
fix: Handles disabled options on Select All

### PR DESCRIPTION
**Pull request by michael-s-molina**
### SUMMARY
Updates `Select` to correctly handle disabled options on Select All.

Follow-up of https://github.com/apache/superset/pull/22084

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
https://user-images.githubusercontent.com/70410625/214135879-d4502cc7-3e8a-4543-883d-4637b07d7ad0.mov

### TESTING INSTRUCTIONS
- Select All should count only disabled options that are selected initially.
- Select All should NOT count disabled options that are unselected.
- Select All shouldn't change the original state of disabled options.
- Clear All should preserve disabled options that are selected initially.

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by kgabryje** [comment]
Selecting all correctly ignores the disabled option, but un-selecting all does include the disabled option.
Example: We have options "A", "B" and "C". Option "A" is selected by default and disabled so that user can't unselect it. Clicking "Select all" correctly adds options "B" and "C" to selection, but clicking it again unselects all options, including disabled "A".

**Comment by michael-s-molina** [comment]
> Selecting all correctly ignores the disabled option, but un-selecting all does include the disabled option. Example: We have options "A", "B" and "C". Option "A" is selected by default and disabled so that user can't unselect it. Clicking "Select all" correctly adds options "B" and "C" to selection, but clicking it again unselects all options, including disabled "A".

@kgabryje Can you provide an example? I tested in the Storybook but was not able to reproduce the bug.

https://user-images.githubusercontent.com/70410625/216078994-52d2fc12-5eb6-4605-82aa-8bef4fed371e.mov

**Comment by kgabryje** [comment]
> @kgabryje Can you provide an example? I tested in the Storybook but was not able to reproduce the bug.

I think there's a problem with `Select`'s `onChange` function. When selecting/deselecting, `onChange` provides an array of all currently selected item ids. So when there is a disabled option that is selected by default, un-clicking `Select all` should call `onChange` with an array containing the disabled option's id. Instead, it's passing an empty array.

Mock piece of code that should allow to repro this example:

```
const [selectValue, setSelectValue] = useState(1);
const options = [{ value: 1, disabled: true }, { value: 2 }, { value: 3 }];
const handleChange = (selected) => setSelectValue(selected); 
return <Select options={options} value={selectValue} onChange={handleChange} />
```

In this example, value `1` should be selected by default and be un-selectable. Un-selecting all will call `onChange` with an empty array and un-select value `1`.
Of course, I could work around it by adding logic to `handleChange` to ensure that `1` stays selected, but I think it'd be better to have that logic in `Select` component.

**Comment by michael-s-molina** [comment]
> I think there's a problem with Select's onChange function.

@kgabryje There was a problem indeed! I submitted a fix for it in my last commit.

**Review by geido — APPROVED** [review]
LGMT!

**Pull request merged**
