### PR TITLE
docs: Show clickable link instead of code-formatting

### PR DESCRIPTION
**Pull request by pylipp**
### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by villebro — APPROVED** [review]
LGTM, thanks for the fix! One thing worth considering is moving the backticks inside the link (probably the original intent). But this is a matter of taste.

**Comment by pylipp** [comment]
> LGTM, thanks for the fix! One thing worth considering is moving the backticks inside the link (probably the original intent). But this is a matter of taste.

In the top part of the paragraph, mysqlclient is not formatted in backtics either, so I propose the same format is used for the part that I updated.

**Comment by villebro** [comment]
> In the top part of the paragraph, mysqlclient is not formatted in backtics either, so I propose the same format is used for the part that I updated.

Makes sense, will merge once CI passes

**Comment by villebro** [comment]
@pylipp there was an issue on CI which has now been fixed. Are you able to rebase your PR? Thanks!

**Comment by rusackas** [comment]
Just opened a PR pulling in this commit - hopefully it's mergable, and @pylipp will still get the credit. Happy to close that one if you'd rather rebase this... if not, I'll close this one when the other merges. Thanks either way, and join us in #documentation on [Slack](http://bit.ly/join-superset-slack) if you want to contribute to more documentation touchups!

**Comment by rusackas** [comment]
Closing this since we haven't heard back and the copy of it has been merged. Thank you for the alleyoop!

**Pull request closed without merging**
