### PR TITLE
chore: Replace deprecated command with environment file

### LINKED ISSUE #24061: Replace deprecated `set-output` command with environment file
**Describe the issue**
In workflow, `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)

### PR DESCRIPTION
**Pull request by jongwooo**
### SUMMARY

Resolve #24061

Update workflows and shell scripts to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)

I found the files that use `set-output` command through the following command:

```bash
$ find . -name '*.yml' -o -name '*.yaml' -o -name '*.sh'  | xargs egrep '\bset-output\b'
```

**AS-IS**

```yml
echo "::set-output name=count::$count"
```

**TO-BE**

```yml
echo "count=$count" >> $GITHUB_OUTPUT
```

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by rusackas** [comment]
Approving CI

**Comment by rusackas** [comment]
@jongwooo would you be able to rebase this? Hopefully we can get it across the finish line.

**Comment by jongwooo** [comment]
@rusackas #26921 made most of the changes, I changed the `set-output` commands that were still left after the rebase.

**Comment by rusackas** [comment]
Thanks @jongwooo - running CI jobs now 🤞

**Review by geido — APPROVED** [review]

**Comment by geido** [comment]
Hello @jongwooo it seems this PR introduced an issue. The unit tests did not launch, thus we did not see this failing. Would you be interested to try this again when this PR that launches the tests is merged in? https://github.com/apache/superset/pull/27297

**Comment by jongwooo** [comment]
@geido Sure thing:)

**Comment by geido** [comment]
Thanks! It is merged now @jongwooo

**Pull request merged**
