### PR TITLE
docs: pointers to plugins blog post

### PR DESCRIPTION
**Pull request by mistercrunch**

### CODE REVIEW

**Comment by ktmud** [comment]
This is definitely useful content to share! Awesome work and thanks for putting this together, @evans !

Two questions:

1. The blog post seems to be encouraging people to share their plugins, but `CONTRIBUTING.md` still kind of discourages it.

   Blog post:

   > If <strike>your</strike> (typo here BTW) your plugin is something you think the entire Superset community can make use of, feel free to open a pull request to superset-ui! For plugins that are more experimental, or for specialized/rare use cases, we plan to provide a better means to publish such viz plugins in the near future (and let you know about it here!).

   incubator-superset/CONTRIBUTING.md:

   > Superset is working towards a plugin system where new visualizations can be installed as optional npm packages. To achieve this goal, we are not accepting pull requests for new community-contributed visualization types at the moment. However, bugfixes for current visualizations are welcome.

   While they do not necessarily conflict with each other, do you think there's a need to reconcile the tones?

2. The FAQ page already has <strike>a section</strike> [two](https://superset.incubator.apache.org/faq.html#how-do-i-create-my-own-visualization) [questions](https://superset.incubator.apache.org/faq.html#how-do-i-go-about-developing-a-new-visualization-type) about creating new visualizations. Maybe merge and update?

I'm also a little concerned about adding links to an external resource that is not part of the Superset project. Apart from the risk of content being outdated, permlinks moved, etc, there also seems to be a conflict of interest that I simply couldn't overlook. Are we comfortable this is how we wanna manage the docs (and potentially new feature releases---there's language like _"let you know about it here"_ in the blog post)? What about other contents Preset may create in the future? And what if some other people want to add their own tutorial posts to the official docs?

Don't get me wrong, Preset has done a great deal of valuable work for viz plugins and we must give credit where credit's due---just wanted to make sure our practice is prudent and future-proof here.

**Comment by mistercrunch** [comment]
@rusackas ^

**Comment by mistercrunch** [comment]
This is one of the most common questions on our Slack / GitHub issues and it seems like a shame not to provide that pointer.

I think we're committed to keeping the blog post alive and up to date, but I agree that it may belong closer to the docs. Maybe we bring that back to the Superset docs in the future as it settles?

**Comment by rusackas** [comment]
@ktmud I did (and do!) intend to bring alignment to the messaging here. We're still working on a path toward dynamic imports, which will really open the floodgates, but in the interim, I'm hoping to propose some changes to `CONTRIBUTING.md` to slightly soften the restriction. Something along the lines that the community can be _open to_ reviewing PRs for new plugins on `Superset-UI if they're applicable to the broader community, but that we might not necessarily accept PRs to add them as default plugins in `incubator-superset`. Do you think that would be a reasonable compromise for the time being?

As for the conflict of interest, I completely understand where you're coming from, and have no intention of ruffling feathers with the community or Apache. I/we do intend to maintain the blog post as needed, while continuing to improve the process. When things are a little further along (both the plugins and the docs), I'm hoping to migrate the content/process into the official Superset documentation, thus replacing the link.

**Comment by rusackas** [comment]
Oh, and thanks for catching that typo, @ktmud :)

**Comment by rusackas** [comment]
Added some copy changes (and random markdown auto-formatting) on [this PR](https://github.com/mistercrunch/superset/pull/251) to your branch, @mistercrunch

**Comment by ktmud** [comment]
Didn't realize we already have a `Resources` section in the README already. I think it makes sense to include these type of resources as they are super useful to the community. It's probably even OK to keep them as external links as they are just nice-to-have learning materials.

I do really hope we can create the new doc site as soon as possible though so that Roadmap/Feature Announcement type of content can have a better home.

> 2\. The FAQ page already has a section [two](https://superset.incubator.apache.org/faq.html#how-do-i-create-my-own-visualization) [questions](https://superset.incubator.apache.org/faq.html#how-do-i-go-about-developing-a-new-visualization-type) about creating new visualizations. Maybe merge and update?

^ Also want to make sure you saw this.

https://github.com/mistercrunch/superset/blob/readme_plugins/docs/faq.rst#how-do-i-create-my-own-visualization

https://github.com/mistercrunch/superset/blob/readme_plugins/docs/faq.rst#how-do-i-go-about-developing-a-new-visualization-type

Can we remove these two questions with outdate examples?

**Comment by rusackas** [comment]
@ktmud Thanks for pointing out those two links. I'll update those in a separate PR if that's OK. Maybe this one could be pushed through otherwise, and I'll pick it up from there?

@mistercrunch looks like this needs a rebase :/

**Comment by kristw** [comment]
Could you update to include my last name?
https://preset.io/blog/2020-07-02-hello-world/

image

**Comment by rusackas** [comment]
> Could you update to include my last name?
> https://preset.io/blog/2020-07-02-hello-world/
> 
> image

Of course! Sorry I missed that!

**Comment by rusackas** [comment]
This one seems to be kind of lingering. @mistercrunch would you mind a quick rebase on this, and @ktmud mind if I address the docs wording in a separate PR?

**Comment by mistercrunch** [comment]
rebased!

**Review by ktmud — APPROVED** [review]

**Pull request merged**
