### PR TITLE
refactor: icon to icons for sliceheader component

### PR DESCRIPTION
**Pull request by pkdotson**
### SUMMARY
mirgrates the filter indicator icon to the icons component

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
before
Screen Shot 2021-07-06 at 7 08 45 PM

after
Screen Shot 2021-07-06 at 9 52 21 PM

### TESTING INSTRUCTIONS
Must enable native filters and crossfiltering feature flags and go to dashboard component

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by pkdotson** [comment]
/testenv up FEATURE_DASHBOARD_NATIVE_FILTERS=true FEATURE_DASHBOARD_CROSS_FILTERS=true

**Review by michael-s-molina — APPROVED** [review]
LGTM

**Pull request merged**
