### PR TITLE
Install superset in Kubernetes with helm chart

### PR DESCRIPTION
**Pull request by cychiang**
Hi,

I created a simple helm chart to easily install superset in Kubernetes.

This helm chart is created by helm v2.9.0 and tested in Kubernetes v1.9.3

- Install with helm: `helm upgrade --install superset ./install/helm/superset`

It should start to install superset into "default" namespace in Kubernetes

The image used in this helm chart comes from: [https://hub.docker.com/r/amancevice/superset](url)

### CODE REVIEW

**Comment by mistercrunch** [comment]
Nice, can you add an entry in the docs? @`docs/installation.rst`

**Review by brylie — APPROVED** [review]

**Comment by cychiang** [comment]
@mistercrunch 
No problem, I have added a short installation guide in `docs/installation.rst`

**Comment by maver1ck** [comment]
@cychiang 
How this chart is connected to 
https://github.com/kubernetes/charts/tree/master/stable/superset
?
Which one is official and should be used ?

**Comment by maver1ck** [comment]
@cychiang I'm asking this question because I'd like to add support for Celery workers to one of the charts and I think I'll go with kubernetes/charts.

**Comment by cychiang** [comment]
@maver1ck 
That is great if you want to contribute your work in superset helm chart. 
Personally, I would say, choose the one you like. 
But I can assure you that if I make any changes of superset helm chart, I will submit pull request to here. 😄

**Comment by ahsanshah** [comment]
Question on this chart...does this work or is it compatible with the Docker/Contrib install steps or are the two different?  I would think given Helm leverages Docker images it may be best to "sync" the 2?  For instance, OOTB helm chart works great.  However, trying to do the chart install with a custom base docker image requires a lot of template changes.

**Comment by cychiang** [comment]
@ahsanshah Hi! This helm chart is based on this image: [amancevice/superset](https://hub.docker.com/r/amancevice/superset/), and it may not be compatible with the image from Docker/Contrib. This is a good idea to leverage Docker/Contrib image to provide a better user experience of the superset. I will spend some time to take a look of Docker/Contrib image and try to leverage it with helm chart if I have free time.

**Comment by charles-zhan** [comment]
@cychiang so what is the default username and password for superset webui when installed with this script.

**Comment by cychiang** [comment]
Hi @charles-zhan, I assume you deploy the superset in Kubernetes cluster and want to know the username and password when open the web UI.

According to the document [here](https://superset.incubator.apache.org/installation.html#getting-started) you need to create username and password by your own. 
Here is the step to create the username and password.
1. Invoke `superset-init` to create an admin account by `kubectl exec -ti ${your_pods_name} -- superset-init`
2. You will enter the interactive mode, and it will request you enter information to create the credential.

3. After you complete all steps, you should be able to login with username and password you provided on the previous stage.

**Comment by newtonjose** [comment]
hey, @cychiang, I need pass new `superset_config.py` to chart, how make it? Tka

**Comment by cychiang** [comment]
Hej, @newtonjose 
I try my best to answer your question since I haven't updating my template for quite a long time. Maybe there're many different ways, but you can make it as following steps:
1. create a `config` directory in helm project root, in this case, same layer as `Chart.yaml`
2. place your `superset_config.py` under that directory
3. deploy your template

What's behind the scene?
You can look at line 27 on `templates/configmap.yaml`, it will generate a Kubernetes configmap resource along when you deploy your template. 
Then, look at line 42 on `templates/deployment.yaml` you can see that it will mount a configmap to a container which is superset. 
After all, you can expect your `superset_config.py` will show up on `/etc/superset/`

**Comment by newtonjose** [comment]
Work good @cychiang , maybe this can be a feature. Something else, I don't see on docs how initialize the superset app, but you explain how do that above. I think have a good solution [like](https://github.com/helm/charts/blob/c8dc1b2b66726b650a61039ec899482c35e72f4b/stable/superset/values.yaml#L15).

Well, I try change `SQLALCHEMY_DATABASE_URI`, but my problem was the `SECRET_KEY` and getting this error `Invalid decryption key`.

**Pull request merged**
