### PR TITLE
fix: Download to CSV shows a special Chinese characters

### PR DESCRIPTION
**Pull request by Habeeb556**
fix: Download to CSV shows a special Chinese characters.

### ADDITIONAL INFORMATION

- [x] Has associated issue: #29224, #29410
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by mistercrunch** [comment]
Let's not downgrade every single installs because of a particular issue that's important to few. Is there a werkzeug-specific documented issue for this? I'd much rather push forward rather then stepping back.  

If we think this is important enough to prevent certain version, the proper way to do it would be to change the range in pyproject.toml and add a comment right above where we set the range explaining why the upper bound is in effect, ideally linking to a werkzeug-hosted issue.

**Comment by Habeeb556** [comment]
> Let's not downgrade every single installs because of a particular issue that's important to a few, as it's fair to assume that many others may need the progress that exists since that version was published. Is there a werkzeug-specific documented issue for this? I'd much rather push forward rather then stepping back.
> 
> If we think this is important enough to prevent certain version, the proper way to do it would be to change the range in pyproject.toml and add a comment right above where we set the range explaining why the upper bound is in effect, ideally linking to a werkzeug-hosted issue.

I agree with you; I think it's related to non-English characters. I have opened a bug issue case with Werkzeug to check on this: https://github.com/pallets/werkzeug/issues/2922. This bug appeared starting from `version 3.x`.

**Comment by mistercrunch** [comment]
Closing for now, happy to push Werkzeug dependency forward when the fix is in

**Comment by Habeeb556** [comment]
Hi again, I have reproduced the issue in both Superset v4 and v5 and traced it to `Werkzeug 3.x` and v2. The problem happens when exporting CSVs with utf-8-sig (used for non-English characters (e.g., Arabic, Chinese, etc.). I have opened a https://github.com/pallets/werkzeug/issues/3057 after reviewing their 3.x changelog — looks like the enforced UTF-8 behavior (from PR https://github.com/pallets/werkzeug/issues/2602) is the cause.

While downgrading to `Werkzeug==2.3.8` resolves the issue, it's not ideal — that version was flagged in issue #28623 due to a CVE, so relying on it long-term is risky.

**Comment by davidism** [comment]
The only thing the change in Werkzeug did was remove the ability to configure anything but utf-8 for automatic encoding. You can still encode text manually, passing the exact bytes you want to respond with: `Response(text.encode(...))`

**Comment by Habeeb556** [comment]
> The only thing the change in Werkzeug did was remove the ability to configure anything but utf-8 for automatic encoding. You can still encode text manually, passing the exact bytes you want to respond with: `Response(text.encode(...))`

Thanks @davidism, I already do this manually encodes the CSV string before returning it in the response. Since **Werkzeug 3** removed support for automatic encoding configuration, I update `superset/commands/sql_lab/export.py`

```
# Manual encoding using the specified encoding (default to utf-8 if not set)
csv_string = csv.df_to_escaped_csv(df, index=False, **config["CSV_EXPORT"])
csv_data = csv_string.encode(config["CSV_EXPORT"].get("encoding", "utf-8"))
```

To replace:

`csv_data = csv.df_to_escaped_csv(df, index=False, **config["CSV_EXPORT"])`

And it passed successfully.

**Pull request closed without merging**
