### PR TITLE
feat(helm): Make Chart.AppVersion default value for image tag

### PR DESCRIPTION
**Pull request by dnskr**
### SUMMARY
The PR adds `appVersion` to `Chart.yaml`, pins default Superset version to `2.0.1` and uses it as a default value for image tag. The same logic is used in many other official helm charts.
This change also eliminates confusing `helm search repo` output saying chart deploys Superset 1.0:
```
$ helm search repo
NAME              CHART VERSION   APP VERSION     DESCRIPTION
argo/argo-cd        5.19.6          v2.5.7          A Helm chart for Argo CD, a declarative, GitOps...
...
minio/operator      4.5.8           v4.5.8          A Helm chart for MinIO Operator
...
superset/superset   0.8.4           1.0             Apache Superset is a modern, enterprise-ready b...
```

### TESTING INSTRUCTIONS
Check that the right value is used by default `helm template test ./helm/superset`
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-superset
  ...
spec:
  containers:
    - name: superset
      image: "apache/superset:2.0.1"
```
and with custom image tag `helm template test ./helm/superset --set image.tag=custom`
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-superset
  ...
spec:
  containers:
    - name: superset
      image: "apache/superset:custom"
```

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by craig-rueda — APPROVED** [review]

**Comment by dnskr** [comment]
@craig-rueda Not sure why `helm-docs` hook failed. Should I revert `helm/superset/README.md` changes?

**Comment by craig-rueda** [comment]
Please re-gen `/charts/superset/README.md` using `helm-docs`

**Comment by dnskr** [comment]
> Please re-gen `/charts/superset/README.md` using `helm-docs`

Done

**Comment by dnskr** [comment]
> Please re-gen `/charts/superset/README.md` using `helm-docs`

Done

**Review by craig-rueda — APPROVED** [review]

**Comment by craig-rueda** [comment]
Looks like `helm-docs` hook is failing still

**Comment by dnskr** [comment]
> Looks like `helm-docs` hook is failing still

Are there any ideas why?
I've changed line separators from `CRLF` to `LF` and force pushed changes. Hope it will help.

**Comment by craig-rueda** [comment]
You can always try running `pre-commit` locally to verify if this doesn't work

**Comment by dnskr** [comment]
I have the same `pre-commit` output locally, so it doesn't help to solve the issue.
@sergeyshevch Could you please have a look what might be the issue since your commit is the last and successfully passed tests?

**Comment by sergeyshevch** [comment]
@dnskr It can be my bad. I didn't execute pre-commit and I ran helm-docs directly instead. I can look more into it on Monday.

**Review by dpgaspar — APPROVED** [review]

**Comment by dpgaspar** [comment]
@sergeyshevch this was a problem we had on CI, was fixed here: https://github.com/apache/superset/pull/22907
so please rebase

**Comment by sergeyshevch** [comment]
I guess it's more for @dnskr

**Comment by dnskr** [comment]
@dpgaspar Done! Please approve to run tests.

**Review by dpgaspar — APPROVED** [review]

**Pull request merged**
