### PR TITLE
feat(alerts-reports): adding pdf filetype to email and slack reports

### PR DESCRIPTION
**Pull request by fisjac**
### SUMMARY

Adding requested pdf filetype to options for alerts and reports

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

Before:
https://www.loom.com/share/accb313d566e413d9ee572a5da86f07c

After:
https://www.loom.com/share/7e52e6e95d094f6192cb84dea3d2a4f9
### TESTING INSTRUCTIONS

Create an alert or report a dashboard or chart. Select the pdf option under content format. Save the report and activate it. The report should send as a pdf.
### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [x] Required feature flags: ALERT_REPORTS=True
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by eschutho — APPROVED** [review]
Thanks @fisjac, this looks really great! LGTM!

**Comment by Shah-Panam** [comment]
In which version will this feature be available?

**Comment by eschutho** [comment]
@Shah-Panam This feature will go into the 4.1 release in/around May.

**Comment by Shah-Panam** [comment]
@eschutho Thanks for letting me know.

**Pull request merged**
