### PR TITLE
Change kv content-type to text/plain

### PR DESCRIPTION
**Pull request by rahul-rahul-sp**
### CATEGORY

Choose one

- [X] Bug Fix
- [ ] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY

Superset provides endpoints for storing and retrieving key-value pairs from database storage. For example, /explore/kv/store takes a data POST parameter for an arbitrary string to store and returns the corresponding key, which is a simple integer counter. To retrieve the saved data, users issue a GET request to /explore/kv/<key>. The application returns the associated value with the response Content-Type set to text/html, meaning it is possible for users to construct arbitrary HTML pages.
The attacker can simply create another key-value pair with JavaScript source code in the value and include it from the constructed HTML page. Since the script source comes from the same origin as the HTML page, the CSP permits the browser to execute it

### TEST PLAN
Tested that the value returned is text/plain

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by rahul-rahul-sp** [comment]
test this please

**Review by mistercrunch — CHANGES_REQUESTED** [review]
The linter wants you to use single quotes instead of double. Otherwise LGTM

**Comment by rahul-rahul-sp** [comment]
seeing this error:
https://travis-ci.org/apache/incubator-superset/jobs/529428886

seems unrelated to my changes

**Review by mistercrunch — APPROVED** [review]

**Comment by mistercrunch** [comment]
Looks like a flaky test, I restarted to confirm.

**Comment by rahul-rahul-sp** [comment]
can this be merged please?

**Pull request merged**
