### PR TITLE
feat: move supersetbot out of repo

### PR DESCRIPTION
**Pull request by mistercrunch**
This PR
- moves `supersetbot` out of here and onto here https://github.com/apache-superset/supersetbot
- improves the GHA to set it up

### CODE REVIEW

**Comment by mistercrunch** [comment]
I decided to move the bot out of this repo and onto here -> https://github.com/apache-superset/supersetbot

**Comment by rusackas** [comment]
Just curious, is this out of necessity, or just easier to work on it? It might be nice to move it back into Superset/ASF control once the dust settles if it's just to make it easier to get things spun up and tested for a while.

**Comment by mistercrunch** [comment]
Yes the main reason is it doesn't require the same level of scrutiny and rigor as the main repo, and it can have it's own CI/release cycles/tests, .

**Review by rusackas — APPROVED** [review]
Sounds reasonable... perhaps one day it can make a grand homecoming or something. I think the main thing is we need docs on the wiki so we can evangelize its use.

**Comment by mistercrunch** [comment]
Right, it can always move back here once things settle.

**Pull request merged**
