### PR TITLE
fix: change listivew card layouts to the new homepage card layout

### LINKED ISSUE #16155: [card view] card size shrink in dashboard list and chart list
Card size shrink in dashboard list and chart list

### Expected results

Screen Shot 2021-08-09 at 11 49 31 AM

### Actual results

card size in dashboard list and chart list shrink to a shorter size

#### Screenshots

dashboard list 
Screen Shot 2021-08-09 at 2 40 36 PM

chart list
Screen Shot 2021-08-09 at 2 40 21 PM

#### How to reproduce the bug
Thumbnail enable:

1. Go to dashboard list or chart list
2. See error

### Environment

(please complete the following information):

- superset version: latest master
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by pkdotson**
### SUMMARY
This pr updates the listview cards layout to the new the homepage cards layout with smaller fit to screen cards.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

before
Screen Shot 2021-08-10 at 9 46 10 AM

after
https://user-images.githubusercontent.com/17326228/128899471-dab2b6c2-7b2f-4667-be34-558b283cc581.mov

### TESTING INSTRUCTIONS
Go to listviews and change to card view to explore the new layout

### ADDITIONAL INFORMATION

- [x ] Has associated issue: fixes https://github.com/apache/superset/issues/16155, 
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by michael-s-molina** [comment]
Screen Shot 2021-08-10 at 3 40 46 PM

Because the three dots icon has a padding, it's giving the impression that the card content has different left and right margins.

**Comment by michael-s-molina** [comment]
Probably not related to this PR but deleting the last item of a page does not navigate to the previous page.

https://user-images.githubusercontent.com/70410625/128918634-d75c3d3d-bfc4-4475-bc9a-deb80096a7ec.mov

**Comment by rusackas** [comment]
I think you can remove `CardStylesOverrides` from `CRUD/utils.tsx`

**Comment by junlincc** [comment]
Thanks so much for the PR!! In the following PR, can we make card view sticky? currently if I refresh the page or go back, it takes me to list view instead. Not urgent. 🙏

**Review by betodealmeida — APPROVED** [review]
Looks good!

**Pull request merged**
