### PR TITLE
Revert "feat: add rolling window support to 'Big Number with Trendline' viz"

### PR DESCRIPTION
**Pull request by etr2460**
Reverts apache/incubator-superset#9107

This change broke rendering of NULL values in the Big Number with Trendline viz. NULL values now render as 0, which is misleading. I'm reverting as this is a data accuracy bug and is fairly high priority.

Repro steps:
- Run a query like this in SQL Lab:
```
SELECT *
   FROM (
         VALUES ('2020-02-29',
                 4), ('2020-03-01',
                 1), ('2020-03-02',
                      NULL), ('2020-03-03',
                              2), ('2020-03-04',
                              3)) AS t (ds, value)
```
- Explore it and select the big number with trend line viz
- See 0 instead of NULL in the trendline

Screen Shot 2020-03-16 at 1 47 37 PM

to: @john-bodley @mistercrunch @kristw

### CODE REVIEW

**Review by john-bodley — APPROVED** [review]

**Comment by willbarrett** [comment]
@etr2460 was an effort made to reach out to @mistercrunch or anyone else at Preset to come up with a solution to this bug before issuing a revert?

**Comment by etr2460** [comment]
As per the revert guidelines, I've informed the original PR author on the revert, provided concise repro steps, and gotten the revert reviewed.

As this is a regression caused by a new feature and not a bug fix, and because this is a pretty severe data accuracy issue, I moved towards reverting the PR vs attempting a fix. A fix can be added to the original commit, unit test added, PR-ed out, and reviewed pretty quickly

**Comment by willbarrett** [comment]
Preset has been discussing this internally, and we believe this is a one-line fix. We think that counter-indicates a revert, and are happy to provide a PR so that we can roll forward here instead of roll back.

**Comment by etr2460** [comment]
A couple questions (note that regardless of fix difficulty/complexity I'm still strongly in favor of reverting first, then re PR-ing with both the original commit and the fix):
- What is the ETA on the fix?
- Does the fix include a unit test?
- How confident are we that the fix will completely resolve the issue?

**Comment by mistercrunch** [comment]
Sorry about the inconvenience, how about: https://github.com/apache/incubator-superset/pull/9314 ?

**Comment by etr2460** [comment]
Pausing this pending #9314

**Comment by john-bodley** [comment]
Personally I think we should revert per the guidelines as the pending PR doesn’t have a unit test. We should strive to keep `master` as stable as possible.

**Comment by willbarrett** [comment]
I'm working on a unit test for the related PR now. I do not think waiting a small period of time for the fix to become stable is unreasonable. I do think pushing through a revert when engineers responsible for the relevant code are available and responding is a questionable choice. It creates unnecessary friction in the community for only momentary gain.

**Comment by etr2460** [comment]
closing as the fix was merged

**Pull request closed without merging**
