### PR TITLE
fix(embedded): Add translation to embedding error messages

### PR DESCRIPTION
**Pull request by Ralkion**
### SUMMARY
Added translation strings for the error messages used when embedding a dashboard fails. This is related to https://github.com/apache/superset/issues/27426, but does not solve that issue. This PR is purely to add the translation function, and the appropriate French strings - even though the system does not yet properly translate.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
N/A

### TESTING INSTRUCTIONS
N/A

### ADDITIONAL INFORMATION

- [x] Has associated issue: https://github.com/apache/superset/issues/27426
- [x] Required feature flags: `EMBEDDED_SUPERSET`
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by john-bodley** [comment]
Thanks @Ralkion for the change. It seems like there might be something borked with your environment as the generated JSON file no longer contains the correct formatting. Would you mind trying to correct this?

**Comment by Ralkion** [comment]
Sure thing - good catch @john-bodley. I noticed the formatting change, but thought it was just something that got caught in post processing somewhere. Turns out my `prettier` binary had lost +x permissions. Quick `chmod` fix it all up.

**Comment by Ralkion** [comment]
@john-bodley -> Anything else I need to do with this?

**Comment by rusackas** [comment]
Taking another stab at this here: https://github.com/apache/superset/pull/29782

**Comment by rusackas** [comment]
Merged https://github.com/apache/superset/pull/29782, so I think we can close this. Thank you for your help here and elsewhere, @Ralkion!

**Pull request closed without merging**
