### PR TITLE
add hint of filterbox when create (#7458)

### PR DESCRIPTION
**Pull request by doctording**
### CATEGORY

Choose one

- [x] Bug Fix
- [ ] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY

 #7458 
just add a hint of filterbox when created, translations need to do.

the result like this ( a friendly hint to user instead of a confused error)

image

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by villebro** [comment]
@doctording a screenshot before and after would be helpful.

**Comment by doctording** [comment]
> @doctording a screenshot before and after would be helpful.

@villebro , thank you, I'll change my pull request

I just add a hint for the filter required,  but why the filter designed to be required item

**Comment by doctording** [comment]
#: superset/viz.py:1816
msgid "please add at least one filter under the [Filters Configuration]"
msgstr "请在左侧的 [Filters Configuration] 下添加至少一个 filter"

**Comment by mistercrunch** [comment]
Note that people may want to expose a date filter, but no "dimension filter", so we cannot really require it.

**Comment by doctording** [comment]
> Note that people may want to expose a date filter, but no "dimension filter", so we cannot really require it.

thanks. So why the frontend show like this, it should be modified.

image

**Comment by mistercrunch** [comment]
Are you on latest `master`?

**Comment by doctording** [comment]
> Are you on latest `master`?

thanks, I change to  latest `master`, it's ok 

then the error is 

image

**Pull request closed without merging**
