### PR TITLE
[dashboard] more granular grid layout

### PR DESCRIPTION
**Pull request by mistercrunch**
Moving to a grid that is 4 times more granular. 48 columns.
2cabm6nh2v
Shipping a db migration script which will upgrade the position metadata
to reflect this change.

### CODE REVIEW

**Comment by rumbin** [comment]
Thanks!

**Comment by timifasubaa** [comment]
https://github.com/apache/incubator-superset/issues/4014

**Review by graceguo-supercat — APPROVED** [review]
LGTM. 👍

**Comment by mistercrunch** [comment]
closes #4014

**Pull request merged**
