### PR TITLE
[Feature/Bugfix] Datepicker and time granularity options to dashboard filters

### PR DESCRIPTION
**Pull request by Mogball**
As per https://github.com/apache/incubator-superset/issues/1718 and https://github.com/apache/incubator-superset/issues/183, PR adds the ability to set the Time Column (`granularity_sqla`) and Time Grain (`time_grain_sqla`) filters from a dashboard filter, or Time Granularity (`granularity`) and Origin (`druid_time_origin`). 

datepicker_filter

These can be enabled by checking the appropriate boxes in the explore view:

screen shot 2017-10-03 at 12 46 28 pm

Also, the standard drop-down menus for `from` and `to` have been replaced with the same datepicker used for `Since` and `Until` for explore control panels.

EDIT: also addresses https://github.com/apache/incubator-superset/issues/3522

### CODE REVIEW

**Comment by xrmx** [comment]
@mistercrunch this fixes a regression in 0.20.0 #3522

**Comment by mistercrunch** [comment]
I think this is assuming that everyone that wants to expose time filters also wants to expose `granularity` and `time column` in their filter box, which may not be the case. It may also be the case that it would push down other filters that were visible towards a place you may have to scroll to, which could create confusion on existing dashboards.

I think we should add 2 checkboxes to filter_box: `Show Granularity Dropown` and `Show Time Column`, both false by default

**Review by mistercrunch — CHANGES_REQUESTED** [review]
I think this is assuming that everyone that wants to expose time filters also wants to expose `granularity` and `time column` in their filter box, which may not be the case. It may also be the case that it would push down other filters that were visible towards a place you may have to scroll to, which could create confusion on existing dashboards.

I think we should add 2 checkboxes to filter_box: `Show Granularity Dropown` and `Show Time Column`, both false by default

**Comment by joshwalters** [comment]
Once this gets merged in, would it be possible to release a new superset version (`0.20.2`), as it looks like other people are running into problems with this: https://github.com/apache/incubator-superset/issues/3522

**Comment by mistercrunch** [comment]
@joshwalters I usually like to bake releases in Airbnb's production for at least 24 hours, but in this case I should probably cut a branch and cherry pick this on top of `0.12.1`

**Pull request merged**
