### PR TITLE
chore: Moves Tooltip to the components folder

### PR DESCRIPTION
**Pull request by michael-s-molina**
### SUMMARY
Moves `Tooltip` to the components folder.

This work is part of [SIP-61](https://github.com/apache/superset/issues/13632)

@rusackas @junlincc

### TEST PLAN
1 - Execute all tests
2 - All tests should pass

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by rusackas — APPROVED** [review]
LGTM, needs rebase.

This PR also makes me wonder if we couldn't add an `info` prop to the `Tooltip` and add the styling/features of `InfoTooltip` into `Tooltip` that way so that we don't need to maintain two components.

**Comment by michael-s-molina** [comment]
> LGTM, needs rebase.
> 
> This PR also makes me wonder if we couldn't add an `info` prop to the `Tooltip` and add the styling/features of `InfoTooltip` into `Tooltip` that way so that we don't need to maintain two components.

You're totally right. I noticed that now that things are starting to be organized, it's easier to perceive duplicated components or merge-able ones. For me the best example of this is `CertifiedIcon`, `ChartIcon`, `FaveStar`, `IconTooltip`, `RefreshLabel`, `WarningIconWithTooltip`. They could all be merged into an Icon that can be clicked, selected, and have a tooltip. We'll get there in the second wave of refactoring.

**Review by pkdotson — APPROVED** [review]

**Comment by Deena2112** [comment]
Plz don't send

**Pull request merged**
