### PR TITLE
fix: Issue #12004 timegrain not visibile

### PR DESCRIPTION
**Pull request by geido**
### SUMMARY
Fixes an issue that makes the SelectControl options hidden when overflowing.

### TEST PLAN
1. Go to a Dashboard
2. Inside a Filter box open the options of any single-choice dropdown (multi-options dropdowns already worked properly)
3. Make sure the options are visible even when overflowing the filter box container 

### ADDITIONAL INFORMATION

- [x] Has associated issue: #12004 
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by geido** [comment]
@rusackas @junlincc

**Review by junlincc — COMMENTED** [review]
Thanks for the quick fix Diego! 
manually tested. when i resize the filter box with Timegrain to really small, the dropdown got disconnected as I scroll.

https://user-images.githubusercontent.com/67837651/103590359-7f291780-4ea2-11eb-9ec8-a952b445f6c6.mov

couple suggestions for futre:
1. add a video to all the PRs that have UI change or fix 
2. test the feature throughout, resize the window or component from different directions

**Comment by geido** [comment]
@junlincc this is a problem with react-select and this issue was affecting the multi-choice dropdowns already. The issue is known and it is still open. You can read the details here https://github.com/JedWatson/react-select/issues/4088. I will attempt a few possible fixes but there is a high chance that there is no optimal solution for this right now.

**Comment by junlincc** [comment]
> @junlincc this is a problem with react-select and this issue was affecting the multi-choice dropdowns already. The issue is known and it is still open. You can read the details here [JedWatson/react-select#4088](https://github.com/JedWatson/react-select/issues/4088). I will attempt a few possible fixes but there is a high chance that there is no optimal solution for this right now.

got it! thanks for letting me know. if the code looks good, alright to merge :) thanks for the fix!

**Review by junlincc — APPROVED** [review]

**Review by nikolagigic — APPROVED** [review]
LGTM

**Pull request merged**
