### PR TITLE
Avoid fine print.

### PR DESCRIPTION
**Pull request by akuhn**
We should not use 12px font size to avoid agism in design. At age 40, eyesight is about half as good as it did at age 20. I changed all font sizes to be at least 14px. 

Loving the new homepage by the way! :tada: 

Reviewers

- @ascott 
- @mistercrunch

### CODE REVIEW

**Comment by ascott** [comment]
i like the spirit of this PR, and would be happy to make changes to the font size, but i'd like to review these specific cases to see if there is a reason we've bumped the text size down. would be great to include screenshots of the ui that these rules affect.

**Comment by ascott** [comment]
looks like our base font size is 14px, so if we could just remove these rules altogether to get to 14px.

**Comment by akuhn** [comment]
Excited to hear!

Happy to share screenshots internally
- font size of table on home page
- font size of table in sqllab
- font size of tooltips in sqllab
- font size of optional description at top of a dashboard slice 

There is more fine print that I haven't caught yet like the buttons and partition info in sqllab. You can do the following to preview how a 14pt website would look like
- Visit settings
- Click advanced link
- Click customize fonts button 
- Change minimal font size slider to 14

**Comment by mistercrunch** [comment]
This is been open for a while, closing for now. For me hitting `Command-+` is an easy way to adapt the font size.

**Pull request closed without merging**
