### PR TITLE
[log] New, make action log configurable and generic

### PR DESCRIPTION
**Pull request by dpgaspar**
### CATEGORY

- [ ] Bug Fix
- [X] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY
Make event logger configurable and generic

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [x] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by dpgaspar** [comment]
I'm tempted in doing a bigger change. @mistercrunch what do you think about creating a new module with the following structure:

superset/
    log/
       __init__.py (AbstractActionLogger, DBActionLogger, log_this decorator)
       models.py (Log)
       views.py (LogModelView)

**Comment by mistercrunch** [comment]
@dpgaspar the structure looks ok to me as is, my original idea was to just made EVENT_LOGGER a simple function, but the abstraction you have is more modular I guess

It could be good to allow us to shut down the current Log model and ModelView, but these really don't hurt. Main goal here is a hook to allow for hijacking / rewiring these events.

Another PR could add decorate many more views with @logthis

**Comment by dpgaspar** [comment]
Yes, I know it seems over the board this kind of abstraction, but ideally `@log_this` should go out of the `Log` Model class, since we are making it generic, so in the future `AbstractEventLogger` is a good place for the decorator.

**Comment by dpgaspar** [comment]
Rats! :)

**Comment by mistercrunch** [comment]
@dpgaspar the ASF license check is failing, you simply have to add a header to all new files

**Comment by dpgaspar** [comment]
I think I've already done that, logs says:

```
Our attempt to download rat locally to /tmp/lib/apache-rat-0.13.jar failed. Please install rat manually.
ERROR: InvocationError for command /home/travis/build/apache/incubator-superset/scripts/check_license.sh (exited with code 255)
```

**Comment by mistercrunch** [comment]
Mmmh.. trying to force rerun, let's see if that helps.

Oh we just merged a large PR applying `black` you'll want do the same and rebase...

**Review by mistercrunch — CHANGES_REQUESTED** [review]
LGTM except for the fact that some of the new code uses single quotes instead of double quotes, you can probably just run `black` to fix all that.

**Comment by dpgaspar** [comment]
Ok, done

**Review by mistercrunch — APPROVED** [review]

**Pull request merged**
