### PR TITLE
Support multi language for verbose name

### PR DESCRIPTION
**Pull request by roganw**
Supporting local language stored in verbose_name when selecting columns and metrics.

### CODE REVIEW

**Comment by mistercrunch** [comment]
This looks like it would conflict with https://github.com/airbnb/superset/pull/2921

**Comment by RoganW** [comment]
fixed the conflict.

**Comment by RoganW** [comment]
Supporting multi language for verbose name.

**Comment by RoganW** [comment]
@desavera 
This merge request fixed the verbose name of column and metric in the config container of Slice.

And support multi language for the display of column/metric names, by parsing multi_lang_name field which assigned through API or manually.

**Comment by desavera** [comment]
Excellent !

**Comment by markrey** [comment]
Can we merge this one if conflicts are clear?

**Pull request closed without merging**
