### PR TITLE
Rename "slice" to "chart" and update translations

### PR DESCRIPTION
**Pull request by betodealmeida**
This PR renames "slice" to "chart" in all user facing strings. Code has not been updated.

I also regenerated the `messages.pot` file, since it hasn't been updated in a while (`babel.cfg` was still pointing to the old location of Javascript files, before @mistercrunch's reorg), and updated all the `.po` files.

I'll update the `pt_BR` translation on my free time.

```bash
$ fabmanager babel-extract --target superset/translations/ --output superset/translations/messages.pot --config superset/translations/babel.cfg -k _ -k __ -k t -k tn -k tct
$ for LANG in en de es fr it ja pt_BR ru zh
> do
> pybabel update -i superset/translations/messages.pot -d superset/translations -l ${LANG}
> po2json -d superset -f jed1.x superset/translations/${LANG}/LC_MESSAGES/messages.po superset/translations/${LANG}/LC_MESSAGES/messages.json
> done
```

### CODE REVIEW

**Comment by mistercrunch** [comment]
I think translations stopped working since this PR

**Comment by semteu** [comment]
The whole french translation disappeared from the .po file.

**Comment by mistercrunch** [comment]
Should be back in master by now.

**Comment by byc233518** [comment]
@mistercrunch @betodealmeida 
可以这样修改, 不知是否合适,   本地已解决~
-- superset/view/core.py 
image
image

-- superset/assets/src/i18n.jsx
image

**Pull request merged**
