### PR TITLE
fix: Allow chart import to update the dataset an existing chart points to

### PR DESCRIPTION
**Pull request by jfrag1**
### SUMMARY

Currently, attempting to overwrite a chart via import fails when the chart in the import file points to a dataset other than the one the chart currently points at.

This is because of the following filter which gets added to the query that checks if the chart being imported already exists:
```python
filters.extend([getattr(cls, k) == dict_rep.get(k) for k in parent_refs.keys()])
```
which for charts evalulates to
```python
filters.extend([Slice.datasource_id == dict_rep.get("datasource_id")])
```
When the chart's dataset has been changed, the query fails to find the chart even if a chart with the same UUID exists. It then attempts to create the chart since it thinks it doesn't exist, which obviously fails the UUID uniqueness constraint.

This PR allows for charts to be "re-parented" to another dataset on import by removing this filter for chart imports, which can be useful when importing and exporting assets between environments after making changes, or for managing assets as code.

### TESTING INSTRUCTIONS

1. Have a database connection with a dataset
2. Create a virtual dataset identical to the dataset (`SELECT * FROM <physical_dataset>`)
3. Create a chart for each dataset
4. Do a bulk export with both of these charts
5. Extract the export file 
6. Navigate to the charts folder and swap the `dataset_uuid` values for the charts
7. Compress the file
8. Import it back into the Superset instance
9. See the charts have swapped datasets

### ADDITIONAL INFORMATION

- [x] Has associated issue: https://github.com/apache/superset/issues/22506
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by Vitor-Avila** [comment]
This is awesome! Thanks!!!

**Comment by michael-s-molina** [comment]
@jfrag1 I saw yesterday that someone publish a [SIP](https://github.com/apache/superset/issues/24660) about this topic. Should we wait for the SIP before making this change? In the SIP, they are proposing to require explicit confirmation from the user before overriding associated assets. Is this PR going to conflict with the SIP?

**Comment by rusackas** [comment]
The SIP not only proposes the UI to allow choice in the cascade of overrides, but also having a checkbox or similar introduces a place to check for or add ownership/RBAC constraints. I'll add this comment (and others) to the sip as well.

**Comment by Vitor-Avila** [comment]
I think this would only conflict with the SIP in case the chart dataset update also happens when importing a dashboard. Currently the overwrite check is only "applied" to the actual asset being imported -- for example, if you import a dashboard with charts, the dashboard will be overwritten but charts wouldn't. So if this change is only applied when importing a chart directly (or via the `/api/v1/assets/import/` endpoint) I don't think it conflicts.

**Review by betodealmeida — APPROVED** [review]
LGTM!

@michael-s-molina this is not directly related to the SIP you mentioned; it's not doing any cascade imports but just point the chart to a different dataset (which could be new or existing).

**Comment by michael-s-molina** [comment]
Got it. Thanks @jfrag1 @Vitor-Avila and @betodealmeida for the additional context.

**Comment by SharonCastel** [comment]
@jfrag1 finally someone who understands the issue and know how to fix it! You are the best! Can't wait for it...

**Pull request merged**
