### PR TITLE
feat(table): Table with Time Comparison

### PR DESCRIPTION
**Pull request by Antonio-RiveroMartnez**
### SUMMARY
As part of the Time Comparison efforts, we are adding the new controls to the table viz.

### TESTING INSTRUCTIONS
1. Set up a table viz using the new time comparison controls

### ADDITIONAL INFORMATION

- [ ] Has associated issue: https://github.com/apache/superset/issues/27432
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by Smallhi** [comment]
@Antonio-RiveroMartnez  can this feature support PIVOT TABLE ? I tested and found not.

**Comment by Antonio-RiveroMartnez** [comment]
> @Antonio-RiveroMartnez can this feature support PIVOT TABLE ? I tested and found not.

Hey @Smallhi , so far it's not part of the pivot table as you pointed out. Once merged we can consider bringing this to other visualizations like pivot etc, thanks for asking.

**Review by eschutho — APPROVED** [review]

**Pull request merged**
