### PR TITLE
fixed the bleeding dashboard chart issue

### PR DESCRIPTION
**Pull request by MarcusSorealheis**
### CATEGORY

Choose one

- [x] Bug Fix
- [ ] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY
User mentioned Horizon chart was bleeding. I verified that it was and added simple fix. 

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

Before:
Screen Shot 2019-08-12 at 1 27 23 PM

After:

*Dashboard*

dash-horizon-gif

*Explore Chart*

explore-gif

### TEST PLAN
Do we test CSS? I can add if we do, but I did not see that in the project. (honestly didn't look hard)

### ADDITIONAL INFORMATION

- [x] Has associated issue: #7953 
- [x] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### REVIEWERS
@mistercrunch

### CODE REVIEW

**Comment by mistercrunch** [comment]
Oh I think this may cause issues in other charts that are not supposed to scroll (they might show a scrollbar that allows to scroll one or two pixels). We probably want to do like we do with other charts that are scrollable.

Seems like this should do it:
https://github.com/apache-superset/superset-ui-plugins/blob/master/packages/superset-ui-legacy-plugin-chart-horizon/src/HorizonChart.css#L21

Or many we're missing something that would fix the height of the container in the chart itself?

**Comment by MarcusSorealheis** [comment]
@mistercrunch  late on the reply here but I made it so that the height is fixed, rather than scrollable of overflowable (except in the overflowable class). That way, the bleeding is still fixed and nothing is scrollable. I think that's ideal for keeping the dashboard succinct. Screenshot looks the same in this case.

**Comment by MarcusSorealheis** [comment]
I have a better solution. implementing now..

**Comment by mistercrunch** [comment]
I'm having issues with building that other repo, but something like this: https://github.com/apache-superset/superset-ui-plugins/compare/fix_horizon_overflow?expand=1

**Comment by kristw** [comment]
Have you verified how this affect other charts? e.g.
* table
* bar

**Comment by MarcusSorealheis** [comment]
@mistercrunch  On second thought, I think this is the best solution for now.

@kristw 
Hidden doesn't affect any of the other charts in a Dashboard:
Screen Shot 2019-08-12 at 11 23 53 PM
Screen Shot 2019-08-12 at 11 24 01 PM
Screen Shot 2019-08-12 at 11 24 17 PM
Scrolling on tables still works.
Screen Shot 2019-08-12 at 11 24 29 PM
Screen Shot 2019-08-12 at 11 24 45 PM

This change simply bounds all charts in a dashboard in the containing element.

**Comment by MarcusSorealheis** [comment]
@mistercrunch I'll peep what you did there. Thanks

**Comment by MarcusSorealheis** [comment]
I clicked the link after I posted my pictures.

**Comment by MarcusSorealheis** [comment]
I've fixed it to the point where every chart behaves as it did before, and `Horizon` is not allowed to scroll on the dashboards but no one else. Let me make a little video one sec.

**Comment by etr2460** [comment]
Could you also test what happens when charts render error messages from the backend? I've seen error messages overflow in the past when they contain stack traces, and I wonder if this fixes the layout for them too

**Comment by MarcusSorealheis** [comment]
@etr2460 I will check. Please do not merge this as I have observed other issues on Explore Charts.

**Comment by MarcusSorealheis** [comment]
closing this while i work on another approach to solving this issue.

**Comment by MarcusSorealheis** [comment]
[Video of the fix here!](https://drive.google.com/file/d/1reyWm0Szqgd25Ul_5qqzut-XEnyGrKpY/view?usp=sharing)

@mistercrunch I was able to add the fix directly within the superset codebase. Do you prefer changing the upstream?

**Comment by MarcusSorealheis** [comment]
need to for explore view

**Comment by MarcusSorealheis** [comment]
Explore Chart view:

**Comment by MarcusSorealheis** [comment]
I need to check on chrome and safari although it should all be the same

**Comment by MarcusSorealheis** [comment]
everything looks good there

**Comment by MarcusSorealheis** [comment]
Is the decision here to decouple external charts from the main superset application?

**Comment by MarcusSorealheis** [comment]
the bleeding charts issue persists. I added fix to this repo's CSS, but @mistercrunch added a different fix to upstream repo which in an ideal world is more scalable. However, it was not merged.

**Comment by MarcusSorealheis** [comment]
This issue still persists and affects the horizon chart.

**Comment by mistercrunch** [comment]
That was my attempt, I just rebased the PR https://github.com/apache-superset/superset-ui-plugins/pull/180

**Pull request closed without merging**
