### PR TITLE
chore: Update messages.json

### PR DESCRIPTION
**Pull request by Rusta12**
Mistake in ru translation

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by john-bodley — APPROVED** [review]
Thanks @Rusta12 for the fix.

**Comment by john-bodley** [comment]
Actually @michael-s-molina corrected me. You'll have to update the `.po` file.

**Review by rusackas — CHANGES_REQUESTED** [review]
A couple things:
• We should indeed edit the `.po` files, since the `.json` files are generated.
• Are we sure Подитог is correct? I'm hearing that Подытог is the correct spelling. 
• If it _were_ Подитог, should we also correct "Расположение столбцов подытогов" and "Расположение строк подытогов"?

**Comment by rusackas** [comment]
Closing this since it's taking the wrong approach (it should edit .po files)

**Pull request closed without merging**
