### PR TITLE
feat(helm): Add ability to customize affinity per deployment

### PR DESCRIPTION
**Pull request by sergeyshevch**
### SUMMARY

Added ability to add affinity per deployment

Added ability to add topologySpreadConstraints https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/

### TESTING INSTRUCTIONS

- Specify supersetNode.affinity 
- Affinity should be added to helm template result
- Specify global affinity
- Both affinity should be added to helm template result

### ADDITIONAL INFORMATION

- [ x ] Has associated issue: https://github.com/apache/superset/issues/19250
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by craig-rueda** [comment]
Please bump the version in `Chart.yaml` and re-gen the README using `helm-docs`

**Comment by sergeyshevch** [comment]
@craig-rueda Done

**Review by craig-rueda — APPROVED** [review]

**Comment by a-poluyanov** [comment]
Hello, I want my helm-swapped superset to be evenly distributed among the nodes of my cluster and I write like this:
```
# -- TopologySpreadConstrains to be added to all deployments
topologySpreadConstraints: 
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
```
But the pods are still not evenly distributed, does anyone have an example of how this works?
@sergeyshevch Maybe you have an example of even distribution between nodes?

**Comment by sergeyshevch** [comment]
@a-poluyanov You also need to add label selectors

Example: 
```
    topologySpreadConstraints:
      - maxSkew: 1
        whenUnsatisfiable: DoNotSchedule
        topologyKey: kubernetes.io/hostname
        labelSelector:
          matchLabels:
            app: superset
```

Selectors are quite different across deployments
```
app: superset
app: superset-worker
etc
```

**Pull request merged**
