### PR TITLE
docs: add Reward Gateway to README

### PR DESCRIPTION
**Pull request by mistercrunch**
corrects https://github.com/apache/incubator-superset/pull/8533

### CODE REVIEW

**Review by john-bodley — APPROVED** [review]
LGTM. @mistercrunch I appended your PR with a second commit to cleanup line #194.

**Comment by dpgaspar** [comment]
Note: Reward gateway site has an invalid certificate, Common Name (CN)	*.genetex.com

**Review by dpgaspar — CHANGES_REQUESTED** [review]
Reward gateway URL probably is https://www.rewardgateway.com/

**Comment by craig-rueda** [comment]
LGTM

**Pull request merged**
