### PR TITLE
fix: Dropdown menu not closing on Dashboard view

### PR DESCRIPTION
**Pull request by kgabryje**
### SUMMARY
Fixes Menus not closing automatically. It turned out that Antd Menu doesn't work that well with react-bootstrap's DropdownButton, so I replaced it with Antd's Dropdown. We should do the same for other mixes of Menu with DropdownButton soon, as the same issue might occur.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
ezgif com-gif-maker

### ADDITIONAL INFORMATION

- [x] Has associated issue: https://github.com/apache/incubator-superset/issues/11645
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by kgabryje** [comment]
CC @junlincc 
@ktmud Can you please take a look?

**Comment by ktmud** [comment]
I remember before the change the menu for charts would open on the left side of the trigger, now it opens on the right side. Can we make sure it always opens on the left side as the menu could be considered part of the chart and overlaying within the chart container makes sense.

**Comment by kgabryje** [comment]
@ktmud Done
image

**Comment by ktmud** [comment]
Thanks, @kgabryje ! Could you fix the Cypress test, too? Then this one is good to go!

**Pull request merged**
