### PR TITLE
fix: additional lower case text changes

### PR DESCRIPTION
**Pull request by sadpandajoe**
### SUMMARY

Additional missed text from: https://github.com/apache/superset/pull/29673. A few edits here:
* In the dataset editor, changing `Certified By` to `Certified by` in the `Columns` and `Calculated columns` screens
* In the SQL menu, changing from `SQL History` to `SQL history`
* In the SQL menu, changing from `Saved Queries` to `Saved queries`
* In the main menu, changing from `Annotation Layers` to `Annotation layers`
* On a blank tags page, change from `Create a new Tag` to `Create a new tag`

#### Before
Screenshot 2024-09-12 at 9 38 46 AM
Screenshot 2024-09-12 at 9 38 30 AM
Screenshot 2024-09-12 at 8 59 47 AM

#### After
Screenshot 2024-09-12 at 8 59 24 AM
Screenshot 2024-09-12 at 8 59 33 AM
Screenshot 2024-09-12 at 9 36 49 AM
Screenshot 2024-09-12 at 11 19 06 AM

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by yousoph — APPROVED** [review]

**Comment by rusackas** [comment]
Heya! I'm tempted to block on this, but I'll just post a comment instead. 

When changing capitalizations like this, it'll break translations for all of these strings. Can you do a global find/replace that captures these in the .po/.pot files?

If we don't make that change, all the translations will disappear the next time strings are extracted to the .pot files, and .po files get updated.

I'm also adding this to the Town Hall agenda... we need to find a way to capture/enforce this at the PR level or in CI.

**Comment by rusackas** [comment]
Also, that's weird: 
image
¯\\\_(ツ)_/¯

**Review by rusackas — CHANGES_REQUESTED** [review]
Might as well fix the `.po` files containing these strings (and any obvious translated strings next to them), so that we don't regress translations.

**Pull request closed without merging**
