### PR TITLE
perf(native-filters): improve native filter modal form performance

### PR DESCRIPTION
**Pull request by stephenLYZ**
### SUMMARY

Improve native filter modal performance by adding memo or reduce rendering.
### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

Test case : 30+ native filters, 20+ charts

| - | before | after |
| - | - | - |
| re-rendering(counts) | 538 |  4 |
| opening time | 15s | 300 ms |
|  flame graph | image |  image |

### before
https://user-images.githubusercontent.com/11830681/196002347-dad0dfe9-2aef-4107-a5a0-6118d56dbfb6.mov

### after

https://user-images.githubusercontent.com/11830681/196002478-ab260806-de9f-4ca9-98af-5d48a5da8a9a.mov

### ADDITIONAL INFORMATION

- [x] Has associated issue: https://github.com/apache/superset/issues/21147
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by michael-s-molina — COMMENTED** [review]
Great work @stephenLYZ! Really improved the performance. Code LGTM.

During the tests, I found a small issue that may have been there the whole time. These are the steps to reproduce it:
- Select Scoping in the first filter
- Navigate to the second filter
- Go back to the first filter
- Select Settings
- You will see that the panels are collapsed and you need to click twice to open them

https://user-images.githubusercontent.com/70410625/196288875-babad066-ebf1-4196-b685-923ebcab52cb.mov

**Comment by michael-s-molina** [comment]
@jinghua-qa I tested the module but we'll definitely need your help here. Can you book some time to test this PR?

**Review by geido — APPROVED** [review]
Code LGTM. Looking for QA approval.

**Review by zhaoyongjie — APPROVED** [review]
Test in my local. codes LGTM. 

It's my first time reading the Filter Dependence Tree codes, IMO, the data structure of `dependencyMap` *should* be improved. Currently, we use a hashmap to maintain a hierarchical data structure, for instance, the type of `buildDependencyMap` is `Map<string, string[]>`, so the `hasCircularDependency` and `getDependencySuggestion` have to make recursion getting results.

**Pull request merged**
