### PR TITLE
updating the changelog per community request. It's been a minute.

### PR DESCRIPTION
**Pull request by MarcusSorealheis**
### CATEGORY

Choose one

- [ ] Bug Fix
- [ ] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [x] Documentation

### SUMMARY
The community has requested an updated Changelog. The thought has to come to me at times as well. 

Here is an updated changelog containing everything from `0.21.2` to `0.33.0rc2`, the latter of which is upcoming.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by MarcusSorealheis** [comment]
run tests

**Comment by MarcusSorealheis** [comment]
This contains all the changes ever now

**Comment by etr2460** [comment]
Looks like you lost the apache license and need to readd it to the beginning of the changelog

**Comment by MarcusSorealheis** [comment]
@etr2460 I fixed it. Thanks for pointing it out.

**Comment by MarcusSorealheis** [comment]
@etr2460 I'm still getting acquainted with this Travis CI. I overlooked going into the build failure and wrote it off as part of the existing Travis issues. I'll refer to it more closely in the future.

**Review by etr2460 — APPROVED** [review]
This looks awesome to me, @mistercrunch think this is good to merge in?

**Comment by MarcusSorealheis** [comment]
the commits I added were just updating to include the most recent release

**Review by villebro — APPROVED** [review]
LGTM

**Comment by MarcusSorealheis** [comment]
closing this PR changelog updated.

**Pull request closed without merging**
