### PR TITLE
fix: Remove horizontal scroll navigation from SQL Lab

### PR DESCRIPTION
**Pull request by etr2460**
### SUMMARY

People commonly complain about accidentally navigating forwards or backwards in chrome when horizontally scrolling in SQL Lab. Most of our app doesn't have such a horizontal scrolling paradigm, but SQL Lab is the exception. So let's remove that horizontal scrolling navigation behavior in SQL Lab

### TESTING INSTRUCTIONS
Spin up a testenv and test. make sure you can't horizontal scroll to go forward and backwards in sql lab. But when you go back to a dashboard/explore see that you can

Before:

https://user-images.githubusercontent.com/7409244/140548224-aaad7f7e-2c10-4011-8df9-28b3444cf76d.mov

After:

https://user-images.githubusercontent.com/7409244/140548259-cab713f2-39fe-4bac-9194-262ced61f1f4.mov

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

to: @graceguo-supercat @ktmud @rusackas @michael-s-molina

### CODE REVIEW

**Comment by etr2460** [comment]
Marking as ready for review to get the docker build, will tag people when it's actually ready

**Comment by betodealmeida** [comment]
Can we turn it off for the whole app? I hate that pattern! 😆

**Comment by etr2460** [comment]
>Can we turn it off for the whole app? I hate that pattern! 😆

We can consider it, would appreciate a UX designer/PM's take on that first

**Comment by jess-dillard** [comment]
I'd need to do some research on the accessibility issues around turning it off for the entire app, but big thumbs up to doing it here!

**Review by betodealmeida — APPROVED** [review]
<3

**Comment by ktmud** [comment]
@etr2460 @betodealmeida Table chart would need horizontal scrolling at least. Some other tables may also need it.

**Comment by betodealmeida** [comment]
> @etr2460 @betodealmeida Table chart would need horizontal scrolling at least. Some other tables may also need it.

Oh, if I understood correctly we're not getting rid of horizontal scrolling (that's also needed in SQL Lab), but navigating between pages by using horizontal scrolling.

**Pull request merged**
