### PR TITLE
fix:  npm run dev-server error resolved

### PR DESCRIPTION
**Pull request by Abhishek-kumar-ISM**
This error was coming with me, and 3-4 other pc's in which i tried to setup.

`Error: You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer
    at readWasm (/home/test/superset_setup/superset/superset-frontend/node_modules/react-hot-loader/node_modules/source-map/lib/read-wasm.js:8:13)
    at wasm (/home/test/superset_setup/superset/superset-frontend/node_modules/react-hot-loader/node_modules/source-map/lib/wasm.js:25:16)
    at /home/test/superset_setup/superset/superset-frontend/node_modules/react-hot-loader/node_modules/source-map/lib/source-map-consumer.js:264:14
`

How to reproduce:
1. Try fresh installation
2. after superset/superset-frontend when you will do `npm run dev-server` , then above error will come.

Above error was also resolved by doing this:
`export NODE_OPTIONS=--no-experimental-fetch`

But i thought it is better to put in code.

### CODE REVIEW

**Comment by Abhishek-kumar-samsung** [comment]
@lilykuang @michael-s-molina @villebro @rusackas @eschutho @geido i have added one change to solve one error that was coming while running npm run dev-server, to run superset-frontend.

Please review.

**Comment by Abhishek-kumar-samsung** [comment]
> When you say "PCs" do you mean Windows machines? I haven't run into this on Mac, so I'm trying to understand the nature of the error, so I can better understand why this change is needed.

I tried on linux machines.

**Comment by eschutho** [comment]
@Abhishek-kumar-samsung can you add this environment variable to your local/dev/production machines instead as an option? It may be a more flexible option here, in case the rest of the application uses these fetch commands, which I did find some in a quick code search.

**Comment by Abhishek-kumar-samsung** [comment]
@eschutho @rusackas 

I have removed the changes from package.json and moved it to documentation. Written if that error comes to anyone, then he/she can use the solution.

Please review.

**Review by rusackas — APPROVED** [review]
Thanks for capturing this for the sake of others!

**Pull request merged**
