### PR TITLE
chore: make config ENABLE_REACT_CRUD_VIEWS = True by default

### PR DESCRIPTION
**Pull request by mistercrunch**
React CRUD views have been maturing for a while and are ready for prime time.

Screen Shot 2020-10-13 at 8 01 41 PM

### CODE REVIEW

**Review by nytai — APPROVED** [review]

**Comment by etr2460** [comment]
@mistercrunch mind holding off on this for a day or two for us to verify in our environment that everything works as expected? We might mind some further bugs worth addressing before making it the community wide default (although I know we can always simply disable it too)

**Comment by mistercrunch** [comment]
Sounds good @etr2460 , this PR will be right here ready to merge :)

**Comment by bkyryliuk** [comment]
excited about this change ! we have been using react views for quite some time at dropbox

**Comment by etr2460** [comment]
Thanks @mistercrunch! I added a few bugs I found through a precursory QA pass, but otherwise it looks much more feature complete than a few months ago. You can decide which of these (if any) are blocking, then feel free to merge!

#11266 #11265 #11264 #11263

**Comment by mistercrunch** [comment]
@nytai ^^^

**Comment by mistercrunch** [comment]
It appears only these two are still open:
- #11266, non blocking
- #11263, non blocking, fix is under way

Overall the new experience is much better and been used in production at scale in many environments. It's also mentioned in UPDATING.md as a reminder. Merign!

**Comment by kgabryje** [comment]
@mistercrunch Maybe we should modify `tests/superset_test_config.py` to have `ENABLE_REACT_CRUD_VIEWS` true by default as well?

**Comment by kkucharc** [comment]
Hi @mistercrunch I think this change caused problems in pre-commit mypy:
superset/config.py:959: error: Incompatible import of "CELERY_CONFIG" (imported name has type "Type[superset_config.CeleryConfig]", local name has type "Type[superset.config.CeleryConfig]")
superset/config.py:959: error: Incompatible import of "CeleryConfig" (imported name has type "Type[superset_config.CeleryConfig]", local name has type "Type[superset.config.CeleryConfig]")

**Comment by mistercrunch** [comment]
revert? unclear why `mypy` was triggering/flaking for me, it seems like depending on environment `mypy` doesn't agree with itself...

**Pull request merged**
