### PR TITLE
fix: bump FAB to 4.5.2

### PR DESCRIPTION
**Pull request by dpgaspar**
### SUMMARY

WTForms 3.2.X breaks superset with the following error:

```
AttributeError: 'tuple' object has no attribute 'items'
```

More details on: https://github.com/dpgaspar/Flask-AppBuilder/pull/2279

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by betodealmeida — APPROVED** [review]
Thanks!

**Comment by michael-s-molina** [comment]
@dpgaspar Will we need to cherry-pick this into 4.1 which uses `wtforms==3.1.2`? I'm understanding that this fix is for 3.2.X which would make it not required for 4.1. Is that correct? @sadpandajoe

**Review by villebro — APPROVED** [review]
LGTM. However, should we add a lower bound here, too? https://github.com/apache/superset/blob/16981d63169507b39615ca9037f3b36baafba3c0/pyproject.toml#L48

**Comment by dpgaspar** [comment]
> @dpgaspar Will we need to cherry-pick this into 4.1 which uses `wtforms==3.1.2`? I'm understanding that this fix is for 3.2.X which would make it not required for 4.1. Is that correct? @sadpandajoe

yes, I think thats safe to say, if our users install superset without using 4.1 specific dep requirements they will automatically upgrade WTForms and FAB

**Comment by dpgaspar** [comment]
> LGTM. However, should we add a lower bound here, too?
> 
> https://github.com/apache/superset/blob/16981d63169507b39615ca9037f3b36baafba3c0/pyproject.toml#L48

No strong opinions about it

**Pull request merged**
