### PR TITLE
fix(table-viz): value "undefined" for column.name

### PR DESCRIPTION
**Pull request by ktmud**
### SUMMARY

Bump table viz plugin to fix a bug: apache-superset/superset-ui#686

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

See apache-superset/superset-ui#686

### TEST PLAN

Unit test in `superset-ui`.

### ADDITIONAL INFORMATION

- [x] Has associated issue:
- [x] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by etr2460** [comment]
I think you need to run `npm install`

**Comment by ktmud** [comment]
> I think you need to run `npm install`

Yes, but the package hasn't published. So was waiting for https://github.com/apache-superset/superset-ui/pull/686 to be merged.

**Comment by villebro** [comment]
@ktmud I'm assuming this is a 0.37 blocker?

**Comment by etr2460** [comment]
ah, my bad. i assumed this was ready for review. will stamp once CI passes

**Comment by ktmud** [comment]
> @ktmud I'm assuming this is a 0.37 blocker?

@villebro yes, I would prefer this to be shipped with v0.37 as the fix is relatively simple and safe. We should be able to get it merged in a couple of hours.

**Comment by villebro** [comment]
Thanks @ktmud , I'll make sure this makes it into `rc2`.

**Review by etr2460 — APPROVED** [review]

**Pull request merged**
