### PR TITLE
feat: update ingress api version to v1

### PR DESCRIPTION
**Pull request by mvoitko**
### SUMMARY
Update ingress api version to v1

extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+;
networking.k8s.io/v1 Ingress should be used

### TESTING INSTRUCTIONS

`helm upgrade --install --values ./values.yaml superset superset/superset --dry-run`

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by Hokwang** [comment]
you need to edit more. please refer to https://kubernetes.io/docs/concepts/services-networking/ingress/


```
...
      pathType: Prefix
        backend:
          service:
            name: test
            port:
              number: 80
```

**Comment by mvoitko** [comment]
@Hokwang Could you please review?

**Review by craig-rueda — APPROVED** [review]

**Comment by Hokwang** [comment]
I think that you need to provide a way for changing `pathType`. and default is `ImplementationSpecific`.

**Comment by mvoitko** [comment]
@Hokwang modified according to your comment

**Comment by Hokwang** [comment]
Now this PR looks good for me. But I am not a maintainer, reviewer.

**Comment by jqysn** [comment]
When I install via helm, it returned "Error: UPGRADE FAILED: unable to recognize "": no matches for kind "Ingress" in version "networking.k8s.io/v1", is this related with this pr?

**Comment by craig-rueda** [comment]
Likely is. What version of kubernetes are you running? 'v1' is available starting with 1.19.

**Pull request merged**
