### PR TITLE
fix(range-slider): removed localization of metric key

### PR DESCRIPTION
**Pull request by Always-prog**
### SUMMARY
Due to the this localization, the Range Slider is not functioning properly because we are unable to retrieve the `min` and `max` variables from the data because it was translated.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

Example with a russian localization
#### Before

Screenshot_59
<i>Message in english: a non-numeric column is selected</i>

#### After
Screenshot_61

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by john-bodley** [comment]
Thanks @Always-prog for the PR. Would you mind expanding the PR description to include a before and after screenshot? This would help the reviewers better grok the change.

**Comment by Always-prog** [comment]
> 

It's just a simple problem, so there isn't much to explain about. But I have added the screenshots.

**Review by michael-s-molina — APPROVED** [review]
> It's just a simple problem, so there isn't much to explain about. But I have added the screenshots.

Thank you for adding the screenshots @Always-prog. Screenshots are helpful for reviewers and they provide a lot of context to understand the problem. Take your original description for example:

> Due to the this localization, the Range Slider is not functioning properly because we are unable to retrieve the min and max variables from the data because it was translated.

The term "Range Slider" can mean many different components in the application. The screenshot help us quickly understand that you're actually talking about the Numerical range filter type. A reviewer that is not very familiar with that part of the application may not get this information quickly by only looking at the code 😉 

LGTM! Thank you for the fix!

**Comment by john-bodley** [comment]
Thanks @Always-prog for the updated PR description. Echoing @michael-s-molina's comment, looking at the change sans context meant it was hard to grok whether the `min` and `max` words represented labels (which need to be translated) or internal attributes.

**Comment by Always-prog** [comment]
@john-bodley okay, got it!

**Pull request merged**
