### PR TITLE
Init docker for local development environment.

### PR DESCRIPTION
**Pull request by xiaohanyu**
This commit will try to dockerize superset in local development
environment.

The basic design is:
- Enable superset, redis and postgres service instead of using sqlite,
  just want to simulate production environment settings
- Use environment variables to config various app settings. It's easy to
  run and config superset to any environment if we use environment than
  traditional config files
- For local development environment, we just expose postgres and redis
  to local host machine thus you can connect local port via `psql` or
  `redis-cli`
- Wrap start up command in a standard `docker-entrypoint.sh`, and use
  `tail -f /dev/null` combined with manually `superset runserver -d` to
  make sure that code error didn't cause the container to fail.
- Use volumes to share code between host and container, thus you can use
  your favourite tools to modify code and your code will run in
  containerized environment
- Use volumes to persistent postgres and redis data, and also
  `node_modules` data.
  - If we don't cache `node_modules` in docker volume, then every time
    run docker build, the `node_modules` directory, will is about 500 MB
    large, will be sent to docker daemon, and make the build quite slow.
- Wrap initialization commands to a single script `docker-init.sh`

After this dockerize setup, any developers who want to contribute to
superset, just follow three easy steps:

```
git clone https://github.com/apache/incubator-superset/
cd incubator-superset
docker-compose up -d
docker-compose exec superset bash
bash docker-init.sh
```

### CODE REVIEW

**Comment by mistercrunch** [comment]
This is great and useful, though I'm not 100% sure it belongs in the root of this repo, especially if it cannot be maintained by the committers.

Curious what other committers think? Does this belong in this repo? Another repo? In a folder?

Wherever this lands, we should document this in the installation docs as an option to set things up.

One thing we need to change for sure here is the location of `superset/superset_config.py`, this doesn't belong in the main package.

**Comment by xiaohanyu** [comment]
Hi, @mistercrunch ,

Actually, we have used docker based workflow for developing and deploying customized superset for more than half a year and it works great in both developers local machine and for simple deployment just use a modified `docker-compose.yml` in single machine for normal use. So I propose this PR just want to see if get some suggestions.

For the documentation, I can provide more if you think this is OK, and I'll explain some details about the basic workflow for development, some tips to make docker behaves like you local machine without too much code copy and folder share, and real experience about how to use docker-compose to manage different superset version, like from local development environment, to testing, staging, and finally production environment.

The reason about why I contribute this PR to the main repo is I think there should be a faster way to newbies to set up an dev environment for superset. With this PR, new comers can just get a workable/reproducable superset dev workflow in minutes instead of hours. So I just do port mapping, like exposing redis and postgres port directly from docker to host, so you can use most of your familiar redis/postgres to facilitate the dev process.

And about `superset_config.py`, when I propose this PR, I don't want to modify the default `config.py`, so I put some example code to `superset_config.py` and do a `git add -f`, yeah, this is intensive. And we think that use environment variables to configure and inject config to runtime system is very good idea from https://12factor.net/config. Or I think I can put the code to `config.py` directly, first check whether the necessary environment exists, if not, then return to the original default way in `config.py`.

About whether we should put `docker-compose.yml` to another repo, I think yes, just like many other project does. And I can provide `docker-compose` settings for production environment if you like. But right now, for simplicity, I think a simple `docker-compose.yml` in main repo for developers to get on board is enough.

**Comment by mistercrunch** [comment]
I'm 100% sure that `superset_config.py` shouldn't be in the main package though, it seems conflictual and potentially could take over another existing `superset_config.py` depending on PYTHONPATH or the cwd. I'm just thinking it would need to live somewhere else in the repo, and in the context of running in docker it would set the PYTHONPATH to add that folder. Maybe we can we have a docker subfolder in the repository?

I want to make it clear to users that we don't prescribe this setup specifically (using docker, using py3.4, postgres over mysql, redis over rabbit, ...) or that this is the official/proper way of running Superset or whatever. I'd feel more comfortable having all this in a subfolder and adding a section to the installation docs "Quick Start with Docker"

**Comment by xiaohanyu** [comment]
@mistercrunch Agree with you about the `superset_config.py` things.

About the second part, I'll do a later refactoring based on your suggestions.

**Comment by brylie** [comment]
A `docker-compose.yml` file would be a great step to make Superset deployment easier! :-)

**Comment by mistercrunch** [comment]
I agree @brylie, I'm just wondering where it fits in the project. Anything that the maintainer can't commit to maintain should probably go under a `contrib/` folder.

**Comment by brylie** [comment]
@xiaohanyu, any status update here?

Perhaps we can compromise and put these files in a `docker` folder, so it is explicit what they are for?

Having a Docker container would really make this project more viable for several reasons, notably development and deployment. By way of example, we have deployed Metabase and Redash recently on AWS using their Docker images.

**Comment by xiaohanyu** [comment]
@brylie I'll update the status this week. Just come back to work from this week. Sorry for the delay.

Think can put it to a `contrib/docker` folder.

**Comment by xiaohanyu** [comment]
Just rebased and put all files into a `contrib/docker` directory.

It seems current master branch has an issue with db migration, #5088 , so my docker setup fails. Wait for this to be fixed.

**Comment by xiaohanyu** [comment]
Hi, All, 

After #5088 has been fixed, I've revised my patch and now it works.

image

@mistercrunch I've refactored and put all docker related things to a `contrib/docker` directory, users can choose to use this if they like.

@brylie I just finish revision of this PR, too busy in last months.

**Comment by xiaohanyu** [comment]
CI passed after two more commits!

**Comment by brylie** [comment]
When I try to run this via `docker-compose up`, I get the following error:

```
Pulling superset (apache/incubator-superset:)...
ERROR: pull access denied for apache/incubator-superset, repository does not exist or may require 'docker login'
```

**Comment by xiaohanyu** [comment]
@bkyryliuk Hi, you need to build the image locally and manually.

image

Full steps:

```
git clone https://github.com/apache/incubator-superset/
cd incubator-superset
cp contrib/docker/{docker-build.sh,docker-compose.yml,docker-entrypoint.sh,docker-init.sh,Dockerfile} .
cp contrib/docker/superset_config.py superset/
bash -x docker-build.sh
docker-compose up -d
docker-compose exec superset bash
bash docker-init.sh
```

**Comment by brylie** [comment]
Cool, I am really eager to try Superset. I have been waiting for several months for some relatively easy packaging, since the manual installation is somewhat difficult.

**Comment by kakoni** [comment]
Few comments;
1) Instead of doing this in compose config
```
superset:
    image: apache/incubator-superset
```
why not change this to
```
  superset:
    build: .
```
and get rid of docker-build.sh ?

2) entrypoint. Should this have dev option or even run local with something this;
```
elif [ "$SUPERSET_ENV" = "local" ]; then
    superset runserver -d &
    cd /home/work/incubator-superset/superset/assets
    npm run dev
```

**Comment by brylie** [comment]
@kakoni, would you mind opening a PR with your suggested changes?

**Comment by kakoni** [comment]
Of course; https://github.com/apache/incubator-superset/pull/5802

**Pull request merged**
