### PR TITLE
fix(dashboard): narrow empty drop area

### PR DESCRIPTION
**Pull request by justinpark**
### SUMMARY
We've noticed that users are having difficulty adding an element into the tab content area because of its restricted drop zone. This commit expands the drop area for empty content to resolve the problem.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

Before:

https://github.com/apache/superset/assets/1392866/1927a803-a18f-4336-9105-13b0dbef61f7

After:

https://github.com/apache/superset/assets/1392866/bffae35e-6b9d-449e-b912-28912f6a8ecb

### TESTING INSTRUCTIONS
Edit Dashboard and drag and drop to the new tab content

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by michael-s-molina** [comment]
@justinpark I noticed that for some reason, I lost the ability to drag items to the dashboard. Sometimes if I refresh the dashboard, I'm able to drag them but after dropping some charts, the bug reappears. I was not able to reproduce the bug on master.

https://github.com/apache/superset/assets/70410625/da61a115-bb4d-49b9-b35a-b15f4bc3f45f

**Comment by justinpark** [comment]
> I noticed that for some reason, I lost the ability to drag items to the dashboard. Sometimes if I refresh the dashboard, I'm able to drag them but after dropping some charts, the bug reappears. I was not able to reproduce the bug on master.

@michael-s-molina thanks for the testing. I found the some css rule made the side effects. I just updated the hotfix for this bug.

**Comment by john-bodley** [comment]
ping @michael-s-molina

**Review by michael-s-molina — APPROVED** [review]
LGTM

**Comment by Vitor-Avila** [comment]
This is so so so cool! Thank you so much for this improvement.

**Pull request merged**
