### PR TITLE
fix(plugin/country/map): rectify naming for some Vietnamese provinces

### PR DESCRIPTION
**Pull request by hainenber**
fix(plugin/country/map): rectify naming for some Vietnamese provinces

### SUMMARY

Some Vietnamese provinces are incorrectly named without diacritics and "Hồ Chí Minh City" should be named natively as "Thành phố Hồ Chí Minh". This PR is to remediate such issue

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by rusackas** [comment]
Hi! This is much appreciated, but we need to make edits in the Jupyter notebook that generates these files. If we only edit the GeoJson files, they will be overwritten the next time someone runs the notebook. Hopefully this blog post explains it, but if not I'm happy to improve it. 
https://preset.io/blog/how-and-when-and-why-to-update-apache-supersets-country-maps/

**Comment by hainenber** [comment]
Awesome! Thanks for the lead. I'll be checking the referred blog 😄

**Comment by hainenber** [comment]
I've updated the Notebook! No idea why other countries's geojson has a new `name` attribute though :D

**Comment by hainenber** [comment]
oh I saw you were having the side effects also :D 

https://github.com/apache/superset/pull/29627

**Comment by rusackas** [comment]
Heya! Yep... and that PR of mine just merged. If you don't mind rebasing (which might have some notebook changes to sort out) I think this'll be easy to review/merge after that.

**Comment by hainenber** [comment]
Rebased and now pending for review/approval :D

**Comment by hainenber** [comment]
hi @rusackas, is this PR still eligible? A bit rusty in the shed now :D

**Comment by rusackas** [comment]
Sorry I missed this! Yes, it's fine! Merging!

**Review by rusackas — APPROVED** [review]

**Pull request merged**
