### PR TITLE
feat: Add StarRocks support

### PR DESCRIPTION
**Pull request by etr2460**
### SUMMARY
Theoretically, StarRocks supports mysql syntax, so this should work as expected. I'll do a bit more testing before merging though

### TESTING INSTRUCTIONS
CI, connect a starrocks db instance locally to test (still TODO)

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by villebro — COMMENTED** [review]
Thanks for adding! this Can you also add an entry to the docs on how to connect to a StarRocks instance? Also, since it appears to support the MySQL protocol, I'm curious if it actually needs a separate engine spec, or if Superset can "speak" with StarRocks as if it were a MySQL database?

**Comment by etr2460** [comment]
>Also, since it appears to support the MySQL protocol, I'm curious if it actually needs a separate engine spec, or if Superset can "speak" with StarRocks as if it were a MySQL database?

While Superset could speak with StarRocks as if it were a MySQL db, having its own engine spec allows us to display the database as StarRocks throughout the app (as opposed to MySQL). I still need to do a decent amount of testing/documentation work in this PR (thus no reviewers added yet), but will be sure to add docs on how to connect to a StarRocks instance too!

**Comment by john-bodley** [comment]
@villebro regarding:

> Also, since it appears to support the MySQL protocol, I'm curious if it actually needs a separate engine spec, or if Superset can "speak" with StarRocks as if it were a MySQL database?

I've been able to connect to StarRocks via the MySQL connector but there seems to be some nuanced differences—for example the SQL Lab preview failed—which likely means that we'll need a custom engine spec. 

@etr2460 I sense we should ensure that basic functionality works before merging this change and publishing the fact that Superset now supports StarRocks.

**Comment by villebro** [comment]
> > Also, since it appears to support the MySQL protocol, I'm curious if it actually needs a separate engine spec, or if Superset can "speak" with StarRocks as if it were a MySQL database?
> 
> I've been able to connect to StarRocks via the MySQL connector but there seems to be some nuanced differences—for example the SQL Lab preview failed—which likely means that we'll need a custom engine spec.

@john-bodley makes complete sense - I've been noticing other dbs adopting the MySQL protocol, too (which usually aren't fully compatible with the MySQL dialect), so I think this is a pattern we'll start seeing more in the future. So let's try to iron out these issues with the StarRocks spec so we can generalize this for other connectors later.

**Comment by rusackas** [comment]
@john-bodley @etr2460 Just checking in on this as it's been quite a while, to make sure it's still on the docket. Thanks!

**Comment by etr2460** [comment]
Closing since this has been superseded by https://github.com/apache/superset/pull/23209

**Pull request closed without merging**
