### PR TITLE
feat(explore): Upgraded viz select gallery

### LINKED ISSUE #15174: Dynamic plugin not showing up in VizTypeControl
I am trying to load a plugin via url. 

### Expected results

Expect plugin to appear in the list of viz types.

### Actual results

Plugin is not showing up in viz type list. I can see that a request is made to `https://mysupersethost/dynamic-plugins/api/read` and response contains:
```
{
  "count": 1, 
  "label_columns": {
    "bundle_url": "Bundle URL", 
    "changed_by": "Changed By", 
    "changed_by_fk": "Changed By Fk", 
    "changed_on": "Changed On", 
    "created_by": "Created By", 
    "created_by_fk": "Created By Fk", 
    "created_on": "Created On", 
    "id": "Id", 
    "key": "Key", 
    "name": "Name"
  }, 
  "list_columns": [
    "name", 
    "key", 
    "bundle_url", 
    "id"
  ], 
  "modelview_name": "DynamicPluginsView", 
  "order_columns": [
    "name", 
    "key", 
    "bundle_url", 
    "id"
  ], 
  "page": null, 
  "page_size": null, 
  "pks": [
    15
  ], 
  "result": [
    {
      "bundle_url": "url_from_which_plugin_is_served", 
      "id": 15, 
      "key": "superset-indicator-chart", 
      "name": "Indicator Chart"
    }
  ]
}

```
However, the plugin chart does not appear in the modal. I believe this could be a recent regression because I remember being able to use this feature.

#### How to reproduce the bug

1. Write your own plugin using https://github.com/apache-superset/dynamic-import-demo-plugin as template
2. Run `npm install` and `npm run build`, then `npm run serve` to serve `dist` dir
3. Expose port via HTTP server
4. Enable feature flag on Superset host, run `superset init`
5. Go to 'Settings -> Plugins' and create a plugin entry containing plugin url 
6. Go to 'Chart -> Create New' and verify that your plugin does not appear in the list of viz types

### Environment

(please complete the following information):

- superset version: latest master as of now, latest commit 57035c1b93331b925e9bf91f757f365807ca70ab
- python version: 3.8.7
- node.js version: v14.16.0

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

I have verified that the plugin is working when imported directly in source and linked as here: https://superset.apache.org/docs/installation/building-custom-viz-plugins. 

I also debugged and stepped over the piece of code importing the plugin (https://github.com/apache/superset/blob/9773aba522e957ed9423045ca153219638a85d2f/superset-frontend/src/components/DynamicPlugins/index.tsx#L150) and made sure there is no error upon importing.

I have also made sure that the name of the plugin in the package.json is the same as the one in Superset.

### PR DESCRIPTION
**Pull request by suddjian**
### SUMMARY

- Organizes plugins by category
- Displays chart descriptions and examples
- Adds fuzzy search by name, tags, or description
- Improves Add Chart page layout
- Upgrades superset-ui version to populate lots of new plugin metadata
- Improves the plugin context to provide metadata (along with updates to metadata i.e. dynamic plugins)
- Fixes #15174
- ✨ grid ✨ 

This feature branch had several PRs merged into it that were independently reviewed. Approving this should be pretty much a rubber stamp.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

Before: 
Screen Shot 2021-07-02 at 5 32 43 PM

Initial Design:
Screen Shot 2021-06-11 at 3 38 58 PM

After:
Screen Shot 2021-07-02 at 5 31 42 PM

### TESTING INSTRUCTIONS

1. Create chart -> choose a viz type
2. From explore, change viz type

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by geido** [comment]
First of all, this is looking great! Congrats

I wanted to do some manual testing out of curiosity and came up with the following feedback.

#### Selected viz type
When changing a viz type, the modal shows the correct title and description at the bottom. However, the selection of the category is incorrect and it is not showing the currently selected type.

Filter-Segments

#### Inconsistent search behaviour
When clicking on the search input, the category is automatically reset to the default. However, when clearing up the search the previously selected category gets selected back again. I think the behaviour should be consistent and clearing up should bring you to the default, not the previously selected category.

Filter-Segments-_1_

#### Default order
Do we have a default order when searching? Should it be alphabetical?

Screen Shot 2021-07-04 at 18 47 14

#### Unnecessary scroll bar
Just a minor thing. The scroll bar for the categories is showing up even though there are no other categories.

Filter-Segments-_2_

**Comment by EBoisseauSierra** [comment]
Thank you for your brilliant work, it looks amazing! :rocket: 

Here are a some very minor details I've picked along the way:

**Empty selection by default**

When creating a new graph, the first chart type (here, Table) is selected by default (cf. lower half of the dialog).  It would feel more natural (to me) that no chart is selected by default.

default_empty

**Selection not cleared when changing category**

In the same spirit, I'd like to be able to “clear” the selected visualization when changing category. Currently, the last selection “sticks” in the lower half of the dialog, even if that chart type isn't part of the currently selected Category (upper half). This can cause some confusion as I can have both “BigNumber” (selected chart type) and “Correlation” (selected category) at the same time…

sticky_selection

**Charts categorization**

I fully understand this is not a trivial task and that no solution might satisfy everyone. Here are just some of the chart categorisation that appeared unnatural to me:

* _Move deck.gl to Map:_ deck.gl charts are currently in Others. This seems intentional, yet it would feel more natural to me to find them in the Map category.
* _Move funnel to Flow:_ The funnel chart is currently listed in KPI, yet I understand that KPI charts should be more one single value, rather than the evolution of one value over a process/some given steps. In absolute terms “Evolution” would be a natural category as well, yet I understand that Funnel would contrast with the more TS-related chart that are currently in this category.
* _Horizon to Evolution?:_ Horizon is a tricky one, but because its abscissa is time, I'd put it in “Evolution”.
* _Ranking:_ 
  * I see why WordCloud is there, but if I were to look for it, I wouldn't think it could be in the Ranking category (rather “Other”).
  * Nightingale would, for me, better fit in “Part of a whole” (if I understand that chart correctly) — or distribution.

I appreciate the ranking is coherent with D3's one (and I even voted in favour of that ranking in SIP-67)… but the categorization still feels a bit unnatural to me (i.e. if I were to look for a given chart, I'm not sure I would find it first time/I wouldn't struggle finding it — btw, the search bar is a must have, thanks!).

**Browse through all charts at a glance**

I am aware this defeats a large part of your work with the categorization, but something I like with [D3's gallery](https://www.d3-graph-gallery.com/) is that I can have all chart types at a glance by scrolling through one single page. Here, when one clicks on a category, it filters out all the other charts.
Perhaps a presentation similar to [Echarts gallery](https://echarts.apache.org/examples/en/index.html) — where all charts are in one page, with categories as section headings and the list of categories on the left column allowing to “jump” to the right anchor (yet without “filtering out” any chart) — could help?

**Add “deprecated” label**

Some charts are due to be deprecated. This is detailed in their description, yet I feel this doesn't stand out enough. A grey “deprecated” tag (similar to tags in GitHub issues/PR) could help notice it more.
Introducing such tags could also serve in the future to identify “official” chart types from those developed by 3rd parties.

tag


**Chart examples thumbnails scrollbar**

On Firefox DevEd 90.0b12 (64-bit), with ×150% zoom, some “non-scrollable scrollbars” appear around the chart example thumbnails area. In general, I would expect the thumbnails to be more flexible in their sizing (as it's not such an issue if they are downscaled, unlike the description text), so that they adapt to their container instead of forcing it to display scrollbars.

Screenshot from 2021-07-07 10-08-04

Related to this, the chart description and thumbnail area are 2 separate components, with independent scrollbars. It would feel more natural to me to consider both elements as one unique “scrollable” entity. (I.e. have only one scrollbar on the far right, even if it's the text that overflows.)

Screenshot from 2021-07-07 10-58-58


This would mean that “Example” become a sub-heading of the chart type (here “Heatmap”) — one could either introduce the “Description” subheading as well for the left column, or get rid of the “Example” one?

---

All this being said, it's already such a huge step forward I'm very much looking forward to using in prod; thanks a lot!

**Comment by suddjian** [comment]
Thank you both very much for the well-written feedback, paging @junlincc to get product eyes on this.

Some notes:

- The edge case of non-scrollable scrollbars is pretty unavoidable in a grid-based design like this. At some point before things disappear off the edge of the container, the scrollbar has to appear. I don't think it would be worth the unsavory css margin hacks required to tweak when that occurs. A more responsive design could reduce the impact of this, maybe that would be a good follow-up.
- The examples list in its current form is a temporary solution. Ultimately, we'd like to use a carousel or other solution. AntD has these components, but we will need to bump the version to get it working correctly.
- I think a de-selected state makes sense. I've opened a PR to add that: #15577

**Review by rusackas — APPROVED** [review]
There are a lot of good ideas for iteration/improvement on the thread, but to my eyes, this thing looks like a huge improvement, and looks ready to merge!

Not for interested parties, that additional PRs in superset-ui to add metadata to the rest of the plugins, are underway right now

**Pull request merged**
