### PR TITLE
Add "Select All" to SelectControl and allow free form group by expressions

### PR DESCRIPTION
**Pull request by agrawaldevesh**
* Changes to SelectControl: Add a "Select All" feature such that you can easily show all the columns in a Table non-group-by select box
* Allow adding custom expressions to the group by select box such that we can now group by any sql expression and not just columns (no need to add them as "calculated columns first")
* Add ordering of options in the FilterBox

### CODE REVIEW

**Comment by agrawaldevesh** [comment]
Screenshot of the UI changes (as requested by @kristw):

1. Added a "Select All" option for some of the select menus, including not grouped by
image

2. Added ability to free-form add any expression in the group by drop down
image

**Comment by agrawaldevesh** [comment]
PR is ready for review. I have added unit tests and UI screen shots as requested. 

cc: @mistercrunch @betodealmeida @kristw 

Thanks !

**Comment by mistercrunch** [comment]
This LGTM. As discussed eventually we'll want a consistent popover with the `MetricsControl` that exposes a way to validate the expression.

**Comment by mistercrunch** [comment]
I don't know the details yet, but I was looking for the source of this bug and bisected until I got here and identified this as the source of the issue.

The problem is that the clear `x` on some `Selects` doesn't clear anymore as it used to. We need to fix this quickly.

**Comment by agrawaldevesh** [comment]
Hi Max, sorry about that ! Can you please point me to which bug and what
selects have this issue. Thanks!

**Comment by mistercrunch** [comment]
@agrawaldevesh the bug is linked above your comment ^^^

**Comment by mistercrunch** [comment]
No pb, I'm fixing this one on

**Pull request merged**
