### PR TITLE
fix: Keep chosen columns sort option when changing a column

### LINKED ISSUE #15842: [Explore]checking temporal box reorder the columns in the modal
https://user-images.githubusercontent.com/67837651/126688420-181454e1-ab8d-4682-bb6e-763005888c1d.mov

Expected behavior: User checks a column as Temporal, the order of columns should remain the same after the box is checked. 
User only sees the new column list order by sorting. 

When opening a fix PR, please check other checkbox types as well, it does seem only happening to the Temporal one 🙏 @geido

### PR DESCRIPTION
**Pull request by geido**
### SUMMARY
This PR keeps the existing columns sort option while the user makes changes to the columns. Previously the sort order was not kept.

Fixes: #15842

### BEFORE
https://user-images.githubusercontent.com/60598000/127232222-d7b090fe-7ba2-4885-8105-99409a65d495.mov

### AFTER

https://user-images.githubusercontent.com/60598000/127232465-59ad1f0f-471a-4ab7-9080-d2dbc2125948.mp4

### TESTING INSTRUCTIONS
1. Open a Chart in Explore
2. Edit the Dataset
3. Go to Columns
4. Check a column as Temporal, 
5. The order of columns should remain the same after the box is checked

### ADDITIONAL INFORMATION

- [x] Has associated issue: #15842
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by geido** [comment]
@rosemarie-chiu @jinghua-qa

**Review by suddjian — APPROVED** [review]
nice!

**Comment by junlincc** [comment]
LGTM, thanks for the quick fix!! 🙇‍♀️

**Review by junlincc — APPROVED** [review]
LGTM! Thanks for the quick fix! 🙇‍♀️

**Pull request merged**
