### PR TITLE
fix(helm chart): set chart appVersion to 3.0.0

### LINKED ISSUE #25416: Helm chart install fail.
#### How to reproduce the bug

1 install apache/superset image with helm chart.
2 install fails with event Message:
Failed to apply default image tag "apache/superset:latest:3.0": couldn't parse image reference "apache/superset:latest:3.0": invalid reference format  

### Expected results

install succeeds with event message:
Pulling image "apache/superset:3.0.0"

### Actual results

helm install superset never finish

### PR DESCRIPTION
**Pull request by celalettin1286**
### SUMMARY

here: https://github.com/apache/superset/blob/0c083bdc1af4e6a3e17155246a3134cb5cb5887d/helm/superset/templates/deployment.yaml#L90 it gets the appVersion if tag null but app image tag is 3.0.0 not 3.0 causes image pull issues if superset deployed with default values

Fixes https://github.com/apache/superset/issues/25416

### TESTING INSTRUCTIONS
CI.

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by justinpark — APPROVED** [review]
LGTM

**Review by craig-rueda — APPROVED** [review]

**Review by dpgaspar — APPROVED** [review]
@michael-s-molina should we update the README on RELEASING?

**Comment by michael-s-molina** [comment]
> @michael-s-molina should we update the README on RELEASING?

@dpgaspar We have a scheduled meeting to review the release process and one of the questions is about the officially supported artifacts. If Helm ends up being officially supported, then we need to update the `README`.

**Comment by craig-rueda** [comment]
Linting still failing...

**Comment by celalettin1286** [comment]
> Linting still failing...

I guess it was not happy about README just updated it also.

**Pull request merged**
