### PR TITLE
chore: apply capitalization guidelines - iteration 6 (#12343)

### PR DESCRIPTION
**Pull request by michael-s-molina**
### SUMMARY
Apply capitalization guidelines defined in #12343.

@junlincc

### TEST PLAN
Check if modified texts are following capitalization guidelines.

### ADDITIONAL INFORMATION
- [x] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by junlincc** [comment]
please specify all your changes in this PR, include screenshot and test plan, also for all your future PRs. @michael-s-molina 🙏

**Comment by adam-stasiak** [comment]
looks good to me - > please restart to make e2e script green ;)

**Review by Steejay — APPROVED** [review]
looks good to me!

**Review by rusackas — APPROVED** [review]
LGTM, but holding off from merging.

**Pull request merged**
