### PR TITLE
fix(docs): Installation instruction changes

### PR DESCRIPTION
**Pull request by artofcomputing**
### SUMMARY

Updating installation instructions to contain up to date information of Superset's SECRET_KEY variable for production usage.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by sfirke** [comment]
To the reviewer(s): all of the `sidebar_position` changes are to move the "Running with Kubernetes" page up to its logical place, position 3.  All the other pages needed to get shuffled down.

**Comment by shellwirt** [comment]
After this PR, we can change the configuration of the [sidebar](https://docusaurus.io/docs/sidebar) in `docs/sidebars.js` so that we don't depend on each document metadata to define their position, making the documents much easier to work with.

However we might need to document that change, so other contributors can add their pages in the file instead of defining metadata fields.

**Review by artofcomputing — COMMENTED** [review]
Most of the changes were done to fix small grammar issues and to inform users that new Superset versions require the SECRET_KEY environment variable to be set when deploying to production.

**Review by rusackas — APPROVED** [review]

**Comment by sfirke** [comment]
I believe this PR makes another open one obsolete: https://github.com/apache/superset/pull/20482

**Review by rusackas — APPROVED** [review]

**Comment by rusackas** [comment]
Closing/reopening to kick-start CI.

**Pull request merged**
