### PR TITLE
Caravel no data returned exception

### PR DESCRIPTION
**Pull request by gbrian**
Hi there,
Not sure if you are interested by I've changed a bit the way "No results" is managed.
I've kept as an exception but created new one `NoResultsException`, excpetion is returned in a custom header.
Changed the way visualizations notifies error, now they are passing the error object instead only the message.
Finally message is render with another class.

### CODE REVIEW

**Comment by mistercrunch** [comment]
I think you need to rebase

**Comment by gbrian** [comment]
Rebased.
Re ran `npm run lint` seems not to be working properly on my machine, trying to fix and enabling at `PyCharm`
I apology for the inconveniences.

**Comment by mistercrunch** [comment]
This PR isn't right (attempting to delete files) reopen it when it's cleaned up

**Comment by gbrian** [comment]
Ouch! Seems I did something wrong during "re-base" operation.
Now fixing and adding a test case.

**Pull request closed without merging**
