### PR TITLE
[bugfix] css editor dooesn't pop up

### LINKED ISSUE #2218: Dashboard CSS editor not popping up
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

I have installed superset using `pip install superset`. When I go to a dashboard and click on the edit css button present in 
edit_css

The main screen becomes inactive expecting a CSS editor but none opens. The following error is displayed in the browser console after the button is clicked:
`Uncaught TypeError: Cannot read property 'match' of null
    at l.$detectNewLine (dashboard.0.15.4.entry.js:82)
    at l.insert (dashboard.0.15.4.entry.js:82)
    at l.setValue (dashboard.0.15.4.entry.js:82)
    at b.setValue (dashboard.0.15.4.entry.js:85)
    at e.value (dashboard.0.15.4.entry.js:78)
    at r.notifyAll (dashboard.0.15.4.entry.js:35)
    at r.close (dashboard.0.15.4.entry.js:51)
    at r.closeAll (dashboard.0.15.4.entry.js:35)
    at r.perform (dashboard.0.15.4.entry.js:35)
    at s (dashboard.0.15.4.entry.js:51)`

OS: Ubuntu

### Superset version
"version": "0.15.4"

### Expected results
css_editor

### Actual results
Inactive dashboard screen in the background.

### Steps to reproduce
1. Open any dashboard
2. Click on Edit CSS button on the dashboard

### PR DESCRIPTION
**Pull request by mistercrunch**
fixes https://github.com/airbnb/superset/issues/2218

### CODE REVIEW

**Comment by bkyryliuk** [comment]
LGTM

**Comment by ascott** [comment]
strange, i merged this change in last week... https://github.com/airbnb/superset/pull/2188/files

**Comment by ascott** [comment]
oh i see, this is a change on `components/CssEditor.jsx`. i'm not sure this change is needed. i double checked master on staging and i can't repro this bug.

**Comment by mistercrunch** [comment]
You can reproduce it by creating a new dashboard.

**Pull request merged**
