### PR TITLE
failed to install 

### PR DESCRIPTION
**Pull request by joriewong**
no such directory 'static'

### CODE REVIEW

**Comment by xrmx** [comment]
Are you installing on windows?

**Comment by joriewong** [comment]
centos

**Comment by xrmx** [comment]
The there's something wrong with your installation as the path should be there.

**Comment by joriewong** [comment]
image

**Comment by mistercrunch** [comment]
Yeah that's better than going through the symlink, merging.

**Comment by mistercrunch** [comment]
Broke the pypi build

**Pull request merged**
