### PR TITLE
Require the SQLAlchemy URI on the database model

### PR DESCRIPTION
**Pull request by willbarrett**
### CATEGORY

Choose one

- [X] Bug Fix
- [ ] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY

Currently, attempting to create a database connection without a SQLAlchemy connection string defined will throw a server error (calling `strip` on `NoneType`). After the change, the system will reject empty SQLAlchemy connection strings correctly.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### REVIEWERS
@etr2460 @betodealmeida @mistercrunch

### CODE REVIEW

**Review by john-bodley — COMMENTED** [review]
@willbarrett you’ll have to add a Alembic migration as part of this PR since you’re updating the data model.

**Comment by willbarrett** [comment]
@john-bodley this change was to trigger a UI change in the FAB database UI. I don't feel strongly about adding a NOT NULL constraint at the database level. Do you think such a constraint would be valuable?

**Comment by etr2460** [comment]
I think we should keep the data model and the database in sync as much as possible here. Also because any generated migration will then try to add this restriction again

**Comment by willbarrett** [comment]
Works for me. I'll add the migration.

**Review by mistercrunch — APPROVED** [review]

**Review by dpgaspar — APPROVED** [review]

**Pull request merged**
