### PR TITLE
build: ignore Storybook stories in CodeCov

### PR DESCRIPTION
**Pull request by ktmud**
### SUMMARY

Ignore Storybook stories in CodeCov report so we don't get these unnecessary warnings:

image

Stories are a type of visual tests themselves and do not normally need test coverage.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

N/A

### TEST PLAN

CI

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by michael-s-molina** [comment]
@ktmud some stories have `.jsx` extension. We should also ignore those while we don't change to typescript.

**Comment by ktmud** [comment]
@michael-s-molina These warnings only show up when you modify a file. I'm hoping the next time we touch a `.stories.jsx` we would have converted it to `.tsx` already!

**Comment by michael-s-molina** [comment]
> @michael-s-molina These warnings only show up when you modify a file. I was hoping the next time we touch a `.stories.jsx` we would have converted it to `.tsx` already!

I didn't know that the warnings only show when we modify.. in that case we should be fine 😁

**Comment by michael-s-molina** [comment]
Hum.. thinking a little more about it.. we have the case of executing the coverage script through npm.. in that case it will count .jsx stories. What do you think @ktmud ?

**Comment by ktmud** [comment]
Yeah, it could have an impact on coverage percentages, but should not throw the warnings. So I'm adding `.jsx` to the ignore list anyway.

**Review by rusackas — APPROVED** [review]
Nice catch! Thanks!

**Pull request merged**
