### PR TITLE
chore: Remove actions prop and refactor code in SQL Lab

### PR DESCRIPTION
**Pull request by EugeneTorap**
### SUMMARY

Refactor all actions in sqlLab in order to use useDispatch() hook instead of actions prop in every child components.
Also fix type for Query

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by rusackas** [comment]
Pinged a couple committers for review, and might also ask for eyes from @codyml or @eric-briscoe if they have time.

**Review by codyml — APPROVED** [review]
This looks great to me!

**Comment by EugeneTorap** [comment]
@michael-s-molina Can we merge it?

**Review by kgabryje — APPROVED** [review]
LGTM!

**Pull request merged**
