### PR TITLE
feat(sqllab): add shortcut for run current sql

### PR DESCRIPTION
**Pull request by justinpark**
### SUMMARY
The manual selection of the current query is time-consuming. (Longer the query more time it takes to select manually)
This commit creates a new shortcut(`ctrl + shift + enter`) which automatically detects and selects the range of the current query and then run the selection in order to reduce the manual selection work.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

After:

https://github.com/apache/superset/assets/1392866/d146c9a5-5819-4fe2-af22-6281f3bb0de6

Before:

https://github.com/apache/superset/assets/1392866/45f22a20-32b3-4eab-b075-95bf4e108df6

### TESTING INSTRUCTIONS
Hit "Ctrl+Shift+Enter" on sql editor

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by michael-s-molina** [comment]
@justinpark Ephemeral environments are not working anymore.

**Comment by michael-s-molina** [comment]
If the cursor is at the end of the line, it will jump to the next statement.

https://github.com/apache/superset/assets/70410625/e3f00516-6efe-49d4-be32-fafe278fe570

**Comment by michael-s-molina** [comment]
Should we ignore comments?

https://github.com/apache/superset/assets/70410625/0daa6018-338c-48cb-9d10-02dc7cbfb4a1

**Comment by cploonker** [comment]
To me it should be any query delimited by semi-colon OR (start/end of file) around the cursor should be picked.

If the cursor is just after the semicolon, next query should be picked. 

If I am editing a specific query my cursor is likely going to be inside that query,

**Comment by justinpark** [comment]
> If the cursor is at the end of the line, it will jump to the next statement.
> 
>  Screen.Recording.2023-06-09.at.14.44.03.mov


As Chandraprakash mentioned, this is intended. If the cursor is the next to the semi column, it will jump to the next statement.

**Comment by justinpark** [comment]
> Should we ignore comments?
> 
>  Screen.Recording.2023-06-09.at.14.47.42.mov

As we faced the regression of handling comments in FE, ignoring comments makes more complex and can be an issue in some edge cases. I'd rather make simple (including comments) to make features functional.

**Comment by cploonker** [comment]
Is it possible to send the delimited query for execution without actually selecting the query in the UI?
Can we NOT skip this step off selecting it in the UI? 
I don't have a demo to play with, but I was thinking that the selection will actually move my cursor and if I need to further edit then I still need to use the mouse to go back to the location of edit.

If not i guess this can be a stepping stone to end goal some day.

**Comment by michael-s-molina** [comment]
> Is it possible to send the delimited query for execution without actually selecting the query in the UI?

I think this is a great suggestion from an usability perspective. It's quite common to edit the statement after a failed query. That's actually the default behavior of many database tools. Here's an example of [DBeaver](https://dbeaver.io/):


https://github.com/apache/superset/assets/70410625/8dd4c68d-eff5-4ce6-92ca-cf4596fcb9c5

**Comment by cploonker** [comment]
We can try to pass an additional parameter into `runQueryFromSqlEditor` e.g. currentQuery=true with default value as false. And then move the calc to find the query inside that function.

https://github.com/apache/superset/blob/c1d882e9153624046a450257a6e19e36a1f96e9d/superset-frontend/src/SqlLab/actions/sqlLab.js#L390

**Comment by cploonker** [comment]
Can we merge this change please. 
We can always iterate on how ctrl + shift + enter works.
For the most part the end user experience will remain the same

**Comment by michael-s-molina** [comment]
> Can we please merge this change.
> We can always iterate on how ctrl + shift + enter works.
> For the most part the end user experience will remain the same

The iterative approach makes sense given that the current behavior already offers a valuable feature.

**Review by michael-s-molina — APPROVED** [review]
LGTM

**Comment by EugeneTorap** [comment]
@justinpark Thanks for this nice PR!
@michael-s-molina Can rerun the cancelled CI test and merge the PR?

**Comment by justinpark** [comment]
cc: @cploonker @michael-s-molina @EugeneTorap 

As suggested, I updated the selection back to the current cursor position.

https://github.com/apache/superset/assets/1392866/197e0ca1-b718-484b-8d51-60fcf1fa5d8e

**Comment by cploonker** [comment]
> cc: @cploonker @michael-s-molina @EugeneTorap
> 
> As suggested, I updated the selection back to the current cursor position.
> 
>  without.selection.mov

ooohhh nice

**Comment by EugeneTorap** [comment]
Hi @rusackas @kgabryje! Can we merge it?

**Comment by villebro** [comment]
> This is awesome! I'll review it tomorrow.

Agreed, this has been long overdue, thanks for this work @justinpark ! ❤️

**Pull request merged**
