### PR TITLE
Viz py fix try 4 (Multi-line chart bug)

### PR DESCRIPTION
**Pull request by willbarrett**
### CATEGORY

Choose one

- [X] Bug Fix
- [ ] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY

https://github.com/apache/incubator-superset/pull/9522 was merged after we finally got CI to pass, but it contained an experimental fix recommended by Max that didn't actually resolve the issue. This PR reverts to the original fix, which does resolve the issue.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### REVIEWERS
@villebro

### CODE REVIEW

**Comment by villebro** [comment]
Oh, that's curious, I thought Max's solution would have fixed it, too. Let me think this through and get back in a second.

**Comment by villebro** [comment]
Ha, a typo! 
https://github.com/apache/incubator-superset/blob/master/superset/viz.py#L118

**Comment by willbarrett** [comment]
🤦 updating

**Comment by willbarrett** [comment]
I'm actually going to wait and see if we actually get a clean build on this branch. No point in doing the update here if it Travis messes up again.

**Comment by willbarrett** [comment]
Something is weird with history on this branch, closing.

**Pull request closed without merging**
