### PR TITLE
feat: add toast feedback to annotation templates

### PR DESCRIPTION
**Pull request by kgabryje**
### SUMMARY
This PR adds toast messages as a feedback to user actions: creating an annotation template and editing annotation template.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

https://user-images.githubusercontent.com/15073128/150381907-aafb48f3-8de1-4b64-9a30-13ff370967c0.mov

### TESTING INSTRUCTIONS
Create an annotation template, verify that toast message appears.
Edit an annotation template, verify that toast message appears.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

CC @yousoph @rusackas 
https://app.shortcut.com/preset/story/35387/annotation-layer-templates-system-feedback

### CODE REVIEW

**Comment by rusackas** [comment]
@jess-dillard / @kasiazjc if you feel like taking a look to validate from the design side, you can check the ephemeral environment link above. :)

**Comment by jess-dillard** [comment]
@rusackas Looks good to me!

**Review by michael-s-molina — APPROVED** [review]
LGTM

**Pull request merged**
