### PR TITLE
chore: relax greenlet requirements

### PR DESCRIPTION
**Pull request by sadpandajoe**
### SUMMARY

Currently we are pinning greenlet to be 3.0.3, however, there are some instances that greenlet needs to be in a higher version like 3.1.1. Loosening up the requirements here to include the upper bound as needed.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by mistercrunch** [comment]
I thought playwright has a hard requirement on 3.0.3 (jut cause they don't know better... submitted a PR to relax their req). The reason why I pinned it is because it throws off `supersetbot` - it tried to upgrade to 3.1.1 but playwright then complains...

**Comment by sadpandajoe** [comment]
> I thought playwright has a hard requirement on 3.0.3 (jut cause they don't know better... submitted a PR to relax their req). The reason why I pinned it is because it throws off `supersetbot` - it tried to upgrade to 3.1.1 but playwright then complains...
> 
> I guess this only affects the `development.txt`, not the `base.txt`...

We currently use 3.1.1 in our system so when we try to do a build without this being relaxed it'll throw an error. So just relaxing it here but keeping the main .txt files untouched.

**Comment by mistercrunch** [comment]
actually I have an idea, let me try something

**Review by mistercrunch — APPROVED** [review]
Moving the pin to `base.in`, let me know if that unblocks you. If not, we could move to `development.in`, but both environments would be out-of-sync in regards to their greenlet version, which isn't a problem.

**Pull request merged**
