### PR TITLE
fix(dashboard rbac): make a dashboard with no role assigned accessible only when PUBLISHED instead of DRAFT

### LINKED ISSUE #22640: Dashboard RBAC access doesn't conform to documentation (and access permission exposes a possible security risk)
`DASHBOARD_RBAC` does not behave as explained in documentation: it says 'Roles is a list which defines access to the dashboard. Granting a role access to a dashboard will bypass dataset level checks. **If no roles are defined, then the dashboard is available to all roles.**', but instead when I do not assign any role to the dashboard only admin and owners can access to it.

#### How to reproduce the bug

1. Feature flag `DASHBOARD_RBAC` set to `True`
2. Open a published dashboard that has no role assigned as a Alpha-role-assigned user

### Expected results

The dashboard

### Actual results

A permission error

#### Screenshots

image

### Environment

(please complete the following information):

- browser type and version: both Edge and Firefox
- superset version: both `1.5` and `2.0`
- python version: `python --version 3.9`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

While investigating in the problem I found out that it is possible to access any dashboard with status DRAFT from any user (when dashboard has no RBAC role assigned). 

The problem could probably be here: https://github.com/apache/superset/blob/001100ddf02db7be1ea94a1cac16475d00436b78/superset/security/manager.py#L1994

Indeed, I cannot figure out why the condition should be `or (not dashboard.published and not dashboard.roles)` and not `or (dashboard.published and not dashboard.roles)`.

Is there a case in which a non-admin and non-owner user should view a (not even menu-listed) draft dashboard?

### PR DESCRIPTION
**Pull request by ghost**
### SUMMARY
Minor bug fix on dashboard RBAC faulty behaviour

### TESTING INSTRUCTIONS
See issue #22640

### ADDITIONAL INFORMATION
- [x] Fixes #22640
- [x] Has associated issue:
- [x] Required feature flags: `'DASHBOARD_RBAC' = True`
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by frabenetti** [comment]
We have the same issue and I see this PR will solve the problem, I tested the modification in a docker in versione 2.0.1.

**Comment by frabenetti** [comment]
Any news about the approval of this PR?

**Comment by eschutho** [comment]
@giovannipapini-agilelab is this PR ready for review?

**Comment by giovannipapini-agilelab** [comment]
Hi @eschutho, yes, it is a quite basic fix but fundamental for `DASHBOARD_RBAC` feature flag working. We have already applied this patch on our prod env, where gives the desired result.

**Comment by CeelamkotiVinod** [comment]
I tried applying your changes, but still issue persists.

**Comment by mdeshmu** [comment]
@giovannipapini-agilelab How will this behave if DASHBOARD_RBAC is enabled with no roles assigned in a published dashboard's properties? Will it gives access to every logged in user or will it fall back to dataset permissions ?

**Comment by giovannipapini-agilelab** [comment]
> Will it gives access to every logged in user or will it fall back to dataset permissions ?

It will fall back to user's dataset permissions. It seems to me the right behaviour, coherent with the text box under dashboard roles `If no roles are defined, then the dashboard is available to all roles.`

**Comment by mdeshmu** [comment]
My understanding of this text:

`If no roles are defined, then the dashboard is available to all roles.`

is

dashboard will be available to any logged in user which is then a security issue.

**Comment by giovannipapini-agilelab** [comment]
We could also fix that text box writing something like 

`If no roles are defined, then the dashboard is visibile to users on the base of general datasource permissions.`

that is the most precise behaviour definition.

**Comment by mdeshmu** [comment]
IMO, correction of that text is also needed. Something like this as shown in this documentation https://superset.apache.org/docs/creating-charts-dashboards/creating-your-first-dashboard/#manage-access-to-dashboards

`If no roles are defined, then the access will fallback to Dataset permissions.`

@amitmiran137 I feel there is a fullstop (.) missing in the documentation in here ->

image

**Comment by giovannipapini-agilelab** [comment]
@mdeshmu may I add those also those fixes in this pr?

**Comment by mdeshmu** [comment]
@giovannipapini-agilelab I would love to see clarity in the texts.

**Comment by mdeshmu** [comment]
@sfirke confirmed here: https://apache-superset.slack.com/archives/C016B3LG5B4/p1677865116611839?thread_ts=1677781629.874359&cid=C016B3LG5B4

`Right now if I don't add a role to a dashboard, it gives access to all roles, i.e., even the public.`

It is really a security issue then.

**Comment by mdeshmu** [comment]
@giovannipapini-agilelab With your changes in this PR, Can you please test that if dashboard is published and no role is assigned to dashboard, is it accessible by a user with Public or Gamma Role ?

**Comment by giovannipapini-agilelab** [comment]
> @giovannipapini-agilelab With your changes in this PR, Can you please test that if dashboard is published and no role is assigned to dashboard, is it accessible by a user with Public or Gamma Role ?

Hi, we verified this case and in indeed the behaviour is this:
- If the dashboard is **draft** it is not listed in dashboard menu and only owners and admins can open it.
- If the dashboard **is published** has some rbac role assigned, then the it is listed in dashboard menu (d.m.) and visible **to and only to** those roles (with the exception of dashboard owners and admins). Other roles do not see it listed in d.m. and when they open it via permalink they get a "You cannot access this dashboard!" error page. 

Imo this is the correct behaviour (and note that it is not the same as before this PR).

- If the dashboard **is published** and has no rbac role assigned, then it is visible in d.m. only to those who have dataset-level permissions, **but** it is accessible and visible *via permalink* also to everyone else (Gamma or Public roles).
This could be seen as a security issue, even more if combined with the `PUBLIC_ROLE_LIKE = "Gamma"` setting.

Probably we should fix the fallback behaviour, in this or in some other PR, what do you think @mdeshmu?

**Comment by sfirke** [comment]
Good summary @giovannipapini-agilelab.  Are you testing out applying your patch to 2.1.0rc1?  I was testing out another feature on that version and found that the DASHBOARD_RBAC behavior had changed from 2.01.  Now if a dashboard is _draft_ and has no RBAC role assigned, it tries to load - its name appears in the browser - but it errors before it can load.  So I would make sure you're trying your changes on top of the latest.

> This could be seen as a security issue, even more if combined with the PUBLIC_ROLE_LIKE = "Gamma" setting.

Agreed.

**Comment by sfirke** [comment]
Good summary @giovannipapini-agilelab.  FYI I was testing out a separate feature on version 2.1.0rc1 and found that the DASHBOARD_RBAC behavior is slightly different from 2.01.  If a dashboard is **draft** and has no RBAC role assigned, it still _tries_ to load - its name appears in the browser - but it errors before it can load.  I suppose this is the same behavior since it's trying to load, but heads up in case that complicates how this is discussed.

**Comment by giovannipapini-agilelab** [comment]
> Are you testing out applying your patch to 2.1.0rc1?

No, atm we are using the patches applied to v2.0.1 as of this PR. For sure I can try 2.1.0rc1 with this patches and see which is the behaviour.

**Comment by ivan-price-acted** [comment]
Hi there,

Just discovered this 'feature' whilst testing for our organisation: the fact that (currently) Draft dashboards provide a window for unauthorised users onto data they wouldn't normally be allowed to see, (if no RBAC roles are assigned) if this PR merges than those same unauthorised users will see the data when the dashboards are published.

I'm surprised we don't simply delete the line of code in question, i.e. be explicit in the RBAC rules that if we want a world-readable dashboard we assign a role that we know all users have ?

Why do we assume no roles == everyone cas access the data ? It is very likely users creating dashboards will forget to publish or unpublish their dashboards and not assign any RBAC rules, and will not understand the implications in terms of who can access their data between the two states.

As an administrator this presents a risk, trusting the users to do the right thing here (manage the draft / published AND the RBAC rules) is not realistic for us.

Can we make a plea for removing line 1994

```
or (dashboard.published and not dashboard.roles)
```

completely, and require the user to add an explicit role instead ?

-ivan

**Comment by villebro** [comment]
@ivan-price-acted you may have missed this PR, which I believe addresses at least part of the permission issue: #23586

**Comment by ivan-price-acted** [comment]
Hi @villebro indeed i had missed that and indeed that appears to address our concerns !

Looking forward to release 2.1.1 , thanks for the heads up !

**Comment by eschutho** [comment]
I'm going to close this pr for https://github.com/apache/superset/pull/23586 with hopes that the latter covers this use case.

**Pull request closed without merging**
