### PR TITLE
fix: Translations related to the date range filter

### LINKED ISSUE #17779: Superset translation native filters bug
#### How to reproduce the bug

1. Active other language, for example, German in `superset_config.py`.
2. Change the language of superset.
3. Create a dashboard with some charts.
4. Create a native filter of type 'Time grain' and other of type 'Time range'.
5. Save the filter configuration.
6. Click on time grain select. You will see the grains in english.
7. The time range chip will be set to 'No filter', but if you click on it, you will see 'Kein Filter' (german) as selected in the Popup.

### Expected results

The expected result of the Time grain select would be in german, and the chip in german too. I reviewed `messages.po` and `messages.json` and the translations are there. This happens in other languages that have the translations too.

### Actual results

Time grain is in english, and the chip is in english too.

#### Screenshots

Granularity:
granularity

Time range chip:
Time range chip

### Environment

- browser type and version: Google Chrome Versión 96.0.4664.93
- superset version: master head

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### LINKED ISSUE #25728: Translation: missing terms in french
Some terms are not translated in the UI

#### How to reproduce the bug

1. Open a dashboard
2. Click on ADD/EDIT Filters
3. Add a Time range filter
4. Filter has default value  : Choose Last
5. Choose 'Last quarter'
6. Save

### Expected results

The value of the filter should be "Le trimestre dernier" 

### Actual results

But it is "Last quarter"

The same for each period: "Last day" to ... "Last year" are not translated as value for the filter.
#### Screenshots

bug_french

### Environment

(please complete the following information):

- browser type and version:Firefox 118.0.2
- superset version: 2.1.0
- python version: 3.8.16
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### LINKED ISSUE #26061: Time filters not being translated, even with appropriate .json, .po & .mo files.
I'm already working on a PR for this - but figured I should create an issue and close the discussion.

===

### Discussed in https://github.com/apache/superset/discussions/25994

<div type='discussions-op-text'>

<sup>Originally posted by **Ralkion** November 15, 2023</sup>
Hello all,

I've been struggling with the translations for a couple of days now and I think I've resolved all my issues except these two. The value displayed in the Time Range filter after selecting a translated option is displayed in English.
image

The second issue I've run into is that the Time Grain options are all displayed in English.
image

I've read lots of discussions & MRs around translations - particularly those done by AndVK and hbruch. The most relevant is where hbruch says "No filter for many charts still is not localized." in this issue: https://github.com/apache/superset/issues/17779.

I also found this issue, https://github.com/apache/superset/issues/25728 complaining about the Time Range, and a comment saying that it's fixed in 3.0.0. However when I tried out 3.0.0 I found no changes to the problem outlined in that issue.

Is there something that I've missed in my configuration or are these two not actually translated in the UI?</div>

### PR DESCRIPTION
**Pull request by Ralkion**
### SUMMARY
This PR *partially* addresses discussion #25994 & issue #26061. It fixes the issue with the date range filter not showing translated values.

The issue was that the front-end client was sending requests that asked for strings like "Last year" and displaying the `timeRange` property in the response. As it stands now, the backend translates the human-readable string into actual dates, along with the requested string in the `timeRange` property (see [api.py#L98](https://github.com/apache/superset/blob/master/superset/views/api.py#L98). The front-end needed to translate the property coming back, but also needed to be sure that it expected the same value it sent (see changes in DateRangeFilter.tsx).

One thing I will say is that it was not clear at first how to go about fixing translation issues. I initially did the same as #26010, thinking that updating the .po and .json files was the correct path.
It wasn't until later that I realized that a 'proper' fix would follow the instructions [in the docs](https://superset.apache.org/docs/contributing/translations/). Most of this PR is actually the result of trying to resolve the issues that existed in the translation pipeline.

I'm going to outline it here. I know I was confused for a while, and it seems like others were also confused as per the discussion in #26010.
The translation is a multi-step process:
1. One should do a full extraction [/scripts/babel_update.sh](https://github.com/apache/superset/blob/master/scripts/babel_update.sh)
  - This will generate the .pot file based on the strings in the code
  - Then it will merge the .pot file with the existing .po files to the best of its ability
    - This will sometimes cause the tool to make 'guesses' at what the value should be if it doesn't already exist. Those guesses are annotated as 'fuzzy'.
2. The next step is to review/edit/fix the values in the .po file
3. Next generate the .json file(s) with the [/scripts/po2json.sh](https://github.com/apache/superset/blob/master/scripts/po2json.sh) file.
  - The .json file is used by the frontend code for translations
  - 'fuzzy' values in the .po are not translated to the .json files.
4. Finally generate the .mo file(s) with the command `pybabel compile -d superset/translations`
  - The .mo file is used by the backend code for translations
  - The .mo file is *not* checked into the git codebase. I'm unclear as to why the .json file is if the .mo file is not.
  - It is unclear looking at the UI which strings are generated by the frontend and which are generated by the backend

What is not addressed by this PR from the original issue is the time-grain values. I've looked into fixing this, but since the front-end is using standard 'select' input fields to display this, there's no good location in the front-end to force a translation. I do have a branch that does the translation in the backend (which is why I had to dig so deep into the translation stuff for the backend .mo files), but that's breaking some integration tests so I need to find another way to do this. I'm open to suggestions if anyone has any.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Before:
image
After:
image

### TESTING INSTRUCTIONS
1. Launch a new instance of superset loaded with examples and the French language enabled
2. Open the "Birth Rates" dashboard
3. Create a new "Time Range" filter
4. Switch to French
5. [ ] Verify that the new filter display the properly translated values after selecting one of the 'last X' options instead of the English versions

### ADDITIONAL INFORMATION
- [X] Has associated issue: 
  - Associated to but does not fix #17779
  - Associated to but does not fix #25728
  - Associated to but does not fix #26061
  - Related to PR #26010
  - Related to Discussion #25994
- [ ] Required feature flags:
- [X] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by Ralkion** [comment]
Thanks for running the checks.
* I fixed the PR title for the lint
* I'm not sure what I can do about the Docker build failing

As to the code coverage warnings. I don't see where those can be fixed. I looked for tests covering the code around the 2 flagged issues, but found nothing. If someone can point me in the right direction, I'm happy to fix those as well.

**Comment by fatiiates** [comment]
I was looking for a solution for this exact problem and came across your PR, thank you very much for your effort @Ralkion 

The docker issue in the workflow looks like a 502 error, it may have been a temporary outage. If you can, you should try restarting the workflow.

**Comment by aehanno** [comment]
Hi @Ralkion, you just have to change your title to have the last test to pass
the : nedd to be right after fix

**Comment by Ralkion** [comment]
Thanks @michael-s-molina for fixing the name. When it was mentioned that I had to fix the name I honestly thought I had done so already, so figured something else must've been up.

Due to the size of the PR, and the failing checks, I had planned on splitting this into two PRs -> one to address the functionality and one to address the translations, but never found the time to do so. Glad to see that it's passing the checks now!

**Comment by Edern** [comment]
Thanks @Ralkion for this PR. What is missing for this PR? Any hope to see it moving forward?

**Comment by Ralkion** [comment]
Thanks @Edern . I'm honestly not entirely sure what needs to come next. I was thinking it might make sense to split the PR into two parts - one for the functionality and one for the language files. That might make the review easier; I just haven't done this yet.

And honestly the PR was made so long ago there may be some things out-of-date, so It'd probably be a good idea for me (or the code owner(s)) to check and make sure everything still makes sense.

**Comment by rusackas** [comment]
I think most of this PR looked good... it just got bogged down because it's busy and disables lint warnings, probably :P 

If you want to rebase it to resolve the conflicts, I think we can try harder to shove it through. You did all the right things here as far as translated strings (using the `%()s` substitutions, and making changes to the .po files rather than the .json like so many do.

I don't think you need to split it... we just shouldn't have let it slip under the radar like it did. If you rebase it, I'll test/review it :)

**Comment by Ralkion** [comment]
Thanks so much @rusackas. I've merged main into the branch, so it should be all good now I think.

**Comment by rusackas** [comment]
Uh oh... I didn't realize it, but another PR updating .pot files and all the rest caused another nasty pile of conflicts. It's hard to tell how many changes you made to the .po files for this PR, but I think you might just need to rebase again, accept all changes, and re-generate the pot/po/json files. Reach out if you want to go through it on slack/zoom, since it's... kinda my fault this is stuck again.

**Comment by Ralkion** [comment]
No worries @rusackas. I'm working through the conflicts now. Quick question as I wanted to verify.

`_("..%(var)s", var="str")` is preferred over `_("..%(var)s") % {"var": "str"}` correct?

**Comment by rusackas** [comment]
> No worries @rusackas. I'm working through the conflicts now. Quick question as I wanted to verify.
> 
> `_("..%(var)s", var="str")` is preferred over `_("..%(var)s") % {"var": "str"}` correct?

I believe so, yes... and I think if you get it wrong, one of the scripts complains :)

**Comment by Ralkion** [comment]
@rusackas. I think I finally got through all the conflicts and re-applied my FR translations. Thanks for your assistance.

**Review by rusackas — APPROVED** [review]

**Comment by geido** [comment]
@Ralkion thanks for this! Some pre-commit checks are failing. I'll stamp this but those should be fixed to merge this in

**Review by geido — APPROVED** [review]

**Comment by Ralkion** [comment]
Thanks. I've managed to fix the pre-commit issue, but I've been struggling with the cypress one. I can't get cypress to run on my local machine (running on Ubuntu in WSL 1 due to corp restrictions).

I think I've traced it to this line though ([nativeFilters.test.ts#L429](https://github.com/apache/superset/tree/master/superset-frontend/cypress-base/cypress/e2e/dashboard/nativeFilters.test.ts#L429)). Without being able to run it, I'm not sure why it's finding `China` when it's expecting to find nothing.

**Pull request merged**
