### PR TITLE
add kerberos configure for Druid

### PR DESCRIPTION
**Pull request by pokyu**
add kerberos configure for Druid at  config.py

### CODE REVIEW

**Comment by pokyu** [comment]
there are many code for the kerberos, but it need to install krb5-workstation at Travis CI .

Can you change the CI configure?

**Comment by pokyu** [comment]
Is there any problem with this pr?

**Comment by mistercrunch** [comment]
Wait does this do anything? There's a new config key `ENABLE_KERBEROS_AUTHENTICATION`  but then no reference to it.

**Comment by pokyu** [comment]
commit the funcation "get_kerberos_auth", but travis-ci need to modify the environment configuration b for kerberos. what should I do？

**Comment by pokyu** [comment]
recommit

**Pull request closed without merging**
