### PR TITLE
chore(connector): Cleanup base models and views according to SIP-92

### PR DESCRIPTION
**Pull request by john-bodley**
### SUMMARY

This PR is a partial step towards [SIP-92 Proposal for restructuring the Python code base](https://github.com/apache/superset/issues/20630) where the `superset.connectors` submodule represents a bygone error of Superset when we supported both the Druid NoSQL and SQLAlchemy database engine connectors. Note long term the `superset.connectors` submodule should be abandoned with the models, views, and utilities moved elsewhere, but I thought it would be prudent to make said change in smaller bites. 

Many of the base models and views are superfluous as they're only extended by one and only class. This PR:

1. Integrates  the `BaseColumn` and `BaseMetric` classes into the `TableColumn` and `SqlMetric` classes respectively.
2. Integrates the `DatasourceModelView` class into the `TableModelView` class.
3. Moves `superset.connectors.base.models.BaseDatasource` to `superset.connectors.sqla.models.BaseDatasource`.

Ideally I would love to deprecate the `BaseDatasource` however at this stage I'm not brave enough. Currently (in addition to `SqlaTable` class) the `AnnotationDatasource` class is derived from it and thus sunsetting it is somewhat problematic. We maybe need to remove the `AnnotationDatasource` class somewhat like the `Query` class which behaves somewhat like a datasource/dataset.

### TESTING INSTRUCTIONS

CI.

### ADDITIONAL INFORMATION

- [x] Has associated issue: https://github.com/apache/superset/issues/20630
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by john-bodley** [comment]
@eschutho and @michael-s-molina I was wondering whether this PR would be a good candidate to have merged prior to the 3.1 cut given it refactors a non-trivial number of files.

**Review by michael-s-molina — APPROVED** [review]
LGTM

**Comment by eschutho** [comment]
@john-bodley This change looks really great! 

> @eschutho and @michael-s-molina I was wondering whether this PR would be a good candidate to have merged prior to the 3.1 cut given it refactors a non-trivial number of files.
This is already merged, so I'm late to respond, but in theory, I would say it would be good to merge refactors right after a minor/major release has gone out, so that the next release starts hardening on top of the refactor. But you're still going to be impacted for any patch releases. There's no way to make this perfect, of course.

**Comment by john-bodley** [comment]
@eschutho it's likely somewhat of a tough balance right? If you do this right after a major/minor release then it gives time for the `master` branch to harden, but it likely makes cherry-picking harder—as you pointed out. The value of merging these changes just prior to a branch cut, is the `3.0` branch will soon be a LTS branch and thus there's likely only going to be a few cherry-picks/reverts onto said branch, whereas most of the upcoming cherry-picks/reverts will be occurring on `3.1` which _should_ be relatively pain free.

**Pull request merged**
