### PR TITLE
fix: use dynamic time_grains for schema

### PR DESCRIPTION
**Pull request by eschutho**
### SUMMARY
When testing out TIME_GRAIN_ADDONS from the config, although new time grains are working for line charts, they don't work for table charts:
Explore_-_Untitled_Query_2_04_07_2021_18_50_18

This PR uses the built in time grains from the db_engine_spec and adds the time_grain_addons from the config to make the schema fields for the charts

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
after: 
Explore_-_Untitled_Query_2_04_07_2021_18_50_18

### TEST PLAN
I didn't see any unit tests for schemas. It's typically a very static file. I can add a new test if it feels warranted. Otherwise, to manually test, add a new time grain for the selected db and test with different types of charts. 

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by eschutho** [comment]
@betodealmeida @villebro

**Comment by eschutho** [comment]
failed test looks like a connection error.. rerunning.

**Comment by eschutho** [comment]
front-end check error is an npm timeout, and I ran the `tests/datasets/api_tests.py::TestDatasetApi::test_update_dataset_item_w_override_columns` test several times locally and it passes every time.

**Comment by eschutho** [comment]
🏷 rush!

**Review by villebro — APPROVED** [review]
LGTM!

**Review by suddjian — APPROVED** [review]

**Comment by eschutho** [comment]
Thanks @suddjian and @villebro!
🏷 ready-to-merge

**Comment by yousoph** [comment]
🏷️ 2021.13

**Pull request merged**
