### PR TITLE
basic elastic connector implementation

### PR DESCRIPTION
**Pull request by takkarharsh**
I tried running the code for earlier PR 2953 raised for elastic search , but i was not able to run it due to some package issue, 
I have updated the code and , now it is able to connect to elastic search , however ui view and agg function needs to be corrected further

**upgrade steps**
cd $SUPERSET_HOME 
pip install . --upgrade
superset db upgrade
superset init

### CODE REVIEW

**Comment by mistercrunch** [comment]
Can you keep my commit(s) intact so we can identify what's been put on top easily and keep have the history attributed to the right contributor.

**Comment by takkarharsh** [comment]
@mistercrunch I have cherry picked your changes and again merged the change, Thanks for pointing it.

**Comment by takkarharsh** [comment]
@mistercrunch Please have a look for the validity of implementation, if it looks good, let us know the further steps to fix the integration issues

**Comment by mistercrunch** [comment]
That's generally the right direction. I think the though part will be around filling up the methods in `models.py`

**Comment by bipinsoniguavus** [comment]
@mistercrunch we are getting the following error `Multiple head revisions are present for given argument 'head'; please specify a specific target revision, '<branchname>@head' to narrow to a specific head, or 'heads' for all heads`, could you please guide us why it happens everytime when we commit our code? we are fixing it by running `superset db merge heads` to resolve this problem, but we don't want to do on each commit. Please suggest the proper way to resolve it.

**Comment by takkarharsh** [comment]
Hi @mistercrunch, Please let us know the correct way to merge head as , every time there is a new checkin in master we get multiple head issue

**Comment by TimHeckel** [comment]
The requirements.txt file lists `5.5.3` as the minimum version for elasticsearch. Official SQL support landed in elasticsearch as of `6.3.0`.  It seems like this PR is still predicated on 5.5.3? Much like its [predecessor](https://github.com/apache/incubator-superset/pull/2953)? With perhaps an attempt to map the SQL coming in the SQL alchemy api without relying on the new sql[ _translate endpoint](https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-translate.html)? If that's the intent here, I think it would be smart to focus solely on ES 6.3.0+ -- am I understanding this correctly?

**Comment by mistercrunch** [comment]
https://preset.io/blog/2019-12-16-elasticsearch-in-superset/

**Pull request closed without merging**
