### PR TITLE
feat: multiple results pane on explore and dashboard

### PR DESCRIPTION
**Pull request by zhaoyongjie**
### SUMMARY

Currently, the Superset QueryContext contains multiple queries but the south pane in the Explore only supported single results pane. this PR intends to support multiple results pane in the Explore page and Dashboard.

This PR also add fully unit test for SamplePane and ResultsPane.
### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

https://user-images.githubusercontent.com/2016594/172156306-f0b5afe4-17a9-4901-a197-e2214e9bc001.mov

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [x] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by kgabryje — CHANGES_REQUESTED** [review]
Great feature! I only have 1 comment about the labels - I don't think that the results of second query should be labeled as "Results 1". I think that for multiple queries we should have either: `Results / Results 2` or `Results 1 / Results 2` or `Results A / Results B` (since the queries are labeled as `A` and `B` in control panel). In the charts that have only 1 query we should keep the label `Results`.

**Comment by zhaoyongjie** [comment]
> Great feature! I only have 1 comment about the labels - I don't think that the results of second query should be labeled as "Results 1". I think that for multiple queries we should have either: `Results / Results 2` or `Results 1 / Results 2` or `Results A / Results B` (since the queries are labeled as `A` and `B` in control panel). In the charts that have only 1 query we should keep the label `Results`.

Names are always a difficult thing. "Results 2" make sense. if have any good ideas, I will change them.

**Comment by kgabryje** [comment]
@kasiazjc WDYT?

**Review by kgabryje — APPROVED** [review]
Tested, works great except 1 minor thing. In Explore, when I change time column formatting from formatted to original, the change is applied in all tabs (results, results 2, samples). When I do the same thing on Dashboard, the change is applied only in 1 tab for that column.
Approving since it's a minor, non-blocking problem, but we may want to fix it before merging if it's quick and easy to fix

**Comment by zhaoyongjie** [comment]
I merged first, then fix it in the separate PR.

**Pull request merged**
