### PR TITLE
Add extraction function support for Druid queries

### PR DESCRIPTION
**Pull request by jasnovak**
Adds support for using extraction functions in Druid. Apply the extraction function in the queries, as well as filters.

NOTE: this PR requires the latest pydruid branch on master. Specifically, this commit: https://github.com/druid-io/pydruid/commit/875ae4cebaaf984c244783e289662434c4944be2

### CODE REVIEW

**Comment by mistercrunch** [comment]
Can you bump the pydruid dep to `0.4.2` as part of this PR?
https://github.com/apache/incubator-superset/blob/master/setup.py#L78

**Comment by mistercrunch** [comment]
@fabianmenges do you all use extraction functions much? Do you think you can review this?

**Comment by fabianmenges** [comment]
I don't think so, will verify.

**Comment by mistercrunch** [comment]
@fabianmenges @john-bodley I'm identifying this PR as something that could break things in your environment but I can't really test it in my environment since we don't have a lot of charts on Druid at this point. Can you 2 review/greenlight this?

**Comment by john-bodley** [comment]
@mistercrunch I don't believe we use extraction functions in any of the Druid clusters connected to Superset (per a quick code search).

**Comment by jeffreythewang** [comment]
We currently don't use extraction functions either.

This may have already been answered, but I'm curious why you didn't use the pydruid [`DimensionSpec`](https://github.com/druid-io/pydruid/blob/master/pydruid/utils/dimensions.py#L8) builder?

**Comment by jasnovak** [comment]
Hmm, I'm not sure where you are suggesting using DimensionSpec in this PR. Or are you asking that about the code in general? As far as the filters that this PR is creating, as I note in the code, I couldn't use the Dimension or Bound classes as they don't support extraction functions.

**Comment by jeffreythewang** [comment]
My bad, I thought you were attaching `extractionFn`s to `DimensionSpec`s as well like in [this](http://druid.io/docs/latest/querying/dimensionspecs.html#extraction-functions) way, but it seems like you are building the `Filter`s from `DimensionSpec`s that already have `extractionFn`s defined.

I assume you have users (or someone else) define their own `extractionFn`s in the datasource configuration?

**Comment by SpyderRivera** [comment]
The filtering works when an extractionFn is added to the dimension spec of the lookup, but then the look up doesn't work as a column.

```{
  "dimension": "country",
  "outputName": "country_group",
  "outputType": "STRING",
  "retainMissingValue": true,
  "type": "selector",
  "extractionFn": {
    "type": "lookup",
    "lookup": {
      "map": {
        "Algeria": "EMEA",
        "Faroe Islands": "EMEA",
        "Luxembourg": "EMEA",
        "Andorra": "EMEA",
        "Cameroon": "EMEA",
        "Burkina Faso": "EMEA",
        "Benin": "EMEA",
        "Bahrain": "EMEA",
        "Aland Islands": "EMEA",
        "Australia": "AU/NZ",
        "Iceland": "EMEA",
        "Cape Verde": "EMEA",
        "Germany": "EMEA",
        "Bosnia and Herzegovina": "EMEA",
        "Belgium": "EMEA",
        "Netherlands": "EMEA",
        "Central African Republic": "EMEA",
        "Belarus": "EMEA",
        "Albania": "EMEA",
        "Switzerland": "EMEA",
        "New Zealand": "AU/NZ",
        "Bulgaria": "EMEA",
        "Greenland": "EMEA",
        "Angola": "EMEA",
        "Chad": "EMEA",
        "Svalbard and Jan Mayen": "EMEA",
        "Comoros": "EMEA",
        "Austria": "EMEA",
        "Burundi": "EMEA",
        "Botswana": "EMEA"
      },
      "type": "map",
      "isOneToOne": false
    }
  }
}
``` 
VS

```
{
    "type": "lookup",
    "dimension": "country",
    "outputName": "country_group",
    "outputType": "STRING",
    "retainMissingValue": true,
    "lookup": {
      "type": "map",
      "map": {
        "Australia": "AU/NZ",
        "New Zealand": "AU/NZ",
        "Aland Islands": "EMEA",
        "Belgium": "EMEA",
        "Faroe Islands": "EMEA",
        "Greenland": "EMEA",
        "Iceland": "EMEA",
        "Luxembourg": "EMEA",
        "Netherlands": "EMEA",
        "Svalbard and Jan Mayen": "EMEA",
        "Austria": "EMEA",
        "Germany": "EMEA",
        "Switzerland": "EMEA",
        "Albania": "EMEA",
        "ALgeria": "EMEA",
        "Andorra": "EMEA",
        "Angola": "EMEA",
        "Bahrain": "EMEA",
        "Belarus": "EMEA",
        "Benin": "EMEA",
        "Bosnia and Herzegovina": "EMEA",
        "Botswana": "EMEA",
        "Bulgaria": "EMEA",
        "Burkina Faso": "EMEA",
        "Burundi": "EMEA",
        "Cameroon": "EMEA",
        "Cape Verde": "EMEA",
        "Central African Republic": "EMEA",
        "Chad": "EMEA",
        "Comoros": "EMEA"
      },
      "isOneToOne": false
    }
  }
```
Here you can see the filter works, but the column values for country group are not populating.
screen shot 2018-05-02 at 2 27 16 pm

**Comment by SpyderRivera** [comment]
@jasnovak Is the intent to have each lookup have an exFn? Or could the exFn be applied at filter time only?

**Comment by jasnovak** [comment]
@jeffreythewang yes, the extraction functions are defined in the druid datasource configuration, e.g. "Edit Druid Datasource"

**Comment by jasnovak** [comment]
@SpyderRivera I'm not sure I understand your question. The PR is just for folks that want to use the extraction functions -- eg. mapping or regex, in their column definitions.  Without this PR, if you filtered on a column that used a mapping or regex extraction fn in its spec, the filter would fail.

As far the 'lookup' type syntax, I understand they are an experimental feature in Druid per http://druid.io/docs/latest/querying/dimensionspecs.html. I don't know if Superset supports them, looks like maybe not. However, this PR doesn't address lookups. I'm just adding support for extraction functions.

**Comment by SpyderRivera** [comment]
I see. I was hoping it would fix the filters not working on lookups. Nvm

**Comment by jasnovak** [comment]
Just curious, is there a reason you can't define your map using extraction functions?

**Comment by SpyderRivera** [comment]
You mean like I did above? Is there a better way?

**Comment by SpyderRivera** [comment]
@jasnovak I can get the filter to work with this change OR the map to work, but not both at the same time. I can create two columns one to filter on and the other to group by. However, that is an ugly hack. Have you been successful with both working?

**Comment by jasnovak** [comment]
Yes, we do both: we create a mapped column using an extraction function, and use it to filter. Do you click both the "groupable" and  "filterable" box when you create your column?

Also, perhaps there's something amiss in your definition? Try defining like this:

{
  "type": "extraction",
  "dimension": "country",
  "outputName": "country_group",
  "outputType": "STRING",
  "extractionFn": {
    "type": "lookup",
    "dimension": "dimensionName",
    "outputName": "dimensionOutputName",
    "replaceMissingValueWith": "missing_value",
    "retainMissingValue": false,
    "lookup": {
      "type": "map",
      "map": {
        "Algeria": "EMEA",
        "Faroe Islands": "EMEA",
        "Luxembourg": "EMEA",
        ...

**Comment by SpyderRivera** [comment]
Type "extraction" appears to be where I was failing. Thanks so much!bitmoji

**Pull request merged**
