### PR TITLE
docs(featureflags): add GENERIC_CHART_AXES flag

### PR DESCRIPTION
**Pull request by novemberde**
### SUMMARY

I found that GENERIC_CHART_AXES flag exists via superset config file, but GENERIC_CHART_AXES is not described in the document.(This feature was applied via https://github.com/apache/superset/pull/17917)
This would be helpful for the superset user reading only documents.

### ADDITIONAL INFORMATION

- [x] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by stephenLYZ** [comment]
Thanks for the suggestion! I think the only point we might need to check is whether to put it into `stable` or `in testing`. cc @rusackas @villebro

**Comment by zhaoyongjie** [comment]
@novemberde I think that the feature should still need polishing.

**Comment by novemberde** [comment]
@zhaoyongjie Thank you for your review.
I've moved GENERIC_CHART_AXES feature to "in testing" block.

**Review by srinify — APPROVED** [review]

**Comment by srinify** [comment]
Thanks for the contribution!

**Pull request merged**
