### PR TITLE
feat: add risingwave.py in db engine specs

### LINKED ISSUE #22122: feat: add `db_engine_specs/risingwave.py` to support `time grain`
Hi, represents [RisingWave](https://github.com/risingwavelabs/risingwave). Want to add RisingWave into Superset's codebase for time grain support. RisingWave is a postgresql-compatitable database with sqlalchemy dialect. The driver is in here: https://github.com/risingwavelabs/sqlalchemy-risingwave.

I may need to add a `db_engine_specs/risingwave.py`. For the first version, I think highly alike `db_engine_specs/cockroachdb.py`.  
I tried locally, only after add this file, the `time grain` option is going to work. (PS: Although we support postgresql protocol, the connection URI string is `risingwave://....` instead of `postgresql://...`)

This issue is created before the PR. Glad to see your comments! Thanks.

### PR DESCRIPTION
**Pull request by BowenXiao1999**
### SUMMARY

Fixes #22122 

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

Can see the time grain option now.
image

### ADDITIONAL INFORMATION

- [x] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by villebro** [comment]
Hi @BowenXiao1999 , thanks for the contribution! A few comments:
- would it be possible to add documentation for how to connect to RisingWave here: https://github.com/apache/superset/tree/master/docs/docs/databases ?
- Based on your screenshot, you've selected monthly time grain, but still the table is displaying two values for January 2022 (there should only be one entry for that month). Is time grain working correctly?

**Comment by BowenXiao1999** [comment]
> Hi @BowenXiao1999 , thanks for the contribution and always happy to see more databases added to Superset! A few comments:
> 
> * would it be possible to add documentation for how to connect to RisingWave here: https://github.com/apache/superset/tree/master/docs/docs/databases ?
> * Based on your screenshot, you've selected monthly time grain, but still the table is displaying two values for January 2022 (there should only be one entry for that month). Is time grain working correctly?

Thanks! I will provide more context based on your suggestion.

**Comment by BowenXiao1999** [comment]
The reason that these entry is not merged is expected I think, cuz the raw records is chosen and no group by or agg is done on.
image

After switch to aggregation, they are correctly differetiate.
image

BTW, we have a demo link: https://risingwave-labs.notion.site/Tutorial-Building-streaming-dashboards-with-Superset-ae1c667aa6734bffa38f0d260734a470, but maybe we should not put it in doc seems it evolve fast.

@villebro PTAL again and feel free to give comments, thanks!

**Comment by villebro** [comment]
> The reason that these entry is not merged is expected I think, cuz the raw records is chosen and no group by or agg is done on. image
> 
> After switch to aggregation, they are correctly differetiate. image
> 
> BTW, we have a demo link: https://risingwave-labs.notion.site/Tutorial-Building-streaming-dashboards-with-Superset-ae1c667aa6734bffa38f0d260734a470, but maybe we should not put it in doc seems it evolve fast.
> 
> @villebro PTAL again and feel free to give comments, thanks!

Ah, makes sense 👍 @BowenXiao1999  are you able to add a note to the docs as requested in my previous review? We want to make sure others will also know that RisingWave is also supported!

**Comment by BowenXiao1999** [comment]
> > The reason that these entry is not merged is expected I think, cuz the raw records is chosen and no group by or agg is done on. image
> > After switch to aggregation, they are correctly differetiate. image
> > BTW, we have a demo link: https://risingwave-labs.notion.site/Tutorial-Building-streaming-dashboards-with-Superset-ae1c667aa6734bffa38f0d260734a470, but maybe we should not put it in doc seems it evolve fast.
> > @villebro PTAL again and feel free to give comments, thanks!
> 
> Ah, makes sense 👍 @BowenXiao1999 are you able to add a note to the docs as requested in my previous review? We want to make sure others will also know that RisingWave is also supported!

Sorry my bad, forgot to push. Already added, pls check.

**Review by villebro — APPROVED** [review]
LGTM

**Pull request merged**
