### PR TITLE
fix: handle TIME column serialization

### LINKED ISSUE #15905: Global async query -  Unserializable object {} of type <class 'datetime.time'>
Impossible to render a chart, say a TableView, presenting a Time column when the global async query feature is enabled.

### Expected results

We expected the chart to be rendered with the data on display.

### Actual results

Error message on display.

#### Screenshots

Capture d’écran 2021-07-27 à 12 13 02

#### How to reproduce the bug

1. Enable Global Async Query feature
2. Make sure to have a Redis configured for caching the result
3. Open a dashboard with a table view presenting a column Time
From the logs we have the following message
`{"asctime": "2021-07-27 13:46:01,004", "name": "superset.views.base", "levelname": "WARNING", "process": 18, "message": "Unserializable object 10:30:00 of type <class 'datetime.time'>"}`

### Environment

(please complete the following information):

- superset version: `1.2`
- python version: `3.7.9`
- node.js version: `Unknown`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

I looked up in the code base to see where the message was coming from. I found out two different methods aiming to perform the same job which is to json serialize dates
```python
def json_iso_dttm_ser(obj: Any, pessimistic: bool = False) -> str:
    """
    json serializer that deals with dates

    >>> dttm = datetime(1970, 1, 1)
    >>> json.dumps({'dttm': dttm}, default=json_iso_dttm_ser)
    '{"dttm": "1970-01-01T00:00:00"}'
    """
    val = base_json_conv(obj)
    if val is not None:
        return val
    if isinstance(obj, (datetime, date, time, pd.Timestamp)):
        obj = obj.isoformat()
    else:
        if pessimistic:
            return "Unserializable [{}]".format(type(obj))

        raise TypeError("Unserializable object {} of type {}".format(obj, type(obj)))
    return obj


def json_int_dttm_ser(obj: Any) -> float:
    """json serializer that deals with dates"""
    val = base_json_conv(obj)
    if val is not None:
        return val
    if isinstance(obj, (datetime, pd.Timestamp)):
        obj = datetime_to_epoch(obj)
    elif isinstance(obj, date):
        obj = (obj - EPOCH.date()).total_seconds() * 1000
    else:
        raise TypeError("Unserializable object {} of type {}".format(obj, type(obj)))
    return obj
```
It seems to me that the second might be at fault here.

### PR DESCRIPTION
**Pull request by frafra**
### SUMMARY
See the long comment at: https://github.com/apache/superset/issues/15905#issuecomment-929226661

### TESTING INSTRUCTIONS
Use a dataset with a `TIME` column (not `DATETIME`) and represent it using a `Table view`, by including the `TIME` column in `COLUMNS`.

### ADDITIONAL INFORMATION

- [x] Has associated issue: Fixes #15905
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by frafra** [comment]
I got a `too-many-return-statements` from pylint. Should I rework the whole cascade of `if` statements?

**Comment by frafra** [comment]
I tried to do a very small refactory, just to group together the 2 (now 3) instance types requiring a serialization via `str(...)`.

**Comment by villebro** [comment]
I'm surprised this is not happening with GAQ disabled - is this really the case? Long term we should probably introduce the option to format time values in the frontend like we do with `TIMESTAMP`/`DATE`/`DATETIME`, and to do that we would need to convert it into millisecond format like we do for `datetime`, introduce a new `GenericDataType` type called `TIME` that the frontend could then use to properly format the values. Is this something you would be willing to collaborate on @frafra ? In the mean time this could be a good compromise.

**Comment by frafra** [comment]
I do not have the time to tackle such a big effort at the moment, and this is my very first PR to Superset (excluding documentation).

**Comment by villebro** [comment]
@jerwen sorry for letting this slip between the cracks 🙁 I'll look at this now and try to get it into the next release.

**Review by villebro — APPROVED** [review]
LGTM - tested, reproduced the error on master and retested on the PR and saw the error resolved.

**Comment by villebro** [comment]
@jerwen you need to rebase this PR, as we've bumped the Python version on CI from 3.7 to 3.8, hence it's expecting the status to be reported for Python 3.8 tests (which weren't run here due to CI being on 3.7 at the time of the PR being opened)

**Comment by jerwen** [comment]
@frafra could you rebase this PR on master please ?

**Comment by jerwen** [comment]
@villebro the PR should now be ready for merge 🎊 
Thank you @frafra for your availability

**Comment by villebro** [comment]
Thanks all for helping out here!

**Pull request merged**
