### PR TITLE
fix(helm): Set priorityClassName to pods (superset, celeryBeat, celeryBeatFlower, celeryBeatWorker, celeryBeatWebsocket, jobs)

### PR DESCRIPTION
**Pull request by sabyrzhan**
### SUMMARY
Add ability to assign custom `priorityClassName` to pods. Each workload (superset, celeryBeat, celeryBeatFlower, celeryBeatWorker, celeryBeatWebsocket, jobs) has ability to assign custom `priorityClassName`

### TESTING INSTRUCTIONS
Specify custom `priorityClassName` to one of the deployments (superset, celeryBeat, celeryBeatFlower, celeryBeatWorker, celeryBeatWebsocket, jobs) to assign to its pods

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by craig-rueda** [comment]
Can you please bump the chart version and re-build the chart README?

**Comment by sabyrzhan** [comment]
@craig-rueda Yes, I can. But isnt it done automatically after the merge? Or should I trigger manually a workflow? Could you just elaborate a little about the process please?

**Comment by sabyrzhan** [comment]
Ok, I see it needs to be released locally if I am not wrong, and send as a separate PR like this, is that right?
https://github.com/apache/superset/pull/27946

**Review by villebro — APPROVED** [review]
LGTM (I've also needed this, so I assume this is useful to the general public, too). Not sure what the unrelated lint issue is, will try to repro locally.

**Comment by sabyrzhan** [comment]
@villebro Thank you for review. I wrote yesterday in slack channel. Maybe you missed it.
The related MR that broke it is this: https://github.com/apache/superset/pull/28762 from @hanslemm.
Seems like linting skipped on it: https://github.com/apache/superset/actions/runs/9381289976

**Comment by villebro** [comment]
> @villebro Thank you for review. I wrote yesterday in slack channel. Maybe you missed it. The related MR that broke it is this: #28762 from @hanslemm. Seems like linting skipped on it: https://github.com/apache/superset/actions/runs/9381289976

@sabyrzhan oh, that skip on CI shouldn't have happened IMO (probably warrants looking into separately from this, though) 🙁 Do you think you'll be able to fix it as a bycatch here? I'm assuming it should be simple to fix. If not I can take a stab at it.

**Comment by sabyrzhan** [comment]
@villebro sure, not a problem. Will start fixing right now and push it.

**Comment by villebro** [comment]
Thanks @sabyrzhan !

**Comment by sabyrzhan** [comment]
@villebro Pushed the fix.

**Review by villebro — APPROVED** [review]
Restamping - big thanks for fixing this unrelated error!

**Comment by villebro** [comment]
@sabyrzhan the helm chart should be automatically released by CI. Let me take a look to see why this is not the case..

**Comment by akerkau** [comment]
@villebro It seems as if this feature is still not available in the latest chart. Can you have another look?

**Comment by villebro** [comment]
I'm now investigating why the GHA workflow isn't triggering.

**Comment by akerkau** [comment]
@villebro Thanks for the fix. Happy about the working `priorityClassName` feature.

**Pull request merged**
