### PR TITLE
Update to fix the broken blueprints link

### PR DESCRIPTION
**Pull request by mmutiso**
The current link is http://flask.pocoo.org/docs/0.12/blueprints/ which redirects to a non-existent page. The new link is https://flask.palletsprojects.com/en/1.1.x/tutorial/views/.

### CATEGORY

Choose one

- [ ] Bug Fix
- [ ] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ x ] Documentation

### SUMMARY

Update to the broken link for redirection to flask blueprints.

### TEST PLAN
1. Go to superset's installation page and scroll to the blueprints section https://superset.incubator.apache.org/installation.html#blueprints
2. Click on the link on the first sentence; "Blueprints are Flask’s reusable apps"
3. The link should redirect to Flask's blueprint documentation at https://flask.palletsprojects.com/en/1.1.x/tutorial/views/

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by etr2460 — APPROVED** [review]
lgtm, although you might want to link to `https://flask.palletsprojects.com/en/1.0.x/tutorial/views/` since I think we're on v1.0.2 of flask right now. not sure if anything changed, but it might be more accurate

**Comment by mmutiso** [comment]
I have pushed a commit with the recommended change.

**Comment by etr2460** [comment]
@mmutiso thanks for the documentation! Would you mind rebasing to rerun travis then it should be good to go

**Comment by mmutiso** [comment]
Done. You can proceed to merge.

**Review by john-bodley — APPROVED** [review]

**Pull request merged**
