### PR TITLE
Druid subqueries support

### PR DESCRIPTION
**Pull request by michalmisiewicz**
### CATEGORY

- [x] Bug Fix
- [ ] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY
Druid SQL supports subqueries so superset should allow users to explore druid queries.

### AFTER SCREENSHOTS
Screenshot from 2019-07-12 18-22-56
Screenshot from 2019-07-12 18-24-28

### ADDITIONAL INFORMATION
- [x] Has associated issue: #7849 
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by mistercrunch** [comment]
Wait does Druid support subqueries now!?

**Comment by mistercrunch** [comment]
Looking at the docs, it looks like it does support subqueries, @john-bodley @betodealmeida does your version of Druid in production support them? Should we merge this?

**Comment by betodealmeida** [comment]
Oh, is this new? What version?

**Comment by michalmisiewicz** [comment]
@betodealmeida I've tested on druid 0.12.3

**Comment by betodealmeida** [comment]
This is awesome! Thanks, @michalmisiewicz!

**Comment by betodealmeida** [comment]
@john-bodley, I know AirBnB was running an older version of Druid. How do you think we should handle cases like this? Should we set druid version in `config.py` and add something like this:

```
# config.py
DRUID_VERSION = (0, 12, 3)
```

```
# superset/db_engine_specs/druid.py 
allows_subquery = config['DRUID_VERSION'] >= (0, 12, 3)
```

?

**Comment by john-bodley** [comment]
@betodealmeida I just checked the version of our Druid clusters. A couple of them are running on versions pre `0.12.3` and thus we would need to have a mechanism for enabling this feature on a per cluster basis. 

Rather than having this defined globally in the config it seems we'll need to add a field (and thus database column) to the `druidclustermodelview`.

**Comment by mistercrunch** [comment]
We have a method to find out which version is the cluster running here https://github.com/apache/incubator-superset/blob/master/superset/connectors/druid/models.py#L165

Now it's a matter of making `allows_subquery` a method that receives the cluster/database, or something like that.

**Comment by michalmisiewicz** [comment]
The subqueries are supported since druid 0.10 - the first version with sql support.  
https://github.com/apache/incubator-druid/blob/master/docs/content/querying/sql.md

**Review by mistercrunch — APPROVED** [review]
Ok then, LGTM

**Comment by KreteJalakasPiP** [comment]
Hi, I am totally new Superset user - is this option "Superset should enable user to create visualization for druid in SQL lab " will be then soon available?

**Pull request merged**
