### PR TITLE
[js deps] fix dependencies vulnerabilities

### PR DESCRIPTION
**Pull request by mistercrunch**
```
found 68 vulnerabilities (63 low, 4 moderate, 1 high) in 41818 scanned packages
  run `npm audit fix` to fix 4 of them.
  64 vulnerabilities require semver-major dependency updates.
```

### CODE REVIEW

**Comment by kristw** [comment]
`react-map-gl` may have api changes. I had to do some updates for `MapBox`.  
Have you verified with the `deck.gl` charts?

**Comment by mistercrunch** [comment]
I had looked at the `deck.gl demo` examples dashboard to validate, they look fine.

Though it looks like `MapBox` doesn't work in `master` for now, seems unrelated to this though.

**Comment by kristw** [comment]
@mistercrunch `MapBox` has an issue particularly with the demo in `master`. Some `lat` or `lon` values has long tailed decimal point (due to float being float) and are serialized as `json-bignumber` and crashed the `MapBox` because it expects `number`, not `object`. Adding rounding to the query in `viz.py` probably helps.

**Comment by mistercrunch** [comment]
@kristw I limited precision to 10 digits, the plan is probably to deprecate this visualization eventually

**Review by kristw — APPROVED** [review]

**Comment by kristw** [comment]
Approved!

**Comment by muraiki** [comment]
Do you know what the high vulnerability package was? Should I be concerned about this as an end user running release 0.28.1?

**Pull request merged**
