### PR TITLE
fix: style tweaks for inconsistent button spacing

### PR DESCRIPTION
**Pull request by rusackas**
### SUMMARY

The `Button` component had some styles to adjust margins of consecutive sibling buttons. This wasn't working in all cases since some were rendered as different element types (`button` or `a`). This PR adds a (library agnostic) class to the `Button` elements, so that they can be spaced more reliably using an Adjascent Sibling Selector (`+`).

I also pulled out the `grid-gap` from `.ResultSetButtons` since the above adjustments take care of the spacing.

~~This also includes a little bycatch of a seemingly unnecessary `React.Fragment`~~

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

Before:
image

After:
image

### TEST PLAN

Screenshots look right
Storybook looks good
Other buttons elsewhere in the UI show no fallout.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [x] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

reviews welcome from @eschutho @AAfghahi @michael-s-molina  (or anyone else, of course)

### CODE REVIEW

**Review by maloun96 — APPROVED** [review]

**Comment by michael-s-molina** [comment]
@evans The fragment is used to absorb `Nav` props that shouldn't be passed to HTML elements. The intention was to remove the warning while we don't migrate to AntD.

**Review by eschutho — APPROVED** [review]
Thanks @rusackas!

**Comment by junlincc** [comment]
Looking perfect, thanks for the fix! ✅ 
did a quick check on all button spacing and alignment, everything looks good, beside https://github.com/apache/superset/issues/13112, hopefully we can get to it soon... 
Screen Shot 2021-02-22 at 9 04 08 PM

**Comment by rusackas** [comment]
> @rusackas The fragment is used to absorb `Nav` props that shouldn't be passed to HTML elements. The intention was to remove the warning while we don't migrate to AntD.

Oops! I put it back. My console log thanks you.

**Review by villebro — APPROVED** [review]
This is a nifty trick to know 👍

**Pull request merged**
