### PR TITLE
[SECURITY] bump packages with security vulnerabilities

### LINKED ISSUE #8571: Security vulnerability in lodash-es < 4.17.14
Github reports the following vulnerability in lodash-es < 4.17.14:
https://github.com/advisories/GHSA-jf85-cpcp-j695

Remediation
Upgrade lodash-es to version 4.17.14 or later. For example:
```
"dependencies": {
  "lodash-es": ">=4.17.14"
}
```
or…
```
"devDependencies": {
  "lodash-es": ">=4.17.14"
}
```

#### How to reproduce the bug

...

### Environment

...

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by nytai**
### CATEGORY

Choose one

- [x] Bug Fix
- [ ] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY

Upgrades several packages with known security vulnerabilities as reported by github and npm
### TEST PLAN

- Front end loads 
- examples dashboards render 

### ADDITIONAL INFORMATION

- [x] Has associated issue: Fixes #8571 
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by suddjian — APPROVED** [review]
🔒

**Review by etr2460 — COMMENTED** [review]
was it intentional that cypress got removed from the package lock in this PR?

**Comment by nytai** [comment]
@etr2460 definitely not intentional. 

`cypress` isn't listed anywhere in dependencies/dev-dependencies, which is probably why my run of `npm install` caused it to be removed. I see there is a install cypress script: `"install-cypress": "npm install cypress@3.4.1"`. My guess is that whoever updated the package lock file last had run that command before. 

I ran the script, and since I'm running npm5 (which defaults to `--save`), cypress was added as a dependency in package.json. Do you know if there's a reason/history for the `install-cypress` script and not just listing it as a dependency?  Additionally do you know if there's a reason for _not_ list it as a dependency?

I've updated the pr with what happened after I:
- `npm run install-cypress`
- `npm install`
- `git rebase master`

Looks like now I'm adding cypress in both package.json and package-lock.json

**Comment by mistercrunch** [comment]
We do not want `cypress` in `package.json` and `package-lock.json` as it increase the build time and docker image size significantly.

We'll need some effective way to prevent `cypress` from bleeding into this package... Probably by having another package.json that depends on this one somewhere. Is it possible to reference a relative folder in a package.json? Or maybe with some `npm link` trickery?

In the meantime we should push this forward (without cypress in the package)

**Comment by nytai** [comment]
@mistercrunch sounds good. I went ahead and created an issue for it: https://github.com/apache/incubator-superset/issues/8593

**Review by dpgaspar — APPROVED** [review]

**Pull request merged**
