### PR TITLE
refactor: Removes the deprecated DASHBOARD_FILTERS_EXPERIMENTAL feature flag

### PR DESCRIPTION
**Pull request by michael-s-molina**
### SUMMARY
As part of the [4.0 approved initiatives](https://github.com/orgs/apache/projects/292/views/1), this PR removes the `DASHBOARD_FILTERS_EXPERIMENTAL` feature flag and the associated `GroupByFilterPlugin`.

The previous value of the feature flag was `False` and now the feature is permanently removed.

### TESTING INSTRUCTIONS
CI should be sufficient for merging this PR. We'll do a complete testing of 4.0 after all approved proposals are merged.

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by villebro** [comment]
@michael-s-molina was there broad agreement to remove the groupby Filter? The reason I ask is because I don't think it's been marked as deprecated, and I believe some orgs may be using it. Ping @amitmiran137 @simcha90 @cccs-jc @cccs-rc for heads up and any concerns if you missed the discussion (not sure if this is relevant for your orgs or not).

While I'm sure this should rather be brought up in the town hall, I think there's good use cases for the groupby filter, and cleaning it up and adding full support to the ECharts plugin package could be a fairly low hanging fruit, and one that I could potentially take on if this is still deemed relevant for other users.

**Comment by michael-s-molina** [comment]
@villebro It's a good question. We can submit a [specific proposal](https://github.com/orgs/apache/projects/292/views/1?pane=issue&itemId=48229848) for lazy consensus for removing the `GroupByFilterPlugin` and see if someone is using it and is able to support it. If not, then let's remove it.

**Comment by michael-s-molina** [comment]
The drill by feature provides a similar functionality as the `GroupByFilterPlugin` and for that reason we may choose to remove the plugin.

**Comment by cccs-rc** [comment]
> @michael-s-molina was there broad agreement to remove the groupby Filter? The reason I ask is because I don't think it's been marked as deprecated, and I believe some orgs may be using it. Ping @amitmiran137 @simcha90 @cccs-jc @cccs-rc for heads up and any concerns if you missed the discussion (not sure if this is relevant for your orgs or not).
> 
> While I'm sure this should rather be brought up in the town hall, I think there's good use cases for the groupby filter, and cleaning it up and adding full support to the ECharts plugin package could be a fairly low hanging fruit, and one that I could potentially take on if this is still deemed relevant for other users.

Thanks for the heads up @villebro! We're not currently using the Group By filters, but admittedly that's only because I hadn't spotted the feature flag before. I agree there are good use cases for it that aren't entirely covered by the drill by feature.

**Review by john-bodley — APPROVED** [review]

**Pull request merged**
