### PR TITLE
Only creating perms for restricted metrics

### PR DESCRIPTION
**Pull request by mistercrunch**
The previous `is_restricted` PR created way too many permissions, we really just need for the restricted metrics to have permission created

### CODE REVIEW

**Comment by mistercrunch** [comment]
@x4base

**Comment by x4base** [comment]
@mistercrunch 
When will init_metrics_perm() be triggered?
Does the user have to run `caravel init` every time is_restricted is toggled?
Or maybe we need to trigger it in post_update of SqlMetricInlineView and DruidMetricInlineView, and also  in checkbox() ?

**Comment by mistercrunch** [comment]
Good catch. I added post_update hooks and removed the checkbox from the list view. I figured it's ok to add a few extra click for this feature. Another option would be to use the sqlalchemy event handler.

**Comment by x4base** [comment]
I don't know there is such event handler in sqlalchemy, but sounds good!

**Comment by mistercrunch** [comment]
https://github.com/airbnb/caravel/blob/131372740e79fa0d6ebd7484026cb9ac5918f631/caravel/models.py#L260

**Pull request merged**
