### PR TITLE
refactor(views): Dashboard, Slice, Database, SQL_Lab into separate folders

### PR DESCRIPTION
**Pull request by S-YOU**
It is easier to find each components in folders, instead of all in one huge file.

Hope this does not break CI, or I will fix it.

### CODE REVIEW

**Comment by mistercrunch** [comment]
I'm not against breaking down `views/core.py` as it has grown to be a pretty big module, but I'd like to follow a different approach.

I don't like putting logic in `__init__.py` files. I think they should generally be used only for defining how packages should be exposed (show or hiding modules, lifting classes from module up to package level, ...)

Another approach to breaking things down could be around getting all the model views our of `core.py` and into `model_views.py`

**Comment by S-YOU** [comment]
Thanks for review. I agree that __init__.py should be used for exposing purpose.

Moving to model_views.py does not make much differrence on visibility.

How about moving to another file in subfolders and use __init__.py to expose those?

**Comment by mistercrunch** [comment]
I mean you could break down `core.py` into different subsets of views. Would be:
* explore.py
* dashboard.py
* sql_lab.py
* maybe `core.py` becomes `common.py`
* and maybe datasource_editor.py, though I think that belongs in the `connectors` package for the most part

Though this kind of PR creates annoying merge conflicts. Either we try to merge as much as possible beforehand, bite the bullet and do it, or wait later on until it's more needed.

**Comment by mistercrunch** [comment]
Also note that another approach would be to structure the apps more as blueprints where the first breakdown would be explore, dashboard and sql_lab, and each one of these package (flask blueprint) would have their own views.py / models.py / templates.

I'm not sure if it's worth it at this time though.

**Comment by S-YOU** [comment]
I see, may be I should do one by one, instead of many to avoid merge conflicts. I will do dashboard as it should be small changes.

Regarding blueprints, I dont have much knowledges yet, so I will stick to current approach.

**Comment by S-YOU** [comment]
Looks like you are going to release 0.18 very soon. I guess I will do it later then.

**Pull request closed without merging**
