### PR TITLE
[DO NOT MERGE] demonstrate time comparison in Table chart 

### PR DESCRIPTION
**Pull request by zhaoyongjie**
### SUMMARY

Time comparison in Table Viz and apply the AA panel in it.

image

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by eschutho** [comment]
Thanks for this example @zhaoyongjie!

**Comment by eschutho** [comment]
@zhaoyongjie since we have the time column in the filter, do you think it's possible to allow users to build a chart without the time column as a dimension as well? Maybe we're doing something wrong, but we weren't able to remove the time dimension from this chart. 
Screenshot 2024-03-19 at 3 45 33 PM

**Comment by zhaoyongjie** [comment]
> since we have the time column in the filter, do you think it's possible to allow users to build a chart without the time column as a dimension as well? Maybe we're doing something wrong, but we weren't able to remove the time dimension from this chart.

@eschutho may be not 100% percent understand why the time dimension should be removed from the chart, --- the filter only affect the where clause but the time dimension should be aggregated from the source table.

Hidden time dimension in the frontend might be more making sense? The custom tab in Table chart is able to set different format by columns, the same logic might add in it, for instance, the "hidden" checkbox should be added in there.

**Comment by eschutho** [comment]
Gotcha. What if we don't want to aggregate/group by the time, though, but rather a different column? Here's an example of what we're trying to get to. It's grouped by name and filtered by date. The time column only serves as a filter for the selected metrics and the time comparison.
Screenshot 2024-03-20 at 4 28 52 PM

Another example from this PR, we want to group by product line, and remove the date. We could remove it from the frontend, but there will still be duplicate rows on the product lines. 
Screenshot 2024-03-20 at 4 33 48 PM

**Comment by zhaoyongjie** [comment]
> What if we don't want to aggregate/group by the time, though, but rather a different column? Here's an example of what we're trying to get to. It's grouped by name and filtered by date. The time column only serves as a filter for the selected metrics and the time comparison.

Hey @eschutho, thank you for clarifying it. I've just realized this use case. In my opinion, it might not be a time comparison but rather a feature that sounds like "metrics comparison based on arbitrary dimensions".

What's interesting is that I've opened a [SIP](https://github.com/apache/superset/issues/27544) to refactor the time_offset field in the Query_Object in order to build such queries.

Could you please take a look at the SIP to see if it aligns with your requirements?

**Comment by eschutho** [comment]
Thanks @zhaoyongjie! Taking a look.

**Pull request closed without merging**
