### PR TITLE
[fix] Push browser history on pagination in react listviews

### PR DESCRIPTION
**Pull request by lilykuang**
### CATEGORY

Choose one

- [x] Bug Fix
- [ ] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY

Before: 
- When browser button back was hit, it went to prior view not prior paginated page 

After: 
- When browser button back was hit, it went to prior paginated page

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

BEFORE:
https://www.loom.com/share/2aa499227bb044fc9728a6910f01f650
AFTER:
https://www.loom.com/share/f049bbb13cc848d2ad14bdce11bf437d
### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [x] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### REVIEWERS
@rusackas @nytai

### CODE REVIEW

**Comment by willbarrett** [comment]
It might be worth pushing a change to trigger a rebuild - looks like the JS build failed due to a flake (Javascript OOM)

**Comment by dpgaspar** [comment]
Triggered a rerun for the failed tests

**Review by nytai — APPROVED** [review]
LGTM. It's a working solution though a little repetitive. It looks like there's some issues syncing state, since we're storing it in various places (query params, internal filters, actual state that triggers data fetching). Part of the reason for this fragmentation is due to changing requirements (holding state until submit button is pressed, storing state in queryparams, etc.). Once the dust settles on these listview redesigns we should come back and try to consolidate state as much as possible. eg, we can create a hook called useStateWithQueryParam which would abstract away the queryParams state for us.

**Review by rusackas — APPROVED** [review]
LGTM!

**Pull request merged**
