### PR TITLE
refactor: icon to icons for infotooltip component

### PR DESCRIPTION
**Pull request by pkdotson**
### SUMMARY
this pr refactors the infotooltip component from icons to icon

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
before 
Expose in SQL Lab 6

after
Screen Shot 2021-06-29 at 4 15 47 PM

### TESTING INSTRUCTIONS
got to database modal to verify infotooltip icon

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by michael-s-molina** [comment]
Can you fix the vertical alignment of the checkbox, text, and icon?

**Comment by pkdotson** [comment]
> Can you fix the vertical alignment of the checkbox, text, and icon?

Yep fixed and updated in new after photo

**Comment by michael-s-molina** [comment]
> > Can you fix the vertical alignment of the checkbox, text, and icon?
> 
> Yep fixed and updated in new after photo

The `i` icon still looks a little bit up.

**Review by michael-s-molina — APPROVED** [review]

**Pull request merged**
