### PR TITLE
perf(native-filters): Decrease number of unnecessary rerenders in native filters

### PR DESCRIPTION
**Pull request by kgabryje**
### SUMMARY
The goal of this PR is to remove redundant rerenders of key components that build `FilterBar` in order to enhance the performance of native filters.
Components refactored: `FilterBar`, `FilterControls`, `FilterControl`, `FilterValue`, `CascadePopover`.
The method was similar to the one used in PRs #16421, #16444, #16525, #16545.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
The number of redundant rerenders of key components the changes (measured by counting logs produced by `whyDidYouRender` library) - tested on `Video Game Sales` dashboard with 5 native filters added:

**BEFORE**
* FilterBar - 182
* FilterControls - 252
* CascadePopover - 960
* FilterControl - 985
* FilterValue - 760

**After**
* FilterBar - 0
* FilterControls - 0
* CascadePopover - 0
* FilterControl - 0
* FilterValue - 20

Loading time on large test dashboard (~80 charts, 15 native filters) - measured as time from opening the dashboard to all charts and native filters fully loaded:

**BEFORE**
~60 seconds

https://user-images.githubusercontent.com/15073128/137484637-f46d8baf-d5f5-4c48-a652-4a90b66b1a68.mov

**AFTER**
~45 seconda

https://user-images.githubusercontent.com/15073128/137484738-d7134c2d-8512-4d5c-b2b1-f2e298058dfd.mov

### TESTING INSTRUCTIONS
Every feature related to native filters should work the same as before

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

CC @junlincc @rusackas

### CODE REVIEW

**Review by villebro — APPROVED** [review]
AMAZING work! So much unnecessary rerendering cleaned up here, wow! Code LGTM and works very well! 👍

**Review by michael-s-molina — APPROVED** [review]
Left some non-blocking comments. Unfortunately, we still don't have enough automated tests to make us feel safe merging these types of changes. Can we get @jinghua-qa approval before merging?

**Comment by michael-s-molina** [comment]
The difference in the number of renders is remarkable! Really cool work! 🚀

**Comment by graceguo-supercat** [comment]
Thanks so much for the work! let's merge it into master and I will test it with our benchmark dashboards to see the improvement.

**Pull request merged**
