### PR TITLE
Improve the error message in the slices

### PR DESCRIPTION
**Pull request by x4base**

### CODE REVIEW

**Comment by mistercrunch** [comment]
I like the idea of improving the error messages but we should allow for both custom message and this introspection of the web response. What about `slice.error` receives both `message` and `response` and we print a nice div (perhaps expandable, with more details) depending on what is provided by the user?

**Comment by x4base** [comment]
Do you mean something like this?
```
      getErrorMsg: function (xhr) {
        if (xhr.statusText === "timeout") {
          return "The request timed out";
        }
        var msg = "";
        if (!xhr.responseText) {
          var status = xhr.status;
          msg += "An unknown error occurred. (Status: " + status + ")";
          if (status === 0) {
            // This may happen when the worker in gunicorn times out
            msg += " Maybe the request timed out?";
          }
        }
        return msg;
      },
```
, then
```
-      error: function (msg) {
+      error: function (msg, xhr) {
         token.find("img.loading").hide();
-        var err = '<div class="alert alert-danger">' + msg + '</div>';
+        var err = msg ? ('<div class="alert alert-danger">' + msg + '</div>')
+            : "";
+        err += '<div class="alert alert-danger">' + this.getErrorMsg(xhr) + '</div>';
         container.html(err);
         container.show();
```

**Comment by mistercrunch** [comment]
Yeah that looks right.

**Comment by x4base** [comment]
I have updated the branch

**Comment by x4base** [comment]
Updated again to solve the conflict

**Pull request merged**
