### PR TITLE
Add an "Edit Mode" to Dashboard view

### PR DESCRIPTION
**Pull request by mistercrunch**
stxstantp0
What changes when toggling between edit/view mode:
* can't edit title
* can't remove slices
* can't move slices
* only actions available: "force refresh" and "set autorefresh"

### CODE REVIEW

**Comment by graceguo-supercat** [comment]
apply_filter
 
Hi Max, thanks for adding 'Edit Mode'. I have a question, please see the attached example:
User has a dashboard with a filter-box, which can apply filter to all slices. If they changed filter, they can also saveas/overwrite the dashboard with changed filter value. 
So In this use case, applying filter and save dashboard with different filter value, is it to be in a `edit mode`?

**Comment by mistercrunch** [comment]
Right, we need to allow for "Save As" in view mode. I had missed that. Let me add it back.

Note that changing the filter does not trigger the "has changed" notification.

**Comment by mistercrunch** [comment]
@graceguo-supercat I addressed your comment

**Comment by graceguo-supercat** [comment]
@mistercrunch It looks good to me. Only 1 question to clarify: all of the components' 'editMode' default value is `false`, but dashboard's initial state is set `editMode` be true. is it an intended design? thank you.

**Comment by mistercrunch** [comment]
@graceguo-supercat good point, I meant to set 1editMode`'s default to `false` everywehre, let me fix that.

**Review by graceguo-supercat — APPROVED** [review]
LGTM

**Pull request merged**
