### PR TITLE
fix(plugin): Simplify Peru GeoJSON file (#22923)

### LINKED ISSUE #22923: Peru geojson file is huge
`@superset-ui/legacy-plugin-chart-country-map` provides geometry for 85 countries.  
Most of these GeoJSON files weight is 50 ~ 300 Ko. The *largest* country (Russia) file is 750 Ko.

→ Peru is **9.5 Mo**. ❗

As compared to neighboring countries, Peru's geometry is over-detailed.

#### How to reproduce the bug

1. List files in `superset-frontend/plugins/legacy-plugin-chart-country-map/src/countries/`

### Expected results

Having homogeneous geometry précisions

### Actual results

The geometry of Peru is extravagantly large compared to other countries.

#### Screenshots

image

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by mabhub**
### SUMMARY

Simplify Peru GeoJSON file to have similar précision (and file weight) as other countries.

### ADDITIONAL INFORMATION

- [x] Has associated issue: Fixes #22923
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by rusackas** [comment]
Thanks for the PR! Updated the PR description to automatically close the PR when this merges. When CI passes, I'll spin up a test environment so any reviewer (myself or otherwise) can play around with it.

**Comment by rusackas** [comment]
Hmm... something's not right here. The new map seems to render half the country, and draws a giant bounding box around it, as seen in the "after" screenshot below. You can test it out on the ephemeral environment linked above.

Before: 
image

Testing on ephemeral environment.
image

**Comment by kakoni** [comment]
@rusackas It could be that the geojson in this PR is correct, but ```d3.geo.centroid``` returns wrong center coordinates (and you endup with a map like above) see https://github.com/d3/d3/issues/1883 or https://github.com/d3/d3-geo/issues/81.

**Comment by rusackas** [comment]
> @rusackas It could be that the geojson in this PR is correct, but `d3.geo.centroid` returns wrong center coordinates (and you endup with a map like above) see [d3/d3#1883](https://github.com/d3/d3/issues/1883) or [d3/d3-geo#81](https://github.com/d3/d3-geo/issues/81).

Hmm... could be, but I'm still not sure why this one would be an outlier from the other countries.

**Review by rusackas — APPROVED** [review]

**Comment by rusackas** [comment]
Check out this blog post, I think this is the answer: https://ruky.me/2023/03/11/how-to-correctly-load-your-country-in-to-apache-superset/

... which probably leads to a bigger project to fix the underlying issue...

**Review by rusackas — CHANGES_REQUESTED** [review]
We just need to make sure the map is working (see related blog post link) before we merge this, and the map winds up broken (even if smaller). Thanks!

**Comment by rusackas** [comment]
Closing this... this has been fixed via updates to the Jupyter notebook,

**Pull request closed without merging**
