### PR TITLE
Using the time zone with specific name for querying Druid

### PR DESCRIPTION
**Pull request by asdf2014**
Using the time zone with specific name for querying Druid.

Just use `DRUID_TZ = tz.gettz('Africa/Abidjan')` to test, and then it will be modified into `tz.tzutc()`.

By the way, sorry for creating so many PRs. I just figure out that i should create the new branch `time_zone` to contribute codes. :)

### CODE REVIEW

**Comment by xrmx** [comment]
I don't understand why we want to use a random timezone as default in our config.

**Comment by asdf2014** [comment]
Not random... The timezone of `Africa/Abidjan` is +00:00~+00:00

**Comment by xrmx** [comment]
@asdf2014 arbitrary not random, sorry. Anyway why you want to do so? It's just as an example of using gettz? What's wrong with utc?

**Comment by asdf2014** [comment]
There will be a option to support when we meet a wrong result from `tz.tzlocal()`.

**Comment by asdf2014** [comment]
Yep, i just want add `tz.gettz('Africa/Abidjan')` as a doc for superset's users.

**Comment by asdf2014** [comment]
By the way, i got `Server Error (500)` message when i visit [https://landscape.io/github/airbnb/superset/pulls/2143](https://landscape.io/github/airbnb/superset/pulls/2143)...

**Comment by asdf2014** [comment]
I got Server Error (500) message when i visit [https://landscape.io/github/airbnb/superset/pulls/2143](v) too... What happened to landscape? :-(

**Comment by mistercrunch** [comment]
LGTM !

**Comment by asdf2014** [comment]
Okey :D

**Comment by zaczhao** [comment]
is that changing the default timezone in the query?
image
I want to change the "UTC" to other timezone as the datetime stored in DB are not "UTC" timezone, that query return the datetime with some hours delay.
anyone has solution?
Cheers
Zac

**Pull request merged**
