### PR TITLE
fix: Column name and icons alignment in the Datasource Panel (Explore)

### LINKED ISSUE #13449: [Explore] Long columns and metrics with descriptions wrap differently in Dataset panel
## Description

The "Info" icon of a very long metric will not wrap to a new line, but it will for a very long column.

### PR DESCRIPTION
**Pull request by geido**
### SUMMARY
Fixes #13449 by changing the alignment of the column name and icons in the Datasource Panel.

### BEFORE
before

### AFTER
after_ellipsis

### TEST PLAN
1. Open a chart in Explore
2. Edit the dataset and change the label of a column with a very long one
3. Make sure that the left icons, the column name, and tooltip icon are showing on the same line and that the column name cuts with ellipsis
4. Make sure the responsive behavior works when the Datasource panel width is increased/decreased

### ADDITIONAL INFORMATION

- [x] Has associated issue: #13449
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by geido** [comment]
@junlincc @rusackas

**Comment by geido** [comment]
Thanks for spotting that @junlincc. That was a problem specifically for names with spaces, affecting both Columns and Metrics. It's fixed now.

**Comment by junlincc** [comment]
perfect after the fix thanks! 
Screen Shot 2021-05-11 at 10 25 32 AM

**Review by junlin-qa — APPROVED** [review]

**Review by rusackas — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
