### PR TITLE
style: eslint curly rule

### PR DESCRIPTION
**Pull request by rusackas**
### SUMMARY

On a recent PR, I had a simple if/else, sans-curlies, and @ktmud asked me to put them in. Seemed like a reasonable style call, so I'm adding a lint rule to make sure we're more consistent about this going forward!

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by villebro — APPROVED** [review]

**Review by ktmud — APPROVED** [review]
Thank you!

**Review by etr2460 — COMMENTED** [review]
could you add this rule for ts/tsx files too?

As a followup in another PR, we should fix this file so that the TS config extends from the JS one probably

**Comment by rusackas** [comment]
> could you add this rule for ts/tsx files too?
> 
> As a followup in another PR, we should fix this file so that the TS config extends from the JS one probably

Hah, I did, but forgot to push it! Incoming!

**Comment by ktmud** [comment]
Hmm, I thought ESLint `overrides` extends the root `rules`?

**Pull request merged**
