### PR TITLE
fix: x axis title disappears when editing bar chart

### LINKED ISSUE #29877: Bar Chart: Bar Chart Echart X Axis and Y Axis labels not showing
### Bug description

When creating a bar chart, we are able to add the x axis and y axis labels. However, upon editing the labels, the x axis and y axis labels gets removed. Besides, the x axis label rotation does not function as well. 

### How to reproduce the bug

1. Go to chart page and click on + Chart
2. Select a dataset and bar chart
3. Input the required data and generate the chart. 
4. In the customize tab, add an x-axis and y-axis label together with the label rotation. 
5. Save the chart, exit the page and select the saved chart from the chart list. 
6. Edit the x-axis and y-axis label, the label will the removed. 

### Screenshots/recordings

1. Image when first time creating chart
image

2. Image after saving the chart and editing the x axis, y axis label
image

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Additional context

1. This issue happens inconsistently, where sometimes only the x-axis is removed and sometimes both are removed. 
2. Certain times, reloading the page fixes the issue. 

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### LINKED ISSUE #30370: X-Axis title disappears when editing bar chart
### Bug description

**Description**

When editing a bar chart in Superset, changing the X-axis title causes the title to disappear. Similarly, adjusting the margins leads to unexpected behavior—they either reset or are not applied correctly.

### How to reproduce the bug

    Open an existing bar chart in Superset or create a new one.
    Enter the edit mode for the chart.
    Change the X-axis title to a new value.
    Observe that the X-axis title disappears from the chart.
    Adjust the margin settings.
    Notice that the margins do not update as expected or revert to previous settings.

### Screenshots/recordings

[Screencast from 2024-09-24 10-57-58.webm](https://github.com/user-attachments/assets/67f392ae-9b4f-4eaa-a6d0-408fdadc2980)

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Firefox

### Additional context

_No response_

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [ ] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### PR DESCRIPTION
**Pull request by DamianPendrak**
### SUMMARY
Fixes #29877

Fixes #30370

The `createAxisTitleControl` and `createAxisControl` functions use the `visibility` prop to hide controls. This caused an issue where controls with duplicate names were stashed from the form data if one of them had `visibility` set to `false` and was rendered later than the visible one.

#### Solution
To resolve this, I introduced a new prop `disableStash`, to the `Control` component, which prevents stashing for the control where it is applied.
Additionally, I set the `resetOnHide` prop to `false` to prevent the axis titles from disappearing on the chart when changing the orientation.

#### Hidden prop bug
Initially, I considered replacing `visibility` with a `hidden` prop in the Bar chart controls. However, this approach led to issues with refreshing hidden control values and I decided to keep the `visibility` prop for a less invasive change.
While working with the `hidden` prop, I discovered a bug where `{...restProps}` overwrote the `hidden` prop's intended value, so `() => false` value was hiding the control. I plan to address this in a separate issue. The first commit reflects this initial approach, but I reverted it in the following commit to keep this PR focused on the `visibility` prop and `disableStash` solution.

#### Before
https://github.com/user-attachments/assets/79d349fd-d86d-4320-be88-9b74e3ce7e76

#### After
https://github.com/user-attachments/assets/51013344-3e61-474a-9795-312c8f5f51fa

### TESTING INSTRUCTIONS

1. Open an existing bar chart in Superset or create a new one.
2. Enter the edit mode for the chart.
3. Change the X-axis title and/or margin to a new value.
4. Switch between horizontal and vertical orientation and edit values again

### ADDITIONAL INFORMATION

- [x] Has associated issue: #29877 #30370
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by eschutho** [comment]
Thanks @DamianPendrak I'll set up a testing environment for us to take a look

**Review by geido — APPROVED** [review]

**Review by kgabryje — APPROVED** [review]
lgtm!

**Pull request merged**
