### PR TITLE
build(cypress): Use pull_request_target event to run cypress

### PR DESCRIPTION
**Pull request by robdiciuccio**
### SUMMARY
Updates Cypress e2e test Github Actions workflow to use the [pull_request_target event](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/) in order to work around the [secrets sharing limitation](https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets#using-encrypted-secrets-in-a-workflow) for forked repos. Also adds concurrency via multiple `containers`.

**NOTE**: the `pull_request` event trigger is required to get e2e tests passing in this PR, but will be removed in a subsequent PR in favor of `pull_request_target`.

Replaces https://github.com/apache/incubator-superset/pull/11730

### TEST PLAN
e2e test workflow should run with a populated `CYPRESS_RECORD_KEY` value from the upstream repo's secrets.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by robdiciuccio** [comment]
Cypress runs are not showing up in the Cypress dashboard for some reason.

**Comment by ktmud** [comment]
`push` run and `pull_request` run is different as `push` run tests the code on the branch, `pull_request` tests the code after merging with `master`. Normally this doesn't matter as most branches are up to date when the PR is created, but there is this difference so I just want to make sure we made a conscious decision here.

**Comment by robdiciuccio** [comment]
Thanks for the clarification @ktmud. The `pull_request` triggered workflow runs are reported on PRs, making it a bit confusing (and likely unknown) that `push` workflow runs are also running in the background. Though, the Cypress dashboard reports mainly `push` triggered runs, with an occasional `pull_request` event. Unclear why this is.

Another strange thing, `push`-based workflows seem to be [running concurrently](https://dashboard.cypress.io/projects/ukwxzo/runs/1945/specs), even though they should not(?) have access to secrets in the upstream repo.

**Comment by robdiciuccio** [comment]
Restoring `push` on all branches to test if concurrency works and if it's reported in the Cypress dashboard.

**Comment by robdiciuccio** [comment]
Confirmed: the `push` triggered tests [are run in parallel](https://dashboard.cypress.io/projects/ukwxzo/runs/1991/specs).

**Review by nytai — APPROVED** [review]

**Comment by ktmud** [comment]
I think the `pull_request` run (the one that is used in CI status reporting in PRs) still don't run in parallel, which means we probably have spun up two jobs unnecessarily.

It seems `pull_request_target` can only run in the background (like `push`) and can not be used to update CI status.

I'm wondering if we should just revert back to the `push` and `pull_request`, but 1). skip Container 2 and Container 3 if `CYPRESS_RECORD_KEY` is not accessible; 2) let committers know that if they create branches and make PRs from the `apache` repo, the CI will run faster.

**Comment by robdiciuccio** [comment]
@ktmud correct, the `pull_request` runs are not running in parallel because they don't have access to the record key. The goal here is to merge this PR, then open a subsequent PR to remove the `pull_request` event in favor of `pull_request_target`, which should have access to the record key. If this plan doesn't work, we can revert this and try a different approach.

**Comment by ktmud** [comment]
> @ktmud correct, the `pull_request` runs are not running in parallel because they don't have access to the record key. The goal here is to merge this PR, then open a subsequent PR to remove the `pull_request` event in favor of `pull_request_target`, which should have access to the record key. If this plan doesn't work, we can revert this and try a different approach.

Makes sense!

**Comment by robdiciuccio** [comment]
Here's how this worked in superset-ui: https://github.com/apache-superset/superset-ui/pull/853

**Review by ktmud — APPROVED** [review]

**Pull request merged**
