### PR TITLE
fix(native-filters): Show incompatible native filters indicator

### LINKED ISSUE #12568: [dashboard]native filter indicator incompatible section is missing
Dashboard filter indicator is supposed to have 3 filtering status sections(soon will be 4): ✅ Applied, ⚠️Incompatible, and Unset. see below
Screen Shot 2021-01-15 at 8 43 14 PM

Expected:
1. Show all 3 filtering status sections in the filter indicator
2. Two highlighted filters in below image and selected values should go under ⚠Incompatible as there are created using incompatible datasets  
Screen Shot 2021-01-15 at 8 40 46 PM

https://user-images.githubusercontent.com/67837651/104798749-b1295c00-5775-11eb-91fc-ef27635de042.mov

todo: 
1. bring incompatible section back to indicator 
2. send incompatible filter value to the the correct section - ⚠️incompatible

### PR DESCRIPTION
**Pull request by agatapst**
### SUMMARY

- The aim of this PR was to add **Incompatible** section to filter indicator. ⚠Incompatible filters are created using datasets & fields which are incompatible with a given chart.
- I have also added simple mocks for native filters: _mockStore_ and _mockNativeFilters_ to test displaying filter indicators for native filters.
- I have also slightly changed structure of Filter Badge tests in `FiltersBadge_spec.tsx` - I have divided them into _'for dashboard filters'_ and _'for native filters'_. Section _'for dashboard filters'_ is the same as on master, I have only added analogical tests for native filters.

Fixes #12568
Closes #12568 

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Before incompatible section for native filters was missing.
Now different configurations:
**With some correct native filters applied and one incompatible:**
Zrzut ekranu 2021-01-22 o 15 02 38

**With trying to apply two incompatible native filters from two different datasets:**
Zrzut ekranu 2021-01-22 o 15 09 53

**With one dashboard filter applied and one incompatible native filter:**
Zrzut ekranu 2021-01-22 o 15 12 35

**With incompatible dashboard filters (without native filters):**
Zrzut ekranu 2021-01-22 o 15 23 49

### TEST PLAN
Enable native filters: go to `config.py` and set `"DASHBOARD_NATIVE_FILTERS": True,`
Go to dashboards and create native filters. One one them should be created with incompatible dataset, which cannot be applied to this dashboard.

### ADDITIONAL INFORMATION

- [x] Has associated issue: #12568
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

cc @junlincc @rusackas @villebro @suddjian 
@adam-stasiak could you test?

### CODE REVIEW

**Comment by adam-stasiak** [comment]
Scenario:
Set 3 native filters (1 valid for this dashboard)
Enable all filters
Apply change
Check chart filters
Disable one of incorrect native filters and apply change

Observed: I see disabled filter in section Incompatible Filters 
Expected: I would see this filter under Unset section.

https://user-images.githubusercontent.com/25153919/105514912-568f8300-5cd4-11eb-9224-480f209e61ba.mov

**Review by suddjian — APPROVED** [review]
Code LGTM, nice

**Comment by adam-stasiak** [comment]
Retested again and consulted with Agata. It looks like my issue was caused by performance on my machine (on video you can see how long everything takes). 
I double checked that after computer restart and saw that it was for a moment in yellow zone without value but after a second it was moved to unset 🆗 . 

So no issue there.

**Comment by suddjian** [comment]
Oh apologies Adam, I didn't see your comment when I left my review. Glad it's working!

**Comment by junlincc** [comment]
LGTM, thank you for fixing it! ♥️ @agatapst  we are very close to demo-able stage.

**Review by graceguo-supercat — APPROVED** [review]
LGTM

**Pull request merged**
