### PR TITLE
chore: upgrading cypress to version 9

### PR DESCRIPTION
**Pull request by sadpandajoe**
### SUMMARY

Upgrading cypress to the latest version following their (migration guide)[https://docs.cypress.io/guides/references/migration-guide#Migrating-from-cypress-file-upload-to-selectFile].
- Bumping version to 9
- Removing flag `--headless` as it's default with Cypress 8
- No other test updates are required as part of the migration

Here is the [change log](https://cypress.io/whats-new/) of all the changes made.

### TESTING INSTRUCTIONS

- Run all tests to ensure they are passing

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by zhaoyongjie** [comment]
@sadpandajoe Could you rebase the latest master to your branch? Thanks!

**Comment by sadpandajoe** [comment]
@zhaoyongjie done.

**Comment by zhaoyongjie** [comment]
@sadpandajoe, thanks!
The CI is brocked by an npm compatible error. I think we just need to remove the `engines` declaration to fix it.

```
diff --git a/superset-frontend/tools/eslint-plugin-translation-vars/package.json b/superset-frontend/tools/eslint-plugin-translation-vars/package.json
index d4353a88d..83e8c184d 100644
--- a/superset-frontend/tools/eslint-plugin-translation-vars/package.json
+++ b/superset-frontend/tools/eslint-plugin-translation-vars/package.json
@@ -12,9 +12,5 @@
   "dependencies": {},
   "peerDependencies": {
     "eslint": ">=0.8.0"
-  },
-  "engines": {
-    "node": "^16.9.1",
-    "npm": "^7.5.4"
   }
 }
```

**Comment by sadpandajoe** [comment]
@zhaoyongjie this was added by @stephenLYZ in this PR: https://github.com/apache/superset/pull/19828/files. I want to confirm that it's ok with them before editing that file as I don't want to break other things.

**Comment by zhaoyongjie** [comment]
@stephenLYZ Could you confirm that this modification is safe?

**Comment by sadpandajoe** [comment]
closing for now

**Comment by rusackas** [comment]
@sadpandajoe looks like you intended to close this. I'll do ya the favor, but please feel free to reopen if warranted.

**Pull request closed without merging**
