### PR TITLE
feat: import/export dashboards via cli 

### LINKED ISSUE #5821: Allow import and export dashboards and charts by CLI
### Superset version
On master branch

### Description of the new feature
I think that it's a great idea allow to superset the possibility to import and export dashboards and charts by means of the command line interface (CLI). It's similar to the feature to import and export the datasources by means of the CLI .Thanks !

### PR DESCRIPTION
**Pull request by arpit-agarwal**
This PR will add back changes of #5991 that were reverted by #6035. This PR will close #5821

The travis configuration changes resolved the postgres test stuck issue

@graceguo-supercat  We can attach details of travis change as well for future reference.

### CODE REVIEW

**Comment by kristw** [comment]
@arpit-agarwal Is this rebased on top of current master?

**Comment by arpit-agarwal** [comment]
@kristw  Yes

However I see it is behind by 1 commit now due to latest commit of @graceguo-supercat .

**Comment by arpit-agarwal** [comment]
@graceguo-supercat / @kristw 

I am not sure why this is failing for postgres when exactly same test works for other db.

I think it is best to mock the db operations in this test as this code is written on top of existing functionality that is well tested.

I am removing tests for now and will raise a new PR with only tests.

let me know what you guys think?

**Comment by graceguo-supercat** [comment]
here is failed build, just for reference in the future:
https://travis-ci.org/apache/incubator-superset/jobs/439235984

if you follow the stack trace, it goes from `assert_dash_equals` => compare slice one by one => viz_type not match. Before we compare slices one by one, we sort slice by name. But i hit into some case that a slice doesn't have a name, so handle it as ''. Is it possible that you hit into cases that multiple slices don't have name, and cause slice comparison failed?

**Review by graceguo-supercat — APPROVED** [review]
LGTM

**Comment by arpit-agarwal** [comment]
Thanks @graceguo-supercat .
I am doing comparisons by id to avoid the confliclt.
I am exporting the dashboards already present in db so they should ideally match.

I am not sure why they will differ unless some other parallel execution modif the slices transitively
I will investigate further and raise the PR.

**Comment by HimanshuArora1234** [comment]
Hello Just wanted to know if this feature has already been released ? if so then in which version of superset ? Thanks a lot. Keep doing the great work :)

Cheers,
Himanshu

**Comment by arpit-agarwal** [comment]
This is released in 0.28

**Comment by arslanselcuk** [comment]
Hi everyone , 

I need exported dashboards to be imported to another environment from command line to deploy dashboards on DTAP street.

Is it possible to see an implementation of this feature? Somehow I could not find it, or maybe I could not understand how to use it.
Regards.

**Comment by ITNoesis** [comment]
Hello All,
Can someone give me an example of how to export and import a dashboard via commandline?

**Comment by ITNoesis** [comment]
> Hello All,
> Can someone give me an example of how to export and import a dashboard via commandline?

Guess I am answering my own question:

Export dashboards from containerized install of SuperSet:
===============================
-- Login to docker container running superset app:
docker exec -it --user=<username> superset_app bash

-- Export dashboards:
$pwd
/app
$superset export_dashboards -f <filename and path>
--Example:
$superset export_dashboards -f /app/test_exportdashboards.json

-- Copy the dashboard to localhost
docker cp superset_app:/app/test_exportdashboards.json /devtools/superset/dashboards
===============================

This however, will download all the dashboards and I did not see an option to download a specific one. 
The only available options are:

/app$ superset export-dashboards --help
Loaded your LOCAL configuration at [/app/pythonpath/superset_config.py]
INFO:superset.utils.logging_configurator:logging was configured successfully
/usr/local/lib/python3.6/site-packages/flask_caching/__init__.py:189: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
  "Flask-Caching: CACHE_TYPE is set to null, "
Usage: superset export-dashboards [OPTIONS]

  Export dashboards to JSON

**Options:
  -f, --dashboard-file TEXT  Specify the the file to export to
  -p, --print_stdout         Print JSON to stdout
  --help                     Show this message and exit.**

**Pull request merged**
