### PR TITLE
fix(frontend): allow "constructor" property in response data

### LINKED ISSUE #23953: "Object contains forbidden constructor property" error when using specific word
If I understand it correctly, if a reserved word `constructor` is used somewhere in returned data, there is a rendering error, both in charts and in the SQL lab. Quite a funny bug if so :)

#### How to reproduce the bug

1. Go to 'SQL Lab'
2. Run a query that returns a string containing `constructor`. It can be a select from a table or even a simple select of a static string: `select 'constructor'`

Or, alternatively, create a table containing `constructor` word in one of the fields, and build a chart from this table that actually shows the `constructor` word in group by, bar name, column name, etc.

### Expected results

The query in SQL Lab will not fail, and the chart will render.

### Actual results

You got error `Object contains forbidden constructor property`

#### Screenshots
image
image

### Environment

- browser type and version: `Chrome 112.0.5615.138`
- superset version: `2.1.0` - SQL Lab error reproduces in 1.5.3, but charts with `constructor` work in 1.5.3 and don't work in 2.1.0
- python version: `3.8`
- node.js version: `N/A`
- any feature flags active: None

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

I have searched for similar issue, but found only this that can be related: https://github.com/apache/superset/issues/22778

### PR DESCRIPTION
**Pull request by SpencerTorres**
### SUMMARY

Fixes #23953

Allows response JSON to be parsed with a property containing the name "`constructor`".
The `json-bigint` module has some safety options in place to prevent prototype pollution, but it prevents the queries from loading data where the columns contain `constructor` in the name/value. For example, `test_constructor` and `constructor` would both throw an error. 

### TESTING INSTRUCTIONS

See #23953 for example query

### ADDITIONAL INFORMATION

- [x] Has associated issue: Fixes #23953
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by rusackas** [comment]
Thanks for the rebase @SpencerTorres :) Running CI now and added a few reviewers. Hopefully we can get this across the finish line and close out the issue!

**Comment by SpencerTorres** [comment]
looks like CI was broken on master when I pulled. Updated again

**Comment by SpencerTorres** [comment]
Looks like master is consistently failing to run, however I did fix a new one-line lint issue related to test code added in this commit. Updated *again*

**Comment by rusackas** [comment]
CI running... fingers crossed!

**Comment by rusackas** [comment]
Looks like CI is happy now! Re-pinging @betodealmeida @john-bodley @villebro to see if they have a moment to help with a review.

**Review by villebro — APPROVED** [review]
LGTM, an interesting issue, thanks for the fix and great tests! TIL

**Comment by villebro** [comment]
@SpencerTorres would you be able to rebase the PR? The mandatory CI workflows have changed since CI last run, causing a few of them to now be missing.

**Comment by rusackas** [comment]
kicking off CI. Fingers crossed!

**Pull request merged**
