### PR TITLE
Fix flaky unit test - remove 'Markup' object in data

### PR DESCRIPTION
**Pull request by mistercrunch**
example of the failed test
https://travis-ci.org/apache/incubator-superset/jobs/397891630

@williaster

### CODE REVIEW

**Comment by williaster** [comment]
@mistercrunch thanks for looking into this!

for the frontend modifications, are existing slices guaranteed to not have markup?

**Review by graceguo-supercat — APPROVED** [review]
LGTM

**Comment by graceguo-supercat** [comment]
I like this code change, simplify `modified` attribute. But I am not sure this will resolve unit test issue.

**Comment by williaster** [comment]
I agree, good change but I think the real problem is that tests modify the db, and tests all share the same db.

cc @john-bodley

**Comment by mistercrunch** [comment]
Went with @graceguo-supercat 's solution as far as fixing the tests go, but I feel like this cleans the regexes and we should get it through.

**Pull request merged**
