### PR TITLE
[Feature] Copy-to-clipboard button in View Query

### PR DESCRIPTION
**Pull request by Mogball**
Adds a button that copies the query string:

screen shot 2017-10-02 at 4 39 58 pm

### CODE REVIEW

**Comment by mistercrunch** [comment]
We already have some component for this. I'd rather be consistent and always our component, or always use `react-copy-to-clipboard` . Not 2 different ways to do the same thing...

https://github.com/apache/incubator-superset/blob/master/superset/assets/javascripts/components/CopyToClipboard.jsx

**Comment by Mogball** [comment]
I modified the existing `CopyToClipboard` component a bit to make it more robust (wasn't previously working when a modal was open)

**Comment by mistercrunch** [comment]
killingit

**Comment by john-bodley** [comment]
@mistercrunch @Mogball regrettably it seems the change to `copyToClipboard` causes an undesirable behavior of including a newline in the copied value. This surfaced when someone copying and pasting a slice shortcut, 
screen shot 2017-11-21 at 1 22 24 pm
which gets pasted as (note the empty line):
```

http://0.0.0.0:8088/r/9
```

**Comment by Mogball** [comment]
@john-bodley can you make an issue for this and link this PR? Easier to navigate to than digging up a closed PR

**Pull request merged**
