### PR TITLE
feat(chart-data-api): download multiple csvs as zip

### LINKED ISSUE #17960: exported csv file from Mixed Time-Series chart only contains one series
2 series in chart, only the first serie can be exported

### PR DESCRIPTION
**Pull request by villebro**
### SUMMARY
For charts that request more than one query, only the first result can be downloaded as CSV. This PR does the following:
- When downloading a CSV, return a CSV file if there is only one result (current behavior), but return all results bundled in a ZIP file if there are more than one results. Also add a unit test to ensure that requesting a multi-query `QueryContext` returns a zip with the expected contents
- If user tries to request CSV for a `QueryContext` with an empty `queries` property, return a 400. Also add a unit test for this case.
- Add assertion for the `mimetype` to the pre-existing single result CSV integration test
- Add assertion for the `mimetype` to the pre-existing JSON download integration test

### TESTING INSTRUCTIONS
1. Create a Mixed Timeseries chart
2. Click the "Export to .CSV format" button
3. Verify that the downloaded ZIP file includes two CSVs with the correct contents

### ADDITIONAL INFORMATION

- [x] Has associated issue: closes #17960
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by geido — APPROVED** [review]
LGTM!

**Comment by kgabryje** [comment]
When I use only 1 metric for a query, metric's name is not present in the csv
image

However, when I use more than 1 metric, I can see the metric names.
image

Is that intended behaviour?

**Review by kgabryje — APPROVED** [review]
Left a small comment, but since that behaviour wasn't introduced by this PR, LGTM!

**Comment by srinify** [comment]
Looks good, just tested! Approving :]

**Pull request merged**
