### PR TITLE
added text wrapper function to bignumber.js subheader

### PR DESCRIPTION
**Pull request by avrilpearl**
- Added a text wrapper function to bignumber.js (wrapper function based off of the example [Wrapping Long Labels](https://bl.ocks.org/mbostock/7555321))
- Partial fix for issue [#2224](https://github.com/apache/incubator-superset/issues/2224)
- Call this function on the subheaderer text so that a new line is
created if the subheader is wider than the width of the slice:
screen shot 2017-09-11 at 11 26 34 am

### CODE REVIEW

**Comment by xrmx** [comment]
It looks to me there's a ton of changes not related to this particular change.

**Comment by avrilpearl** [comment]
@xrmx removed the changes to backendSync.json, now only changes are related to the bignumber viz and the wrapping of the subheader.

**Comment by slarrain** [comment]
Whats the state of this PR @xrmx ? It looks like is ready to be merged, or not yet?

**Comment by xrmx** [comment]
@slarrain it's ready to be reviewed

**Comment by cmajel** [comment]
@xrmx do you have an update on this? this would be a super useful fix.

**Pull request closed without merging**
