### PR TITLE
feat: custom content in alert and reports

### PR DESCRIPTION
**Pull request by mayurnewase**
### SUMMARY

Add text editor in alert/report modal to add custom html content for email and markdown content for slack reports.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

Before
image

After
image

### New Dependencies
New dependency on `https://github.com/jpuri/react-draft-wysiwyg` for editor

### TESTING INSTRUCTIONS

Enable ALERTS_REPORTS feature flag
Set report for any chart/dashboard
Check received report -> should have custom body set in above step.

### TODO
- [ ] Update all other delivery methods to use custom content.
- [ ] Migration to add new column in table with `<a href="{chart_explore_url}">Explore in Superset</a>` link for existing reports.
- [ ] Update existing tests and add new for this feature.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by yousoph** [comment]
hi @mayurnewase ! 

The current description already gets sent in the body of the alert or report, so the message body field may be redundant. 
What types of content are you looking to include in your alerts/reports?

**Comment by gkachru** [comment]
hi @yousoph 

I haven't worked on this pull request, but I would like to see this feature added as well. My use case is to add multiple call-to-actions for other systems (like Approve or Create Task etc) for people who may not have access to superset but may need to act on the information provided.

**Comment by mayurnewase** [comment]
I thought the simple text in description field wasn't enough to send descriptive reports, so wanted to add text editor for html and markdown for different delivery methods.
After above comments looks like there is some interest for it, so I might complete this feature over weekend and mark ready for review.

**Comment by chetank81** [comment]
@mayurnewase, @yousoph & @betodealmeida : When do we think we will have this feature avaiable in main branch? Very important feature for folks who wish to use superset as audit report tool in organization.

**Pull request closed without merging**
