### PR TITLE
Fix update ids in dashboard metadata on import

### PR DESCRIPTION
**Pull request by smacker**
### CATEGORY

Choose one

- [x] Bug Fix
- [ ] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY

Add update for ids of following fields in the json:

- `filter_immune_slice_fields`
- `default_filters`

Add test for correct update of `timed_refresh_immune_slices`.

### TEST PLAN

1. Export dashboard with `default_filters`.
2. Import it using master -> dashboard is broken
3. Import it using code from this PR -> dashboard works correctly

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### REVIEWERS

@mistercrunch

### CODE REVIEW

**Comment by smacker** [comment]
I'm not sure why cypress test has failed:
```
CypressError: Timed out retrying: Expected to find element: '.SouthPane .ReactVirtualized__Table', but never found it.
```

The PR should not change anything related to SQLlab UI.

**Comment by villebro** [comment]
This is probably just the unreliable js test acting up. I restarted it, should be ok.

**Comment by smacker** [comment]
Still failing. I tried to run it locally and everything passed correctly:
```
(venv) smacker in ~/Work/incubator-superset on fix_ids_in_dash_metadata_import [!]
$ TOXENV=cypress-sqllab tox
...
  cypress-sqllab: commands succeeded
  congratulations :)
```

**Comment by etr2460** [comment]
I just restarted the test again. If you need to manually restart CI, closing and reopening the PR should do it too.

**Comment by mistercrunch** [comment]
This LGTM generally, I'm thinking we need uuids longer term to make things like this easier.

**Comment by amitmiran137** [comment]
closing due to inactivity

**Pull request closed without merging**
