### PR TITLE
chore(build): remove extraneous prettier step in superset-frontend CI

### PR DESCRIPTION
**Pull request by hainenber**
chore(build): remove extraneous prettier step in superset-frontend CI

### SUMMARY

I noticed there are duplicate CI steps in `superset-frontend` and `pre-commit` jobs. Since `pre-commit` job is ran regardless of all changes, I think it's better to remove the duplication in `superset-frontend`.

Unless there are missing historical contexts I'm not aware of ...

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

N/A

### TESTING INSTRUCTIONS

N/A

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by mistercrunch — APPROVED** [review]
Thanks for the contribution!

**Comment by mistercrunch** [comment]
Looks like we may be able to drop the task in `.github/workflows/superset-websocket.yml` as well since I think it's covered by the [pre-commit](https://github.com/apache/superset/blob/master/.pre-commit-config.yaml#L58-L65) checks (?)

**Comment by hainenber** [comment]
Prettier task in `supserset-websocket.yml` isn't duplicate of the one removed and the pre-commit check though. They're different in their working directories 🤓 

-  Prettier in `pre-commit` and `superset-frontend` CI
image
image


- Prettier in `superset-websocket.yml`
image

**Comment by mistercrunch** [comment]
Yes I notice the setup isn't identical but I think it's effectively the same. Let's merge this as a net positive and can revisit this other potential duplication later one.

**Pull request merged**
