### PR TITLE
Excel support

### PR DESCRIPTION
**Pull request by blcksrx**
### CATEGORY

Choose one

- [ ] Bug Fix
- [x] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY

Adding excel(xslx) support to export from sql_lab and explore

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Before:
Screenshot from 2019-05-06 12-56-39
Screenshot from 2019-05-06 12-59-41

After:
Screenshot from 2019-05-06 12-51-56
Screenshot from 2019-05-06 12-52-25

### ADDITIONAL INFORMATION

- [x] Has associated issue: #7430
- [x] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [x] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by kakoni** [comment]
Hi! This is pretty useful feature, any specific reason why it became stale?

**Comment by kakoni** [comment]
@blcksrx I've updated this original request so that it works with the current master branch. However I (obviosly) cannot reopen this original pull request. Any thoughts, how to proceed?

**Comment by blcksrx** [comment]
@kakoni I can't reopen it.I will create another PR for that

**Comment by villebro** [comment]
@blcksrx please do, I'll be happy to review this.

**Comment by blcksrx** [comment]
@villebro I'm going to do it now!

**Pull request closed without merging**
