### PR TITLE
Add Iran to Country Visualization

### PR DESCRIPTION
**Pull request by ali-behjati**
- [x] Enhancement (new features, refinement)

This PR Requires [This superset-ui-plugins PR](https://github.com/apache-superset/superset-ui-plugins/pull/306) to be merged first.

### CODE REVIEW

**Comment by robdiciuccio** [comment]
It looks like many countries are missing from this list. Would you mind adding all of the missing countries?

**Comment by nytai** [comment]
@robdiciuccio looks like this has a corresponding pr https://github.com/apache-superset/superset-ui-plugins/pull/306 that includes the geojson file for this country. Adding _all_ the missing countries may be a significant amount of work

**Comment by ali-bahjati** [comment]
My PR in superset-ui is merged now. I think you can merge this. I don't know should I increase superset-ui-plugins package version or no.

**Comment by ali-bahjati** [comment]
@mistercrunch Is it ok to merge?

**Comment by ali-bahjati** [comment]
Any comments on this PR?

**Comment by villebro** [comment]
@ali-bahjati can you rebase? There's a conflict on `controls.jsx` that's blocking merging

**Comment by ali-bahjati** [comment]
@villebro Done.

**Comment by villebro** [comment]
Thanks @ali-bahjati !

**Pull request merged**
