### PR TITLE
feat: have user go to explore after dataset creation

### PR DESCRIPTION
**Pull request by pkdotson**
### SUMMARY
This pr creates a new flow from the dataset modal where after user creates a datasource it directs them to the explore page.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

after

https://user-images.githubusercontent.com/17326228/167704197-d7167d42-31bd-4e72-bebb-3e647139dae6.mov

### TESTING INSTRUCTIONS
Go to create dataset and save. It should direct you to explore page.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by AAfghahi — APPROVED** [review]

**Comment by yousoph** [comment]
Two things I noticed: 

1. In the add chart flow, the dataset in the dropdown isn't styled the same way as if you had selected the dataset manually
image

2. I think it would be smoother to bring the user directly to the create chart flow without the user seeing the dataset CRUD view in between, if we can do that. The dataset created confirmation toast could appear on the create chart page (instead of on the CRUD view) 

cc @jess-dillard if you want to test on the ephemeral & for feedback on point 2

**Comment by jess-dillard** [comment]
Agreed with @yousoph, let's make those changes.

**Pull request merged**
