### PR TITLE
feat(homescreen and cards): Toggle thumbnails off or on and feature flag

### PR DESCRIPTION
**Pull request by pkdotson**
### SUMMARY
This pr adds toggle for thumbnails within cards on homescreen and on chart/dashboard listviews and renders the toggle depending if feature flags is enabled.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
WITH FEATURE FLAG OFF:
Screen Shot 2021-03-17 at 6 52 00 PM

WITH FEATURE FLAG ON:

https://user-images.githubusercontent.com/67837651/111695927-ddeb0580-87f0-11eb-8448-e7ef9bf00235.mov

### TEST PLAN
**to test toggle btn you must set the thumbnails feature flag to true**
unit test will be updated to reflect new toggle btn.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [X ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by graceguo-supercat** [comment]
@pkdotson Thanks for the feature! In the PR description, could you explain which feature flag to use, and how to use it?

**Comment by junlincc** [comment]
thanks for the PR, @pkdotson I think we have make this feature available to general, what's the requirement for removing the FF?

**Review by junlincc — COMMENTED** [review]
Screen Shot 2021-03-18 at 2 08 23 PM
is there a way to remove the save query card as well? @pkdotson

**Comment by pkdotson** [comment]
> Screen Shot 2021-03-18 at 2 08 23 PM
> 
> is there a way to remove the save query card as well? @pkdotson
Yep its add and ready to go @junlincc

**Review by junlin-qa — APPROVED** [review]
good to go. 🟢 

-jc

**Comment by junlincc** [comment]
@pkdotson please get the tests passed.

**Review by hughhhh — APPROVED** [review]

**Pull request merged**
