### PR TITLE
fix: Removing parent filter causes incorrect state of child filter

### LINKED ISSUE #16825: [native filter] Remove parent filter cause incorrect state of child filter
### Expected results

Remove parent filter should update all its children filters to top level filters.

#### How to reproduce the bug

1. create dashboard from baby_names dataset.  Add a few filters. For example, add Gender filter, State filter, Number filter, and set number filter's parent filter is State filter.
2. Load dashboard.
3. Remove State filter.
4. In dashboard filter bar, you don't see State filter or Number filter. But number filter is still in dashboard's metadata, and it also shows in Filter Sets:
```
    {
      "id": "NATIVE_FILTER-1VxgvI-iF",
      "controlValues": {
        "multiSelect": true,
        "enableEmptyFilter": false,
        "defaultToFirstItem": false,
        "inverseSelection": false,
        "searchAllOptions": false
      },
      "name": "Number Filter",
      "filterType": "filter_select",
      "targets": [{"datasetId": 2, "column": {"name": "num"}}],
      "defaultDataMask": {
        "extraFormData": {},
        "filterState": {},
        "ownState": {}
      },
      "cascadeParentIds": ["NATIVE_FILTER-wvlKEa4U5"],
      "scope": {"rootPath": ["ROOT_ID"], "excluded": []},
      "chartsInScope": [133],
      "tabsInScope": []
    }
```

Screen Shot 2021-09-23 at 7 04 53 PM

Screen Shot 2021-09-23 at 7 04 40 PM

### Environment

latest master

### Additional context

cc @m-ajay @michael-s-molina @junlincc

### PR DESCRIPTION
**Pull request by michael-s-molina**
### SUMMARY
Fixes https://github.com/apache/superset/issues/16825

It also fixes another issue where the advanced section was being collapsed when a user unchecked all the options.

@junlincc @jinghua-qa It would be great to have your approval.

### AFTER SCREENSHOTS OR ANIMATED GIF
https://user-images.githubusercontent.com/70410625/135140558-2a0415a9-4def-42b5-980c-6fa38d68dcb3.mov

### TESTING INSTRUCTIONS
Check the original issue for instructions.

### ADDITIONAL INFORMATION
- [x] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by villebro — APPROVED** [review]
Thanks for fixing this + making the code much more readable 👍

**Comment by geido** [comment]
/testenv up FEATURE_DASHBOARD_NATIVE_FILTERS=true FEATURE_DASHBOARD_CROSS_FILTERS=true FEATURE_DASHBOARD_NATIVE_FILTERS_SET=true FEATURE_DASHBOARD_FILTERS_EXPERIMENTAL=true

**Comment by geido** [comment]
Hi @michael-s-molina. I found a problem with deleting and undoing a deletion on the fly without saving. As you can see in the video the child filter won't show as hierarchical after the parent filter has been removed and then added back again.

https://user-images.githubusercontent.com/60598000/135246287-0c1afaad-a961-439d-9f66-1b24a1c46373.mp4

**Comment by michael-s-molina** [comment]
> Hi @michael-s-molina. I found a problem with deleting and undoing a deletion on the fly without saving. As you can see in the video the child filter won't show as hierarchical after the parent filter has been removed and then added back again.
> 
>  Video.Game.Sales.1.mp4

@geido I noticed that in my tests. It's related to the form `preserve={false}`.  I didn't change it because it's a minor problem and I know that you're investigating the `preserve={false}` in the undo PR follow-up so I preferred to wait for your conclusions. If in the end, you remove the `preserve={false}`, this bug will be fixed. If not, I can fix it in a follow-up using a different strategy.

**Comment by geido** [comment]
> > Hi @michael-s-molina. I found a problem with deleting and undoing a deletion on the fly without saving. As you can see in the video the child filter won't show as hierarchical after the parent filter has been removed and then added back again.
> > Video.Game.Sales.1.mp4
> 
> @geido I noticed that in my tests. It's related to the form `preserve={false}`. I didn't change it because it's a minor problem and I know that you're investigating the `preserve={false}` in the undo PR follow-up so I preferred to wait for your conclusions. If in the end, if you remove the `preserve={false}`, this bug will be fixed. If not, I can fix it in a follow-up using a different strategy.

I was able to reproduce the correct behavior on master. It appears that the hierarchical setting is properly restored when undoing.

https://user-images.githubusercontent.com/60598000/135252580-150b3a65-c54c-40bb-8019-104564c87733.mp4

**Comment by michael-s-molina** [comment]
@geido I changed the strategy to present "(deleted)" when a parent is removed. This works for saved and non-saved filters.

https://user-images.githubusercontent.com/70410625/135289736-439da6d1-7284-4f04-9e6d-5e6849f84fa6.mov

**Review by geido — APPROVED** [review]
LGTM! Thanks for the fix!

**Pull request merged**
