### PR TITLE
Portuguese Translation

### PR DESCRIPTION
**Pull request by nunohelibeires**
complete.

my contribution to superset, with the help of @jcoelho-pt

### CODE REVIEW

**Comment by xrmx** [comment]
Are you sure portuguese is ptpt and not just pt or pt_PT?

**Comment by xrmx** [comment]
Also you are missing the messages.json for the frontend

**Comment by nunohelibeires** [comment]
@xrmx honestly it should be just pt but as I noticed there was a ptbr version, I changed to ptpt.

added the missing json file

**Comment by xrmx** [comment]
You added the messages.json to pt_br and please rename the ptpt dir to pt with git mv

**Comment by xrmx** [comment]
You have to rebase on upstream master not merge it.

**Comment by nunohelibeires** [comment]
@xrmx yes, I messed up sorry about that.

I think it is best to close the pr and submit the translation later on

**Comment by xrmx** [comment]
@nunohelibeires whatever works for you, if you open a new PR please work a branch and not on your master to avoid this kind of issues.

**Comment by mistercrunch** [comment]
Please reopen with clean set of commits

**Comment by mzangie** [comment]
Hm

**Pull request closed without merging**
