### PR TITLE
fix: Dataset Fuzzy search issue on creating a new chart.

### PR DESCRIPTION
**Pull request by codemaster08240328**
### SUMMARY

Dataset Fuzzy search in "Create a new Chart" UI isn't searching all available datasets when there are more than 100 datasets.

[ISSUE](https://github.com/apache/superset/issues/18034)

### CODE REVIEW

**Comment by michael-s-molina** [comment]
@codemaster08240328 Thanks for looking into this. We can't fix this problem using `fetchOnlyOnSearch` because we intend to keep the behavior of opening a Select and scrolling through its options without typing anything. To fix this we need to investigate why that particular text was not retrieved from the server-side. If instead of setting `fetchOnlyOnSearch` you simulate a page size smaller than the total results like pageSize={10} you can see the requests fired to the server with the typed text. The only case where we won't fire a request to the server is if all the options are already loaded on the client-side.

**Review by michael-s-molina — CHANGES_REQUESTED** [review]
@codemaster08240328 Thanks for looking into this. We can't fix this problem using `fetchOnlyOnSearch` because we intend to keep the behavior of opening a Select and scrolling through its options without typing anything. To fix this we need to investigate why that particular text was not retrieved from the server-side. If instead of setting `fetchOnlyOnSearch` you simulate a page size smaller than the total results like `pageSize={10}` you can see the requests fired to the server with the typed text. The only case where we won't fire a request to the server is if all the options are already loaded on the client-side.

**Comment by rusackas** [comment]
FWIW, it looks like we lost some of the PR template in the description, but you can add "Fixes: #xyz" in a PR description to automatically close the issue when a PR merges.

**Comment by rusackas** [comment]
We believe this one is taken care of by happenstance/nature.... we can re-open this if the Issue/ticket reopens.

**Pull request closed without merging**
