### PR TITLE
fix: Dataset duplication fatal error

### LINKED ISSUE #21281: Error when duplicating virtual dataset
Getting an error when trying to duplicate a virtual dataset (feature in this PR: https://github.com/apache/superset/pull/20309)
#### How to reproduce the bug

1. Visit the Datasets page
2. On the Actions column of a Virtual dataset, click the duplicate icon 
3. Enter a dataset name and click "Duplicate" 

### Expected results
Virtual dataset gets copied and created successfully

### Actual results
An error message appears and the dataset doesn't get created 

#### Screenshots
Superset 2022-08-31 15-10-11

### Environment

(please complete the following information):

- browser type and version:
- superset version: `master`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by reesercollins**
### SUMMARY
Minor fix for dataset duplication.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
image

image

### TESTING INSTRUCTIONS
Try duplicating a dataset. It should work now.

### ADDITIONAL INFORMATION

- [x] Has associated issue: Fixes #21281 
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by EugeneTorap** [comment]
@michael-s-molina @lyndsiWilliams ^^

**Review by eschutho — APPROVED** [review]
Thanks @reesercollins!

**Comment by sadpandajoe** [comment]
LGTM

**Comment by EugeneTorap** [comment]
@eschutho Can you update the description and write 'Fix #21281' to auto close the GitHub issue?

**Pull request merged**
