### PR TITLE
fix: allow CSV upload in Other db

### PR DESCRIPTION
**Pull request by betodealmeida**
### SUMMARY

The "Other" database should have CSV uploads showing up as an option.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

Before:

Screenshot 2023-01-20 at 11-34-31 Superset

After:

Screenshot 2023-01-20 at 12-51-10 Superset

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by rusackas** [comment]
Relates to the documentation request in https://github.com/apache/superset/issues/19247

**Comment by rusackas** [comment]
Should there be any sort of tooltip/warning, to explain that not all database types _actually_ support this?

**Review by codyml — APPROVED** [review]
LGTM!  +1 on @rusackas's note too.

**Comment by betodealmeida** [comment]
> Should there be any sort of tooltip/warning, to explain that not all database types _actually_ support this?

@yousoph should we ticket this?

**Pull request merged**
