### PR TITLE
replace missing round function in d3 to fix MapBox

### PR DESCRIPTION
**Pull request by aboganas**
This PR to fix issue #6279 as round function in d3 seems to be deprecated.

### CODE REVIEW

**Review by mistercrunch — CHANGES_REQUESTED** [review]
Please fix the build issues and write some unit tests for that new function.

**Comment by mistercrunch** [comment]
You can run `yarn run lint` from the `assets/` folder to lint the code locally

**Comment by aboganas** [comment]
> You can run `yarn run lint` from the `assets/` folder to lint the code locally
thanks for guiding me with my first PR of more to come

**Review by aboganas — COMMENTED** [review]
requested changes has been applied

**Review by mistercrunch — APPROVED** [review]

**Comment by mistercrunch** [comment]
bugs

**Pull request merged**
