### PR TITLE
fix: passing url params in sqllab

### LINKED ISSUE #13315: Unable to Use Jinja Context for "url_param"
### Expected results

It gives 'rangga' as the parameter of username in url

### Actual results

It returns None

#### Screenshots

image

#### How to reproduce the bug

0. Activate your jinja context in superset/docker/pythonpath_dev/superset_config.py by adding "ENABLE_TEMPLATE_PROCESSING" : True in dictionary of FEATURE_FLAGS
image

1. Go to sqllab
2. Edit your url and add '?username' argument
3. Reload the page
4. Write the query using jinja context of url_param and run the query

### Environment

(please complete the following information):

- superset version: 1.0.1 (docker version)
- python version: 3.7.9

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by maltoze**
### SUMMARY
Fixes: #13315

### BEFORE
image

### AFTER
image

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by egeste** [comment]
Bump

**Review by lisun — APPROVED** [review]

**Comment by egeste** [comment]
How can I help move this PR along?

**Comment by villebro** [comment]
Thanks so much for this fix @maltoze and sorry for it slipping through the cracks 🙁 I'll work on pushing this through now.

**Review by kgabryje — APPROVED** [review]
LGTM!

**Comment by egeste** [comment]
🎉 🎉 🎉 🎉

**Pull request merged**
