### PR TITLE
Feature: Implementing incremental search for a column values 

### PR DESCRIPTION
**Pull request by fabianmenges**
This is the current fitler UI.
currentfilter
It will pre populate all possible values. Up to a threshold, that can not be changed. If you data source contains more distinct possible values for you filter it won't load those. 

This MR contains the backend for incremental search. I'm happy to make the necessary changes to the front end as well.

Example:
Searching for "me" on the "name" column of the "birth_names" datasource limited to five return values will return: 
search_me
Searching for "mel" will return:
search_mel
The idea is that you make async calls to query for the possible filter values while the user is typing.

### CODE REVIEW

**Comment by xrmx** [comment]
A test would be fine :)

**Comment by fabianmenges** [comment]
Added a unit test for druid datasources...

**Comment by fabianmenges** [comment]
Updated the Unit test for SQL

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 222 days. Feel free to comment and request for this issue to be reopened.

**Pull request closed without merging**
