### PR TITLE
chore: more logging around cypress/codecov

### PR DESCRIPTION
**Pull request by mistercrunch**
Adding some more logging to see whether the curl or the codecov scripts
is the flaky step.

### CODE REVIEW

**Comment by ktmud** [comment]
Don't we need `endgroup`?

**Comment by mistercrunch** [comment]
oh what is `say`? I just assumed a fancier `echo` but now I tried it locally and my mac talked to me :/ 

try `say "hello world"` on mac os :)

**Comment by mistercrunch** [comment]
Had to lookup `say` and decided to move to simple `echo` here

**Comment by ktmud** [comment]
Yes, it's fancier `echo`: https://github.com/apache/incubator-superset/blob/c4be6cda1cd9e4bd1d9f23706d770d8de5488e03/.github/workflows/bashlib.sh#L27-L32

`@actions/cached-dependencies` allows bash commands to run parallel. `say` disabled echo for parallel mode so that `::group::` and `::endgroup::` doesn't intervene with each other.

**Pull request closed without merging**
