### PR TITLE
fix: Color consistency

### LINKED ISSUE #11677: [dashboard properties] metadata saving behavior on SAVE
ezgif-3-d5c8ef83fcf9

Actual Behavior:
To see changes made in JSON metadata in Dashboard Properties - Advanced, user needs to click `SAVE`in the modal, and `SAVE` in Dashboard, AND refresh... 

Expected Behavior 
like edits in other Basic Information fields, when users edit json metadata in Dashboard Properties - Advanced, they should be able to see changes by first `SAVE` after exiting the modal

ezgif-3-a758b432e0f9

### LINKED ISSUE #16891: [color theme] stacked bar chart with 'Superset color' theme will change color when save to dashboard
stacked bar chart with superset color theme will change color (within the same color theme) when save to dashboard

#### How to reproduce the bug

1. Go to a chart, pie chart or bar chart from example charts
2. Click on CUSTOMIZE panel and select 'Superset color theme'
3. Save the chart with superset color theme to dashboard

### Expected results
When save chart to dashboard, chart color did not change

### Actual results

When save chart to dashboard, chart color changed to other color within the same color theme

#### Screenshots

https://user-images.githubusercontent.com/81597121/135226103-a6b7ab5a-8010-4c4d-8103-886da3c67cdc.mov

### Environment

(please complete the following information):

- browser type and version: Chrome
- superset version: master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### LINKED ISSUE #16961: [color theme][dashboard] adding new chart to same dashboard change color of other charts
When user adding new chart to a dashboard, existing charts will change color

### How to reproduce the bug

1. Go to explore and make a new chart
2. Click on save to save the chart to a dashboard with existing charts
3. Observe color of existing charts after adding a new chart to the dashboard

### Expected results

Existing charts did not change color

### Actual results

Existing charts change color

### Screenshots
**Before add a new chart**
Screen Shot 2021-10-04 at 10 46 19 AM

**After add a new chart**
Screen Shot 2021-10-04 at 10 55 19 AM

### Environment

(please complete the following information):

- browser type and version: Chrome
- superset version: master
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### LINKED ISSUE #16970: [dashboard][color theme] chart color are changed when refreshing dashboard
chart color are changed when refreshing dashboard

#### How to reproduce the bug

1. Go to dashboard with multiple charts
2. Applied color theme to dashboard, for example supers color
2. Refresh dashboard
3. Observe color of each chart

### Expected results

Refresh dashboard did not change color of chart

### Actual results

Refresh dashboard did not change color of chart

#### Screenshots
https://user-images.githubusercontent.com/81597121/135937535-016cd613-cbf5-48a4-9849-7b0010a68176.mov

### Environment

(please complete the following information):

- browser type and version: Chrome
- superset version: master
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### LINKED ISSUE #16979: [color theme][chart] Series in the chart is starting in a random order of color
Series in chart is starting in a random order of color

#### How to reproduce the bug

1. Go to explore, make a gauge chart with multiple series
2. Click on color theme and observe the color number
3. See error

### Expected results

Series will follow the color order

### Actual results

Series seems appear in random color order

#### Screenshots

Gauge_d3_10

### Environment

(please complete the following information):

- browser type and version: Chrome
- superset version: master
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### LINKED ISSUE #16980: [color theme][chart] When #series is larger than #color, the color start from random order to repeat
When number of series is larger than number of color, the color start from random order to repeat

#### How to reproduce the bug
Use clean_sales_data
1. Go to explore, create mixed time series chart
2. Select 'month' in group by
3. Select a color theme of 10 (for example d3 category 10)

### Expected results

When #series > #color, the series start from 1st color then repeat 1st color

### Actual results

When #series > #color, the series start from random order then repeat 1st color

#### Screenshots

mixed_time_series_superset

### Environment

(please complete the following information):

- browser type and version: chrome
- superset version: master
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by geido**
### SUMMARY
This PR refactors the color scheme implementation and fixes the following issues:

Fixes: https://github.com/apache/superset/issues/11677
Fixes: https://github.com/apache/superset/issues/16970
Fixes: https://github.com/apache/superset/issues/16891
Fixes: https://github.com/apache/superset/issues/16961
Fixes: https://github.com/apache/superset/issues/16980
Fixes: https://github.com/apache/superset/issues/16979

It adds the ability to port custom label colors from the Dashboard to Explore.
It makes the custom label colors persistent and independent from the color scheme change in Dashboard.

### KNOWN ISSUES

There are several known issues related to the color consistency project currently affecting master which will be tackled in separate PRs, as follows:

- https://github.com/apache/superset/issues/17243
- https://github.com/apache/superset/issues/17244
- https://github.com/apache/superset/issues/17318
- Pie chart issue with the categorical color scheme using the same color for the last and first slices of the pie, making it hard to differentiate the two slices (will require deeper investigation)

### REQUIRED SUPERSET-UI PR

This PR requires the change in the related Superset-ui PR to be merged in first https://github.com/apache-superset/superset-ui/pull/1406

##### Change a color scheme in Explore. Then refresh.

https://user-images.githubusercontent.com/60598000/137151884-3b0d2713-e279-4c06-9aac-c6a3e3659a1b.mp4

##### The chart should use the colors in order and restart from the first color in the scheme when running out of available colors.

https://user-images.githubusercontent.com/60598000/137152219-09d92db1-70b6-4470-91b1-1565f9232d54.mp4

##### Chart should inherit the color scheme of the dashboard

https://user-images.githubusercontent.com/60598000/137152359-63879a43-788a-488c-a333-c5118957b1ef.mp4

##### Charts in the dashboard should use custom label color, show the change immediately, on save and on refresh

https://user-images.githubusercontent.com/60598000/137152699-a4860053-2905-4001-a07a-4bd323c47004.mp4

##### Explore should use the same color scheme and custom label colors of the originating dashboard

https://user-images.githubusercontent.com/60598000/137152790-b2ab8a80-869f-4fdc-866b-1e208c0e90d1.mp4

### TESTING INSTRUCTIONS
Please follow each test case as shown in the videos above

### ADDITIONAL INFORMATION

- [x] Has associated issue: https://github.com/apache/superset/issues/11677 https://github.com/apache/superset/issues/16970 https://github.com/apache/superset/issues/16891 https://github.com/apache/superset/issues/16961 https://github.com/apache/superset/issues/16980 https://github.com/apache/superset/issues/16979
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by michael-s-molina — COMMENTED** [review]
This PR is awesome. So many issues fixed 👏🏼 . 
The code looks good. Can we spin up a test env to get @jinghua-qa approval?

**Review by kgabryje — APPROVED** [review]
LGTM!

**Comment by sadpandajoe** [comment]
🏷️ 2021.44

**Pull request merged**
