### PR TITLE
feat(explore): Rearrange controls in most popular charts

### PR DESCRIPTION
**Pull request by kgabryje**
### SUMMARY
Rearrange controls in some of the most popular charts:
- Table
- Bar (nvd3)
- Echarts Timeseries (generic, line, area, bar, stepped, smooth line, scatter)
- Big number (total + trendline)
- World map
- Pivot table v2
Sections "Chart", "Time" and "Filter" are expanded, other sections are collapsed by default.

This is the first stage of changing order and names of controls in charts. Updates for the rest of the charts coming in the next couple of weeks!

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

https://user-images.githubusercontent.com/15073128/164293537-9954f6c0-b492-4579-b84d-704fa0b797c3.mov

### TESTING INSTRUCTIONS
Make sure that the charts listed in summary work like before

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

CC @kasiazjc @lauderbaugh

### CODE REVIEW

**Comment by villebro** [comment]
A few thoughts:
- I've probably raised this many times before, but I'll do it once more, just in case 😆  The title "Chart" (instead of "Query") could be seen as slightly ambiguous, as everything should affect the chart. While I know that "Query" isn't very business user friendly, maybe there's some other term out there that could convey more clearly what these controls are.
- I noticed that Mixed Timeseries isn't included in this PR. Could we update that one, too?

**Comment by kasiazjc** [comment]
> A few thoughts:
> 
> - I've probably raised this many times before, but I'll do it once more, just in case 😆  The title "Chart" (instead of "Query") could be seen as slightly ambiguous, as everything should affect the chart. While I know that "Query" isn't very business user friendly, maybe there's some other term out there that could convey more clearly what these controls are.
> 
> - I noticed that Mixed Timeseries isn't included in this PR. Could we update that one, too?

I think we were on the fence on how to name this section... Like "Required"/"Basic", but I don't think it makes sense 🫠 I think for now we can change the name to "query" and adjust later. This section will always be opened as there are all (I think in most cases) required controls, so shouldn't be a problem.

We included only Tier 1 charts, but I guess as Mixed Timerseries is similar we can tackle that one too, @kgabryje?

**Comment by kgabryje** [comment]
1. After a discussion with @villebro we decided to stick with "Chart" for now
2. As for Mixed Timeseries, that chart has a more complex control panel since we configure 2 queries - Query A and Query B. If we were to use the same pattern as in other charts in this PR, we'd have a structure `Query A, Filter A, Advanced query settings A, Query b, Filter B, Advanced query settings B` and that's not what we aim for. For that reason I'm going to leave it as it is for now and wait for design input. @kasiazjc

**Review by villebro — APPROVED** [review]
Code LGTM - probably good to get QA or product to sign off on this change?

**Comment by kgabryje** [comment]
@lauderbaugh As Ville pointed out, this change needs a product sign off. Can you take a look?

**Comment by stephenLYZ** [comment]
LGTM.

**Comment by kasiazjc** [comment]
Checked in testing env and it looks great! Thanks 🙏

**Comment by lauderbaugh** [comment]
Looks good!

**Comment by michael-s-molina** [comment]
@kgabryje Should we rebase this PR?

**Comment by michael-s-molina** [comment]
> @kgabryje Can you rebase the PR and possibly remove the `hold` label?

**Comment by rusackas** [comment]
Any idea how long this will be on hold? Wondering if it should just be converted to draft for safety, or even closed and re-opened if the day ever comes.

**Comment by kgabryje** [comment]
@rusackas Unfortunately this has been pushed far down the list of priorities :( I'm going to convert it to draft and hopefully we can get back to it in the future

**Pull request closed without merging**
