### PR TITLE
No exception on no data

### PR DESCRIPTION
**Pull request by betodealmeida**
When trying to replicate a bug I found out to the backend is raising exceptions when no data is returned, both in Druid (explicitly) and in SQLAlchemy (iterating over a `cursor.description` that is `None`).

I think the SQLAlchemy bug happens only in conjunction with the `druid` backend, and I recently fixed it (https://github.com/druid-io/pydruid/pull/133/). But it's better to be on the safe side here.

### CODE REVIEW

**Comment by hughhhh** [comment]
What will transpire in the UI for a No Data? Right now GeoVis actually uses that exception (400 status code) for indicating there isn't data available.

**Comment by betodealmeida** [comment]
@hughhhh, the UI will now show the yellow bar with the text "No Data". The exception is raised later in `viz.py`, when it detects that the dataframe is empty.

**Comment by hughhhh** [comment]
🚢

**Comment by mistercrunch** [comment]
LGTM

**Pull request merged**
