### PR TITLE
chore: Removes Popover duplication

### PR DESCRIPTION
**Pull request by michael-s-molina**
### SUMMARY
Removes `Popover` duplication.

### TEST PLAN
1 - Execute all tests.
2 - All tests should pass.

@rusackas @junlincc 

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by rusackas — COMMENTED** [review]
It seems like `import Popover from 'src/components/Popover';` just loads a wrapper which effectively aliases `import { Popover } from 'src/common/components';` - should we just point directly to the latter, and remove `src/components/Popover`? It seems like the only reason to keep the wrapper would be if we intend to enhance or style the "stock" popover.

**Comment by michael-s-molina** [comment]
> It seems like `import Popover from 'src/components/Popover';` just loads a wrapper which effectively aliases `import { Popover } from 'src/common/components';` - should we just point directly to the latter, and remove `src/components/Popover`? It seems like the only reason to keep the wrapper would be if we intend to enhance or style the "stock" popover.

Great question @rusackas! `src/common/components` will be deleted when we migrate all to `src/components`. The import in `src/components/Popover` is wrong, it should be `from antd`. I'll fix it!

Later we'll create and index in src/components and export all with named exports. Then we could delete `src/components/Popover` if there's no customization.

**Review by geido — APPROVED** [review]
LGTM!

**Review by rusackas — APPROVED** [review]
LGTM!

**Pull request merged**
