### PR TITLE
docs: reorganize the CONTRIBUTING section

### PR DESCRIPTION
**Pull request by mistercrunch**
### SUMMARY
Screenshot 2024-04-25 at 12 17 23 PM

Recently I realized that much of the content in CONTRIBUTING.md was
duplicated in `docs/docs/contributing`, and had evloved into much of a
complicated patchwork of semi-useful content.

How I approached it:
- decided to make CONTRIBUTING.md a simple pointer to the documentation
  website
- merged all information into `docs/docs/contributing`, tried to take
  the more complete where docs had been copy/pasted
- review the big sub-section into a more comprehensive set
  - Contibuting to Superset: high level info and orientation
  - Guidelines: how we approach guidelines, conventions, and interactions
  - Setting up a dev envrionemnt
  - Development how-tos
  - Resources: for things like ERD, arch diagrams, ...
  - Misc.: catch all for all the rest of things that don't fit anywhere
- I re-did the top part of "Setting up a dev envrionemnt", as things
  were confusing and wanted to point more directly to docker-compose as
  the main supported method
- various edits

There's more work to be done here, but this seems much saner and much
more manageable.

### CODE REVIEW

**Comment by rusackas** [comment]
CC @artofcomputing

**Comment by artofcomputing** [comment]
This is great, having the docs as the only source of truth makes any future changes much more manageable IMO.

**Review by artofcomputing — APPROVED** [review]
LGTM

**Comment by mistercrunch** [comment]
@sfirke I was thinking the arch diagram you mentioned before will fit nicely under the "Resources" section along with the ERD that's in there now.

**Review by betodealmeida — APPROVED** [review]
Beautiful!

**Review by sfirke — APPROVED** [review]
I don't have bandwidth to review the bulk of this.  I looked at a little bit of it and pointed out some small things. But I love the idea of consolidating!  As people use this documentation, any issues from the consolidation will surface.

**Review by rusackas — APPROVED** [review]

**Pull request merged**
