### PR TITLE
refactor: extract json_required view decorator

### PR DESCRIPTION
**Pull request by ad-m**
### SUMMARY

During review #18151 there was a comment about code duplication of snippet like:

```python
        if not request.is_json:
            raise InvalidPayloadFormatError("Request is not JSON")
```

> Do we have a decorator for this? Might want to add one if not yet.

_Originally posted by @ktmud in https://github.com/apache/superset/pull/18151#discussion_r791180093_

I would like to get familiar with part of the codebase of the project written in Python, so I perceived that as a good first issue for a new contributor.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

N/A

### TESTING INSTRUCTIONS

Python test handle all scenarios. I added a new one integration tests to verify behaviour of extracted decorator.
 
### ADDITIONAL INFORMATION

- [ ] Has associated issue: #18151
- [ ] Required feature flags: NO
- [ ] Changes UI: NO
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351)): NO
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API: NO
- [ ] Removes existing feature or API: NO

@ktmud, @michael-s-molina Can I request reviews? I am aware this is a trivial change, but I want to try to grab the project style & structure to be able to make bigger changes, and the beginning has to be somewhere.

### CODE REVIEW

**Comment by michael-s-molina** [comment]
Thank you for the PR @ad-m. Grabbing an example from Java, I really like the abstraction of `@Produces` and `@Consumes` annotations of [JAX-RS](https://docs.oracle.com/cd/E19798-01/821-1841/gipzh/index.html). They accept the MIME type as an argument.

`@Consumes("application/json")`

Since [request.is_json](https://flask.palletsprojects.com/en/2.0.x/api/#flask.Request.is_json) is pretty much checking the MIME type we could create a generic decorator the same way JAX-RS does. This will allow us to validate all request types in our endpoints.

**Comment by ad-m** [comment]
I like to make it even more generic. I will apply you suggestion soon!

śr., 26 sty 2022, 12:21 użytkownik Michael S. Molina <
***@***.***> napisał:

**Comment by ktmud** [comment]
I'm not sure we need to make it generic. Which other request payload type we must handle?

**Comment by ktmud** [comment]
I'd recommend use a single decorator to keep things simple---so you don't have to import both the decorator and the constant. It may be more appropriate to name the function with a verb, i.e. `requires_json` instead of `json_required` (which sounds like a state).

**Comment by michael-s-molina** [comment]
> I'm not sure we need to make it generic. Which other request payload type we must handle?

The `*/import` endpoints use `multipart/form_data` as the MIME type for the body.

> I'd recommend use a single decorator to keep things simple---so you don't have to import both the decorator and the constant. It may be more appropriate to name the function with a verb, i.e. requires_json instead of json_required (which sounds like a state).

While checking the API docs I found `application/json` and `multipart/form_data` as request MIME types. I also find `application/text` as the response MIME type for some endpoints. There doesn't seem to be much variation, so I'm fine with either approach.

**Comment by ad-m** [comment]
I renamed decorator to `requires_json` and created a separate decorator `requires_form_data` for `multipart/form_data` request. 

I inspected code looking for other request formats and I notice that have `superset.views.core.Superset.import_dashboards` (endpoint `/import_dashboard/`)  which uses two request formats depending on the request method - empty request (GET with HTML form in response) or form-data (POST with redirection on success response). However, I think we can handle this particular scenario in a special way.

I decided to use two decorators because I considered a small number of scenarios, I felt there was no reason to add more responsibility to one function (which increases complexity) since there are only two simple scenarios. The current approach is simple - readable and easy to use.

**Review by michael-s-molina — APPROVED** [review]
LGTM

**Pull request merged**
