### PR TITLE
[RFC] fix hive.fetch_logs

### LINKED ISSUE #2954: TApplicationException: Invalid method name: 'GetLog'
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.18.4

### Expected results
pyhive will work

### Actual results
when query against `hive://` backends, superset worker will raise this error:

```
  File \"\/usr\/lib\/python3.6\/site-packages\/superset\/db_engines\/hive.py\", line 18, in fetch_logs
    logs = self._connection.client.GetLog(req)
  File \"\/usr\/lib\/python3.6\/site-packages\/pythrifthiveapi\/TCLIService\/TCLIService.py\", line 762, in GetLog
    return self.recv_GetLog()
  File \"\/usr\/lib\/python3.6\/site-packages\/pythrifthiveapi\/TCLIService\/TCLIService.py\", line 779, in recv_GetLog
    raise x
thrift.Thrift.TApplicationException: Invalid method name: 'GetLog'
```

### Steps to reproduce
* install pyhive v0.3.0, pythriftapi on 4e2e9935bdddbe2f30630ef22c5aa045b713478e (at the time of writing, the pythriftapi on pypi is using python3 incompatible import style, must install from github repo)
* add a database in superset using the `hive://` prefix
* run some hql queries, in my case, the simple ones like `select * from table_name limit 2` will work, but complex query that'll run for a long time in hive CLI, will raise this error.

### ~~Study~~
~~I see there's [this `fetch_logs` method](https://github.com/airbnb/superset/blob/master/superset/db_engines/hive.py#L6) that looks like a patch for [the original `fetch_logs`](https://github.com/dropbox/PyHive/blob/master/pyhive/hive.py#L320) method, but I didn't see any code that actually does the patching, just a method declaration lying there, so AFAIK the `fetch_logs` method ran by superset worker, is still the original ones from pyhive?~~

### PR DESCRIPTION
**Pull request by timfeirg**
what's in this PR:
* adopted https://github.com/airbnb/superset/issues/2954#issuecomment-308023559
* change return type to string instead of a list of strings.
* fix one of the assert statements inside the except clause

this closes https://github.com/airbnb/superset/issues/2954
@mistercrunch

### CODE REVIEW

**Comment by timfeirg** [comment]
codeclimate complains about line length, but in this case, breaking lines up actually hurts readability, if this is absolutely required, I'll fix.

**Comment by timfeirg** [comment]
Sorry that I've notified you when the PR isn't ready, but I think I've got it working correctly now, request for comment @mistercrunch

**Comment by timfeirg** [comment]
request for comment @bkyryliuk

**Comment by timfeirg** [comment]
I've adjust the line breaks just to satisfy codeclimate. all green lights now, care to comment? @mistercrunch 

again, sorry to mention you so many times, but I was suspecting if github had some kind of mechanics that prevent maintainers from receiving notifications from inadequate pull requests, because I didn't think the codeclimate's suggestions are useful and just let its tests stay unsuccessful.

now that travis and codeclimate tests is passing, I really wish somebody can take a look at this and tell me if I was doing things the way it should be.

I've also added some explanations in the PR descriptions, looking forward to your response.

**Comment by mistercrunch** [comment]
Sorry it took me a while to get to this, I was out on vacation for a while and busy in general. Reviewing now.

**Pull request merged**
