### PR TITLE
Adding Trendline chart

### PR DESCRIPTION
**Pull request by VinodLouis**
trendline

Adding a Trendline chart to superset.

### CODE REVIEW

**Comment by mzangie** [comment]
Confused?

**Comment by mistercrunch** [comment]
Personally would prefer if we could make this an option to the existing line chart.

**Comment by VinodLouis** [comment]
@mistercrunch I agree with you. Will work on that

**Comment by JamshedRahman** [comment]
@VinodLouis Great work here. Have you considered making this an annotation, so that it can be overlaid on top of an existing series?

**Comment by EvelynTurner** [comment]
We were thinking of having it as part of annotation layer, providing options for linear, exponential, polynomial, etc. using a library (R^2 square and equation not shown but it's easy to implement). I guess it could be just a trendline option in line chart as well if you desire.
screen shot 2018-06-06 at 5 27 42 pm
screen shot 2018-06-06 at 5 27 56 pm

**Comment by mistercrunch** [comment]
@EvelynTurner is this a mock up or something you have in your fork?

**Comment by EvelynTurner** [comment]
@mistercrunch It's just something that I worked on internally for fun(?); the code is not public.  @VinodLouis I see that you started working on it 10 days ago; do you have an almost completed solution? Otherwise I can share my code with you; you can improve upon it and commit. You are good at visualization and there is some useful improvements we can make in my solution. I don't mind at all if you already have something planned. My previous comment was just to show another option.

**Comment by VinodLouis** [comment]
@EvelynTurner I have this complete solution of trendline as independent chart. But this makes more sense in annotation as in that case we would be leveraging the existing line chart less code more productivity. I have not yet started working on trendline as annotation not sure will start at least till this week (engaged in exams). If you have done it proceed with that to integrate in superset that would be an awesome addition.

**Comment by EvelynTurner** [comment]
Cool, I'll put up a PR this upcoming weekend

**Comment by hajdbo** [comment]
This is an awesome feature that I'd like to see merged :)

**Pull request closed without merging**
