### PR TITLE
[js] version js file names using webpack chunkhash

### PR DESCRIPTION
**Pull request by ascott**
this pr introduces automatic js filename versioning so we don't have to rely on updating the package.json version to make sure changed js files get their cache busted.

@mistercrunch @graceguo-supercat

### CODE REVIEW

**Comment by mistercrunch** [comment]
Very nice. Happy to see this! LGTM

**Review by mistercrunch — APPROVED** [review]

**Comment by yidazh** [comment]
In dev mode, the `manifest.json` changes but will not be reloaded after js files changing, so the pages remain the same. Utilizing webpack chunkhash depending on the NODE_ENV will be prefered. Like this:

```
process.env.NODE_ENV === 'dev' ? '[name].entry.js' : '[name].[chunkhash].entry.js'
```

**Comment by mistercrunch** [comment]
I don't have this problem in dev mode. It was an issue inn the master branch for a little while recently but it's fixed now. Can you rebase?

**Comment by yidazh** [comment]
@mistercrunch Thanks for your reply. It works. Great job.

**Pull request merged**
