### PR TITLE
refactor: Fix typescript any

### PR DESCRIPTION
**Pull request by maloun96**
Replace all "any" with custom type "$anyType"

### CODE REVIEW

**Comment by maloun96** [comment]
@rusackas @etr2460

**Comment by ktmud** [comment]
> It's weird that the package lock file has 60k new lines, maybe there were merge conflicts? I'd recommend looking into fixing that

Most likely from `package-lock.json`!

**Comment by rusackas** [comment]
@maloun96 This PR needs a rebase anyway, and we can see what happens to `package-lock.json` then, but I think since `package.json` didn't change, we should just not commit any `package-lock.json` changes. 

For some annoying reason, `npm install` almost always makes a bunch of noisy changes in the package-lock. I usually just don't commit those changes at all, unless `package.json` changed.

**Comment by amitmiran137** [comment]
closing due to inactivity

**Pull request closed without merging**
