### PR TITLE
Added button on slice for export D3js graph to png

### PR DESCRIPTION
**Pull request by ymatagne**
Hello,

We want to export the graphics in dashboard to be transmitted to the different clients.

I therefore add a button on the slices allowing the export of the graph D3.JS to a file png.

These actions are performed on the browser side.

Have a great day.
Yan

### CODE REVIEW

**Comment by zhangwenwu** [comment]
Uncaught DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range. 
How to solve this problem?

**Comment by Benji81** [comment]
Hello,
Any progress on this PR?
It is a very nice feature

**Comment by milesmuthu1** [comment]
Hi,

Any progress on this feature? Would be awesome to have.

**Comment by kristw** [comment]
Close and create issue to track idea.
https://github.com/apache/incubator-superset/issues/6743

**Pull request closed without merging**
