### PR TITLE
fix: Correction translation

### PR DESCRIPTION
**Pull request by aehanno**
Correction french translation

### SUMMARY
Remove to fuzzy to add the right translation

### BEFORE
image

### TESTING INSTRUCTIONS
Check that after we got the new translation

### CODE REVIEW

**Comment by aehanno** [comment]
@rusackas There is my new PR
I don't if we waiting the end of the discussion about the .json file before merging mine ?

**Comment by aehanno** [comment]
@rusackas and @villebro, can we go forward with this PR ?

**Review by rusackas — APPROVED** [review]

**Comment by aehanno** [comment]
Hi @rusackas, I see the tag 4.0.2 has been release but without this PR
How I can put it in the next one ?

**Comment by rusackas** [comment]
@michael-s-molina would have the most context on the patch releases, but I can say that 4.1 (coming soon, pending timeline from @sadpandajoe) should include this, since it'll be a fresh cut from the `master` branch.

**Pull request merged**
