### PR TITLE
[i18n] Add French translation

### PR DESCRIPTION
**Pull request by emirot**
I would like to add some french translations but I don't know what to refer to because the navbar_menu is auto generated.

### CODE REVIEW

**Comment by xrmx** [comment]
It could be that the stuff you want to translate comes from https://github.com/dpgaspar/Flask-AppBuilder so you may want to update the translation there

**Comment by emirot** [comment]
@xrmx I've created https://github.com/dpgaspar/Flask-AppBuilder/pull/735

**Comment by xrmx** [comment]
@emirot merci! :)

**Comment by emirot** [comment]
The PR dpgaspar/Flask-AppBuilder#735 got merged closing this one.

**Pull request closed without merging**
