### PR TITLE
chore: Upgrade pylint to 2.5.3 and fix most new rules

### PR DESCRIPTION
**Pull request by willbarrett**
### SUMMARY
Bumps pylint to 2.5.3, fixes most of the new checks, disables one new check that would keep us from working around circular import issues that we have right now.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
n/a

### TEST PLAN
Rely on CI

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

## Reviewers
@john-bodley @mistercrunch @craig-rueda

### CODE REVIEW

**Comment by willbarrett** [comment]
Woohoo! Clean build!

**Review by nytai — APPROVED** [review]
lgtm

**Comment by mistercrunch** [comment]
**Squeaky** clean build!

**Comment by mistercrunch** [comment]
Mergin' before it conflicts with any of the 40 files it touches!

**Comment by john-bodley** [comment]
Thanks @willbarrett. So happy to see people chipping away at fixing `pylint`.

**Pull request merged**
