### PR TITLE
fix(helm): set chart appVersion to 4.0.2

### PR DESCRIPTION
**Pull request by alecodev**
### SUMMARY

Fixed Helm version to match latest release

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by dpgaspar — APPROVED** [review]

**Comment by rusackas** [comment]
Ruh roh... thanks for the approval @dpgaspar but it seems we didn't merge this fast enough! @alecodev could you rebase/update the PR, and we'll try to snipe the merge button a little faster this time?

**Review by villebro — APPROVED** [review]
LGTM after rebasing and setting the correct new chart version number (patch bump). FYI we're planning on moving to `latest` tag after 4.1.0 release for latest stable version, so these types of bump chores won't be needed in the future.

**Comment by rusackas** [comment]
Moving this to draft mode, hopeful that @alecodev comes back to touch it up and mark it as "ready for review" again :)

**Comment by MattpaulKing** [comment]
watching

**Comment by rusackas** [comment]
I'm assuming @alecodev isn't coming back to rebase this... closing for now, but happy to reopen as needed.

**Pull request closed without merging**
