### PR TITLE
Set logging level to debug for DummyStatsLogger

### LINKED ISSUE #3660: [stats_logger] entries flooding the console log
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.20.4

### Expected results
The console log of `superset runserver` shows _useful_ information.

### Actual results
The console output is flooded with these messages:
```
2017-10-12 17:28:23,111:INFO:root:[stats_logger] (incr) queries
2017-10-12 17:28:23,363:INFO:root:[stats_logger] (incr) queries
2017-10-12 17:28:24,111:INFO:root:[stats_logger] (incr) queries
2017-10-12 17:28:25,111:INFO:root:[stats_logger] (incr) queries
2017-10-12 17:28:25,362:INFO:root:[stats_logger] (incr) queries
2017-10-12 17:28:26,111:INFO:root:[stats_logger] (incr) queries
2017-10-12 17:28:27,111:INFO:root:[stats_logger] (incr) queries
2017-10-12 17:28:27,362:INFO:root:[stats_logger] (incr) queries
2017-10-12 17:28:28,112:INFO:root:[stats_logger] (incr) queries
2017-10-12 17:28:29,113:INFO:root:[stats_logger] (incr) queries
```

### Steps to reproduce
Run `superset runserver` in the foreground.
Maybe it's important that we are running `superset worker` parallel and use _redis_ as backend/cache.

### Thoughts
Did I simply miss any config option to silence these messages?
Parts of my config that I consider as being somewhat related:
```
# Whether to run the web server in debug mode or not
DEBUG = False
# Whether to show the stacktrace on 500 error
SHOW_STACKTRACE = True
# Console Log Settings
LOG_FORMAT = '%(asctime)s:%(levelname)s:%(name)s:%(message)s'
LOG_LEVEL = 'DEBUG'
# Whether to bump the logging level to ERRROR on the flask_appbiulder package
# Set to False if/when debugging FAB related issues like
# permission management
SILENCE_FAB = True
```

### PR DESCRIPTION
**Pull request by mistercrunch**
fixes https://github.com/apache/incubator-superset/issues/3660

### CODE REVIEW

**Comment by timifasubaa** [comment]
lgtm

**Comment by rumbin** [comment]
@mistercrunch Are you sure that this fixes #3660? I included your changes in our installation and restarted superset, and these log messages still are flooding the console log. I don't assume that I was supposed to build anything here, as this is only a py file, right?

**Comment by xrmx** [comment]
@rumbin you have default log level set to debug, you have to raise it to something less spammy.

**Comment by rumbin** [comment]
Well this is embarassing.
I didn't notice that the _default_ LOG_LEVEL is set to DEBUG.

Thanks anyway, @xrmx...

**Pull request merged**
