### PR TITLE
chore(frontend): captialize reports for ocd relief

### PR DESCRIPTION
**Pull request by cemremengu**
### SUMMARY

Capitalize `reports` so that page title is `Alerts & Reports`

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

AFTER

image

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by etr2460 — CHANGES_REQUESTED** [review]
I _think_ the current behavior is desired. See https://github.com/apache/superset/wiki/Capitalization-Guidelines.

Maybe @rusackas could validate since he was the last editor of that wiki page?

**Comment by cemremengu** [comment]
Thanks for the info this makes sense. However I think that the `&` can be an exception in my opinion. Other texts did not catch my attention but for some reason this feels off.

**Comment by rusackas** [comment]
Pinging @mihir174 and @jess-dillard for more design input here, but my two cents are that `&` should not be an exception. It's cap height, which probably does make it a little odd, but I'd almost rather replace it with `and` than bend or break the rule we're still trying to spread around the UI consistently. 

If we DO decide to go with that decision and close this, we should add a rule about `&` to the style guideline :) It's a good callout, @cemremengu and I/we appreciate the contribution/consideration!

**Comment by jess-dillard** [comment]
@rusackas @cemremengu Agreed we need to put some more thought into standardization here – in the meantime I have no issue with either option.

**Comment by rusackas** [comment]
@cemremengu is this still bothering you? Not sure if we should re-open the debate, or let it go and close this PR :P 

I think generally people are fine with the capitalization standards and the product as-is, but I'm very curious your thoughts :)

**Comment by cemremengu** [comment]
@rusackas since most of the community is happy and it is aligned with the current guidelines, I think we can close this to focus on more important tasks. 

Thank you for asking and consideration!

**Pull request closed without merging**
