### PR TITLE
Visualization Unicode bug fix

### PR DESCRIPTION
**Pull request by JamshedRahman**
This change fixes unicode data errors in Python 2. Replacing str() with six.text_type(), which is unicode() in Python 2 and str() in Python 3.
This change is an extension of #5093 for all viz types.
Also includes an unit test for time series viz types.

### CODE REVIEW

**Comment by JamshedRahman** [comment]
This build is failing due to an unrelated issue. Looks like #5236 and #5357 are creating a conflict due to duplicate keys in _controls.jsx_ line 211. Please fix _controls.jsx_...

**Comment by mistercrunch** [comment]
LGTM, can you rebase please. I think `master` may have been broken at the time you created your branch.

**Comment by JamshedRahman** [comment]
Updated and resubmitted. @mistercrunch please merge to master when you get chance :-)

**Comment by mmuru** [comment]
@JamshedRahman:  Please, can you add the following change into your PR. The issue #5479 has more details
``
Line 753 in superset/models/core.py 
sqls = [str(s).strip().strip(';') for s in sqlparse.parse(sql)] 
should change to 
sqls = [six.text_type(s).strip().strip(';') for s in sqlparse.parse(sql)]
``
I tested this change and worked.

**Comment by mistercrunch** [comment]
Ooops, noticed the new comment after merging. It should be able to create a new PR with that change.

**Pull request merged**
