### PR TITLE
chore: Removes Select duplication

### PR DESCRIPTION
**Pull request by michael-s-molina**
### SUMMARY
This PR removes `Select` duplication by moving old `src/common/components/Select` to `src/components/Select` folder. To achieve that, the old component was renamed to `NativeSelect`. Currently, our `Select` component uses `react-select` but we should migrate it to AntD so this PR is an intermediary step in our refactoring process with the objective of organizing all `Select` in the same folder.

### TEST PLAN
1 - Execute all tests.
2 - All tests should pass.

@rusackas @junlincc 

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by geido — APPROVED** [review]
LGTM!

**Review by rusackas — APPROVED** [review]
LGTM! Tested all the places this touches.

**Comment by rusackas** [comment]
@robdiciuccio not sure if the testenv was super delayed due to GH Actions queueing, or if there's something else afoot with this one.

**Pull request merged**
