### PR TITLE
increase node memory in tox testenv

### PR DESCRIPTION
**Pull request by DiggidyDave**
### CATEGORY

Choose one

- [X] Bug Fix
- [ ] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY
I've seen lots of webpack OOM failures in PR requests the last couple of days. This is an attempt to unblock those.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### REVIEWERS
@dpgaspar @mistercrunch @betodealmeida

### CODE REVIEW

**Comment by DiggidyDave** [comment]
This seems to be working based on the push jenkins job.  @dpgaspar @thunter009 et al who have OOM failures in other PR builds.

@mistercrunch @betodealmeida etc plz review.

**Comment by dpgaspar** [comment]
Yep `0xad641e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xad6654 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [no`

**Review by kristw — APPROVED** [review]

**Comment by kristw** [comment]
Thank you @DiggidyDave

**Comment by kristw** [comment]
The JS build stalls after finishing unit test. Not sure why.

**Pull request closed without merging**
