### PR TITLE
chore: bump @superset-ui/plugin-chart-table to 0.17.28

### PR DESCRIPTION
**Pull request by ktmud**
### SUMMARY

bump @superset-ui/plugin-chart-table to 0.17.28 to bring in https://github.com/apache-superset/superset-ui/pull/1039

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

See https://github.com/apache-superset/superset-ui/pull/1039

### TEST PLAN

Manual testing and visual confirmation

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by ktmud** [comment]
Also bump chrono-node so it adds typing. https://github.com/apache/superset/pull/13797#discussion_r605869581

**Review by etr2460 — APPROVED** [review]

**Review by junlin-qa — APPROVED** [review]
Tested locally! LGTM thanks for the enhancement. 🙏

I think we should allow user to set the alignment(left, center and right) in the future.

**Pull request merged**
