### PR TITLE
[DRAFT] fix: Change url in cache-warmup celery task

### PR DESCRIPTION
**Pull request by duynguyenhoang**
### SUMMARY
Currently, there is cache-warmup task allows us to warm up dashboards/slices. But this feature is not working at all.
There is also available endpoint to warmup cache, this pull request will use that endpoint.

### TESTING INSTRUCTIONS
- Add cache task: 'cache-warmup' to CELERYBEAT_SCHEDULE
- Very that the selected slice in dashboard is refreshed after every warmup

Example Beat schedule config

```
CELERYBEAT_SCHEDULE = {
	'cache-warmup-3-minute': {
		'task': 'cache-warmup',
		'schedule': crontab(minute='*/3'),  # Every 3 minutes for testing
		'kwargs': {
			'strategy_name': 'top_n_dashboards',
			'top_n': 1,
			'since': '7 days ago',
		},
	},
}
```

### ADDITIONAL INFORMATION

- [x] Has associated issue: 
  - #10150,
  - #9597
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by nytai** [comment]
@etr2460 @john-bodley @graceguo-supercat I believe y'all make use of the cache warmup feature, do these changes make sense?

**Comment by nytai** [comment]
Can we add an example (can be commented out) to the default Celery beat config in config.py so other users know how to enable cache warmup scheduling?

**Comment by graceguo-supercat** [comment]
@nytai thanks for the alert :)  
This PR updates cache_warmup celery tasks, while in airbnb we used airflow job and call superset/warm_up_cache/?slice_id= directly. I don't think this change will impact airbnb, @betodealmeida is the best person for this feature.

**Comment by duynguyenhoang** [comment]
Having more test and I encounter that `superset/warm_up_cache/?slice_id=` doesn't work as expected. The root cause is the way cache keys are build. They are different in places.

**Comment by t0il3ts0ap** [comment]
@duynguyenhoang  were you able to get this to work ?
Also does this solve the issue with authentication.

**Comment by duynguyenhoang** [comment]
Hi @t0il3ts0ap,
It does fix issue with authentication, but for some chart types it doesn't work correct. For new charts using new API, they use different way to build cache key and why the current API doesn't work.

**Comment by b1de0** [comment]
Any updates?

**Comment by duynguyenhoang** [comment]
Hi @b1de0 unfortunately I am quite busy recently. I couldn't make it work. The cache API has been changed alot after version 1.0. I need to spend more time to understand the new implementation in order to fix this issue properly.

**Comment by villebro** [comment]
For charts that are using the new chart data endpoint the cache key should be calculated based on the `query-context` payload in the slice metadata (this is populated automatically when the chart is saved). In the long term we will probably introduce a Node based "sidecar" for generating the query context payload on the fly (they have to be rendered in JavaScript by the `buildQuery` callback in the plugin, hence can't be generated by the Python-based backend), but this will probably not happen in the near future.

@duynguyenhoang let me know if you have time to work on this and need help.

**Comment by duynguyenhoang** [comment]
@villebro thank you for your input, I might have some free time next week. I will check your suggestion and will ask you if I have any further questions.

**Comment by musicmuthu** [comment]
this issue not solved yet #bug

**Comment by musicmuthu** [comment]
this issue is resolved ?

**Comment by musicmuthu** [comment]
Hi @duynguyenhoang  this cache refresh is not working in 2.0 also can you please reopen this?

**Comment by rajniyadavashish** [comment]
Its working in 3.0.2 version but not in 3.1.0

**Pull request closed without merging**
