### PR TITLE
fix(Explore): Clear filter value when changing columns

### LINKED ISSUE #16844: [explore] when changing column of an existing filter, the existing filter value did not changed
When changing column of an existing filter, the existing filter value did not changed, the new filter will still show previous filter values which are not exist in the new filter

### Expected results

when i change the column of an existing filter, i expect the old value can be remove 

### Actual results

when i change the column of an existing filter, old value did not remove

#### Screenshots

https://user-images.githubusercontent.com/81597121/134817660-10d9dd15-a150-4bdd-96f6-bf09ccc2b694.mov

#### How to reproduce the bug

1. Go to explore, select column A for filter and select value for column A and save
2. Go to filter and change column A to column B
3. Observe the filter value and see error

### Environment

(please complete the following information):

- browser type and version:
- superset version: superset 1.3 RC2
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by geido**
### SUMMARY
This PR fixes an issue for which the filter value wasn't resetting when the column was changed.

### BEFORE
See #16844

### AFTER

https://user-images.githubusercontent.com/60598000/135114360-f16989ce-7616-4b27-85c7-0484261afeee.mp4

### TESTING INSTRUCTIONS
1. Open a Chart in Explore
2. Set a filter
3. Change the column of the filter
4. Make sure the filter value resets

### ADDITIONAL INFORMATION

- [x] Has associated issue: Fixes #16844
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by geido** [comment]
@jinghua-qa @junlincc

**Review by villebro — APPROVED** [review]
LGTM, almost surprised it took so long for this bug to surface!

**Comment by jinghua-qa** [comment]
I tested in the ephemeral environment, for the charts that have set filter, i am not able to change it to another column, if i add a new filter and change to another column, it work fine.

https://user-images.githubusercontent.com/81597121/135327094-6c5b3b46-9853-4f70-97fa-73b745d1778b.mov

**Pull request merged**
