### PR TITLE
fix: Set width to pseudoelement to wrap filter box

### PR DESCRIPTION
**Pull request by maloun96**
### SUMMARY
Set width to pseudoelement to wrap filter box

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
BEFORE
Kapture 2021-01-06 at 14 32 07

AFTER
Kapture 2021-01-06 at 14 28 22

### TEST PLAN
Select any chart to explore
Expand Query section
Click Filters
Select "NOT IN" or "IN"

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API
- [x] Fixes https://github.com/apache/superset/issues/12139

### CODE REVIEW

**Comment by maloun96** [comment]
@junlincc @rusackas

**Review by riahk — APPROVED** [review]

**Comment by adam-stasiak** [comment]
@maloun96 Could you verify this?
I see one issue there - > When I put multiple options there I cannot click Save button because modal buttons are covered with edit field.

https://user-images.githubusercontent.com/25153919/103891639-7e82c200-50ea-11eb-92c6-e7e9e3a8516b.mov

**Comment by junlincc** [comment]
Screen Shot 2021-01-07 at 6 41 23 AM
I'm also seeing this issue, adding scroll bar could introduce regressions in other area, so i would not recommend. is it possible to auto adjust the popover's height? 

Thanks for the PR, Thanks for testing! @maloun96 @adam-stasiak 🙏
cc: @michael-s-molina

**Review by junlincc — COMMENTED** [review]
Screen Shot 2021-01-07 at 6 41 23 AM
I'm also seeing this issue, adding scroll bar could introduce regressions in other area, so i would not recommend. is it possible to auto adjust the popover's height? 

Thanks for the PR, Thanks for testing! @maloun96 @adam-stasiak 🙏
cc: @michael-s-molina

**Comment by maloun96** [comment]
@junlincc  @adam-stasiak 

https://user-images.githubusercontent.com/8277264/104003643-58712680-51ab-11eb-9f0d-534fba916376.mp4

**Comment by junlincc** [comment]
getting some webpack errors when i run docker for this PR. tried all the tricks you guys taught me but nothing worked. any idea how to solve? @rusackas @nytai @zhaoyongjie?
Screen Shot 2021-01-08 at 8 48 34 AM

**Comment by nytai** [comment]
@junlincc That's weird, none of those errors seem related to files in this PR. Not seeing anything obvious

**Review by junlincc — APPROVED** [review]
ezgif-3-7b399b1b6e47

finally get docker working 🥺 
LGTM! @maloun96 well done 🙏

**Review by rusackas — APPROVED** [review]
LGTM!

**Pull request merged**
