### PR TITLE
fix: big number to handle NULL as it did in the past

### PR DESCRIPTION
**Pull request by mistercrunch**
context: https://github.com/apache/incubator-superset/pull/9313

### CODE REVIEW

**Review by etr2460 — CHANGES_REQUESTED** [review]
can we add a unit test to this PR as this was a regression that was recently introduced?

**Comment by mistercrunch** [comment]
I can write a unit test covering `get_data` later tonight

**Review by etr2460 — COMMENTED** [review]
ok. I think i'd feel comfortable accepting then once you add the manual test plan and some screenshots

however, a unit test should fast follow

**Comment by willbarrett** [comment]
I'm working on a unit test for this PR now.

**Comment by willbarrett** [comment]
@etr2460 unfortunately I was unable to come up with a comprehensive unit test by the end of my day. This will have to wait for @mistercrunch to free up again this evening. Apologies.

**Comment by mistercrunch** [comment]
Definitely was worth taking the time to write the unit test. Pandas is doing some funky things here in `pivot_table`. While clearly `np.isnan(np.sum(np.nan)) == True` `df.pivot_table({...}, aggfunc=np.sum)` of a column that has only `None` returns 0.

Anyhow. This here works, I picked `np.min` as no aggregates apply (already at the right grain) and with `np.min` a `None` leads to `nan`, which works well in the end (same as before the original PR). I tested this same unit test on before this PR and it fails (as expected, with the `0` value in place of the `None/nan/NULL`), and tested on before the a commit prior to the PR that created the problem  `753aeb482991f0dd3f36373f6d248ce277c67949` and this unit test passes. This gives pretty high confidence that `None` / `NULL` will be treated the same as before.

**Review by etr2460 — APPROVED** [review]
makes sense to me, thanks for adding the unit test!

I appreciate the quick response to the regression called out in the revert PR

**Review by villebro — APPROVED** [review]
Makes sense, LGTM. It seems one really has to be careful when applying Pandas transformations.

**Comment by etr2460** [comment]
@mistercrunch is this good to merge now?

**Pull request merged**
