### PR TITLE
[cosmetic] remove margin-bottom on dropdowns

### PR DESCRIPTION
**Pull request by mistercrunch**
`react-select` components have been added 15px bottom-margin without a
good reason. Other controls like text or checkboxes don't have that,
making Selects look non-standard, add making the control list too
sparse.

My perspective is that all controls should have the same
padding/margins.

## before 
screen shot 2019-01-09 at 5 34 39 pm

## after
screen shot 2019-01-09 at 5 26 51 pm

### CODE REVIEW

**Comment by elibrumbaugh** [comment]
@mistercrunch 

- What was the previous padding?
- What is the new padding?
- Is there any logic behind the new padding size?

The new padding feels a little too tight. For example the checkbox is really close to the row limit count.

**Comment by mistercrunch** [comment]
As mentioned above, only the dropdowns have an extra bottom padding of `15px`, other controls (text, textarea, checkbox, ...) do not have this extra 15px. If this is too tight, it means others controls are probably too tight too, and padding should be added to all controls (for consistency).

**Comment by elibrumbaugh** [comment]
Thanks Max. I agree this should be revisited for all controls for consistency's sake.

Is the best way to solve this to remove the 15px of extra padding and adjust all of control padding globally?

Considering this is an information dense UI my suggestion is to try 16px of padding on all controls.

**Comment by mistercrunch** [comment]
>Is the best way to solve this to remove the 15px of extra padding and adjust all of control padding globally?
yes

`15px` (as show on the picture above) seemed like way too much for me. Less density just means more scrolling.

**Comment by kristw** [comment]
@elibrumbaugh I think the 15px or 16px bottom padding for all controls are too much whitespace. IMO, I would try 4-6px for little separation but still preserve screen space for less scrolling.

**Comment by mistercrunch** [comment]
screen shot 2019-01-17 at 5 01 27 pm

**Comment by kristw** [comment]
LGTM

**Pull request merged**
