### PR TITLE
[bugfix] Fix the arguement order for security function

### PR DESCRIPTION
**Pull request by feng-tao**
Minor bug fix: the perm and view_menu seems to be in the wrong order.

cc @mistercrunch @hughhhh

### CODE REVIEW

**Comment by xrmx** [comment]
Opportunity to add a test?

**Comment by mistercrunch** [comment]
I'm wondering if the perms are reversed here somehow, which would make this a backward incompatible change...

**Comment by feng-tao** [comment]
@xrmx,  I could add a test if it is an issue. I hope I am not misunderstand the code...

**Comment by feng-tao** [comment]
@xrmx , @mistercrunch , @hughhhh  actually is it get_perm(https://github.com/apache/incubator-superset/blob/master/superset/connectors/druid/models.py#L512) actually is get_view_menu?

**Pull request closed without merging**
