### PR TITLE
feat: Select Component Feature Branch (Testing only)

### PR DESCRIPTION
**Pull request by rusackas**
### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by rusackas** [comment]
/testenv up FEATURE_DASHBOARD_NATIVE_FILTERS=true FEATURE_DASHBOARD_CROSS_FILTERS=true FEATURE_UX_BETA=true FEATURE_ENABLE_EXPLORE_DRAG_AND_DROP=true FEATURE_ENABLE_TEMPLATE_PROCESSING=true FEATURE_ENABLE_DND_WITH_CLICK_UX=true FEATURE_VERSIONED_EXPORT=true

**Comment by jinghua-qa** [comment]
Found 2 cosmetic issues in data table (can not repo on dev and prod):
1, the row bubble take some time to load when switching between data and sample

https://user-images.githubusercontent.com/81597121/134236002-a61e27d1-6434-4fa8-b767-704a4174bc01.mov

2, rolling down the data table and sample table the column title row is rolling too

https://user-images.githubusercontent.com/81597121/134236077-c5711a38-50fb-41b2-b0b8-a2ff84363376.mov

**Comment by geido** [comment]
/testenv up FEATURE_DASHBOARD_NATIVE_FILTERS=true FEATURE_DASHBOARD_CROSS_FILTERS=true FEATURE_UX_BETA=true FEATURE_ENABLE_EXPLORE_DRAG_AND_DROP=true FEATURE_ENABLE_TEMPLATE_PROCESSING=true FEATURE_ENABLE_DND_WITH_CLICK_UX=true FEATURE_VERSIONED_EXPORT=true

**Comment by geido** [comment]
> Found 2 cosmetic issues in data table (can not repo on dev and prod):
> 1, the row bubble take some time to load when switching between data and sample

Could not repro

https://user-images.githubusercontent.com/60598000/134532383-88289411-ccca-4694-ae05-acc785b1dfe1.mp4

> 2, rolling down the data table and sample table the column title row is rolling too

Could not repro as well 

https://user-images.githubusercontent.com/60598000/134532462-0ace75ef-fbcb-4862-bf82-5bf03b69dc6a.mp4


> 3, when adding annotation, need to click ok twice to add one annotation

I could reproduce this one and I am going to tackle it in the appropriate PR.

I also finished all the test cases and could not find any blocker. So I believe we are safe to proceed @jinghua-qa @junlincc

**Pull request closed without merging**
