### PR TITLE
chore: Moves CheckboxIcons to Checkbox folder

### PR DESCRIPTION
**Pull request by michael-s-molina**
### SUMMARY
Moves `CheckboxIcons` to `Checkbox` folder.

### TEST PLAN
1 - Execute all tests.
2 - All tests should pass.

@rusackas @junlincc 

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by geido — CHANGES_REQUESTED** [review]
LGTM with a small nit

**Review by geido — APPROVED** [review]

**Review by rusackas — APPROVED** [review]
LGTM!

**Pull request merged**
