### PR TITLE
chore: move react to peerDeps

### PR DESCRIPTION
**Pull request by zhaoyongjie**
### SUMMARY

This PR 
1. moved React to peerDependencies in plugins.
2. changed "range version" to "any version" in peerDeps
3. update "@ant-design/icons": "^4.2.2" to "@ant-design/icons": "^4.7.0"

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

N/A

### TESTING INSTRUCTIONS
CI

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by villebro — APPROVED** [review]
LGTM!

**Review by kgabryje — APPROVED** [review]
LGTM

**Review by kgabryje — APPROVED** [review]
LGTM

**Comment by zhaoyongjie** [comment]
I found some issues after `npm i --legacy-peer-deps` in this PR, so close it now.

**Pull request closed without merging**
