### PR TITLE
fix: bump Redis minor version

### PR DESCRIPTION
**Pull request by mvoitko**
### SUMMARY
To get Redis k8s deploy fixes https://github.com/bitnami/charts/pull/4911
 
### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by mvoitko** [comment]
@craig-rueda please review Redis chart fixes for k8s

**Review by craig-rueda — APPROVED** [review]

**Comment by craig-rueda** [comment]
Ur gonna need to bump chart version

**Comment by mvoitko** [comment]
@craig-rueda done. Thank you!

**Comment by mvoitko** [comment]
@amitmiran137 could you please merge?

**Pull request merged**
