### PR TITLE
[SIP-36] Migrate Link.jsx to Link.tsx

### PR DESCRIPTION
**Pull request by etr2460**
### CATEGORY

Choose one

- [ ] Bug Fix
- [x] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY
This is an example PR for migrating a React component from JSX to TSX. I performed the following steps:
1. Rename the component file from `Link.jsx` => `Link.tsx`
1. Install typedefs for imported libraries (ex. `npm install @types/react-bootstrap`) or add `// @ts-ignore` if no valid typedefs exist
1. Replace the `propTypes` const with an `interface Props` definition
1. Move default props into the default arguments within the React component
1. Resolve any type errors that may have been exposed by the migration
1. Attach before/after screenshots to the PR to ensure the component functionality remains the same

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Before:
Screen Shot 2020-02-18 at 10 20 51 AM

After:
Screen Shot 2020-02-18 at 10 15 36 AM

### TEST PLAN

CI and unit tests, confirm the Link component in SQL Lab renders as expected

### ADDITIONAL INFORMATION

- [x] Has associated issue: #9101
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### REVIEWERS
to: @graceguo-supercat @nytai @rusackas @kristw

### CODE REVIEW

**Review by nytai — APPROVED** [review]
LGTM! 

Looks like tslint is causing travis to fail, ++ for deprecating it in favor of eslint

**Comment by nytai** [comment]
also, I've noticed that tslint doesn't seem to run as part of `lint-fix` 

`./node_modules/.bin/tslint -c ./tslint.json --fix ./{src,spec}/**/*.ts{,x}`

is how I've been getting around it.

**Comment by etr2460** [comment]
@nytai is deprecating tslint in favor of eslint something you can take on? I think we're all pretty much in agreement that it's the right move

**Review by suddjian — APPROVED** [review]

**Comment by nytai** [comment]
@etr2460 sure, I'll give it a try tomorrow

**Pull request merged**
