### PR TITLE
feat(country-map): Adds Philippines regional map and updates/cleans existing Philippines provincial map

### PR DESCRIPTION
**Pull request by jdruii**
### SUMMARY

- Added `philippines_regions.geojson` map using the regional ISO codes
- Updates `philippines.geojson` by dividing Maguindanao province to Maguindanao del Norte and Maguindanao del Sur, as well as splintering off Davao Occidental from Davao del Sur
- Cleans `philippines.geojson` by incorporating the inconsistently placed highly urbanized cities (which sometimes uses a pseudo-ISO code) into their respective geographical provinces. This is done to be more in line with how the Philippine Statistics Authority does it in their census.
- Merges the 16 cities and 1 municipality within Metropolitan Manila under the regional ISO code `PH-00` since there is no provincial ISO for the cities within.

References:
- [ISO-3166-2:PH codes](https://en.wikipedia.org/wiki/ISO_3166-2:PH)
- [2020 Philippine Census by the Philippine Statistics Authority](https://psa.gov.ph/content/highlights-philippine-population-2020-census-population-and-housing-2020-cph)

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

ph_div
ph_prov_mm
ph_prov_luzon
ph_prov_visayas
ph_prov_mindanao

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by rusackas** [comment]
Hi there... this is great, and we thank you for the contribution. Both the geojson files and the countries.ts file in this PR will be overwritten by anyone running the Jupyter notebook that generates Superset's maps. Would you be able to make your changes in that notebook so that the geojson/typescript in this PR is generated? This will help the whole project maintain good maps going forward.

**Comment by jdruii** [comment]
Added it. I hope it's okay that I used a different source for the changes that I made for the `phiippines.geojson`. The one being generated by the files from the Natural Earth Data is just outdated and too messy with the inconsistent highly urbanized cities.

**Comment by rusackas** [comment]
I'll take a look... as long as the data being pulled in is license-compatible with the Apache 2 license, I think we should be OK.

**Comment by rusackas** [comment]
I see the repo you set up with the geojson is MIT licensed. I suppose that's good enough, though I don't know where it came from beyond that 🤔 . Meanwhile, I'll close and reopen this to see if we can get CI to finish this time.

**Comment by jdruii** [comment]
Some of the coordinates are still from the original file. The rest are hand-fixed using [geojson.io](https://geojson.io). And according to them:

> The data you create and modify in geojson.io doesn't acquire any additional license: if it's secret and copyrighted, it will remain that way - it doesn't have to be public or open source.

**Review by rusackas — APPROVED** [review]

**Pull request merged**
