### PR TITLE
chore: refactor header menu to show in header grid component

### LINKED ISSUE #16424: [dashboard edit] can we make tool menu show up for header when hover over
Currently header tool menu(size, background, trashcan) did not show up when mouse hover over, which is not consistent behavior as other dashboard components.

https://user-images.githubusercontent.com/81597121/130660609-ede0bf93-7aa1-4cf5-ba12-491b70fcde32.mov

### PR DESCRIPTION
**Pull request by pkdotson**
### SUMMARY
This pr removes the hovermenu less file and refactors code to show the dashboard hover menu delete icon inside the header. 

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

before

https://user-images.githubusercontent.com/17326228/133115922-7670a640-18f5-4649-abc5-38920d63a3c0.mov

after

https://user-images.githubusercontent.com/17326228/133116020-c83fc7a5-20c9-4a6f-a79c-c22472f688b5.mov

### TESTING INSTRUCTIONS
Go to a dashboard and click on edit. Next drag a header tab to dashboard and ensure that the delete button show up on hover.

### ADDITIONAL INFORMATION

- [x ] Has associated issue: Fixes https://github.com/apache/superset/issues/16424
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by graceguo-supercat** [comment]
May I know why do you want to remove extra menu/options for dashboard header? 

cc @junlincc

**Comment by jinghua-qa** [comment]
@graceguo-supercat, we want to make this change because of 2 reasons:
1, For header and markdown component, the trashcan icon is not shown when hovering over (shown by click), which is inconsistent behavior with the rest of other dashboard components.
2,This inconsistent behavior sometimes could cause confusion. For example, when we have a markdown in a row, when user hovering over the markdown, a trashcan icon will show because of the Row component and makes user think that icon is to delete the markdown, but clicking on that trash icon will delete the Row with all components because the trash icon is shown when hovering a row and markdown trash icon wont show until you click on it. 
Screen-Recording-2021-09-13-at-5


We got this feedback from a first time user feeback so we suggest that 
1, to make trashcan icon show when hovering over for all components
2, when trashcan icon show for header and markdown, it will show in the right top conner inside the component so that it is clear to the user what is deleting.

**Comment by graceguo-supercat** [comment]
> We got this feedback from a first time user feeback so we suggest that
> 1, to make trashcan icon show when hovering over for all components
> 2, when trashcan icon show for header and markdown, it will show in the right top conner inside the component so that it is clear to the user what is deleting.

based on your comment, this PR didn't do it correctly. it removed font-size and background menu, is it part of design?

**Comment by pkdotson** [comment]
> > We got this feedback from a first time user feeback so we suggest that
> > 1, to make trashcan icon show when hovering over for all components
> > 2, when trashcan icon show for header and markdown, it will show in the right top conner inside the component so that it is clear to the user what is deleting.
> 
> based on your comment, this PR didn't do it correctly. it removed font-size and background menu, is it part of design?


@graceguo-supercat font size and background menu is still there. You have to click on the grid component to have them show like you do in markdown.

**Comment by jinghua-qa** [comment]
@pkdotson I tested in the test env, for header, it is worked as expected: trash icon is showed when hovering over, and the font size and background menu is shown when clicking on the component. But for markdown, the trash icon is not shown inside the component when hover over, it is still shown by clicking.

https://user-images.githubusercontent.com/81597121/133304334-e3e5ff1a-f7a0-4855-808f-dedbe73bbb7d.mov

**Comment by jinghua-qa** [comment]
> > We got this feedback from a first time user feeback so we suggest that
> > 1, to make trashcan icon show when hovering over for all components
> > 2, when trashcan icon show for header and markdown, it will show in the right top conner inside the component so that it is clear to the user what is deleting.
> 
> based on your comment, this PR didn't do it correctly. it removed font-size and background menu, is it part of design?



> > We got this feedback from a first time user feeback so we suggest that
> > 1, to make trashcan icon show when hovering over for all components
> > 2, when trashcan icon show for header and markdown, it will show in the right top conner inside the component so that it is clear to the user what is deleting.
> 
> based on your comment, this PR didn't do it correctly. it removed font-size and background menu, is it part of design?
@graceguo-supercat I tried in the test env, the font-size and background menu will show by click. Is our plan to change the trashcan to show by hovering over in header and markdown sound good to you?

**Comment by graceguo-supercat** [comment]
before: click to show UI menu + trash icon
after: click to show UI menu, but hove to show trash icon

Do you really need to make this change?

**Comment by pkdotson** [comment]
> before: (both header and markdown) click to show UI menu + trash icon
> 
> after:
> Header: click to show UI menu, but hove to show trash icon
> Markdown: click to show UI menu + trash icon.
> 
> isn't this more _inconsistent_? Do you really need to make this change?

@graceguo-supercat this has been changed as well. The delete now shows in the markdown on hover as well.
Screen Shot 2021-09-15 at 3 00 24 PM

**Review by graceguo-supercat — APPROVED** [review]
LGTM! thanks for the work!

**Pull request merged**
