### PR TITLE
fix(ListView): avoid firing event on change of selection

### PR DESCRIPTION
**Pull request by justinpark**
### SUMMARY
When you paste a value in the list view filter, the input field automatically submits the input value right away.
This happens because the `onSelect` event is triggered when the `onChange` event occurs, instead of when the actual selection is made.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

Before:

https://github.com/apache/superset/assets/1392866/1b319b5a-e339-4ab4-988b-990576b0b8d8

After:

https://github.com/apache/superset/assets/1392866/ee9bde52-6e6e-4632-ba60-d2582f1fa323

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by rusackas — APPROVED** [review]
LGTM! The failing test looks like an easy-peasy fix ;)

**Review by michael-s-molina — CHANGES_REQUESTED** [review]
@justinpark When you paste something on the Select component, it's already selected. The change you did might confuse users because if you paste and then close the select, the filter won't be applied but the value will be selected.

What is the problem of triggering the query when you paste?

**Comment by michael-s-molina** [comment]
> @justinpark When you paste something on the Select component, it's already selected. The change you did might confuse users because if you paste and then close the select, the filter won't be applied but the value will be selected.

What is the problem of triggering the query when you paste?

**Comment by justinpark** [comment]
Closed as #28017 solved the issue

**Pull request closed without merging**
