### PR TITLE
fix(docker): error around missing requirements/base.txt

### LINKED ISSUE #27606: Problem Building dev Docker image
### Bug description

When building the Docker images on macOS, there is an issue when installing the dependencies on the Dev image.
Looks like it might be a result of #27505 

M2 Pro
macOS Sonoma 14.2.1

### How to reproduce the bug

Fresh repo clone
Before building, I pruned Docker's cache.

From the project's root dir
`docker compose build`

Output
```sh
[superset-worker dev 2/2] RUN --mount=type=bind,target=./requirements/development.txt,src=./requirements/development.txt     --mount=type=cache,target=/root/.cache/pip     pip install -r requirements/development.txt:

0.345 ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements/base.txt'
```

### Screenshots/recordings

_No response_

### Superset version

master / latest-dev

### Python version

Not applicable

### Node version

Not applicable

### Browser

Not applicable

### Additional context

_No response_

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### PR DESCRIPTION
**Pull request by mistercrunch**
### SUMMARY

I'm unclear on why exactly CI succeeded while this was an issue running
locally. I'm guessing it has to do with `--mount` and how it works
around caching, so I'm moving to a COPY-based approach, which is more
standard and easy to reason about. It also leaves a useful artefact on
the machine as to how it was built. It does add a tiny layer and payload
on the image, but it's super cheap for the utility/introspection it provides.

Closes https://github.com/apache/superset/issues/27606

----
I found the issue as to why this defect in the dockerfile wasn't caught in CI, it's because the `--preset dev` parameter was not getting passed down properly, and resulting in targeting the `lean` layer, avoid that issue altogether. I fixed `supersetbot`, added unit tests and published a new version on npm.

### TESTING/VALIDATION

tested `docker-compose up` and validated that CI is now building the right target as opposed to always be building the `lean` target.

### CODE REVIEW

**Review by rusackas — APPROVED** [review]
I'll admit I had GPT walk me through some of this, but it seems like it all ought to be fine from what I/we can tell.

**Comment by guizsantos** [comment]
I think the issue here was that `requirements/development.txt` references `requirements/base.txt` and since `base.txt` is mounted during runtime, it is not available when the second pip install is running. I believe adding `--mount=type=bind,target=./requirements/base.txt,src=./requirements/base.txt \` in addition to the `development.txt` mount fixes the issue. I liked the mount base approach, much prefer it over the `COPY`-based one.

**Comment by mistercrunch** [comment]
Oh right, totally, that was the issue.

Originally in my PR I was confused as to why CI didn't fail / catch this issue in the first place which I found along the way and commented on the PR body ->

> I found the issue as to why this defect in the dockerfile wasn't caught in CI, it's because the --preset dev parameter was not getting passed down properly, and resulting in targeting the lean layer, avoid that issue altogether. I fixed supersetbot, added unit tests and published a new version on npm.

**Comment by xyy94813** [comment]
Hi, 
I want to confirm if this PR fixes follow bug in CI of my PR??

```
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements/testing.txt'
```

https://github.com/apache/superset/actions/runs/8235126931/job/22862070545?pr=26180

**Comment by mistercrunch** [comment]
@xyy94813 rebase and you should be fine

**Pull request merged**
