### PR TITLE
fix(dashboard): Open "View Chart in Explore" in the same window

### LINKED ISSUE #14672: Keep dashboard's "View chart in Explore" from opening a new tab
Currently, when you navigate from a chart in a Dashboard to Explore via the "view chart in Explore" menu item, it opens a new tab. 

Let's do a little detective work in git blame to reach out to the original author(s) and find out if/why this behavior was intended. For now, I think we should keep everything in one tab/window.

### Expected results

The link should keep you in the same tab, navigating away from the dashboard, rather than opening a new tab.

### Actual results

A new tab is opened

CC @steejay @mihir174 @mistercrunch @junlincc in case you're aware of any existing counter arguments against this change.

### PR DESCRIPTION
**Pull request by geido**
### SUMMARY
Fixes: #14672

The function `postForm` introduced in PR #9345 has the target set to `_blank` by default. This PR specifies `_self` instead. There does not seem to be any obvious issue in doing so. Input from @graceguo-supercat is appreciated as a double check.

### TESTING INSTRUCTIONS
1. Open a dashboard
2. Choose a chart and select "View Chart in Explore"
3. Make sure the chart Explore page is opened in the same window

### ADDITIONAL INFORMATION

- [x] Has associated issue: #14672
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by junlincc** [comment]
Thanks for the PR. Please see video of Before and After behavior in select of Dashboard->Explore->Dashboard flow 

https://user-images.githubusercontent.com/67837651/119709552-31da2200-be12-11eb-9cf6-f75e93948dc7.mov

Previous behavior. View chart in Explore takes user to Explore, user revise the chart in Explore and can save it back to same dashboard( preselect in the dropdown). i dont think your PR changed the behavior, just wonder why the source dashboard is not preselected anymore.

**Comment by geido** [comment]
@junlincc I don't see the problem that you are describing but I see a worse problem.

If you open up any dashboard it will always pre-select the same dashboard, independently from the actual dashboard that you have opened. This is not related to this PR as this problem is reproducible on master and in this branch also now that I have merged it with master.

See video.

https://user-images.githubusercontent.com/60598000/119866680-b9fd1c00-bf25-11eb-8980-9057a44541eb.mp4

Please let me know if you can reproduce it, we should file a separate issue.

**Review by michael-s-molina — APPROVED** [review]

**Review by villebro — APPROVED** [review]
LGTM. I looked at the original PR, and I didn't see an explicit mention of meaning to start opening the browser in `_blank`, so I assume that was a regression. But it would be nice if @graceguo-supercat could confirm this. However, what does seem to be intentional is targeting `_blank` when pressing "Run in SQL Lab" from "Explore". I wonder if that behavior should also be changed, or if it's the exception that validates the rule?

**Comment by john-bodley** [comment]
@geido @villebro et al. could one provide context as why we want to explore a chart in place as opposed to in a new tab? I think many users prefer opening a chart in a new tab whilst maintaining reference to the dashboard—especially when one wishes to open multiple charts (which isn't possible now). Additionally per @villebro's comment the behavior of opening a chart in a new tab is consistent with "Run in SQL Lab" etc.

**Comment by graceguo-supercat** [comment]
I didn't notice this PR till today....Airbnb users preferred to open "View Chart in Explore", because our dashboard is large, many charts, many tabs, user may click a few tabs and then click View chart. Open the chart in the same window will make user lost their context. Please revert this PR.

**Comment by rusackas** [comment]
@graceguo-supercat @john-bodley @junlincc 

The reason for the change was that users were annoyed by the proliferation of new tabs, when they felt they _weren't_ necessary. 

Rather than reverting the PR, how about one of two means to support either behavior?

1) Make it an actual link so that users can Command-click or right-click the link to choose to open it in a new window?
2) Add a configuration variable in config.py so that the admin of the installation can override it?

If neither of those work, or take too long, I suppose we can revert it and then carry it forward in a new PR if needed.

**Comment by john-bodley** [comment]
@rusackas we think option (2) makes the most sense, though given this is a breaking change (in terms of UX) we sense it is best to revert the PR and in a follow up PR and the configuration option.

**Comment by junlincc** [comment]
hi @john-bodley @michellethomas i saw that you have reverted this change from locally. thanks for the feedback 🙏

We assume that the reason why a user click "View chart in Explore" is to tweak a specific chart, because all of the "view only" functionalities, including 1) view query 2)view chart details by hovering 3) maximize chart 4) filtering chart can all be done straightly from Dashboard. 
Under this assumption, "opening Explore from the same window -> making changes in Explore -> saving chart and going back to the same dashboard -> seeing changes appear on original or a new dashboard" seem to be a better/ more simplified workflow than leaving multiple tabs that show different versions of the same dashboard hanging. One quick enhancement to eliminate confusion is to change "View chart in Explore" to "Edit chart in Explore" 

I apologize if this assumption doesn't make sense to your users and the inconvenience we introduced by the change. 
As more and more users adopt Superset globally, accommodating to all users from different organizations became harder and harder, which means changes are inevitable. 
But I'm not sure if this this change is considered as a "breaking change"
according to a passed SIP [SIP-57] Proposal for Semantic Versioning, the definition of UI/UX changes is as follow 
- Changes that removes an existing functionality, such as a chart type or ability to select favorites. 
(Inconsequential visual changes or small functional changes such as removing a tooltip or the removing the ability to color a label aren't considered breaking changes.)
- Changes that break an existing workflow without providing a clear alternative or require user intervention for the alternative to be applied.

User may take a while to adapt to the optimized new flow, but the original functionality - opening Explore was not removed by this PR. I would suggest to go with proposed solution 2 without reverting from the main repo. 🙏

**Comment by graceguo-supercat** [comment]
> users were annoyed by the proliferation of new tabs,

Isn't this showing how frequently user needs to _**dig into many charts from a dashboard**_? If this is the case,
- option 1: open chart from same dashboard window, and go back to dashboard, wait it load, and find next chart.
- option 2: open chart into another window and leave original dashboard open. he can always go back to dashboard without waiting reloading and find the right tab.

To me the option 2 is much easier and intuitive way.

**Comment by graceguo-supercat** [comment]
> change "View chart in Explore" to "Edit chart in Explore"

really BAD idea. don't do it.

**Comment by junlincc** [comment]
> really BAD idea. don't do it.

sure!! 😁 
but again, the assumption we had is based on feedback from a good number of new Superset users. I can foresee more "disagreements" on changes are coming in the future, to make everyone happy, i suggest to make Superset more configurable and general, instead of building it around any specific organizations.

**Comment by graceguo-supercat** [comment]
Totally agree  **make Superset more configurable and general**

**Comment by john-bodley** [comment]
Thanks @rusackas for reverting this. In terms of user feedback, for this week's internal Airbnb release we forgot to locally revert the change (as was done in the previous release) and were pinged almost immediately by a user in Slack with the following:

> When clicking View chart in Explore in my Supeset dashboards, it used to open up Explore view in a separate tab, but now it is navigating away from the dashboard in the same tab..
>
> **Are others experiencing this same behavior?**  (might be an issue with my browser settings, although I have not changed anything recently)
>
> **Is this expected behavior?**  I frequently use this button to explore multiple charts and datasets and it’s rather cumbersome to have to navigate back to the dashboard every time.  And when you navigate back to the dashboard, it does not return to the tab you were on before (edited)

**Pull request merged**
