### PR TITLE
added a 'no_trend_line' option

### PR DESCRIPTION
**Pull request by xiaoyugit**
screen shot 2018-07-06 at 20 27 33

### CODE REVIEW

**Comment by williaster** [comment]
@xiaohanyu @mistercrunch it would have been great to clean up the code and consolidate vis types, deprecating the "big number" _without_ trend line, in this PR. Now we have two vis types that essentially do the same thing (one with a superset of functionality over the other).

**Comment by mistercrunch** [comment]
@williaster this one will take the latest available dot in the time series where "Big Number" would disregard the time granularity.

Personally I'm ok with a revert on this if you prefer. I know you had touched `big_number.js` in the past and there's an open PR on this. Happy to defer to that.

I'll make sure to keep PRs open longer before merging them to allow for more input.

**Comment by xiaohanyu** [comment]
@williaster I'm sorry but you @ the wrong person, LOL~

**Comment by xiaoyugit** [comment]
@xiaohanyu LOL~ guess I am the wrong person.
@williaster @mistercrunch  given different ways of handling time granularity, I don't think these two plots are redundant on functionality. Personally I would love to keep a number plot with Month-over-Month comparison but without the trend line (for tidiness).

**Comment by williaster** [comment]
@xiaohanyu sorry about that! 🙉 

@mistercrunch @xiaoyugit thanks for the thoughts. I think these two are still really redundant and the granularity difference could be handled with more config options. Will keep the two for now, though, since that's more work / would need a migration.

**Pull request merged**
