### PR TITLE
feat: Excel file export

### PR DESCRIPTION
**Pull request by blcksrx**
### SUMMARY

Support excel for exporting
### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

Screenshot from 2020-05-27 12-57-02
Screenshot from 2020-05-27 12-56-17
Screenshot from 2020-05-27 12-55-50

### ADDITIONAL INFORMATION

- [x] Has associated issue:
- [x] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [x] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by blcksrx** [comment]
@villebro

**Comment by bkyryliuk** [comment]
@blcksrx - could you share more about this feature use case and why .csv is not good enough? e.g. excel supports csv files as well as I know

**Comment by rusackas** [comment]
Pulling over a comment from a Slack discussion:

I would say it's worth embracing the growth of additional save/export options with a dropdown menu, e.g.:
```
+------------------------+
| Export Data To...  | ▼ |
+------------------------+
| Clipboard              |
| CSV                    |
| Excel                  |
| Parquet                |
| Google Sheet           |
+------------------------+
```
... to avoid button proliferation and add a spot for future integrations.

**Comment by opus-42** [comment]
Hello @bkyryliuk. I have provided additional context on why this may be useful 
#11162. 

Not every user may be CSV-friendly users. Excel Export are easier to handle for those users. For me, this is about Superset being more accessible to generic users.

This feature would be really help ful in production

**Comment by ninad-casebook** [comment]
One additional use-case for Excel over CSV is that datetime formats are not preserved in CSV. If the data being exported contains several datetime columns, then since CSV does not store date formatting this data is lost.

**Comment by arojoal** [comment]
I would like to know why finally this is not included into Superset. Here you cas read a very good explanation of the importance of this feature for end users.
https://medium.com/geekculture/apache-superset-export-data-to-excel-38b8170a30ee

**Comment by blcksrx** [comment]
Actually Im frustrated about this, I made PRs two time about it, but after a while nobody did pay attention

**Comment by timnick-snow** [comment]
export-data-to-excel

**Comment by niyouzhu** [comment]
we need exporting as excel. it's common.

**Comment by lukoou3** [comment]
we need exporting as excel. it's common.

**Comment by Habeeb556** [comment]
++

**Pull request closed without merging**
