### PR TITLE
chore: bump python version to 3.11 in Dockerfile

### PR DESCRIPTION
**Pull request by tooptoop4**
### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by rusackas** [comment]
Pinging @villebro and @EugeneTorap as I believe you've wrangled with this in the past, and know the perils and pitfalls here better than most :)

**Comment by EugeneTorap** [comment]
Hi @tooptoop4!
We use minimum supported version of python in Dockerfile. It's 3.8 version.
But we can push a docker image with python 3.11 - look at https://github.com/apache/superset/pull/22770 PR how to do it!
@villebro @dpgaspar can we rid 3.8 & 3.9 PY versions of in superset 3.0 and use only 3.10 & 3.11 PY versions? In superset 4.0 we'll rid 3.10 PY version of and will use only 3.11 & 3.12 PY versions. What do you thinks?

**Comment by villebro** [comment]
@EugeneTorap I agree, we should bump to 3.10 as the official version. Would you be up for making the changes?

**Comment by EugeneTorap** [comment]
@villebro Yes, I want to do it!

**Comment by EugeneTorap** [comment]
@mdeshmu We use the minimum supported version of Python! It's Py3.9 because a lot of drivers don't have support Py3.10 & Py3.11 (for example: PyHive don't have support new version of python)

**Comment by mdeshmu** [comment]
I am not changing the default image version which supports 3.9. I just added the ability to create additional images with 3.11 so that we can use it with Superset's code base. 
Talking of database drivers, Many of the drivers we use, do support Py 3.11.  For e.g. pyathena, redshift-connector, pyscopg2 and many more.

**Comment by EugeneTorap** [comment]
@mdeshmu, I agree with you but @sebastianliebscher and me are working on updating the minimum PY version of the superset from 3.9 to 3.10 and use only 3.10 & 3.11 here.

**Comment by mdeshmu** [comment]
I didn't clearly understand what you are saying. 
I saw @sebastianliebscher's [PR](https://github.com/apache/superset/pull/23890) in which he has made python 3.9 as default and added support for 3.10 additional images. 
I have justed extended that work and added support for 3.11 additional images.

**Comment by EugeneTorap** [comment]
@mdeshmu Yes, we will soon have a PR for `Bump to Python3.10` where we only use 3.10 and 3.11 PY for docker images.

**Comment by mdeshmu** [comment]
Would that be in 3.0 ?

**Comment by EugeneTorap** [comment]
If you have a slack account in apache/superset you can join `#server-refactoring` channel and help us to fix PyHive for PY 3.10

**Comment by rusackas** [comment]
@EugeneTorap @villebro @tooptoop4 is this PR still relevant? It looks like we're still on 3.9.

**Comment by mistercrunch** [comment]
Closing this in favor or https://github.com/apache/superset/pull/24112

**Pull request closed without merging**
