### PR TITLE
docs: nvm error while local setup

### PR DESCRIPTION
**Pull request by Abhishek-kumar-ISM**
Did documentation changes, so that people getting similar type of problem while local setup that i got (by following documentation) can easily identify.

### CODE REVIEW

**Comment by Abhishek-kumar-samsung** [comment]
@justinpark @michael-s-molina @villebro @rusackas @eschutho @geido i have added one change to documentation, at the point where nvm install instructions was there (Issue that i was facing while usage so that if anyone else has similar issue can resolve)

Can you please review.

**Review by ved-kashyap-samsung — CHANGES_REQUESTED** [review]
Or you can try this curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash

**Comment by Abhishek-kumar-samsung** [comment]
> Or you can try this curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash

Yes this one is working. Maybe due to version specified in documentation i had error.

But when i used the one that was specified in documentation, it was installing but not loading nvm. Thats why i mentioned if you have used curl command to install nvm but nvm is not loaded and still shows nvm: command not found, then you can use what i mentioned in this PR (to complete nvm installation documentation).

**Review by ved-kashyap-samsung — APPROVED** [review]
Looks good to me

**Review by rusackas — APPROVED** [review]

**Comment by rusackas** [comment]
Approved the PR, and running CI. Nag me if it gets stuck or of I forget to circle back to merge it ;)

**Pull request merged**
