### PR TITLE
perf: Implement Echarts treeshaking

### PR DESCRIPTION
**Pull request by kgabryje**
### SUMMARY
Use [Echarts tree shaking API](https://echarts.apache.org/handbook/en/basics/import/) to shrink the library's bundle size.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Before:

Screenshot 2024-08-06 at 14 08 29

After:

Screenshot 2024-08-06 at 15 59 04

### TESTING INSTRUCTIONS
All Echarts and all features (like legends, data zoom etc) should work as before.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by villebro — APPROVED** [review]
Super nice work, improvements on many levels here! One final thing that comes to mind is maybe adding a linting rule to block direct imports of `echarts`. Other than that LGTM!

**Comment by michael-s-molina** [comment]
KAMIL IS ON FIRE!!! 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥

**Comment by kgabryje** [comment]
> Super nice work, improvements on many levels here! One final thing that comes to mind is maybe adding a linting rule to block direct imports of `echarts`. Other than that LGTM!

Good idea! Let me do that in a separate PR 🙂

**Pull request merged**
