### PR TITLE
[Bugfix/Feature] Fixed slice render staggering on dashboard first load

### PR DESCRIPTION
**Pull request by Mogball**
- Initial dashboard loading set a random delay (usually 0 to 5 seconds) on slice rendering
- Triggering a dashboard refresh by changing filters or clicking "Refresh" did not do this
- If a slice is indicated in `timed_refresh_immune_slices` it will not load upon initial rendering

Refreshing the dashboard now will either stagger or not stagger slice rendering, regardless of how it is triggered, and there is the option to disable this and set the stagger interval (in milliseconds) in the dashboard's JSON Metadata: `{ ...
    "stagger_refresh": false,
    "stagger_time": 15000
}`

Default value is true and 5 seconds. Staggering is also more deterministic.

### CODE REVIEW

**Comment by mistercrunch** [comment]
These 2 new configuration elements (`stagger_refresh`, `stagger_refresh`) need to be documented. Currently the best place for that is `faq.rst`

**Comment by Mogball** [comment]
@mistercrunch Added to docs

**Comment by mistercrunch** [comment]
Wait I didn't realize that there was a `5 * random` sec delay by default on first load. I thought [community contributed] `startPeriodicRender` only applied when auto-refresh mode was on. 

We need to remove that delay on the first load, the idea with the delay was to randomize the subsequent refreshes so that if you set it to refresh every 5 minutes, it won't go all reload at once, it's nicer if the slices go randomly over that period.

Do you want take this on as part of this PR since you're already deep into it?

**Comment by Mogball** [comment]
Alrighty. I'll make changes so that
- Dashboard instantly refreshes: on initial load, when changing dashboard filters, when force refreshing the dashboard
- `stagger_refresh` and `stagger_time` will only affect the periodic refreshing

**Comment by Mogball** [comment]
@mistercrunch Done

**Pull request merged**
