### PR TITLE
fix(capitalization): Capitalizing a button.

### PR DESCRIPTION
**Pull request by rusackas**
### SUMMARY
Capitalizing the `+ Alert` and `+ Report` buttons.

Before:

image

image

After:

image

image

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by mistercrunch — APPROVED** [review]

**Comment by mistercrunch** [comment]
@yousoph asked for an env to test the capitalization

**Comment by kasiazjc** [comment]
@rusackas I think @mistercrunch's test env command didn't work, can you try to do it? 🙏🏻

**Comment by kasiazjc** [comment]
> Hah, I merged it too quickly, sorry... not sure why ephemerals aren't working. I did test it though, as seen in the screenshots.
> 
> There is one remaining inconsistency, but it seemed relatively minor. It asks in one modal "Delete Alert?" or "Delete Report?" now. I can just make it so that these strings aren't reused variables, and just put them in the correct capitalization in the places they go.

Ha, it's on you now @rusackas 🤠

**Comment by rusackas** [comment]
Maybe we're OK, depending on how our capitalization lawyers interpret this:
> Where a product page is titled “Settings”, you refer to this in writing as follows: “Edit your personal information on the Settings page”.

**Pull request merged**
