### PR TITLE
Remove Cypress from package.json

### PR DESCRIPTION
**Pull request by mistercrunch**
I'm building some Docker images these days and realizing just how big
the Cypress package is. Looks like its ~500mb or so.

I prefer adding it as needed only as opposed to having to play tricks as
in `npm ci && rm node_modules/cypress`

### CODE REVIEW

**Comment by kristw** [comment]
This can be problematic to debug cypress tests though as we have no trace or lock of what version we are using.
How much time are you saving with not installing cypress?
or can the command to create docker image add `npm uninstall cypress` to remove before creation?

**Comment by mistercrunch** [comment]
I think this is important. Cypress is a large package and installing/uninstalling a 500mb+ compressed thing is really bad for CI and docker image bloat... 

Let me pin the Cypress version in the install command

**Comment by kristw** [comment]
Let's add a `script` to `package.json`

```
"scripts": {
  "install-cypress": "npm install cypress@3.0.3"
}
```

Then call `npm run install-cypress` from `cypress_build.sh`
This way developers can also call `npm run install-cypress` for running locally with same version.

cc: @michellethomas

**Comment by mistercrunch** [comment]
Good call!

**Comment by kristw** [comment]
Please let me know once you push and I'll approve.

**Comment by mistercrunch** [comment]
@kristw pushed, waiting for CI

**Review by kristw — APPROVED** [review]

**Comment by xtinec** [comment]
@mistercrunch @kristw @michellethomas  I'm cherry-picking this change into `0.31`. Npm removed `bignumber.js 8.1.0` from its registry. In order for the rest of the RCs for `0.31` to deploy, we need to up the version of `bignumber.js`. Given that this PR passed CI, I'm going to go ahead and cherry-pick instead of doing a one-off PR for `0.31` that just up the version of `bignumber`. Any objections?

**Comment by mistercrunch** [comment]
Yeah it appears someone deleted the `8.1.0` version of that lib. The package manager shouldn't allow deletion!

**Comment by hajdbo** [comment]
> Yeah it appears someone deleted the `8.1.0` version of that lib. The package manager shouldn't allow deletion!

bignumber.js 8.1.0 had a breaking syntax error, and should not have been released: 
https://github.com/MikeMcl/bignumber.js/issues/222#issuecomment-466758462

**Pull request merged**
