### PR TITLE
chore: write access request for jwilliams-ocient

### PR DESCRIPTION
**Pull request by jwilliams-ocient**
### SUMMARY

I'm currently working on #22812 and am requesting write access to kick off CI runs without bugging the superset team 🙃 .

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by rusackas — APPROVED** [review]

**Comment by rusackas** [comment]
Interesting approach :) 

We can't grant write access to the repo. Only Apache does that once you've been voted in as a committer. 

I just re-ran the failing E2E tests on your PR to see if it passes this time, so hopefully we can merge that shortly. Nag me here or on Slack if it needs to be kicked again.

I'd rather merge that PR than clutter the changelog with this (or who knows how many others who use the same technique). Either way, you should be free of that approval burden once your first PR merges.

**Comment by jwilliams-ocient** [comment]
Thanks @rusackas! I went ahead and read the _very thorough_ contribution guidelines (duh!) which clearly outline how to run the pre-commit checks locally. They pass on my end, hoping we're ready to ship after the next CI run. 🤞🏾 

Apologies for the context switch, and thanks for your time!

**Comment by jwilliams-ocient** [comment]
I'll go ahead and close this PR and ping you directly on #22812 if the next CI run fails 🙃

**Comment by rusackas** [comment]
Sorry for the flaky test headaches... There's a lot of effort ahead on that front. Thanks again for the contribution - it's merged!!

**Pull request closed without merging**
