### PR TITLE
feat: Keep searching result

### PR DESCRIPTION
**Pull request by puridach-w**
### SUMMARY
The feature change involves retaining search filter results across SQL Lab tabs by integrating search text into the Redux state.

Under the previous system, users would encounter the resetting of their search results each time they switched to a different SQL Lab tab and back. This process required users to repeatedly enter their search filters, resulting in a disrupted workflow.

This enhancement directly tackles this inconvenience. Upon rendering SQL Lab, it now utilizes the search text stored in Redux state as the filter value. This ensures that no matter how many tabs a user switches between, the search filter results remain persistent, no longer disappearing upon tab switching.

### BEFORE SCREENSHOTS OR ANIMATED GIF
https://github.com/apache/superset/assets/76474644/79a9d872-87c3-49d9-9e9e-01b958c4f86c

### AFTER SCREENSHOTS OR ANIMATED GIF
https://github.com/apache/superset/assets/76474644/801704af-a891-4405-8749-1064a0980210

### TESTING INSTRUCTIONS
- Navigate to the SQLLab page
- Execute Query
- Apply a filter on the resulting output table using the search box
- Navigate to other  SQL editor tab
- Return to the initial SQL editor tab
- Notice that the previously input search text and filter results are still visible

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by michael-s-molina** [comment]
Hi @puridach-w. Thank you for PR. I'm not sure why the table is re-rendered when you switch tabs but that could be a problem for this feature given that it won't be intuitive for users that the results will be filtered after you run the query again.  @justinpark probably has more context why the tabs need to be re-rendered. If the tab was not re-rendered, then maintaining the search state would totally make sense (actually that's what I would expect when switching tabs).

**Comment by puridach-w** [comment]
Video:  https://github.com/apache/superset/assets/76474644/780415d6-a42f-4187-81de-02a5c8d89a75
Actually, after switching back to the original tab, it automatically fetches the result table, as shown in the provided video.

**Comment by puridach-w** [comment]
Could you clarify more? I'm not quite sure what you're meaning or what the next steps should be.

**Comment by john-bodley** [comment]
cc @gaurav7261

**Comment by justinpark** [comment]
> Could you clarify more? I'm not quite sure what you're meaning or what the next steps should be.

This issue wasn't intended and will be fixed (without your PR) once this [PR](https://github.com/apache/superset/pull/26156) is merged.

**Comment by puridach-w** [comment]
> > Could you clarify more? I'm not quite sure what you're meaning or what the next steps should be.
> 
> This issue wasn't intended and will be fixed (without your PR) once this [PR](https://github.com/apache/superset/pull/26156) is merged.

I've noticed that the issue was resolved following the merge of the PR you mentioned, so I'll close this PR.

**Pull request closed without merging**
