### PR TITLE
Remove Extra Margin in SQL Lab

### PR DESCRIPTION
**Pull request by SalehHindi**
Address #2901.
Removes extraneous whitespace from SQL lab by adding CSS to `superset.css` that removes the extra margin at the bottom of the form.

I see that there are some extra commits that got pushed to my remote branch. I kept trying squash all the commits into one commit to keep the code clean but I am having absolutely no luck. Do you care or should I take the time to squash the commits?

Thanks!

### CODE REVIEW

**Comment by xrmx** [comment]
Any chance you can rebase your branch on top of master? 21 commits for a single of line of css looks a bit exaggerated :)

**Comment by SalehHindi** [comment]
Of course : ) I just posed the question on Stackoverflow and I am experimenting with how to properly do this.

**Comment by xrmx** [comment]
To rebase your branch on top of master you have to do these steps:

```
git checkout master
# assuming origin is this repo not yours
git pull origin master
git checkout <yourbranch>
git rebase master
# this will replace whatever you have on your remote branch so be sure you are not losing work :)
git push -f yourfork yourbranch
```

Once you have a PR, no need to create a new, just update the branch.

**Comment by SalehHindi** [comment]
@xrmx I decided to reset my master to airbnb/master, checkout a new branch,  redo the changes, and make a new pull request. It looks like there was some funkiness with a botched merge I made earlier. Thanks for the help!

**Pull request closed without merging**
