### PR TITLE
fix(websocket): add error handling

### PR DESCRIPTION
**Pull request by harshit2283**
### SUMMARY

Adding Error handling in websocket to avoid crashing whole service due to a faulty socket etc

Certain Browsers (i.e Safari) don't play nicely with WS Protocol, they can end up crashing the whole service. [ref](https://github.com/websockets/ws/issues/1354#issuecomment-1288007531)

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by villebro — APPROVED** [review]
LGTM, thanks for the fix!

**Comment by villebro** [comment]
@harshit2283 it seems there's a linting error. Can you fix it so we can get this merged?

**Comment by harshit2283** [comment]
> @harshit2283 it seems there's a linting error. Can you fix it so we can get this merged?

Have fixed it.

**Comment by villebro** [comment]
btw @harshit2283 as you appear to be using GAQ with websockets, it would be valuable to get your feedback on a recent proposal to simplify the GAQ architecture: #29515

**Comment by harshit2283** [comment]
@villebro Sure, I will check it out. Thank you!

**Pull request merged**
