### PR TITLE
fix: using lazy_gettext instead of gettext

### LINKED ISSUE #20060: Missing French Translation
Issues to add french translation missing

Step : 

- [ ]  The additional French translations
- [ ] Fixing the untranslated strings
- [ ] using gettext instead of lazy_gettext
- [ ] translate variable
- [ ] translate changed_on_delta_humanized

### PR DESCRIPTION
**Pull request by aehanno**
### SUMMARY
using gettext instead of lazy_gettext

### ADDITIONAL INFORMATION
Fixes https://github.com/apache/superset/issues/20060

### CODE REVIEW

**Comment by aehanno** [comment]
@villebro, PR you ask me to create from an other one

**Review by villebro — CHANGES_REQUESTED** [review]
One of the tests is failing due to the `_LazyString` object not being JSON serializable. Check out this stackoverflow post on how to address this:  https://stackoverflow.com/questions/26124581/flask-json-serializable-error-because-of-flask-babel

**Comment by rusackas** [comment]
@aehanno  is there any intent to follow through on this, or shall we close it out?

**Comment by john-bodley** [comment]
@villebro is this somewhat related to the issue we discussed yesterday?

**Comment by aehanno** [comment]
> @aehanno is there any intent to follow through on this, or shall we close it out?

Hey ! Yes, but I was wating to know if my correction it's okay before doing another rebase

**Comment by rusackas** [comment]
> > @aehanno is there any intent to follow through on this, or shall we close it out?
> 
> Hey ! Yes, but I was wating to know if my correction it's okay before doing another rebase

Oh no! That went under my radar for FAR too long. I don't think there's any objection to the PR if you want to rebase it. (@villebro can correct me if I'm wrong, of course).

**Pull request closed without merging**
