### PR TITLE
overlap of Legends with the ToolTip 

### PR DESCRIPTION
**Pull request by shyam2794**
In the Time Series bar chart , there is a overlap of Legend with the Tool Tip . So just added the chart.legend,margin property in the Code .

### CODE REVIEW

**Comment by mistercrunch** [comment]
you PR is empty. Can you screenshot the before/after?

**Comment by shyam2794** [comment]
@mistercrunch 
Before the change - superset/assests/visualisation/nvd3.vis

screenshot from 2017-11-16 12-44-11

After the change - superset/assests/visualisation/nvd3.vis

screenshot from 2017-11-16 12-43-33

**Comment by mistercrunch** [comment]
Sorry I meant of snapshot of what the visualization looks like not the code.

**Comment by shyam2794** [comment]
@mistercrunch . Sorry for not replying soon . Here it goes , 

The Datalabels used to collide with the legends Like below

screenshot from 2017-10-23 20-47-08

But there should be a spacing between the legend and the data labels .Something like this 

screenshot from 2017-11-24 14-48-24

**Pull request closed without merging**
