### PR TITLE
feat(db_engine_specs): added support for Denodo Virtual DataPort (Superset 4.0 branch)

### PR DESCRIPTION
**Pull request by denodo-research-labs**
### SUMMARY

Following up on #20656, this PR adds basic support for connecting to Denodo Virtual DataPort (aka VDP Server) from Superset 4.0.x.

This includes:

- A Denodo DB Engine Spec (in `superset/db_engine_specs/denodo.py`).
- Version configuration for the [companion SQLAlchemy dialect](https://pypi.org/project/denodo-sqlalchemy/) (in `setup.py`).
- Changes to the documentation in order to mention the new support (in `docs/docs/databases/*`).

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [x] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by villebro — APPROVED** [review]
Code LGTM, cool to see yet another new db engine! owever I'm curious if we really need to rejig those `sidebar_position` entries every time we add a new entry that's not at the end of the list? @rusackas do you know?

**Comment by villebro** [comment]
@denodo-research-labs please check the failing CI checks (probably minor linting issues)

**Review by michael-s-molina — CHANGES_REQUESTED** [review]
@denodo-research-labs Thanks for your contribution. Would you mind point to `master` instead of `4.0` branch? Otherwise this feature will get dropped in future releases.

Also, 4.0 cannot accept features. It would require a minor release such as 4.1, 4.2, etc.

**Comment by denodo-research-labs** [comment]
> Would you mind point to master instead of 4.0 branch? Otherwise this feature will get dropped in future releases.

There are two PRs, we created #29927 for `master`.

**Comment by denodo-research-labs** [comment]
> Also, 4.0 cannot accept features. It would require a minor release such as 4.1, 4.2, etc.

We are now adding modifications to the PR for 4.1 in `master` (#29927). We assume this one for 4.0 should be abandoned, right? In such case, please feel free to close this one when suitable.

**Comment by michael-s-molina** [comment]
> We are now adding modifications to the PR for 4.1 in master (https://github.com/apache/superset/pull/29927).

@denodo-research-labs Ideally, you would only merge this to master and let the release manager determine in which minor version this should be included. For 4.1 release, @sadpandajoe is the release manager.

**Pull request closed without merging**
