### PR TITLE
Renaming files to allow RPM build

### PR DESCRIPTION
**Pull request by SpyderAlba**
I was having issues getting an RPM to build. My error was

Processing files: superset-0.20.1-1.noarch
error: File must begin with "/": Lockup
error: File must begin with "/": With
error: File must begin with "/": Text.svg
error: File must begin with "/": Lockup
error: File must begin with "/": With
error: File must begin with "/": Text@2x.png
error: File must begin with "/": Lockup
error: File must begin with "/": Without
error: File must begin with "/": Text@1x.svg
error: File must begin with "/": Lockup
error: File must begin with "/": Without
error: File must begin with "/": Text@2x.png
error: File must begin with "/": Mark.png
error: File must begin with "/": Mark@1x.svg

for ref pypa/setuptools#767
File renaming fixes this issue

### CODE REVIEW

**Comment by xrmx** [comment]
Do we need these files? Looks like they are not referenced anywhere.

**Comment by xrmx** [comment]
Anyway the error looks like some missing quoting

**Comment by SpyderRivera** [comment]
I don't see them being used. However, when running rpmbuild they cause the issue. I can change to delete them...

**Comment by mistercrunch** [comment]
Happy to merge, those assets are really just in the repo for reference and could live some place else. That reminds me that I should print a bunch of Superset tshirts!

**Pull request merged**
