### PR TITLE
chore: Remove the need for explicit bubble up of certain exceptions

### PR DESCRIPTION
**Pull request by john-bodley**
### SUMMARY

There are instances where we bubble up exceptions, however this is akin to simply not catching it, since any uncaught exception is propagated up the call stack.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by mistercrunch** [comment]
Right. I considered doing the same during https://github.com/apache/superset/pull/29166, but thought there might have some reason for the code to point out the "likely exception" in the code, maybe to allow future handling or something. I decided to leave them as they were since my goal was enabling the lint rule and minimizing the code changes.

**Review by mistercrunch — APPROVED** [review]
Approving as those lines effectively do nothing - except maybe for calling out semantically in the code the exceptions that are likely to happen during the try block.

**Comment by john-bodley** [comment]
@mistercrunch the catalyst for the change is I was rebasing https://github.com/apache/superset/pull/24969 (a longstanding PR I've been wrangling with failing tests for a while).

**Comment by michael-s-molina** [comment]
> thought there might have some reason for the code to point out the "likely exception" in the code, maybe to allow future handling or something.

I think for this case, the best approach is to document the exceptions in docstrings:

```
"""
    Perform some operation.

    Raises:
        ValueError: If the input is invalid.
        FileNotFoundError: If a required file is not found.
        CustomException: If a specific condition is not met.
    """
```

**Review by michael-s-molina — APPROVED** [review]

**Comment by john-bodley** [comment]
@michael-s-molina I addressed your comment.

**Pull request merged**
