### PR TITLE
Add cache support for 'CSV Export' function. This change will get CSV…

### PR DESCRIPTION
**Pull request by smokemonster99**
… results using cache so that user does not need to again wait for the query to complete when exporting results to CSV.

Tested with 0.28.1

### CODE REVIEW

**Comment by smokemonster99** [comment]
Hi, I was hoping to get this merged in...anything else I need to do? This PR significantly speeds up CSV Export by using the cache (instead of performing the query again). Also a small and very contained code change.

**Comment by smokemonster99** [comment]
@mistercrunch can you have a look to see if this can be merged in?

**Comment by theikkila** [comment]
@mistercrunch @smokemonster99 @kristw 
Could you please review this PR

**Comment by villebro** [comment]
This change is largely a copy of the `get_df_payload` method. I believe the following change should be sufficient:
```python
        df = self.get_df_payload().get("df")
```

You can open up a new PR for this.

**Pull request closed without merging**
