### PR TITLE
chore: Cypress dashboard list selectors refactor

### PR DESCRIPTION
**Pull request by adam-stasiak**
### SUMMARY

Replaced class selectors with data-test selectors.
### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by hnle — APPROVED** [review]
Look goods.

**Review by rusackas — APPROVED** [review]
LGTM! Please rebase, and I'll merge if/when CI passes.

**Comment by adam-stasiak** [comment]
@rusackas I had to update this a little bit and it is green now : )

**Comment by RuslanPanin** [comment]
> @rusackas I had to update this a little bit and it is green now : )

Yu best

**Pull request merged**
