### PR TITLE
docs: fix typo in doc

### PR DESCRIPTION
**Pull request by philipqnguyen**
Fix typo, `insode` should be `inside`.

### CODE REVIEW

**Review by mistercrunch — APPROVED** [review]

**Comment by nytai** [comment]
Not sure why some CI checks aren't running. @philipqnguyen would you mind rebasing this PR to see if it triggers some of these checks?

**Comment by mistercrunch** [comment]
@nytai FYI closing/reopening also works, I just triggered it

**Comment by philipqnguyen** [comment]
Some of the CI jobs seems to be stuck even after @mistercrunch closed/reopened it. I went ahead and rebased it, let's see if it works this time.

**Comment by philipqnguyen** [comment]
I made a new branch and new PR with a new commit to see if that can get us past these stuck CI jobs. It is here #11026
So I'm closing this PR.

**Pull request closed without merging**
