### PR TITLE
fix(explore): hide time section for datasets with no time column

### PR DESCRIPTION
**Pull request by ktmud**
### SUMMARY

This could be a somewhat controversial feature, but it doesn't seem to make much sense to display the Time section when the datasource has no time columns available. Shall we hide it for these datasources?

One downside of this is that the granularity and time range will reset to default when users change to a non-timeseries dataset then change it back to a timeseries dataset. The benefit is cleaner UI and less clutters for non-timeseries datasets.

#### Before

energy-use-yes-time

#### After

energy-use-no-time

### TEST PLAN

Manual verification:

1. Open "Explore" in datasets with and without a time column
2. Make sure both cases work

I also added some Cypress tests.

### ADDITIONAL INFORMATION

- [x] Has associated issue: 
- [x] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by srinify** [comment]
Big big +1 from me! In general, I'm a fan of the UI hiding things that aren't relevant to my current context. Few cases to maybe double check (I'm sure you did):

- How does the flow work when a user edits the data model, is the option revealed again?
- Does this clash with dashboard filters at all? Not sure how it would but ya

**Comment by eugeniamz** [comment]
I prefer customers to leave it empty than having it with some datasets and not with others. I think will create confussion

**Comment by ktmud** [comment]
Hi @srinify , here are the answers to your questions:

> * How does the flow work when a user edits the data model, is the option revealed again?

Yes, the Time section will re-appear. However, users will need to check "IS TEMPORAL" in order to select the new time column added:

is-temporal

> * Does this clash with dashboard filters at all? Not sure how it would but ya

Dashboard filters are separate to this. They are unlikely to clash. The same logic of hiding for non-timeseries dataset do apply to the legacy `FilterBox` though.

**Comment by ktmud** [comment]
> I prefer customers to leave it empty than hiding it with some datasets and not with others. I think will create confusion

@eugeniamz wouldn't it be more confusing seeing a time column configuration with empty values on a non-timeseries dataset?

**Comment by ktmud** [comment]
I'm unsure about this change, either. So let's vote.  React to this comment, 👍  for hiding non-relevant Time options,  👎 for always keeping them for consistency.

**Comment by john-bodley** [comment]
Another benefit of hiding the time section if it isn't relevant is time based dashboard filters will no longer apply. This is currently misleading as the dashboard indicator would infer that the filter is being applied yet it has to relevance to the chart.

**Comment by robdiciuccio** [comment]
I would think collapsing it rather than completely removing it from the UI would make this less confusing for users. Removing based on no temporal fields is also relying heavily on the automatic detection or manual identification of these fields, which may be inaccurate or not set correctly. Not displaying the UI at all may lead the user to believe that filtering by time range is not possible at all in a visualization.

**Comment by john-bodley** [comment]
@ktmud maybe this could be a topic for Friday's Apache Superset Contributor Meetup.

**Comment by mihir174** [comment]
+1 from me. I think hiding the time section for when there are no temporal columns makes sense. We shouldn't be providing users an option they cannot act on. 

Re: user confusion- it could be just as confusing for a user to notice a missing `time` section as it is for them to open an empty `time column` dropdown

**Comment by Steejay** [comment]
+1 keeping a field that the user cant edit will just add to the user's cognitive load when scanning the panel to complete tasks. It may confuse and frustrate the user when trying to interact with it.

**Comment by ktmud** [comment]
> I would think collapsing it rather than completely removing it from the UI would make this less confusing for users. Removing based on no temporal fields is also relying heavily on the automatic detection or manual identification of these fields, which may be inaccurate or not set correctly. Not displaying the UI at all may lead the user to believe that filtering by time range is not possible at all in a visualization.

1. Currently users have to select "Is temporal" for a column to appear in the Time Column select. So this inference is at least guaranteed to be consistent with the Time column choices.
2. If the Time column choice is empty, then filter by time range is indeed impossible for the specific chart, right?

**Comment by robdiciuccio** [comment]
> Currently users have to select "Is temporal" for a column to appear in the Time Column select. So this inference is at least guaranteed to be consistent with the Time column choices.

The "is temporal" option is automatically checked for certain column types when creating a dataset, so many users are likely unaware of these column settings. My main point was, if this column type auto-detection fails for whatever reason, the time filter options will be fully hidden from the user, even though there may be a viable temporal column that just needs to be manually configured.

> If the Time column choice is empty, then filtering by time range is indeed impossible for the specific chart, right?

Yes, we display a "No options" message in the filter column selector. Perhaps the existing time filter UI could be replaced in this case with a message (only visible upon toggling the filter open) saying "there are no temporal columns configured for this dataset, click here to add one."

**Comment by ktmud** [comment]
> > Currently users have to select "Is temporal" for a column to appear in the Time Column select. So this inference is at least guaranteed to be consistent with the Time column choices.
> 
> The "is temporal" option is automatically checked for certain column types when creating a dataset, so many users are likely unaware of these column settings. My main point was, if this column type auto-detection fails for whatever reason, the time filter options will be fully hidden from the user, even though there may be a viable temporal column that just needs to be manually configured.
> 
> > If the Time column choice is empty, then filtering by time range is indeed impossible for the specific chart, right?
> 
> Yes, we display a "No options" message in the filter column selector. Perhaps the existing time filter UI could be replaced in this case with a message (only visible upon toggling the filter open) saying "there are no temporal columns configured for this dataset, click here to add one."

@robdiciuccio  I got what you mean now. I think those are valid concerns. I wonder if we can improve our inference during dataset creation or column syncing to make sure it's less likely to fail, or add some inline reminders in the Datasource editor, but prompting users to add temporal columns sounds like a good solution, too.

Either way, would you say hiding it is better or worse than status quo (an empty select and a time range filter with no effect)?

**Comment by graceguo-supercat** [comment]
I had same concern as @robdiciuccio  said. I feel `hide` time section is worse, but disable it will be a good indicator for `not available for interaction`.

**Comment by rusackas** [comment]
Late to the party, but I want to echo a few sentiments:

> ... is relying heavily on the automatic detection or manual identification of these fields

This concern immediately popped into my head. We should audit and/or add unit tests as needed to make that bulletproof for every format of temporal data we intend to support.
 
Additionally, I would prefer there to be _something_ in place of just hiding controls. In agreement that an action to "add or assign temporal columns" would be hugely valuable. 

If, hoever, adding that link/flow merits a separate PR or design cycle, we could show the temporal controls header and include a "no temporal columns available" message to at least _indicate_ that this functionality is available for this chart type. A tooltip there explaining the user's options to add the column would get us even closer in terms of usability.

**Comment by john-bodley** [comment]
I still don’t really see much value in showing UI elements (even if they’re disable) which take up pristine real estate if the datasource does not support temporal functionality.

My arm could be twisted in terms of an indication to the user (via a link in a condensed form the the component) as to how one could declare a column as being temporal.

Furthermore we should likely extend this logic to filterable/groupable columns. If these don’t exist for the datasource there is limited value in showing the associated controls if they’re unusable.

The one caveat (covering my arse) is I’m uncertain what the end state is for the explorer redesign with the left-hand-panel and proposed drag-and-drop functionality, but I speculate the above logic will still hold, i.e., why show a component where the drop target will never be eligible.

**Comment by ktmud** [comment]
In terms of end state, I remember being confused by why does every chart has to have a Time control section when I first used Superset. It's just strange to just treat every query as timeseries by default.

I've imagined a future where the time column is defined as just another type of calculated column---this is much more intuitive and could support advanced features such as applying multiple time dimension to a chart---you can filter by one, then plot by another.

I understand how it could be confusing when users sometimes see the time section sometimes don't, but this is already when the switch between viz types. With proper documentation and education, I think it's quite easy to pick up the idea that the a dataset needs to have a temporal column AND a viz type needs to support timeseries in order to have the Time controls.

**Comment by junlincc** [comment]
Running a poll in slack #general, so far 11 responses, 100% agreed with hiding time section for datasets with no time column. 
81.8% It's confusing - I should only see a set of control that's relevant to my dataset and selected viz type.
18.2% It's confusing - when I see an empty select dropdown in time column, I perceive it as a bug.
all answers came randomly from the community. 

Screen Shot 2021-02-04 at 3 40 39 PM

This move is aligned with our long-term product vision in Explore.  It does seem risky in the short term, as automatic detection may not be able to catch columns correctly each time, but I would prefer to expose edge cases in early time.
Also with the left data panel that lists all columns along with a data type icon, users can easily verify whether not seeing the time section is a bug or not. 

Screen Shot 2021-02-04 at 3 55 41 PM

**Comment by nytai** [comment]
I largely agree with @ktmud's sentiments. I never quite understood why superset doesn't treat time just like any other calculated dimension or filter. I suspect it's due to time series datasets always being quite large and there's a high probably of users hosing the client. It could also be due to superset's early focus on time series data. It's a +1 from me for making superset a more general purpose data visualization tool with dimensions, metrics and filters as the core building blocks. 

However, change management is important and this is a significant change that's likely to cause existing users to think it's a bug. We should find a way to gently transition to the ideal end state. I think having good docs and an FAQ section could be sufficient. Adding dismissable tooltips to explore to communicate the recent changes could also work.

**Comment by junlincc** [comment]
Screen Shot 2021-02-15 at 3 51 07 PM

**Review by villebro — APPROVED** [review]
Based on the user feedback this seems to be the right course of action for now.

**Review by junlincc — APPROVED** [review]
Approving as product/design sign-off.

This change is aligned with all up coming UI/UX changes in Explore, including control panel UI redesign, Explore dynamic controls, drag and drop control. It is a good small step forward, and is backed by user research. A few projects are undergoing to address the concerns in this PRs - 
1. general effort around adding unit and e2e test 
2. Improve datatype inference ability 
3. manual testing plan using a certified test dataset with multiple different time format columns. 

From product's standpoint, I don't see any reasons to hold off. @ktmud @villebro please merge if you feel ready. (up to you)

**Comment by ktmud** [comment]
Hi, @villebro @junlincc, I think from last Superset meetup when we discussed this issue, the consensus was fold the Time column and add an explaining text instead of completely remove it.

We'll think about strategies to blend the Time section into other controls (filter, column select) once bigger redesign with filters are starting to taking shape.

**Comment by ktmud** [comment]
I'll start working on the folding and help text when I finish my other work at hand. Thanks!

**Comment by junlincc** [comment]
> the consensus was fold the Time column and add an explaining text instead of completely remove it.

I am really not sure if this is necessary. we try to change UI too often, that's gonna confuse user. can just leave it as it.

**Comment by ktmud** [comment]
No time to work on this. Hopefully someone else will pick it up.

**Comment by villebro** [comment]
Closing this, as this has been implemented already.

**Pull request closed without merging**
