### PR TITLE
[WIP] feat: Set dataset name

### PR DESCRIPTION
**Pull request by mayurnewase**
### SUMMARY

Add a name to the dataset instead of using table name.
Helps distinguish if multiple datasets have the same table name, described in #14246 

TODO
* Name is optional,and if not set while adding dataset set to table_name by default.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

For before shots check above issue linked.

After
image

image

image

Screenshot from 2021-04-28 20-06-36

### TEST PLAN

Test adding dataset
Test editing dataset
Test exploring chart on dataset
Test migration

### ADDITIONAL INFORMATION

- [x] Has associated issue:
- [x] Changes UI
- [x] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by etr2460** [comment]
Looks like you'll need to write a db migration for this too, and might want to merge that pr in first so the change is backwards/forwards compatible

**Comment by zhaoyongjie** [comment]
There is no unique constraint on the SqlaTable table, so why do we need to introduce the dataset name?

https://github.com/apache/superset/blob/1c1626165124ec3a17acf79b1558d86d206d7466/superset/connectors/sqla/models.py#L451-L470

**Comment by mayurnewase** [comment]
> There is no unique constraint on the SqlaTable table, so why do we need to introduce the dataset name?
> 
> https://github.com/apache/superset/blob/1c1626165124ec3a17acf79b1558d86d206d7466/superset/connectors/sqla/models.py#L451-L470

You mean to use `table_name` to save dataset_name?

**Comment by mayurnewase** [comment]
> There is no unique constraint on the SqlaTable table, so why do we need to introduce the dataset name?
> 
> https://github.com/apache/superset/blob/1c1626165124ec3a17acf79b1558d86d206d7466/superset/connectors/sqla/models.py#L451-L470

I think having dataset name makes more sense given database now also has seperate name.

**Comment by betodealmeida** [comment]
> There is no unique constraint on the SqlaTable table, so why do we need to introduce the dataset name?

```
    __table_args__ = (UniqueConstraint("database_id", "table_name"),)
```

**Comment by rumbin** [comment]
> > There is no unique constraint on the SqlaTable table, so why do we need to introduce the dataset name?
> 
> ```
>     __table_args__ = (UniqueConstraint("database_id", "table_name"),)
> ```

Wouldn't it be useful to have the schema included in this constraint? In most cases it is only the fully qualified db.schema.table name that really is unique by definition.
The proposed approach of having a custom unique dataset name serves the same purpose, though.

**Comment by betodealmeida** [comment]
> Wouldn't it be useful to have the schema included in this constraint? In most cases it is only the fully qualified db.schema.table name that really is unique by definition.

Right, and eventually I'd like to see us supporting catalogs as well. Presto's hierarchy is `catalog.schema.table`.

> The proposed approach of having a custom unique dataset name serves the same purpose, though.

For sure! Specially with Google spreadsheets, that when added have the full URL as the name. This is definitely a step in the right direction!

I'm writing a SIP (Superset Improvement Proposal) about datasets, proposing the creation of a separate model for tables and datasets, instead of having a single `SqlaTable` model. It's nice to see that some of the ideas I want to propose are needed. :)

**Comment by mayurnewase** [comment]
> > Wouldn't it be useful to have the schema included in this constraint? In most cases it is only the fully qualified db.schema.table name that really is unique by definition.
> 
> Right, and eventually I'd like to see us supporting catalogs as well. Presto's hierarchy is `catalog.schema.table`.
> 
> > The proposed approach of having a custom unique dataset name serves the same purpose, though.
> 
> For sure! Specially with Google spreadsheets, that when added have the full URL as the name. This is definitely a step in the right direction!
> 
> I'm writing a SIP (Superset Improvement Proposal) about datasets, proposing the creation of a separate model for tables and datasets, instead of having a single `SqlaTable` model. It's nice to see that some of the ideas I want to propose are needed. :)

@betodealmeida So should I complete this or not?

**Comment by rumbin** [comment]
> I'm writing a SIP (Superset Improvement Proposal) about datasets, proposing the creation of a separate model for tables and datasets, instead of having a single `SqlaTable` model. It's nice to see that some of the ideas I want to propose are needed. :)

Definitely! In my understanding the Presto catalogs seem to be somewhat similar to Snowflake's multiple databases in a single Snowflake account. And this is exactly our use case:
Ideally, we would simply define the Snowflake connection once, have the connection mutator adjust to the user's role and provide access to all visible databases of the Snowflake account this way.
Since a user can join tables from multiple Snowflake DBs, it is not quite useful to distinguish them on a connection level. This would also have to be reflected in the schema browser in SQLLab, though. Only one of the Snowflake DBs can be browsed here at a time and the user needs to decide which one to use....
I would be grateful if you could include these considerations in your SIP, @betodealmeida. If you like, we can discuss things together and I can contribute my thoughts.

**Comment by betodealmeida** [comment]
> @betodealmeida So should I wait for your SIP, or complete and clean this up?

I'm going to have the SIP out next week, and I estimate that it would take another month to discuss it and implement the new `Dataset` model. If that timeframe is ok for you I'd recommend waiting, but if you need this urgently maybe go ahead?

**Comment by mayurnewase** [comment]
> > @betodealmeida So should I wait for your SIP, or complete and clean this up?
> 
> I'm going to have the SIP out next week, and I estimate that it would take another month to discuss it and implement the new `Dataset` model. If that timeframe is ok for you I'd recommend waiting, but if you need this urgently maybe go ahead?

No urgency, will wait for it.

**Pull request closed without merging**
