### PR TITLE
fix(webpack-dev-server): parse env args

### LINKED ISSUE #19743: webpack-cli throws 'Unknown option' error when using --superset arg
#### How to reproduce the bug

1. execute the example command from - 
https://github.com/apache/superset/blob/master/CONTRIBUTING.md#webpack-dev-server  

```bash
npm run dev-server -- --superset=https://my-superset
```

### Expected results

Webpack dev server should proxy to the remote superset backend.  

### Actual results
Error is thrown -  
`[webpack-cli] Error: Unknown option '--superset=https://my-superset'`

### Environment

- browser type and version: Chrome [NA]
- superset version: `master`
- python version: `3.9.10`
- node.js version: `v16.14.2`
- any feature flags active: none

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by jdbranham**
### SUMMARY
The `--superset` arg is rejected by webpack because it's not well known.  

This PR updates the documentation and changes the flag to use the `--env` arg as a way to override the backend superset environment when running the `webpack-dev-server`.   

### TESTING INSTRUCTIONS
From the `superset-frontend` directory, run the command to use a remote superset backend.  

```bash
npm run dev-server -- --env=--superset=https://my-superset-backend
```

### ADDITIONAL INFORMATION  
- [x] Has associated issue: Fixes #19743 
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by vivostar** [comment]
+1, the patch work well on my local dev environment

**Comment by TacoBel42** [comment]
that solved connection problem, thx!

**Comment by rusackas** [comment]
Sorry this never got a review somehow. Adding a few folks to review/test this. I'm also closing/reopening to kick-start CI, and see if we can get this thing across the finish line.

**Review by rusackas — APPROVED** [review]
LGTM!

**Pull request merged**
