### PR TITLE
Add Apache Rat for license checks

### PR DESCRIPTION
**Pull request by bolkedebruin**
This adds Apache Rat license checks to the build matrix. 

It sets a count and saves this in the caching directory. The count cannot go up higher otherwise PRs will fail. To move it a little bit faster you could subtract an arbitrary number to force contributors to add extra headers.

@mistercrunch

### CODE REVIEW

**Comment by bolkedebruin** [comment]
@mistercrunch I suggest using Rat as it removes the maintenance burden on maintaining rodent. I couldn’t find rodent in the tree either ;-)

**Comment by mistercrunch** [comment]
The issue I had with RAT is it wouldn't deal with py and js/jsx files in a way that our linters liked, and there was lots of files to touchup... rodent is a very small app (haven't pushed it to pypi), but could become an alternative to RAT.

Also it wasn't aware of my .gitignore, but I see you took care of this here with a rat-ignore...

**Comment by bolkedebruin** [comment]
I don’t follow entirely? The way RAT is used in this case is to verify if a compliant license is present. What would be the deal with the py files? Or were you trying to have RAT add the headers? That I didnt like either and for Airflow I ended up writing a small script to do it.

**Comment by mistercrunch** [comment]
Right, I wanted a tool to add the headers to all my files py/js/jsx/ts files in a linter friendly way (from memory, shebangs and future import have to be before the license I think). Writing rodent took little time, probably much less than editing all the files and maybe less work than it would take for me to get RAT to do this.

Also wanted for the devs to not have to install JDK to run these checks or auto-add licences locally if they want to.

I'm curious to see whether RAT will be ok with the way rodent crafted the licenses too....

**Comment by bolkedebruin** [comment]
Gotcha. Why not merge it now and see how it behaves? Most developers will have a java installed somewhere. We can always toss it out again as it is not that invasive. 

She bangs yes, future imports no: 
https://docs.python.org/2/reference/simple_stmts.html#future

Also most ides (vi etc included) you can setup just to add the license header for you if creating new files.

**Comment by bolkedebruin** [comment]
Just checked rodent, seems simple indeed but it will miss a lot of files while checking (svg, md, sh, ...). Of course fixable but do you really want to go down that rabbit hole (oh yes I was just waiting to be able to make that comment 😂😂😂😂)

**Comment by bolkedebruin** [comment]
@mistercrunch ping. Quite some new files have been added since #5800 and they are all missing license headers.

**Comment by mistercrunch** [comment]
@bolkedebruin looks like storing the license number in the cache is flawed based on what's happening on `master` and PRs that forked that broken master. 

Can we think of a more deterministic approach? Perhaps checking-in a list of file names that we know are lacking license?

**Comment by bolkedebruin** [comment]
This only happens for old PRs that have not been rebased against master. This allows you to merge a PR that fails the license check. 

What you suggest (keeping a list) defeats the purpose: the list is not fixed, people add new files all the time. 

The way to fix it is just to add a PR that adds a lot of license headers to files. Yes slightly annoying, but in the end you want to move the count down. Adding a license header is just a copy paste. Superset has over 2000 license headers missing so there is some.work to do :-)

**Comment by mistercrunch** [comment]
So to be clear about the approach, the number we're caching (that fails if it goes up) is the number of files that don't have a license header?

**Comment by bolkedebruin** [comment]
Yes absolutely

**Pull request merged**
