### PR TITLE
feat: make CTA text in Alerts & Reports mails configurable

### PR DESCRIPTION
**Pull request by cemremengu**
### SUMMARY

This PR makes call-to-action link text used in Alerts & Reports emails configurable

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by rusackas — APPROVED** [review]
Looks pretty straightforward to me, so I'll approve... just pointing out the risk that if someone actually changes that value in their config, the translations will not likely exist.

**Comment by rusackas** [comment]
Closing/reopening to kick-start CI. Sorry this fell between the couch cushions for so long! Please feel free to nag us more here or on Slack if this happens again! Thank you!

**Comment by cemremengu** [comment]
@rusackas no worries, repo is busy like a bee hive already so don't want to ping much. Thanks for your hardwork!

**Comment by cemremengu** [comment]
@rusackas no worries, repo is busy like a bee hive already so don't want to ping much. Thanks for your hardwork!

**Pull request merged**
