### PR TITLE
docs: add VLMedia to users list

### PR DESCRIPTION
**Pull request by iercan**
VLMedia added to user list

### CODE REVIEW

**Review by villebro — COMMENTED** [review]
Thanks for the contribution! Would you mind adding your GitHub alias next to the link (see e.g. `komoot` above).

**Comment by ibotheperfect** [comment]
> Thanks for the contribution! Would you mind adding your GitHub alias next to the link (see e.g. `komoot` above).

done

**Review by villebro — APPROVED** [review]
LGTM; will merge once CI passes.

**Review by mistercrunch — APPROVED** [review]

**Comment by mistercrunch** [comment]
Welcome aboard!

**Pull request merged**
