### PR TITLE
chore: Select component refactoring - ColorSchemeControl - Iteration 5

### PR DESCRIPTION
**Pull request by geido**
### SUMMARY
It replaces the react-select Select component with the Antdesign one in the ColorSchemeControl component.

### BEFORE
https://user-images.githubusercontent.com/60598000/124637377-f6f3f100-de89-11eb-835f-7be93edb5d68.mp4

### AFTER
https://user-images.githubusercontent.com/60598000/124637400-0115ef80-de8a-11eb-93ec-3deec4e1f265.mp4

### TESTING INSTRUCTIONS
1. Open a chart, for instance, the _Cross Channel Relationship_ example chart
2. Click on the "Customize" tab
3. Observe the COLOR SCHEME Select
4. Select a different color scheme and observe the behavior

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by geido** [comment]
@junlincc @rusackas @adam-stasiak

**Review by michael-s-molina — APPROVED** [review]
The code looks good. Just need to fix the Cypress test.

**Review by rusackas — APPROVED** [review]
LGTM as well, and the ephemeral env is lookin' good!

**Pull request merged**
