### PR TITLE
feat(Handlebars): formatNumber and group helpers

### PR DESCRIPTION
**Pull request by Vitor-Avila**
### SUMMARY
This PR adds two new helpers to the Handlebars chart:
* `formatNumber`: allows using `number.toLocaleString(locale)` to format numbers as needed.
* `group` (via the [handlebars-group-by module](https://github.com/shannonmoeller/handlebars-group-by)): Allows grouping data.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Example using both helpers:
image

### TESTING INSTRUCTIONS
1. Create a Handlebars chart using the `cleaned_sales_data` dataset.
2. Use `year` and `deal_size` as dimensions and create any metric with the `test_metric` label.
3. Use below Handlebars template:
```
{{#group data by="year"}}
<h3>Year: {{ value }}</h3>
<ul>
{{#each items}}
	<li>{{ deal_size }} deals: {{ formatNumber test_metric "de-DE"}}</li>
{{/each}}
</ul>
{{/group}}
```

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by kgabryje — APPROVED** [review]
LGTM

**Comment by jediwarpraptor** [comment]
This is phenomenal @Vitor-Avila - HUGE!  🎉 🚀 💜

**Review by rusackas — APPROVED** [review]
Love it! 
• _Could_ add a test, but it would be a pretty low-likelihood-to-fail test since it would just test that JS does JS stuff.
• We're low on docs for this thing, but this is a reminder that we could really use some, and I'd say we should update them if we had them at all.

**Comment by Vitor-Avila** [comment]
@rusackas 100% agreed. I just took a look at https://superset.apache.org/docs/using-superset/exploring-data, and we don't have a section for Handlebars just yet. I'll see if I can work on a follow up PR covering docs (and perhaps testing).

**Comment by muralikrishnaIrakam** [comment]
i created handlebar with href(another dashboard) working but , i didnt get filtered data ( how to pass the filters )

**Pull request merged**
