### PR TITLE
chore: Enable suppressing default chart context menu

### PR DESCRIPTION
**Pull request by kgabryje**
### SUMMARY
Add a config option to chart metadata to allow suppressing the default chart context menu on the dashboard (the one with the default cross filter and drill to detail menu items)

### TESTING INSTRUCTIONS
1. Tests should pass
2. The dashboard context menu should work like before

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by michael-s-molina** [comment]
@kgabryje Can you explain a little bit more about the intention of this PR? Currently, disabled options are greyed out by default but you're trying to completely suppress the menu, which might lead to users asking why right click is not working. Could you explain what's the use case you're trying to solve?

**Comment by kgabryje** [comment]
> @kgabryje Can you explain a little bit more about the intention of this PR? Currently, disabled options are greyed out by default but you're trying to completely suppress the menu, which might lead to users asking why right click is not working. Could you explain what's the use case you're trying to solve?

The intention is so that a viz plugin can define it's own, fully custom context menu. For example, the viz plugin could have a context menu with more actions, specific to this plugin.
This option is not intended to be used with any of our currently existing plugins

**Comment by michael-s-molina** [comment]
> This option is not intended to be used with any of our currently existing plugins

I recommend adding a comment to the property explaining the use as it can be easily removed. This also raises the question if this shouldn't be an extension to be more explicit?

**Comment by kgabryje** [comment]
@michael-s-molina Added a comment. I believe this change fits in Superset - for instance, it would be useful if in the future we wanted to improve the table viz plugin by adding more table-related actions to the context menu. Currently it's not possible as we are limited by the context menu defined in ChartRenderer which is the same for every plugin.

**Review by michael-s-molina — APPROVED** [review]

**Pull request merged**
