### PR TITLE
fix(dashboard): fixed FullSize charts broken #13600

### PR DESCRIPTION
**Pull request by toop**
When you click the “Maximize chart”  option of the chart in the dashboard, the chart is incomplete。
### BEFORE：
image
### AFTER：
image

### ADDITIONAL INFORMATION

- [x] Has associated issue:
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [x] Migration is atomic, supports rollback & is backwards-compatible
  - [x] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API
@junlincc

### CODE REVIEW

**Comment by junlincc** [comment]
Hi @toop thank you so much for your contribution! 

To help us better review and testing your PR, could you add 2-3 sentences description and BEFORE vs AFTER screenshot? 
Also please get the checks passed. Thanks!

**Comment by junlincc** [comment]
Tested locally, Pie, World map and Bar that reported broken previously are fixed. 🙏
The only thing I'm seeing thats abnormal is the backward button causes page crash. I don't think that's related to this PR. 
so LGTM. 

@ktmud Jesse, can you help take a look at the code? thanks

**Comment by zhaoyongjie** [comment]
@toop 
please rebase the master branch and then force push to your owner repo branch, so that I can view your changes.

**Comment by toop** [comment]
It's done。 @zhaoyongjie

**Comment by toop** [comment]
It's done。 @zhaoyongjie

**Comment by zhaoyongjie** [comment]
@toop, Your PR contains other PR changset, please push this change relevant code only.

**Pull request closed without merging**
