### PR TITLE
chore: add cypress required checks for branch protection

### PR DESCRIPTION
**Pull request by eschutho**
### SUMMARY
Continuation of #12921, https://github.com/apache/superset/pull/12928 and https://github.com/apache/superset/pull/12969 , this PR adds more required github checks. 

### TEST PLAN
verify that the correct tests are required after this is merged. If this yml file doesn't match correctly, we will need to rename the checks so that they match or open an infra ticket to Apache to update it.
### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by eschutho** [comment]
@ktmud I'm queuing up the remaining checks to rebase when the other PRs are merged and then put up for review.

**Comment by eschutho** [comment]
@ktmud this is the last batch of the previously required checks. Is there anything else we want to add? I noticed there are some 3.8 matrix db tests for example.

**Comment by ktmud** [comment]
Yeah, I think it makes sense to add 3.8 checks since we are going to wait for them anyway.

**Comment by eschutho** [comment]
Ok, only postgres of the currently required has a 3.8 matrix.. unless we want to add in presto and hive?

**Comment by ktmud** [comment]
I think it makes sense to keep Hive and Presto optional as they are more difficult to set up. If it somehow starts breaking in `master`, everyone would have to wait for someone with the environment set up to fix it (although docker-compose has made this easy).

I can also see why it's important to make sure master is stable for Presto/Hive, so I'm OK with either way.

**Review by ktmud — APPROVED** [review]

**Comment by eschutho** [comment]
🏷 ready-to-merge

**Comment by eschutho** [comment]
@ktmud I saw that we still have `required_signatures: true` that you requested to be added in the last commit. Is the repo currently set up with that requirement? I can add it in here if you think it's safe.

**Comment by nytai** [comment]
@eschutho we should add that option. It doesn't really matter since github will add the signatures anyway if merging is happening via the UI (currently that's the only way to merge), but it will likely appease some of the apache infra 👀

**Pull request merged**
