### PR TITLE
feat: support complex types and use get_columns implementation of starrrocks python client

### PR DESCRIPTION
**Pull request by miomiocat**
### SUMMARY

1. support complex types:
- largeint
- json
- percentile
- hll
- bitmap
2. remove `get_columns` from db_spec to use the dialect's implementation of starrocks own python client
3. update logo image

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by rusackas** [comment]
Looks reasonable to me, but deferring to @john-bodley @betodealmeida and @villebro who will be better at spotting the "gotchas" than I am ;) Much appreciated!

**Comment by john-bodley** [comment]
Thanks @miomiocat for the PR. Would you mind:

1. Resolving the merge conflict.
2. Running `tox -e pre-commit` locally? We added the `pyupgrade` hook which rewrites type hints.

**Comment by miomiocat** [comment]
> Thanks @miomiocat for the PR. Would you mind:
> 
> 1. Resolving the merge conflict.
> 2. Running `tox -e pre-commit` locally? We added the `pyupgrade` hook which rewrites type hints.

Done, please take a look at this PR

**Review by villebro — APPROVED** [review]
LGTM, thanks for the improvements, cleanup and added tests 👍 While I kinda would prefer the transparent background on the logo, the dark text would make it illegible on dark mode if the background were to be dark, so maybe it's better like this.

**Pull request merged**
