### PR TITLE
Revert "perf(sqllab): Rendering perf improvement using immutable stat…

### PR DESCRIPTION
**Pull request by hughhhh**
…e (#20877)"

This reverts commit f77b910e2cc9f1bd90ac0f3a9097ec5d394b582d.

### SUMMARY

Fixes the issue with the tablemetadata schema not loading properly

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

https://user-images.githubusercontent.com/27827808/187982652-218a1745-36fe-432b-9aca-7d22a9dedd69.mp4

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by EugeneTorap** [comment]
@hughhhh Why should we revert the big commit with useful perf and refactoring changes?
That's a lot of work put in here. For the sake of a small bug that can be fixed with a few lines of code, do we revert it?
@justinpark Can we prepare small hot fix for this issue in another PR?

**Comment by EugeneTorap** [comment]
I understand that an easy way to revert it than spend more time fixing it.
In this case we can revert whole project, and we will never have bugs & issues.

**Comment by justinpark** [comment]
@EugeneTorap
I posted a hotfix here: #21304 
if it doesn't know, we can revert the changes.

**Comment by EugeneTorap** [comment]
@justinpark Thanks. I appreciate your work.

**Comment by EugeneTorap** [comment]
@villebro Can we close this PR? We've fixed the bug.

**Comment by villebro** [comment]
> zhaoyongjie villebro Can we close this PR? We've fixed the bug.

@EugeneTorap I defer to @hughhhh (also a committer) who has opened the PR, as I have not participated in this discussion

**Comment by justinpark** [comment]
@EugeneTorap There's one more hotfix related to this change. Please add this patch together

#21311

**Pull request closed without merging**
