### PR TITLE
[fix] auth for celery cache warmup requests (issue #7954)

### PR DESCRIPTION
**Pull request by mifercre**
### CATEGORY

Choose one

- [X] Bug Fix
- [ ] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by willbarrett — COMMENTED** [review]
I'd love to see some tests around this, especially since it was broken recently :). Thank you for submitting a fix!

**Comment by umandal** [comment]
@mifercre Is your cache getting refreshed after authentication?
after using these changes our authentication is successful but, Superset is not able to trigger query to refresh cache, and cache not getting refreshed

**Comment by mifercre** [comment]
@umandal yes. Can you paste any error logs, flask/gunicorn logs...

**Comment by ukm21** [comment]
@mifercre Thanks for your reply,
I got this working using
[#7148](https://github.com/apache/incubator-superset/pull/7148/commits/76e6aa9e1395f8445d8d4cd613b9b865da4fdb8c)
as the master branch hits this url 'http://0.0.0.0:8081/superset/explore/?form_data=%7B%22slice_id%22%3A%204%7D'   but for cache warmup we need to hit 'http://0.0.0.0:8081/superset/warm_up_cache/?slice_id=30'

**Comment by saurabh1920** [comment]
@ukm21 I tried what you suggested but I am getting unauthorized error.

Here is traceback.
`Traceback (most recent call last):
  File "/app/superset/tasks/cache.py", line 304, in cache_warmup
  File "/usr/local/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: UNAUTHORIZED`

How did you manage to bypass authorization?

**Pull request closed without merging**
