### PR TITLE
Fix: updated required cryptography version to 2.4.2 to resolve #6509

### LINKED ISSUE #6509: docker-compose up fails
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
latest  commit on master

### Expected results
successfully start docker container

### Actual results

`Command "/usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-fa_crv71/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-chrjo_4e/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-fa_crv71/cryptography/
ERROR: Service 'superset' failed to build: The command '/bin/sh -c pip install --upgrade setuptools pip     && pip install -r requirements.txt -r requirements-dev.txt     && rm -rf /root/.cache/pip' returned a non-zero code: 1
`

### Steps to reproduce
I followed these steps: https://github.com/apache/incubator-superset/blob/master/docs/installation.rst
based on that commit https://github.com/apache/incubator-superset/commit/02aa3c6395a381e59dced848df55cb1daf733e95

### PR DESCRIPTION
**Pull request by haaspt**
The current requires cryptography version in requirements.txt causes `docker-compose up` to fail. Updating the required version, per https://github.com/apache/incubator-superset/issues/4870#issuecomment-444189653, resolves the issue.

### CODE REVIEW

**Review by mistercrunch — CHANGES_REQUESTED** [review]
You have to update setup.py and run the pip-compile command to do this properly.

**Comment by haaspt** [comment]
Sorry about missing the changes to setup.py, tried again after changing the script and running pip-compile. Thanks for the heads up.

**Comment by Andrew-Tan** [comment]
Also waiting on this change as I cannot build the docker image now :)

**Review by mistercrunch — APPROVED** [review]

**Comment by mistercrunch** [comment]
Got a false negative on one of the Cypress builds, restarted it, this is ready to merge once the build is green

**Pull request merged**
