### PR TITLE
fix: update SQL Lab Buttons to better wording

### PR DESCRIPTION
**Pull request by AAfghahi**
### SUMMARY
Changed the wording to be more dynamic in accordance to Figma designs. 

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Before:
image

After:
Screen Shot 2021-02-17 at 9 59 52 AM

### ADDITIONAL INFORMATION

- [ ] Has associated issue: fixes issue 13001 https://github.com/apache/superset/issues/13001
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by eschutho — APPROVED** [review]
LGTM. Waiting for some product/design ideas before flagging it for merge. @yousoph @steejay

**Review by etr2460 — APPROVED** [review]

**Comment by Steejay** [comment]
updated button labels look good to me. thanks @AAfghahi @eschutho

**Comment by AAfghahi** [comment]
> updated button labels look good to me.
> 
> is there a reason why the button margins differ between explore, download and copy? can we make all 8px between buttons?
> 
> @AAfghahi @eschutho

Oh, I just noticed this, and will change it now.

**Comment by AAfghahi** [comment]
@Steejay 
Screen Shot 2021-02-19 at 10 26 20 AM
Like this?

**Comment by Steejay** [comment]
@AAfghahi yes! youre an all star!

**Comment by eschutho** [comment]
@AAfghahi did you push your latest commit with the spacing updates yet? I'll check back if you need another review on it.

**Comment by AAfghahi** [comment]
> @AAfghahi did you push your latest commit with the spacing updates yet? I'll check back if you need another review on it.

Unsure what happened there, but I just pushed it.

**Pull request merged**
