### PR TITLE
multi language in react

### PR DESCRIPTION
**Pull request by lxzhangchao**

### CODE REVIEW

**Comment by xrmx** [comment]
I think we need to use some tools that would get the annotated strings automatically. This is too error prone.

**Comment by lxzhangchao** [comment]
This should be considered. Do you have any suggestions?

**Comment by lxzhangchao** [comment]
Is it possible to use React-intl to implement multiple languages?

**Comment by mistercrunch** [comment]
For internationalization of the frontend, I'd like to impose some constraints that aren't respected here:
* single place for backend / frontend translations (we use Python's Babel in the backend)
* should be integrated with webpack somehow so that there's different entry points built for each language somehow so that the javascript would be minified properly with only what you need as opposed to downloading all languages

**Comment by lxzhangchao** [comment]
To share the translation files of Python and the translation files of JS.
I looked at some information and did some experiments with API. I got some results
I translate the python translation to JS translation by calling the function method
1. the translation of the string is implemented in the form of reference, but to translate multiple pages, you need to send multiple requests that slow down the load. This method is not available
2. I tried another method, through the function call the translation of files, disposable loading to translate the language files, but the string type to call them the result of API that is not what we want to use the translation, the conversion process is not achieved.
3., I have found through other tools, such as react-intl, react-intl-universal, that internationalization functions or new language configuration files, translation files can't be unified.

I wonder if you have any new ideas to implement common translation files to achieve universal internationalization of Python and JS

**Comment by xrmx** [comment]
@lxzhangchao seen this? https://github.com/apache/incubator-superset/issues/1926#issuecomment-313050727

**Comment by xrmx** [comment]
@lxzhangchao if you have opened a new PR please close this one.

**Pull request closed without merging**
