### PR TITLE
fix(Sql Lab tabs): Empty SQL lab tabs

### LINKED ISSUE #17630: Closing all tabs on SQL Lab leaves the screen blank
When closing all tabs on SQL Lab, the whole screen goes blank due to there not being a single open tab left. 

#### How to reproduce the bug

1. Go to SQL Lab
2. Close all tabs
3. Notice how the whole screen goes blank

### Expected results

A new empty tab should be opened automatically. The same can now be achieved by clicking on SQL Lab in the menu, which correctly opens an empty tab.

### Actual results

The screen goes blank

#### Video

https://user-images.githubusercontent.com/33317356/144376770-4872c145-5e57-4efc-9862-5e4909d58f4d.mp4

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by Yahyakiani**
### SUMMARY

This PR fixes the problem in which all SQL Lab tabs could be closed leaving an empty window. Now instead of trying to close the last window an error modal will pop up.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

before
after

### ADDITIONAL INFORMATION

- [x] Has associated issue:#17630
- [ ] Required feature flags:
- [x] Fixes #17630  
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [x] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by ofekisr** [comment]
I don't think popping up an error message is a good way, IMO is better to create automatically a new tab when the last tab is deleted

**Comment by kasiazjc** [comment]
Hi! I agree that adding an error message is quite agressive as there is no real reason why user cannot have all of the tabs closed (and they may want to have like this for their peace of mind). 

I would say that the easiest way to go and most user friendly would be improving an error state, below is a solution that I'd like to propose 

image

sql empty state

**Comment by yousoph** [comment]
I love the blank state proposal from @kasiazjc , agreed that it's more user friendly than showing an error on closing.

**Comment by villebro** [comment]
@Yahyakiani thanks so much for the contribution! My apologies for not checking in with design on the original issue in #17630 🙁 Do you think you would be able to implement the proposed design? If not we'll be happy to help; just ping me on Slack if you want to discuss!

**Comment by Yahyakiani** [comment]
> @Yahyakiani thanks so much for the contribution! My apologies for not checking in with design on the original issue in #17630 🙁 Do you think you would be able to implement the proposed design? If not we'll be happy to help; just ping me on Slack if you want to discuss!

Certainly, I will let you know in case of any questions.

**Comment by Yahyakiani** [comment]
> Hi! I agree that adding an error message is quite agressive as there is no real reason why user cannot have all of the tabs closed (and they may want to have like this for their peace of mind).
> 
> I would say that the easiest way to go and most user friendly would be improving an error state, below is a solution that I'd like to propose
> 
> image
> 
> sql empty state
Thanks for the feed. Which can I find or import this design from ? or will I have to create it . Any direction would be helpful.

**Comment by kasiazjc** [comment]
@Yahyakiani I added it all to the [figma file](https://www.figma.com/file/EmbCgU8uikecetsqkBrasB/%5BDT%5D-SQL-LAB-Tab-Empty-State?node-id=101%3A7965). You should be able to export all of the details, objects, check the colours etc.

 I do not have the correct design for the implemented tabs, so I guess you should use the spacings etc that we already have and do not mind the details of the design too much.

Let me know if you can access the file :)

**Comment by eschutho** [comment]
cc @yousoph

**Comment by yousoph** [comment]
Closing this PR since https://github.com/apache/superset/pull/18817 took it to completion

**Pull request closed without merging**
