### PR TITLE
Update down_revision to fix migrations 

### PR DESCRIPTION
**Pull request by 1AB9502**
### CATEGORY

Choose one

- [x] Bug Fix
- [ ] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY
We forgot to update down_revision in #4725, so now the migrations have 2 heads.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [x] Requires DB Migration.
- [x] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by 1AB9502** [comment]
Looking into why travis is failing

**Comment by graceguo-supercat** [comment]
thanks for the quick fix. will merge after ci passed.

**Review by graceguo-supercat — APPROVED** [review]
LGTM

**Comment by 1AB9502** [comment]
@graceguo-supercat ,

Thanks! 1 test is still failing, so I am looking into it now

**Comment by graceguo-supercat** [comment]
don't worry about unit test failing...it's false alert from cypress. i will make a new PR for this issue.

**Pull request merged**
