### PR TITLE
chore: enable ruff lint rule TRY201 and B904 to improve `raise` stack traces

### PR DESCRIPTION
**Pull request by mistercrunch**
When intercepting and re-raising an error in python, it's almost always better to simply `raise` over raising the exception alias ie: `raise ex`. The main reason is that the stack trace often (always?) gets truncated in the process, losing track of where the error occurred.

Similarly, when intercepting and re-raising another exception, it's better to `raise AnotherException() from ex` (using  `from`), so I'm fixing and enforcing this as well.

I found this while debugging and dealing with incomplete stack traces, and thought it be a good idea to fix and enforce using ruff's TRY201 and B904

### CODE REVIEW

**Comment by mistercrunch** [comment]
Summoning some of our backend / python folks - @betodealmeida @dpgaspar @john-bodley , what do you think?

**Review by giftig — APPROVED** [review]

**Comment by giftig** [comment]
I think there might be cases where you legitimately don't want to use `from` because you don't care about the original exception, but it's probably not very often. But a bare `raise` is always better than reraising the original exception you just caught imo, for the reasons you mentioned.

**Review by villebro — APPROVED** [review]
TIL

**Review by john-bodley — APPROVED** [review]

**Comment by mistercrunch** [comment]
> TIL

yeah I didn't know that until I was like "where's the rest of my stacktrace!?!?! how did we get here?"

**Pull request merged**
