### PR TITLE
add Zalando to the list of organizations

### PR DESCRIPTION
**Pull request by dmigo**

### CODE REVIEW

**Comment by mistercrunch** [comment]
Mind rebasing the brach, with Apache I can't be a Github admin so I can't force merge....

**Comment by mistercrunch** [comment]
Actually the master build is broken now, we need to figure out what's up.

**Comment by dmigo** [comment]
@mistercrunch sure, I'll rebase as soon as the master goes green.

**Comment by mistercrunch** [comment]
master is green!

**Comment by dmigo** [comment]
@mistercrunch locked and loaded =)

**Pull request merged**
