### PR TITLE
chore: remove QueryView (ModelView)

### PR DESCRIPTION
**Pull request by mistercrunch**
### SUMMARY
This is not needed anymore as we have the "Query Search" page, and the `/api/v1/query` REST endpoints.

### CODE REVIEW

**Comment by willbarrett** [comment]
Some odd test failures on this one. I'd change `deprecate` to `remove` in the PR title - this isn't deprecation, which implies prior notice of removal. This is deleting API endpoints.

@john-bodley @etr2460 @betodealmeida @bkyryliuk are these endpoints in use by your organizations? Trying to cast a wide net early...

**Comment by etr2460** [comment]
Could you share an example of the URLs that are removed?

**Comment by bkyryliuk** [comment]
> Some odd test failures on this one. I'd change `deprecate` to `remove` in the PR title - this isn't deprecation, which implies prior notice of removal. This is deleting API endpoints.
> 
> @john-bodley @etr2460 @betodealmeida @bkyryliuk are these endpoints in use by your organizations? Trying to cast a wide net early...

we don't use those, thanks for the cleanup!

**Comment by bkyryliuk** [comment]
> Some odd test failures on this one. I'd change `deprecate` to `remove` in the PR title - this isn't deprecation, which implies prior notice of removal. This is deleting API endpoints.
> 
> @john-bodley @etr2460 @betodealmeida @bkyryliuk are these endpoints in use by your organizations? Trying to cast a wide net early...

we don't use those, thanks for the cleanup!

**Comment by mistercrunch** [comment]
@etr2460  this removes `/queryview/read`

Can I get a stamp?

**Review by willbarrett — APPROVED** [review]

**Pull request merged**
