### PR TITLE
[sql lab] Update event handler name

### PR DESCRIPTION
**Pull request by graceguo-supercat**
Update SqlEditor database change event handler name to be more specific.

### CODE REVIEW

**Comment by mistercrunch** [comment]
LGTM, welcome on board Grace!

**Comment by jfeng15** [comment]
woohoo!!  excited to see you ship your first change Grace!   welcome aboard :-)

ship

**Comment by graceguo-supercat** [comment]
merge into master

**Comment by graceguo-supercat** [comment]
squash and merge.

**Pull request merged**
