### PR TITLE
fix(explore): 'Edit Datasource' is missing from btn-dropdown

### LINKED ISSUE #10247: Cannot edit datasources from the Pivot Table viz
When the pivot table viz is selected in Explore and I click on the datasource name, I don't see the option to edit the datasource, only change it or explore it in sql lab.

### Expected results

See the option to edit the datasource

### Actual results

Don't see that option

#### Screenshots

image

#### How to reproduce the bug

1. Open a chart in explore
2. Change it to viz type pivot-table
3. Click on the datasource name
4. don't see the edit datasource option

### Environment

(please complete the following information):

- superset version: `master`

@rusackas or @suddjian, do you think this is related to moving the pivot table controls into superset-ui? I know it happened a while ago, but I can't think of another reason for this to break, so tagging you here

### PR DESCRIPTION
**Pull request by mistercrunch**
Not sure how it got broken but he's a fix. I'm thinking this is related
to the controls refactor.

closes https://github.com/apache/incubator-superset/issues/10247

### CODE REVIEW

**Comment by mistercrunch** [comment]
@villebro let's make sure this makes 0.37!

**Review by ktmud — APPROVED** [review]
Thanks for the fix! This could be due to #10224 and probably impacts all charts.

**Comment by ktmud** [comment]
This probably doesn't fix the onSave behavior, I'll make another followup PR.

**Comment by mistercrunch** [comment]
Yeah I noticed after the fact that the action is not bound and doesn't get dispatched. It does fix the menu, the modal showing up and actually saves, but changes are not reflected in the redux state...

Thanks for taking this over @ktmud

**Pull request merged**
