### PR TITLE
fix: dashboard side actions

### PR DESCRIPTION
**Pull request by pkdotson**
### SUMMARY
This pr fixes the issues where the dashboard side actions aren't displayed when in edit mode.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

https://user-images.githubusercontent.com/17326228/117920413-aace6b00-b2a3-11eb-87bd-b15a7df0efc0.mov

### ADDITIONAL INFORMATION

- [x ] Has associated issue: 14554
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by rusackas** [comment]
Code looks simple enough... easy review! 
Waiting on the ephemeral build to verify. 

Two questions for @pkdotson:
1) Was it tested with and without the Native Filters feature flag enabled?
2) Can you think of any sort of regression test we can add here? RTL's `toBeVisible` doesn't seem sufficient here.

**Review by graceguo-supercat — APPROVED** [review]
LGTM

**Comment by junlincc** [comment]
1. Was it tested with and without the Native Filters feature flag enabled? 
Tested Yes

**Comment by yousoph** [comment]
🏷️ 2021.19

**Pull request merged**
