### PR TITLE
[New-Viz][AmericanExpress] Funnel/Step Visualization

### PR DESCRIPTION
**Pull request by BrainyZeiny**
### CATEGORY

- [ ] Bug Fix
- [x] Enhancement (new features, refinement)
- [ ] Refactor
- [x] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY
This is a PR to our most popular viz_type at American Express. The Step/Funnel Visualization is a 2 in 1 visualization that is simple to use and highly modifiable. It has unique support of multi-pass queries and thus is worthy of the PR effort. The  'Funnel' feature can be turned on or off if the user prefers a simple step visualization over 'funnel'. 

### Funnel-Mode
image

### Step-Mode
image

### Control Panel Supports Multi-Step Queries with 'Add Step'
image

### ADDITIONAL INFORMATION
- [x] Has associated issue:
- [x] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [x] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by villebro** [comment]
Would you be able to post some screenshots? I think step charts would be an awesome addition, as they seem to be all the rage for decomposing financials these days.

**Comment by etr2460** [comment]
Linking this comment here: https://github.com/apache/incubator-superset/pull/8346#issuecomment-538508719

Maybe this should be in a separate plugin instead so that we don't update the deprecated `viz.py` file

**Comment by TheLastSultan** [comment]
Updated @villebro .  Just finishing some cleanup efforts and waiting to pass build.

**Comment by mistercrunch** [comment]
We're in the process of moving all visualizations to live as plugins in other repos. This is very in-flight at the moment. Started writing an example here:
https://github.com/apache-superset/superset-ui-plugins/pull/216

Happy to get on a call to talk about it and help you through the process. You can ping me on the Superset Slack.

**Comment by TheLastSultan** [comment]
@mistercrunch amazing!  Viz.py was getting a little out of hand to say the least  :)

Although it is much needed and welcome, "in-flight" is apt for where superset-ui-plugin effort is at the moment. It would be much less time consuming to write a plugin once the legacy plugins are up and functional. Would it be possible to revisit that refactor when the time comes ?

**Comment by TheLastSultan** [comment]
Bump @etr2460 @mistercrunch

**Comment by TheLastSultan** [comment]
@etr2460  It's been 10+ days. What is the status of this PR? Can we get some reviewers on it please.

**Comment by TheLastSultan** [comment]
Hey @mistercrunch , i'll be working on merging this in superset-ui-plugins this weekend. Since it's merged off of master now I'll use that as an example.

**Pull request closed without merging**
