### PR TITLE
chore: bumps the handlebars plugin package version to match the family.

### PR DESCRIPTION
**Pull request by rusackas**
### SUMMARY

Just bumps the version number to be in lockstep with other plugins. Will publish to NPM once this merges.

### TESTING INSTRUCTIONS

N/A

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by michael-s-molina — APPROVED** [review]
LGTM

**Comment by michael-s-molina** [comment]
`master` is failing again after this PR 😢. Can you check @rusackas?

**Comment by rusackas** [comment]
Now it's published on NPM, so hopefully that resolves it... again. Gotta find some automated way to bump versions and publish. The github bot might be one good way to do that... e.g. watch for a merge, and publish automatically... or something a similar action based on tags.

**Comment by rusackas** [comment]
Actually, CI seems to be TRYING to publish the package... not sure if GH Actions can use a specific bot-username that we give proper permissions to on NPM.

**Pull request merged**
