### PR TITLE
feat(supersetbot): introduce `supersetbot` as its own npm package, CLI and comment-operated bot

### PR DESCRIPTION
**Pull request by mistercrunch**
### SUMMARY
While GitHub actions are powerful, it's been hard to work with actions as they hard to develop, test, and debug.

Introducing a new `supsersetbot` utility bot that can be used to help around GitHub, CI and beyond. For now it does some basic things like labeling PRs and issues, but the idea is to grow it to serve set of utility functions to help around GitHub, GitHub actions, CI, release management and the repo int general. Things like managing ephemeral environments, supporting release management.

Because it's a proper npm app, it can be tested, versioned, deployed and used locally.

It's a CLI as in:
```
$ supersetbot
Usage: supersetbot [options] [command]

Options:
  -r, --repo <repo>          The GitHub repo to use (ie: "apache/superset") (default: "mistercrunch/superset")
  -a, --actor <actor>        The actor (default: "bob")
  -h, --help                 display help for command

Commands:
  label [options] <label>    Add a label to an issue or PR
  unlabel [options] <label>  Remove a label from an issue or PR
  orglabel [options]         Add an org label based on the author
  help [command]             display help for command
```
But it can also be called from GitHub comments, as in:
Screenshot 2024-02-14 at 3 17 15 PM

This means that PR comments can be used a bit more like a terminal, and committers and users can trigger things. Note that it's fully context-aware, nows whether the commenter is a committer, and can decide who should be able to do what.

While this first version brings back the funcitonality we had with a previous, hosted now defunct `supersetbot`, the vision is to extend it to manage ephemeral envs, tag PRs with release-related information, ...

### CODE REVIEW

**Comment by mistercrunch** [comment]
@supersetbot label preset-io

**Comment by mistercrunch** [comment]
@supersetbot label preset-io

**Comment by mistercrunch** [comment]
@supersetbot label preset-io

**Comment by mistercrunch** [comment]
@supersetbot label preset-io

**Comment by mistercrunch** [comment]
@supersetbot label preset-io

**Comment by mistercrunch** [comment]
@supersetbot label preset-io

**Comment by mistercrunch** [comment]
@supersetbot label preset-io

**Comment by mistercrunch** [comment]
@supersetbot label preset-io

**Comment by mistercrunch** [comment]
test

**Comment by mistercrunch** [comment]
Oh wow, i was really confused, this only triggers if it's on `master`: 
Screenshot 2024-02-07 at 10 28 31 PM

**Comment by geido** [comment]
@supersetbot label "preset-io"

**Comment by geido** [comment]
@supersetbot label preset-io

**Comment by mistercrunch** [comment]
@supersetbot label preset-io

**Review by betodealmeida — APPROVED** [review]
This is awesome, #TIL

**Review by rusackas — CHANGES_REQUESTED** [review]
Only one change request... this seems like it'd cause some potential release/security issue, if I'm not mistaken and _anyone_ can remove _any_ tag. We should probably have some means to protect important tags (or namespaces thereof) like release numbers that Cherry Tree uses, or `hold` tags, for example.

**Review by rusackas — APPROVED** [review]
LGTM — I think the last thing it needs (which could be done separately) is adding some documentation. Either a page on the docs site, or maybe a page on the wiki. The description on the PR here is a great starting point — a tweaked version of that would suffice to raise initial awareness.

**Pull request merged**
