### PR TITLE
feat: Turkish translation files added

### PR DESCRIPTION
**Pull request by coteli**
### SUMMARY

Turkish translation files created and added to repo. Many UI elements have been translated. 

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

English
Turkish

### TESTING INSTRUCTIONS

For the translation to take effect after compile translation catalogs into binary MO files with the command below:
pybabel compile -d superset/translations
Language can be change.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by rusackas — APPROVED** [review]
Awesome! Looks good to me! Thanks for making the changes in the .po file... we'll soon probably drop the .json files and make them part of the build/deploy/CI processes.

**Comment by coteli** [comment]
gitte bir problem yaşadığım için bu requesti kapatıyorum. lütfen değişiklikleri dikkate almayın, karışıklıklardan dolayı çok üzgünüm. probleri çözdükten sonra yeni bir request yapacağım.

**Comment by coteli** [comment]
I'm closing this request because I'm having a problem with git. Please ignore the changes, I am very sorry for any confusion. After solving the problems, I will make a new request.

**Comment by aysenurseref** [comment]
@coteli  Hi! I'm facing a problem with Turkish translations even after compiling the translation catalogs into binary MO files. I can see the Turkish option in the language selection dropdown menu. However, when I select this option, I got  error: "TypeError: Cannot read properties of null (reading 'domain')" on the console. I  attached a screenshot of this error. What steps should I take to solve  this issue?  
translation-error

**Comment by coteli** [comment]
Hi @aysenurseref, I couldn't figure out where the error came from. 
Maybe you can add the Turkish option to the Languages section in your config file, if you haven't already.
If your problem persists, you can open an issue on superset's slack channel or github and explain it in detail.

**Pull request closed without merging**
