### PR TITLE
[fix] Support APP_ICON_WIDTH configuration parameter in SPA menu

### PR DESCRIPTION
**Pull request by natalierue**
### CATEGORY

Choose one

- [X] Bug Fix
- [ ] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY
The SPA menu component was relying on a hardcoded icon width of 126. This change exposes the config.py APP_ICON_WIDTH property to the frontend through the apps bootstrapping process and alters the SPA menu component to consume this value as the logo image width.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
n/a

### TEST PLAN
Set APP_ICON_WIDTH property to a value other than 126 and observe the SPA and template version of the header have matching logo sizes.

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [X] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by etr2460 — CHANGES_REQUESTED** [review]
could you set the width in the config file to 126? Then we'll both have documentation of the config var existing, and can replace the `config.get` with a `config["APP_ICON_WIDTH"]` because we can always assume it exists

**Review by rusackas — APPROVED** [review]
LGTM

**Comment by rusackas** [comment]
> could you set the width in the config file to 126? Then we'll both have documentation of the config var existing, and can replace the `config.get` with a `config["APP_ICON_WIDTH"]` because we can always assume it exists

It appears  `APP_ICON_WIDTH` is [already set to 126](https://github.com/apache/incubator-superset/blob/c474ea848a1c5e611d1b30301686aa83eb2cda06/superset/config.py#L183) in `config.py`.

There are a handful of other config.get instances that pull in existing vars from `config.py` - I'm not sure how big an issue is, or if it should be blocking for this PR.

**Comment by etr2460** [comment]
We've tried to standardize around `config[]` over `config.get` in the past, so I think it's better to keep going in that direction. see https://github.com/apache/incubator-superset/pull/8454

**Review by etr2460 — APPROVED** [review]
lgtm, thanks for the fix!

**Pull request merged**
