### PR TITLE
feat(alerts): Column for select tabs to send

### PR DESCRIPTION
**Pull request by m-ajay**
As of now, users can only send the first tab of the dashboard. We are improving the feature, to let the user select the tabs to send. Please see the discussion here #14056 .

This PR adds a new column to Report schedule, initially this will be used to store the IDs of the tabs to send.

### SUMMARY

Second PR will include letting users select the tabs of the dashboards to send.

### ADDITIONAL INFORMATION

- [x] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [x] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [x] Migration is atomic, supports rollback & is backwards-compatible
  - [x] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by graceguo-supercat** [comment]
@m-ajay Thanks for the work! 
Currently, we want to enrich the email report feature with dashboard tab selection. But in the very near future, we might want to enrich the report with filter set selection, or dashboard_owners etc. So i think all these extra configuration for a report, could be stored in the same column that you will add today.

So how about name this column as `extra_config`, column type `Text` is good, and will populate an empty json `{}` text as default data?

**Comment by dpgaspar** [comment]
@m-ajay can you please update the PR description and fix CI, seems like a mig issue

**Comment by etr2460** [comment]
should we use `extra` for the column name instead of `extra_config`, to be consistent with other tables in superset?

**Review by graceguo-supercat — APPROVED** [review]
LGTM

**Review by riahk — APPROVED** [review]

**Pull request merged**
