### PR TITLE
fix: Filters alert width

### PR DESCRIPTION
**Pull request by michael-s-molina**
### SUMMARY
Fixes the filters alert width and also changes the modal width.

Following @kasiazjc's [comment](https://github.com/apache/superset/pull/24559#issuecomment-1632099115) in https://github.com/apache/superset/pull/24559: 
>  I think in general we have to bump the width of the modal in the default mode to ~880px (and resize just after it not longer fits in the screen), so that everything is more visible.

I adjusted the modal to have a fixed base width instead of percent based one. I set it to 1000px instead of 880px as a middle ground.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Screenshot 2023-07-25 at 11 36 58
Screenshot 2023-07-25 at 11 46 35

### TESTING INSTRUCTIONS
Make sure the the width of the filters' alert takes the available space.

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by rusackas — APPROVED** [review]

**Review by justinpark — COMMENTED** [review]
Looks good to me other than 1000px adjustment change (will be reviewed @kasiazjc

**Review by justinpark — APPROVED** [review]

**Comment by kasiazjc** [comment]
> ### SUMMARY
> Fixes the filters alert width and also changes the modal width.
> 
> Following @kasiazjc's [comment](https://github.com/apache/superset/pull/24559#issuecomment-1632099115) in #24559:
> 
> > I think in general we have to bump the width of the modal in the default mode to ~880px (and resize just after it not longer fits in the screen), so that everything is more visible.
> 
> I adjusted the modal to have a fixed base width instead of percent based one. I set it to 1000px instead of 880px as a middle ground.
> 
> ### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
> Screenshot 2023-07-25 at 11 36 58 Screenshot 2023-07-25 at 11 46 35
> ### TESTING INSTRUCTIONS
> Make sure the the width of the filters' alert takes the available space.
> 
> ### ADDITIONAL INFORMATION
> * [ ]  Has associated issue:
> * [ ]  Required feature flags:
> * [ ]  Changes UI
> * [ ]  Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
>   
>   * [ ]  Migration is atomic, supports rollback & is backwards-compatible
>   * [ ]  Confirm DB migration upgrade and downgrade tested
>   * [ ]  Runtime estimates and downtime expectations provided
> * [ ]  Introduces new feature or API
> * [ ]  Removes existing feature or API

I think on the smaller screens, modals that are that big of a size can be overwhelming (that's why I would prefer to avoid them) and I do not think that we add that much value with the increased size (especially because with 880x the fields are already bigger than our default + 240px seems like enough). I think we use width of 880px we use in the dashboard properties etc and the 1000px+ is used for alerts&reports as there is a lot of content and different inputs etc. 

Can be convinced that 1000px is better though if you give me reasons @michael-s-molina :D

**Comment by michael-s-molina** [comment]
> Can be convinced that 1000px is better though if you give me reasons @michael-s-molina :D

I was worried it wouldn't work for Airbnb but I checked with @justinpark and 880px is fine for most cases. I changed the width back to 880px.

**Comment by kasiazjc** [comment]
> > Can be convinced that 1000px is better though if you give me reasons @michael-s-molina :D
> 
> I was worried it wouldn't work for Airbnb but I checked with @justinpark and 880px is fine for most cases. I changed the width back to 880px.

Thank you @michael-s-molina ❤️

**Review by kasiazjc — APPROVED** [review]
LGTM ✨

**Pull request merged**
