### PR TITLE
Add Udemy to INTHEWILD

### PR DESCRIPTION
**Pull request by sungjuly**
Udemy is using SqlLab feature experimentally, thanks for making the great project!

### CODE REVIEW

**Comment by mistercrunch** [comment]
Glad to have you in board. Just curious, which backends are you using sql lab against?

**Comment by sungjuly** [comment]
@mistercrunch for Presto, Redshift and Hive.

**Comment by mistercrunch** [comment]
We'll have better support for Hive soon on SQL Lab with an estimated progress bar and access to logs.

How's SQL Lab working against Redshift? There's a bit of confusion around schema/database/owner hierarchy in SQLAlchemy that results in uneven features and bugs on our side I think.

**Comment by mistercrunch** [comment]
Oh I see you have that PR open, I'll take a look.

**Comment by sungjuly** [comment]
@mistercrunch glad to hear good news in terms of Hive, there's a bunch of bugs/minor issues than Hue as you know.

**Pull request merged**
