### PR TITLE
fix: Owners selection in dataset edit UX

### LINKED ISSUE #15530: Not Able to Update DataSet Owner in Superset
### Expected results

When I click on a Dataset  I am not able to update the owner for the datasets as the Owner list is not rendered and I am not able to see all the users in the drop down

### Actual results

Should be able to update the Owner of the datasets 

#### Screenshots

Screenshot 2021-07-02 at 10 02 06 PM

#### How to reproduce the bug

1. Go to  saved queries, 
2. Click on datasets and click on edit
3. Go to setting and update the owner 

### Environment

(please complete the following information):

- superset version: `superset version`  1.0.1
- python version: `python --version`  
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### LINKED ISSUE #16883: [edit_dataset]can not see full list of users in edit dataset dropdown
I can not search all users in the edit dataset -> settings -> owners and add a desired user to the dataset ownership 
#### How to reproduce the bug

1. Open any chart
2. Click on the 3 dots and Edit dataset, click on the settings tab
3. Scroll down to Owners
4. see if you can find all users(?) 

### Expected results

what you expected to happen.
be able to search and add any users in my organization

### Actual results

some of the users are missing from dropdown

#### Screenshots

https://user-images.githubusercontent.com/67837651/135178539-d30b6e48-63bf-43aa-a2c1-3bc6637313ce.mov
Note: I didnt fake enough accounts to reproduce this issue. 

(please complete the following information):

- browser type and version: chrome 
- superset version: `superset version` 1.3 maybe? 
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by hughhhh**
### SUMMARY

The original dataset edit screen didn't populate owners and wasn't allowing users to properly query the db for potentially new owners.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

https://user-images.githubusercontent.com/27827808/136850207-f4658700-0058-4d60-a226-dbc9243915fc.mov

### TESTING INSTRUCTIONS

1. Goto datasets
2. Click on edit dataset in one of list items
3. Goto settings
4. Change owners
5. Save
6. Make sure owners in list reflect owners you chose

### ADDITIONAL INFORMATION

- [ ] Has associated issue: closes #15530 closes #16883 
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by betodealmeida — APPROVED** [review]
Looks good, I just left 2 small nits.

**Review by betodealmeida — CHANGES_REQUESTED** [review]

**Review by betodealmeida — APPROVED** [review]

**Comment by junlincc** [comment]
does this PR fix https://github.com/apache/superset/issues/15530 and https://github.com/apache/superset/issues/16883?

**Pull request merged**
