### PR TITLE
Bump FAB to 2.1.4

### PR DESCRIPTION
**Pull request by dpgaspar**
### CATEGORY

Choose one

- [X] Bug Fix
- [X] Enhancement (new features, refinement)

### SUMMARY
FAB to 2.1.X brings the following relevant topics:

- It's now possible to override class permission name and method permission name. Useful to aggregate view permissions and reduce the amount of generated view/menu/api, permission pairs.
- Builtin roles defined on config that support regular expressions
- flask-sqlalchemy bump to 2.4.0 with more config options

### ADDITIONAL INFORMATION
- [X] Introduces new feature or API

CHANGELOG from FAB since version 2.0.0:

- Improvements and Bug fixes on 2.1.4

Fix, #1027 API dotted notation joins to same table
Fix, #1012 API default resource name must be lower case
Fix, #1013 Use csrf exempt by default when CSRFProtect is registered has a Flask extension
Fix, #1007 API Support for property decorated functions has models fields
Fix, #1002 Permission mapping
New, #1010 Support for UUID sqlalchemy fields has string fields on WTForms

- Improvements and Bug fixes on 2.1.3

Fix, Index view override on class instantiation is discarded

- Improvements and Bug fixes on 2.1.2

Fix, #993 App factory pattern, AppBuilder object can be fully configured using config keys
Fix, #994 If builtin role don't check db also, higher permission on DB would allow access

- Improvements and Bug fixes on 2.1.1

Fix, #991 Make Admin builtin optional, only if declared on config

- Improvements and Bug fixes on 2.1.0

New, #977 flask-sqlalchemy bump to 2.4.0 (new config options)
New, #986 Builtin roles using regex, Admin role is now one of these
New, #969 Override class and method permission names and procedure to converge/migrate
Fix, #985 Deprecation warning EOL version was wrong
New, #976 pRison version bump
Fix, #966 Change the default email value for auth_remote_user in security manager

### CODE REVIEW

**Review by mistercrunch — APPROVED** [review]
LGTM

**Comment by elukey** [comment]
This is great, having all these improvements in the next release would be massive!

**Comment by mistercrunch** [comment]
@elukey these features are in the new `RestModelView` which we're migrating towards.

**Comment by elukey** [comment]
@mistercrunch thanks a lot for working on this. I don't have a ton of context about the migration towards 2.x for FAB, I am mainly interested in a fix (https://github.com/dpgaspar/Flask-AppBuilder/pull/966/commits) for a recurrent issue that I have in my superset environment. Instead of simply bumping fab to 2.x by myself and rebuild I preferred to wait since IIUC the migration is not as simple as changing the version in requirements.txt :)

**Pull request merged**
