### PR TITLE
feat(native-filter): limit max tag count for selected filter values

### LINKED ISSUE #12462: [dashboard][native-filter]make single filter select field collapsible
requirement: make filter select field collapsible to allow user hide the long list of selected value of a single filter from the dashboard. 

Screen Shot 2021-01-12 at 9 07 52 AM

### PR DESCRIPTION
**Pull request by einatbar**
### SUMMARY
show max tag count in select filter
resolves: #12462

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
https://user-images.githubusercontent.com/5047207/117138441-b3123c00-adb3-11eb-97ae-e3ab87010a43.mov

### ADDITIONAL INFORMATION

- [x] Has associated issue:
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by junlincc** [comment]
thanks for the PR! I personally love the solution. @amitmiran137 
However, we want to offer the transparency to show dashboard consumer what filter values are selected at a glance. 
The problem is that the list could get long and take up lots of space. My proposed solution is to offer the option to collapse/minimize the select box, to 2 lines maybe?  

@graceguo-supercat @mihir174 @ktmud wdyt?

**Comment by amitmiran137** [comment]
The ability here is to limit the amount of items that are visible.
Currently @einatbar  used 5 items and then the rest goes into the count 

We can increase that number to what ever feels right 
And also the select box can always be opened to see the full list

**Comment by amitmiran137** [comment]
We used the out of the box feature bin antD
No collapse/expand ability in the select

**Comment by graceguo-supercat** [comment]
@einatbar  thanks for the PR. If the filter is growing taller when as user typing in more values, what will happen for the filter below this one? In your example, if "Name" is on top of "Gender" filter, will it keep push "Gender" filter down?

**Comment by einatbar** [comment]
@graceguo-supercat It will push "Gender" down until the user reaches the max visible tags count. If we set a low max tags count like 5, it will be pushed by 2 rows down at most, depending on values lengths I guess.

**Comment by michael-s-molina** [comment]
I also really like the solution. I think that when we have a lot of selected values it's difficult for the user to actually see what's selected. Generally, the user wants to know if a particular value is selected, and for that case opening the select and searching for it can be faster than trying to find it visually in the middle of 30 selected items. Another thing that bugs me is the layout flick of every item below the select. 

Independently of which solution we choose, we need to keep the consistency of all selects. For example, in Explore, the selects are expanding so if we choose to use the tag count here, we should also apply the same pattern there.

**Comment by junlincc** [comment]
one suggestion: when user click the +4 to view all, we should only show the selected values.

**Comment by junlincc** [comment]
@michael-s-molina is the purpose of expanding to view all selected values or to edit select? User can certainly click the empty space to edit the select

**Comment by ktmud** [comment]
It is possible to add a tooltip to the "+4..." pill to display all remaining items?

**Comment by michael-s-molina** [comment]
> @michael-s-molina is the purpose of expanding to view all selected values or to edit select? User can certainly click the empty space to edit the select

Both. The AntD team decided to use this default behavior because it's important to the user to view which values are selected and also which ones are not, and to quickly be able to select/unselect a value. Most of the time the user is looking to see if a specific value is selected, and not to read through all the values. Personally, I would stick to the default behavior proposed by AntD.

**Comment by michael-s-molina** [comment]
One thing that we can do is sort the values presenting the selected ones first.

**Comment by michael-s-molina** [comment]
> It is possible to add a tooltip to the "+4..." pill to display all remaining items?

@ktmud I liked the idea. If we have few values it's easy to check the remaining items. If we have a bunch of values the user can click on the select and search for a specific value.

**Comment by rusackas** [comment]
> > It is possible to add a tooltip to the "+4..." pill to display all remaining items?
> 
> @ktmud I liked the idea. If we have few values it's easy to check the remaining items. If we have a bunch of values the user can click on the select and search for a specific value.

It seems that where this gets difficult is not when we're in a `+4` situation, but when we're in a `+104` situation. 

For _most_ use cases, I'd bet the select menu isn't absurdly long, and the list of checked/selected items isn't absurdly long either. In that case, clicking the `+𝒙` and popping open the select menu to view/add/remove items from the selection seems perfectly acceptable.

However, with LOTS of selections from LOTS of options (let's say, cities in the US... and you've selected 90 of them) then we have a bigger problem. For _that_ I see multiple potential approaches:

1) When you click the `+𝒙` it opens the select menu, with two new features:
 • Selected items at the top
 • A search input to find a specific option to (de)select
 • A tooltip on the `+𝒙` to show a lightweight list of items contained therein

2) Leave the select menu as-is (maybe add the search anyway), but add an interactive popover to the `+𝒙` item.
 • Popover would contain the remaining list of selected values.
 • Each value in that list would have a little 🅧 button next to it to remove the selection, just like the other tag/label selections  that precede the `+𝒙`

3) Both?

Not sure if this makes sense - happy to draw up wireframes if it helps explain (perhaps with @mihir174)

**Comment by villebro** [comment]
I personally LOVE this solution, and at the risk of this hiding something vital, I think it solves the much bigger problem of killing the UX by eating the whole filter tab when having lots of selected values.

**Comment by mistercrunch** [comment]
Love this improvement, one extra thing that could help is to make sure that the selected values shows on top as you re-open the dropdown as per GitHub

Screen Shot 2021-05-07 at 12 05 30 PM

**Comment by mihir174** [comment]
I think this is an awesome solution, and that Max's list ordering suggestion improves it even further. An interactive popover on the `+x` doesn't reveal any more information that the list itself, so I don't think we need one. We could use this for all select components across the product.

**Review by amitmiran137 — APPROVED** [review]

**Comment by amitmiran137** [comment]
are there any mixed feelings here on merging this and do follow-ups PR's?

**Review by villebro — APPROVED** [review]
Let's merge and refine in subsequent PRs

**Comment by villebro** [comment]
> Love this improvement, one extra thing that could help is to make sure that the selected values shows on top as you re-open the dropdown as per GitHub
> 
> Screen Shot 2021-05-07 at 12 05 30 PM

I opened this PR to implement reordering of the selected values on reopening the dropdown: #14842

**Pull request merged**
