### PR TITLE
Set examples as published=True

### LINKED ISSUE #7865: Example dashboards are unpublished by default
Example dashboards are unpublished by default

### Expected results
Example dashboards to be published

### Actual results

They're unpublished

#### Screenshots
image

#### How to reproduce the bug

1. Setup superset from scratch
2. See that the example data creates unpublished dashboards

### Environment
- superset version: master

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by mistercrunch**
### CATEGORY

Choose one

- [x] Bug Fix
- [x] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY
related to https://github.com/apache/incubator-superset/pull/4725
closes https://github.com/apache/incubator-superset/issues/7865

### CODE REVIEW

**Review by villebro — CHANGES_REQUESTED** [review]
I think you're missing similar changes in the following files:
- `unicode_test_data.py`
- `tabbed_dashboard.py`

**Comment by mistercrunch** [comment]
Those 2 are more or less used for unit tests, I wanted to publish only the decent example dashboards.

**Comment by villebro** [comment]
> Those 2 are more or less used for unit tests, I wanted to publish only the decent example dashboards.

Thinking more about this, if these are not considered official example dashboards, perhaps they should be installed using a different command, like `superset load_tests` or similar?

**Comment by mistercrunch** [comment]
Changes here now included in https://github.com/apache/incubator-superset/pull/7773

**Pull request closed without merging**
