### PR TITLE
chore: split cypress files for less memory

### PR DESCRIPTION
**Pull request by eschutho**
### SUMMARY

Testing to see if this will fix the cypress memory issues. 
Also added the chrome flag `disable-dev-shm-usage`

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by mistercrunch** [comment]
Matrix (1, chrome) failed so I restarted it manually. Wondering if a wider matrix would help. Also it seems we have 5 * chrome now, but could try running also against Firefox to see if the memory consuption is more or less of a problem on that browser.

**Comment by rusackas** [comment]
> Matrix (1, chrome) failed so I restarted it manually. For the record `dashboard/nativeFilters.test.ts` is the one that failed, even after shrinking it down as part of this PR. I'm wondering if lowering the limit / cardinality of filters could help here too if the issue comes from too many filters with too high of a cardinality (assuming that this specific test is the hot spot).
> 
> Wondering if a wider matrix would help. Also it seems we have 5 * chrome now, but could try running also against Firefox to see if the memory consuption is more or less of a problem on that browser.

Yes, that is the hot spot, and it's always the one that fails. We've also seen GitHub issues about performance regressions when there are lots of filters, so this failure is likely reflecting a real problem. We can throw memory, split tests, reduce test scope, etc. to smooth out devEx, but I think we're just dancing around a real problem.

**Comment by eschutho** [comment]
@rusackas this is passing CI.. can we try to merge it?

**Review by mistercrunch — APPROVED** [review]

**Review by rusackas — APPROVED** [review]

**Comment by mistercrunch** [comment]
Looked at `master` hoping to see some green but no :/
Screenshot 2024-09-25 at 2 35 23 PM

**Comment by mistercrunch** [comment]
Giving a shot at troubleshooting memory here -> https://github.com/apache/superset/pull/30397 , seems promising

**Pull request merged**
