### PR TITLE
fix input height to match with react-select

### LINKED ISSUE #3830: Fix react-select's height
This looks a little off, height should match the TextControl
screen shot 2017-11-10 at 10 30 08 am

### PR DESCRIPTION
**Pull request by graceguo-supercat**
before vs after
screen shot 2017-11-15 at 2 00 23 pm

fix https://github.com/apache/incubator-superset/issues/3830

### CODE REVIEW

**Comment by mistercrunch** [comment]
I think that will create other problems like what's here being addressed here (inconsistent sizing between buttons and form controls):
https://github.com/apache/incubator-superset/pull/3850

The notion of `bsSize="small"` is consistent across bootstrap (control input, buttons, ...). We've been using `bsSize="small"` pretty much everywhere too.

If we want react-select to match the size of form inputs, we should either create a small react-select, or move to not using `bsSize="small"`

**Comment by graceguo-supercat** [comment]
Is it a better solution like this one?
https://github.com/JedWatson/react-select/issues/1322

**Comment by mistercrunch** [comment]
Yeah that looks sound.

**Comment by mistercrunch** [comment]
LGTM

**Pull request merged**
