### PR TITLE
[WIP] Repair and improve sample data functionality

### LINKED ISSUE #6009: Can't select wb_health_population columns using Postgres
- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.26.0 - following [docker-compose instructions](https://superset.incubator.apache.org/installation.html#start-with-docker)

### Expected results
Be able to run World Bank dashboard.

### Actual results
I'm not able to run any query that state particular `wb_health_population` column as in Postgres columns created with " " should be referenced this way as well. The exact same problem as here: https://stackoverflow.com/questions/24253814/cant-select-an-existing-column-in-postgresql

```
2018-09-29 14:00:38,127:INFO:root:SELECT SP_POP_TOTL
FROM wb_health_population
LIMIT 1
2018-09-29 14:00:38,128:ERROR:root:column "sp_pop_totl" does not exist
LINE 1: SELECT SP_POP_TOTL
               ^
Traceback (most recent call last):
  File "/home/work/incubator-superset/superset/sql_lab.py", line 185, in execute_sql
    db_engine_spec.execute(cursor, query.executed_sql, async_=True)
  File "/home/work/incubator-superset/superset/db_engine_specs.py", line 376, in execute
    cursor.execute(query)
psycopg2.ProgrammingError: column "sp_pop_totl" does not exist
LINE 1: SELECT SP_POP_TOTL
```

### Steps to reproduce
Follow [docker-compose instructions](https://superset.incubator.apache.org/installation.html#start-with-docker) and try to render WB dashboard.

I hope that it's not because of the fact I'm still using 0.26. Either way I would be very happy to help with improving test data set generation or with Docker images maintenance.

### LINKED ISSUE #7339: Unicode test example not working
### Expected results

This should display a word cloud on the chart / dashboard with the different values from the unicode strings

### Actual results

The chart doesn't load with this error:
`Metric 'sum__value' is not valid`

This is the stacktrace:
```
Traceback (most recent call last):
superset_1  |   File "/home/superset/superset/viz.py", line 405, in get_df_payload
superset_1  |     df = self.get_df(query_obj)
superset_1  |   File "/home/superset/superset/viz.py", line 193, in get_df
superset_1  |     self.results = self.datasource.query(query_obj)
superset_1  |   File "/home/superset/superset/connectors/sqla/models.py", line 835, in query
superset_1  |     query_str_ext = self.get_query_str_extended(query_obj)
superset_1  |   File "/home/superset/superset/connectors/sqla/models.py", line 481, in get_query_str_extended
superset_1  |     sqlaq = self.get_sqla_query(**query_obj)
superset_1  |   File "/home/superset/superset/connectors/sqla/models.py", line 594, in get_sqla_query
superset_1  |     raise Exception(_("Metric '{}' is not valid".format(m)))
superset_1  | Exception: Metric 'sum__value' is not valid

```
#### How to reproduce the bug

1. Install via docker with latest version of master
2. Go to charts and select Unicode Cloud
3. 

### Environment

(please complete the following information):

- superset version: `master`
- python version: 3.6.8
- node.js version: v10.15.3
- npm version: 6.4.1

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by villebro**
### CATEGORY

- [x] Enhancement (new features, refinement)
- [x] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [x] Documentation
- [x] Bug Fix

### SUMMARY
A summary of changes:
- Fix a handful of encountered bugs:
   - Compile column names in expressions to ensure quotes are present when needed, the lack of which causes problems on (at least) Postgres.
   - `sum__SP_RUR_TOTL` metric was missing from `wb_health_population`.
   - `sum__value` metric was missing from `unicode_test`.
   - Text columns in `unicode_test` defined as non-Unicode SQLAlchemy type `String`, should be `Unicode`.
   - MySQL fails to import Unicode text due to defaulting to currently using `latin1` charset. Changed default charset to `utf8m4` (per official recommendation). 
   - Polygon chart broken due to missing metric.
   - Incorrect height on Polygon chart due to wrong metadata (reference to `js_datapoint_mutator`, should be `js_data_mutator` and incorrect syntax in mutator code).
   - Incorrect color on Path chart due to wrong metadata (same as Polygon chart).
   - Fix edge case in `sqla/models.py` when ordering by a metric whose label has been mutated.
- Add `SAMPLE_DATA_DB_DATASOURCE_NAME` and `SAMPLE_DATA_DB_SCHEMA_NAME` to make it possible to load sample data into any database/schema with csv upload support. Currently loading is only supported into main backend database.
- Make sample data work on all databases. This is made possible by leveraging column label mutation logic found in `db_engine_specs` by conditionally mutating any unsupported column names in sample data and references thereof in the chart metadata. A few examples of columns that need to be mutated:
   - BigQuery: Columns starting with a number, e.g. columns `2004`-`2014` in `birth_france_by_region`
   - Redshift: non-lowercase columns, e.g. column `DEPT_ID` in `birth_france_by_region`
- Move `DataFrame` uploading logic to `db_engine_specs` to enable uploading to engines that don't support vanilla `DataFrame.to_sql()` like BigQuery (requires use of `to_gbq()`). As a biproduct BigQuery now also supports CSV uploading.
- Add `README.md` explaining the steps needed to add a new sample dataset and the more complex parts like conditional mutating of column names.

By being able to deploy sample data & charts/dashboards on any db will make it easier to make sure that an engine really works, spot regressions/bugs and also reduce clutter in the main backend database.

### SCREENSHOTS
Screenshot 2019-04-24 at 11 28 21
Polygon heights now work.

Screenshot 2019-04-24 at 11 28 40
Path colors now work

Screenshot 2019-04-24 at 11 29 56
Picture taken from from sample dataset deployed to BigQuery. Notice the mutated column names (original name `2004`, now prefixed with undescore and trailing md5 hash as per logic in `db_engine_specs`). Having the full md5 hash is slightly overkill, but can be changed later (first 5 few chars should suffice to avoid realistic collision risk).

### TEST PLAN
Tested on Sqlite, Postgres and BigQuery, all of which work well.

### ADDITIONAL INFORMATION
- [x] Has associated issue: fixes #6009, fixes #7339

### REVIEWERS
@dostiharise @andy-clapson @trrahul @michaldul please give this a try if you can.

### CODE REVIEW

**Comment by villebro** [comment]
This is NOT ready for review, but apparently draft PRs block CI, so needed to undraft this.

**Comment by villebro** [comment]
@mistercrunch this is approaching completion; due to the large amount of bugs this turned out to be fairly large. Would you prefer to have this hacked into smaller pieces, or is this ok?

**Comment by villebro** [comment]
Closing this for now, I will be splitting this into smaller and more easily digestable PRs.

**Comment by dostiharise** [comment]
Sorry @villebro, couldn't respond in time. 

Please let me know if I can assist you with any future PRs related to this issue. 

Would be glad to help!

**Comment by dostiharise** [comment]
> @mistercrunch this is approaching completion; due to the large amount of bugs this turned out to be fairly large. Would you prefer to have this hacked into smaller pieces, or is this ok?

Try Squashing your commits into a single commit. Might be that convinces the bot?

**Comment by dostiharise** [comment]
My bad, your PR is indeed very large. 

According to the Bot page "size/XL" is described as "Denotes a Pull Request that changes 500-999 lines."

Don't squash please. Just split.

**Comment by villebro** [comment]
Yeah, I think this is something like 10 PRs in one. Will start picking this apart shortly.

**Pull request closed without merging**
