### PR TITLE
Giving hints that we support SparkSQL

### PR DESCRIPTION
**Pull request by mistercrunch**

### CODE REVIEW

**Comment by sbookworm** [comment]
It's a very good news for us that caravel supporting hive :+1: 
When testing the data url 'jdbc+hive://',  the error 'Can't load plugin: sqlalchemy.dialects:jdbc.hive' occurred. I checked the dialects of sqlalchemy http://docs.sqlalchemy.org/en/latest/dialects/
it seems not support jdbc,  could you tell me what should I install to resolve the problem? Thanks very much :)

**Comment by giaosudau** [comment]
current only hive://ip:port/db_name works.

**Comment by cristina-grosu** [comment]
When is going to be released the support for the "jdbc+hive" dialect? Has anyone managed to define their own dialect?

**Comment by mistercrunch** [comment]
@cristina-grosu I don't know the specifics, but pyhive defines a hive dialect for sqlalchemy, and if you install the jdbc driver for python it should work in theory

**Pull request merged**
