### PR TITLE
Add modules to sandbox.js

### PR DESCRIPTION
**Pull request by hughhhh**
Updated color package to use d3-color and added package to encode/decode geohashes

@betodealmeida  @mistercrunch

### CODE REVIEW

**Comment by mistercrunch** [comment]
Good call on making d3-color available, but I'm wondering what users would do with the geohash lib  assuming that Superset deals with this in the backend.

**Comment by kristw** [comment]
What would be example of how user use `d3-color` in the sandbox? I am not sure we want to expose too many libraries in the sandbox. One thing to consider is it also adds a constraint for us when upgrading or switching library because there is no easy way to check if this will break these js code in sandbox. For example, now the codebase is stuck with `underscore` 1.8.x, although I would prefer to switch to `lodash`

**Comment by williaster** [comment]
yeah @mistercrunch @hughhhh what are your thoughts on breaking backward compatibility for libraries that are exposed there? 

I feel like at one point we discussed breaking changes being okay because this is a power-user feature (similar to custom css on dashboards) .

**Comment by mistercrunch** [comment]
I'd say for now and until this really settles we'd just post in `UPDATING.md` when breaking backward compatibility.

**Comment by hughhhh** [comment]
@mistercrunch I see a lot of our users wanting adhoc transforms on the geo data. I wanted it here to allow us to do custom encoding/decoding just incase they want to do more things. I get that the backend has some but its not a catch all in my opinion. We can continue to iterate and move more of the functionality into the controls when we see fit which is what we've been doing.

@kristw We've been mostly using it for deckgl animations and gradients based upon the rows metadata. Here's an example deck.gl has for setting the color based upon density http://deck.gl/#/documentation/deckgl-api-reference/layers/polygon-layer. I also thing adding `d3-scale-chromatic` would dope too

@williaster backward compatibility +1 with what @mistercrunch mentioned.

**Pull request closed without merging**
