### PR TITLE
chore: bump node.js to v14

### PR DESCRIPTION
**Pull request by kgabryje**
### SUMMARY
Bumps node version to v15.8.0 - current stable. Changelog: https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V15.md

Docker image: https://hub.docker.com/layers/node/library/node/15/images/sha256-05b68ed85be74950052b3afe25ce93b9f534d86454cb12547964739c607557b1?context=explore
### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

CC @villebro @rusackas @ktmud

### CODE REVIEW

**Review by villebro — COMMENTED** [review]
Super excited about this! 🎉  We also probably need to bump it in these places:
- https://github.com/apache/superset/blob/master/Dockerfile#L48
- https://github.com/apache/superset/blob/master/docker-compose.yml#L76

**Comment by kgabryje** [comment]
> Super excited about this! 🎉 We also probably need to bump it in these places:
> 
> * https://github.com/apache/superset/blob/master/Dockerfile#L48
> * https://github.com/apache/superset/blob/master/docker-compose.yml#L76

Oops, my bad. Done

**Review by villebro — APPROVED** [review]

**Comment by ktmud** [comment]
Can we stick with current LTS version v14 instead?

**Comment by villebro** [comment]
> Can we stick with current LTS version v14 instead?

I personally prefer keeping these as recent as possible so we can incrementally add support for new features, but If there are concerns that going with v15 will introduce stability issues, I vote going with v14. When reading https://nodejs.org/en/about/releases/ I get the impression that only library developers should go with Current and all others should use LTS. So perhaps v14 is safer.

**Comment by ktmud** [comment]
Yeah, they specifically recommend `Production applications should only use Active LTS or Maintenance LTS releases.`

We are unlikely to use any cutting-edge features from the current release anyway, so it's probably safer to go with LTS.

**Comment by etr2460** [comment]
I completely agree with Jesse here, generally Node odd numbered releases are full of bugs/issues. I'd feel much better with keeping us at 14

**Review by villebro — CHANGES_REQUESTED** [review]
Thanks for the review comments @ktmud and @etr2460 ; @kgabryje would you mind downgrading to v14 to address the feedback?

**Comment by kgabryje** [comment]
@villebro Done! Thank you for feedback @ktmud @etr2460

**Review by ktmud — APPROVED** [review]
LGTM. Do you mind updating `superset-frontend/.nvmrc` as well? I know probably not many people use it, but we do recommend `nvm use` in CONTRIBUTING.md.

**Comment by kgabryje** [comment]
@ktmud Done

**Review by villebro — APPROVED** [review]

**Pull request merged**
