### PR TITLE
feat: Added latin america countries to country map

### LINKED ISSUE #21440: [SIP-89] Proposal for adding latin america countries to country map
*Please make sure you are familiar with the SIP process documented*
(here)[https://github.com/apache/superset/issues/5602]. The SIP number should be the next number after the latest SIP listed [here](https://github.com/apache/superset/issues?q=is%3Aissue+label%3Asip).

### Motivation

I'm working on a project where I need to visualise data from latin america countries, but there a lot of countries missing from the country map.

### Proposed Change

I propose to add the following countries: argentina, bolivia, chile, colombia, costa rica, cuba, dominican republic, ecuador, el salvador, guatemala, haiti, honduras, nicaragua, panama, paraguay, puerto rico, saint barthelemy, saint martin and venezuela by using the guide detailed in this [documentation](https://superset.apache.org/docs/miscellaneous/country-map-tools/#adding-a-new-country).

### New or Changed Public Interfaces

19 new countries are going to be added to the country map visualization tool

### New dependencies

None

### Migration Plan and Compatibility

None

### Rejected Alternatives

None

### PR DESCRIPTION
**Pull request by bryanjtc**
### SUMMARY

Added argentina, bolivia, chile, colombia, costa rica, cuba, dominican republic, ecuador, el salvador, guatemala, haiti, honduras, nicaragua, panama, paraguay, puerto rico, saint barthelemy, saint martin and venezuela.
Fixes #21440 
### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

venezuela
saint martin
saint barthelemy
puerto rico
paraguay
panama
nicaragua
honduras
haiti
guatemala
el salvador
ecuador
dominican republic
cuba
costa rica
chile
colombia
bolivia
argentina

### TESTING INSTRUCTIONS

Clone the repo and go to its root directory. Run the following shell commands:

cd superset-frontend && npm install
npm run plugins:storybook
### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [x] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by villebro — COMMENTED** [review]
Thanks for this wonderful addition! One question; did you use the `Country Map GeoJSON Generator.ipynb` file to generate the new files? If so, would it be possible to add the changes to the notebook so these can be recreated later if needed?

**Comment by bryanjtc** [comment]
@villebro Yes. I did use the generator file. I just pushed the file with the changes.

**Review by ktmud — APPROVED** [review]
Thanks for the updates! At some point maybe we should just add all countries, lol.

**Comment by bryanjtc** [comment]
@betodealmeida Did you reviewed my changes. Do I need to change anything?

**Comment by villebro** [comment]
@bryanjtc thanks for the reminder. This has been open long enough, so I started CI flow and can merge once it's ready if CI is green

**Pull request merged**
