### PR TITLE
Adding tests for the time table viz

### PR DESCRIPTION
**Pull request by michellethomas**
Testing get data for metric queries and for group by queries. Also testing exceptions in query_obj.

### CODE REVIEW

**Comment by michellethomas** [comment]
@john-bodley adding tests for time series table viz

**Review by john-bodley — APPROVED** [review]

**Comment by mistercrunch** [comment]
LGTM

**Comment by timifasubaa** [comment]
@mistercrunch @john-bodley  Why haven't we merged this?

**Comment by mistercrunch** [comment]
I think for committers it's preferable for them to merge their own PRs as they might know things others don't or may want to merge their multiple PR in a certain order. @michellethomas do you have `write` access to the repo yet?

**Comment by michellethomas** [comment]
I don't have access, I'm not a committer yet.

**Pull request merged**
