### PR TITLE
fix(helm): update init containers to include extra env vars

### LINKED ISSUE #24805: Init containers should be getting same ENV var setups like the final containers
Init containers should be getting same ENV var setups like the final containers

#### How to reproduce the bug

Try hosting superset on k8s using helm and get the values for `DB_HOST`, `DB_NAME`, etc from some different secret.

#### Screenshots
image

### PR DESCRIPTION
**Pull request by luthes**
### SUMMARY

The init containers in the helm chart do not get the same environment variables as the other pods. This causes issues when the init containers attempt to ping the database, and the database variables are overridden in environment variables.

### TESTING INSTRUCTIONS

* Add env vars to `values.yaml`, `extraEnvRaw`, or `extraEnv` example:
```yaml
extraEnvRaw:
  # Load DB password from other secret (e.g. for zalando operator)
  - name: DB_PASS
    valueFrom:
      secretKeyRef:
        name: superset.superset-postgres.credentials.postgresql.acid.zalan.do
        key: password
```

```yaml
extraEnv:
  GUNICORN_TIMEOUT: 300
```

* Run `helm template superset .` 

* Verify changes, in this case `deployment.yaml`, shortened for readability.

With no values in `envFromRaw` or `extraEnv`:
```yaml
# Source: superset/templates/deployment.yaml
[...]
      initContainers:
      - command:
        - /bin/sh
        - -c
        - dockerize -wait "tcp://$DB_HOST:$DB_PORT" -timeout 120s
        envFrom:
        - secretRef:
            name: 'superset-test-env'
        image: 'apache/superset:dockerize'
        imagePullPolicy: 'IfNotPresent'
        name: wait-for-postgres
      containers:
[...]
```

With no values in `envFromRaw`, but `GUNICORN_TIMEOUT` set in `extraEnv`:
```yaml
# Source: superset/templates/deployment.yaml
[...]
      initContainers:
      - command:
        - /bin/sh
        - -c
        - dockerize -wait "tcp://$DB_HOST:$DB_PORT" -timeout 120s
        envFrom:
        - secretRef:
            name: 'superset-test-env'
        image: 'apache/superset:dockerize'
        imagePullPolicy: 'IfNotPresent'
        name: wait-for-postgres
        env:
          - name: "GUNICORN_TIMEOUT"
            value: "300"
      containers:
[...]
```

With `DB_PASS` set in `envFromRaw`, no values set in `extraEnv`:
```yaml
[...]
      initContainers:
      - command:
        - /bin/sh
        - -c
        - dockerize -wait "tcp://$DB_HOST:$DB_PORT" -timeout 120s
        envFrom:
        - secretRef:
            name: 'superset-test-env'
        image: 'apache/superset:dockerize'
        imagePullPolicy: 'IfNotPresent'
        name: wait-for-postgres
        env:
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                key: password
                name: superset.superset-postgres.credentials.postgresql.acid.zalan.do
      containers:
[...]
```

With both `DB_PASS` and `GUNICORN_TIMEOUT` set:
```yaml
[...]
      initContainers:
      - command:
        - /bin/sh
        - -c
        - dockerize -wait "tcp://$DB_HOST:$DB_PORT" -timeout 120s
        envFrom:
        - secretRef:
            name: 'superset-test-env'
        image: 'apache/superset:dockerize'
        imagePullPolicy: 'IfNotPresent'
        name: wait-for-postgres
        env:
          - name: "GUNICORN_TIMEOUT"
            value: "300"
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                key: password
                name: superset.superset-postgres.credentials.postgresql.acid.zalan.do

      containers:
[...]
```

### ADDITIONAL INFORMATION

- [x] Has associated issue: Fixes #24805
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by dpgaspar — COMMENTED** [review]
Thank you.
Looks good you need to bump the chart version

**Comment by luthes** [comment]
This should be good to go now. Let me know if you need any further changes.

**Comment by jsvdvis** [comment]
Any updates on this one?

**Comment by craig-rueda** [comment]
I resolved the conflict on the Chart.yaml, however the README will need to be rebuilt as well.

**Comment by rusackas** [comment]
Is there any interest in rekindling this, or shall we close it? I'd love to see the linked issue closed by this PR or the other one.

**Comment by rusackas** [comment]
Actually, I'll just close this in favor of https://github.com/apache/superset/pull/27226 which seems closer to merging. Thanks for the contribution @luthes and feel free to reopen this if you want to get it across the finish line.

**Pull request closed without merging**
