### PR TITLE
Statistical regression fit annotation layer in line chart

### PR DESCRIPTION
**Pull request by ghost**
screen shot 2018-07-15 at 9 06 17 pm

In reference to: https://github.com/apache/incubator-superset/pull/5235

### CODE REVIEW

**Comment by mistercrunch** [comment]
@vylc @williaster would love to get your input on design / color line type usage.

Seems like the color should be the same as the one its coupled to (perhaps with lower opacity?) unless specified?

**Comment by vylc** [comment]
i've seen regression lines be bolder/thicker and usually of a completely different color family (ie. if the palette is composed of lighter/paler colors, then the regression could be darker/bolder) since we use the dotted lines of the same color for time comparisons, I think same color family but lower opacity could be confusing.

**Comment by hajdbo** [comment]
This is an awesome feature that I'd like to see merged :)

**Comment by thunter009** [comment]
This is an awesome feature that I'd like to see merged as well :)

**Comment by EvelynTurner** [comment]
I got locked out from github (remember to save the recovery code!) so I comment this late. There's an option to change the line styles so the user could change them themselves (or I guess I could change the default for the regression lines). Thank you for the interest but I'm no longer interested in developing Superset so I leave it be closed but anyone should be able to just copy the logic and rebase. I'm deleting my account too, thanks.

**Pull request closed without merging**
