### PR TITLE
add `_()` to Exception messages

### PR DESCRIPTION
**Pull request by roganw**
`_()`  missing in `raise Exceptions("msg")`

### CODE REVIEW

**Comment by xrmx** [comment]
I think that exceptions in the logs should really be the same for everyone so that we can easily grep them.

**Comment by RoganW** [comment]
@xrmx Logging exception information are recommend to use `logging.info/warning/error/...`
When use `raise Exception()`, the exceptions will be raised to the end user's browser.

**Comment by xrmx** [comment]
Right, then it's fine by me

**Comment by mistercrunch** [comment]
LGTM except for the broken build

**Comment by RoganW** [comment]
@mistercrunch Done

**Pull request merged**
