### PR TITLE
chore: Bump @svgr/webpack to 5.5.0

### PR DESCRIPTION
**Pull request by kgabryje**
### SUMMARY
Bumps `@svgr/webpack` from `^5.4.0` to `^5.5.0`

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by villebro — APPROVED** [review]

**Comment by graceguo-supercat** [comment]
Hi @kgabryje, we saw some errors when we tried to deploy latest master branch to airbnb production. the error is like ```


[2021-06-30T01:15:09Z] [Jun 30 01:15:09]  INFO ==>  ERROR in ./src/showSavedQuery/index.jsx
--
  | [2021-06-30T01:15:09Z] [Jun 30 01:15:09]  INFO ==>  Module build failed (from ./node_modules/babel-loader/lib/index.js):
  | [2021-06-30T01:15:09Z] [Jun 30 01:15:09]  INFO ==>  Error: Cannot find module '@emotion/babel-plugin-jsx-pragmatic'
  | [2021-06-30T01:15:09Z] [Jun 30 01:15:09]  INFO ==>  Require stack:
  | [2021-06-30T01:15:09Z] [Jun 30 01:15:09]  INFO ==>  - /srv/superset-internal/superset-fork/superset-frontend/node_modules/@emotion/babel-preset-css-prop/dist/emotion-babel-preset-css-prop.cjs.prod.js
  | [2021-06-30T01:15:09Z] [Jun 30 01:15:09]  INFO ==>  - /srv/superset-internal/superset-fork/superset-frontend/node_modules/@emotion/babel-preset-css-prop/dist/emotion-babel-preset-css-prop.cjs.js
  | [2021-06-30T01:15:09Z] [Jun 30 01:15:09]  INFO ==>  - /srv/superset-internal/superset-fork/superset-frontend/node_modules/@babel/core/lib/config/files/plugins.js
  | [2021-06-30T01:15:09Z] [Jun 30 01:15:09]  INFO ==>  - /srv/superset-internal/superset-fork/superset-frontend/node_modules/@babel/core/lib/config/files/index.js
...
```

we used npm version `7.12`. If we revert this PR then build successful. Do you know anyway to fix above error? Why do we need this webpack upgrade?  thanks!

cc @michellethomas @john-bodley

**Comment by nytai** [comment]
pretty sure this upgrade was due to a security vulnerability in the current installed version. Looks like the issue is missing dependency`@emotion/babel-plugin-jsx-pragmatic`, we can probably just add that dependency and it should work.

**Comment by kgabryje** [comment]
Yes, I bumped that version to fix a vulnerability reported by dependabot. That error is surprising since the build on CI has passed... and I can't see `showSavedQuery/index.js` being used anywhere. Anyways, I opened a PR which adds the missing dependency: https://github.com/apache/superset/pull/15491. I'd appreciate it if you took a look

**Comment by kgabryje** [comment]
Adding `@emotion/babel-plugin-jsx-pragmatic` triggered multiple build errors on CI, which seem unrelated. I think debugging that might not be trivial, so for now I'd propose reverting this PR and revisiting the issue later.

**Comment by rusackas** [comment]
I agree that reverting this for now is probably the right approach if it's causing pain, and we can re-address it in a new PR or series of PRs. I fear that many issues of this type are indicating a need to upgrade to Webpack v5, which will likely be a large effort.

**Comment by rusackas** [comment]
Revert PR opened @graceguo-supercat - https://github.com/apache/superset/pull/15508

**Comment by graceguo-supercat** [comment]
thank you @kgabryje @nytai and @rusackas for investigation!

**Pull request merged**
