### PR TITLE
feat: Stop async queries

### PR DESCRIPTION
**Pull request by ganczarek**
### SUMMARY
Currently async queries executed in Chart view cannot be stopped. 

To stop a running query in the backend the following changes were required:
- use existing `job_id` (a random UUID that is returned to frontend) as celery task id
- endpoint `DELETE /api/v1/chart/async_job/<string:job_id>` to terminate/revoke Celery task with a given task id
- close db cursors for engines that use it to cancel a running query (e.g. Trion client)

In frontend we need to call endpoint to stop an async query when:
- AbortController communicates an abort signal ('Stop' button was clicked)
- Chart component will unmount
- beforeunload event is fired

Frontend keeps job id returned by backend in chart state. 

### TESTING INSTRUCTIONS
Enable and configure `GLOBAL_ASYNC_QUERIES` feature. Next go to Chart view, execute a long running query, and verify that Celery task is terminated and query in database is cancelled when:
- 'Stop' button is clicked
- Chart view is changed (e.g. click 'Home' tab)
- browser tab is closed
- browser tab is refreshed

### ADDITIONAL INFORMATION

- [x] Has associated issue: https://github.com/apache/superset/issues/24890
- [x] Required feature flags: `GLOBAL_ASYNC_QUERIES: True`
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [x] Introduces new feature or API - adds endpoint `DELETE /api/v1/chart/async_job/<string:job_id>`
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by ganczarek** [comment]
Hi. All tests passed. I'm sorry for so many force-pushes. I'm done making changes to this PR and it's ready for review. Thank you.

**Comment by giftig** [comment]
Hi @villebro @john-bodley @michael-s-molina could we get some eyes on this one? Let us know if we need to raise a SIP; I don't think @ganczarek has done anything too controversial here as it's just implementing a missing feature -- with global async queries enabled, that button currently does nothing.

**Comment by john-bodley** [comment]
@ganczarek I _believe_ all Celery tasks should already have a UUID assigned, i.e., per the attached screenshot from [Flower](https://flower.readthedocs.io/en/latest/) you can see the async task has a UUID.

Screenshot 2023-12-16 at 11 57 20 AM

**Comment by giftig** [comment]
@john-bodley it's been a little while but as I recall, the reason we're setting the UUID explicitly is that a different job ID was already being used and stored in the db, whereas the celery task ID was automatically generated as a different UUID and we couldn't look up the task we wanted to stop. Since celery lets you assign your own ID if desired and the other ID associated with the query was also a fresh-generated UUID, the simplest solution seemed to be to tell celery to use the same ID.

**Comment by giftig** [comment]
@ganczarek correct me if I'm wrong ^

**Comment by ganczarek** [comment]
> @ganczarek correct me if I'm wrong ^

That's correct. Thanks @giftig.

**Comment by mistercrunch** [comment]
PR is messed up, showing 1k+ files changed, closing, you can reopen a fresh one and reference this one.

**Comment by rusackas** [comment]
@ganczarek do you think you'll be able to rebase/reopen this?

**Comment by ganczarek** [comment]
@rusackas I'm sorry, but I'm not able to work on this right now.

Backend (Python) changes are easy to merge. Only the change that [closes all cursors](https://github.com/apache/superset/pull/24905/commits/832f1b211ed1f52be97eb843ee221d57d1b57916) might be controversial (as it's not standard part of the API) and touches many places in code.

[The frontend changes](https://github.com/apache/superset/pull/24905/commits/1b6059b3dcbc292d56212b307500b6c7696621f3) are the ones I struggle with the most as I'm not much of a fronted developer. They are not properly tested, and while I manually verified they work, I'm not sure if that's the correct way to implement this.

**Pull request closed without merging**
