### PR TITLE
[sqllab] Cancel database query on stop

### PR DESCRIPTION
**Pull request by smacker**
### CATEGORY

Choose one

- [ ] Bug Fix
- [x] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY

Sorry for submitting PR without creating an issue first. It doesn't look like a big change but I can convert the issue and proposal into SIP if needed.

#### The issue
SQL Lab has Stop button but it only updates state of superset without actually stopping the database query.
In some cases complex query can run in background for days and affect database performance.
The issue especially affect us as we use Superset with [gitbase](http://github.com/src-d/gitbase) which speeks MySQL protocol.

#### This commit solves the problem as following:

1. Add new key `cancel_payload` into extra attribute of the Query instance.
2. Add `get_cancel_query_payload` method to EngineSpec that returns some
payload from the connection which allows to cancel it later.
3. `execute_sql_statements` before executing queries retrieves and saves
cancel payload into Query
4. Stop handler calls new `cancel_query` method of EngineSpec

Both new methods are implemented only for MySQL for now but it is easy
to add support for PostgreSQL, MSSQL and maybe some other DBs.

For MySQL I use `KILL CONNECTION` to terminate multiple statements.

#### Alternative approach:

Maintain list of open connections and close them on cancel.
This solutions looks cleaner but has some disadvantages:
- would require big changes in the codebase
- implementation would get very tricky in distributed mode
- some drivers can keep query running even after `close()` call.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

N/A

### TEST PLAN

Run complex log-running query with MySQL using SQL lab. Press stop. The query should be killed.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [x] Requires DB Migration.
- [x] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by smacker** [comment]
rebased on master, fixed an issue for sync mode

**Comment by smacker** [comment]
@mistercrunch any opinion how to proceed with this? Should I convert it into SIP? Or is it good as a PR? Maybe some changes are required (for example tests for which I would love some advice because I couldn't find tests for similar functionality)

**Comment by smacker** [comment]
@mistercrunch no. #8097 stops executing list of queries if one of them was stopped.

This PR stops (kills) underlying connection to DB (no matter 1 or more queries are there).
In async mode in SQLLab queries are executed in celery and stop button doesn't really stop them, the task is running until it gets some results from DB. (which may take days)

If you are interested in the fix, I can re-work it using `extra_json` instead of a new field in DB. It will make easier to add support for other backends. (for example for Spark just id isn't enough but special object should be serialized: https://github.com/src-d/sourced-ui/pull/267)

**Comment by mistercrunch** [comment]
It'd be great to enable the true killing of queries, sorry I missed this back in May...

**Comment by smacker** [comment]
Cool. Thank you. I'll re-work this PR in the following days to avoid DB migration and make it more flexible.

**Comment by smacker** [comment]
@mistercrunch I updated the code. It's simpler and more flexible now.

**Pull request closed without merging**
