### PR TITLE
fix(explore): Data tables styling issues on Explore view

### LINKED ISSUE #12370: [Explore]Data table sort icon misaligned
sort icons break into another line
    This happens when there are too many columns (tested with the `wh_health_data` dataset)

Confirmed issue in master 
Screen Shot 2021-01-08 at 5 30 18 PM

(can't reproduce the search box cutoff issue)
Screen Shot 2021-01-08 at 5 41 33 PM

_Originally posted by @ktmud in https://github.com/apache/superset/issues/12257#issuecomment-756967446_

### LINKED ISSUE #12371: [Explore]Data table pagination bar should be sticky to bottom on scroll
Scrolling (both horizontally and vertically) moves the pagination bar
    scrolling
    which makes it almost unusable.

Not sure how feasible it is, maybe it's worth looking into rendering this table with `DataTable` from the table viz plugin. It handles many rendering issues like 4 and 5. I had a plan to generalize that implementation, but didn't have time to finish. If someone can pick it up from where it was left, that would also be great.

_Originally posted by @ktmud in https://github.com/apache/superset/issues/12257#issuecomment-756967446_

confirmed in master 
ezgif-3-09bf57840a97

### PR DESCRIPTION
**Pull request by kgabryje**
### SUMMARY
Closes https://github.com/apache/superset/issues/12371
Closes https://github.com/apache/superset/issues/12370
Fixes an issue with wide tables stretching the chart section container, resulting in some components being cut off (described in comment https://github.com/apache/superset/pull/12257#issuecomment-756967446)
Fixes displaying "0 rows retrieved" with "error" style when data is still loading

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
https://user-images.githubusercontent.com/15073128/104090226-9d618f80-5275-11eb-8b83-5c9d63ac6888.mov

### ADDITIONAL INFORMATION

- [x] Has associated issue: https://github.com/apache/superset/issues/12370, https://github.com/apache/superset/issues/12371
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

CC: @junlincc, @ktmud, @villebro

### CODE REVIEW

**Review by villebro — APPROVED** [review]
LGTM

**Review by junlincc — APPROVED** [review]
ezgif-7-7d0019f43dd3

tested, this pr fixed reported issues. 
resizing is relatively slow but probably not related to this PR

**Comment by junlincc** [comment]
@kgabryje thanks for the fix! im still seeing [fix(explore): Update samples table when datasource changes ](https://github.com/apache/superset/pull/12378)this issue in this branch. just want to make sure both issues are addressed properly

**Comment by villebro** [comment]
> @kgabryje thanks for the fix! im still seeing [fix(explore): Update samples table when datasource changes ](https://github.com/apache/superset/pull/12378)this issue in this branch. just want to make sure both issues are addressed properly

I think this branch was cut before that fix was merged

**Comment by kgabryje** [comment]
That's correct, fix of samples table is not included in this PR

**Comment by ktmud** [comment]
TODO: we might want to fix the table header as well.

**Comment by junlincc** [comment]
> TODO: we might want to fix the table header as well.

let me try this one.... @kgabryje @ktmud

**Comment by junlincc** [comment]
i believe we do have fixed header.. but only works in Firefox. doesn't in Chrome

ezgif-7-20414277498c

in Safari, I can't even see the scroll bars and pagination 

Screen Shot 2021-01-10 at 7 48 40 PM

**Pull request merged**
