### PR TITLE
[dashboard-builder] add top-level tabs + undo-redo

### PR DESCRIPTION
**Pull request by williaster**
This is a PR for the `dashboard-builder` [branch](https://github.com/apache/incubator-superset/pull/4528) that adds
- support for top-level tabs
- support for undo-redo

I have a couple more todos (below) but wanted to put it up in case anyone has feedback. If not, when it's done we can just merge into the dashboard-builder branch 🤷‍♂️ 

tabs-undo-redo

Tabs behave as follows
- You can have top-level tabs, or not
- You may have more sets of tabs within a top-level tab (ie in the main dashboard canvas)
- Top-level tabs behave just like other tabs, meaning you can 
  - add/remove/edit them
  - re-order them
  - move individual tab components between tab sets (top-level or not)
- If you delete the top-level tabs component, the resulting canvas will have all of the content from each individual top-level tab stacked on top of each other

REMAINING TODO: 
- [x] improve UX for deleting top level tabs (make it clear what will happen)
- [x] improve drag/drop logic to restrict drag/drop based on component depth (so you can't, e.g., have tabs in tabs in tabs in ...)
- [x] improve UI/UX of nested containers + resizing
- [x] update size of all child components when resizing a container

@graceguo-supercat
cc @mistercrunch @eli-brumbaugh

### CODE REVIEW

**Comment by tcollier1975** [comment]
this sounds like a great possible addition!!! we have some folks that would LOVE this capability

**Comment by williaster** [comment]
@graceguo-supercat I think this is ready to merge into the `dashboard-builder` [branch](https://github.com/apache/incubator-superset/pull/4528). nesting rows in columns should also work now, and column children inherit parent column width where relevant (e.g., charts) as we discussed.

going to take a separate pass at tests and for the logic to detect when a row is overflown.

**Comment by williaster** [comment]
going to merge.

**Comment by SpyderRivera** [comment]
What is the timeline for merging the dashboard-builder branch into master?

**Comment by williaster** [comment]
@SpyderRivera likely another 4 weeks or so/early May, mostly because of the migration and testing needed.

**Comment by Artic2019** [comment]
О

**Pull request merged**
