### PR TITLE
fix: Revert "refactor: Replace react-bootstrap tabs with Antd tabs (#11090)"

### LINKED ISSUE #11192: Scrolling SQL Lab Results doesn't work
When you have a large results table in SQL Lab and they overflow horizontally, scrolling doesn't work

### Expected results

scrolling to work

### Actual results

scrolling doesn't work

#### Screenshots

image

#### How to reproduce the bug

1. Query a large amount of data in SQL Lab
2. Try to horizontally scroll

### Environment

(please complete the following information):

- superset version: `master`

### PR DESCRIPTION
**Pull request by john-bodley**
### SUMMARY

This reverts commit 4fd993c4e07f8bd1220d105fbaa18733daf5aebb.

### TEST PLAN

Reverted the change locally and confirmed that one could scroll horizontally for a wide table in SQL Lab.

### ADDITIONAL INFORMATION

- [x] Has associated issue: Fixes #11192 
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by etr2460 — APPROVED** [review]
can you add a test plan?

**Review by rusackas — APPROVED** [review]

**Comment by mistercrunch** [comment]
Hey, I'm noticing reverts are coming in fast without opportunities to push forward. I'm wondering if we should change the approach or the revert guidelines https://github.com/apache/incubator-superset/blob/master/CONTRIBUTING.md#revert-guidelines

I'm fine either way personally, but let's agree on guidelines.

**Comment by john-bodley** [comment]
@mistercrunch I per the guidelines I think reverting made sense:

> Availability of the PR author: If the original PR author or the engineer who merged the code is highly available and can provide a fix in a reasonable timeframe, this would counter-indicate reverting.

Unclear. @kgabryje is a relatively new contributor.

> Severity of the issue: How severe is the problem on master? Is it keeping the project from moving forward? Is there user impact? What percentage of users will experience a problem?

SQL Lab is unusable for result sets with a moderate number of columns.

> Size of the change being reverted: Reverting a single small PR is a much lower-risk proposition than reverting a massive, multi-PR change.

PR was relatively small and reverted without conflict.

> Age of the change being reverted: Reverting a recently-merged PR will be more acceptable than reverting an older PR. A bug discovered in an older PR is unlikely to be causing widespread serious issues.

The PR is relatively new and was merged 5 days ago.

> Risk inherent in reverting: Will the reversion break critical functionality? Is the medicine more dangerous than the disease?
Difficulty of crafting a fix: In the case of issues with a clear solution, it may be preferable to implement and merge a fix rather than a revert.

The risk is low especially as this was a new feature and the previous state was deemed stable.

**Comment by mistercrunch** [comment]
> Availability of the PR author: If the original PR author or the engineer who merged the code is highly available and can provide a fix in a reasonable timeframe, this would counter-indicate reverting.

That's the one item here, can we leave a minimum of ~24H after identifying the issue and reaching out to the author/merger combo on Slack?

**Comment by rusackas** [comment]
Just to chime in (since I approved both the PR and the revert), I appreciate the need for a stable `master` when people are deploying it regularly and reliant on a certain standard of stability. That said, I feel we should continue working to increase the cadence of Apache releases as stable waypoints, so that `master` can be a _little_ more forgiving in this area. I agree that 24h to provide a patch seems like a reasonable window for the author (or anyone) to apply a patch, with the (documented) addition of exceptions such as newly introduced security vulnerabilities.

**Comment by etr2460** [comment]
Personally, I think we should err on the side of keeping `master` as stable as possible, especially since many people do depend on running and developing from master. When master is broken, it not only can break deployments of Superset, but also makes developing significantly harder.

To me, reverts and re-PRs seem pretty trivial in terms of actual work required. Is there really significantly more overhead with adding a fix to a previous branch vs. fixing forward? Especially when these are clean reverts without any merge conflicts.

As for the revert guidelines, I think i've always been more aggressively pushing for reverts, perhaps even more so than the guidelines allow. But in this case, I think the guidelines were adhered to. 24hr of broken master could affect up to 20 developers and even more end users of Superset, so that seems like far too long to live in a broken state. I'd go so far as to say that if the initial committer isn't immediately available in slack, then we should move forward with reverting. Personally, if I introduced a regression in master and couldn't immediately fix it, I would much rather have it be reverted for me to come back to later than for it to live in master and slow others down

**Pull request merged**
