### PR TITLE
fix: Athena timestamp literal format

### PR DESCRIPTION
**Pull request by thinhnd2104**
related: [#19969]
from [AWS official docs](https://docs.aws.amazon.com/athena/latest/ug/data-types.html)

- [ x] Has associated issue:  [#19969]
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by rusackas** [comment]
Pinged for some reviews. Thanks for the contribution!

**Comment by john-bodley** [comment]
@thinhnd2104 do you mind addressing the failed CI checks?

**Comment by thinhnd2104** [comment]
> @thinhnd2104 do you mind addressing the failed CI checks?

Thank you. This commit was updated.

**Review by villebro — APPROVED** [review]
LGTM, thanks for the fix!

**Comment by villebro** [comment]
@thinhnd2104 I pushed a commit to fix the linting error and will merge once CI passes.

**Comment by thinhnd2104** [comment]
> 

Thank you!

**Comment by villebro** [comment]
@thinhnd2104 thanks again for the fix; I'm tagging this for 1.5.1 which I'm hoping we'll get up for vote later this week

**Pull request merged**
