### PR TITLE
feat: allow exporting all tabs to a single PDF in report

### PR DESCRIPTION
**Pull request by US579**
### SUMMARY

This update will give user an option to export all tabs if there are more then one in a dashboard, all tabs will be included in a single PDF document

ANIMATED GIF

output10

### BEFORE/AFTER SCREENSHOTS

Before user could only include one tab into a PDF report

Screenshot 2024-10-24 at 10 54 02 am

example output: 

[1_ FCC New Coder Survey 2018 (1).pdf](https://github.com/user-attachments/files/17499190/1_.FCC.New.Coder.Survey.2018.1.pdf)

After user could choose to include all tabs to their report

Screenshot 2024-10-24 at 10 53 04 am

example output: 
 [1_ FCC New Coder Survey 2018.pdf](https://github.com/user-attachments/files/17499180/1_.FCC.New.Coder.Survey.2018.pdf)

NOTE: This feature can also be modified to include specific tabs in the email, but it would require changes on the frontend (allow users to select multiple tabs).

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [x] Required feature flags: this need to enable feature flag: ALERT_REPORT_TABS
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by oOhyeahh — APPROVED** [review]

**Comment by rusackas** [comment]
Running CI again... let me know if you want me to keep clicking the button, or if you have tests running locally ;)

**Comment by US579** [comment]
> Running CI again... let me know if you want me to keep clicking the button, or if you have tests running locally ;)

ah sorry my bad, should have run all the tests

**Comment by eschutho** [comment]
/testenv up FEATURE_ALERT_REPORTS=True FEATURE_ALERT_REPORT_TABS = True

**Review by eschutho — APPROVED** [review]
LGTM. Thanks @US579!

**Comment by yousoph** [comment]
Hi @US579 ! Thanks for adding this feature :) 

We noticed that the all tabs export doesn't seem to export the tabs in any specific order (our report with 3 tabs exported with tab 2, then 3, then 1 in the PDF). Would you be open to making an enhancement to export the tabs in the order they appear in the dashboard? 

Thanks!

**Comment by US579** [comment]
> thanks for the feedback @yousoph ! yep i will take a look and get back to you

**Comment by US579** [comment]
> Hi @US579 ! Thanks for adding this feature :)
> 
> We noticed that the all tabs export doesn't seem to export the tabs in any specific order (our report with 3 tabs exported with tab 2, then 3, then 1 in the PDF). Would you be open to making an enhancement to export the tabs in the order they appear in the dashboard?
> 
> Thanks!

thanks for the feedback again! I have created an MR for fixing the order issue here
https://github.com/apache/superset/pull/30888

**Comment by lihan** [comment]
Can we get this into a stable release?

**Pull request merged**
