### PR TITLE
Fix for SQL editor throwing can't deserialize google.cloud.bigquery._helpers.Row with BigQuery

### PR DESCRIPTION
**Pull request by kuriancheeramelil**
This is as per discussion on #4028
Please review.

@xrmx, Sorry for the delayed response to comment on https://github.com/apache/incubator-superset/pull/4034. As we were making changes to master branch of our fork of superset, that changes were getting added to the above mentioned pull request as I did a pull request from that master. I don't know git enough to prevent that from happening, so creating this new request from a different branch.

### CODE REVIEW

**Comment by mistercrunch** [comment]
Please lint the code, you can look at the travis logs to debug.

**Comment by kuriancheeramelil** [comment]
Travis is failing with 
E:1192, 8: Unable to import 'google.cloud.bigquery._helpers' (import-error)

How can this be fixed in Travis?

**Comment by fabianmenges** [comment]
I bet flake8 complains because you are importing a 'private' module.

**Comment by kuriancheeramelil** [comment]
@fabianmenges, yes google.cloud.bigquery._helpers.Row is imported within BQEngineSpec.
If this shouldn't be imported within here, could you suggest where the change needs to be made.

**Comment by mistercrunch** [comment]
try `# pylint: disable=import-error`

**Pull request merged**
