### PR TITLE
fix(native-filter): Default value multi-select height in native filters

### LINKED ISSUE #14792: Multi-select input is obscuring other elements
## Screenshot

Pasted_Image_5_24_21__9_43_AM

## Description

The multi-select component seems to have taken a turn for the worse in CSS at some point. In the Native Filters config modal, you can see it overlap neighboring controls when you add a "Select" filter and then add a bunch of default values.

Similarly in the Native Filters bar itself on the left, in this example there's a hidden "B" filter that is obscured by the vertically-expanding control.

There's probably just a fixed height happening somewhere that should be made more flexible.

### PR DESCRIPTION
**Pull request by geido**
### SUMMARY
Fixes the height of the multi-select for the "Default value" in the native filters modal, as well as the multi-select in the native filters left sidebar.

### BEFORE
119386138-f4dc2700-bc7b-11eb-834a-68c157121a35

### AFTER
Screen Shot 2021-05-25 at 16 29 06

Screen Shot 2021-05-25 at 16 46 25

### TESTING INSTRUCTIONS
1. Open a dashboard
2. Select the filters
3. Add values in the "Default value" multi-select
4. Make sure the selected values are appearing correctly

### ADDITIONAL INFORMATION

- [x] Has associated issue: Fixes #14792
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by geido** [comment]
This PR is effectively overriding the fixed height that is passed to the `SuperChart` in `superset-frontend/src/dashboard/components/nativeFilters/FilterBar/FilterControls/FilterValue.tsx` and `superset-frontend/src/dashboard/components/nativeFilters/FiltersConfigModal/FiltersConfigForm/DefaultValue.tsx`. I can't really say why such height was set originally. 

@rusackas seems like you have contributed to this functionality originally. Maybe you can help to answer this question.

**Review by junlincc — COMMENTED** [review]
Thanks for the PR!
The reported issue is fixed, but we need to take care of the other issue "fixed height for select filter value box, so that multiple value select don't take up too much real estate in the filter bar". 
just repeating myself.. I'm ok to go with the ."...+4" solution as long as the selected filter value s are at the top when expand the list. please coordinate the fix with @michael-s-molina and @villebro 

https://user-images.githubusercontent.com/67837651/119574304-609cbd80-bd6a-11eb-919a-f050059816aa.mov

**Comment by michael-s-molina** [comment]
> Thanks for the PR!
> The reported issue is fixed, but we need to take care of the other issue "fixed height for select filter value box, so that multiple value select don't take up too much real estate in the filter bar". 
> just repeating myself.. I'm ok to go with the ."...+4" solution as long as the selected filter value s are at the top when expand the list. please coordinate the fix with @michael-s-molina and @villebro 
> 
> https://user-images.githubusercontent.com/67837651/119574304-609cbd80-bd6a-11eb-919a-f050059816aa.mov
> 
> 
> 
> 
@geido Thanks for the fix!

@junlincc I'll add the select with +4 to my todo list. I will work on it right after we deliver the native filters revamp 😉

**Comment by villebro** [comment]
@geido this seems to need a rebase. With regard to the "...+4" feature, I'd suggest merging #14486 and following up with a new PR that moves the selected values to the top

**Review by villebro — APPROVED** [review]
LGTM and works great! I'm wondering if we could be more explicit about the `> div > div` but I'm fine with this!

**Pull request merged**
