### PR TITLE
[css] adding spaces before opening curlies.

### PR DESCRIPTION
**Pull request by rusackas**
### SUMMARY
In another PR, @etr2460 observantly caught me not adding spaces before some opening brackets, which is a good standard. This is minuscule PR is just a quick sweep to clean up that formatting issue everywhere else.

### CODE REVIEW

**Review by willbarrett — APPROVED** [review]

**Comment by rusackas** [comment]
@etr2460 I added a stylelint config file to catch this in the future - is there already a linting system for this sort of thing that I'm missing that we can standardize around?

**Comment by etr2460** [comment]
It looks like we've started to add prettier to parts of the codebase (the dashboard code at least) but not everything. Now might be a good time to do a big format PR and get everything using Prettier (assuming everyone agrees). I think Prettier is pretty standard these days, but if people have other preferences, then we should discuss (maybe in the meetup tomorrow)

**Review by dpgaspar — CHANGES_REQUESTED** [review]
This is a new file we need to add Apache license to it

**Comment by rusackas** [comment]
> This is a new file we need to add Apache license to it

JSON doesn't allow comments by nature, so I deleted that file and moved the rules into package.json, which is also supported.

**Review by dpgaspar — APPROVED** [review]

**Pull request merged**
