### PR TITLE
fix cal_heatmap tips location error (#5480)

### PR DESCRIPTION
**Pull request by Narcissus7**

### CODE REVIEW

**Comment by graceguo-supercat** [comment]
`graph-legend` still have same issue.

**Comment by Narcissus7** [comment]
@graceguo-supercat 
it works on my machine.
the reason is that it trigger **TypeError: targetel.getScreenCTM is not a function**
about tip.show, doc says **tip.show(data, target)** .[d3-tip](https://github.com/Caged/d3-tip/blob/master/docs/showing-and-hiding-tooltips.md#tipshow) 
There is no target here.
tips

**Comment by graceguo-supercat** [comment]
p4vlkzcury

in chrome version 68

**Comment by Narcissus7** [comment]
It's OK now.
graph-legend
@graceguo-supercat

**Comment by graceguo-supercat** [comment]
thanks! 🎆 🍾

**Pull request merged**
