### PR TITLE
feat(db_engine): Implement user impersonation support for StarRocks

### PR DESCRIPTION
**Pull request by Woellchen**
### SUMMARY

This PR adds user impersonation support for the StarRocks database by leveraging the native `EXECUTE AS {user} WITH NO REVERT` user management query.

### TESTING INSTRUCTIONS

1. If necessary create a separate user on your StarRocks DB and your Superset instance. The names must match and it should be different from the user that is used for the StarRocks connection itself
2. Enable the user impersonation feature in the security settings of your StarRocks database
3. Log in to Superset with your testing user
4. Execute `SELECT CURRENT_USER();` and see that it shows your current Superset user
5. Disable user impersonation feature again
6. Execute `SELECT CURRENT_USER();` again and see that it changed back to the user of the StarRocks connection

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [x] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by Woellchen** [comment]
Thanks @john-bodley! Sure, I will look into it :)

**Comment by rusackas** [comment]
Looks like the [pre-commit hooks](https://superset.apache.org/docs/contributing/hooks-and-linting/) also need to be run to make the linters happy.

**Comment by Woellchen** [comment]
Hey @rusackas and @john-bodley, I have tried to address your issues. Could you please another look at it? :)

**Comment by rusackas** [comment]
Running CI... fingers crossed!

**Review by villebro — COMMENTED** [review]
LGTM, but we need to rebase the PR to ensure tests are running ok on the other dbs due to the sig changes. Please ping me for a new review once done.

**Comment by tooptoop4** [comment]
@Woellchen can u pls add postgres + redshift? https://docs.aws.amazon.com/redshift/latest/dg/r_SET_SESSION_AUTHORIZATION.html , https://www.postgresql.org/docs/current/sql-set-session-authorization.html

**Comment by Woellchen** [comment]
Hey @villebro! I have rebased the branch and verified that everything still works as expected :) Thank you

**Comment by Woellchen** [comment]
I had missed one usage for `databricks`, I fixed that now

**Review by villebro — APPROVED** [review]
LGTM, thanks for the patience and apologies for the loooong review process, excited to see this finally get merged! 🚀

**Comment by Woellchen** [comment]
No problem, glad we merged it! Thank you too!

**Pull request merged**
