### PR TITLE
feat(explore): add automatic conditional formatter to pivot table v2

### PR DESCRIPTION
**Pull request by villebro**
### SUMMARY
This PR adds a new conditional formatting type to the pivot table viz that automatically infers the lower and upper bounds of the color scale. In addition a db migration migrates heatmap coloring from the previous version of the Pivot Table V2 chart to the new conditional formatting control. This is done by applying conditional formatting on all metrics with red scale using the new `None` operator (infer cutoff and extreme value from cell values). While this does not provide a 1-1 feature mapping to the previous version of the plugin, it's the closest match that is possible to be achieved with the new formatting control.

This PR requires the following `superset-ui` PRs to function properly (in `superset-ui` version `0.17.78` which is now on master):
- https://github.com/apache-superset/superset-ui/pull/1264
- https://github.com/apache-superset/superset-ui/pull/1269

### BEFORE
Before the removal of the heatmap feature, the Pivot Table v2 chart provided six different conditional formatting options; heatmap and bar across all, row and column values:
Screenshot 2021-08-03 at 14 45 55

After the introduction of the new conditional formatting feature, those charts lost their coloring:
image

### AFTER
After the migration the charts will display colored cells again. As can be seen, the bar option has been removed, along with row/column orientations (now formatting is always done per metric).
image

The new automatic conditional formatting control option, which doesn't have a target value:
image

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by graceguo-supercat** [comment]
Hi @villebro i tested this PR in our sandbox environment. i saw upgrade running correct:
```
INFO  [alembic.runtime.migration] Running upgrade 31b2a1039d4a -> 143b6f2815da, migrate pivot table v2 heatmaps to new format
```
But after that, the chart still not populated a `CUSTOMIZE METRICS`
Screen Shot 2021-08-04 at 12 43 15 AM

Before the chart is configured to display as this:
Screen Shot 2021-08-04 at 12 44 52 AM

**Comment by villebro** [comment]
@graceguo-supercat this PR still needs to bump `superset-ui` (we still don't have the required https://github.com/apache-superset/superset-ui/pull/1264 PR in). We're bumping today, after that this should work.

**Review by graceguo-supercat — APPROVED** [review]
LGTM

**Comment by henryyeh** [comment]
🏷️ 2021.31

**Pull request merged**
