### PR TITLE
[sql lab] Make sql editor resizable

### PR DESCRIPTION
**Pull request by dmigo**
Implements #2237

The idea of this PR is to be able to resize the editor of the sql lab.

### CODE REVIEW

**Comment by mistercrunch** [comment]
Glad to see you're working on this. There was some issues in SQL Lab around resizing the window where the height of some components wouldn't be altered as they should. Please make sure resizing the window work well along with this set of changes.

**Comment by dmigo** [comment]
@mistercrunch not quite sure what you mean, I encountered 2 problems while working on this PR.  
**First**: it wasn't possible to resize `react-ace` properly it had some issues. This one is solved by updating to the version `5.1.2`.  
**Second**: Sql Lab has one hack in it. This hack adjusts sizes of some parts of the page. I didn't fix it, since it is out of scope of the PR, however I have a couple of ideas about it.

**Comment by mistercrunch** [comment]
I pulled the branch and tried it. It mostly works but it's a little funky. We went from single-page app to no-quite that where there's one too many scrollbars on the lower right panel.

I don't think the lower-right panel should have a fixed height anymore. Meaning if/when you scroll down to look at the data in the result pane the SQL Editor would flow out of the screen, leaving more place for to browse the results.

**Comment by mistercrunch** [comment]
I'd also like to have a minimum height constraint on the SQL editor, so that users can't get confused as to it completely disappearing.

**Review by mistercrunch — CHANGES_REQUESTED** [review]
no scroll on the lower right and minimum height on SQL editor

**Comment by dmigo** [comment]
@mistercrunch got it 👍

**Comment by dmigo** [comment]
@mistercrunch 
It is going to be hard with 
> no scroll on the lower right  

On the lover right we have `react-virtualized` which[ doesn't seem to have this out of the box](https://stackoverflow.com/questions/45553667/how-to-add-a-scroller-to-the-nesting-element-of-the-react-virtualize-table).  
We could create our own component for that, or try to extend [`react-virtualized`](https://github.com/bvaughn/react-virtualized). Either way it seems to me as a separate big task to me. What would you say?

**Comment by mistercrunch** [comment]
Right, sorry I didn't think that through. Then it should probably just be a full-page app, same as jsfiddle works for me.

**Comment by dmigo** [comment]
@mistercrunch it is ready in terms of code. Should I squash all the changes into one commit?

**Comment by mistercrunch** [comment]
Not need to squash, we use the Github "Squash and merge" button. Let me try it out!

**Comment by mistercrunch** [comment]
img

**Review by mistercrunch — APPROVED** [review]

**Comment by mistercrunch** [comment]
@dmigo found a bug related to this, when popping a new tab things don't init right:
screen shot 2017-08-23 at 9 31 45 am

**Comment by dmigo** [comment]
@mistercrunch sorry, didn't notice the comment in time. Did #3363 solved all the problems?

**Comment by mistercrunch** [comment]
Everything is good now, leveraging `react-split-panes` abstracted a lot of the complexities

**Pull request merged**
