### PR TITLE
feat(cross-filters): using verbose map in applied cross-filters

### PR DESCRIPTION
**Pull request by Always-prog**
### SUMMARY
Displaying human-readable column names in cross-filters by using verbose mapping from the chart's datasource.

### BEFORE

Screenshot_46

### AFTER 
Screenshot_45

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [x] Required feature flags: DASHBOARD_CROSS_FILTERS
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by Always-prog** [comment]
@villebro Hello! Can I get review of my PR?

**Review by villebro — APPROVED** [review]
LGTM with one stylistic nit and tested to work as expected. Great work btw!

**Comment by kgabryje** [comment]
Looks great, thanks for contribution!
1 nit -  when we do `const charts = useSelector(state => state.charts);`, the component will rerender each time any chart changes (for example, when a dashboard with 10 charts loads, the charts change their `chartStatus` `loading -> success -> rendered` - that's 30 changes/rerenders already).
It looks like `getVerboseMap` actually only needs chart ids, not full chat objects, so could we do something like `const chartIds = useSelector(state => Object.keys(state.charts));` instead?

**Comment by Always-prog** [comment]
@kgabryje Thank you for review! 
I'll optimize `getVerboseMapsForCharts` function today

**Comment by kgabryje** [comment]
Another improvement that we could use to DRY things up is to transform `getVerboseMapsForCharts` into a react hook, so that we don't need to select datasources and charts in each component where we want to get the verbose maps. But that's optional 🙂

**Comment by Always-prog** [comment]
@kgabryje Hello!
I updated `GetChartsVerboseMaps ` function, it return charts verbose maps one time without rerender, and it doesn't need any params.
Can you please review code? 
Thank you!

**Comment by kgabryje** [comment]
@Always-prog Tested, works great! 1 last nit - the naming conventions for functions is to start them with lowercase letter + if it's a hook, start the name with `use`. Could you rename `GetChartsVerboseMaps` to `useChartsVerboseMaps`?

**Comment by Always-prog** [comment]
@kgabryje Of course, renamed in the last commit.

**Comment by Always-prog** [comment]
@kgabryje Hello!
I renamed the function, can you review my code please?

**Review by kgabryje — APPROVED** [review]
LGTM!

**Pull request merged**
