### PR TITLE
[setup] Using pip-tools to create requirements.txt

### PR DESCRIPTION
**Pull request by john-bodley**
@mistercrunch this is an approach we could take for automatically ensuring that the build was deterministic by autogenerating `requirements.txt` from `setup.py`.

Note this approach pins all sub-modules (in effect the output of `pip freeze`) which wasn't viable when we supported both Python 2 and Python 3.

### CODE REVIEW

**Comment by victornoel** [comment]
@john-bodley why not use pipenv directly? It is meant to solve this situation I think…

**Comment by mistercrunch** [comment]
@victornoel this article seems to be leaning towards pip-tools over pipenv and is fairly recent from what I gather: https://twigstechtips.blogspot.com/2018/05/python-comparison-of-pipenv-vs-pip-tools.html

**Comment by mistercrunch** [comment]
BTW it's ideal to have deterministic builds, but in some cases it prevents us from ever knowing about issues that occur when people simply `pip install superset` (which is based purely on what's in the `setup.py`, which is not pinned). I wonder if we should have an extra slot in the build matrix that would `pip install -e .` and not `pip install -r requirements.txt` to let us know that something is up with the vanilla build.

**Comment by mistercrunch** [comment]
LGTM

**Comment by victornoel** [comment]
@mistercrunch thanks for the link :)

**Pull request merged**
