### PR TITLE
docs: update changelog for 1.0.0

### PR DESCRIPTION
**Pull request by eschutho**
### SUMMARY
Changelog for 1.0

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by eschutho** [comment]
@garden-of-delete @villebro

**Review by betodealmeida — APPROVED** [review]
672 PRs! :O

**Comment by garden-of-delete** [comment]
Thanks for doing this @eschutho!

**Comment by eschutho** [comment]
Yeah you bet. I will mention that @betodealmeida and @hughhhh and @lyndsiWilliams also all chipped in because it was such a large changelog and I kept getting rate limited. We may need to find a workaround instead of splitting up the commits into chunks like I did. Also cc @dpgaspar for any ideas. 🙏

**Comment by eschutho** [comment]
🏷 v1.0.1

**Comment by villebro** [comment]
@eschutho yeah, we really need to add support for GH tokens to the script so we don't get rate limited. This should probably be done before we start working on 1.1.0. FYI I removed the `1.0.1` tag as the changelog updates where already in the `1.0` branch (I'll make a note to add a step to the release instructions to update `CHANGELOG.md` and `UPDATING.md` on `master` after a release candidate is promoted to an actual release).

**Comment by dpgaspar** [comment]
@villebro true it's annoying and time consuming. I'll update the script to support github token (Auth)

**Pull request merged**
