### PR TITLE
fix(explore): Disable saved metric name edit in Metric popover

### LINKED ISSUE #12578: [explore]metrics control temporary adjustment
Based on user feedback on the new Explore control panel, we propose 2 small changes as a temporary solution during the process of bigger control field refactoring and redesign in Explore. 

1. temporary disable editing metric name for saved metric tab 
2. switch SAVED metric and SIMPLE tabs

### PR DESCRIPTION
**Pull request by kgabryje**
### SUMMARY
Currently a user can edit a name of saved metric in popover, but the change doesn't show anywhere, because this feature is not implemented for saved metrics yet. This PR disables name edit feature for saved metrics.
Also, now "Saved" is a default tab in Metrics popover. When user opens a popover, "Saved" tab is selected by default, unless there are no saved metrics for current dataset.
Closes https://github.com/apache/superset/issues/12578

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
https://user-images.githubusercontent.com/15073128/104911028-8532f400-598a-11eb-89d8-2e3f0117f649.mov

### ADDITIONAL INFORMATION

- [x] Has associated issue: https://github.com/apache/superset/issues/12578
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

CC: @junlincc @villebro @ktmud

### CODE REVIEW

**Comment by adam-stasiak** [comment]
Tested manually - Order of tabs has changed in compare to old version 🍏 and title is not editable for saved tab 🟢 .

**Comment by zhaoyongjie** [comment]
It is a little strange to adjust the order of tabs depending on whether the dataset contains saved metrics or not.

thank you for your fix.

**Comment by junlincc** [comment]
> It is a little strange to adjust the order of tabs depending on whether the dataset contains saved metrics or not.
> 
> thank you for your fix.

right.......we should add tooltip or even enable user to save a ad hoc metric to saved metrics in the popover in the near future. 
as i'm getting more familiar with Superset, i do see advanced and enterprise users tend to use saved metrics more often. placing Saved tab first in the modal can encourage users to use and create reusable metrics across team and organization.

**Comment by ktmud** [comment]
+1 on allowing saving adhoc metric in place.

I think this PR looks great. Just one more thing, can we show the name (or verbose name if available) of the saved metric instead of "My metric"?

**Comment by junlincc** [comment]
> +1 on allowing saving adhoc metric in place.

will have to wait until metrics refactoring work is done. @zhaoyongjie

**Comment by villebro** [comment]
> +1 on allowing saving adhoc metric in place.
> 
> I think this PR looks great. Just one more thing, can we show the name (or verbose name if available) of the saved metric instead of "My metric"?

Agreed, this would be really nice. Also, showing "My Metric" for simple/custom metrics is slightly confusing as the metric will not show up as such on the chart. It might be more intuitive to show the title as it will be rendered with a dark grey color if the user hasn't provided a custom title to show what the metric will actually be called. In the screenshot below we would show "MAX(gender)" instead of "My Metric" in the title.
image

**Comment by kgabryje** [comment]
@ktmud @junlincc @villebro Done

https://user-images.githubusercontent.com/15073128/105062356-d0c4cb00-5a7a-11eb-9360-ca224491770e.mov

**Comment by ktmud** [comment]
@kgabryje can we make the title change more "responsive", i.e. change as soon as users have selected an item from the dropdown or switched tabs?  Not a blocker if it requires too much refactoring, though.

**Comment by kgabryje** [comment]
@ktmud That was my plan at first, but we keep current values of edited metrics in a state of component that is a sibling of popover title component. So we'd have to either pass the state to a parent and down to popover title or move the edited metric's state to parent component (perhaps with Context API?). I thought that for now current solution would be sufficient and we could address "responsiveness" later as a separate issue. WDYT?

**Comment by ktmud** [comment]
> I thought that for now current solution would be sufficient and we could address "responsiveness" later as a separate issue. WDYT?

Agreed.

**Review by ktmud — APPROVED** [review]

**Review by junlincc — APPROVED** [review]
LGTM!

Thank you all! Let's keep the scope of each PRs small. 

https://user-images.githubusercontent.com/67837651/105088504-d3122f80-5a50-11eb-9a4b-3af730ba88e4.mov

**Comment by ktmud** [comment]
@kgabryje @junlincc Found a bug one this one: opening a selected adhoc metric should open the SIMPLE or CUSTOM tab, but now it always opens the SAVED tab.

**Pull request merged**
