### PR TITLE
fix(cosmetic): Fix Datasource Modal Out Of Box

### LINKED ISSUE #20236: Datasource Modal's content out of box
## Description

[related PR](https://github.com/apache/superset/pull/20147)

Due to which the modal content's height is limited, but the overflow of that is 'visible'.

### PR DESCRIPTION
**Pull request by Renderz**
### SUMMARY

remove 'overflow: visible' from DatasourceModal component, to fit with the height limit, and show the scrollbar.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

Before
before

After
after

### ADDITIONAL INFORMATION

- [x] Has associated issue: [Fixed #20236](https://github.com/apache/superset/issues/20236)
- [ ] Required feature flags:
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by stephenLYZ** [comment]
Thanks for the contribution! Actually this css snippet can be found in the context of this [issue](https://github.com/apache/superset/pull/13858), so we probably can't remove it easily, but if we verify that the issue is working correctly, I think it's okay to remove it. I think the problem is probably related to this [issue](https://github.com/apache/superset/pull/20147/files#diff-8681971330bf64f19cbbe547d528fe0f78b56787224726fc4d6f2ab4bf31bb47R99). cc @rusackas

**Comment by Renderz** [comment]
> Thanks for the contribution! Actually this css snippet can be found in the context of this [issue](https://github.com/apache/superset/pull/13858), so we probably can't remove it easily, but if we verify that the issue is working correctly, I think it's okay to remove it. I think the problem is probably related to this [issue](https://github.com/apache/superset/pull/20147/files#diff-8681971330bf64f19cbbe547d528fe0f78b56787224726fc4d6f2ab4bf31bb47R99), which is about maxHeight of the modal. cc @rusackas

Thanks for reviewing.
I think other modals may facing the same issue(when actual height is more than max height).

**Review by rusackas — APPROVED** [review]
Approving since this works for the modal in question. As per @stephenLYZ 's point, this might indeed be an issue on other modals. I'm on the fence between just reverting mine to minimize my PR to minimize fallout, or taking this PR and attempting to do a quick audit and fix-forward the others that might be affected.

**Review by stephenLYZ — APPROVED** [review]
LGTM! Thanks for the work!

**Comment by rusackas** [comment]
FWIW, when I run this locally, I'm not seeing the issue that @AAfghahi was tackling in his earlier PR, but I'm spinning up an ephemeral environment, and pinging him for a review, just in case :)

image

image

**Comment by rusackas** [comment]
Looked at the other two modals that allow overflow, and they don't seem so problematic. I think this fix is the better way forward than the revert, but I'll let it simmer for a moment for discussion.

**Comment by rusackas** [comment]
Thanks for fixing this. The Save Chart modal has overflow visible, but looks OK since it's short. Same with the Dashboard's Refresh Interval Modal. We can do this same fix on either, but it makes matters _worse_ on the Refresh Interval modal. If you do this fix on the Save Chart modal, it works fine, but looks a bit goofy as the bottom Select menu goes upward to cover the Input above it. I'll leave them both alone, but I'm open to ideas/consideration.

**Pull request merged**
