### PR TITLE
Visualization for multiple line charts

### PR DESCRIPTION
**Pull request by betodealmeida**
This PR adds a new viz type, `line_multi`. It's similar to the Deck.gl multi, in that it combines different saved charts (of lines) into a single chart. Here's an example combining two charts, one of them with a group by:

screen shot 2018-04-12 at 6 11 04 pm

screen shot 2018-04-12 at 6 11 12 pm

The viz works by fetching all the data for each chart in parallel (in Javascript), and passing the payload to the `nvd3Vis` function. Different time series are padded with `null` at the edges to bypass a bug in `multiChart` when timeseries have different ranges for `x`.

One thing I did in this PR was add a `sectionOverrides` config in `visTypes.js`, so that the datasource selector is not shown in this viz (I'll add it to the Deck.gl multi in a next PR, or I can do it in this one).

### CODE REVIEW

**Comment by mistercrunch** [comment]
Neat. I wonder if there is an easy way to align the ticks on both Y axes so they line up. Not a big deal but all those grey lines look a bit chaotic. If you Google image search “dual axis chart”  you’ll most tools out there align the ticks.

**Comment by betodealmeida** [comment]
screen shot 2018-04-16 at 12 39 41 pm

**Comment by CrystalSun1992** [comment]
which version do u change?

**Comment by CrystalSun1992** [comment]
i try to add a new visualization ,echarts_funnel,but it does not display in the types on the front ,my version is 0.24.0  .  T.T

**Comment by mistercrunch** [comment]
Build is failing :( 
Oh also it could be nice to add an example in `data/__init__.py` this will automatically add test coverage in `viz.py` as all examples get unit tested.

**Comment by betodealmeida** [comment]
The build is failing due to conflicting numpy versions, not sure why that's happening. Will take another look, and also add an example.

**Comment by mistercrunch** [comment]
Let's talk about what to do around filters, it may be easy to pass them as `extra_filters`

**Comment by betodealmeida** [comment]
@mistercrunch, I removed the SQL and filter controls in the last commit. I'll do a separate PR handling them properly, accounting for multiple datasources.

**Comment by mistercrunch** [comment]
Cool, please fix merge conflicts, as this looks like it's ready to be merged.

**Comment by anju-jsl** [comment]
@mistercrunch , can you please let me know when this feature will be released?
Thanks

**Comment by mistercrunch** [comment]
In 0.26.0, should be cut over the next week or two.

**Pull request merged**
