### PR TITLE
fix: update package list with mapbox-gl

### PR DESCRIPTION
**Pull request by hughhhh**
### SUMMARY

When install superset-frontend we starting clean repo. This PR represents the changes need and running `npm install` in these directories:
```
superset/superset-frontend/plugins/legacy-plugin-chart-map-box
superset/superset-frontend/plugins/legacy-preset-chart-deckgl
```

## Error:
```
ERROR in ./plugins/legacy-plugin-chart-map-box/src/ScatterPlotGlowOverlay.jsx 26:0-38
Module not found: Error: Can't resolve 'mapbox-gl/dist/mapbox-gl.css' in '/Users/hugh/src/superset/superset-frontend/plugins/legacy-plugin-chart-map-box/src'

ERROR in ./plugins/legacy-preset-chart-deckgl/src/DeckGLContainer.jsx 29:0-38
Module not found: Error: Can't resolve 'mapbox-gl/dist/mapbox-gl.css' in '/Users/hugh/src/superset/superset-frontend/plugins/legacy-preset-chart-deckgl/src'
```

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by etr2460** [comment]
I thought that @zhaoyongjie just removed this to fix another issue? FWIW, I was wrestling with the above error before, and realized it was because i was `npm install`ing with the `--legacy-peer-deps` option, and replacing that with `--force` fixed it for me. I don't know what the correct solution is, but sharing what i hit today for extra context

**Comment by zhaoyongjie** [comment]
@hughhhh @etr2460 the related PR at [here](https://github.com/apache/superset/pull/17851). I think that `mapbox-gl` installed as a dependence from `react-map-gl`.

**Comment by hughhhh** [comment]
just `npm install mapbox-gl` fixed this issue for me

**Comment by eschutho** [comment]
@hughhhh can we see if we can find a longer-term fix? Any reason why we can't merge your pr? Or maybe we need to have someone run npm install with --force and push up that pr with the updated package-lock.json file.

**Pull request closed without merging**
