### PR TITLE
fix: do not show vertical scrollbar for charts in dashboard

### LINKED ISSUE #12477: [chart]added unnecessary scroll bar to the chart container in Explore and Dashboard
ezgif-6-59395baf91fa

### PR DESCRIPTION
**Pull request by graceguo-supercat**
### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

closes #12477

### CODE REVIEW

**Comment by rusackas** [comment]
I was looking at the same approach, but this does have a side effect... in some situations, particularly with Filter Box, the options spill over, and can't be seen/clicked.

image

**Comment by graceguo-supercat** [comment]
I am not sure how to reproduce the screenshot :) Do you make filter_box container really small?

**Comment by rusackas** [comment]
> I am not sure how to reproduce the screenshot :) Do you make filter_box container really small?

Exactly... I rejiggered the layout, and made the filter box short. Kind of a mean edge case, I admit, but the problem may exist if there are a lot of filters added to a filter box. 

Good news is, I think I see another possible approach. I'll kick the tires a little more and open a PR in a few minutes for evaluation.

**Comment by ktmud** [comment]
@rusackas I just pushed a fix.

**Comment by rusackas** [comment]
Me too: https://github.com/apache/superset/pull/12479

**Comment by ktmud** [comment]
For transparency, what I did is reverting #11580 and adding a proper fix for #11419 , making chart header sticky as mentioned in https://github.com/apache/superset/pull/11580#issuecomment-724181309 .

Chart renders do have access for parent sizes, you just need to pass it on in `transformProps`.

In general, charts should handle its own scrollable area, the chart container should always be unscrollable. We will make sure wherever the charts are rendered, correct parent sizes are passed to `SuperChart`.

**Comment by ktmud** [comment]
Also related: #12153

**Review by rusackas — APPROVED** [review]
LGTM! Less LESS! I like the per-plugin responsibility for setting scroll capability. Seems to work great after some manual testing. Thanks for the quick turnaround @ktmud!

**Pull request merged**
