### PR TITLE
feat(dashboard): add dashboard description field in modal and apis

### PR DESCRIPTION
**Pull request by opus-42**
### SUMMARY
This pull request add a dashboard description field in the dashboard APIs and in the dashboard modal UI.
This evolution is part of an effort to bring documentation of Superset object, discussion about this issue can be found in the following issue: #14510  

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Before 
image

After
image

### ADDITIONAL INFORMATION

- [X] Has associated issue: #14510  
- [ ] Required feature flags:
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by opus-42** [comment]
Hello sorry, I had no time to get back to that feature, trying now to resolve the last front-end test that was blocking, linked to  change in modal format. Should be hopefully good now (tested locally) ! Thks

**Review by riahk — COMMENTED** [review]
@opus-42 This looks good! Can we get it rebased please?

**Comment by opus-42** [comment]
Hello @riahk, thank you ! There was some merge conflicts with master. Could you check out everything is still fine after the merge ? Thanks again

**Comment by riahk** [comment]
@opus-42 It looks like your spec for `PropertiesModal` needs to be updated! A `Certification` section got added that needs to be accounted for. :) Other than that it still looks good!

**Comment by opus-42** [comment]
@riahk 
Thank you, I'll finalise this pull request now so that it can be integrated in subsequent versions.

**Comment by opus-42** [comment]
Hello @riahk. Could you check if everything is ok to be merged ? (CI/CD needs review) Thanks 🙏

**Comment by geido** [comment]
Hello @opus-42. Thank you for moving this forward! I see there's is a conflict. Would you mind checking that out?

**Comment by geido** [comment]
Hello @opus-42 below some comments after manual testing your PR

- When adding a description, applying, saving and then reopening the properties modal again, the description isn't appearing. This happens also when the Dashboard is reloaded, making me think it is not being saved.

https://user-images.githubusercontent.com/60598000/152997097-3a9f1bd9-bab9-4429-ac25-9a31262d18d4.mp4

- What do you think of showing the description in the Dashboards list in a tooltip just after each Dashboard title?

**Comment by opus-42** [comment]
> * When adding a description, applying, saving and then reopening the properties modal again, the description isn't appearing

Ok, this seems only to happen in the dashboard Edit Mode. I'll patch that.

- What do you think of showing the description in the Dashboards list in a tooltip just after each Dashboard title?
Yes that would be a great addition. I'll look at it also.

**Comment by opus-42** [comment]
@geido 

Here is a proposition for the tooltip
image

Or maybe we could put the tool tip after the link (with SupersetTheme color as well)
image

**Comment by geido** [comment]
> @geido
> 
> Here is a proposition for the tooltip image
> 
> Or maybe we could put the tool tip after the link (with SupersetTheme color as well) image
> 
> NB: when put after there is some slight Icon shift on overing due to Tooltip default style
> 
> ```
> .ant-tooltip-open {
>             display: inline-block;
>             &::after {
>               content: '';
>               display: block;
>             }
>          }
> ```

Hello @opus-42 thanks for the adding. I think the icon on the right is the proper place as it is consistent with the certification icon. I am running CI and spinning up a test env for more testing

**Comment by opus-42** [comment]
Hello @geido. 

https://user-images.githubusercontent.com/33355870/156941000-4818c661-a6c0-4cf8-bb8b-17634c368026.mov

I have completed checks and addition of the tooltip for dashboard description. See the screen record below.
All test have passed and I think everything should now be finally ready !

**Comment by opus-42** [comment]
> @geido Ephemeral environment spinning up at http://35.88.151.201:8080. Credentials are `admin`/`admin`. Please allow several minutes for bootstrapping and startup.

I have just test, I see a refresh issue when changing the description (tooltip does not seems to change). Pushing the fix now

**Comment by kylepapili** [comment]
Any remaining blockers on getting this PR merged? Would love to take advantage of this feature.

**Comment by villebro** [comment]
> Any remaining blockers on getting this PR merged? Would love to take advantage of this feature.

Hello @opus-42 - sorry for letting this slip through the cracks. Can you rebase the PR to resolve the conflicts? I'm happy to help push this through.

**Comment by opus-42** [comment]
Hello @villebro, happy to get back and finalise this as well, but it need to be rebased and somewhat re-written I think following the recent frontend evolution. Let me get through the rebase 😃

**Comment by rusackas** [comment]
I'm for some reason no able to re-start the CI actions on this PR, which I hope are just flaky. I'm going to close and re-open this in hopes that it kick-starts things! 🤞

**Comment by one-data-cookie** [comment]
@michael-s-molina Isn't it a bit of shame to close this, since it's been almost done? Or are there any plans to implement it via a different PR?

**Comment by michael-s-molina** [comment]
> @michael-s-molina Isn't it a bit of shame to close this, since it's been almost done? Or are there any plans to implement it via a different PR?

Yes, it is but the PR is stale as you can see by @rusackas comment that was not replied:

> @opus-42 it's been a while since this PR saw any love, but I think it's safe to say we're all still quite interested in getting this feature merged, if you're able to rebase the PR and help it across the finish line 🤞❤️

@one-data-cookie Are you interested in reopening the PR and work on it?

**Comment by one-data-cookie** [comment]
@michael-s-molina Not at the moment, I'm afraid.

@opus-42 Any chance you'd be able to finish and merge this? 🤞

**Pull request closed without merging**
