### PR TITLE
build: implement codecov carryforward flags

### PR DESCRIPTION
**Pull request by jfrag1**
### SUMMARY
Attempts to implement [carry-forward flags](https://docs.codecov.io/docs/carryforward-flags) for codecov as proposed [here](https://github.com/apache/superset/issues/9930#issuecomment-785978529)

The goal is that for any new commits, codecov will pull coverage data for unchanged areas of the codebase from previous commits, only recalculating coverage for areas of the codebase that have changed.  

### TEST PLAN
Testing will involve waiting for CI to see if the carry-forward flags are working as intended and continuing to tweak until it's working

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by junlincc** [comment]
@jfrag1 thanks for your contribution! can you provide some details in the PR description? thanks!

**Comment by jfrag1** [comment]
The fact that the codecov bot's report only showed six flags rather than the usual seven leads me to believe that this change is at least somewhat functional.

I'm guessing that this branch being about a day behind master is the reason for these coverage changes reported by the codecov bot on this PR.
Screen Shot 2021-03-18 at 4 10 58 PM
I plan on rebasing and re-running CI tonight when fewer actions are queued up to try to isolate the temporary print statement.  If it works as intended, we should see codecov only reporting the python flag.

**Comment by ktmud** [comment]
This indeed seems to be working! Can't believe it is as simple as adding one config value. Thought we'd have to add file name matching for flags or something...

**Comment by Psyruss77** [comment]
Ss

**Review by willbarrett — APPROVED** [review]

**Pull request merged**
