### PR TITLE
feat(native-filters): improve inverse selection indicators

### PR DESCRIPTION
**Pull request by villebro**
### SUMMARY
Currently setting a select filter to "inverse selection" doesn't visually indicate that the emitted WHERE clause is in fact a "NOT IN" as opposed to the normal "IN". This replaces the normal `CheckOutlined` icon with `StopOutlined` when inverse selection is applied. In addition, a new reserved parameter `label` is introduced on `filterState`, which makes it possible to customize the indicator label.

We might also want to consider adding support for being able to pass `ReactNode` labels to be able to further customize the indicator label. If this seems like a good approach, I'll add the `label` property to the `DataMask` type in `@superset-ui/core`.

### BEFORE
Currently the dropdown icon for both regular and inverse selection are a checkmark:
image

The filter indicator also only shows the values as such, without indicating that the values are excluded:
image

### AFTER
Now the dropdown icon signals that the selected values are excluded:
image

In addition, the filter indicator text now signals that the selected values are in fact excluded, not included:
image

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by junlincc** [comment]
this is much clearer than before already! can we implement the same icon in Explore NOT IN? thank you Ville!

**Comment by villebro** [comment]
> can we implement the same icon in Explore NOT IN?

@junlincc do you mean here instead of "NOT IN"?

image

**Review by kgabryje — APPROVED** [review]
That looks really good!

**Comment by junlincc** [comment]
> @junlincc do you mean here instead of "NOT IN"?

yes, but i mean the check mark showing in the "NOT IN" select could be confusing. this one is good to go! thank you so much! 🟢

**Comment by villebro** [comment]
> > @junlincc do you mean here instead of "NOT IN"?
> 
> 
> 
> yes, but i mean the check mark showing in the "NOT IN" select could be confusing. this one is good to go! thank you so much! 🟢

Ah yes of course, now I understand 😄 I will follow up later with this addition!

**Pull request merged**
