### PR TITLE
feat(jinja): add option to format time filters using strftime

### PR DESCRIPTION
**Pull request by villebro**
### SUMMARY
A continuation on #30142, making it possible to format `from_expr` and `to_expr` using `datetime.strftime`. This is handy if the target column is string based using a custom format, like `YYYY-MM-DD`, which tends to be the typical partitioning scheme, and we want to avoid having to cast the column to a temporal type.

### AFTER

Now you can format like this (assuming `my_date` is a `VARCHAR` with `YYYY-MM-DD`):
```python
{% set time_filter = get_time_filter(strftime="%y-%m-%d") %}
{% set from_expr = time_filter.from_expr %}
{% set to_expr = time_filter.to_expr %}
SELECT
...
{% if from_expr or to_expr %}WHERE 1 = 1
{% if from_expr %}AND my_date >= '{{ from_expr }}'{% endif %}
{% if to_expr %}AND my_date < '{{ to_expr }}'{% endif %}
{% endif %}
```

This will render
```sql
SELECT
  ...
WHERE 1 = 1
AND my_date >= '2024-08-03'
AND my_date < '2024-09-03'
```

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by michael-s-molina — APPROVED** [review]

**Comment by Nebula1230** [comment]
Hello, It seems that this macro doesn't work for me
Screenshot from 2024-10-10 18-52-48
Can someone enlighten me on that how can i use it?

**Comment by villebro** [comment]
Please double check your python syntax before posting here. You're missing a comma before `remove_filters`.

**Comment by Nebula1230** [comment]
> Please double check your python syntax before posting here. You're missing a comma before `remove_filters`.

Oh i'm sorry it was just trying to reproduce the query because i was trying different thing. But it doesn't work even with the comma

**Comment by villebro** [comment]
In general, `remove_filter` will only work if you're targeting a specific column: you have `column="my_col"` in the call. Also note, that this is not available on any official release yet, only master branch, and will become generally available in 5.0.

**Comment by Nebula1230** [comment]
Ah thank you so much, i should then stick for the variables to_dttm and from_dttm for the moment

**Comment by qianglitaotao** [comment]
i have the same question on superset 4.0.2. i use :{% set time_filter = get_time_filter(column="start_time",default='',target_type=DATETIME, strftime='%y-%m-%d %H:%M:%S',remove_filter=True) %} , it did not work . 

if it is usable until 5.0  , how can i get the  time range filter that i needed , while there is  two time range filter in dashboard. like:
start_time  、  end_time

I want to use the two time range filter like this:
{% set start_time_filter = get_time_filter(column="start_time",default='',target_type=DATETIME, strftime='%y-%m-%d %H:%M:%S',remove_filter=True) %}
{% set end_time_filter = get_time_filter(column="end_time",default='',target_type=DATETIME, strftime='%y-%m-%d %H:%M:%S',remove_filter=True) %}
{% set start_from_expr = start_time_filter.from_expr %}
{% set start_to_expr = start_time_filter.to_expr %}
{% set end_from_expr = end_time_filter.from_expr %}
{% set end_to_expr = end_time_filter.to_expr %}
select 
 *
from (select 
 cast('2024-10-12 13:12:11' as DATETIME) as start_time,
 cast('2024-10-12 16:12:11' as DATETIME) as end_time,
 'zhangsan' as name
 union all
 select 
 cast('2024-10-11 13:12:11' as DATETIME) as start_time,
 cast('2024-10-11 16:12:11' as DATETIME) as end_time,
 'lisi' as name) t
{% if start_from_expr or start_to_expr or end_from_expr or end_to_expr %}WHERE 1 = 1
{% if start_from_expr %}AND start_time >= '{{ start_from_expr }}'{% endif %}
{% if start_to_expr %}AND start_time < '{{ start_to_expr }}'{% endif %}
{% if end_from_expr %}AND end_time >= '{{ end_from_expr }}'{% endif %}
{% if end_to_expr %}AND end_time < '{{ end_to_expr }}'{% endif %}
{% endif %}

**Comment by Nebula1230** [comment]
You can find it in the beginning of the superset documentation related to jinja templation, you have to use superset variables to_dttm and from_dttm

**Comment by qianglitaotao** [comment]
邮件已收到，谢谢！

**Comment by qianglitaotao** [comment]
image

I have use this : start_time >= cast('{{ from_dttm }}' as datetime) AND start_time < cast('{{ to_dttm }}' as datetime) ,and it is work, but it only get the last time range filter ,  i want to get start_time filter

**Comment by villebro** [comment]
@qianglitaotao that's not how time filters work: you should **not** have two or more time filters on a dashboard affecting the same charts. A single time filter will convert into a start and end date. Feel free to play around with the various options (Last, Advanced, Custom etc) to see how you can use it.

**Pull request merged**
