### PR TITLE
chore: Select component refactoring - DateFilterControl - Iteration 5

### PR DESCRIPTION
**Pull request by geido**
### SUMMARY
It replaces the react-select Select component with the Antdesign one in the DateFilterControl components.

### BEFORE / AFTER

https://user-images.githubusercontent.com/60598000/124779721-4bf33e00-df42-11eb-80bb-9e5ceb8820f0.mp4

https://user-images.githubusercontent.com/60598000/124779858-675e4900-df42-11eb-89d6-c9971beccd70.mp4

### BEFORE / AFTER

https://user-images.githubusercontent.com/60598000/124779875-6c22fd00-df42-11eb-9180-dfc864e493e1.mp4

https://user-images.githubusercontent.com/60598000/124779886-6e855700-df42-11eb-8f13-7943f814e38f.mp4

### TESTING INSTRUCTIONS
1. Open a chart, for instance, the Cross Channel Relationship example chart
2. Click on the "Time" tab 
3. Click on "No filter" under "TIME RANGE"
4. Select a "RANGE TYPE" and observe the behavior
5. Choose the "RANGE TYPE" and set it to "Custom"
6. Set the "START (INCLUSIVE)" and "END (EXCLUSIVE)" options and observe the behavior

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by geido** [comment]
@adam-stasiak @jinghua-qa @junlincc @rosemarie-chiu @rusackas help with testing really appreciated! thanks

**Review by michael-s-molina — APPROVED** [review]

**Comment by michael-s-molina** [comment]
Beautiful 🚀

**Review by pkdotson — APPROVED** [review]
LGTG!

**Pull request merged**
