### PR TITLE
refactor: icon to icons for filterbadge components

### PR DESCRIPTION
**Pull request by pkdotson**
### SUMMARY
This pr migrates the original icon to icons for filterbadge components. Specifically the crossfilter filter icon

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

Screen Shot 2021-07-06 at 12 32 45 PM

### TESTING INSTRUCTIONS
To test you must enable native filters and cross filtering.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by rusackas** [comment]
/testenv up FEATURE_DASHBOARD_CROSS_FILTERS=true FEATURE_DASHBOARD_NATIVE_FILTERS=true

**Review by zhaoyongjie — APPROVED** [review]
LGTM

**Pull request merged**
