### PR TITLE
fix(native filter): clean deleted parent filter ids

### PR DESCRIPTION
**Pull request by justinpark**
### SUMMARY
When a parent filter has been removed, the cascadingParentIds has not updated accordingly.
This regression caused by the [redux state mutation migration](https://github.com/apache/superset/pull/23535/files#diff-a0c8ea9949521964211b0fd6059011e3deb0294a81aee69de9c17e780bb8e5b3R316-R320) which remains `filterConfigMap` in obsolete dependency metadata because the redux action will update `state.nativeFilters` whereas `filterConfigMap` references from `state.dashboardInfo.metadata.native_filter_configuration`

This commit updates the `cleanDeletedParents` logic to retrieve the updated `filterConfigMap` data and then pass to the onSave payload in order to sync the latest updates.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
After:

https://github.com/apache/superset/assets/1392866/154684ec-b1da-4814-bd29-cb593ad2c7c7

Before:

https://github.com/apache/superset/assets/1392866/11d11646-3fac-4e06-8d67-01b29f1a5e8a

### TESTING INSTRUCTIONS
Create a native filter and links a dependent filter
Hit save and then edit the native filter again
Remove the dependent filter only and then save
mouse over the filter has the dependent filter and see an error

### ADDITIONAL INFORMATION
- [x] Has associated issue: https://github.com/apache/superset/issues/24729
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by john-bodley** [comment]
Thanks @justinpark for the fix. I pushed a commit which includes a migration to remedy any corrupted dashboards. It would be good to verify said change in your environment.

Note you'll need to rebase your branch (and update the Alembic migration file) as `863adcf72773` is the latest revision on `master`.

**Review by michael-s-molina — APPROVED** [review]
LGTM. Thank you for the fix and added tests!

**Comment by justinpark** [comment]
> Thanks justinpark for the fix. I pushed a commit which includes a migration to remedy any corrupted dashboards. It would be good to verify said change in your environment.

Confirmed the migration script worked well and the corrupted cascadingParentIds has been cleaned.

**Comment by john-bodley** [comment]
FYI @eschutho I wonder if you want to cherry-pick this into 2.1.1. Note there's a DB migration and thus you'll have to handle the version.

**Pull request merged**
