### PR TITLE
[requirements] Bump pydruid version

### PR DESCRIPTION
**Pull request by john-bodley**
### CATEGORY

Choose one

- [ ] Bug Fix
- [ ] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [x] Build / Development Environment
- [ ] Documentation

### SUMMARY

This PR bumps the version of `pydruid` to [0.5.6](https://pypi.org/project/pydruid/0.5.6/) which contains a number of bug fixes and the ability to leverage [Druid SQL](https://druid.apache.org/docs/latest/querying/sql) headers. 

### TEST PLAN

CI.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### REVIEWERS

to: @betodealmeida @mistercrunch

### CODE REVIEW

**Review by etr2460 — CHANGES_REQUESTED** [review]
shouldn't this be updated in setup.py?

**Comment by john-bodley** [comment]
@etr2460 `setup.py` defined loose bounds for compatibility requirements. The `requirements.txt` file pins down the actual dependencies.

**Comment by etr2460** [comment]
I would've expected the PR to look like this: https://github.com/apache/incubator-superset/pull/7832

Updating the min bounds in `setup.py`, then running the script at the top of `requirements.txt`. Seems like you wouldn't want to modify an auto-genned file

**Comment by etr2460** [comment]
spoke offline and i kinda understand how python deps work now. this should be fine 🤷‍♂

**Review by mistercrunch — APPROVED** [review]

**Pull request merged**
