### PR TITLE
feat(chart): add feature flag that displays the data pane closed by default

### PR DESCRIPTION
**Pull request by victorarbuesmallada**
### SUMMARY
Currently the **Data** section in the Chart screen is open or not depending on what the user has done previously in other charts (i.e. a flag is kept in the local storage that determines if the**Data** section will need to be render or not depending of what the user's done in other chart screens).
Our team decided that we want that screen to have that section collapsed until the user clicks on the caret that opens it.

### TESTING INSTRUCTIONS
After setting the new flag (DATAPANEL_CLOSED_BY_DEFAULT) to true, every time the chart screen is loaded it should have the **Data** section collapsed.

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [x] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [x] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by doornot** [comment]
@stephenLYZ  please help review.

BTW, if this pr be approved and merged, will CI publish [@superset-ui/embedded-sdk](https://www.npmjs.com/package/@superset-ui/embedded-sdk) automatically?

**Review by zhaoyongjie — COMMENTED** [review]
@Painyjames Thanks for the PR. It's a pretty useful feature for increasing the loading pace on Explore. 

I found an issue when I tested this on my local environment. First, setting FF was enabled. Then, opened an existent Chart, the DataPanel was expected as closed for now.  Next, opened the DataPanel and return to the Charts list. Finally, reopened the previous Chart but the DataPanel was white and seemed opened.

image

**Comment by Painyjames** [comment]
@zhaoyongjie I was not able to reproduce that issue locally, as it seems to be working fine. Could you spin up a testing instance with that flag on?

**Comment by Painyjames** [comment]
I've replicated that locally and recorded the behaviour on this PR's branch:
[gif](https://imgur.com/a/98LDzFp)

**Comment by Painyjames** [comment]
hi @zhaoyongjie , it appears collapsed when you enter into that chart, I think the carets might be odd in the new version though. I'll take a video shortly.

**Comment by Painyjames** [comment]
cannot upload videos directly on github, but I've uploaded that [here](https://streamable.com/zon1y5)

**Comment by Painyjames** [comment]
@zhaoyongjie you were right, I needed to make sure the padding was right on the `ExploreChartPanel` component as well.
I've committed some changes that amend that and hopefully it's all fine now.

**Review by zhaoyongjie — APPROVED** [review]
LGTM! I love this new feature since it reduces explore page loading time.

**Pull request merged**
