### PR TITLE
fix: safe removal of empty tab with scoped filters

### PR DESCRIPTION
**Pull request by rusackas**
### SUMMARY
Fixes a bug where some tabs couldn't be deleted due to native filters that point to no-longer existing charts within the tab.

This PR fixes the acute issue, but there's room for improvement! Whenever a chart is removed, we should
1) confirm that no filter is scoped to that missing chart any longer.
2) (optional) if the filter no longer has ANY charts within scope, we could ask the user if they want to delete it.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

Before:
before

After:
After

### TESTING INSTRUCTIONS

To repro the issue (prior to this PR):

1) Make a dashboard
2) Add tabs
3) Add a chart to a tab (I just used a table)
4) Add a native filter scoped to that chart.
5) (Problem 1) Try to delete the tab containing the chart with the scoped filter. You get an ugly error.
6) Remove the chart with the scoped filter, optionally saving the dash
7) (Problem 2) Try to delete the tab again. Even with the chart gone, you still can't remove the tab.

With this PR, you should be able to remove the tab _with or without_ the chart.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by kgabryje — APPROVED** [review]
Lgtm!

**Comment by rusackas** [comment]
@kgabryje if you keep a personal backlog, you might be a good candidate to fix the root cause... the filter _seems_ to still be scoped to a deleted chart. That's probably not good in the long run, but doesn't seem to be a _problem_ for now.

**Comment by rosemarie-chiu** [comment]
🏷 2021.27

**Comment by junlincc** [comment]
LGTM! thanks for the quick fix! did spot a UX issue not caused by this PR, will file separately 
@rosemarie-chiu wanna give a product/QA sign-off checkmark? 😉

After 

https://user-images.githubusercontent.com/67837651/125395984-bfd98000-e360-11eb-9ee0-2111f58a673f.mov

Before(unnecessary long video please skip watching lol )

https://user-images.githubusercontent.com/67837651/125396027-cbc54200-e360-11eb-9788-ee2231dde026.mov

https://user-images.githubusercontent.com/67837651/125396057-d7186d80-e360-11eb-8360-d7b2df693405.mov

**Comment by rosemarie-chiu** [comment]
Tested with multiple filter some scope to all, some scope to specific tabs. LGTM!

**Review by rosemarie-chiu — COMMENTED** [review]
Tested issue fixed. Tabs with native filter can be deleted successfully.
✅ QA Product sign off

**Pull request merged**
