### PR TITLE
fix: row component handler is visible

### LINKED ISSUE #12481: [Dashboard] Row component handler is truncated
## Screenshot

Screen Shot 2021-01-12 at 6 18 17 PM

## Before
Screen Shot 2021-01-12 at 6 23 54 PM

## Design input
Need bigger space for the left-border. 
cc @junlincc @zuzana-vej

### PR DESCRIPTION
**Pull request by kkucharc**
### SUMMARY
In dashboard's edit mode menu with `delete` and `move` on left was cut by left end of page/browser.
I made equal margin on both sides. The menu is closer the edited row.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
**Before:**
Left margin was more narrow than right one. 
Screenshot 2021-01-13 at 17 47 17

Menu with `move` and `delete` in dashboard edit was truncated:
Screenshot 2021-01-13 at 17 47 37

**After:**
_Without native filters:_
Preview mode:
Screenshot 2021-01-13 at 17 39 47

Edit mode:
Screenshot 2021-01-13 at 17 39 11

_With native filters:_
Preview mode:
Screenshot 2021-01-13 at 17 41 36

Edit mode:
Screenshot 2021-01-13 at 17 42 47

### TEST PLAN
1. Go to any dashboard and check margins
1a. Go to edit mode of dashboard and try edit row of dashboard (on left there will be icon to delete or to move chart)

To test native filters:
Go to `supserset/config.py` and change `"DASHBOARD_NATIVE_FILTERS": False,` -> `"DASHBOARD_NATIVE_FILTERS": True,`

### ADDITIONAL INFORMATION
- [x] Has associated issue: close: #12481
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

cc: @agatapst Can you take a look? I made some changes in your code.
cc: @junlincc @adam-stasiak

### CODE REVIEW

**Comment by ktmud** [comment]
How does it look like when the native filter is expanded? 

I filed a related bug report yesterday: https://github.com/apache/superset/issues/12486

**Comment by adam-stasiak** [comment]
@ktmud looks lite this:
image

image
looks fine to me.

**Comment by agatapst** [comment]
@kkucharc regarding native filters:
- when Filter Bar is hidden, the sidebar should look the same in Dashboard page and Explore page and it does 👍 
Explore sidebar:
Zrzut ekranu 2021-01-14 o 09 59 46
Dashboard sidebar:
Zrzut ekranu 2021-01-14 o 09 59 35

- when Filter Bar is open:
in your PR:
Zrzut ekranu 2021-01-14 o 10 05 37

master:
Zrzut ekranu 2021-01-14 o 10 00 04

I can see there is bigger distance between Filter Bar and Dashboard in your PR, but in my opinion both versions look just fine. If the cost of smaller distance between Native Filter Bar and Dashboard is UI issues in some other component, then I am totally fine with it.

**Comment by junlincc** [comment]
Screen Shot 2021-01-14 at 8 58 38 AM
can we have the icons perfectly centered in the page by adding more padding on the right side?
Screen Shot 2021-01-14 at 8 59 54 AM
Screen Shot 2021-01-14 at 9 01 58 AM

**Review by rusackas — APPROVED** [review]
Code LGTM! Nice and simple. @junlincc 's question is a good one, so I'll leave this open in case you want to increase the gutter between the icons and charts a bit before merging.

**Comment by kkucharc** [comment]
Thanks @rusackas @junlincc for the test and review. I centered horizontally those icons, rebased and removed IMO redundant (top-bottom) padding. Now it looks like this:
Screenshot 2021-01-15 at 17 47 14

Screenshot 2021-01-15 at 17 47 34

Screenshot 2021-01-15 at 17 52 12

**Review by junlincc — APPROVED** [review]
Screen Shot 2021-01-17 at 4 35 09 PM

LGTM, please disregard my last comment. thanks for the fix!

**Pull request merged**
