### PR TITLE
Superset issue #4354 - Properly filter datasources

### PR DESCRIPTION
**Pull request by maver1ck**
#4354 
Properly filter datasources

### CODE REVIEW

**Comment by xrmx** [comment]
It would be very nice to add some tests to avoid regressions :)

**Comment by maver1ck** [comment]
Could you point me the best place for tests ?
I'm rather new in Superset code.

**Comment by xrmx** [comment]
superset.tests.core_tests looks like a place for testing views permissions handling

**Comment by maver1ck** [comment]
@xrmx 
I think access_tests will be better. Looking into it.

**Comment by xrmx** [comment]
@maver1ck AFAIR access_tests are specfic to inviting people to access a dashboard

**Comment by maver1ck** [comment]
Closing this because of https://github.com/apache/incubator-superset/pull/4565

**Pull request closed without merging**
