### PR TITLE
Allowing to specify schema for tables

### LINKED ISSUE #336: Issue in adding tables for Redshift
Hi,

1) I created a connection using 
redshift+psycopg2://username:password@host:5439/dev
2) I clicked on Test Connection. It says "Connection seems ok!"
3) I save it and go back.
4) I click on Sources -> Tables -> New table
5) Give name of table and Database as my newly created Database and click on save. It gives me below error.

screen shot 2016-04-13 at 12 18 28 pm

6) I go back to my Database and see that connection string has become

redshift+psycopg2://username:XXXXXXXXXX@host:5439/dev
I believe password has been masked.
But now when i click on Test Connection it gives error

screen shot 2016-04-13 at 12 20 59 pm

7) When I click on table name, which I created in step 5, it redirects me to error page

screen shot 2016-04-13 at 12 32 38 pm

Not sure, what am I doing wrong.

### PR DESCRIPTION
**Pull request by mistercrunch**
Database that have schemas have been challenging to integrate properly, this PR allows people to specify the schema when creating a table.
closes https://github.com/airbnb/caravel/issues/336

### CODE REVIEW

**Comment by deniszgonjanin** [comment]
This didn't work for me, but I didn't dig too much as to why exactly. I have an alternative PR that I started before I saw this one, which adds a bit less code and seems to work well: #340

**Comment by mistercrunch** [comment]
I think having the schema as a table attribute is ideal as the same database entry can be used.

**Comment by deniszgonjanin** [comment]
coolio. I'll fix up this PR instead and resubmit

**Comment by yml** [comment]
thank you a ton @mistercrunch I have been able to create my first slice in caravel using redshift and a fully qualified name `schema.table`.

**Comment by alanmcruickshank** [comment]
Thanks from me too. @mistercrunch. I can confirm that specifying schema name at table creation on Postgres works without specifying additional flags in the database creation stage (no parameters passed in the JSON blob)

**Comment by shahneil88** [comment]
@mistercrunch @alanmcruickshank @yml 
I have been trying connecting non public schema in Redshift and it seems to work now :smiley: 
But, I cannot add tables, when I have same table name in multiple schema.

**Comment by shahneil88** [comment]
I have opened an issue https://github.com/airbnb/caravel/issues/356

**Comment by alanmcruickshank** [comment]
I see the same thing. Provided that there aren't any other table names
registered with that name already it works fine. One option would be to
allow qualified names at the table creation stage: specifying name
"schema1.tablename" to distinguish it from "schema2.tablename".

On Fri, 15 Apr 2016 04:55 Neil Shah, <notifications@github.com> wrote:

> I have opened an issue #356 <https://github.com/airbnb/caravel/issues/356>
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/airbnb/caravel/pull/330#issuecomment-210274558>
>
-- 

_______
Alan Cruickshank
E: alanmcruickshank@gmail.com
T: +44 770 6851825

**Pull request merged**
