### PR TITLE
chore: Changes the AlertReportModal to use the new Select component

### PR DESCRIPTION
**Pull request by michael-s-molina**
### SUMMARY
Changes the `AlertReportModal` to use the new Select component.

@junlincc @jinghua-qa @adam-stasiak @rusackas 

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
https://user-images.githubusercontent.com/70410625/128703615-6f638594-952a-4c4e-af76-c7318a241275.mov

https://user-images.githubusercontent.com/70410625/128716478-40c29160-fae2-4ba5-bf64-646845fc411f.mov

### TESTING INSTRUCTIONS
- Enable the `ALERT_REPORTS` feature flag.
- Go to the Alerts & Reports in Settings
- Check the replaced selects

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by geido — COMMENTED** [review]
Hey @michael-s-molina this looks good. I have spotted some small glitches that I believe we should review

1. Before changing between Message Content - Chart or Dashboard leave a dropdown open, then change option, then go back to the previous option. You will see the dropdown appears for a moment. I think it should get programmatically closed when changing option to avoid this UI glitch.

https://user-images.githubusercontent.com/60598000/129225871-a09e24ae-36a8-4f99-a252-89b089647d4d.mp4

2. When opening an Async dropdown you will see the "No data" appearing briefly before the data is rendered on screen. I think this is a glitch that was solved some time back but it is now coming back.

I think both issues affect the Select Component throughout the whole project, not specifically related to this PR.

**Comment by michael-s-molina** [comment]
@geido 

> Before changing between Message Content - Chart or Dashboard leave a dropdown open, then change option, then go back to the previous option. You will see the dropdown appears for a moment. I think it should get programmatically closed when changing option to avoid this UI glitch.

Fixed.

> When opening an Async dropdown you will see the "No data" appearing briefly before the data is rendered on screen. I think this is a glitch that was solved some time back but it is now coming back.

Already added to the list of Select improvements.

**Review by villebro — APPROVED** [review]
Code LGTM

**Pull request merged**
