### PR TITLE
docs: small fixes and update of README screenshots

### PR DESCRIPTION
**Pull request by artofcomputing**
### SUMMARY

A small batch of changes, specially targeted at updating Superset screenshots under README, fixing Apache Doris image on list of supported databases, and removing stale information.

### CODE REVIEW

**Comment by artofcomputing** [comment]
BTW, the intro video seems old, should we redo that?

**Review by sfirke — APPROVED** [review]
LGTM!

**Comment by sfirke** [comment]
thanks @artofcomputing !  What does the Doris image change?  The current one seems to be loading okay here: https://superset.apache.org/ when I scroll down.

**Review by rusackas — APPROVED** [review]
LGTM, let us know if you want to fix that one screenshot before merging, or touch that up some other time :) Thanks for this!!

**Comment by artofcomputing** [comment]
> What does the Doris image change? The current one seems to be loading okay here: https://superset.apache.org/ when I scroll down.

Just changed the background to solid white to be the same as other DB engines, it bugs me out every time I see it on GH's README (mine is in dark mode) that I can't read the name properly 👀

**Comment by artofcomputing** [comment]
> The only issue I spotted is that in the Slack example dash, the logo is missing from the top left. 

Ah I didn't catch that, fixed it on my instance and just made a commit, looks good now.

**Pull request merged**
