### PR TITLE
chore(translations): updating pot -> po -> json files (babel 2.9.1)

### PR DESCRIPTION
**Pull request by rusackas**
### SUMMARY

Runs translation scripts (e.g. pybabel) to update .pot and .po files

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by mistercrunch — APPROVED** [review]
I know this is just a draft, but there's nothing controversial here. Feels like progress to merge this. Seems that whole flow is broken now and this fixes some of it.

**Comment by rusackas** [comment]
Keeping this as a draft because it'll potentially overwrite a LOT of translation PRs.

**Comment by rusackas** [comment]
We can discuss it at Town Hall and/or Release Strategy... it might warrant a SIP or some form of consensus to make doing this something that happens at each major version release (since it can undo the work of others, which seems like a breaking change)

**Comment by rusackas** [comment]
Pulling in some new translation work from `master` and troubleshooting some files... should be current now! Also checked through some stuff with @mistercrunch and we believe that these updates should be largely non-breaking, since the pybable library seems pretty great about how it maps translation `msgid` fields, and our flow should not remove "obsolete" .po entries.

**Comment by mistercrunch** [comment]
```
git rm superset/translations/*/*/*.json
```

**Review by michael-s-molina — APPROVED** [review]

**Pull request merged**
