### PR TITLE
fix: upgrade celery to 5.1.0

### PR DESCRIPTION
**Pull request by shawnzhu**
### SUMMARY
Upgrade celery to 5.1.0 to pick up fix of https://github.com/celery/celery/issues/6422 (So that it can connect to Redis 6 with username/pass authentication)

Based on the official guide [Upgrading from Celery 4.x](https://docs.celeryproject.org/en/stable/history/whatsnew-5.0.html#upgrading-from-celery-4-x), here are the 5 steps:

1. [x] Step 1: Adjust your command line invocation - #15053
2. [x] Step 2: Update your configuration with the new setting names - #12560
3. [ ] Step 3: Read the [important notes](https://docs.celeryproject.org/en/stable/history/whatsnew-5.0.html#v500-important) in this document
    - <strike>drops support for python 2.7 & 3.5</strike>
4. <strike>[ ] Step 4: Migrate your code to Python 3</strike>
5. [ ] Step 5: Upgrade to Celery 5.0 - This PR

### TESTING INSTRUCTIONS

See #14925 

### ADDITIONAL INFORMATION

- [x] Has associated issue: #14925 
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by shawnzhu** [comment]
@junlincc Would you please review this one? Notice that there're some break changes including:

1. removal of deprecated celery API: `celery.task.base.Task` -> `celery.Task`
2. enforcing `--app` as celery global option

**Comment by shawnzhu** [comment]
Split the doc change into #15053 to block review/merge of this PR

**Comment by robdiciuccio** [comment]
https://github.com/apache/superset/pull/12560 should land with any Celery upgrade.

**Comment by nytai** [comment]
retriggering ci

**Comment by shawnzhu** [comment]
@nytai Thanks. I need help to deal with the intermittent test failure: https://github.com/apache/superset/blob/745b57745a50a07893a24c929e97d02befb3374a/tests/sql_validator_tests.py#L226-L240

And I remember another test case failed when I tried to merge other 2 dependant PRs but forgot which one it was.

Do you have any suggestion on how to handle such situation?

**Comment by john-bodley** [comment]
Apologies @shawnzhu I didn't see this PR when I drafted https://github.com/apache/superset/pull/15927, but seeing as https://github.com/apache/superset/pull/15927 is passing CI (without conflicts) I think we can close this PR.

**Comment by mistercrunch** [comment]
Closing in favor of https://github.com/apache/superset/pull/15927 that pushes to `5.1.2` instead of `5.1.0` and builds correclty.

**Comment by shawnzhu** [comment]
@john-bodley no need to apologize, I'm happy to see the outcome and glad my preparation became useful!

Can not wait to try this upgrade in new release!

**Pull request closed without merging**
