### PR TITLE
fix(embedded): Guest Role Permissions

### PR DESCRIPTION
**Pull request by sinhashubham95**
### SUMMARY
This fixed the fetching of roles over a guest token. Using this the embedded dashboard can get the roles associated with the guest token.

### TESTING INSTRUCTIONS
curl --location --request GET 'http://localhost:8080/api/v1/me/roles/' \
--header 'accept: application/json' \
--header 'X-guesttoken: {guest_token}'

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by sinhashubham95** [comment]
@geido please check.

**Comment by sinhashubham95** [comment]
@geido can you please check?

**Comment by sinhashubham95** [comment]
@villebro @jinghua-qa can you please check this pr?

**Comment by sinhashubham95** [comment]
@cccs-tom @dpgaspar @eschutho can you please review this pr?

**Comment by sinhashubham95** [comment]
@bkyryliuk can you please check this pull request as you recently changed this file?

**Comment by sinhashubham95** [comment]
@geido @hughhhh @eschutho @villebro @jinghua-qa @bkyryliuk @cccs-tom @dpgaspar can you please check this PR?

**Comment by elpioramirez** [comment]
Thanks for addressing this, I'm trying to implement the guest token and I'm facing the same issue. This approach is great! Hope someone reviews this PR soon.

**Comment by villebro** [comment]
I started CI, will review soon

**Review by villebro — APPROVED** [review]
LGTM, thanks for fixing this!

**Pull request merged**
