### PR TITLE
fix(embedded): add missing GUEST_TOKEN_HEADER_NAME to bootstrap data

### PR DESCRIPTION
**Pull request by ghost**
### SUMMARY

There's a discrepancy between our backend configuration and frontend implementation for GUEST_TOKEN_HEADER_NAME.

We allow customization of GUEST_TOKEN_HEADER_NAME in the backend configuration.
However, this configuration is not being passed to the frontend.

As a result, the ability to customize the header name in the frontend is currently not functional.

https://github.com/apache/superset/blob/bc9eab9902a11543e138005ff1d0ac36e63265ef/superset-frontend/src/embedded/index.tsx#L153-L159

https://github.com/apache/superset/blob/bc9eab9902a11543e138005ff1d0ac36e63265ef/superset/embedded/view.py#L79-L85

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by john-bodley** [comment]
Thanks for the fix @hexcafe. Per [here](https://github.com/apache/superset/blob/896fe854dc3865214325cfceea94824ff41a1b6c/superset-frontend/src/embedded/index.tsx#L156) it seems like the frontend is expecting said header.

**Review by john-bodley — APPROVED** [review]
LGTM. @hexcafe you'll have to run `tox -e pre-commit` locally in order to fix the formatting.

**Comment by suddjian** [comment]
Sorry for this oversight, thanks for the fix :)

**Comment by ryatsuger** [comment]
@john-bodley @john-bodley Would it be beneficial to backport this change to the 4.0 as well? Thanks!

**Comment by hexcafe** [comment]
@john-bodley @suddjian  Thank you for merging this PR. Could we backport this patch to version 4.0? It could be beneficial for future users of version 4.0 who need to embed the dashboard.

**Pull request merged**
