### PR TITLE
feat: make logo link point to welcome page

### PR DESCRIPTION
**Pull request by mistercrunch**
### SUMMARY
New that we have a home page, let's point the logo to it

### CODE REVIEW

**Review by nytai — APPROVED** [review]

**Comment by nytai** [comment]
Additionally, should we also make the home page route `/` and redirect `/superset/welcome` there to preserve old links? I'm not sure of the history here. I always thought the lack of any content on `/` a bit strange.

**Comment by mistercrunch** [comment]
@nytai I think the reason is that it's a bit of a puzzle around how FAB does things and issues around python circular imports. I don't think it's super hard put requires a bit of thinking / refactoring.

**Comment by rusackas** [comment]
Adjusting the route was on our radar for follow-up, when the moon is right. I'd actually wondered if it could just be at `/superset` instead of `/superset/welcome`

The other quandry is if/when we want to add profile/role information to the homepage (perhaps as a sidebar, perhaps as a hero/header) to replace the feature of the user page you could previously get to by clicking the logo.

... or maybe that should all be shoved under the user/account menu in the top right somehow. ¯\\\_(ツ)_/¯

**Comment by ktmud** [comment]
Should we plan adding user profile picture as well? Maybe use gravatar.com to get started?

**Pull request merged**
