### PR TITLE
feat: auto-label PRs that contain db migrations

### PR DESCRIPTION
**Pull request by mistercrunch**
The goal here is simply to auto-assign a GitHub label `risk:db-migration` to every PR that touches that folder. Having a label we can rely on is good so it can be trusted for release automation and other purposes.

I'm closing/reopening https://github.com/apache/superset/pull/26683 while pointing to the `apache` repo as opposed to a fork since security / perms work only on the main fork apparently.

### CODE REVIEW

**Comment by mistercrunch** [comment]
Nice. Looks like it worked. Removing the DUMMY file now, and this should be good to merge.

**Comment by michael-s-molina** [comment]
Thanks for the PR @mistercrunch. This will be really valuable when cherry-picking fixes into patches.

There's a typo here [label-miration-pr.yml](https://github.com/apache/superset/pull/26745/files#diff-e73c82aeefff1ecabfea9fb61d2dd0ba9c15b42a9e47169f8921172639757587). Could you fix it?

**Comment by mistercrunch** [comment]
Ok, fixed the typo, should be good to merge

**Review by michael-s-molina — APPROVED** [review]
LGTM

**Review by rusackas — APPROVED** [review]
approving as codeowner

**Pull request merged**
