### PR TITLE
chore: add some basic instrumentation to Node WebSocket server

### PR DESCRIPTION
**Pull request by benjreinhart**
### SUMMARY
This adds some basic instrumentation to the node WebSocket server. For now, adding two counters:

1. Number of connected clients
2. Number of times the server fails to deliver and event to a client

### TEST PLAN

Unit tests, manual

### CODE REVIEW

**Comment by etr2460** [comment]
I'm curious, what's the value of Prometheus over statsd here? The main superset app uses statsd for metrics and counters currently, so I wonder if we should use the same protocol for both apps

**Comment by benjreinhart** [comment]
@etr2460 there had been talks on the Preset side around moving to Prometheus given a couple of problems we ran into with statsd. @craig-rueda has more context on those.

I agree that being consistent makes sense, so I think for now we can revert back to statsd.

**Review by craig-rueda — APPROVED** [review]

**Comment by etr2460** [comment]
Makes sense. If we want to switch, i think that seems SIP worthy. But would love to learn more about the issues you've been having!

**Review by etr2460 — APPROVED** [review]
lgtm, thanks for adding instrumentation!

**Pull request merged**
