### PR TITLE
fix: Add Sankey diagram with loops support

### PR DESCRIPTION
**Pull request by svdimchenko**
### SUMMARY
- added corresponding plugin to MainPreset.js
- added python class to viz.py file

### TESTING INSTRUCTIONS
- build an image
- run superset with command `docker compose -f docker-compose-non-dev.yml up --build --force-recreate`

### ADDITIONAL INFORMATION
- [x] Has associated issue: https://github.com/apache/superset/issues/18103
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by rusackas** [comment]
Sorry this slipped through the cracks! If you're able to re-open it, we can try to do a better job of seeing it through.

**Comment by bonamim** [comment]
@svdimchenko / @rusackas 

I suggest reopening, as it is important that we have this feature.
We need to use it here too.

I think people are not giving visibility to this problem, so it seems not to be a very used feature.

**Comment by svdimchenko** [comment]
@rusackas it seems I have no rights to reopen it ( could you help with that ?

**Comment by bryan-oliveira** [comment]
This is something that our team would love to get working! Hope that this gets prioritized.

**Comment by rusackas** [comment]
> @rusackas it seems I have no rights to reopen it ( could you help with that ?

I don't either... maybe the branch on your fork is gone, or something?

It might be worth you or @bryan-oliveira copying this to a new branch and opening a fresh PR. 

You might be able to seek help on [Superset Slack](http://bit.ly/join-superset-slack) too, or coordinate the effort a bit more expediently than on github.

**Comment by nicomoya123** [comment]
@svdimchenko Hey,
Do you still want to fix it ?
I can take over if there is no problem from your end.

**Pull request closed without merging**
