### PR TITLE
chore(dependencies): bumping jinja2

### PR DESCRIPTION
**Pull request by rusackas**
### SUMMARY

Just another opportunistic bump. Fixes include:

Fix compiler error when checking if required blocks in parent templates are empty. [#1858](https://github.com/pallets/jinja/pull/1858)

xmlattr filter does not allow keys with spaces. GHSA-h5c8-rqwp-cp95

Make error messages stemming from invalid nesting of {% trans %} blocks more helpful. [#1918](https://github.com/pallets/jinja/pull/1918)

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by mistercrunch — APPROVED** [review]

**Review by mistercrunch — CHANGES_REQUESTED** [review]
Oh, I approved earlier but changed my mind after seeing now that you skip the what appears to be dysfunctional `pip-compile-multi` step (super slow, maybe never-ending?), wondering if that could lead to a future regression when re-generating. As far as I'm guessing, pip-compile does not look into the .txt file for input. I'd make sure to add the right rule in the corresponding `.in` file to prevent regression. Also that tool does do some hash checking and may fail for the next person...

**Review by villebro — APPROVED** [review]

**Comment by rusackas** [comment]
@mistercrunch @villebro am I doing this right?

Ran pip-compile-multi --no-upgrade, and committed everything except where it replaced `.` with my local path to Superset.

**Comment by michael-s-molina** [comment]
I wonder if we should run `pip-compile-multi --no-upgrade` on CI when dependency files change, and fail if there are differences between the output and what's being committed.

**Comment by rusackas** [comment]
> I wonder if we should run `pip-compile-multi --no-upgrade` on CI when dependency files change, and fail if there are differences between the output and what's being committed.

Yep... we should probably have one that does this for all the "this shouldn't change" jobs — translations, npm, pip, maps, etc, all alongside the pre-commit check.

**Review by mistercrunch — APPROVED** [review]

**Comment by mistercrunch** [comment]
LGTM apart from the conflicts. Am I the only for which this takes forever? Any `--verbose` flag or other flags to accelerate this. It's good to know about the `-P` thought, hopefully it scopes down the work and make execution faster.

**Pull request merged**
