### PR TITLE
chore: Pylint downgrade

### PR DESCRIPTION
**Pull request by amitmiran137**
### SUMMARY
it appears pylint gets stuck sometimes when run on the Superset repo. Seems others are running into this, too: https://github.com/PyCQA/pylint/issues/4972

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by villebro — APPROVED** [review]

**Comment by zhaoyongjie** [comment]
Since this issue stuck all PRs, I'll do the fix first.

**Comment by amitmiran137** [comment]
What did you run to re calc the dependencies ? @zhaoyongjie

**Comment by zhaoyongjie** [comment]
@amitmiran137 
run ` pip-compile-multi` at root of repo, then commit only the `pylint` related dependencies, and modify the hash value for the `requirements/testing.txt

**Comment by amitmiran137** [comment]
> @amitmiran137 
> run ` pip-compile-multi` at root of repo, then commit only the `pylint` related dependencies, and modify the hash value for the `requirements/testing.txt`

Where do you get the hash value ?

**Comment by zhaoyongjie** [comment]
> > @amitmiran137
> > run ` pip-compile-multi` at root of repo, then commit only the `pylint` related dependencies, and modify the hash value for the `requirements/testing.txt`
> 
> Where do you get the hash value ?

After running the `pip-compile-multi` command, a hash value will be generated.

**Pull request merged**
