### PR TITLE
Pin FAB to 1.10.0

### PR DESCRIPTION
**Pull request by mistercrunch**
Related to
https://github.com/apache/incubator-superset/issues/5088#issuecomment-394064133

### CODE REVIEW

**Comment by xrmx** [comment]
Isn't it the very same of mine? https://github.com/apache/incubator-superset/pull/5091

**Comment by mistercrunch** [comment]
Oh right. Merging yours.

**Comment by villebro** [comment]
Haha, I had a similar one in, too, I need to pay more attention to other PRs.

**Comment by mistercrunch** [comment]
Merging this one to since other PR targeted 0.25 branch.

**Comment by mistercrunch** [comment]
Pushed `0.25.6` out with this fix btw.

**Pull request merged**
