### PR TITLE
refactor: Removes hard coded colors

### PR DESCRIPTION
**Pull request by michael-s-molina**
### SUMMARY
Removes hard coded colors defined in src/components/styles.ts. The colors defined in this file were used only in the Select component so they were migrated to src/components/Select/styles.tsx and adjusted to conform to the theme colors.

Here is the theme color palette and the corresponding mapping:

Screen Shot 2020-12-09 at 11 33 21 AM

Here are some screenshots of Select component:

Screen Shot 2020-12-10 at 9 04 21 AM
Screen Shot 2020-12-10 at 10 02 38 AM
Screen Shot 2020-12-10 at 10 00 27 AM
Screen Shot 2020-12-10 at 9 03 18 AM

### TEST PLAN
You can view the select component inside Storybooks.

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [x] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by junlincc** [comment]
welcome on board Michael! thanks for the first PR!!  @michael-s-molina

**Comment by michael-s-molina** [comment]
> welcome on board Michael! thanks for the first PR!! @michael-s-molina

@junlincc Thanks! I'm very excited to work with you.

**Review by ktmud — APPROVED** [review]

**Comment by ktmud** [comment]
Welcome onboard, @michael-s-molina ! Thanks for working on this.

Could you also add a screenshot of Select component in real action just for sanity check?

**Comment by rusackas** [comment]
I think the scope of this PR is great, but hoping we can use the theme context via the `<ThemeProvider>` rather than importing/using the `supersetTheme` directly from `superset-ui`

**Comment by michael-s-molina** [comment]
> Welcome onboard, @michael-s-molina ! Thanks for working on this.
> 
> Could you also add a screenshot of Select component in real action just for sanity check?

@ktmud Thanks! I added the screenshots as requested.

@rusackas All styles are now coming from `<ThemeProvider>`. 

The Select component uses a combination of style sources (react-select theme, default theme and theme props). If we have the intention on unifying all this then we should do it in another PR because we may need a bunch of refactoring.

**Comment by ktmud** [comment]
I think current approach makes sense, given how react-select structures its styling. With #11916 in the work, I wouldn't invest too much in the refactoring.

**Comment by ktmud** [comment]
Tested locally and everything looks great.

**Comment by rusackas** [comment]
Congrats on the first merge! Welcome to the community!

**Pull request merged**
