### PR TITLE
Backend only tagging system

### PR DESCRIPTION
**Pull request by betodealmeida**
This is the backend only part of https://github.com/apache/incubator-superset/pull/5524/.

### CODE REVIEW

**Review by xtinec — APPROVED** [review]
LGTM. I'll cherry-pick this into `v0.31` to resolve the everlasting migration problems at Lyft. :)

**Comment by betodealmeida** [comment]
@willgroves just want to double check with you, since you requested in the other PR to not have any frontend files.

**Comment by michellethomas** [comment]
We've been having trouble with this db migration in our sandbox environment. The initial deploy fails (likely due to the db migration timing out), somehow the tag and tagged_objects tables get created but not populated with any data and the alembic_version doesn't upgrade to the latest because of the timeout. So if we try to deploy again it fails because it tries to rerun this migration but the Tag table already exists.

I was assuming that the tables should get added along with the data all on commit at the end, is that not true? Is there a way to optimize this migration? It takes a long time with all of the data we have. cc: @john-bodley @graceguo-supercat

**Comment by mistercrunch** [comment]
DDL operations like table creation cannot be part of transactions. `commit` only apply to DML, not DDL. From my understanding on most DBs, DDL also act as implicit `COMMIT` for ongoing transactions.

**Comment by michellethomas** [comment]
@mistercrunch By "DDL operations like table creation cannot be part of transactions" you mean that the table creation should be in a separate migration than transactions like adding or changing data in tables? Does that mean someone needs to move everything added to Tag and TaggedObject out of this migration?

**Pull request merged**
