### PR TITLE
chore(Dashboard): Simplify scoping logic for cross/native filters

### LINKED ISSUE #30687: Broken use cases appliying native & cross filters on common columns
### Bug description

As commented on issue https://github.com/apache/superset/pull/30438 by @Mainer-g00t, proposed fix broken our usual use case. We are providing service to customers with setup described below.
To deal with high cardinality tables on our database, is not an option for us showing all dimensions we need, so:
1. we split data on as many datasets as dimensions we need to show.
2. we create datasets with a custom jinja snippet, same on all datasets we want to filter.
3. we configure cross-filters to work on desired charts.

Result: by implementing that, we are able to filter several charts minimizing high dimensionality derived issues, increasing queries speed. 

We provide tow gifts showing that configuration working on:
- Superset v 4.0.2: works well
- Superset v4.0.1rc3: broken our approach

Please, consider our use case.

### Screenshots/recordings
- Supserset v4.0.2
sample_sales_dashboard_crossfiltering_distinct_columns_v402

- Supserset v4.1.0rc3
sample_sales_dashboard_crossfiltering_distinct_columns_v410rc3

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Not applicable

### Configuration file: `superset/docker/pythonpath_dev/superset_config.py`

```
# CUSTOM FEATURE FLAGS
FEATURE_FLAGS = {"ALERT_REPORTS": True,
"ENABLE_TEMPLATE_PROCESSING": True,
"ENABLE_TEMPLATE_REMOVE_FILTERS": True,
"DASHBOARD_NATIVE_FILTERS": True,
"DASHBOARD_CROSS_FILTERS": True,
"EMBEDDED_SUPERSET": True,
"DASHBOARD_RBAC": True,
"DRILL_TO_DETAIL": True,
"HORIZONTAL_FILTER_BAR": True,
"ALERTS_ATTACH_REPORTS": True,
"VERSIONED_EXPORT": True}

# CUSTOM FEATURES
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = False
SESSION_COOKIE_HTTPONLY = False
GUEST_ROLE_NAME = "Admin"
WTF_CSRF_ENABLED = False
ENABLE_PROXY_FIX = False
TALISMAN_ENABLED = False
GUEST_TOKEN_JWT_EXP_SECONDS = 28880

```

#### sample_sales_a_product_name
```
--{# Comment it out #}

  {% set from_dttm = '2022-01-01T00:00:00' %}
  {% set to_dttm   = '2022-01-04T04:00:00' %}

{%
  set filters = {
      'product_name'          : filter_values('product_namedistribution_country'),
      'distribution_country'  : filter_values('distribution_country')
    } 
%}



SELECT
  product_name,
  SUM(sales_amount) AS sales_amount
FROM 
  asd.sample_sales_data
WHERE
  -- from datetime
  {% if from_dttm is not none %}
      sale_date >= '{{ from_dttm }}'::DATE
  {% else %}
      AND sale_date >= (DATE_TRUNC('DAY', CURRENT_DATE ) - INTERVAL '2 DAYS')
  {% endif %}
    
    -- to datetime
  {% if to_dttm is not none %}
      AND sale_date < '{{ to_dttm }}'::DATE
  {% else %}
      AND sale_date < (DATE_TRUNC('DAY', CURRENT_DATE))
  {% endif %}
  
  {% for key, values in filters.items() if values %}
   AND {{ key }} IN ('{{ values | join("','") }}')
  {% endfor %}
GROUP BY 1
```

#### sample_sales_d_disitribution_country
```
--{# Comment it out #}

  {% set from_dttm = '2022-01-01T00:00:00' %}
  {% set to_dttm   = '2022-01-04T04:00:00' %}

{%
  set filters = {
      'product_name'          : filter_values('product_namedistribution_country'),
      'distribution_country'  : filter_values('distribution_country')
    } 
%}



SELECT
  distribution_country,
  SUM(sales_amount) AS sales_amount
FROM 
  asd.sample_sales_data
WHERE
  -- from datetime
  {% if from_dttm is not none %}
      sale_date >= '{{ from_dttm }}'::DATE
  {% else %}
      AND sale_date >= (DATE_TRUNC('DAY', CURRENT_DATE ) - INTERVAL '2 DAYS')
  {% endif %}
    
    -- to datetime
  {% if to_dttm is not none %}
      AND sale_date < '{{ to_dttm }}'::DATE
  {% else %}
      AND sale_date < (DATE_TRUNC('DAY', CURRENT_DATE))
  {% endif %}
  
  {% for key, values in filters.items() if values %}
   AND {{ key }} IN ('{{ values | join("','") }}')
  {% endfor %}
GROUP BY 1
```

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### PR DESCRIPTION
**Pull request by geido**
### SUMMARY
PR https://github.com/apache/superset/pull/30438 introduced optimizations to enhance performance by reducing backend requests for cross and native filters. However, due to a lack of clarity around the specific use cases these functionalities are meant to support, and in response to reports of certain broken use cases (such as https://github.com/apache/superset/issues/30687), this PR simplifies the scoping logic to accommodate all use cases while still addressing the original issue of preventing requests for charts that are out of scope.

Specifically:

- When in global scope, all charts will be affected by the filter
- When in specific scope, only the selected charts will be affected by the filter

Fixes https://github.com/apache/superset/issues/30687

### TESTING INSTRUCTIONS
1. Create a native or cross filter
2. Change the scope to be global
3. All charts will be affected by the filter
4. Change the scope to only specific charts
5. Only charts that were selected should be affected by the filter

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by michael-s-molina** [comment]
cc @fmannhardt @Mainer-g00t @fbgeobit

**Review by villebro — APPROVED** [review]
LGTM. Not something that necessarily needs to be addressed here, but I found the duplicated scoping logic in `getRelatedChartsForSelectFilter` and `getRelatedChartsForCrossFilter` surprising. I wonder if that could be DRYed up.

**Comment by michael-s-molina** [comment]
@geido I'm not sure if this bug is related to your PR but it's something really important to make your changes clear for users.

https://github.com/user-attachments/assets/1ab2a1e0-93e9-4714-9eaf-b3ffc4025b87

The applied scopes seems to be correct when loading and highlighting charts. It looks like there's a bug when rendering the scope tab as it's not correctly identifying that not all charts are selected.

**Comment by michael-s-molina** [comment]
https://github.com/user-attachments/assets/96c90e0f-5325-4785-ba2b-243e0adcf27c

Given that the first chart belongs to a different dataset but was selected in the scope:
- Should it indicate that the filter was applied?
- Should the query also apply the filter?

**Comment by geido** [comment]
> * Should it indicate that the filter was applied?
> * Should the query also apply the filter?

@michael-s-molina the backend takes the judgement here about what should be applied and what not. I think if the filter is inapplicable it should not be applied and there should not be an indication as well. The user is informed that the chart will reload by loading when the filters get applied, that should give enough confidence to the user that there was an attempt to apply the filter but it was deemed inapplicable at query time.

> The applied scopes seems to be correct when loading and highlighting charts. It looks like there's a bug when rendering the scope tab as it's not correctly identifying that not all charts are selected.

I believe this issue existed in master due to excessive optimizations of the state. I'have fixed it in the latest commit.

**Review by michael-s-molina — APPROVED** [review]
Thank you for the fix and for addressing the comments @geido!

**Review by rusackas — APPROVED** [review]
Thanks!

**Pull request merged**
