### PR TITLE
feat: allow configuring labels on init job

### PR DESCRIPTION
**Pull request by roeap**
### SUMMARY

Allows to configure labels on init-job pods.

At my work we encourage use of Azure Workload identities. These require to set the `azure.workload.identity/use: "true"` label for the federated credential file to get mounted.

With these changes AAD enabled databases can be used requiring no additional credentials

### TESTING INSTRUCTIONS

Haven't seen any means of testing the helm chart in the repo, but we deployed superset with the current changes, and it worked fine.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by dpgaspar — COMMENTED** [review]
Looks good, please update README with helm-docs

**Comment by roeap** [comment]
Sorry I missed that ... docs are updated now.

**Comment by rusackas** [comment]
This one seems to have fallen off the map. Sorry about that. @roeap would you mind rebasing, and bumping the docs again? Hopefully we can finally get this through ;)

**Comment by villebro** [comment]
So sorry about letting this one fall through the cracks 🙁 I'm closing this in favor of #25681 to get this improvement pushed through ASAP.

**Pull request closed without merging**
