### PR TITLE
refactor: add set data mask to build query

### PR DESCRIPTION
**Pull request by simcha90**
### SUMMARY
Add `setDataMask` to `buildQuery` of charts, this will give to us opportunity to manage external chart data like `ownData` before it comes to component itself on build query stage

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by junlincc** [comment]
@simcha90 could you please add more description to the PR? thanks!

**Comment by villebro** [comment]
Related PR: https://github.com/apache-superset/superset-ui/pull/985

**Comment by simcha90** [comment]
> @simcha90 could you please add more description to the PR? thanks!

added @junlincc

**Review by villebro — APPROVED** [review]
LGTM

**Pull request merged**
