### PR TITLE
feat(database): Add OceanBase support

### PR DESCRIPTION
**Pull request by yuanoOo**
### SUMMARY

[OceanBase](https://www.oceanbase.com/) is an enterprise-level [open source](https://github.com/oceanbase/oceanbase) distributed relational database with high availability, high performance, horizontal scalability, and compatibility with SQL standards.
Although OceanBase is compatible with the MySQL protocol, there are still some differences in data types, SQL syntax, etc.

https://en.oceanbase.com/docs/common-oceanbase-database-10000000001375342
https://en.oceanbase.com/docs/common-oceanbase-database-10000000001375338

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

- after

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [x] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by yuanoOo** [comment]
@john-bodley Can you take a look in your free time.

**Comment by zhaoyongjie** [comment]
@yuanoOo please adding license header in new files, ping me please if you need helping. Thanks for your contributions!

**Comment by yuanoOo** [comment]
> @yuanoOo please adding license header in new files, ping me please if you need helping. Thanks for your contributions!

Thanks for the reminder, I've fixed it. Can you help trigger the github workflow again?

**Comment by yuanoOo** [comment]
@zhaoyongjie  @rusackas Hi, After my review, the reason for the failure of GitHub Workflow does not seem to be related to this PR.

**Comment by zhaoyongjie** [comment]
@yuanoOo I've retriggered the CI.

**Review by zhaoyongjie — APPROVED** [review]
LGTM

**Comment by fairchilddb** [comment]
Can not add oceanbase database when SQLALCHEMY URL contains tenant information please help!
superset version 4.1.1
OceanBase version 3.1.4

**Pull request merged**
