### PR TITLE
[Explore] Add Test SQL button to table explore view

### LINKED ISSUE #5417: [Table config] Add SQL query editor functions in SQL Expression box
Just killed myself trying to edit my SQL formula for a metric in the SQL expression box. Would be really helpful to have the syntax checking/linting/autocompletes of columns from the table - especially with end quotes and parentheses in this box.

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### PR DESCRIPTION
**Pull request by IndexOutOfRange**
### CATEGORY

Choose one

- [X] Bug Fix
- [X] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY
Fix issue https://github.com/apache/incubator-superset/issues/5417
This add a new button to check user SQL function in the table explore view when :
- creating a new fields in a table
- creating a new metrics in a table

- I used the sql_json API to not create a new API
- Used a popup as the test connection button. 
- Launch a query SELECT {expression} FROM {table} LIMIT 1 as suggested in the bug description

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
the button is present in the column tab and metric tab. this display a popup saying OK if it seems OK or display the SQL error :
testsql_feature_popup
testsql_feature
testsql_feature_popup_error

### TEST PLAN
Manual test for the most of it (different column, tables, bases and with user with restricted access or not)

### ADDITIONAL INFORMATION

- [X] Has associated issue: Fix #5417 
- [X] Changes UI : see screenshot
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by willbarrett** [comment]
By "test SQL" it appears you mean "run this arbitrary SQL" - I think we should make it clear in the UI that the content of the field will be executed.

**Comment by IndexOutOfRange** [comment]
Thank you for your feedback. I agree the wording of the button is not clear. I suggest a new wording "Run SQL Expression" with a tooltip indicating "This will run the query to test it".
run_query_tooltip

Open to any other/better suggestion. If we agree on wording/Ui modification I can commit corresponding code.

**Comment by willbarrett** [comment]
@IndexOutOfRange that wording looks much better, thank you for updating. Please do commit the change :)

**Comment by IndexOutOfRange** [comment]
I don't know if you guys have notification on commit but changes are commited and CI passed.

**Comment by villebro** [comment]
To address @willbarrett 's concern, instead of actually running the query, I wonder if it would be feasible to implement some type of sql statement dry run functionality in `BaseEngineSpec`. For instance, in Postgres one can prefix the query with `EXPLAIN`, which returns the following for a valid query:
image
When doing the same for an invalid query, it returns the following:
image
For other dbs without `EXPLAIN`, one could potentially do a `ROLLBACK` at the end or some other trickery.

Personally, I don't particularly like the idea of running a query out of context like this, and can imagine some dbs potentially getting overloaded if the query generates a large number of rows.

**Pull request closed without merging**
