### PR TITLE
Add relative start param for time filters

### PR DESCRIPTION
**Pull request by villebro**
### CATEGORY

- [ ] Bug Fix
- [x] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY
#6721 introduced the possibility to use time filters that end right now as opposed to midnight. However, this also made the start date reference the current time, leading to a moving window. While this might be fine for some use cases eg. line graphs with fine granularity, the full start day is often preferred in bar charts and similar; otherwise the start day will start dropping observations, as the day progresses. This PR introduces a new parameter `DEFAULT_RELATIVE_START_TIME`, which defaults to `today`.

### BEFORE
As can be seen below, when setting `DEFAULT_RELATIVE_END_TIME = 'now'`, the start date starts to drop off observations prior to the current time.
Screenshot 2019-05-16 at 13 57 03

### AFTER
When setting `DEFAULT_RELATIVE_START_TIME = 'today'` and `DEFAULT_RELATIVE_END_TIME = 'now'`, the start date starts at midnight, while the end date is relative to the current time.
Screenshot 2019-05-16 at 16 19 42

### TEST PLAN
Tested to work in practice.

### REVIEWERS
@agrawaldevesh as this extends your original PR, I would be interested in hearing your thoughts on this.

### CODE REVIEW

**Comment by agrawaldevesh** [comment]
lgtm

**Comment by mistercrunch** [comment]
@betodealmeida @john-bodley

**Comment by villebro** [comment]
This got me thinking more broadly about time filters. I think default behaviour for the presets (Last x days/weeks/etc) should apply the time grain to the where clause. For example, when applying a "Last Year" with quarterly grains, the first quarter will almost always have an incomplete set of rows, as the where clause will start somewhere between the start and and of the first quarter. It would be more logical to omit the first quarter entirely to make sure that all quarters are true full quarters. Applying the time grain to the time filter would rake care of this automatically. Thoughts?

**Comment by john-bodley** [comment]
@villebro wold you be able to provide some unit tests?

**Comment by villebro** [comment]
@john-bodley I added unit tests for both relative start and end, and made the `now` case more realistic (was equal to `today` before). I also noticed that relative start/end logic was missing from `QueryObject`, so added that there, too.

**Review by john-bodley — APPROVED** [review]

**Pull request merged**
