### PR TITLE
chore: Bumping pyarrow / pandas

### PR DESCRIPTION
**Pull request by craig-rueda**
### SUMMARY
Bumps pandas to `1.3.4` and pyarrow to `5.0.0`. Note that `6.0.0` is the latest pyarrow, but there are other dependencies with conflicting ranges. Also note that pylint yelled at me about various superfluous "ignores" that I ended up fixing. Hence all the seemingly unrelated changes.

### CODE REVIEW

**Review by zhaoyongjie — APPROVED** [review]
LGTM

**Comment by cwegener** [comment]
pyarrow 6.0 is the minimum requirement to use the python 3.10 wheel for pyarrow.
Without pyarrow 6.0, installing superset under python 3.10 becomes almost impossible due to the difficulty of compiling pyarrow from source.

I can upgrade easily to pyarrow 6.0 with only a few dependency changes (thereby allow me to run superset with python 3.10):

1. Remove pinning on `pypackaging` 21.0 (thereby allowing 21.3)
2. Remove version block that blocks `pyparsing` version upgrades to 3.0 and higher (thereby allowing pyparsing 3.0.6)
3. Remove pinning on pylint 2.9.6 (thereby allowing 2.12.2)

@craig-rueda Do you see any problems with the above changes?

The upgrade block to pyparsing 3.0 was introduced in #11418  by @zhaoyongjie  . I suspect that a review and some testing of the time picker feature is required to assess compatibility with pyparsing 3.0.6

**Comment by craig-rueda** [comment]
I think it should be fine. I'll test it out on M1 hardware to be certain in the next day or so. That's the only potential issue I know of.

**Comment by cwegener** [comment]
FIY, I have been running a local dev set up (no docker, just plain python 3.10 on Arch Linux) without problem with the above changes. I am certainly not claiming to have done any sort of rigorous testing.

Let me know if you would like me to open an issue / PR for this dependency update change.

**Pull request merged**
