### PR TITLE
fix: Time filter position and click in Horizontal FilterBar

### PR DESCRIPTION
**Pull request by geido**
### SUMMARY
Fixes positioning of the Time filter popover as well as a bug that would close the popover when clicking on the filter from within the Horizontal FilterBar dropdown container.

### BEFORE

https://user-images.githubusercontent.com/60598000/205947478-9a0234a2-5f85-438b-8816-f0b25567e826.mp4

### AFTER

https://user-images.githubusercontent.com/60598000/205947555-cc029f0c-7f80-4c7b-bc8a-f97eea32c24c.mp4

### TESTING INSTRUCTIONS
See repro steps in the videos

### ADDITIONAL INFORMATION

- [] Has associated issue:
- [x] Required feature flags: HORIZONTAL_FILTER_BAR
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by michael-s-molina** [comment]
Tagging @diegomedina248 too.

**Review by michael-s-molina — APPROVED** [review]
LGTM. Can we get @jinghua-qa and @diegomedina248 approvals too?

**Review by diegomedina248 — APPROVED** [review]
LGTM

**Review by jinghua-qa — APPROVED** [review]
LGTM

**Pull request merged**
