### PR TITLE
fix(native-filters): Reset column field for removed dataset

### LINKED ISSUE #12457: [dashboard]Native filter FIELD loops when dataset in usewas removed
You can see on dashboard that Filter loops and if you open this -> then FIELD dropdown has looped animation

### Expected results

Expected: We should indicate somehow that Filter is malformed(@junlincc) and do not propose not available options to set.

### Actual results

Observed: You can find that *FIELD has looped loading animation with name of not available field. After I choose different datasource I still see this old type of field as an option in field box.
#### Screenshots
image

https://user-images.githubusercontent.com/25153919/104338901-4c60ce00-54f7-11eb-93c6-c369e89c9f27.mov

#### How to reproduce the bug
Scenario:
Create Filter with reference to dataset
Delete this dataset
Go back to Filter Configuration and Scoping:

### Environment

Please enable native filter first
Run code from commit 90915db60d0f330fd28a5fc2b7a6676944c4dbb5

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by agatapst**
### SUMMARY
After removing dataset, which is used in some native filter, it was still possible to see field from this dataset. Dataset was removed, but field value was not removed from Filter Config Modal.
Described in #12457

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Before:
First we set some native filter
remove_dataset_before
Then we remove used dataset and come back to native filter config
dataset_remove

After:
remove_dataset_after
dataset_remove_after

### TEST PLAN
Set `"DASHBOARD_NATIVE_FILTERS": True`
Create new native filter with given dataset
Go to datasets and remove this dataset
Come back to native filter you have just created and check if you see 'Select' placeholder instead of field value from removed dataset

### ADDITIONAL INFORMATION

- [x] Has associated issue: Fixes #12457
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

@junlincc @rusackas @adam-stasiak

### CODE REVIEW

**Review by villebro — APPROVED** [review]
LGTM

**Comment by adam-stasiak** [comment]
First issue:
For dashboard I have two native filters for 2 different datasets
I remove one dataset and go back to native filters
I can see that for filter with removed dataset -> datasource and field are cleaned - OK!
I can see in the second native filter (without touched dataset) - I can se cleaned field but should not! - NOK!

**Comment by adam-stasiak** [comment]
second issue:
After steps from issue#1 I set proper field for malformed filter
Change is applied
Refreshed page
Open filter configuration and scoping -> I can see cleaned FIELD for both -> but I think it is only on UI -> because left side of screenshot is showing available options :) 
image

**Comment by agatapst** [comment]
Thanks a lot Adam, I think these issues are connected with each other. I am working on them now!

**Comment by adam-stasiak** [comment]
Tested manually - it is fine.

**Comment by adam-stasiak** [comment]
Retest for your fixes -> it is ok 🟢

**Comment by junlincc** [comment]
> I remove one dataset and go back to native filters

@adam-stasiak you are really the QA KING. thanks for taking care of the project while i was gone...

**Comment by junlincc** [comment]
Thank you so much for the PR! @agatapst 

for some reasons, I'm not seeing changes described above. but a spinning sign for the filter with deleted dataset.. not sure if I tested correctly? @adam-stasiak 
https://user-images.githubusercontent.com/67837651/104804152-c7d3b100-577d-11eb-859e-e65880270444.mov

**Comment by adam-stasiak** [comment]
@junlincc I saw this spinner in situation od removed dataset - > I consulted this with Agata and good idea is to raise new issue for this as it needs design for not available filters. I left this on Friday and forgot to raise : | I will create an issue for this.

**Comment by agatapst** [comment]
@junlincc yes, actually @adam-stasiak asked me about that spinner and at first thought about making separate issue - but if this PR is still not merge, let's improve it in this PR. 
Below I am attaching screenshot when there is something wrong with filter (i.e. dataset was removed). There is a text instead of spinner. Any suggestions about the copy are welcomed. 🙂 
error_filter

**Comment by junlincc** [comment]
this error msg definitely need design 🙏 @mihir174

thanks for the change! @agatapst

**Comment by mihir174** [comment]
@agatapst @adam-stasiak @junlincc 

This might be a bit of a heavy treatment, but here's the standard error component in the Superset design system -
We can have the body text = the cause of the error

Screen Shot 2021-01-20 at 12 42 25 AM

**Comment by agatapst** [comment]
Thanks @mihir174 
Could we make this message more generic, universal? We could show it for all errors connected with Filter Bar filters. Right now it is impossible to distinguish if the error comes from removing dataset. It may be one of the reasons that loading filter is not possible - but for example the reason may be that some used in this filter field was removed from dataset. So it won't be the same as 'removed dataset'. 
Maybe we can tell the user to 'check the configuration'?

**Comment by adam-stasiak** [comment]
Can we make the spacing bigger? It looks very tight. @agatapst @junlincc @mihir174 
image

**Comment by adam-stasiak** [comment]
Issue: After I fixed filter (Change dataset to existing one) I can see error remains :( 

https://user-images.githubusercontent.com/25153919/105252954-c986e580-5b7e-11eb-952c-3f397323725e.mov

**Comment by agatapst** [comment]
Thanks a lot Adam! @adam-stasiak 
Could you check it once again? It seems ok now on my side:
error_alert

I have also made the margin slightly bigger:
Zrzut ekranu 2021-01-21 o 09 31 06

**Comment by junlincc** [comment]
@rusackas @mistercrunch please help merge this PR, LGTM with code reviews and few rounds of changes...

**Comment by junlincc** [comment]
thank you everyone for the PR, testing, design input, reviewing and merging. @agatapst @mihir174 @adam-stasiak @zhaoyongjie @villebro 🙏

@mistercrunch Max,  just want to use this PR as an example to show how much work the team put into each single PR before merging.

**Pull request merged**
