### PR TITLE
chore(chart): Rearrange properties relevance

### LINKED ISSUE #12376: [Explore]allow user to search metrics and columns by properties in data panel
Feature request: to allow user to search metrics and columns by their properties (text in the info icon and question mark) in data panel
Rank search results by relevancy 

Screen Shot 2021-01-08 at 9 09 53 PM

Screen Shot 2021-01-08 at 9 10 14 PM

Screen Shot 2021-01-08 at 9 10 00 PM

### PR DESCRIPTION
**Pull request by nikolagigic**
### SUMMARY
This is in response to this comment: https://github.com/apache/superset/pull/12549/files#r559769842

closes #12376

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by geido — APPROVED** [review]
LGTM

**Review by ktmud — APPROVED** [review]
Sorry for nitpicking, but I think `verbose_name` should be before `description`...

**Comment by junlincc** [comment]
> Sorry for nitpicking, but I think `verbose_name` should be before `description`...

I place `verbose_name` after because they are often the same as metrics/column name.

**Review by junlincc — COMMENTED** [review]
⚠️ not ready to merge

Screen Shot 2021-01-19 at 11 25 20 AM

in this case above, shouldn't the columns go first? @nikolagigic

**Comment by ktmud** [comment]
> I place `verbose_name` after because they are often the same as metrics/column name.

But in case they are different, they should rank higher than description.

**Comment by junlincc** [comment]
tested again, LGTM, file a follow up issue about clearing search input while switching dataset. @nikolagigic thanks for the improvement!

**Comment by junlincc** [comment]
@ktmud do we wanna close this PR since we merged your changes?

**Comment by ktmud** [comment]
> @ktmud do we wanna close this PR since we merged your changes? 

Yeah, #12675 started with fixing performance issue but ended up fixing things targeted here as well.

Was meant to mention this PR but referenced the wrong PR number.

**Pull request closed without merging**
