### PR TITLE
chore(config): Migrating `ENABLE_JAVASCRIPT_CONTROLS` from app config to a feature flag

### LINKED ISSUE #18909: [2.0] change the `ENABLE_JAVASCRIPT_CONTROLS` from a config value to a feature flag

### PR DESCRIPTION
**Pull request by rusackas**
### SUMMARY

This PR moves the boolean enablement of the JS controls (i.e. custom tooltips in the DeckGL viz) from app configuration to feature flags. Two main reasons: 
1) To better support deployments who manage feature flags on the fly... this seems more fitting in that area of configuration
2) To move the feature (with its self-admitted risks, and unknown level of community adoption) to the Feature Flag lifecycle, wherein we may more systematically either secure the feature's development and enablement, or deprecate it and replace it with a newer feature (e.g. jinja/markdown tooltips).

This is considered a breaking change since certain deployments may rely on enabling/disabling this feature, and they may have to adapt their configuration to set it in a new place.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
n/a

### TESTING INSTRUCTIONS
Turn on the flag, and see that it works! We can (and shall!) do this on an ephemeral environment on this PR.

### ADDITIONAL INFORMATION

- [x] Has associated issue: Fixes #18909 
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ x ] Removes existing feature or API _well, kind of_

### CODE REVIEW

**Comment by rusackas** [comment]
Note that in testing, I was encountering potential bugs and usability issues with the JS controls features. However, I was encountering this in both app config and feature flag modes. The intent of this PR is to move the configuration, not to stop and address issues with the feature itself.

**Review by villebro — COMMENTED** [review]
It's my understanding that the feature flag dict in `config.py` is meant for temporarily enabling features that aren't yet considered stable. However, anything that needs to be permanently customizable should be a global config flag. For this reason it can be argued that the `ENABLE_TEMPLATE_PROCESSING` flag should also be moved back to a global config flag. It would be good to hear other people's thoughts on this - @dpgaspar @john-bodley , any thoughts?

**Comment by rusackas** [comment]
> It's my understanding that the feature flag dict in `config.py` is meant for temporarily enabling features that aren't yet considered stable. However, anything that needs to be permanently customizable should be a global config flag. For this reason it can be argued that the `ENABLE_TEMPLATE_PROCESSING` flag should also be moved back to a global config flag. It would be good to hear other people's thoughts on this - @dpgaspar @john-bodley , any thoughts?

Agreed, and a part of the motivation to move this back to a feature flag is to de-stabilize the feature. Due to potential bugs, UX difficulties, and security concerns, I think we can move to deprecate it and replace it with a safer/simpler feature in coming versions. 

_But I must confess this also selfishly provides our org with an easier means to tweak the setting easily with the way we manage deployments, while its deprecation is being considered_

**Review by suddjian — APPROVED** [review]
Javascript controls are a feature, this is a flag for that feature, it's a feature flag. QED 😁

**Pull request merged**
