### PR TITLE
fix: filters push out apply button on dashboard

### PR DESCRIPTION
**Pull request by kkucharc**
### SUMMARY
Changed behaviour of too big filter block:
* Added class and calculated height (100%-padding) for blocks -> otherwise scroll was appearing in every chart
* Added auto overflow for blocks on dashboards so scroll will appear when there will be too many filters
* Added `menuPortalTarget` because dropdown menu was limited to the box of chart.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Before:
97113844-1fe0a700-16aa-11eb-9be6-879800b42ca2

After:
Large GIF (490x694)

### ADDITIONAL INFORMATION

- [x] Has associated issue: #11419
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by rusackas** [comment]
@graceguo-supercat @ktmud curious if you have any objection to this solution. This issue has come up several times in the past, and I heven't seen a solution yet that makes everyone happy. This seems like at least a step in the right direction. Thoughts?

**Comment by ktmud** [comment]
I think this makes sense. But is there a way to make only the chart content the scrollable area, i.e., make the chart title sticky?

**Comment by junlincc** [comment]
> I think this makes sense. But is there a way to make only the chart content the scrollable area, i.e., make the chart title sticky?

agreed, make sense. let's make the filter box title sticky. @kkucharc 🙏

**Comment by rusackas** [comment]
@ktmud do you think there would be much value in making the Apply button sticky on the bottom, so the filters start to scroll behind it? Or is that just hogging the limited real estate?

**Comment by ktmud** [comment]
As much as I like it to be sticky too, I think your point about limited real estate is more important.

**Comment by kkucharc** [comment]
I appreciate your feedback and input 👍  I will figure our and propose something.

**Review by rusackas — APPROVED** [review]

**Pull request merged**
