### PR TITLE
[Feature] Dashboard scoped filter

### PR DESCRIPTION
**Pull request by graceguo-supercat**
### CATEGORY

Choose one

- [ ] Bug Fix
- [x] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
**Before:**
With the growing size of the dashboard, user may want to apply one dashboard filter to some of charts in dashboard, and one filter apply to another set of charts. A very common use case is user groups similar charts in different tabs, and make a filter only applicable for this group. Currently the way to set filter's scope is not very easy to use:
Screen_Shot_2019-10-16_at_9_49_54_AM

**After:**
1. Start filter scope selector:
jwMsJ1jNea

2. User can edit a single filter, or edit multiple filter fields all together. We also allow user toggle back to a single filter field in the multi-edit mode:
PtIvVuSV6s

3. Search chart name:
d2ZfBriTy2

4. When new chart is added to dashboard, based on its layout position, it will get filters that are applicable to its tab(s):
NvggG46SWb

5. When user move charts between tabs, this may cause chart to be applicable to different filter(s). We will show a warning message when chart is moved to a different filter scope.
MVYXjUXxDr

### TEST PLAN
CI and manual test.

### REVIEWERS
@etr2460 @kristw  @mistercrunch @willbarrett @betodealmeida

### CODE REVIEW

**Review by etr2460 — APPROVED** [review]
this has been reviewed when merging into the feature branch, so this should be good to go!

**Comment by mistercrunch** [comment]
stoked

**Comment by vumaasha** [comment]
Is this feature available on latest version on pypi? Seems to be missing there

**Comment by lilila** [comment]
This feature looks amazing, congrats! 
However, I try to use on 0.36.0.rc1 release and I cannot click on "close" nor "save" buttons :(

**Pull request merged**
