### PR TITLE
add hostnfly as users of superset

### PR DESCRIPTION
**Pull request by alexisrosuel**

### CODE REVIEW

**Comment by mistercrunch** [comment]
Travis never started. Mind pushing a dummy commit on top to get it to fire (we don't have admin rights on the Apache repos, so I can't force-refresh travis...)

**Comment by alexisrosuel** [comment]
I pushed an empty commit but it still doesn't seem to start...

**Comment by mistercrunch** [comment]
@fabianmenges had similar issues recently, something about Travis' abuse detection misfiring... @fabianmenges was the workaround to change the branch name or to open a ticket with Travis?

Should we ask Apache-infra to make Travis checks optional for merging for cases like this?

**Comment by fabianmenges** [comment]
@alexisrosuel @mistercrunch I contacted Travis support when I had that issue. It looks like they changed something on their end and now every organization needs to enable Travis on their Github account otherwise Travis won't pick up builds.

I complained that that does not make sense since our forks are public. We'll see if they fix it.

**Comment by alexisrosuel** [comment]
@fabianmenges thanks for the answer, I wait and see then

**Comment by kristw** [comment]
replaced with #7065

**Pull request closed without merging**
