### PR TITLE
Disable complexity check.

### PR DESCRIPTION
**Pull request by bkyryliuk**
I am not sure that such a check is useful for the repo.
More details are here:
http://radon.readthedocs.io/en/latest/intro.html#cyclomatic-complexity

Existing code has many complexity warnings:
https://codeclimate.com/github/airbnb/caravel/issues?category=complexity&engine=

@mistercrunch - what do you think ?

### CODE REVIEW

**Comment by ascott** [comment]
i agree, i don't think this check is neccessary at this point in time.

**Comment by williaster** [comment]
++

**Comment by mistercrunch** [comment]
LGTM

**Comment by bkyryliuk** [comment]
thanks !

**Pull request merged**
