### PR TITLE
Revert "chore: Bump redis to 4.5.4"

### PR DESCRIPTION
**Pull request by sinhashubham95**
Reverts apache/superset#23845

This change is being requested because `rediscluster` is not compatible with the newer version of Redis. Builds are failing because of that.

### CODE REVIEW

**Comment by EugeneTorap** [comment]
Hi @sinhashubham95! Where do we use `rediscluster` lib?
New version of Redis supports the cluster.
```python
from redis.cluster import RedisCluster

rc = RedisCluster(host='localhost', port=16379)

print(rc.get_nodes())
```

**Review by dpgaspar — COMMENTED** [review]
I would prefer not to revert the bump to `psycopg2`

**Comment by sinhashubham95** [comment]
@EugeneTorap the redis cluster module is broken, and does not work.

**Comment by EugeneTorap** [comment]
@sinhashubham95 Let's fix it using the new redis
Pls, describe steps how you configure redis cluster. Via helm?

**Comment by rusackas** [comment]
We've stayed on 4.5.4 for almost a year now, and I don't think this is still a common/major concern? Closing this PR for that reason and because it needs a rebase. If you think it's still warranted, please feel free to rebase, reopen, and rekindle the conversation. Thanks for contributing!

**Pull request closed without merging**
