### PR TITLE
Fix issue: Oracle backend: pandas Exception : KeyError #953 with models.py change 

### PR DESCRIPTION
**Pull request by TryHarder01**
Fix issue: Oracle backend: pandas Exception : KeyError #953 
This builds on the work of #3775 but I'm making a change in the `models.py` query method which i think is a better home.

### CODE REVIEW

**Comment by xrmx** [comment]
This would be a lot better if done in `superset.models.core.Database.get_df` no?

**Comment by TryHarder01** [comment]
@xrmx not sure. I'm using the `query_object` that gets passed into the `query()` method in `models.py` in order to exclude the agg/metrics columns calculated by superset (things like, "min__X").

If I go up to `core.Database.get_df` I don't have access to that anymore (as far as I can tell).

I'll have a SQL output that has columns "orders, data, min_PRICE" and I want to make sure I only upper() the first two, since Superset is expect "min_PRICE" just like that. The `query_obj['metrics']` gives me access to the columns that should be left unchanged. 

I'm up for improvements, but when trying to make your change the code fails without accessing that variable.

**Comment by mistercrunch** [comment]
All database-engine-specific code should live in `superset.db_engine_spec`

**Comment by mistercrunch** [comment]
Closing since it isn't the right approach. I also feel like this is an upstream bug with the the SQLAlchemy dialect where listing the objects should have the proper case upfront.

**Pull request closed without merging**
