### PR TITLE
Adding Dashboard toggle fullscreen button

### PR DESCRIPTION
**Pull request by zhaoyongjie**
### SUMMARY
Dashboard can recieve url parameter `standalone` toggle fullscreen mode or not, expose this function to Dashboard header dropdown 

### adding button in dashboard dropdown
image

### Dashboard in fullscreen mode
image

### TEST PLAN
Adding unit test to getDashboardUrl_spec.js

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [x] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by etr2460** [comment]
Could you attach a screenshot showing what the dashboard looks like after clicking the button?

**Comment by zhaoyongjie** [comment]
@etr2460 HI, I append a image to PR comment. thanks for you remind

**Review by lilykuang — APPROVED** [review]

**Review by riahk — APPROVED** [review]

**Comment by rusackas** [comment]
I think "standalone" is a better term... I would reserve "fullscreen" for some sort of `Element.requestFullscreen()` implementation... 

Or, you could consider adding that functionality in this PR to make the functionality better fit the name.

**Comment by rusackas** [comment]
Actually, @zhaoyongjie I'm curious what your use case is here... do you want to share the link to others in "standalone mode" or is it that you want a version for TV/presentation purposes (i.e. "presentation mode")?

**Comment by ktmud** [comment]
FWIW, Tableau has a Presentation Mode on desktop app, but a Full Screen button on web.



They also removed the main menu on the dashboard page and replaced it with a back button.

**Pull request merged**
