### PR TITLE
chore: deprecate /superset/slice_json/<int:slice_id> and /superset/annotation_json/<int:layer_id>

### PR DESCRIPTION
**Pull request by diegomedina248**
### SUMMARY

Continuing the effort on deprecating all `/superset/` REST API endpoints
Deprecates `/superset/slice_json/<int:layer_id>`
Deprecates `/superset/annotation_json/<int:layer_id>`

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by dpgaspar — APPROVED** [review]
Looks good, but I don't have a lot of context here

**Comment by EugeneTorap** [comment]
LGTM!
We should try to deprecate `/superset/explore_json/` API in `superset-frontend/packages/superset-ui-core/src/chart/clients/ChartClient.ts:112` and use only `/api/v1/chart/data` for all viz of chart.

**Review by villebro — COMMENTED** [review]
Wow! While we're at it, I think we should try to burn the following code, as it's mostly just neeeded for annotation layers, as the table viz migrated to v1 chart data endpoint a long time ago: https://github.com/apache/superset/blob/d479009e35a86dfda321492afeda2a1683a9345a/superset/viz.py#L690-L838
I think you need to do a few changes here, but it should be fairly straight forward:
https://github.com/apache/superset/blob/d479009e35a86dfda321492afeda2a1683a9345a/superset/common/query_context_processor.py#L569-L589

Please ping me on Slack if you need help. If we go this extra mile, we'll be killing a HUGE amount of tech debt in one go! 🚀

**Review by villebro — APPROVED** [review]
Actually, come to think of it, my proposed changes are breaking, so we need to hold off on them until we cut the 3.0 release. So LGTM!

**Review by geido — APPROVED** [review]
LGTM!

**Pull request merged**
