### PR TITLE
fix(dashboard): artefacts shown while drag and dropping deck.gl charts

### LINKED ISSUE #12181: [dashboard] dragging a deck.gl chart shows header artifacts
Only the chart itself should be shown during the drag event.

Screen Shot 2020-12-22 at 9 56 41 AM

### PR DESCRIPTION
**Pull request by kkucharc**
### SUMMARY
Disables `:before` in charts while drag'n'drop which caused artefacts in chart preview.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Before
Large GIF (1298x860)

After
Large GIF (1300x860)

### TEST PLAN
1. Go to deck.gl dashboard
2. Go to edit mode
3. Try drag and drop one of charts

### ADDITIONAL INFORMATION

Fixes #12181 
- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by kkucharc** [comment]
cc: @adam-stasiak can you test?

**Comment by adam-stasiak** [comment]
I found artifact which was in code before your change:

https://user-images.githubusercontent.com/25153919/104235374-2aaf0a80-5455-11eb-8bb3-1bb289b482c4.mov
Is it possible to fix this with the same PR or create a new issue for this @kkucharc? @junlincc Would you like to split this into another issue?

**Review by junlincc — APPROVED** [review]
@kkucharc drag & drop experience seems improved in general not just deck.gl charts. LGTM. 
let's test again after this PR is merged. @adam-stasiak 

NOTE⚠️: 

- This is only Product and QA approval with NO code reviews 
- This approval indicates that all UI changes meet product requirements, no noticeable regression 
- This approval gives the green light to code review, thus saving the PMC's effort from reviewing the code repeatedly before the PR is ready
- Please do NOT merge this PR without at least one code review approval from PMC member
- Please do NOT merge PRs in(Explore and Dashboard) without Product and QA approval

**Comment by junlincc** [comment]
cc @graceguo-supercat do you mind taking a look at this PR?

**Review by graceguo-supercat — COMMENTED** [review]
LGTM

**Review by graceguo-supercat — APPROVED** [review]

**Pull request merged**
