### PR TITLE
chore: encapsulate flask app into superset app

### PR DESCRIPTION
**Pull request by ofekisr**
### SUMMARY
encapsulate the flask app under supersetApp type, then new features can be declared and added to the new type

### CODE REVIEW

**Review by amitmiran137 — APPROVED** [review]
LGTM! 
nice encapsulation

**Comment by john-bodley** [comment]
@ofekisr could you please provide more context as to why this is needed?

**Comment by cwegener** [comment]
> @ofekisr could you please provide more context as to why this is needed?

It doesn't look like this encapsulation ever ended up being used anywhere. What indeed is the point of having this `SupersetApp` class?

**Comment by cwegener** [comment]
> @ofekisr could you please provide more context as to why this is needed?

It doesn't look like this encapsulation ever ended up being used anywhere. What indeed is the point of having this `SupersetApp` class?

**Pull request merged**
