### PR TITLE
chore: replace "dashboard" -> "report" in chart email report modal

### PR DESCRIPTION
**Pull request by sfirke**
### SUMMARY
When setting up a new email report for a chart, the popup incorrectly says "dashboard" and "screenshot."

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
In Superset 3.0.0, click the `...` on a chart, then Manage email report, then Set up an email report.  You'll see:

image

a) This shouldn't say screenshot because the user can pick a text or .CSV format choice
b) This should say chart instead of dashboard

### TESTING INSTRUCTIONS
N/A, just changing a line of text.

### CODE REVIEW

**Comment by sfirke** [comment]
I'm confused, what does this failed check say I should do?
> Error:   337:14  error  Replace `⏎············{t('The·report·will·be·sent·to·your·email·at')}⏎··········` with `{t('The·report·will·be·sent·to·your·email·at')}`  prettier/prettier

**Comment by sfirke** [comment]
Also I see that the string I modified `A screenshot of the dashboard will be sent to your email at` appears in ten translation files when I search the code base.  Should I make the corresponding modification in each of those as well?

**Comment by sfirke** [comment]
Ugh I am bad at rebasing! 😖

**Comment by sfirke** [comment]
reopening at the awful state so I can force push and kind of fix this

**Comment by sfirke** [comment]
@rusackas I rebased this one and it's passing CI.  It makes the translations slightly out of date, I don't know how to deal with that...

**Review by rusackas — APPROVED** [review]
I suppose my only little question is this: does a user reliably know that a Report is a screenshot of a dashboard? I would assume so, but I'm not sure if this is explained elsewhere in the UI. I'll approve, since it seems fine to me, but I'll also ping @yousoph and @eschutho to see if they have feelings about it :D

**Comment by sfirke** [comment]
> I suppose my only little question is this: does a user reliably know that a Report is a screenshot of a dashboard?

Ah, I sent this PR because I was setting up a Report for a single chart and didn't like that it said "dashboard."  I see now that when I set up a report for a dashboard, it uses this same modal, and in that case "dashboard" and "screenshot" are correct.

Maybe that's where you're coming from?  A report is not always a screenshot of a dashboard, it can be a screenshot or .csv of a single chart.  Thus this fix which makes it agnostic as to which is being configured.

**Review by mistercrunch — APPROVED** [review]

**Pull request merged**
