### PR TITLE
[SQL Lab] Improve perf for filterable table rendering

### PR DESCRIPTION
**Pull request by etr2460**
### CATEGORY

Choose one

- [ ] Bug Fix
- [x] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY

Uses @kristw's new `getMultipleTextDimensions` to improve perf about 3x for FilterableTable rendering

### TEST PLAN

Ensure tables in sql lab still render properly

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### REVIEWERS
@kristw @graceguo-supercat @betodealmeida

### CODE REVIEW

**Review by kristw — APPROVED** [review]

**Comment by kristw** [comment]
Hmm. Code looks good. I was not aware that `array.flat()` has been implemented. 
Not sure why CI fails. Does this work locally for you?

**Comment by etr2460** [comment]
`array.flat()` is now implemented in modern browsers, but cypress uses an older version of headless chrome (according to @graceguo-supercat). I've reverted to the old school `[].concat(...array)` syntax.

**Comment by graceguo-supercat** [comment]
see discussion in cypress community: https://gitter.im/cypress-io/cypress/archives/2019/01/24

**Comment by etr2460** [comment]
cc @robdiciuccio if you're interested in some of the client side sql lab perf fixes

**Pull request merged**
