### PR TITLE
fix(explore): add Time section back to FilterBox

### PR DESCRIPTION
**Pull request by ktmud**
### SUMMARY

Before #12147 and #12091, FilterBox is considered a timeseries viz, and has a Time section where users can set time granularity and time filter. This adds it back so people can still use Time filter on FilterBox and the existing charts that do use it don't break.

In the future, we should probably bring the TimeFilter to regular AdhocFilter, as long as a column is temporal. This way we convert FilterBox into a non-timeseries viz. But since we are investing in native filters, this is probably not necessary anyway.

(cc @zhaoyongjie @junlincc )

#### Before

FilterBox has no Time section (incorrectly removed)

image

#### After

image

Time section is added back.

### TEST PLAN

- Go to Explore a filter box viz
- You should see the Time section

### ADDITIONAL INFORMATION

- [x] Has associated issue: see summary
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by zhaoyongjie — APPROVED** [review]
LGTM

**Review by junlincc — APPROVED** [review]
Screen Shot 2021-01-14 at 9 36 17 PM

thanks for the quick fix

**Review by villebro — APPROVED** [review]
Thanks for fixing, sorry about the regression!

**Comment by junlincc** [comment]
@michellethomas apologize for the regression!

**Pull request merged**
