### PR TITLE
fix(timepicker): make pyparsing thread safe

### PR DESCRIPTION
**Pull request by zhaoyongjie**
### SUMMARY
make `pyparsing` thread-safe

### TEST PLAN

1. run superset with below
```
 gunicorn -w 1 --threads 64 -b "0.0.0.0:8088" "superset.app:create_app()"
```
2. open `world bank's data` dashboard without error

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by junlincc** [comment]
lgtm!

**Without lock** 
Screen Shot 2021-01-13 at 1 49 47 AM
**With lock**
Screen Shot 2021-01-13 at 1 50 14 AM

**Review by villebro — APPROVED** [review]
This seems to fix it consistently for me in local dev env. Let's merge this quickly to unblock master and continue refining/optimizing perf later.

**Review by dpgaspar — APPROVED** [review]
Thank you for the fix, but if pyparser is not thread safe we should start working on removing this dependency

**Comment by junlincc** [comment]
> Thank you for the fix, but if pyparser is not thread safe we should start working on removing this dependency

I will hate to see this new feature go, so will many other users, as we already receive some positive feedback from the community. can we figure out a way to fix it forward instead of removing the dependency? @dpgaspar

**Comment by dpgaspar** [comment]
right @junlincc we should figure out a way to replace the dependency (without removing the feature) not sure if our dependency is light or not. But this needs a more detailed analysis.
I may be wrong but there is the probability that this lock will not be the end of this problem

**Comment by ktmud** [comment]
I think I may have found another fix:

```diff
diff --git a/superset/utils/date_parser.py b/superset/utils/date_parser.py
index aee2c83a0..513c740ab 100644
--- a/superset/utils/date_parser.py
+++ b/superset/utils/date_parser.py
@@ -33,6 +33,7 @@ from pyparsing import (
     Optional as ppOptional,
     ParseException,
     ParseResults,
+    ParserElement,
     pyparsing_common,
     quotedString,
     Suppress,
@@ -40,6 +41,8 @@ from pyparsing import (
 
 from .core import memoized
 
+ParserElement.enablePackrat()
+
 logger = logging.getLogger(__name__)
 
 
@@ -375,7 +378,7 @@ class EvalHolidayFunc:  # pylint: disable=too-few-public-methods
         raise ValueError(_("Unable to find such a holiday: [{}]").format(holiday))
 
 
-@memoized()
+@memoized
 def datetime_parser() -> ParseResults:  # pylint: disable=too-many-locals
     (  # pylint: disable=invalid-name
         DATETIME,
```

Could you test this diff and see if it fixes things for you?

**Comment by ktmud** [comment]
Enabling [packrat cache](https://pyparsing-docs.readthedocs.io/en/latest/pyparsing.html#pyparsing.ParserElement.enablePackrat) seems to have fixed it for me.

I'd assume no other programs are using `pyparsing` so this should be relatively safe.

**Comment by ktmud** [comment]
Looks like packrat cache comes with a lock for free: https://github.com/pyparsing/pyparsing/blob/f10fcf8c98ea07a63f8286288ce82f773e7e152e/pyparsing/core.py#L719

So I'm 90% sure this will fix the bug... (with the additional benefit of making things a little faster).

**Comment by villebro** [comment]
> Looks like packrat cache comes with a lock for free: https://github.com/pyparsing/pyparsing/blob/f10fcf8c98ea07a63f8286288ce82f773e7e152e/pyparsing/core.py#L719
> 
> So I'm 90% sure this will fix the bug... (with the additional benefit of making things a little faster).

I can confirm that this fixes the problem for me, too 👏  This looks like the perfect solution for this case. I think we can also re-enable the original memoization to get some additional perf improvement.

**Comment by zhaoyongjie** [comment]
> Looks like packrat cache comes with a lock for free: https://github.com/pyparsing/pyparsing/blob/f10fcf8c98ea07a63f8286288ce82f773e7e152e/pyparsing/core.py#L719
> 
> So I'm 90% sure this will fix the bug... (with the additional benefit of making things a little faster).

I changed this PR to add ParserElement.enablePackrat() and enable cache for datetime_parser, thank you for your finger out this solution

**Comment by junlincc** [comment]
countless thanks to you all for resolving this.🙏 @ktmud @villebro @zhaoyongjie

**Comment by mistercrunch** [comment]
This was easily one of the ugliest bug in Superset history: elusive, hard to reproduce, thread-safety-related, ...

Good work tracking it down and finding a viable fix for this one!

**Pull request merged**
