### PR TITLE
bugfix: cli export_datasources (fixes 7437)

### LINKED ISSUE #7437: Exporting Datasource to YAML fails
Exporting the main sqlite database to YAML via the List Databases interface and its Export to YAML option fails with the error `TypeError: '<' not supported between instances of 'dict' and 'dict'`.

### Expected results

I expect to receive a YAML file.

### Actual results

```bash
2019-05-02 21:28:47,467:INFO:werkzeug:127.0.0.1 - - [02/May/2019 21:28:47] "GET /databaseview/list/ HTTP/1.1" 200 -
2019-05-02 21:28:48,209:INFO:werkzeug:127.0.0.1 - - [02/May/2019 21:28:48] "GET /superset/csrf_token/ HTTP/1.1" 200 -
g2019-05-02 21:37:49,117:INFO:werkzeug:127.0.0.1 - - [02/May/2019 21:37:49] "POST /databaseview/action_post HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/rjurney/Software/incubator-superset/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/rjurney/Software/incubator-superset/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/rjurney/Software/incubator-superset/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rjurney/Software/incubator-superset/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/rjurney/Software/incubator-superset/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rjurney/Software/incubator-superset/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rjurney/Software/incubator-superset/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rjurney/Software/incubator-superset/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/rjurney/Software/incubator-superset/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rjurney/Software/incubator-superset/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/rjurney/Software/incubator-superset/venv/lib/python3.6/site-packages/flask_appbuilder/views.py", line 578, in action_post
    return action.func(items)
  File "/Users/rjurney/Software/incubator-superset/superset/views/base.py", line 195, in yaml_export
    data = [t.export_to_dict() for t in items]
  File "/Users/rjurney/Software/incubator-superset/superset/views/base.py", line 195, in <listcomp>
    data = [t.export_to_dict() for t in items]
  File "/Users/rjurney/Software/incubator-superset/superset/models/helpers.py", line 215, in export_to_dict
    key=lambda k: sorted(k.items()))
TypeError: '<' not supported between instances of 'dict' and 'dict'
```

#### How to reproduce the bug

1. Go to `/databaseview/list/`
2. Click on the checkbox for the 'main' database
3. Select the 'Actions' menu
4. Click on 'Export to YAML'
5. Click 'OK'
6. See error

### Environment

(please complete the following information):

- superset version: [e.g. `v0.31`, `release--0.31`, `700cbf4f`]
- python version: `Python 3.6.7`
- node.js version: `v11.6.0`
- npm version: `6.5.0`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by Aylr**
### CATEGORY

Choose one

- [x] Bug Fix
- [ ] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY
1. I needed a quick fix to move some datasources over to a new deployment.
2. The dict sorting wasn't working.
3. I implemented the quickest possible (read janky) fix by coercing to string.

### TEST PLAN

1. Checkout & install
2. `superset db upgrade`
3. `superset init`
4. `superset load_examples`
5. `superset export_datasources` and note the yml output.

### ADDITIONAL INFORMATION

- [x] Has associated issue: Fixes #7437 
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### REVIEWERS

### CODE REVIEW

**Review by etr2460 — COMMENTED** [review]
I'm not super familiar with this code, but I would've expected a change to the import function if the export format was changing. Does this still work when you try to import the new exported file?

**Comment by mistercrunch** [comment]
Actually I think the fix may be to *not* sort the list at all. I'm guessing the intention was to have a deterministic ordering so that aligns well in source control.

I think the ordering of the keys is stable/predictable given that it follow the `export_fields` ordering.

**Comment by Aylr** [comment]
@mistercrunch I guessed that the sorting was for the same thoughtful reason - to reduce VCS thrash, and that's why I though a hacky string coercion would be a suitable fix.

@etr2460 Since this affects only the ordering of the yml that is output by the function, there is no change required on the import code.

**Comment by Aylr** [comment]
What's the next step in the process to get this merged?

**Comment by mistercrunch** [comment]
Ok I resolved a conflict, let's move forward with this once CI passes

**Comment by mistercrunch** [comment]
Note that it fixes the bug but could also lead to random re-ordering when objects change. Maybe once https://github.com/apache/incubator-superset/pull/7472 lands, we can use the new `uuid` field as a deterministic way to sort lists of exported objects.

**Comment by smacker** [comment]
@mistercrunch we have identified more problems with export/import and now consider fixes that we would love to send upstream. The current proposed solution is also to use uuids. You can find the document here: https://docs.google.com/document/d/1vfiAw7yCzqvb3ALo_aiBX3XFPjLNZ1Mira-X7HCK1lI/edit?usp=sharing

**Comment by mistercrunch** [comment]
@smacker some work on `uuid` has been done here https://github.com/apache/incubator-superset/pull/7472 , but it should probably be refactored out into a smaller/simpler PR.

**Comment by mistercrunch** [comment]
Also related, found issues that I fixed here as bycatch https://github.com/apache/incubator-superset/pull/7773 in the `export_dashboards` method. Exporting dashboards would actually break the existing ones in the context of unit tests. Not sure if that was the same in production...

**Comment by Aylr** [comment]
Ping @mistercrunch what do we need to do to either get this merged or apply another fix? This 5 character PR has been open for 20 days now. What can I do to help?

**Pull request merged**
