### PR TITLE
fix(plugin-chart-handlebars): Update webpack/babel config to fix build/runtime warnings/errors

### PR DESCRIPTION
**Pull request by codyml**
### SUMMARY

This PR is an attempt to fix the Handlebars viz plugin, which currently raises both build and runtime errors, by updating Webpack and Babel config.

#### Build warning
Webpack would emit the following warning several times during build: `require.extensions is not supported by webpack. Use a loader instead.`.  The source listed was various lines in `./node_modules/handlebars/lib/index.js`.  According to the Handlebars GH project, this is due to the package not correctly indicating which build is client-side-compatible.  A [fix](https://github.com/handlebars-lang/handlebars.js/pull/1862) was merged, but it hasn't made it into an NPM-published release.  A workaround was recommended by [this comment](https://github.com/handlebars-lang/handlebars.js/issues/953#issuecomment-239874313) and is included in this PR.  This issue doesn't seem to be related to the runtime error and this fix just clears the build warning.

#### Runtime error
When rendering a Handlebars chart in Explore, the following error appears: `ReferenceError: exports is not defined`.  An inspection of the console shows that the culprit is the `just-handlebars-helpers` package's references to `exports`, as is standard in the CJS module system.  After some digging, I found [this comment](https://github.com/webpack/webpack/issues/4039#issuecomment-419284940) that makes me think the problem is a CJS/ESM incompatibility: our Babel setup assumes all JS is ESM-style modules and therefore doesn't transpile CJS-style `require` and `module.exports` statements into `import`/`export` statements, and Webpack assumes Babel output is ESM-style modules and doesn't provide global `require`/`module.exports` that you'd find in a CJS environment, causing this error (`just-handlebars-helpers` seems to be CJS-only).  As suggested by the comment, I changed `sourceType` to `unambiguous` so it stops assuming modules are ESM-style and instead makes a guess based on the presence of `require`/`module.exports`.  This seems to fix the issue, though I don't have a great sense of what else this might affect.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

Before:

Screen Shot 2022-10-11 at 8 59 13 PM

Screen Shot 2022-10-11 at 8 59 24 PM

After:

Screen Shot 2022-10-11 at 9 00 27 PM

Screen Shot 2022-10-11 at 9 00 35 PM

### TESTING INSTRUCTIONS

- Run webpack and ensure the aforementioned build warnings are gone.
- Try creating a Handlebars chart and ensure the runtime error doesn't show up.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by zhaoyongjie** [comment]
@codyml When I looked into the dependency that [Just Handlebars Helpers](https://www.npmjs.com/package/just-handlebars-helpers), it said that *A lightweight package with common [Handlebars](https://github.com/wycats/handlebars.js) helpers.* from the npm registry description. It just provided some shortcuts for the `Handlebars`, so it's not a core function for the Handlebar. This plugin was introduced from [PR](https://github.com/apache/superset/pull/20648).

IMO, I would rather remove the `Helper` than change the global Bable setting to fit a plugin's configuration.

**Comment by villebro** [comment]
> @codyml When I looked into the dependency that [Just Handlebars Helpers](https://www.npmjs.com/package/just-handlebars-helpers), it said that _A lightweight package with common [Handlebars](https://github.com/wycats/handlebars.js) helpers._ from the npm registry description. It just provided some shortcuts for the `Handlebars`, so it's not a core function for the Handlebar. This plugin was introduced from [PR](https://github.com/apache/superset/pull/20648).
> 
> IMO, I would rather remove the `Helper` than change the global Bable setting to fit a plugin's configuration.
> 
> What do you think about this? @evans @villebro

I believe there's actually an open PR out there to do exactly this: #21143 (the discussion there is pretty similar to what you're proposing). I think this comes down to whether or not we feel maintaining these helpers ourselves is something we want to do or not. Normally I'd say let's just use the npm package, but if using the upstream package requires us to do hacky workarounds, then I'm not so sure.

**Comment by rusackas** [comment]
Heya @zhaoyongjie / @villebro 

It's true, I don't like the idea of copying over all the internals of that helper module into our codebase for a couple of reasons:
1) It feels "gross" from a copyright/licensing/plagiarism perspective
2) We would lose the benefit of any updates/expansions that the other project takes on.

So, I'd _like_ to use this `just-handlebars-helpers` module if possible. I'm also open to competitors, but nothing obvious turns up except for [this one](https://github.com/assemble/handlebars-helpers) which seems unmaintained.

I'll open up an Issue on the `just-handlebars-helpers` repo to see if they would be willing to create an EJS version. Otherwise, if we can change the babel config for a specific file path, that'd be a little more surgical than this PR currently is.

However, the big question I have is: do we see any realistic risk or downslides to this change in babel config? Maybe we can approve/merge this until the day that `just-handlebars-helpers` adds EJS (maybe we write a PR there!) at which point we can lock this back down.

**Comment by codyml** [comment]
@zhaoyongjie @villebro @rusackas If it helps, I just pushed a diff that overrides the Babel `sourceType` for just the package in question rather than the whole project.

**Comment by rusackas** [comment]
> @zhaoyongjie @villebro @rusackas If it helps, I just pushed a diff that overrides the Babel `sourceType` for just the package in question rather than the whole project!

Thanks! We spent a few minutes looking for a way to do that, but didn't see one!

**Review by rusackas — APPROVED** [review]

**Comment by zhaoyongjie** [comment]
> _Total side note: Apologies to Evans, who gets pinged by this project all the time, and is not me ;)_

I really wanted to say sorry to Evan, and buy him a drink.

**Comment by sadpandajoe** [comment]
🏷️ preset:2022.41

**Pull request merged**
