### PR TITLE
 fix bug: can't  translation in add_slice page

### PR DESCRIPTION
**Pull request by byc233518**
before: 
image

after:
image

### CODE REVIEW

**Review by byc233518 — COMMENTED** [review]
add a comma

**Review by byc233518 — COMMENTED** [review]
adjust the code format

**Review by byc233518 — COMMENTED** [review]
import

**Review by byc233518 — COMMENTED** [review]
update

**Comment by mistercrunch** [comment]
Please fix the build. Looks like there are errors on the py3 side of things.

**Pull request closed without merging**
