### PR TITLE
fix: dashboard endpoint sig changed

### PR DESCRIPTION
**Pull request by dpgaspar**
### SUMMARY
`/superset/dashboard/<id>` Flask endpoint signature changed on #9939.

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by john-bodley — APPROVED** [review]
Thanks for the fix, and apologies for the regression.

**Comment by willbarrett** [comment]
Can we add a unit test to avoid future regressions?

**Review by bkyryliuk — APPROVED** [review]

**Review by villebro — APPROVED** [review]
Thanks for the fix! It seems slightly brittle to accept any `kwarg`, as linters aren't able to pick up on which are valid and which aren't. Perhaps out of scope for this PR, but to avoid future regressions, perhaps we should have named arguments for the valid ones, and those then get pushed into a dict that is fed to `url_for(**kwargs)` in `get_url_for_path`.

**Comment by dpgaspar** [comment]
Good point, I'll merge this and make a subsequent PR

**Pull request merged**
