### PR TITLE
adding cx_oracle package

### PR DESCRIPTION
**Pull request by davidginzburg**
python oracle  package

### CATEGORY

Choose one

- [ ] Bug Fix
- [x] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [x] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by nytai** [comment]
hi @davidginzburg thanks for opening a PR! A couple questions, is there a reason you've listed it in `requirements-dev.txt` vs  in `setup.py` under `extras_require` along with the other db drivers? Also, do you think there's a strong case for superset to ship with the oracle driver by default?

**Comment by mistercrunch** [comment]
Lots of people don't use Oracle, so it should be an optional dependency. If anywhere this should go in the extras_require section of setup.py

**Comment by davidginzburg** [comment]
hi,i think superset  is a powerful tool! i think the  more db  kinds it
supports the more people  will use this cool app! i am using oracle db and
mysql and helps me alot!(you cant even  imagine)
a long  time ago i successed adding cx_oracle python package but now for
some reason i cant add it  when i  am  building  the docker image (and i it
would help me alot if you can add cx_oracle to the requirements-dev.txt)
thank you  very much!
david.

‫בתאריך יום ה׳, 5 בדצמ׳ 2019 ב-7:03 מאת ‪Maxime Beauchemin‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by mistercrunch** [comment]
Oh, you can just add whatever library you need in your environment on top of the `superset` package. You don't need for the `cx_oracle` package to be inside the `superset` package itself.

```bash
pip install superset
pip install cx_oracle
```

**Comment by davidginzburg** [comment]
i  tried that, but for some reason when i  do docker save it i dont see the
cx_oralce inside...
i  also tried to  do it  inside the container also no success :(

‫בתאריך שבת, 7 בדצמ׳ 2019 ב-1:07 מאת ‪Maxime Beauchemin‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by mistercrunch** [comment]
If `pip install cx_oralce` fails, you should see with the maintainers of that package.

**Pull request closed without merging**
