### PR TITLE
fix timestamp error in table view

### LINKED ISSUE #1934: timestamp in TableView is returned in number
in commit c14c7ed, the json_dumps function of class TableViz was deleted, but this default parameter of this function has different value -- utils.json_**iso**_dttm_ser:

    def json_dumps(self, obj):
        return json.dumps(obj, default=utils.json_iso_dttm_ser)

compared to json_**int**_dttm_ser in:

    def json_dumps(self, obj):
        """Used by get_json, can be overridden to use specific switches"""
        return json.dumps(obj, default=utils.json_int_dttm_ser, ignore_nan=True)

so when the granularity in not all in table view, the timestamp will be like this:

### PR DESCRIPTION
**Pull request by flametest**
fix #1934, using iso serializer instead of int serializer in table view.

### CODE REVIEW

**Review by xrmx — APPROVED** [review]
~~~LGTM~~~

**Review by xrmx — DISMISSED** [review]
Could you please avoid removing simplejson? It's used in other parts of the code.

**Comment by flametest** [comment]
@xrmx hi, i found only one place that used simplejson in view.py, that's line 1408 where i modified the code. so i deleted this module in this file.

**Comment by xrmx** [comment]
I meant just for consistency wrt other superset code, i agree we should just use json and drop simplejson dependency altogether.

**Pull request merged**
