### PR TITLE
[WiP][explore] metrics as popovers

### PR DESCRIPTION
**Pull request by mistercrunch**
screen shot 2017-07-28 at 2 42 30 pm

### CODE REVIEW

**Comment by john-bodley** [comment]
@mistercrunch it seems these metrics don't persist in the DB so the state is local, and thus one couldn't share the URL with others. Is this correct?

**Comment by mistercrunch** [comment]
These are local to the Slice. Radio button #2 represents the list of predefined metrics as they exist now.

**Comment by williaster** [comment]
@mistercrunch would that be problematic for sharing urls that refer to these types of metrics? what would happen in that case? would an error be thrown?

**Comment by mistercrunch** [comment]
@williaster the metric definition is just part of the `formData` meaning it's in the URL

**Comment by mistercrunch** [comment]
Superseeded by https://github.com/apache/incubator-superset/pull/4663

**Pull request closed without merging**
