### PR TITLE
fix: humanised changed on UTC on dashboards and charts

### PR DESCRIPTION
**Pull request by dpgaspar**
### SUMMARY
This PR introduces the same concept used on dashboards `ModelView`'s for changed_on humanised text. Has reported on #10307 humanised dates differ from the API dashboard response and the MVC list `ModelView`.
Dashboard `ModelView` is always correct because it computes the timestamp humanised delta on the server, and the server is always coherent with itself since it automatically timestamps the `changed_on` and `created_on` fields and computes the humanised delta at the server side.

This PR introduces this concept to the API, and adds a `changed_on_utc` that assumes servers are always on UTC. Note that we are not submitting TZ dates to the backend and this should be later addressed

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Screenshot 2020-07-15 at 13 29 18

Screenshot 2020-07-15 at 13 29 59

### TEST PLAN
Change dashboards and charts on any TZ and assert the humanised timestamp is correct

### ADDITIONAL INFORMATION
- [X] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by villebro** [comment]
Do we need to add the new keys to this test to avoid introducing this flaky test again? #10021

**Comment by dpgaspar** [comment]
@villebro fixed the dashboard test and added a chart test for the humanized changed_on, also added the sort by for the humanized changed_on

**Review by villebro — APPROVED** [review]
LGTM! 💯

**Review by graceguo-supercat — APPROVED** [review]
LGTM!

**Review by nytai — APPROVED** [review]
lgtm :)

**Pull request merged**
