### PR TITLE
feat(build): uplift Lerna + replace insecure shortid with nanoid + uplift Yeoman-related packages + ESM-ize generator-superset

### PR DESCRIPTION
**Pull request by hainenber**
feat(build): uplift major version for CI-related packages

### SUMMARY

Uplift major version for notable CI-related packages. Notable changes:
- Uplift Lerna v6 to latest v8
- Replace unsupported and insecure `shortid` with successor `nanoid` + corresponding refactors
- Uplift `yeoman`-related packages to latest v7
- ESM-ize the `generator-superset` package in order to work with `yeoman-generator` v7

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by rusackas — COMMENTED** [review]
This is looking great to me... I just need to find time to test it out!

**Review by mistercrunch — APPROVED** [review]
LGTM

**Comment by mistercrunch** [comment]
I really appreciate all your solid contributions! I'll take a look at all your open PRs today.

**Review by rusackas — APPROVED** [review]
Generator seems to work! I echo Max... thanks for all the contributions!

**Comment by fisjac** [comment]
After the Lerna uplift, I'm experiencing build errors in docker when running build-dev. It appears the optional dependency @nx isn't being installed, but is required by Lerna post update. Anyone experiencing this?

**Comment by hainenber** [comment]
Can you share the build failure's screenshot? I ran `npm run build-dev` locally and it finishes as usual. Maybe you can run `npm ci` to ensure all packages installed as specified in the lockfile? 👀 

```
➜  superset-frontend git:(master) npm run build-dev

> superset@0.0.0-dev build-dev
> cross-env NODE_OPTIONS=--max_old_space_size=8192 NODE_ENV=development webpack --mode=development --color

[Superset Plugin] Use symlink source for @superset-ui/chart-controls @ ./packages/superset-ui-chart-controls
[Superset Plugin] Use symlink source for @superset-ui/core @ ./packages/superset-ui-core
[Superset Plugin] Use symlink source for @superset-ui/legacy-plugin-chart-calendar @ ./plugins/legacy-plugin-chart-calendar
[Superset Plugin] Use symlink source for @superset-ui/legacy-plugin-chart-chord @ ./plugins/legacy-plugin-chart-chord
[Superset Plugin] Use symlink source for @superset-ui/legacy-plugin-chart-country-map @ ./plugins/legacy-plugin-chart-country-map
[Superset Plugin] Use symlink source for @superset-ui/legacy-plugin-chart-event-flow @ ./plugins/legacy-plugin-chart-event-flow
[Superset Plugin] Use symlink source for @superset-ui/legacy-plugin-chart-heatmap @ ./plugins/legacy-plugin-chart-heatmap
[Superset Plugin] Use symlink source for @superset-ui/legacy-plugin-chart-histogram @ ./plugins/legacy-plugin-chart-histogram
[Superset Plugin] Use symlink source for @superset-ui/legacy-plugin-chart-horizon @ ./plugins/legacy-plugin-chart-horizon
[Superset Plugin] Use symlink source for @superset-ui/legacy-plugin-chart-map-box @ ./plugins/legacy-plugin-chart-map-box
[Superset Plugin] Use symlink source for @superset-ui/legacy-plugin-chart-paired-t-test @ ./plugins/legacy-plugin-chart-paired-t-test
[Superset Plugin] Use symlink source for @superset-ui/legacy-plugin-chart-parallel-coordinates @ ./plugins/legacy-plugin-chart-parallel-coordinates
[Superset Plugin] Use symlink source for @superset-ui/legacy-plugin-chart-partition @ ./plugins/legacy-plugin-chart-partition
[Superset Plugin] Use symlink source for @superset-ui/legacy-plugin-chart-rose @ ./plugins/legacy-plugin-chart-rose
[Superset Plugin] Use symlink source for @superset-ui/legacy-plugin-chart-sankey @ ./plugins/legacy-plugin-chart-sankey
[Superset Plugin] Use symlink source for @superset-ui/legacy-plugin-chart-sankey-loop @ ./plugins/legacy-plugin-chart-sankey-loop
[Superset Plugin] Use symlink source for @superset-ui/legacy-plugin-chart-world-map @ ./plugins/legacy-plugin-chart-world-map
[Superset Plugin] Use symlink source for @superset-ui/legacy-preset-chart-deckgl @ ./plugins/legacy-preset-chart-deckgl
[Superset Plugin] Use symlink source for @superset-ui/legacy-preset-chart-nvd3 @ ./plugins/legacy-preset-chart-nvd3
[Superset Plugin] Use symlink source for @superset-ui/plugin-chart-echarts @ ./plugins/plugin-chart-echarts
[Superset Plugin] Use symlink source for @superset-ui/plugin-chart-handlebars @ ./plugins/plugin-chart-handlebars
[Superset Plugin] Use symlink source for @superset-ui/plugin-chart-pivot-table @ ./plugins/plugin-chart-pivot-table
[Superset Plugin] Use symlink source for @superset-ui/plugin-chart-table @ ./plugins/plugin-chart-table
[Superset Plugin] Use symlink source for @superset-ui/plugin-chart-word-cloud @ ./plugins/plugin-chart-word-cloud
[Superset Plugin] Use symlink source for @superset-ui/switchboard @ ./packages/superset-ui-switchboard

28% building 4/12 entries 58/59 dependencies 25/41 modules`isModuleDeclaration` has been deprecated, please migrate to `isImportOrExportDeclaration`
    at isModuleDeclaration (/Users/dotronghai/Projects/github.com/apache/superset/superset-frontend/node_modules/@babel/types/lib/validators/generated/index.js:2748:35)
    at PluginPass.Program (/Users/dotronghai/Projects/github.com/apache/superset/superset-frontend/node_modules/babel-plugin-lodash/lib/index.js:102:44)
`isModuleDeclaration` has been deprecated, please migrate to `isImportOrExportDeclaration`
    at isModuleDeclaration (/Users/dotronghai/Projects/github.com/apache/superset/superset-frontend/node_modules/@babel/types/lib/validators/generated/index.js:2748:35)
    at PluginPass.Program (/Users/dotronghai/Projects/github.com/apache/superset/superset-frontend/node_modules/babel-plugin-lodash/lib/index.js:102:44)
`isModuleDeclaration` has been deprecated, please migrate to `isImportOrExportDeclaration`
    at isModuleDeclaration (/Users/dotronghai/Projects/github.com/apache/superset/superset-frontend/node_modules/@babel/types/lib/validators/generated/index.js:2748:35)
    at PluginPass.Program (/Users/dotronghai/Projects/github.com/apache/superset/superset-frontend/node_modules/babel-plugin-lodash/lib/index.js:102:44)
`isModuleDeclaration` has been deprecated, please migrate to `isImportOrExportDeclaration`
    at isModuleDeclaration (/Users/dotronghai/Projects/github.com/apache/superset/superset-frontend/node_modules/@babel/types/lib/validators/generated/index.js:2748:35)
    at PluginPass.Program (/Users/dotronghai/Projects/github.com/apache/superset/superset-frontend/node_modules/babel-plugin-lodash/lib/index.js:102:44)
`isModuleDeclaration` has been deprecated, please migrate to `isImportOrExportDeclaration`
    at isModuleDeclaration (/Users/dotronghai/Projects/github.com/apache/superset/superset-frontend/node_modules/@babel/types/lib/validators/generated/index.js:2748:35)
    at PluginPass.Program (/Users/dotronghai/Projects/github.com/apache/superset/superset-frontend/node_modules/babel-plugin-lodash/lib/index.js:102:44)
28% building 4/12 entries 563/594 dependencies 84/248 modules`isModuleDeclaration` has been deprecated, please migrate to `isImportOrExportDeclaration`
    at isModuleDeclaration (/Users/dotronghai/Projects/github.com/apache/superset/superset-frontend/node_modules/@babel/types/lib/validators/generated/index.js:2748:35)
    at PluginPass.Program (/Users/dotronghai/Projects/github.com/apache/superset/superset-frontend/node_modules/babel-plugin-lodash/lib/index.js:102:44)
`isModuleDeclaration` has been deprecated, please migrate to `isImportOrExportDeclaration`
    at isModuleDeclaration (/Users/dotronghai/Projects/github.com/apache/superset/superset-frontend/node_modules/@babel/types/lib/validators/generated/index.js:2748:35)
    at PluginPass.Program (/Users/dotronghai/Projects/github.com/apache/superset/superset-frontend/node_modules/babel-plugin-lodash/lib/index.js:102:44)
28% building 4/12 entries 851/1000 dependencies 177/299 modules`isModuleDeclaration` has been deprecated, please migrate to `isImportOrExportDeclaration`
    at isModuleDeclaration (/Users/dotronghai/Projects/github.com/apache/superset/superset-frontend/node_modules/@babel/types/lib/validators/generated/index.js:2748:35)
    at PluginPass.Program (/Users/dotronghai/Projects/github.com/apache/superset/superset-frontend/node_modules/babel-plugin-lodash/lib/index.js:102:44)
28% building 4/12 entries 1000/1071 dependencies 186/375 modules`isModuleDeclaration` has been deprecated, please migrate to `isImportOrExportDeclaration`
    at isModuleDeclaration (/Users/dotronghai/Projects/github.com/apache/superset/superset-frontend/node_modules/@babel/types/lib/validators/generated/index.js:2748:35)
    at PluginPass.Program (/Users/dotronghai/Projects/github.com/apache/superset/superset-frontend/node_modules/babel-plugin-lodash/lib/index.js:102:44)
`isModuleDeclaration` has been deprecated, please migrate to `isImportOrExportDeclaration`
    at isModuleDeclaration (/Users/dotronghai/Projects/github.com/apache/superset/superset-frontend/node_modules/@babel/types/lib/validators/generated/index.js:2748:35)
    at PluginPass.Program (/Users/dotronghai/Projects/github.com/apache/superset/superset-frontend/node_modules/babel-plugin-lodash/lib/index.js:102:44)
1059 assets
14017 modules
webpack 5.89.0 compiled successfully in 29595 ms
```

**Comment by fisjac** [comment]
I believe this error is specific to building with docker. When I sh into the superset_app contianer, I see that the optional dependencies aren't being built within the node_modules directory. Building locally with `npm i` seems fine. Opening a separate issue ticket.

**Comment by eschutho** [comment]
I'm hitting the same issue that @fisjac reported in our ci now. https://github.com/apache/superset/actions/runs/10119252433/job/27987414693?pr=29723

**Comment by kgabryje** [comment]
I'm also hitting it here https://github.com/apache/superset/pull/29788 🙁

**Comment by eschutho** [comment]
The side effects were fixed with @mistercrunch's PR [here](https://github.com/apache/superset/pull/29779).

**Pull request merged**
