### PR TITLE
docs: authentication type methods

### PR DESCRIPTION
**Pull request by blcksrx**
### SUMMARY
Apache superset use `flask-appbuilder` and also use the **authentication methods** provided. This PR is exact copy and pates of `flask-appbuilder` docs about authentication methods and types that become superset's docs more useful.

### ADDITIONAL INFORMATION

- [x] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by etr2460 — COMMENTED** [review]
Instead of copy pasting, why not link out to the FAB documentation page that's relevant? That way this won't get out of date when FAB updates and we use the new version

**Comment by blcksrx** [comment]
It's a good idea, I'm going to change my PR.

**Review by mistercrunch — APPROVED** [review]

**Comment by willbarrett** [comment]
LGTM once conflicts are resolved.

**Comment by blcksrx** [comment]
@willbarrett I did it. but idk whats wrong with cypress

**Comment by willbarrett** [comment]
It's likely a flake. You can either push a whitespace commit or close/reopen to trigger another run. It appears the system failed attempting to upload coverage info (🤦 )

**Comment by blcksrx** [comment]
@willbarrett Done :D

**Pull request merged**
