### PR TITLE
fix(dashboard): scope status of filter not update in dashboard metadata

### PR DESCRIPTION
**Pull request by stephenLYZ**
### SUMMARY

This PR fixes the problem that the scope status of filter which adds to the dashboard is not updated in the dashboard json metadata, steps to reproduce:
1.  add a nativeFilter to the dashboard
2. edit dashboard and see the json metadata
3.  metadata don't have field `chartsInScope` and `filterConfig`

It will cause the incorrect scope status if we update the native filter via json metadata like this issue  https://github.com/apache/superset/issues/17932
### before

https://user-images.githubusercontent.com/11830681/148345707-509eecf8-086c-422a-9472-957b5bd4b72e.mov

### after

https://user-images.githubusercontent.com/11830681/148345724-a86cc1b5-b96b-46a8-9e6e-0007b8bf33d6.mov

### ADDITIONAL INFORMATION

- [x] Has associated issue: Fixes https://github.com/apache/superset/issues/17932
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by jinghua-qa** [comment]
[sc-34490]

**Comment by jinghua-qa** [comment]
/testenv up FEATURE_DASHBOARD_NATIVE_FILTERS=true FEATURE_DASHBOARD_CROSS_FILTERS=true FEATURE_ENABLE_EXPLORE_DRAG_AND_DROP=true FEATURE_UX_BETA=true

**Comment by jinghua-qa** [comment]
Stephen I have tested the PR in the env, i saw some issues
1, when i create a native filter, it put the filter out of scope even i selected all scope
2, the edit in metadata fornative filters seems not stay
Here is the video
https://user-images.githubusercontent.com/81597121/148483193-14bb16e7-f624-408a-b5ff-ef75d25ae941.mov

**Review by rusackas — APPROVED** [review]
LGTM! @jinghua-qa if you could give this a test bashing before we merge, that would be great!

**Comment by rusackas** [comment]
/testenv up FEATURE_DASHBOARD_NATIVE_FILTERS=true FEATURE_DASHBOARD_CROSS_FILTERS=true FEATURE_ENABLE_EXPLORE_DRAG_AND_DROP=true FEATURE_UX_BETA=true

**Review by jinghua-qa — APPROVED** [review]
LGTM

**Comment by rosemarie-chiu** [comment]
🏷 2022.1

**Pull request merged**
