### PR TITLE
Permissions cleanup: remove none and duplicates.

### PR DESCRIPTION
**Pull request by bkyryliuk**
We have a lot of duplicates in perms and that makes UI unresponsive.
This script cleans them up, tested on staging.

Reviewers: @mistercrunch, @ascott, @vera-liu

### CODE REVIEW

**Comment by mistercrunch** [comment]
Would be easy to put this in the CLI. If you don't want it to be "public" I'd go for a `scripts` folder instead of `one_offs`. `scripts` folder should probably be in the root of the repo if we don't want to package this

**Comment by bkyryliuk** [comment]
thanks @mistercrunch  - moved to the scripts. This should be one off as bugs were resolved.

**Comment by mistercrunch** [comment]
LGTM!

**Comment by bkyryliuk** [comment]
thanks !

**Pull request merged**
