### PR TITLE
chore: change order of tab on explore data panel 

### PR DESCRIPTION
**Pull request by lilykuang**
### SUMMARY

- show metrics before columns on explore data panel

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

**After**
https://www.loom.com/share/b8c248ca475a493c9d8925a91c086d45

### ADDITIONAL INFORMATION

- [x] Has associated issue: #12316 
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by pkdotson — APPROVED** [review]
LGTM!

**Comment by adam-stasiak** [comment]
OK for me after test!

**Review by junlincc — COMMENTED** [review]
thanks for the fix! 
ezgif-7-042034e00752

@lilykuang, could you please make sure the changes made in  [fix(explore): metrics caret not expanding in datasource panel](https://github.com/apache/superset/pull/12305) are captured in your PR? - both sections open by default. 

not ready to merge yet.

**Review by junlincc — APPROVED** [review]
ezgif-7-38ff703f1fd1

tested again, both section open by default. approving

**Pull request merged**
