### PR TITLE
Add show metadata button back to the explore view

### PR DESCRIPTION
**Pull request by xtinec**
- Add the show metadta button, accidentally removed from PR #6046, back to the explore view
- Remove dead code that is no longer reachable from DataSourceModal.jsx.

### CODE REVIEW

**Comment by mistercrunch** [comment]
I removed it since I thought it wasn't really relevant anymore (superset of the information can be shown in the modal)

**Comment by xtinec** [comment]
> I removed it since I thought it wasn't really relevant anymore (superset of the information can be shown in the modal)

Interesting. @vylc @dorq to chime in. UX suggested adding this button back during the testing of `0.31` for the convenience it provides in the explore view. Worth discussing here whether we want this button for `0.31` and beyond.

**Comment by mistercrunch** [comment]
Yeah I don't have a strong opinion one way or another.

**Comment by vylc** [comment]
we should add back in--takes at least 2 clicks + scroll to view columns via modal vs. 1 click w/ '+' button

**Comment by mistercrunch** [comment]
LGTM

**Review by mistercrunch — APPROVED** [review]
LGTM

**Comment by michellethomas** [comment]
hey, just noticed this got merged, I've been working on #6816 to add back the ability to change the datasource from explore, as part of this we wanted to put the icons under a dropdown so that we don't have so many icons next to datasource. The show metadata button doesn't really work super well under a dropdown, and I'm not sure if it would be confusing to have both a dropdown and an icon next to the datasource. 

I'll resolve the conflicts and look into different options for the show metadata button along with the dropdown. If anyone has any thoughts or suggestions let me know @xtinec @mistercrunch

**Comment by vylc** [comment]
Let's have design propose some suggestions? i think the only requirement for the use case of creating a chart is that there needs to be a frictionless way for a user to scan through the columns and decide what to put on the chart. It doesn't need to persist throughout the entire chart creation, so the collapse/expand model works pretty well. @elibrumbaugh

**Comment by michellethomas** [comment]
@vylc  What if we put the metadata info in a modal? This would also be 2 clicks to get to so it's similar to just using the datasource editor, but clearly listing "See datasource metadata" in a dropdown might make it feel easier to use.

I'm concerned that having an icon next to a dropdown button would be confusing, and the collapse / expand metadata doesn't fit into a dropdown. If we need to use collapse/expand for metadata, it seems like we may just need to go back to listing a number of icons next to each other (which doesn't seem ideal).

I'm not sure design has time to do another round of review soon to make it fit with this addition, so it would be good to discuss options on our own first.

**Comment by vylc** [comment]
@michellethomas only issue with modal is that it blocks you from actually working on the chart, so you have to x it out in order to add fields, then enable again to view, whereas the expand/collapse allows you to scroll
hmmm...what does your dropdown look like right now?

**Comment by michellethomas** [comment]
@vylc This is what the dropdown looks like: https://github.com/apache/incubator-superset/pull/6816#issuecomment-463457413

**Comment by michellethomas** [comment]
If we don't have much time for design iteration right now, I can add the change datasource back as an icon and save the design changes for whenever we want to clean up this section.

**Comment by vylc** [comment]
@michellethomas dropdown looks good. i think it might be okay to still have the + next to it... designers probably shudder at this, but is at least intuitive

**Pull request merged**
