### PR TITLE
chore(toggle thumbnails): use localstorage for toggle

### LINKED ISSUE #14158: [dashboard] dashboard card view is not showing thumbnail in dashboard list
dashboard card view is not showing thumbnail in preset

### Expected results

dashboard card view will show thumbnail

### Actual results

dashboard card view is not showing thumbnail

#### Screenshots

Screen Shot 2021-04-14 at 10 49 05 PM

#### How to reproduce the bug

1. Go to 'Dashboards
2. Click on card view icon on the left corner  of the tool bar

### Environment

- superset version:  preset 2021.15.0 Development

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [Y] I have reproduced the issue with at least the latest released version of superset.
- [Y] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by pkdotson**
### SUMMARY
This is follow up for toggle thumbnails for homescreen to make the listviews show thumbnails based off homescreen toggle.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

https://user-images.githubusercontent.com/17326228/113974491-e1235100-97f2-11eb-9524-808d7f44b4d4.mov

### TEST PLAN
enable feature flag THUMBNAILS = True
check each listview for toggle of thumbnails

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by junlin-qa — COMMENTED** [review]
Tested locally! LGTM when thumbnail is NOT enabled! Thanks for the fix 🙏  
When thumbnail IS enabled, the default is still card view, can we make it consistent, default to list for all time? @pkdotson 
please note: currently view is not sticky. after user switch from list to card view, and refresh, it lands on list view again. that should be the expected behavior as well. 

https://user-images.githubusercontent.com/80974222/114069779-36dc1580-9854-11eb-92fd-d0b43a4404e4.mov

**Review by junlin-qa — APPROVED** [review]

**Comment by rusackas** [comment]
> When thumbnail IS enabled, the default is still card view, can we make it consistent, default to list for all time? @pkdotson

My understanding is that the selection of list/cards should be set via `LISTVIEWS_DEFAULT_CARD_VIEW` and decoupled from the thumbnail feature flag (`THUMBNAILS`).

> please note: currently view is not sticky. after user switch from list to card view, and refresh, it lands on list view again. that should be the expected behavior as well.

As I understand from the title, the "stickiness" is the point of this PR... the description could probably be clearer on this the intent, and the testing steps). If the view setting is not being saved/retrieved here, then something may be wrong.

**Review by villebro — APPROVED** [review]
LGTM!

**Comment by henryyeh** [comment]
label:2021.13

**Comment by henryyeh** [comment]
:label:2021.13

**Comment by henryyeh** [comment]
:label:2021.13

**Pull request merged**
