### PR TITLE
chore: Improves the Select component UI/UX - iteration 3

### PR DESCRIPTION
**Pull request by michael-s-molina**
### SUMMARY
Improves the `Select` component UI/UX - iteration 3.

Storybook changes:

Interactive Select
- Adds the remaining properties
- Hides the options control
- Shows a radio group with no header, text header, and ControlHeader

Page Scroll
- Adds a panel to show how the Select behaves when there's a scroll on the page

Select component changes:
- Shows the loading indicator while scrolling
- Improves the error handling
- Removes unnecessary `useEffects`
- Paginates a few px before the bottom of the scroll for better UX
- Adds the `invertSelection` option
- Changes the API to only expose single and multiple modes
- Removes the usage of `any` from the implementation
- Improves the support for pagination 

Improvements/tasks that will be done in the next iterations:
- Add RTL tests

@rusackas @geido @villebro @pkdotson @kgabryje @suddjian @zhaoyongjie 
This component will be used by everyone. Please take the time to learn the API, play with the different controls, review and test.

PS: Sometimes the storybook is producing a 404 error. We need to investigate that in another PR and also update the Storybook version. For now, if you find the error, you only need to delete the `.cache` folder inside `node_modules` to make it work.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
https://user-images.githubusercontent.com/70410625/123261304-f7c17600-d4cc-11eb-9a1e-a353749c921a.mov

https://user-images.githubusercontent.com/70410625/123261311-fb54fd00-d4cc-11eb-80c9-938aba099702.mov

### TESTING INSTRUCTIONS
1- Start the storybook
2 - Open the Select panels
3 - Test the controls

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by geido — APPROVED** [review]
Code LGTM! Thanks for the improvements 👍

**Comment by rusackas** [comment]
On the Async Select story, I noticed that if you turn on the `allowNewOptions` prop, the behavior is not as I'd expect.

If you type some gibberish into the input, and hit return, it DOES create the new list item, but it does NOT select it. I expected it would, but the prior selected value remains selected and displayed.

**Comment by rusackas** [comment]
Minor nit, or something for a future iteration: The Interactive Select might benefit from a separate "selected values" display, to prove that the `invertSelection` prop works as expected.

**Review by rusackas — APPROVED** [review]
Loving the improvements to the Storybook, and the code in general. This component is looking fantastic!!!

I could only find one thing that didn't behave quite as I'd expected, but since it seems like it could be handled in a future iteration, I'm marking this PR as approved!

**Review by villebro — APPROVED** [review]
This is looking really great, LGTM!

**Comment by michael-s-molina** [comment]
> Minor nit, or something for a future iteration: The Interactive Select might benefit from a separate "selected values" display, to prove that the `invertSelection` prop works as expected.

@rusackas An interesting point here. Actually, the selected values are the same, we just change the icon from the checkmark to the forbidden one. It's just an indication that the selected items will be excluded. With this behavior in mind, do you think there is a more appropriate name for it or that's ok?

**Comment by rusackas** [comment]
> > Minor nit, or something for a future iteration: The Interactive Select might benefit from a separate "selected values" display, to prove that the `invertSelection` prop works as expected.
> 
> @rusackas An interesting point here. Actually, the selected values are the same, we just change the icon from the checkmark to the forbidden one. It's just an indication that the selected items will be excluded. With this behavior in mind, do you think there is a more appropriate name for it or that's ok?

Sounds reasonable to me for now!

**Pull request merged**
