### PR TITLE
fix: Fixes right menu layout in different screen sizes

### LINKED ISSUE #14649: Right menu drops  to full column on page resize
## Screenshot
Screen Shot 2021-05-14 at 1 56 38 PM

## Description
The right menu col size spreads to 24 on page resize from lg to md. 

## Design input
Should reduce col size on smaller views so the the right menu stay in line with overall navbar.

### PR DESCRIPTION
**Pull request by michael-s-molina**
### SUMMARY
Fixes https://github.com/apache/superset/issues/14649.

@rusackas @junlincc @pkdotson 

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
https://user-images.githubusercontent.com/70410625/118643085-7df1ea80-b7b2-11eb-99af-db085a89fcde.mov

https://user-images.githubusercontent.com/70410625/118642802-281d4280-b7b2-11eb-9886-9bb7186a80af.mov

### TEST PLAN
1 - Resize screen
2 - Check the right menu behaviour 

### ADDITIONAL INFORMATION
- [x] Has associated issue:
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by pkdotson — APPROVED** [review]
I pulled the code and LGTM! Thanks for the fix.

**Comment by pkdotson** [comment]
I do notice however when the language selector is not in the right menu there is a lot of padding in betweeen the plus icon and settings. 
Screen Shot 2021-05-18 at 4 03 07 PM

**Review by pkdotson — COMMENTED** [review]
I do notice however when the language selector is not in the right menu there is a lot of padding in betweeen the plus icon and settings. 
Screen Shot 2021-05-18 at 4 03 07 PM

**Review by pkdotson — COMMENTED** [review]
I do notice however when the language selector is not in the right menu there is a lot of padding in betweeen the plus icon and settings. 
Screen Shot 2021-05-18 at 4 03 07 PM

**Comment by michael-s-molina** [comment]
> I do notice however when the language selector is not in the right menu there is a lot of padding in betweeen the plus icon and settings.
> Screen Shot 2021-05-18 at 4 03 07 PM

@pkdotson To fix this I changed the style of `src/common/components/index.tsx -> StyledNav`. Since you worked on the menus, please let me know if this won't introduce any regression.
https://github.com/apache/superset/pull/14689/files#diff-3cb5009f3350abc77ce448ae6bfc6e9dcd99b461136ac4beaf53f0f843ecfccc

**Comment by junlincc** [comment]
hi!menu items seem not aligned on resize?

**Comment by michael-s-molina** [comment]
> hi!menu items seem not aligned on resize?

My last commit fixed @pkdotson comment. The ephemeral env was not updated though.

**Review by rusackas — APPROVED** [review]
LGTM, works with and without the language menu displayed.

**Pull request merged**
