### PR TITLE
feat: move sql lab save and copy buttons

### PR DESCRIPTION
**Pull request by eschutho**
#### In all cases:

*On an Unsaved Query:* 

* Show “Save As” button 
** This opens the Save Query modal

*On a saved query:* 

* Show “Save” button 
** This opens the Save Query modal
* Copy Link button is active and shows tooltip
* Copy Link copies a link to the clipboard
* Confirmation toast shows after user has copied the link 

#### When the {{SHARE_QUERIES_VIA_KV_STORE}} feature flag is enabled: 

User has the ability to copy a share link for an unsaved query

*On an Unsaved Query:* 

* Copy Link button is active and shows tooltip
* Copy Link copies a link to the clipboard
* Confirmation toast shows after use has copied the link

#### When the {{SHARE_QUERIES_VIA_KV_STORE}} feature flag is disabled: 

*On an unsaved query:* 

* Copy Link is disabled and shows tooltip about saving first 

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Before: 
Screenshot_12_16_20__5_18_PM
After: 

copylink

### TEST PLAN
jest tests should pass.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [x] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by eschutho** [comment]
I exited a few tests that I think would be better tested with RTL that we can focus on after the break.

**Comment by eschutho** [comment]
@hughhhh @betodealmeida this is ready for review

**Comment by eschutho** [comment]
retry cypress

**Review by hughhhh — APPROVED** [review]
👍

**Pull request merged**
