### PR TITLE
fix: Select options overflowing Save chart modal on Explore view

### LINKED ISSUE #12521: Add To Dashboard Modal dropdown is hidden
When Saving a Chart the option to ADD TO DASHBOARD is hidden. 

### Expected results

To show the dropdown list.

### Actual results

Shows only 1 dashboard and need to use scroll bar to see more 
#### Screenshots

In an instance with many dashboards available 
1. Go to any chart 
2. Click on save
3. Scroll down to ADD TO DASHBOARD 

### Environment

- superset version: 01/13/2021 release 
- 
### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by kgabryje**
### SUMMARY
Fixes https://github.com/apache/superset/issues/12521

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Before: see linked issue
After:
image

### ADDITIONAL INFORMATION

- [x] Has associated issue: https://github.com/apache/superset/issues/12521
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

CC: @villebro @junlincc @eugeniamz

### CODE REVIEW

**Review by villebro — APPROVED** [review]
LGTM

**Comment by kgabryje** [comment]
Closing - duplicate of https://github.com/apache/superset/pull/12502

**Review by junlincc — APPROVED** [review]
lgtm! Have to reopen this PR. as #12502 doesn't include solution for the dropdown overflow issue in the Explore save modal

**Comment by junlincc** [comment]
@robdiciuccio Rob, tests seem slow again, do you know if anyone internal is working on it? we will need a few more PRs to get in 1.0 rc3. Thanks!

**Comment by junlincc** [comment]
@villebro thanks for fixing the ut!

**Pull request merged**
