### PR TITLE
Link to database-urls in databaseadd view

### PR DESCRIPTION
**Pull request by dirkkelly**

### CODE REVIEW

**Comment by xrmx** [comment]
Shouldn't we make the string traslatable while at it?

**Comment by dirkkelly** [comment]
I'm not sure how to do this and the rest of the file is not translatable. I think that would belong in a separate PR, this simply turns an on screen URL into a link.

**Comment by xrmx** [comment]
Il 31/10/2016 14:06, Dirk Kelly ha scritto:
> I'm not sure how to do this and the rest of the file is not translatable. I
> think that would belong in a separate PR, this simply turns an on screen URL
> into a link.

The other columns are translatable, it should just be a matter of this:

utils.markdown(_(
...
)

**Comment by dirkkelly** [comment]
Sure! I see what you mean, I'll add this PR and do the same [here on 512](https://github.com/airbnb/caravel/pull/1480/files#diff-e9b1e371eebef6df66bd8cde507e5931L512).

**Comment by dirkkelly** [comment]
Thanks @mistercrunch, really appreciate Caravel and looking forward to using it more and more.

**Pull request merged**
