### PR TITLE
chore: bump storybook to 6.5.16

### PR DESCRIPTION
**Pull request by csouchet**
### SUMMARY
Migrate to the latest 6 version of Storybook to migrate in another PR to the 7 version of Storybook.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

| Before | After |
|--------|--------|
| image | image |
| image | image | 

### TESTING INSTRUCTIONS

```shell
cd superset-frontend
npm i
npm run storybook
npm run plugins:storybook
```

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by csouchet** [comment]
I don't understand why some workflows failed because of some unused variables or of prettier. I didn't change those parts :slightly\_frowning\_face:

**Comment by rusackas** [comment]
Well, storybook runs fine on this branch, but the linters are having a BAD time for some reason. I haven't gotten to the bottom of it, but hope I can find time to investiate. I appreciate what you're doing here :)

**Comment by csouchet** [comment]
@rusackas Thank you very much for the investigation. I tried to look for the problem too, but not mastering all the code, it's quite complicated for me to find the reason.  
I might dive back into it a bit later when I have some time 😊

**Comment by csouchet** [comment]
@rusackas After reverting the update of the `@applitools/eyes-storybook` dependency, `npm run lint` and `npm run prettier-check` work fine in local 🙂

**Pull request closed without merging**
