### PR TITLE
Revert "Autocomplete in the table browser in SQL lab is broken (#7736)"

### PR DESCRIPTION
**Pull request by khtruong**
Accidentally broke connecting to tables after searching. Reverting this change.

This reverts commit d1b81e04ac7a8d4e877471432c9bccbd7b369f81.

#### REVIEWERS
@betodealmeida @DiggidyDave @xtinec

### CODE REVIEW

**Comment by betodealmeida** [comment]
+1

**Comment by betodealmeida** [comment]
Looks like the backend should return the tables in a standardized format, and it's not

**Review by etr2460 — APPROVED** [review]
Lgtm

**Comment by villebro** [comment]
I believe the observed bug has its origins in changes introduced by #7453, which changes table names from strings to dicts/objects:
- Before: tables were strings of format `'my_table'` or `'my_schema.my_table'`
- Now: `{ schema: 'my_schema', table: 'my_table' }`

The change was done because many engines support periods in the object names, which confused the frontend. However, apparently there were side-effects that were not covered by unit tests. If having tables in object format causes problems, one solution could be to make them strings again, but make sure periods in object names are properly escaped.

**Pull request merged**
