### PR TITLE
[tests] Fix, removing deprecated function for future Python release compatibility.

### PR DESCRIPTION
**Pull request by MarcusSorealheis**
### CATEGORY

Choose one

- [ ] Bug Fix
- [x] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY

Here, I replaced all the occurrences of `assertEquals` with `assertEqual` in the test files in anticipation of its removal in future Python releases. The alias has been deprecated for sometime.

### TEST PLAN

run tests.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### REVIEWERS
@betodealmeida or someone else that works on tests.

### CODE REVIEW

**Comment by MarcusSorealheis** [comment]
run tests

**Comment by dpgaspar** [comment]
Extra info on this: https://docs.python.org/3/library/unittest.html#deprecated-aliases

@MarcusSorealheis while your at it, can I ask you to change `assertNotEquals` also? (found 2 lines)

**Comment by MarcusSorealheis** [comment]
thanks @dpgaspar

**Comment by MarcusSorealheis** [comment]
@dpgaspar does this LGTM?

**Comment by MarcusSorealheis** [comment]
here is where CI failed (which is unrelated to the change):  

``` (Run Finished)
      Spec                                    Tests  Pass…  Fail…  Pend…  Skip… 
  ┌────────────────────────────────────────────────────────────────────────────┐
  │ ✖ sqllab/index.test.js            00:20      5      2      1      2      - │
  └────────────────────────────────────────────────────────────────────────────┘
    1 of 1 failed (100%)              00:20      5      2      1      2      -  
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! superset@0.999.0-dev cypress: `cypress "run" "--spec" "cypress/integration/sqllab/*" "--record" "false" "--config" "video=false"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the superset@0.999.0-dev cypress script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2019-10-07T17_16_10_188Z-debug.log
ERROR: InvocationError for command /home/travis/build/apache/incubator-superset/superset/assets/cypress_build.sh sqllab (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   cypress-sqllab: commands failed
The command "tox" exited with 1.```

**Review by mistercrunch — APPROVED** [review]

**Review by dpgaspar — APPROVED** [review]
LGTM

**Pull request merged**
