### PR TITLE
feat(native-filters): Hide time filters if loaded datasets don't have temporal columns

### LINKED ISSUE #15068: [native-filters]hide time related filters when there's no temporal column in datasets
Requirement: Hide all 3 time related filters when there's no temporal columns in datasets that support charts on dashboard.

Please test with dashboard that has at least two datasets. 1) both don't have temporal columns, 2) only one has 

Edge case: If a dashboard has charts created from dataset A(has temporal column) and charts created from dataset B (without temporal column), when user create a time range filter, charts created from dataset B should be unscoped in the scoping tree by default. 

-------------------
image

It appears that the COVID dataset doesn't have a temporal column. Which raises the question, we should probably not show a time filter (or time column filter for that matter) if there are no temporal columns available in the target dataset. However, this same problem applies to Filter Box as well, so I propose leaving that to a later PR.

_Originally posted by @villebro in https://github.com/apache/superset/issues/15015#issuecomment-857412274_

### PR DESCRIPTION
**Pull request by kgabryje**
### SUMMARY
If none of the datasets used by charts on current dashboard have any temporal columns, there's no point in applying Time range, Time column or Time grain filters to them. This PR implements disables selecting those filter types on dashboards without datasets with temporal columns.
Also, there's no point in pre-filtering by time range datasets without temporal columns. This PR implements hiding time range picker pre-filter if current dataset doesn't have temporal columns.
I also removed "px" suffix from "0px" css values to remove linter warnings.

Second part of the related issue (https://github.com/apache/superset/issues/15068) was excluding charts that use dataset without temporal columns from scope when creating a time filter. We've decided to handle this as a separate issue (https://github.com/apache/superset/issues/14977). CC @junlincc 

Rejected alternatives: hiding time filters instead of disabling options in select button. We decided that it might be confusing for the users if some filter types just "disappeared".

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Before: see https://github.com/apache/superset/issues/15068

After:
Case 1: only datasets without temporal columns - time filters disabled, time range pre-filter hidden
https://user-images.githubusercontent.com/15073128/122394612-7589fc80-cf76-11eb-9af4-f3662b71d432.mov

Case 2: only some datasets have temporal columns - time filters enabled, time range pre-filter hidden if a dataset without temporal columns is selected ("threads" dataset has temporal columns, "members_channels_2" doesn't)
https://user-images.githubusercontent.com/15073128/122388521-3eb0e800-cf70-11eb-96b6-ad5f2651bf69.mov

### TESTING INSTRUCTIONS
0. Enable `DASHBOARD_NATIVE_FILTERS` feature flag
1. Create a dashboard using datasets without temporal columns (e.g. `covid_vaccines` from test data)
2. Open native filters modal, verify that only Value and Numerical Range filter types are enabled.
3. Create a dashboard using multiple datasets, some of which have temporal columns, and some don't
4. Open native filters modal, verify that all 5 filter types are available
5. Select a dataset with temporal columns and check `Pre-filter available values`. Verify that time range filter shows up
6. Select a dataset without temporal columns and go to pre-filtering section. Verify that time range filter doesn't show up.

### ADDITIONAL INFORMATION

- [x] Has associated issue: fixes #15068 
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by villebro — APPROVED** [review]
LGTM - code looks good and works as expected in testing 👍

**Comment by michael-s-molina** [comment]
@kgabryje I don't need to remove the `px` from the zeros 😆. The CSS minifiers will do that anyway.

**Comment by kgabryje** [comment]
> @kgabryje I don't need to remove the `px` from the zeros 😆. The CSS minifiers will do that anyway.

I know, but Webstorm was displaying lot's of warnings 😄 
image

**Review by michael-s-molina — APPROVED** [review]
LGTM. Nice idea!

**Comment by michael-s-molina** [comment]
> > @kgabryje I don't need to remove the `px` from the zeros 😆. The CSS minifiers will do that anyway.
> 
> I know, but Webstorm was displaying lots of warnings 😄
> image

Oh, gotcha! I hate warnings too 🤣

**Comment by graceguo-supercat** [comment]
i am scanning dashboards with current master branch.
this PR cause many of our dashboards can not add time filter. Could you investigate and test it?

**Comment by villebro** [comment]
@graceguo-supercat This PR relies on backend functionality added in this PR: #15188 . I can investigate this.

**Comment by villebro** [comment]
I am unable to reproduce this problem. I created a datasource with the following columns:
image

When I check the available datatypes in for the datasource in the Dashboard view in Redux, they show up correctly (check `column_types`, where `0 == GenericDataType.NUMERIC`, `1 == GenericDataType.STRING`,  `2 == GenericDataType.TEMPORAL`, `3 == GenericDataType.BOOLEAN`):
image

When I attempt to add a temporal filter, it works as expected:
image

When I uncheck "is temporal", the temporal datatype is removed from Redux, and consequently the temporal filter types are also removed from the filter config modal as expected:
image

image

image

**Comment by kgabryje** [comment]
@graceguo-supercat I tested on a few dashboards and I can't reproduce the issue.
Case 1: a dashboard with multiple datasets, some of them have temporal columns and some don't (Slack Dashboard from test data) - time filters are available.

Case 2: a dashboard with 1 dataset with temporal columns (World Bank's Data), time filters are available

Case 3: a dashboard with a dataset which doesn't have temporal columns (Covid Vaccine Dashboard), time filters are unavailable.

Case 4: Covid Vaccine Dashboard with manually added temporal column through Edit Dataset modal, time filters are available.

**Pull request merged**
