### PR TITLE
Filter box keep selected values after refresh

### PR DESCRIPTION
**Pull request by gbrian**
HI,

Filter box looses the selected value after refresh. Please check this fix. 
I had few issues building development environment so I managed so manually this fix.
Hope next time to provide a better PR

### CODE REVIEW

**Comment by mistercrunch** [comment]
Awesome! Can you please run `npm run lint` and clear the lint log? I'll add a note to the `CONTRIBUTING.md`

For now it's buried a the end of the travis logs...

**Comment by gbrian** [comment]
HI,

This is the output, sorry can't see any error/warning
image

**Comment by mistercrunch** [comment]
screen shot 2016-03-16 at 10 16 22 pm

**Comment by gbrian** [comment]
Ok, thanks!
I'll check why is this not been shown on my local. Fixing...

**Comment by mistercrunch** [comment]
This has been lingering, reopen when fixed.

**Pull request closed without merging**
