### PR TITLE
[format] Using Black

### PR DESCRIPTION
**Pull request by john-bodley**
### CATEGORY

Choose one

- [ ] Bug Fix
- [x] Enhancement (new features, refinement)
- [x] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY

Though for Python we currently use `flake8` and `pylint` for linting and error checking these don't auto-format the code and thus it's still relatively hard to try to enforce a common code style/format. 

There seems to be three main auto-formatters: 

- [autopep8](https://github.com/hhatto/autopep8)
- [YAPF](https://github.com/google/yapf)
- [Black](https://github.com/python/black)

[Here's](https://medium.com/3yourmind/auto-formatters-for-python-8925065f9505) a fairly good comparison of the three tools. Note that YAPF supports a number of styles including "pep8" (which is what autopep8 uses). The "Facebook" style is similar to Black. 

Though I don't necessarily agree with all of Black's style formatting (including the 88 character line length, non-trailing commas, double-quotes, etc.) it seems this has gained popularity(it currently has over 11,000 GitHub stars) over the likes of YAPF mostly because it _isn't_ configurable (and thus ensures consistency) which is a plus if the goal is to align on a style/format across numerous repos. 

This PR performs the following:

1. Formats all the code using the Black format. 
2. Adds a pre-commit hook to auto-format the diff using the Black format on every local commit. 
3. Adds a CI check to ensure that the code is Black format compliant. 

Note the` flake8` and `pylint` CI remains as `flake8` includes checks for import ordering as well as type checking. `pylint` additionally checks for numerous errors. In the future there would be merit in further cleaning up the code and reducing the number of `flake8` codes we ignore. 

### TEST PLAN

CI.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### REVIEWERS

to: @betodealmeida @michellethomas @mistercrunch @villebro

### CODE REVIEW

**Comment by mistercrunch** [comment]
I've been meaning to do this for a while. Black is the way to go.

We could do a 2 phase rollout with `black -S` (skipping the single/vs/double quote issue) first.

Happy to just byte the bullet and go for it.

We might want to have more automation around pre-commit hooks too, something like Husky in the JS world, but on the python side. Looks like there's a `pre-commit` pypi package that could help with that:
https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/

**Comment by john-bodley** [comment]
@mistercrunch I can try the two phase rollout to minimize the change. Regarding `pre-commit` I'm using the suggestion in the doc per [here](https://github.com/john-bodley/incubator-superset/blob/john-bodley--black/.pre-commit-config.yaml).

**Comment by mistercrunch** [comment]
Now thinking about it I'm thinking making it straight black is best, two phases would just be more confusing... There will be lots of conflicts, but resolving them is easy: just run black.

**Comment by john-bodley** [comment]
@mistercrunch are you ok with me merging this once the CI checks have passed? I realize that the PR will cause a number of conflicts in existing PRs, though as you pointed out, resolving these are trivial.

**Review by mistercrunch — APPROVED** [review]
LGTM - deterministic code style FTW!

**Comment by mistercrunch** [comment]
black-square

**Pull request merged**
