### PR TITLE
style: improve "Datasource & Chart Type" <Label>s

### PR DESCRIPTION
**Pull request by mistercrunch**
## after
Screen Shot 2020-09-20 at 12 20 03 PM

## before
Screen Shot 2020-09-20 at 12 21 09 PM

# storybook
Screen Shot 2020-09-20 at 12 17 14 PM

### CODE REVIEW

**Comment by ktmud** [comment]
Overall great improvements! But I'm a little worried that the interaction with DatasourceControl may have become a little more confusing. The gray pill looks the same like the clickable labels in other controls (Viz Type and Time Range) but is not actually clickable. Using the cog icon for a dropdown menu also seems a little anti-pattern. What do you think of keeping it as a dropdown menu and limiting this PR to just changing the style?

**Comment by mistercrunch** [comment]
I totally agree about the dataset label, maybe the label should have a caret and be a dropdown button, but it seemed harder than it should be to do that.

**Comment by JunlinC** [comment]
may I humbly ask UI changes can somehow go thru Product and Design? 🙏 I was planning to work on those labels with Design next sprint. we received some feedback from multiple users ... @mistercrunch

**Comment by mistercrunch** [comment]
@JunlinC  I tagged `design-review` for input!

About the motives, I think the recently tweaked default <Label> is way too dark and "pops" way too much in this current state. The previous "white on a lighter gray" had usability issues, so I figure I'd go "black on light-gray with a light border" and it looks much better to me than before.

More generally, I'm not sure if the label-with-popover pattern for controls is the right approach. I'd be curious to see how it would look if we'd redesign it from scratch.

Open to suggestion & tweaks!

**Comment by mistercrunch** [comment]
Screen Shot 2020-09-22 at 11 05 49 PM

**Comment by rusackas** [comment]
There's [another PR ](https://github.com/apache/incubator-superset/pull/11033/)open where all the icons are moving over from the design system to the codebase. I'm trying to keep the names matching between Figma and the code, so there's a bit of overlap/misalignment with what's in this PR.

In this PR, you're adding a few icons, which are _also_ in the other one, but with different names. Would it be OK to ask for rebasing/renaming when that other PR slides in, lest they both merge and we have duplicates?

Mapping (names):
cog -> gear
minus-circle -> minus
plus-circle -> plus

FWIW, the emerging standard for naming seems to be underscores in filenames (partly thanks to Figma) and dashes in the name values, as you have it.

**Comment by rusackas** [comment]
I also took some of your ideas and melded them into https://github.com/apache/incubator-superset/pull/11034 which uses your inverted/lightened default color, but treats the stroke/border idea differently, applying it to labels of _any_ color, but only when they have an `onClick` handler. Then, at least, the border systemically means "clickable".

That said, this is probably a stopgap solution in the longer term, and many of these clickable labels should be replaced by Buttons, Dropdowns, etc.

**Comment by mistercrunch** [comment]
closing in favor of https://github.com/apache/incubator-superset/pull/11034

**Comment by mistercrunch** [comment]
Oh, reopening for things not covered in #11034

**Comment by mistercrunch** [comment]
@rusackas - rebased!

**Review by rusackas — APPROVED** [review]

**Pull request merged**
