### PR TITLE
refactor: Bootstrap to AntD - Slider

### PR DESCRIPTION
**Pull request by michael-s-molina**
### SUMMARY
- Migrates the `Slider` component from Bootstrap to AntD
- Creates a storybook entry for `Slider`
- Removes `ReactBootstrapSlider`

PS: No tests were added because we don't add any custom behavior to the component. Relying on AntD tests.

See: #10254

@mihir174 I didn't found the `Slider` component in the North Star specification so I used AntD default, which I think fits very well with our theme. Let me know if we need to change it.

@rusackas @junlincc @pkdotson 

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Screen Shot 2021-04-07 at 8 41 49 AM
Screen Shot 2021-04-07 at 8 58 19 AM
Screen Shot 2021-04-07 at 8 47 15 AM

### TEST PLAN
1 - Execute all tests
2 - All tests should pass
3 - Additional testing can be done using Storybook

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by junlincc** [comment]
@michael-s-molina this is awesome Michael! we are finally back on the migration.

**Comment by Steejay** [comment]
looks good to me. cc @mihir174

**Review by suddjian — CHANGES_REQUESTED** [review]
Nice! Good to see the migration continuing. We should probably remove the `BootstrapSliderWrapper` component as well.

**Comment by michael-s-molina** [comment]
> Nice! Good to see the migration continuing. We should probably remove the `BootstrapSliderWrapper` component as well.

Strange.. the PR's description is stating that I removed the file. Maybe I forgot to commit? Anyway, I'll delete it. Thanks for catching that @suddjian!

**Comment by michael-s-molina** [comment]
@suddjian I was reviewing the code and turns out that:

`BootstrapSliderWrapper/index.jsx` was renamed to `Slider/Slider.stories.tsx`
`BootstrapSliderWrapper.less` was renamed to `Slider/index.tsx`

So they were in fact deleted 😄

**Review by suddjian — APPROVED** [review]
Looks good!

**Review by pkdotson — APPROVED** [review]
LGTM!

**Pull request merged**
