### PR TITLE
fix(chart explorer): Chart does not cover the entire page with Standalone=1 #15252

### LINKED ISSUE #15252: Chart does not cover the entire page with Standalone=1
When Standalone=1 (or standalone=true) is passed in query string the chart does not fit the full page like used to do in the previous version.

### Expected results (Superset v. 0.37.2)
In this case the chart area is 1920 x 937 and fit the entire page:

image

### Actual results (Superset v. 1.1.0)
In this case the chart area is 1890 x 806 and does not fit the entire page:

image

#### Screenshots
In line with comments

#### How to reproduce the bug

1. Create and save a chart
2. Generate a link to view/share the chart
3. Get the chart id and point to standalone version: https://superset_v_1_1_0/superset/explore/?r=100&standalone=1
4. See that the chart will not fit the entire page

### Environment
- superset version: Superset 1.1.0
- python version: Python 3.8.9
- node.js version: -

### Checklist
- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context
--

### PR DESCRIPTION
**Pull request by nraschi**
fix(chart explorer): charts cover the entire page when Standalone flag is set

### SUMMARY

Added a check on the Standalone flag.
If the Standalone flag is set to true, then the chart dimensions are set to cover the entire page (without padding, used when in explore mode).

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

Before:
image
  
After:
image

### TESTING INSTRUCTIONS

1. Load a chart with Standalone flag set to true
2. The chart must cover the entire page (without padding)

### ADDITIONAL INFORMATION

- [x] Has associated issue: Fixes #15252
- [ ] Required feature flags:
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by nraschi** [comment]
Hi @villebro, I changed the pull request title, but the merging is blocked. Must I create a new pull request?

Thank you very much

**Comment by villebro** [comment]
@nraschi there's a conflict in the PR, so you need to rebase it to master. If you can do that I can review it and get it merged if all is well.

**Comment by nraschi** [comment]
> 

Hi @villebro, I'm trying to rebase, but unfortunately, I didn't create a branch on my fork and now I can't fetch the upstream to fix that conflict. 
Is there a way to resolve this? Like a new fork will maintain this PR?

Thank you very much

**Comment by nraschi** [comment]
Hi @villebro, I managed to rebase my fork and review the conflict. 
In this new version seem my contribution is not necessary anymore because the code that changes the chart dimension is not present.
I suppose the new version resolve #15252

Thank you

**Comment by villebro** [comment]
Thanks @nraschi - so I assume we can close this PR?

**Comment by villebro** [comment]
Closing as this appears to be redundant

**Comment by nraschi** [comment]
> Thanks @nraschi - so I assume we can close this PR?

Yep, as you've already done, thanks. This solution could be used in version 1.5.x, @villebro do you think is a good idea try to open a PR on that branch?

**Pull request closed without merging**
