### PR TITLE
[WIP] disable quotes for Kylin

### PR DESCRIPTION
**Pull request by villebro**
### CATEGORY

Choose one

- [x] Bug Fix
- [ ] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY
Apparently Kylin doesn't properly support quotes or non-alphanumeric characters in the aliases.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by mgulaydin** [comment]
The main problem here is because of the Apache Kylin's Pypi package kylinpy is sends initial quotes to the SQLAlchemy. But unfortunately, Kylin doesn't support any kind of quotes in the query that will render. To more clarify the problem, here is a basic scenario with screenshots.

**Comment by mgulaydin** [comment]
image

Here i can get success message that means my connection with Kylin is okay.

image


But Superset can not even preview the table.

image

Eventhough i can run my query successfully.

image

After i clicked to the "Explore" in Superset the problem comes back. Because query is looks like this;

`SELECT "WONUM" AS "WONUM",
       "WORKORDERID" AS "WORKORDERID"
FROM
  (SELECT *
   from x.FACT_TABLE_V1) AS expr_qry
LIMIT 1000;`

So i see the same error message in SQL Lab when rendering the query given above. But after removing the quotes and render the query in SQL Lab  seems problem is solving.

It's clearly seen here that Kylin can not render query with quotes. But kylinpy initially sends double quotes to the SQLAlchemy.

image

**Comment by mgulaydin** [comment]
I already tried to remove initial quotes from kylinpy but then restricted word and non alphanumerical character problem shows up. 

@villebro  I am able to test the solution. 

PS : My versions are goes like this;
**_Apache Kylin: 3.0.0
kylinpy: 2.4.1
Apache Superset: 0.35.2
Flask-SQLAlchemy: 2.4.0
SQLAlchemy: 1.3.6
SQLAlchemy-Utils: 0.34.1_**

**Comment by villebro** [comment]
Thanks for the additional context, @mgulaydin . Having given this some additional thought, I think the right place to tackle this is in `kylinpy`. If your case is representative of a typical Kylin installation, the connector should not be adding quotes that are not supported by the dialect. Therefore we should probably defer this discussion to the [kylinpy GitHub page](https://github.com/Kyligence/kylinpy). If there is any fine tuning that needs to take place in Superset, we can definitely accommodate for that in the Kylin spec. Feel free to tag me in issues/PRs in the kylinpy repo.

I'll close this WIP PR for now., but once the necessary changes have been made to `kylinpy`, we can open up a new PR if there are any outstanding changes that need to be made to the Kylin spec.

**Comment by zhaoyongjie** [comment]
hi, @mgulaydin @villebro  I am the maintainer of kylinpy. 

I have tested on Apache Kylin3.1, Kylin 2.6, and it seems that I can use the alias with quotes. Can you tell me the specific version of Kylin you are testing?

image

**Comment by mgulaydin** [comment]
hello @zhaoyongjie , i was using  **Apache kylin version 3.0.0**

**Pull request closed without merging**
