### PR TITLE
chore: skip SIP-68 shadow writing for LTS branches

### PR DESCRIPTION
**Pull request by ktmud**
### SUMMARY

Change [SIP-68](https://github.com/apache/superset/pull/17543) db migrations to no-op and stop shadow-writing datasets to new models.

We should not include the shadow writing logic to official releases as it increases computation costs yet contributes nothing to end user experience (for now). Given the original migration is expensive and we [likely need to redo it](https://github.com/apache/superset/pull/19421) anyway, it's the best to skip it for now.

This PR should only be cherry-picked into the LTS branches such as 1.5 and 2.0. Once #19421 is ready and the new dataset models started to replace the old models, we'll just re-cut the release from `master` and ignore this PR.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by ktmud** [comment]
CI failed but the base branch is showing the same error: https://github.com/apache/superset/runs/5886127859?check_suite_focus=true

I'll leave it as is.

**Comment by villebro** [comment]
> CI failed but the base branch is showing the same error: https://github.com/apache/superset/runs/5886127859?check_suite_focus=true
> 
> I'll leave it as is.

Ugh, I thought I fixed it, but maybe I forgot to commit the fix.

**Review by villebro — COMMENTED** [review]
LGTM (FYI I resolved the build errors on the 1.5 branch) - However, leaving to @betodealmeida to approve as he knows SIP-68 far better than me.

**Comment by villebro** [comment]
@ktmud this PR appears to have a few linting issues (the underlying branch is now green). We're ready to cut 1.5.0rc3 (there's two fixes in it), but going to wait to get this one in.

**Review by betodealmeida — APPROVED** [review]
This looks good. Thanks, @ktmud!

**Comment by ktmud** [comment]
> @ktmud this PR appears to have a few linting issues (the underlying branch is now green). We're ready to cut 1.5.0rc3 (there's two fixes in it), but going to wait to get this one in.

Let me fix those

**Comment by ktmud** [comment]
@villebro The helm chart failure seems to be related to Helm version updated to a new one in `master`. The base branch didn't trigger an error because the lint job only runs on pull requests. Should we create a new PR to fix it first?

**Comment by ktmud** [comment]
It seems the Helm Chart has the content as `master`. I'm not familiar with how Helm works and not sure whether I should bump the version in this branch. Maybe leave as it and just cherry-pick without merge?

**Comment by villebro** [comment]
> It seems the Helm Chart has the content as `master`. I'm not familiar with how Helm works and not sure whether I should bump the version in this branch. Maybe leave as it and just cherry-pick without merge?

This is really confusing. Sounds good, I'll just pick this in as-is 👍

**Comment by villebro** [comment]
Removed `v1.5` label to not confuse `cherrytree` when baking rc3.

**Comment by michael-s-molina** [comment]
@ktmud Can you check CI here? 2.0 is being assembled right now.

**Pull request closed without merging**
