### PR TITLE
Fix broken MultiLine chart

### PR DESCRIPTION
**Pull request by willbarrett**
### CATEGORY

Choose one

- [X] Bug Fix
- [ ] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY

The lines altered in this PR were introduced 8 days ago in this commit: https://github.com/apache/incubator-superset/commit/f0f4f7e91df0adc3a76292381f1ef6a8f579af95

These lines broke

 the Multi Line visualization, as that visualization has no `from_dttm` or `to_dttm` attributes. MultiLine visualizations on current master display the error `'MultiLineViz object has no attribute 'from_dttm'`.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

Before:
Screen Shot 2020-04-09 at 12 11 20 PM
After:
Screen Shot 2020-04-09 at 12 45 32 PM

### TEST PLAN

I've manually tested the change locally. You can verify the fix by navigating to:
Dashbaoards -> Misc Charts
and scrolling to the bottom where the "Multi Line" chart is displayed.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### REVIEWERS
@villebro @dpgaspar @ktmud

### CODE REVIEW

**Review by ktmud — APPROVED** [review]
LGTM. Thanks for the fix!

**Review by villebro — APPROVED** [review]
LGTM, thanks for fixing! 👍

**Review by dpgaspar — APPROVED** [review]

**Comment by willbarrett** [comment]
Travis has passed CI but the status wasn't reported to Github :(

**Comment by villebro** [comment]
Travis is currently almost doing more harm than good.

**Comment by willbarrett** [comment]
Agreed. We're going to try to support the Github Actions work next week.

**Comment by willbarrett** [comment]
OK, build passed again, still no status update from Travis. Does anyone have admin access to merge in this type of situation?

**Comment by villebro** [comment]
It seems once GH drops Travis like this, there's no coming back. It's not elegant I know, but I propose closing this and opening a new PR, as this is a pretty critical fix.

**Comment by willbarrett** [comment]
OK, closing + reopening.

**Pull request closed without merging**
