### PR TITLE
fix: year 54714 is out of range issue with async queries

### PR DESCRIPTION
**Pull request by hughhhh**
### SUMMARY

Reverting PR causing issues with async queries
Whenever a user enables async queries, all results are throwing the following error:
```
Traceback (most recent call last):
File "/Users/hugh/src/superset/venv/lib/python3.8/site-packages/celery/app/trace.py", line 451, in trace_task
R = retval = fun(args, **kwargs)
File "/Users/hugh/src/superset/superset/initialization/init.py", line 105, in call
return task_base.call(self, *args, *kwargs)
File "/Users/hugh/src/superset/venv/lib/python3.8/site-packages/celery/app/trace.py", line 734, in __protected_call__
return self.run(*args, **kwargs)
File "/Users/hugh/src/superset/superset/sql_lab.py", line 189, in get_sql_results
raise ex
File "/Users/hugh/src/superset/superset/sql_lab.py", line 178, in get_sql_results
return execute_sql_statements(
File "/Users/hugh/src/superset/superset/sql_lab.py", line 511, in execute_sql_statements
raise ex
File "/Users/hugh/src/superset/superset/sql_lab.py", line 499, in execute_sql_statements
result_set = execute_sql_statement(
File "/Users/hugh/src/superset/superset/sql_lab.py", line 237, in execute_sql_statement
start_dttm = datetime.fromtimestamp(query.start_time)
ValueError: year 54714 is out of range
```
Screen Shot 2022-09-29 at 1 45 13 PM

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by exherb** [comment]
why frontend change cause this issue?

**Comment by EugeneTorap** [comment]
@villebro The same story like in #21298 PR.
Without the desire to figure out what logic exactly causes this error, fix only this error and cover it with tests so that there are no problems with this in the future, we revert my PR?

**Review by zhaoyongjie — CHANGES_REQUESTED** [review]
Hi @hughhhh, you should check out the `query.star_time` from logging.

```
start_dttm = datetime.fromtimestamp(query.start_time)
ValueError: year 54714 is out of range
```

**Comment by hughhhh** [comment]
@EugeneTorap i spent the majority of the week trying to figure out the issue, and actually update the logic. With no luck I was hoping to revert this code since it's actually blocking all async queries execution then we can revisit the issue from your PR. 

The main thing is that master is broken because of this PR and is blocking our release of superset.

@exherb @zhaoyongjie for some reason with the conversion of the component the client is sending milliseconds instead of seconds, the weird thing is the code isn't touching anything with `startDttm`

**Comment by EugeneTorap** [comment]
@hughhhh give me 1-2 hours I'll investigate my PR

**Comment by EugeneTorap** [comment]
Guys. I can't reproduce the issue in master branch with async queries via redis & WS.

**Comment by EugeneTorap** [comment]
@hughhhh pls, provide all steps how to reproduce the issue.

**Comment by justinpark** [comment]
@hughhhh I found the root cause of this bug. Please see the PR #21667

cc: @EugeneTorap

**Comment by EugeneTorap** [comment]
This is great news, we don't need revert my PR!

**Pull request closed without merging**
