### PR TITLE
fix: homepage card layout

### PR DESCRIPTION
**Pull request by pkdotson**
### SUMMARY
This pr fixes the broken card layout for homepage and card size. Before the cards would not align correctly that was set by media query. 

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
before
https://user-images.githubusercontent.com/17326228/118894996-2a6ac400-b8ba-11eb-9bfe-5e057dd69ed5.mov

after

https://user-images.githubusercontent.com/17326228/118895431-052a8580-b8bb-11eb-9c98-9b4b048318bd.mov

### TEST PLAN
resize homepage screen to view correct layout

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by junlincc** [comment]
thanks for the PR, it will be nice if we can keep the menu and tab items on the same row for a bit longer :) but this is better already. ✅

**Review by junlincc — COMMENTED** [review]
<br class="Apple-interchange-newline">thanks for the PR, it will be nice if we can keep the menu and tab items on the same row for a bit longer :) but this is better already.&nbsp;✅

**Review by zhaoyongjie — APPROVED** [review]
LGTM, Thanks for the fix.

**Comment by michael-s-molina** [comment]
> thanks for the PR, it will be nice if we can keep the menu and tab items on the same row for a bit longer :) but this is better already. ✅

@junlincc https://github.com/apache/superset/pull/14689 fix the menu and tab items.

**Comment by michael-s-molina** [comment]
@pkdotson I noticed that the card title is being cut when resizing.

https://user-images.githubusercontent.com/70410625/119002146-feefe400-b962-11eb-9776-14c8b2328854.mov

**Comment by pkdotson** [comment]
> @pkdotson I noticed that the card title is being cut when resizing.
> 
>  screen-recording-2021-05-20-at-115442-am_KcY42A7p.mov

Yah we are working on a solution for this atm.

**Review by junlin-qa — APPROVED** [review]
@michael-s-molina thanks for pointing it out. i doubt user would resize the screen to that small in reality, we could truncate the title if needed, but probably not in this PR. 

let's merge @pkdotson

**Review by suddjian — APPROVED** [review]
LGTM

**Comment by junlincc** [comment]
https://user-images.githubusercontent.com/67837651/121076919-d56cf000-c78b-11eb-860e-b6b88b26330c.mov

just realized that the carets are gone on resize and the spacing is a bit off between charts and Dashboards. :( @michael-s-molina would you mind opening a PR later on? low priority

**Pull request merged**
