### PR TITLE
feat(explore): Add time shift color control to ECharts

### PR DESCRIPTION
**Pull request by rtexelm**
### SUMMARY

Adds a new checkbox control to timeseries capable charts allowing the user to choose whether or not to duplicate the original series colors for the shifts.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

https://github.com/user-attachments/assets/0df125af-3917-4a0e-b5c8-927357bbf3a4

### TESTING INSTRUCTIONS

1. Create a new chart using the Sales dataset.
2. Use `COUNT(*)` as your metric.
3. Set `order_date` as the X-Axis and a Month time grain.
4. Apply any time range filter that returns data.
5. Expand the time comparison and set 1 month ago.
6. Click on `CREATE CHART`.
7. Navigate to `Customize` tab
8. Click the `Time Shift color` checkbox

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by michael-s-molina** [comment]
The only concern that I have with this approach is about charts consumption at the dashboard layer. It might be confusing for users that time shifts are represented differently among charts which might harm UX. I'm not sure if we should discuss more about this as you can see in https://github.com/apache/superset/issues/26041

**Comment by michael-s-molina** [comment]
Another option is to assume that all time shifts will be of varied colors and remove the need for this checkbox. Essentially, not make the correlation between the series and its time shift using colors, only the legend.

**Comment by yousoph** [comment]
I'm not too concerned about the dashboard level - I'm guessing that there will be consistency at the org or creator level with this control based on preference so there aren't likely to be too many discrepancies at the dashboard level. 

In terms of defaulting to use varied colors, I'm not opposed to that but I thought the original fix in https://github.com/apache/superset/pull/24048 was to retain the same color for the time shift as the original control. Since that was the fix that was implemented, we thought adding a control would be the best way to give the flexibility to use either option.

**Review by Antonio-RiveroMartnez — APPROVED** [review]
LGTM, Thanks!

**Comment by rtexelm** [comment]
@fpassantino sorry for the delay.

**Pull request merged**
