### PR TITLE
feat(explore): Remove default for time range filter and Metrics

### PR DESCRIPTION
**Pull request by kgabryje**
### SUMMARY
Requires https://github.com/apache-superset/superset-ui/pull/1114

Changes default Time Range from "Last week" to "No filter"
Changes using "COUNT(*)" or other saved metric as a default metric to empty metrics control.

In the case of Table chart, removing default metric was a bit more complex. We use Groupby, Metrics and Percentage Metrics there, and at least one of them must have a value to construct a correct query. However, we can only write control validator that use values of its own control - for instance, we can't create a validator for groupby that checks if metrics or percentage_metrics are empty or not. We also couldn't simply mark all 3 controls as required, as only 1 is really required. The result was that upon creating a table chart, an incorrect request to backend was sent and we displayed an Empty query? error. It was quite a bad user experience - a strange error was the first thing that user sees after creating a chart (and what's more, we sent a query that we knew would fail).
For that reason, I created something like a "dynamic" validator - we check the state of groupby, metrics and percentage_metrics in mapStateToProps field of groupby in `superset-ui/plugins/plugin-chart-table/src/controlPanel.tsx`. If all of those fields are empty, we set an error in a new field externalValidationErrors. Since mapStateToProps function is run only when the field changes, we needed a way to trigger it when not only groupby, but also metrics or percentage_metrics fields change. To achieve that, I added a field rerender: ['groupby'] to metrics and percentage_metrics. It is later checked in superset/superset-frontend/src/explore/reducers - if rerender array exists, it triggers getControlStateFromControlConfig for each control in rerender array, which in turn triggers mapStateToProps of that control. Then, externalValidationErrors are merged with calculated validationErrors.
Checkout the video to see the result.

CC: @villebro @junlincc 

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
https://user-images.githubusercontent.com/15073128/118494563-94506580-b722-11eb-9015-845ff0cdb632.mov

Screenshot 2021-05-17 at 10 45 42

### TEST PLAN
Pull https://github.com/apache-superset/superset-ui/pull/1114, link superset-ui/chart-controls and superset-ui/plugin-chart-table (`npm link ../../../superset-ui/plugins/plugin-chart-table ../../../superset-ui/packages/superset-ui-chart-controls`). Then create some new charts and verify that metrics is empty by default and time range filter is set to "No filter". Create a table chart and verify that at least 1 of Groupby, Metrics and Percentage Metrics must have a value to send a query, otherwise a warning message should be displayed.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by villebro — COMMENTED** [review]
I already left a comment to this effect in https://github.com/apache-superset/superset-ui/pull/1114, but I think it would be nice if all three controls would turn red with all three are missing a value. I understand that this will create three error messages on the chart, but as a follow-up PR we could then group together identical error messages on one row by showing something like this:

> Controls labelled **Group by**, **Metrics**, **Percent Metrics**: Group by, Metrics or Percentage Metrics must have a value

instead of

> Controls labelled **Group by**: Group by, Metrics or Percentage Metrics must have a value
> Controls labelled  **Metrics**: Group by, Metrics or Percentage Metrics must have a value
> Controls labelled **Percent Metrics**: Group by, Metrics or Percentage Metrics must have a value

**Review by junlincc — COMMENTED** [review]
Product sign-off. ✅Thanks for making the change. We will have a follow up PR to improve the UI when user enter into Explore, showing a more user friendly msg to prompt metrics input, instead of a warning/error sign . 

cc @srinify @cccs-jc @EBoisseauSierra

**Review by villebro — APPROVED** [review]
LGTM; tested both with and without DnD feature flag, and verified that changing dataset/viz type didn't cause unexpected behavior on controls.

**Pull request merged**
