### PR TITLE
chore: Changes the dashboard properties modal to use the new select component

### PR DESCRIPTION
**Pull request by michael-s-molina**
### SUMMARY
Changes the dashboard properties modal to use the new select component.

@junlincc @jinghua-qa @rusackas 

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
https://user-images.githubusercontent.com/70410625/128198385-9ad06508-6c94-4bcf-967d-2af423c9d453.mov

https://user-images.githubusercontent.com/70410625/128198526-03bf236e-b8fd-4da5-a486-3a98d0238597.mov

### TESTING INSTRUCTIONS
Check the videos for instructions.

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by jinghua-qa — APPROVED** [review]
LGTM! I think the risk of change is low but can we wait to get this in after GA? @junlincc

https://user-images.githubusercontent.com/81597121/128246381-75ea9e1f-f21f-4c4a-9bc6-a9db04daa94f.mov

**Review by geido — APPROVED** [review]
LGTM!

**Review by pkdotson — APPROVED** [review]
LGTM!

**Pull request merged**
