### PR TITLE
fix: helm chart to use Bitnami chart

### PR DESCRIPTION
**Pull request by liamnv**
### SUMMARY
Because charts/stable is deprecated, we need to move dependencies to artifact hub, follow this README: https://github.com/helm/charts

### TEST PLAN
- Helm update dependencies
- Install chart

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by craig-rueda — APPROVED** [review]

**Comment by liamnv** [comment]
@craig-rueda could you please check CI ?

**Comment by craig-rueda** [comment]
@liamnv can you push an empty commit?

**Comment by liamnv** [comment]
@craig-rueda I have fix that, please check

**Comment by liamnv** [comment]
@craig-rueda  please merge

**Pull request merged**
