### PR TITLE
[WIP] style: inconsistent button styles in antD confirmation modal

### LINKED ISSUE #16775: [Explore] Inconsistent button styles in AntD confirmation modal
## Screenshot

Xnip2021-09-21_16-32-10

## Description

We should probably update the button styles in AntD's confirmation modal to be consistent with other parts of the page.

### PR DESCRIPTION
**Pull request by josephsawaya**
### SUMMARY

This PR changes the confirmation modal button styling to match the button styling in the datasource modal. It achieves this by hiding the default buttons in the confirmation modal and creating two buttons with the correct styling that make the function calls on click as the default buttons. Fixes: #16775

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

From the original issue:

With the changes in this PR applied:
image

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [X] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by rusackas** [comment]
I have to assume there are many other locations in Superset that are exhibiting this inconsistency if they Modal component itself isn't already styled this way.

In general, patching up a singular instantiation of something is more difficult to maintain, since the approach will be copied/pasted in numerous locations.

Have you tried taking the approach of modifying the Modal component (which is essentially a decorated version of the AntD modal, with a layer of Emotion styling) so that the correct styles can be added at the root, rather than overriding/bypassing things for a singular instance of the modal? 

CC @michael-s-molina @eric-briscoe @geido  in case either of them have looked at the Modal component lately.

**Comment by rusackas** [comment]
@josephsawaya let me know if my comments make sense, and if we can help further. If you happen to join the [Slack](https://join.slack.com/t/apache-superset/shared_invite/zt-1jp6hjzrq-H0PlFtToyLWuPiJDuRWCNw) workgroup, we can certainly chat there, too!

**Comment by rusackas** [comment]
cc @eric-briscoe regarding getting to the root of the inconsistency in the design system.

**Comment by michael-s-molina** [comment]
@rusackas @josephsawaya I recently merged a PR that [changes the style of Modal's pre-defined functions](https://github.com/apache/superset/pull/22737). I think we close this PR given that `confirm` will use the new style definitions.

**Comment by josephsawaya** [comment]
Sorry, I got caught up with exams after making this PR. 

> @rusackas @josephsawaya I recently merged a PR that [changes the style of Modal's pre-defined functions](https://github.com/apache/superset/pull/22737). I think we can close this PR given that `confirm` will use the new style definitions.

Based on the above I can close the PR.

**Pull request closed without merging**
