### PR TITLE
Allow 'refresh_immune_slices'

### PR DESCRIPTION
**Pull request by ratb3rt**
Ref #2958 , add a 'refresh_immune_slices' property to dashboards. Any slice ids listed will not be included in an automatic dashboard refresh.
I chose to exclude rather than include to be consist with filter_immune_slices.

### CODE REVIEW

**Review by mistercrunch — CHANGES_REQUESTED** [review]
LGTM in general except that the setting name is not specific enough, and you should add an entry in the `docs/faq.rst`

**Comment by mistercrunch** [comment]
Also you can make sure you pass the build before sending in the PR by setting up travis-ci against your fork. It's really easy to setup and will run a build for each new push on your repo.

**Review by ratb3rt — COMMENTED** [review]
Updated to 'timed_refresh_immune_slices' in latest commit, added usage to faq.rst

**Comment by RichRadics** [comment]
Any additional reviews on this PR? (Apart from `don't merge master into your dev branch like that in future` :) )

**Pull request merged**
