### PR TITLE
docs: update README.MD and FAQ Page for Superset 1.0 launch

### PR DESCRIPTION
**Pull request by srinify**
### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

In preparation for Superset 1.0 launch next Tuesday, lets update the visuals in the repo! Swapped out screenshots

geospatial_dash
explore_visualizations
sql_lab
slice_and_dice
slack_dash

### TEST PLAN

- Look for any inaccuracies, spelling / grammar issues, etc.
- Test images & GIF's rendering in Github

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by etr2460 — COMMENTED** [review]
instead of pngs can you attach jpgs here? There should be no need to 5MB image files in the README, so let's reduce the size to a reasonable amount (otherwise it'll take forever to load the page)

**Comment by srinify** [comment]
> instead of pngs can you attach jpgs here? There should be no need to 5MB image files in the README, so let's reduce the size to a reasonable amount (otherwise it'll take forever to load the page)

Good point, I'll compress to JPG. Not much we can do about the GIF though, should I just remove it?

**Comment by junlincc** [comment]
Hey Srini, thanks for updating the doc! Could you replace Explore screenshot with the latest below? Lots of changes have taken place lately, thanks! @srinify 

Screen Shot 2021-01-13 at 1 23 48 PM

**Comment by garden-of-delete** [comment]
Can we change the Release Notes link in README.md to point to RELEASING/README.md, then add a section near the top where we can add links to the release notes for major releases?

**Comment by junlincc** [comment]
@srinify i would like to include it for 1.0 release wdyt?

**Review by rusackas — APPROVED** [review]
LGTM

_edit: Things looked OK to me, but I see others have comments that may not be adressed... hope I didn't ruffle any feathers there_

**Comment by srinify** [comment]
@rusackas thanks for approving Evan! I'll implement Junlin's / Robert's changes and then we can merge! And resolve the merge conflict

**Review by villebro — APPROVED** [review]

**Pull request merged**
