### PR TITLE
style: Change logo color to new branding

### PR DESCRIPTION
**Pull request by willbarrett**
### SUMMARY
Updates the color of the Superset logo to match the new branding primary color from Cartel

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
See images in diff

### TEST PLAN
View images - are they ok?

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### Reviewers
@mistercrunch @rusackas

### CODE REVIEW

**Comment by nytai** [comment]
@willbarrett some of the png files seem significantly smaller, did they get exported in a scaled down form?

**Comment by willbarrett** [comment]
hmmm....yeah, looks like the dimensions are off a bit. Updating shortly...

**Comment by rusackas** [comment]
Files look about right... but they're not in use anywhere :)

**Comment by willbarrett** [comment]
Yup. This is press kit stuff.

**Comment by mistercrunch** [comment]
From here it's easy to alter/copy to `images/` and elsewhere

**Review by mistercrunch — APPROVED** [review]

**Pull request merged**
