### PR TITLE
feat: Adding AWS S3 as notification method options for Alerts/Reports

### PR DESCRIPTION
**Pull request by Ralkion**
# SUMMARY
We are adding the implementation and usage of the AWS S3 upload feature in Apache Superset. This feature allows users to send reports directly to an AWS S3 bucket, and is configured to be an additional delivery option (like email & slack).

When writing files to S3 buckets, there are three methods available for authentication:
1. Taking credentials from the user in the frontend (via a modal) per report
2. Taking credentials from the superset_config.py file
3. Utilizing an AWS IAM role associated with the ECS/EC2 role

Methods 1 & 2 require an AWS IAM User, while method 3 makes use of the executing IAM Role for the running system.

# TESTING INSTRUCTIONS
### Pre-requisites
* Ensure Superset is installed and running.
* Create an AWS IAM User and an access key / secret key for that user.
* Create an S3 bucket with a bucket policy that grants access to the user above, and an aws role of your choice.

##### Enable the feature
User should update the superset_config.py (docker/pythonpath_dev/superset_config.py) file with following:

Ensure that the reports feature is enabled, and enable the feature with the `FEATURE_FLAGS` in superset_config.py.
```
FEATURE_FLAGS["ALERT_REPORTS"] = True
FEATURE_FLAGS["ENABLE_AWS"] = True
ALERT_REPORTS_NOTIFICATION_DRY_RUN = False
```

Note: If the User doesn’t enable the feature flag of ENABLE_AWS, but has ALERT_REPORTS set to True then alerts & reports will still work as per normal (Email & Slack delivery options). The AWS S3 option will be unavailable.

Once enabled, when creating a report, the user will be able to deploy the result to an S3 bucket. They will be able to specify where/how the file should be written through the web interface.

delivery_options
authorization_methods

##### Method 1: Frontend User Credentials
Using this method allows each report to be delivered to different buckets, and to use a different set of credentials. In our use case, this was important as we may be delivering reports directly to different customer S3 buckets.

When accessing the feature in the frontend, users will be prompted to enter their AWS credentials through the existing modal. Users can provide their IAM User's Access Key and the Secret Access Key into the user interface itself. When generating the report, these values will be used to write the file to S3.

input_credentials

##### Method 2: Taking credentials from the superset_config.py file
The report may instead be configured to use a default set of credentials as specified in the config file. This use case allows for a more streamlined method for sending reports, always using the same credentials. This can be used primarily when a company is delivering reports to their own S3 bucket, and could be done with an on-premise setup.

Add the following code in superset_config.py.
```
# AWS Credentials
AWS_ACCESS_KEY = '####'
AWS_SECRET_KEY = '####'
```

config_credentials

##### Method 3: AWS IAM Role
Finally, the report may instead be configured to use the running system's IAM role. This use case follows AWS best practices in granting access to a resource through a role instead of directly through a user. Similar to method 2, this method will always use the same credentials - but this is no longer changeable through the config file. Although this method would most commonly be used by services running in AWS (EC2 or ECS), it could also be run by properly configuring the AWS CLI (which I will not get into here).

role_credentials

### Usage
Once setup has been done, the AWS S3 option can be used for sending reports/alert directly to the S3 bucket from either the settings menu, or when editing a dashboard or chart.

#### Navigate to settings, then on Alerts & Reports.
When creating a report directly, one can choose to deploy the report to an S3 bucket, and may also choose which authentication method they would like to use when delivering the report.
* Create a new report
* In the Notification Method select S3.
* Then select one of the available S3 method options: AWS_S3_credentials, AWS_S3_pyconfig, or AWS_S3_IAM.
* Provide the bucket name to which the report will be delivered.
* if using AWS_S3_credentials, then fill in the required aws credentials.

list

#### From the dashboard / chart
All three S3 method options are available when viewing a dashboard or chart page.
* Create a new dashboard or chart, or view an existing one
* Using the dashboard or chart's menu, select Set up a S3 report and use any of the S3 method options available.
* Observe that the dashboard or chart's report can be seen in the Alerts & Reports page.

start_from_chart
modal_from_chart

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [x] Required feature flags: `ALERT_REPORTS`, (new) `ENABLE_AWS`
- [x] Changes UI
- [x] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [x] Migration is atomic, supports rollback & is backwards-compatible
  - [x] Confirm DB migration upgrade and downgrade tested
  - [x] Runtime estimates and downtime expectations provided
- [x] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by Ralkion** [comment]
This is a re-do of https://github.com/apache/superset/pull/27506.

I'm taking over the work for that PR and as such I had to re-home it to my own repository.

**Comment by Ralkion** [comment]
It looks like there's a few commits from 2.1.0 that are getting re-applied here. I'm not sure I follow why that's happened but I'll look into it. The question I have for the community here -> do we know if they were intentionally *not* part of master or was that a miss?

**Comment by Ralkion** [comment]
Second question I had: We have an svg created with this PR (superset-frontend/assets/images/icons/s3.svg). I wasn't sure on the license for this particular icon. It's currently used in the reports list to show delivery options. Does apache have an icon they would prefer for this?

**Comment by Ralkion** [comment]
My last comment for the opening of this PR: I haven't done the translation process for the new strings. I was afraid they might make the PR too large, so I can do those up when this PR is accepted.

**Comment by eschutho** [comment]
HI @Ralkion, this looks like a great feature. Thank you for the contribution! It looks like you have some extra commits in here from another branch. Can you try rebasing your branch from master and see if it removes them?

**Comment by Ralkion** [comment]
Sure thing @eschutho . It's gonna take me a little bit of time to do though. Hopefully I'll be able to finish the rebase with all its conflicts in 1-2 days.

**Comment by rusackas** [comment]
Thank you @NeHaSinghTeqfocus for providing the foundational direction on the original PR!!!

**Comment by Ralkion** [comment]
Okay, I've completed the rebase. Took longer than I had hoped.

There does seem to be a bug where creating an Email report from the dashboard/chart view will overwrite the previous S3 report for that dashboard/chart. The reverse is also true when creating an S3 report overwriting the Email report.

I'll leave this in draft for now as I imagine there's still more work to do to get this up-to-date.

**Comment by rusackas** [comment]
Closing this since it hasn't been touched in about 9 months, but happy to reopen it if you ever want to revisit/update it, @Ralkion!

**Comment by Ralkion** [comment]
No worries @rusackas , entirely reasonable.

I'm sorry I haven't had a chance to come back to this, it simply became unfeasible to fit it into my schedule. But hopefully the [webhook approach](https://github.com/apache/superset/discussions/29928) would allow for a much wider range of alerts/reports.

**Pull request closed without merging**
