### PR TITLE
chore(ci): change code owners for .github

### PR DESCRIPTION
**Pull request by dpgaspar**
### SUMMARY
Adding myself to .github, mainly because of github workflows and SECURITY.md

Also removing ephemeral env owners since it does not make sense anymore and simplifies the config

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by craig-rueda — APPROVED** [review]

**Comment by michael-s-molina** [comment]
@dpgaspar I was not able to see the change related to adding yourself as a `.github` owner. Did you forget to commit something?

**Comment by dpgaspar** [comment]
> @dpgaspar I was not able to see the change related to adding yourself as a `.github` owner. Did you forget to commit something?

I did... fixed now

**Review by michael-s-molina — APPROVED** [review]
LGTM

**Review by mistercrunch — APPROVED** [review]
LGTM. Note that we could use GitHub groups here for something more dynamic if we wanted, but would have to be managed in the `apache-superset` org, and wouldn't be in source control. This is ok for now I think.

**Review by rusackas — APPROVED** [review]

**Pull request merged**
