### PR TITLE
feat(viz): implement time picker on filter box

### PR DESCRIPTION
**Pull request by zhaoyongjie**
### SUMMARY

- move `utils.ts` and `constants.ts` to `DateFilterControl.utils`
- rename `DateFilterControl.frame` to `DateFilterControl.components`
- remove original `DateFilterControl`
- implement time picker on filter box

### TEST PLAN

changed files/packages structure only. 

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [x] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [x] Removes existing feature or API

### CODE REVIEW

**Review by villebro — COMMENTED** [review]
Here's FilterBox with the old component:
image
Here with the new one (probably needs a slight CSS tweak):
image
Also, should we just remove the old `LegacyDateFilterControl`, as I don't think it's really needed anymore after this?

**Comment by zhaoyongjie** [comment]
> Here's FilterBox with the old component:
> image
> Here with the new one (probably needs a slight CSS tweak):
> image
> Also, should we just remove the old `LegacyDateFilterControl`, as I don't think it's really needed anymore after this?

OH, thanks Ville, good catch. I will check this issue. 

I very much agree to remove the old components, but I am afraid whether there are other companies that still rely on the original components.

**Comment by villebro** [comment]
> I very much agree to remove the old components, but I am afraid whether there are other companies that still rely on the original components.

I think it's ok to remove it, as I feel we've made a collective decision to replace the old time picker with the new one. Anyway, if someone really needs it they can go to a previous SHA and get the code from there 🙂

**Comment by zhaoyongjie** [comment]
> > I very much agree to remove the old components, but I am afraid whether there are other companies that still rely on the original components.
> 
> I think it's ok to remove it, as I feel we've made a collective decision to replace the old time picker with the new one. Anyway, if someone really needs it they can go to a previous SHA and get the code from there 🙂

OK. I remove these legacy codes in this PR.

**Comment by zhaoyongjie** [comment]
@villebro fixed the style issue. 

image

**Review by villebro — APPROVED** [review]
LGTM! Btw, I'd change the title to `feat(viz): implement time picker on filter box` or something similar, as this is more a new feature for filter box than just a refactor.

**Comment by zhaoyongjie** [comment]
Thank you @villebro. 
I totally agree with your suggestion

**Pull request merged**
