### PR TITLE
fix: SQL Lab autocomplete for selected tables

### PR DESCRIPTION
**Pull request by hughhhh**
### SUMMARY

Updated logic to fix the autocomplete render in sqllab for selected tables in the left panel

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

https://user-images.githubusercontent.com/27827808/157082183-7552c13f-a406-41a9-b19e-e7d2137491e3.mov

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by lyndsiWilliams — APPROVED** [review]

**Review by eschutho — APPROVED** [review]

**Comment by jinghua-qa** [comment]
Verified that when user have selected tables in the left panel, autocomplete work for table name in SQL editor.

**Review by jinghua-qa — APPROVED** [review]
QA tested passed. Verified autocomplete worked for table name when user have selected table in left panel

**Pull request merged**
