### PR TITLE
fix: Revert "feat: Adds the Featured Charts dashboard (#28789)"

### PR DESCRIPTION
**Pull request by sadpandajoe**
This reverts commit 95706d9be2b5414ed496ad762ba1996041429e01.

### SUMMARY
Noticed that ephemerals don't have any example data. This reverts the PR that could have caused this in case if we don't find a fix forward before we finish with 4.1

### TESTING INSTRUCTIONS

In the PR, bring up an ephemeral and verify that examples now show up.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by rusackas** [comment]
Taking this out of draft state to see if it helps CI pass. If it does (or at least if it gets far enough) I'll spin up an ephemeral to make sure it works as expected :)

**Comment by rusackas** [comment]
Hmm... the epehemeral still doesn't have examples. Maybe this PR isn't the root cause?

**Comment by sadpandajoe** [comment]
> Hmm... the epehemeral still doesn't have examples. Maybe this PR isn't the root cause?

hmm weird. @eschutho were there any other changes from that and the 4.1 branch?

**Comment by eschutho** [comment]
> hmm weird. @eschutho were there any other changes from that and the 4.1 branch?
Oh strange. That was the one that I reverted from 4.1, but let me see what else might have changed.

**Pull request closed without merging**
