### PR TITLE
Add dotenv to dependencies

### PR DESCRIPTION
**Pull request by mistercrunch**
### CATEGORY

Choose one

- [x] Enhancement (new features, refinement)

### SUMMARY
This lib is optional but helpful, let's add it to setup.py

### CODE REVIEW

**Comment by john-bodley** [comment]
@mistercrunch could you provide more context as to how/where this will be used. Additionally you mention the package is optional and there's been a tendency to remove optional (configuration dependent) packages per [here](https://github.com/apache/incubator-superset/blob/master/UPDATING.md#superset-0310).

**Comment by mistercrunch** [comment]
This just enables `.flaskenv` to get picked up, without install `requirements-dev.txt`. It makes setting up the environment a tiny bit easier.

**Comment by john-bodley** [comment]
@mistercrunch sorry I wasn't aware of the `.flaskenv` file. What was the reason for migrating away from `superset run` towards using `flask run` (per the [CONTRIBUTING.md](https://github.com/apache/incubator-superset/blob/master/CONTRIBUTING.md#flask-server) file)?

**Comment by mistercrunch** [comment]
It was somewhat necessary for the Flask 1.0 upgrade if I remember well. Something around using `flask run` CLI over the `app.run` method. It seemed to fit the pattern we had before with `gunicorn`.

It's better for us to use the rich `flask run` command that is rich and has lots of options instead of maintaining our own equivalent.

**Comment by john-bodley** [comment]
@mistercrunch apologies for the delay in responding. I recently upgraded some other Flask apps to Flask 1.0 and was exposed to the newer way of configuring/running applications. 

I agree that including the dependency for `python-dotenv` makes sense however I was wondering whether this should be included in `requirements-dev.txt` rather than `requirements.txt` as i) one actually doesn't require this to run Superset, and ii) I was wondering whether there was a concern that in production any CLI calls, i.e., `superset db upgrade` would be run using the `FLASK_ENV='development'` environment per [here](https://github.com/pallets/flask/blob/1dda032b00cb4f7a783e018a7c370ee88f15e797/flask/cli.py#L34) which reads the `.flaskenv` if the `dotenv` package is present. 


Also in your PR in the [CONTRIBUTING.md](https://github.com/apache/incubator-superset/blob/master/CONTRIBUTING.md#flask-server) by including this package, I believe
```
cd superset
FLASK_ENV=development flask run -p 8088 --with-threads --reload --debugger
```

now simplifies to, 
```
flask run -p 8088 --with-threads
```

**Comment by mistercrunch** [comment]
Right, all this is assuming you're firing up the command from inside the repo too. I don't think `flask run` makes sense for production anyways, people should really gunicorn or nginx which from my understanding wouldn't be affected by this.

**Comment by john-bodley** [comment]
@mistercrunch people will still be using the CLI commands in production, i.e., we run `superset db upgrade`, `superset init`, etc. as part of every production deploy which would inherit the `.flaskenv` environment.

**Pull request merged**
