### PR TITLE
fix(plugin-chart-echarts): use scale for truncating x-axis

### LINKED ISSUE #26254: Bar chart spilling out past x-axis on both ends
Superset 3.1.0rc2:

image

How it looks previously in 3.0.0:

image

Here's the chart config in 3.1.0rc2: 

image

Again there's a numeric x-axis, maybe broken by #26215 ?

### PR DESCRIPTION
**Pull request by villebro**
### SUMMARY
Following up on #26215 by playing whack-a-mole on the numerical x-axis truncation problem. Move from using `dataMin`/`dataMax` to `scale: true` when truncating x-axis for bar charts. This applies automatic truncation by ECharts, which is able to handle truncation more gracefully. For other than bar charts, we'll retain the `dataMin`/`dataMax` logic without the `scale` parameter.

### AFTER
Now there is a proper margin on the x-axis to not overlap y-axis.
image

Now also mixed series chart has the same functionality:
image

### BEFORE
Previously the smallest and largest bars would 
image

### ADDITIONAL INFORMATION

- [c] Has associated issue: fixes #26254
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by michael-s-molina — CHANGES_REQUESTED** [review]
You need to pass `seriesType` from `transformProps`.

**Comment by villebro** [comment]
> You need to pass `seriesType` from `transformProps`.

Thanks for catching, too many iterations on how to implement this caused the final commit to miss this change..

**Comment by michael-s-molina** [comment]
You also need to adjust the mixed timeseries chart 🙂

**Comment by villebro** [comment]
> You also need to adjust the mixed timeseries chart 🙂

😬

**Review by michael-s-molina — APPROVED** [review]
LGTM

**Pull request merged**
