### PR TITLE
bumping versions of JS packages to latest

### PR DESCRIPTION
**Pull request by mistercrunch**

### CODE REVIEW

**Comment by toabey** [comment]
Updating mapbox-gl-js to 0.26.0 result in this error. Looks like webworkify-webpack has to be updated.

mapboxgl-update

**Comment by mistercrunch** [comment]
Oh interesting, I didn't hit that. What's your node and npm version?

**Comment by toabey** [comment]
node -> 6.3.1
npm -> 3.10.3

**Comment by mistercrunch** [comment]
Ok, I'll just bump the other libs for now since I can't reproduce the bug. @toabey

**Comment by toabey** [comment]
I am so sorry.  It's working fine with 0.26.0.

I imported mapbox-gl inside mapbox.jsx for adding some mapbox controls. That import made the problem.

https://github.com/mapbox/mapbox-gl-js/issues/3291

**Comment by danialgood** [comment]
Still having this problem
map-gl@0.26.0
react-map-gl@1.7.1

npm 3.10.8
node 6.9.1

**Pull request merged**
