### PR TITLE
fix(ci): lint issue on update-monorepo-lockfiles.yml

### PR DESCRIPTION
**Pull request by dpgaspar**
### SUMMARY
Fixes lint issue on `update-monorepo-lockfiles.yml`, impacts open PRs

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by geido — APPROVED** [review]

**Comment by michael-s-molina** [comment]
@dpgaspar All other workflow files have an empty line at the end. The formatter also adds an empty line automatically.

**Comment by michael-s-molina** [comment]
> @dpgaspar All other workflow files have an empty line at the end. The formatter also adds an empty line automatically.

It looks like committed files don't have that line. LGTM.

**Review by michael-s-molina — APPROVED** [review]

**Comment by mistercrunch** [comment]
Do we not re-run `pre-commit` on CI?

**Comment by mistercrunch** [comment]
Oh @rusackas it's because of this -> https://github.com/apache/superset/blob/master/.github/workflows/superset-python-misc.yml#L10-L13, maybe we should run pre-commit across the board, it's pretty cheap anyways, and many checks are not python-specific anymore

**Comment by mistercrunch** [comment]
Preventing this here -> https://github.com/apache/superset/pull/26942

**Pull request merged**
