### PR TITLE
fix: default toast position

### PR DESCRIPTION
**Pull request by suddjian**
### SUMMARY

a typo

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by rusackas — APPROVED** [review]
LGTM! Thanks for fixing

**Comment by rusackas** [comment]
Before:
image

After:
image

**Review by villebro — APPROVED** [review]

**Comment by villebro** [comment]
Tagging PR with the regression: #19144

**Comment by sadpandajoe** [comment]
🏷️  preset:2022.11

**Pull request merged**
