### PR TITLE
fix: Revert "fix: RBAC hide right menu (#16902)"

### PR DESCRIPTION
**Pull request by eschutho**
This reverts commit 87baac7650bdb6a8f8f82cf4992567a2c5c73cba.

We were seeing some bugs on master where SQL Lab wouldn't load with a production build with this error: 
Superset

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
production build after revert: 

Superset

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by hughhhh — APPROVED** [review]

**Review by etr2460 — APPROVED** [review]
looks like this fixes it. we'll need to figure out why next

**Review by rosemarie-chiu — APPROVED** [review]

**Comment by eschutho** [comment]
There was a test that was failing and seems to be failing on master as well, although it passes locally. Trying to fix that and then will merge this.

**Comment by eschutho** [comment]
@lyndsiWilliams I also reverted one of your test changes.

**Comment by rosemarie-chiu** [comment]
🏷 2021.40

**Pull request merged**
