### PR TITLE
Add basic Bar+Line chart support

### PR DESCRIPTION
**Pull request by x4base**
Add basic bar + line chart like this: http://nvd3.org/examples/linePlusBar.html
The first metric will be displayed as bars and the rest will be lines
Still has this problem: https://github.com/novus/nvd3/issues/290

### CODE REVIEW

**Comment by ascott** [comment]
this looks pretty good @x4base. thanks! could you add some screenshots?

**Comment by ascott** [comment]
i pulled this branch down and i'm getting a js error, also looks like we need to add .png for the vis thumbnail.

screenshot 2016-07-20 16 56 13

- would be great to write a test for the `NVD3TimeSeriesBarPlusLineViz` method
- i think it would make sense to move this chart up with the other time series charts in the menu list.

**Comment by x4base** [comment]
I updated it. But I can't find any example of tests of other visualizations.
Can we merge this first and later on when you have the the example of tests on other visualizations, I add the test accordingly.

**Comment by mistercrunch** [comment]
The javascript build failed probably because of lint. Run `npm run lint` to get the error locally.

**Comment by x4base** [comment]
I think I fixed the problem. It was the comma-dangle problem, but it wasn't reported on my system.

**Comment by mistercrunch** [comment]
Closing old PRs that need rebase. Rebase and resubmit if you're still pursuing this

**Pull request closed without merging**
