### PR TITLE
chore: Improve Korean translation

### PR DESCRIPTION
**Pull request by kimsehwan96**
### SUMMARY

Improve Korean translation.
Fix some wrong translation and add more translation.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [x] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by etr2460 — APPROVED** [review]
I don't speak Korean, but this generally looks good. I don't know if anyone in the community speaks Korean, if not I'll merge

**Comment by etr2460** [comment]
And thanks for the contribution!

**Comment by kimsehwan96** [comment]
@etr2460 Thank you for your review!

I'll translate more things when I have time.  😄

Thank you again!

**Comment by DPS0340** [comment]
I'm using korean as main language, and this PR looks pretty cool!

**Comment by willbarrett** [comment]
Code LGTM

**Pull request merged**
