### PR TITLE
fix: Update db2.py

### PR DESCRIPTION
**Pull request by sorieux**
In the documentation, the SQLAlchemy URI prefix to connect Superset to the DB2 database is : `db2+ibm_db://`

However, the `make_url` SQLAlchemy function call, returns a 'string' before the  '+' char (e.g. https://github.com/apache/incubator-superset/blob/master/superset/models/core.py#L225). 

Therefore, and in order to load the Db2EngineSpec class,  the value of the 'engine' variable in `Db2EngineSpec`, must be 'db2' instead of 'ibm_db_sa'.

This modification would fix an old issue (Apache superset - Error retrive db2 table information #5063).

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by villebro** [comment]
@sorieux please rebase, CI rules were recently changed.

**Comment by sorieux** [comment]
> @sorieux please rebase, CI rules were recently changed.

ok, it's done

**Comment by mistercrunch** [comment]
Can this PR break anyone's environment?

**Comment by villebro** [comment]
@sorieux I googled this, and I can't find a `db2` dialect, only references to `ibm_db_sa` ( https://pypi.org/project/ibm-db-sa/ ). What driver are you using to connect to your db2 instance with?

**Comment by sorieux** [comment]
> @sorieux I googled this, and I can't find a `db2` dialect, only references to `ibm_db_sa` ( https://pypi.org/project/ibm-db-sa/ ). What driver are you using to connect to your db2 instance with?

I am using the ibm_db_sa driver. In Superset UX, I configured the SQLAlchemy URI prefix the following `db2+ibm_db://`.

To instantiate, Db2EngineSpec Superst seems to use this URI, and calls a `make_url ` SQLAlchemy function (e.g. https://github.com/apache/incubator-superset/blob/master/superset/models/core.py#L225). 

The problem is that to instantiate the right class, the return from `make_url` (here DB2) is compared with the engine variable (ibm_db_sa). The specialized class is therefore not instantiated.

**Comment by sorieux** [comment]
> Can this PR break anyone's environment? If so we should mention it in `UPDATING.md`
The impact of RA is limited to the connection to DB2.

**Comment by villebro** [comment]
This is confusing. I agree that the dialect appears to be `db2` based on the connection string, but the dialect name is `ibm_db_sa` based on the source code: https://github.com/ibmdb/python-ibmdbsa/blob/765c90d9d078ad8842c72d963910e3f41978b70e/ibm_db_sa/ibm_db_sa/base.py#L653

Perhaps there's two dialects for db2? If that's the case we change the dialect of `Db2EngineSpec` to `db2`, and add a new `IbmDbSa` like so:

```python
class IbmDbSaEngineSpec(Db2EngineSpec):
    engine = "ibm_db_sa"
```

Then we wouldn't need to break anything if `ibm_db_sa` is indeed a valid dialect.

**Comment by sorieux** [comment]
> This is confusing. I agree that the dialect appears to be `db2` based on the connection string, but the dialect name is `ibm_db_sa` based on the source code: https://github.com/ibmdb/python-ibmdbsa/blob/765c90d9d078ad8842c72d963910e3f41978b70e/ibm_db_sa/ibm_db_sa/base.py#L653
> 
> Perhaps there's two dialects for db2? If that's the case we change the dialect of `Db2EngineSpec` to `db2`, and add a new `IbmDbSa` like so:
> 
> ```python
> class IbmDbSaEngineSpec(Db2EngineSpec):
>     engine = "ibm_db_sa"
> ```
> 
> Then we wouldn't need to break anything if `ibm_db_sa` is indeed a valid dialect.



> This is confusing. I agree that the dialect appears to be `db2` based on the connection string, but the dialect name is `ibm_db_sa` based on the source code: https://github.com/ibmdb/python-ibmdbsa/blob/765c90d9d078ad8842c72d963910e3f41978b70e/ibm_db_sa/ibm_db_sa/base.py#L653
> 
> Perhaps there's two dialects for db2? If that's the case we change the dialect of `Db2EngineSpec` to `db2`, and add a new `IbmDbSa` like so:
> 
> ```python
> class IbmDbSaEngineSpec(Db2EngineSpec):
>     engine = "ibm_db_sa"
> ```
> 
> Then we wouldn't need to break anything if `ibm_db_sa` is indeed a valid dialect.



> This is confusing. I agree that the dialect appears to be `db2` based on the connection string, but the dialect name is `ibm_db_sa` based on the source code: https://github.com/ibmdb/python-ibmdbsa/blob/765c90d9d078ad8842c72d963910e3f41978b70e/ibm_db_sa/ibm_db_sa/base.py#L653
> 
> Perhaps there's two dialects for db2? If that's the case we change the dialect of `Db2EngineSpec` to `db2`, and add a new `IbmDbSa` like so:
> 
> ```python
> class IbmDbSaEngineSpec(Db2EngineSpec):
>     engine = "ibm_db_sa"
> ```
> 
> Then we wouldn't need to break anything if `ibm_db_sa` is indeed a valid dialect.

Ok, I understood my mistake.

In the Superset documentation, the SQLAlchemy URI prefix is `db2+ibm_db`. But when Superset call sqlalchemy function `get_backend_name` with this string, the return is "DB2". Below, the `get_backend_name` source code (https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/engine/url.py#L140).



```python
def get_backend_name(self):
        if "+" not in self.drivername:
            return self.drivername
        else:
            return self.drivername.split("+")[0]
```

I try this the SQLAlchemy URI prefix : `ibm_db_sa` . It's working !

I can revert my update and edit the documentation with the right URI. How does this sound to you ?

**Pull request closed without merging**
