### PR TITLE
Change 'timestamp' to '_timestamp_' for Apache Kylin compatibility

### PR DESCRIPTION
**Pull request by lucky2you**
The query is failed when make Apache Kylin as the datasource. The 'timestamp' is a key word in Kylin SQL. So the query "select xxx as timestamp ..." failed. Change 'timestamp' to '_timestamp_' to avoid that.

### CODE REVIEW

**Comment by rocky1001** [comment]
Hi may be you can try the Caravel-Kylin branch (based on Caravel 0.8.9):
https://github.com/rocky1001/caravel/tree/caravel-kylin
which solved most problems when integrated with Kylin.

**Comment by mrbungie** [comment]
We're trying to connect to a Teradata MPP and we're having the same problem, since 'timestamp' is a reserved keyword. +1

**Comment by lucky2you** [comment]
@rocky1001  thanks , it helps a lot! Would you commit your changes to the official repository?

**Comment by rocky1001** [comment]
@lucky2you If you reviewed the adapter-code in the caravel-kylin branch, you can see the solutions right now is not that good. I'd like to move all the adapter-code to ORM level( in Pykylin ), but really lack of time to finish this.

**Comment by mistercrunch** [comment]
This LGTM, I just need to test it against our production DB and make sure all is right.

**Comment by mistercrunch** [comment]
Superseded by https://github.com/airbnb/superset/pull/1590/files

**Pull request closed without merging**
