### PR TITLE
fix(translations): some fix or add for Scheduler translation

### PR DESCRIPTION
**Pull request by xavier-GitHub76**
Fix typo for "Plannifeir", "Plannifier"
Add translations for "Schedule a new email report", "Scheduled task executor not found"

### CODE REVIEW

**Review by john-bodley — APPROVED** [review]

**Review by sfirke — APPROVED** [review]

**Comment by john-bodley** [comment]
Thanks @xavier-GitHub76 for the PR. Would you mind running `tox -e pre-commit` locally which should remedy the `prettier` issue.

**Comment by xavier-GitHub76** [comment]
Thanks for your actions.
@john-bodley, I'm OK to do but I don't know how to do.
Best regards

**Comment by john-bodley** [comment]
@xavier-GitHub76 see [these](https://github.com/apache/superset/blob/master/CONTRIBUTING.md#git-hooks) instructions on how you should configure your local environment to run the Git hooks (which include `prettier`).

**Comment by xavier-GitHub76** [comment]
Thanks for precisions.

I do : 
pip3 install -r requirements/integration.txt
image

pre-commit install
image

tox -e pre-commit
image
image
image

3 errors are founed : 
image

**Comment by rusackas** [comment]
I think the suggested edits will fix the linting issues, but I believe the edits should be made to the .po files, and the .json files will be generated from those.

**Review by rusackas — CHANGES_REQUESTED** [review]
The json files are no longer part of the repo itself. Please make changes to the `.po` files, and the other (`.json` and `.mo`) files will be generated when needed.

**Pull request closed without merging**
