### PR TITLE
style: Wrap chart titles again

### PR DESCRIPTION
**Pull request by rusackas**
### SUMMARY

This PR re-enables line-wrapping. Truncation might be re-enabled as a feature flag or something for those who prefer it, in a subsequent PR.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

Before:
image

After:
image

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [x] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by ktmud** [comment]
Could be a dashboard level config, too!

**Comment by junlincc** [comment]
LGTM, but again, from a product stand point, i don't think wrapping long chart title in dashboard is the best visual solution nor the best user behavior we want to encourage.if that makes sense to the users, we are happy to bring the long title back.

**Comment by ktmud** [comment]
Another idea is to use dynamic font size based on text length. We already do that for [some visualizations](https://github.com/apache-superset/superset-ui/blob/master/plugins/legacy-preset-chart-big-number/src/BigNumber/BigNumber.tsx#L145-L151) and there is a utility function in `superset-ui` readily available to use.

Personally I feel it makes more sense to wrap the title instead of truncating it because users put in long titles for a reason---if they feel it really looks bad, they would choose a shorter title already.

**Comment by junlincc** [comment]
> Another idea is to use dynamic font size based on text length. We already do that for [some visualizations](https://github.com/apache-superset/superset-ui/blob/master/plugins/legacy-preset-chart-big-number/src/BigNumber/BigNumber.tsx#L145-L151) and there is a utility function in `superset-ui` readily available to use.
> 
> Personally I feel it makes more sense to wrap the title instead of truncating it because users put in long titles for a reason---if they really feel it looks bad, they would choose a shorter title already.

Our original design/implementation is to have tooltip showed while user hover truncated title. so that user can view a cleaner dashboard without seeing overloaded information yet being able to access information as they need. My understanding is user have to put in long time is because
1. to include details for specific chart  
2. there are no other easy places to store or display these detailed information 
We certainly shouldn't ask user to cut the necessary details associate with a chart, but we can certainly come up w better solution for the second point. 
Design input and user testing are needed for this topic. though this is a small change in the entire product, we try not to make product decision base on individual preference or a single use case.

**Comment by graceguo-supercat** [comment]
I think offer the **_ability to show full title_** is very important. Chart title is part of data accuracy. If user prefer single line title to descriptive title, they already have other choices.

Here is a real example (before vs after we release new filter status)
Screen_Shot_2020-11-03_at_4_35_06_PM

**Review by suddjian — APPROVED** [review]

**Comment by suddjian** [comment]
> I think offer the **_ability to show full title_** is very important.

The full title is shown on hover right now via a `title` attribute.

**Comment by graceguo-supercat** [comment]
> > I think offer the **_ability to show full title_** is very important.
> 
> The full title is shown on hover right now via a `title` attribute.

Force user to hover chart one by one?

**Comment by rusackas** [comment]
@graceguo-supercat this PR gives you exactly what you're asking for... is there a reason not to approve it?

**Comment by graceguo-supercat** [comment]
> @graceguo-supercat this PR gives you exactly what you're asking for... is there a reason not to approve it?

haha No. Sorry i just forgot :)

**Review by graceguo-supercat — APPROVED** [review]
LGTM

**Comment by suddjian** [comment]
Junlin's outline of the finer points of this design challenge is very insightful. We should look at better ways to address the true underlying user needs driving this discussion. But for now I think removing title truncation makes sense.

**Review by junlincc — APPROVED** [review]

**Comment by suddjian** [comment]
Fixes #11581

**Comment by rusackas** [comment]
Obviously this is one contentious line of CSS! Some of us like shorter chart headers... some of us don't. I can see a few ways to tackle things like it in the future:

1) More feature flags... though many of us are not fans of adding a bunch of feature flags for tiny CSS changes, the option exists
2) Adding a custom style sheet somewhere - think of it as a config file, where you can just override some things like this. This could get fragile quickly, so it would be a "use at your own risk" thing.
3) Adding a user preferences area... though not all that different from feature flags, at least the _user_ gets the choice.
4) Bringing this sort of thing back to the community as DISCUSS and VOTE threads. We have a governance model for a good reason :)

The important thing (to me anyway) is that Superset is going to have a lot of changes... we need to get better at:
• Considering design proposals before approving, so we don't have to backtrack later
• Surfacing feedback from users in a constructive way, as early as possible
• _Iterating_ on features when we can, to prevent big reverts over small details.
• Staying friends through all of this! ❤️ All of your hard work and input is valued here. Thanks, everyone.

... but again, much ado about _just one line_... merging!

**Comment by graceguo-supercat** [comment]
Before implementation, a design document which is clear, accurate, highlight all the changes, public accessible to open source community, will help us.

**Comment by mistercrunch** [comment]
> Before implementation, a design document which is clear, accurate, highlight all the changes, public accessible to open source community, will help us.

It's quite a luxury and ideal to have that when we can, and we're committed to get better at this. But realistically won't always be possible depending on the work at hand. Personally what I think is important is the ability to quickly get to a state that a majority is happy with, and sometimes it'll require some back and forth. It's hard to know ahead of time which areas might be contentious too.

**Pull request merged**
