### PR TITLE
chore(helm): bumping app version to 4.1.1 in helm chart

### PR DESCRIPTION
**Pull request by lodu**
appVersion: ~~4.0.1 -> 4.1.0~~ 4.0.1 -> 4.1.1
chart version: ~~0.13.0 -> 0.13.1~~ ~~0.13.1 -> 0.13.2~~ 0.13.2 -> 0.13.3

For anyone waiting for this to be merged: [check this](https://github.com/apache/superset/pull/29465#issuecomment-2388199975). Be wary tho: sometimes breaking changes might occur in chart update.

### CODE REVIEW

**Comment by lodu** [comment]
don't merge.
Docker images are not yet released (4.1.0 and 4.1.0-dev).

**Comment by lodu** [comment]
blocking issue: https://github.com/apache/superset/issues/30919

**Review by villebro — APPROVED** [review]
LGTM

**Comment by villebro** [comment]
Marking as draft until the docker image is published.

**Comment by villebro** [comment]
@lodu please rebase and update the chart version to 0.13.2, as I needed to bump the version here to 0.13.1: #30924

**Pull request merged**
