### PR TITLE
New administrator tutorial

### PR DESCRIPTION
**Pull request by dylburger**
Committing new administrator tutorial and images (#1846)

### CODE REVIEW

**Comment by mistercrunch** [comment]
img

**Comment by mistercrunch** [comment]
It's out here:
http://airbnb.io/superset/tutorial.html

I just realized you're using an older version of Superset (actually Caravel) and some of the flows have changed a bit (saving a slice for instance). You should upgrade!

The user flows will keep on changing a bit more until they settle. This tutorial is still much better and up-to-date than the one we had before.

**Comment by dylburger** [comment]
@mistercrunch oh cool, I'll definitely upgrade and try to keep the tutorial up-to-date moving forward.

Hoping to start hacking on a feature and get closer to the dev side, so should help me stay aligned with more of the UI changes y'all are making.

Thanks again for the merge and for the help.

**Comment by QiXuanWang** [comment]
Pretty cool. Any chance you would also work on the introduction/tutorial on advanced topics like Druid or celery or SQL Lab usage in superset. I kind of get lost in reading druid documentation and have no idea how it works in superset. Appreciate it.

**Comment by dylburger** [comment]
@QiXuanWang yes, I'd love to develop out these docs. I'll start with Druid - I've been meaning to play around with the Druid / Superset setup recently - and tackle SQL Lab after. I'm unfamiliar with the celery configuration but it sounds like a fun learning opportunity, too.

**Comment by QiXuanWang** [comment]
Will be waiting for this :) 
BTW, the three examples for adding new slice/dashboard is outdated too. The code structure seems got some major change so some of them are no longer within same file at all. Maybe it's too much for you but just write it here so someone else that owned those checkins could have a chance to rewrite something.

A non-related topic: I was thinking about adding one layer between get_data and actually passing to viewer. But realized that these data should be stored in SQL too. Was still struggling. Not sure if superset could do this though.

**Pull request merged**
