### PR TITLE
Dashboard access control

### PR DESCRIPTION
**Pull request by x4base**
Control the access to the dashboards according to the user roles.
Please give me some advices if you think there is any problem

### CODE REVIEW

**Comment by asydorchuk** [comment]
@x4base, just to clarify: the difference from the current behavior is that the dashboard will be accessible by everybody unless explicit role is specified for it in the dashboard_role_access table? If my previous suggestion is correct, why do we need a new tables for this as such permissions theoretically are already configured via ab_permission_view_role table? Please let me know if any of my questions is not clear.

**Comment by x4base** [comment]
@asydorchuk 
Yes, that's one of the differences. I know it can be done by configuring the permissions, but
a. the permission setting is so complicated and is already a mess (to me). There are already too many permissions and it's confusing and not straightforward for the users. The users don't know what permissions can be tweaked and permissions for different purposes are all mixed together in one place. You can see the problem by looking at the long list of permissions of Admin and Alpha roles. By moving it to a separate place, it will be clear and specific. and 
b. we don't have to create permissions for each dashboard. if we have 30 dashboards, we will have to create 30 permissions. It's, again, too complicated to me.
I really wished I could reuse the logic of the permissions. If you still don't think it's a good idea to create another table for dashboard access, maybe another thing we should do is to improve the permission editing page to make it straightforward to the users.
Or maybe keep the new form field "role access" in this pull request, but when the form is saved, finish the logic using ab_permission instead of a new table. But I am not sure if it is feasible.

**Comment by asydorchuk** [comment]
@x4base, sounds reasonable to me, however I am not the owner of the repo. You probably need to update existing datasource_access permission checks.

**Comment by x4base** [comment]
@asydorchuk But what I want I is to make some slices/dashboards only accessible by certain roles, even when the data are from the same datasource.

**Comment by asydorchuk** [comment]
@x4base, understood. Thanks for the explanation!

**Comment by maver1ck** [comment]
Hi,
Could you tell me why this PR was closed ?

**Comment by Gowtham95india** [comment]
Is this feature available in superset?

**Pull request closed without merging**
