### PR TITLE
Adding disclaimer file and a notice file

### LINKED ISSUE #6479: Create NOTICE file at the top of the source directory
From Alan Gates

> Create NOTICE file at the top of the source directory, see
https://incubator.apache.org/guides/releasemanagement.html and
http://www.apache.org/legal/release-policy.html

### LINKED ISSUE #6480: Create a DISCLAIMER file
From Alan Gates

> Need a DISCLAIMER file, see https://incubator.apache.org/guides/branding.html

### PR DESCRIPTION
**Pull request by michellethomas**
Let me know if this doesn't look right. I'm not sure what year should I use for the copyright, the documentation [here](http://apache.org/legal/src-headers.html#notice) lists this that this should be the "year(s) of distribution of the current and past versions of the product". Should I use the start of the project (2015), when it started incubating (I don't know the year for this), or current year?

Fixes #6480 and fixes #6479 

@mistercrunch @kristw

### CODE REVIEW

**Review by phoenix24 — APPROVED** [review]

**Comment by kristw** [comment]
@mistercrunch Should we merge this one?

**Comment by bolkedebruin** [comment]
This needs to be in the MANIFEST.in to make sure it is included in the sdist. See #6671

**Comment by mistercrunch** [comment]
For others trying to figure out what to do with @grntmhqo acting like a random spambot, check out this option:
screen shot 2019-01-13 at 1 58 21 pm

**Comment by kristw** [comment]
Closing this since @bolkedebruin merged #6738

**Pull request closed without merging**
