### PR TITLE
ImpalaEngineSpec inherits HiveEngineSpec

### PR DESCRIPTION
**Pull request by aaronbannin**
Impala maintains compatibility with Hive. Inheriting `HiveEngineSpec` makes it easy to share functionality and override when necessary.

### CODE REVIEW

**Comment by aaronbannin** [comment]
@mistercrunch What are your thoughts on getting this in for 0.26? I've forked our current build and would love to get back onto master.

**Comment by aaronbannin** [comment]
This seems to be working well for slices, but SQL Lab generates this error:

```
2018-07-02 21:20:17,145:INFO:root:Triggering query_id: 16
2018-07-02 21:20:17,151:ERROR:root:cannot import name 'constants'
Traceback (most recent call last):
  File "/opt/superset/venv/lib/python3.4/site-packages/superset/sql_lab.py", line 94, in get_sql_results
    ctask, query_id, return_results, store_results, user_name)
  File "/opt/superset/venv/lib/python3.4/site-packages/superset/sql_lab.py", line 118, in execute_sql
    db_engine_spec.patch()
  File "/opt/superset/venv/lib/python3.4/site-packages/superset/db_engine_specs.py", line 779, in patch
    from pyhive import hive
  File "/opt/superset/venv/lib/python3.4/site-packages/pyhive/hive.py", line 11, in <module>
    from TCLIService import constants
ImportError: cannot import name 'constants'
2018-07-02 21:20:17,152:DEBUG:root:[stats_logger] (incr) error_sqllab_unhandled
2018-07-02 21:20:17,159:ERROR:root:cannot import name 'constants'
Traceback (most recent call last):
  File "/opt/superset/venv/lib/python3.4/site-packages/superset/views/core.py", line 2188, in sql_json
    query_id=query_id, return_results=True)
  File "/opt/superset/venv/lib/python3.4/site-packages/celery/local.py", line 191, in __call__
    return self._get_current_object()(*a, **kw)
  File "/opt/superset/venv/lib/python3.4/site-packages/celery/app/task.py", line 380, in __call__
    return self.run(*args, **kwargs)
  File "/opt/superset/venv/lib/python3.4/site-packages/superset/sql_lab.py", line 94, in get_sql_results
    ctask, query_id, return_results, store_results, user_name)
  File "/opt/superset/venv/lib/python3.4/site-packages/superset/sql_lab.py", line 118, in execute_sql
    db_engine_spec.patch()
  File "/opt/superset/venv/lib/python3.4/site-packages/superset/db_engine_specs.py", line 779, in patch
    from pyhive import hive
  File "/opt/superset/venv/lib/python3.4/site-packages/pyhive/hive.py", line 11, in <module>
    from TCLIService import constants
ImportError: cannot import name 'constants'
```

My `requirements.txt`:
```
contextlib2==0.5.5
flask==0.12.2
flask-cors==3.0.3
flask-mail==0.9.1
flask-oauth==0.12
flask_oauthlib==0.9.3
gevent==1.2.2
psycopg2==2.7.4
pyathenajdbc==1.2.0
pyhive==0.5.0
pyldap==2.4.28
redis==2.10.5
sasl==0.2.1
sqlalchemy-redshift==0.7.0
#sqlalchemy-redshift==0.5.0
sqlalchemy-clickhouse==0.1.1.post3
sqlalchemy-utils==0.32.16
superset==0.22.1
thrift==0.10.0
thrift-sasl==0.2.1
thriftpy==0.3.9
Werkzeug==0.12.1
impyla==0.14.0
```

Has anyone seen a similar error when working with Presto or Hive?

**Comment by RoryJShevin** [comment]
+1 would love to see this change

**Comment by aaronbannin** [comment]
I haven't manually tested every method that is inherited in the Hive and Presto classes, but slices seem to be working just fine for Impala. The partition and logging functionality seem to work just fine (hard for me to be certain w/o automated tests). The only issue I've seen is the TCLI compatibility (which feels like it's a dependency collision). 

My primary goal was to get `epoch_s` to work for Impala, perhaps I should submit a new PR with that change and figure out how to test this further?

**Comment by mistercrunch** [comment]
My concerns would be around SQL Lab

**Comment by aaronbannin** [comment]
Closing this PR and submitted [PR-5349](https://github.com/apache/incubator-superset/pull/5349)

**Pull request closed without merging**
