### PR TITLE
Add .standalone class to <body> when in standalone mode

### LINKED ISSUE #6810: Add a way to write dashboard CSS that only applies in standalone mode
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
commit 88283dc2cbfadedee94bdd6c72004e7a7fba5dfa

### Expected results
When in standalone mode, the `<body>` element has CSS class `.standalone`, so that one can build custom CSS for when a dashboard is in standalone mode. For example to hide the chart controls when in standalone:
```css
.standalone button.slice-header-controls-trigger {
    display: none;
}
```

### Actual results
There is no way to write custom dashboard CSS that will apply in standalone mode, but not outside of standalone mode.

### PR DESCRIPTION
**Pull request by raphaelmerx**
Closes #6810 

Add a `standalone` class to the html `<body>` element when in standalone mode, so that one can add custom dashboard CSS that only applies in standalone mode.

### CODE REVIEW

**Comment by lilila** [comment]
@raphaelmerx , Could you please show an example of css for standalone chart. 
When I use standalone=True I lose the label colors  , do you know how to fix this?

**Comment by lilila** [comment]
@raphaelmerx , could you please show an example of .standalone use in CSS. 
Whenever I "explore" a chart from a dashboard I loos all CSS properties defined in the dashboard. 
For instance, I am trying to increase the font size of dist_bar plot. 
It works well in the Dashboard context but when I click on explore chart (standalone or not), the normal font size comes back. Do you have any suggestion for this? Thank you

**Comment by raphaelmerx** [comment]
@lilila I have a superset URL for a standalone dashbaord that looks like `https://example.com/superset/dashboard/10/?standalone=true`. This URL is used in an iframe that is present on my site.
Then when i open that dashbaord URL (without the `?standalone=true`) in a separate tab, and go to Edit dashboard > Edit CSS, some of my CSS only targets the dashboard in standalone mode e.g.
```css
.standalone .dashboard-component-chart-holder {
    border: 1px solid;
}
```

**Comment by lilila** [comment]
@raphaelmerx Thank you for your answer, so still is is a style sheet applied to the entire dashboard. I wish I find a way to keep the dashboard's style on a single chart when I go to the Explore Chart view. Basically I display iframed charts inside presentation (made with reveal.js) and I wish they look the same in the dashboard and in the presentation. 
If you have any tips for this I would be glad.

**Pull request merged**
