### PR TITLE
Fix createDatasource

### PR DESCRIPTION
**Pull request by betodealmeida**
### CATEGORY

Choose one

- [X] Bug Fix
- [ ] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY

Clicking "Explore" in SQL Lab is currently broken, since the table ID is not passed correctly. This PR fixes it.

### TEST PLAN

Clicking "Explore" in SQL Lab, running master, will display the error message "An error occurred while creating the data source". With this PR it works.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### REVIEWERS

@khtruong @williaster @mistercrunch

### CODE REVIEW

**Comment by betodealmeida** [comment]
@arpit-agarwal, your change in https://github.com/apache/incubator-superset/pull/7907/files is not working for me. If I log the response I get:

```javascript
{json: {table_id: 23}, response: Response}
```

And because of this, `data` is undefined.

cc: @villebro

**Comment by arpit-agarwal** [comment]
Can you mention the the steps via that you found this issue?

Theoretical earlier code and new one is identical. I can run few more tests and revert back.
Have you rebuild frontend.

I am assuming you're logging the response in fromtend
________________________________

**Comment by arpit-agarwal** [comment]
Thanks @betodealmeida 
Apologies a incorrect check-in went into the PR.

**Review by villebro — APPROVED** [review]
Apologies for letting this slip through. I can confirm that this fixes the error.

**Comment by betodealmeida** [comment]
No problem, I just wanted to double check I wasn't missing something. Thanks, @arpit-agarwal and @villebro! :)

**Pull request merged**
