### PR TITLE
[table] [columns] remove generic checkbox API

### PR DESCRIPTION
**Pull request by dpgaspar**
### CATEGORY

- [X] Bug Fix
- [ ] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY
Removes generic checkbox API. Checkboxes are set to disabled on the list view. Users have to change this values on the edit form.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Before:
image

After:
image

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by craig-rueda — APPROVED** [review]
LGTM

**Comment by willbarrett** [comment]
I'm not sure this is the correct solution to the problem. From my understanding, this system was added to support a specific usecase - the need to quickly configure the `Groupable` and `Filterable` options on the view you added screenshots for. Perhaps a viable solution would be to move from a generic implementation of the functionality to a specific one that targets only the appropriate models without the use of metaprogramming?

**Comment by dpgaspar** [comment]
Yes, the final solution most come from a custom implementation and that's exactly the next phase of the API migration. I propose merging this to patch the old API issue, user's don't get too impaired by this, since they can toggle the checkboxes for `Filterable` and `Groupable` on the same page using the edit.

**Comment by willbarrett** [comment]
I think we should check the assumption that this won't cause users problems before merging. I'd love input from @graceguo-supercat and @betodealmeida to see if this functionality is frequently used before we merge. Lyft and Airbnb can live without it for a couple of weeks, that would make me feel more comfortable.

**Comment by graceguo-supercat** [comment]
Some users may only know list view to edit columns attributes, but now they will see the checkboxes are disabled. 
Can we show tooltip (or any other type of message?) on the disabled checkbox to tell user where to edit them?

**Comment by dpgaspar** [comment]
@graceguo-supercat added the tooltip, check if you agree with the text

**Review by graceguo-supercat — APPROVED** [review]

**Pull request merged**
