### PR TITLE
feat: Upgrade documentation V2

### PR DESCRIPTION
**Pull request by hughhhh**
### SUMMARY

Upgrading documentation to use docusaurus instead of gatsbyJS. This will allow us to have better control on the docs provide with different versions of superset as we continue to develop.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

Screen Shot 2022-01-05 at 2 30 58 PM

### Dark mode shot with darkmode logo
Screen Shot 2022-01-05 at 2 31 54 PM

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by srinify** [comment]
@hughhhh I know it's on your list, but just a reminder to investigate SEO redirects :]

These are the ones we've added in Gatsby / DocZ: https://github.com/apache/superset/blob/master/docs/gatsby-node.js

**Comment by hughhhh** [comment]
> @hughhhh I know it's on your list, but just a reminder to investigate SEO redirects :]
> 
> These are the ones we've added in Gatsby / DocZ: https://github.com/apache/superset/blob/master/docs/gatsby-node.js

This plugin looks like it will do the job for us:
https://docusaurus.io/docs/next/api/plugins/@docusaurus/plugin-client-redirects

**Review by srinify — APPROVED** [review]

**Comment by ad-m** [comment]
Are there any design docs why docusaurus was selected as the next solution for Apache Superset documentation? I am not against, I would like to understand the rationale of that. I am thinking of a significant expansion of Apache Superset documentation around Helm Chart (eg. document the parameters on top of recently added schemats etc. - #18161) so I have to rethink how to fit and make it maintainable.

**Comment by hughhhh** [comment]
> Are there any design docs why docusaurus was selected as the next solution for Apache Superset documentation? I am not against, I would like to understand the rationale of that. I am thinking of a significant expansion of Apache Superset documentation around Helm Chart (eg. document the parameters on top of recently added schemats etc. - #18161) so I have to rethink how to fit and make it maintainable.

Hey @ad-m, we discussed it internally in our community partner meetings. I can send you the google doc spike explaining the reasons for the move to docusaurus.

**Comment by ad-m** [comment]
> I can send you the google doc spike explaining the reasons for the move to docusaurus.

I would be happy to read it - my e-mail address is naczelnik@jawnosc.tk

**Pull request merged**
