### PR TITLE
Guess the filter value type

### PR DESCRIPTION
**Pull request by bkyryliuk**
Solves: https://github.com/airbnb/superset/issues/1977

@mistercrunch - please let me know what u think.

### CODE REVIEW

**Comment by mistercrunch** [comment]
Will this work with existing Slices that have filters that aren't quoted?

**Comment by bkyryliuk** [comment]
@mistercrunch - nope, it won't.
I can do a db migration for it.
It is impossible to differentiate '0' from 0 if we do not enforce quotes.

**Comment by mistercrunch** [comment]
LGTM is tested in V1 & V2

**Comment by bkyryliuk** [comment]
@mistercrunch  - tested on staging for both v1 and v2

**Pull request merged**
