### PR TITLE
feat: Disables HTML rendering in Toast by default

### PR DESCRIPTION
**Pull request by michael-s-molina**
### SUMMARY
This PR disables HTML rendering in toast messages by default. I couldn't find any instances of toast messages with HTML content but it is a valid use case, so I created an `allowHtml` property for this scenario.

### TESTING INSTRUCTIONS
1 - Make sure toast messages don't render HTML by default
2 - Make sure toast messages render HTML if `allowHtml` is enabled

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by michael-s-molina** [comment]
Reviewers, please let me know if we actually have an instance where we use HTML in toast messages already. I couldn’t find one.

**Review by kgabryje — APPROVED** [review]
Lgtm. I'm not aware of any toast with html content

**Review by lyndsiWilliams — APPROVED** [review]
LGTM! I did a quick scour through the code and it doesn't look like we have any existing toasts with HTML, I think this should be safe to implement 😁

**Review by rusackas — APPROVED** [review]
LGTM!

**Pull request merged**
