### PR TITLE
fix(docker): Remove race condition when building image

### PR DESCRIPTION
**Pull request by alekseyolg**
After merging the PR, a race condition for writing access to the apt cache directory began to appear from time to time. This oversight must be corrected.
https://github.com/apache/superset/pull/26196

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by michael-s-molina — APPROVED** [review]

**Comment by john-bodley** [comment]
Thanks @alekseyolg for the fix. Would you mind including mention in the `TESTING INSTRUCTIONS` section regarding how we know this fix is suffice? It may be something as simple as:

> Ran `docker-compose` locally.

**Comment by alekseyolg** [comment]
@john-bodley Unfortunately, I am not a native English speaker and will not be able to describe everything correctly. I can write my logic of thoughts that guided me when creating this pull request.

**Comment by michael-s-molina** [comment]
@alekseyolg It looks like the CI Docker build execution time doubled after this PR and is taking more than 1 hour to complete. Could you check?

**Comment by alekseyolg** [comment]
@michael-s-molina The increase in build time is due to the fact that the images are built sequentially; unfortunately, I have not yet figured out how to speed up this process; building ARM64 takes a lot of time.
To speed up the assembly process, respected @sebastianliebscher created a pull request https://github.com/apache/superset/pull/25564 which for some reason was not accepted. This PR should solve the problem of long image assembly.

**Comment by alekseyolg** [comment]
It would also be possible to speed up the build using caching.
https://github.com/apache/superset/pull/25422
This pool request has been closed, but if the respected @craig-rueda tells me where to put the build cache, then I can create a new PR, which will significantly speed up the process of building images.

**Comment by craig-rueda** [comment]
I'll ask Apache infra for a new dockerhub registry that we can use for build caching

**Pull request merged**
