### PR TITLE
[translate]Translate the po file into chinese 

### PR DESCRIPTION
**Pull request by zhouyao1994**
[translate]Translate the po file into chinese 

and regenarate po file from.source code

### CODE REVIEW

**Comment by xrmx** [comment]
FYI you don't need to open a new PR just push the changes to the same branch and the PR will update.

**Comment by zhouyao1994** [comment]
@xrmx sorry~ this is my first time to commit  my code. thank you mind me。

Can I push requer my code in this PR since the prev PR branch had been deleted.

**Comment by zhouyao1994** [comment]
@magicansk  I add the Chinese-Traditional lang but I can't see in my browser, is that has some font problem? can you test it ? thank you ~

**Comment by magicansk** [comment]
Hi, @zhouyao1994 
- Can you more specifically your problem?
- And what do you wanna me to test the feature in # 3717? 
Thanks

**Comment by zhouyao1994** [comment]
thank you reply.i add a Chinese-Traditional lang suport in it  but i can't see it. 
Does you first langues is Chinese-tranditianl?
I just see you commit a with some Chinese word.

it doesn't work with Chinese-tranditianl  but it work with Chinese-simple.
I don't know why.
if you can help me .
thank you very much.

it doesn't work with Chinese-tranditianl

but it work with Chinese-simple also work with Janpanese languages.

**Comment by magicansk** [comment]
Hi @zhouyao1994, 
What URL exactly you are looking at? 
It looks fine in my browser both simple Chinese and traditional Chinese or others languages. 
Possibly, the problems are caused by your browser or country(China) may block the zh-TW in alternative ways. It's not the problem by traditional Chinese.

**Comment by zhouyao1994** [comment]
Hi @magicansk  
ok that's Good. thank you very much~  
My code is running at local host .so it's not work when i send my url to you!

**Comment by zhouyao1994** [comment]
【translate】add Chinese-TW langua  and try to translate more in Chinese

**Comment by zhouyao1994** [comment]
@graceguo-supercat  can you review this code that i commit in This PR?

**Comment by zhouyao1994** [comment]
@mistercrunch #3717 have PR few days。

1.  Is there some code unproper in my translate file?
2.  why there is no translate folder when i install superset throught pip tool? I am work in ubuntu 17.04    python3.5.3 virtualenv.


i used superset set for a few mouth,it's very good I really want to be able to make comtribution to the community.
so i I'm looking forward to your merging my code.


thank you very much!

**Comment by graceguo-supercat** [comment]
@zhouyao1994 Thank you for the contribution. Sorry for the delay, because we have another translation PR https://github.com/apache/incubator-superset/pull/3750 and https://github.com/apache/incubator-superset/issues/3745, I just want to make sure all new translations are put into right place. 

Please resolve conflicts, and then I can merge it. Thank you!

**Comment by zhouyao1994** [comment]
@graceguo-supercat  i just  rebase on  the latest code in master and sovle the conflices .But,it seems that so many changes have been commit. Is that the right thing to do?

**Comment by graceguo-supercat** [comment]
@zhouyao1994 I see you only have 1 conflict for file `superset/views/core.py`. You can do a rebase first to pick up all latest change, then fix conflict in this file. Please double check you didn't overwrite other contributors' code. Thank you!

**Pull request closed without merging**
