### PR TITLE
fix(fab): Fix regression on FAB dropdowns

### PR DESCRIPTION
**Pull request by codyml**
### SUMMARY

This PR removes some global CSS that conflicts with FAB dropdowns.  FAB version was bumped in https://github.com/apache/superset/pull/22580, and the new version includes markup that certain global CSS styles in `superset.less` now apply to, causing a visual bug with dropdown menus.  The global CSS was introduced in https://github.com/apache/superset/pull/3241 to style the `VisualizeModal` component.  This component was removed in https://github.com/apache/superset/pull/5523, so I believe these global styles are no longer used anywhere in the app (though if anyone knows otherwise, definitely let me know).

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

Before:
localhost_9000_rowlevelsecurityfiltersmodelview_add

After:
localhost_9000_rowlevelsecurityfiltersmodelview_add (1)

### TESTING INSTRUCTIONS

- Confirm that FAB views' dropdowns look and work correctly:
  - `/rowlevelsecurityfiltersmodelview/add`

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by codyml** [comment]
For added context, here's what the dropdown looked like before the FAB upgrade:
localhost_9000_rowlevelsecurityfiltersmodelview_add (2)

**Comment by andrey-zayats** [comment]
QA verified the fix. LGTM!

**Comment by codyml** [comment]
> QA verified the fix. LGTM! But dropdown color and selected tile colors is different (PR vs Prod).

Thanks!  Will tackle the color changes in a separate PR.

**Review by Antonio-RiveroMartnez — APPROVED** [review]
LGTM!

**Review by lyndsiWilliams — APPROVED** [review]
Yay, less LESS! 🎉

**Pull request merged**
