### PR TITLE
Deprecate database attribute allow_run_sync

### PR DESCRIPTION
**Pull request by mistercrunch**
There's really 2 modes of operations in SQL Lab, sync or async
though currently there are 2 boolean flags: allow_run_sync and
allow_run_async, leading to 4 potential combinations, only 2 of which
actually makes sense.

The original vision is that we'd expose the choice to users and they
would decide which `Run` or `Run Async` button to hit.
Later on we decided to have a
single button and for each database to be either sync or async.

This PR cleans up allow_run_sync by removing references to it.

### CODE REVIEW

**Review by timifasubaa — APPROVED** [review]

**Comment by john-bodley** [comment]
Thanks for simplifying this logic. One concern is that we shouldn't augment existing migrations but simply create a new migration which drops the deprecated column and sets the async value appropriately.

**Comment by mistercrunch** [comment]
@john-bodley this was done on purpose as db migrations have been a huge plague and should be avoided whenever possible. A lot of the downtime in the history of Superset has been related to db migrations. Either, db locks/deadlocks at migration time, partial rollout (some in-deployments nodes are missing the new column, deployment reverts requiring a manual downgrade from the previous branch, ...)

The lingering database column in my opinion is no big deal in comparison to the issues related to db migrations problems.

**Comment by timifasubaa** [comment]
PING

**Comment by mistercrunch** [comment]
@john-bodley @timifasubaa reviving this, and added the db migration to keep the db clean

**Review by timifasubaa — APPROVED** [review]

**Comment by timifasubaa** [comment]
Looks good to me once you get it to pass CI

**Pull request merged**
