### PR TITLE
fix(1:dashboard-ui,2:Explore control panel): 1:undo and redo buttons weird alignment. 2:Keyboard navigation in Explore control panel

### LINKED ISSUE #16365: [dashboard][cosmetic]undo and redo buttons weird alignment
1. I'm not sure where else in the product is using these unicorns, the purpose of these icons seem unclear to me. and they are not even centered. 🤦🏾‍♀️

https://user-images.githubusercontent.com/67837651/130163663-ae995c1f-1454-49eb-8a33-2db5bc6cdbed.mov

we could consider go straight to implement new design in sip 34, or simply center the icon for now. low priority.

### PR DESCRIPTION
**Pull request by MaxHuiYYDS**
### SUMMARY
1:dashboard-ui:
I think it related to [PR #13037](https://github.com/apache/superset/pull/13037), which help add 8px marginRight when there are more than one element. But it may not apply for this situation, in order not to affect other components, I add the showMarginRight prop in Button Component.

2:Explore control panel:
I added hideNativeTab prop at ControlHeader in selectControl, when the native keyboard Tab actions need to  omit the headers, then define the hideNativeTab to true.

###: BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

###  1:dashboard-ui: BEFORE：
image

###  1:dashboard-ui: AFTER：
image

### 2:Explore control panel: AFTER：

https://user-images.githubusercontent.com/51693396/130355613-79b19e53-4bcd-4b18-9871-3abb04ff0aca.mov

### ADDITIONAL INFORMATION

- [x] Has associated issue: Fixes #16365, #14574
- [] Required feature flags:
- [x] Changes UI
- [] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [] Migration is atomic, supports rollback & is backwards-compatible
  - [] Confirm DB migration upgrade and downgrade tested
  - [] Runtime estimates and downtime expectations provided
- [] Introduces new feature or API
- [] Removes existing feature or API

### CODE REVIEW

**Comment by MaxHuiYYDS** [comment]
@junlincc @ktmud  Please help review.

**Comment by ktmud** [comment]
@MaxHuiYYDS Thanks for the contribution. Could you split this into two PRs? It seems the two changes are not related.

**Comment by junlincc** [comment]
@MaxHuiYYDS please do split this PR into 2, and attach separate issues to them. 🙏

**Comment by MaxHuiYYDS** [comment]
@junlincc @ktmud , done, please help review https://github.com/apache/superset/pull/16418 and https://github.com/apache/superset/pull/16417

**Pull request closed without merging**
