### PR TITLE
fix(sqllab): Updated blank states for query results and query history

### PR DESCRIPTION
**Pull request by lyndsiWilliams**
### SUMMARY

Updated the blank states for query results and query history using the [EmptyStateMedium component](https://github.com/apache/superset/pull/18676).

#### BEFORE
resultsBefore
historyBefore

#### AFTER
resultsCentered
historyCentered

### TESTING INSTRUCTIONS

- Go to the SQL Lab Editor and open a new query
- Observe the updated blank state in the "results" and "query history" tabs

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by pkdotson — APPROVED** [review]
LGTM!

**Review by AAfghahi — APPROVED** [review]

**Comment by yousoph** [comment]
@kasiazjc can you take a look and see if this looks good to you? Thanks!!!

**Pull request merged**
