### PR TITLE
Remove SQLite from CI (Implementation of SIP-33)

### PR DESCRIPTION
**Pull request by willbarrett**
### CATEGORY

Choose one

- [ ] Bug Fix
- [x] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY

See [the relevant SIP](https://github.com/preset-io/infra/pull/new/wbarrett/add-instance-profile)

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [X] Removes existing feature or API

### CODE REVIEW

**Review by craig-rueda — APPROVED** [review]
LGTM

**Comment by villebro** [comment]
@willbarrett I think you need to remove the `py36-sqlite` entry from `.travis.yml`: https://github.com/apache/incubator-superset/blob/master/.travis.yml#L82-L86
Other than that, LGTM

**Review by craig-rueda — APPROVED** [review]

**Review by villebro — APPROVED** [review]

**Comment by mistercrunch** [comment]
I wonder if we should error or warn on startup if the connection string starts with `sqllite`

**Comment by mistercrunch** [comment]
Oh also I just checked and the default connection string in `config.py` is still `sqlite://`

**Comment by willbarrett** [comment]
Agreed @mistercrunch - this is still in draft state, there's more to do here.

**Comment by willbarrett** [comment]
bump

**Comment by willbarrett** [comment]
Implementation no longer valid - we've switched CI vendors. Closing.

**Pull request closed without merging**
