### PR TITLE
fix(Indian Map Changes): fixed-Indian-map-border

### LINKED ISSUE #19729: Update geojson for India's map
Request you to correct geojson map file of India as per latest state list

https://github.com/apache/superset/blob/master/superset-frontend/plugins/legacy-plugin-chart-country-map/src/countries/india.geojson

### LINKED ISSUE #20452: Incorrect Map of India
**### some parts of india is not registered in indian territory i.e gilgit**

### PR DESCRIPTION
**Pull request by Yaswanth-Perumalla**
### SUMMARY
The previous Indian border was inaccurate, and I've now made the required adjustments to the existing border of India.

### BEFORE

image

### AFTER 

image

#### Bug references:
Closes #20452
Closes #19729

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by john-bodley** [comment]
Thanks @Yaswanth-Perumalla for the PR. Would you mind including before and after screenshots so reviewers can visualize the difference. Also any additional context you can provide in terms of what was wrong and/or why your proposed solution is correct would be helpful.

**Review by sevakram — APPROVED** [review]

**Comment by john-bodley** [comment]
@Yaswanth-Perumalla it seems that your updated map may include disputed territories. I think @villebro might have worked on a similar issue in the past and likely should weigh in here. In the case of a dispute I believe we allow all disputing territories include the region in their map.

**Comment by villebro** [comment]
> @Yaswanth-Perumalla it seems that your updated map may include disputed territories. I think @villebro might have worked on a similar issue in the past and likely should weigh in here. In the case of a dispute I believe we allow all disputing territories include the region in their map.

We take the stance that disputed areas can be featured on multiple maps, as long as there is an ISO code to back it up. @Yaswanth-Perumalla would you mind adding a reference to where you obtained the updated polygon data for this PR? Also, if you used the Notebook in this repo, it would be nice if you could also update that as part of this PR so that it's in sync with the current state of the rendered map regions.

**Comment by rusackas** [comment]
@Yaswanth-Perumalla there are a handful of people on Slack very excited to merge this PR. Can you give us an update on the questions above?

**Comment by Yaswanth-Perumalla** [comment]
@villebro  @rusackas  I have not utilized any notebooks in this repository. Can you guide me on where I should make updates?

**Comment by villebro** [comment]
@Yaswanth-Perumalla this is the notebook that's been used to generate most (or all) maps: https://github.com/apache/superset/tree/master/superset-frontend/plugins/legacy-plugin-chart-country-map/scripts Can you check if that generates the correct polygons, and if not, maybe add a note to it so someone doesn't overwrite these in the future.

**Comment by Yaswanth-Perumalla** [comment]
@villebro I have updated the notes. Kindly check and let me know if you need any further changes.

**Comment by Yaswanth-Perumalla** [comment]
@rusackas I've encountered a failed check after making updates to the notes. Can you assist me in understanding the problem?

**Comment by villebro** [comment]
If you check the failed CI workflow, it appears to complain about a missing newline at the end of the file. If you need help resolving it I can help, but feel free to take a stab at it first.

**Comment by villebro** [comment]
If you check the failed CI workflow, it appears to complain about a missing newline at the end of the file. If you need help resolving it I can help, but feel free to take a stab at it first.

**Review by villebro — APPROVED** [review]
LGTM, thanks for your patience

**Comment by amanmaurya** [comment]
The map of India is incorrect after upgrading to version 4.0.1

**Comment by rusackas** [comment]
> The map of India is incorrect after upgrading to version 4.0.1

Eek! If you want to open a PR, feel free, but we'll try to assess/fix ASAP. I even wrote a [blog post](https://preset.io/blog/how-and-when-and-why-to-update-apache-supersets-country-maps/) about how to make such a contribution, and how we're trying to be better about keeping these things current and permanent.

**Comment by PushpenderSaini0** [comment]
> > The map of India is incorrect after upgrading to version 4.0.1
> 
> Eek! If you want to open a PR, feel free, but we'll try to assess/fix ASAP. I even wrote a [blog post](https://preset.io/blog/how-and-when-and-why-to-update-apache-supersets-country-maps/) about how to make such a contribution, and how we're trying to be better about keeping these things current and permanent.

Hi i have raised a PR that restores changes that were made in this PR using the new GeoJson Generator script !

cc @amanmaurya

**Pull request merged**
