### PR TITLE
fix(explore): make SORT DESCENDING visible if SORT BY has value

### PR DESCRIPTION
**Pull request by stephenLYZ**
### SUMMARY

enhancement: Currently, if `SORT BY` is not set, `SORT DESCENDING` is not effective, for this reason, it will mislead the user, here we change it to show this control only if sort by is set.

### after

image

image

### ADDITIONAL INFORMATION

- [x] Has associated issue: https://github.com/apache/superset/issues/15212
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by riahk — APPROVED** [review]
So if SORT BY is set, does it sort descending by default?

**Comment by stephenLYZ** [comment]
> So if SORT BY is set, does it sort descending by default?

Right.

**Comment by villebro** [comment]
Removed 1.4.2 label as this cherry requires monorepo which isn't available on the 1.4 branch

**Comment by ElevenDog** [comment]
why exist default sort(sort by x-field)  this maybe cause The Chart Result data difference to sqlab query result

**Pull request merged**
