### PR TITLE
[SQLLab] Fix, database api unlimited page size v2

### PR DESCRIPTION
**Pull request by dpgaspar**
### CATEGORY

Choose one

- [X] Bug Fix
- [ ] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY
Bumps FAB to 2.1.9, and makes an unlimited request to fetch database connections on SQLLab select box.
Also added a test for this API endpoint using SQLLab request parameters (unlimited, order and filters). The added test failed for FAB 2.1.8 (has expected) and is successful on 2.1.9 

### ADDITIONAL INFORMATION
- [X] Has associated issue: #7996, #7995  
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### REVIEWERS

@etr2460 @mistercrunch

### CODE REVIEW

**Comment by dpgaspar** [comment]
Currently FAB 2.1.9 is in master, ready for release. Contains the fix for issuing SQL commands with LIMIT -1 when `page_size=-1` and `max_page_size=-1`.

I've added a simple test for the new API, and have not found any tests for the old API `/databaseasync` that still lives on superset

**Comment by mistercrunch** [comment]
@john-bodley sorry about the regression / revert earlier around this. This should be good this time around.

**Review by etr2460 — APPROVED** [review]
lgtm, and thanks for adding the test!

**Comment by dpgaspar** [comment]
No problem, for everyone's protection, sorry about this

**Review by mistercrunch — APPROVED** [review]

**Pull request merged**
