### PR TITLE
chore: grouping ALL common modules in one big chunk

### PR DESCRIPTION
**Pull request by rusackas**
### SUMMARY

There was a concern that there were TOO MANY chunks generated by webpack. This PR undoes some custom "vendors" chunking, instead going with Webpack's default of grouping shared modules in `node_modules`. The result? One Giant Chunk! This might take the browser longer to parse, but it might be more highly cached, and reduce loading when moving around between Superset's react apps. All in all, it removes about 100 other chunk files. We could set a max chunk size and break it down into a few for parallel loading, but right now, this PR is more of a discussion point.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

Bundle analyzer screengrabs to come...

### TESTING INSTRUCTIONS

I'll spin up an ephemeral environment, and people can poke around at it in a browser and take a look.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by etr2460** [comment]
Thanks for PRing to start the conversation! @rusackas could you link some screenshots with the bundle size and count before and after?

**Comment by rusackas** [comment]
image

**Comment by rusackas** [comment]
image

**Comment by rusackas** [comment]
image

**Pull request closed without merging**
