### PR TITLE
refactor: icon to icons for popoversection

### PR DESCRIPTION
**Pull request by pkdotson**
### SUMMARY
This pr migrates the icons infosmall and check within popoversection to icons.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Screen Shot 2021-06-29 at 10 36 49 AM

### TESTING INSTRUCTIONS
check icons in annotation layer controls and spatial controls

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by suddjian — APPROVED** [review]

**Comment by michael-s-molina** [comment]
The horizontal spacing between the text and the icons is bigger than it should. I think that's the problem of the fixed width/height of the icon component that we were talking about. One way to solve this is to set the `viewBox` prop.

**Comment by rusackas** [comment]
@geido for reference, in regards to how these components get aligned/spaced

**Comment by geido** [comment]
@rusackas I am a little bit confused about this behavior. If you look at the Storybook, in an isolated state, these icons do not have any space around them. As you resize them the space will be resized accordingly.

Check this out:
Screen Shot 2021-07-02 at 15 29 18

This seems to be an issue with the container element coming with styling that is forcing the icons to behave like that. 

@pkdotson I think this might require more research on your end.

Let me know

CC @michael-s-molina

**Comment by pkdotson** [comment]
> @rusackas I am a little bit confused about this behavior. If you look at the Storybook, in an isolated state, these icons do not have any excessive space around them. As you resize them the space will be resized accordingly.
> 
> Check this out:
> Screen Shot 2021-07-02 at 15 29 18
> 
> This seems to be an issue with the container element coming with styling that is forcing the icons to behave like that.
> 
> @pkdotson I think this might require more research on your end.
> 
> Let me know
> 
> CC @michael-s-molina

That is exactly what is happening. The span is not the issue it's the container styles that are causing these issues.

**Review by rusackas — APPROVED** [review]

**Pull request merged**
