### PR TITLE
fix: Correction translation

### PR DESCRIPTION
**Pull request by aehanno**
Correction french translation

### SUMMARY
Remove to fuzzy to add the right translation

### BEFORE
image

### TESTING INSTRUCTIONS
Check that after we got the new translation

### CODE REVIEW

**Comment by aehanno** [comment]
As it is link to this issue https://github.com/apache/superset/issues/28431

@rusackas, Do you know what I can do about the Docker error? I didn't modify that part, so I don't understand why I'm getting this error

Thanks

**Comment by john-bodley** [comment]
@aehanno regarding the Docker issue, would you mind rebasing?

**Comment by mistercrunch** [comment]
We really need to pull the `.json` files out of the repository. @rusackas any blockers on removing those files?

**Comment by aehanno** [comment]
> @aehanno regarding the Docker issue, would you mind rebasing?

I merge master and did the rebase

**Comment by rusackas** [comment]
> We really need to pull the .json files out of the repository. @rusackas any blockers on removing those files?

Just that people won't have translations anymore... I think you can expect a lot of Issues if that happens. That can be considered as a "breaking change" for 5.0 inclusion if you want to add it to the [5.0 Kanban](https://github.com/orgs/apache/projects/345).

On a related note, there was just an issue where people made a case for bringing the .mo files back. I agree we shouldn't have to include the .json and .mo files in the code base, but to remove them I would hope/expect that they're auto-generated (and gitignored) when installing/starting Superset.

**Comment by mistercrunch** [comment]
Assuming we would:
- add to docker build
- add to official pypi release process
- adapt docs/build instructions 

I guess that leaves people building from the repo directly out

From the perspective of pypi/docker it's not a breaking change. For the rest, maybe a note in `UPDATING.md` suffice?

**Comment by aehanno** [comment]
@rusackas It will impact what I did ?
Do I need to change something on my PR
Because I change the mo files then with the po2json I generated the json file

**Comment by rusackas** [comment]
@aehanno I think your PR is OK... we're just trying to figure out what to do with the json files, and it's just kind of happening on this thread randomly.

**Comment by rusackas** [comment]
Actually @aehanno, in looking at the PR files, there are a whole lot of changed files that look like they have nothing to do with translations. Maybe a rebase is needed?

**Comment by aehanno** [comment]
> Actually @aehanno, in looking at the PR files, there are a whole lot of changed files that look like they have nothing to do with translations. Maybe the rebase didn't work right?

I did another merge and rebase but I still got those change
I don't know why

**Comment by rusackas** [comment]
Yeah, something here isn't right. I suspect you're merging `master` onto your feature branch rather than rebasing. @mistercrunch might have the git-fu to get us out of this mess, but here's a [randomly-slected article](https://www.atlassian.com/git/tutorials/merging-vs-rebasing) on the difference that _miiiight_ help.

**Comment by aehanno** [comment]
@rusackas Can be a solution to create a new branch then the pull request ? Instead of did the correction on this one

**Comment by rusackas** [comment]
@aehanno absolutely. I've definitely done it several times :D

**Comment by aehanno** [comment]
New PR here https://github.com/apache/superset/pull/28497

**Pull request closed without merging**
