### PR TITLE
revert #9329

### PR DESCRIPTION
**Pull request by graceguo-supercat**
### CATEGORY

Choose one

- [x] Revert

### SUMMARY
Airbnb users can not use chart edit modal because of following error:
Screen Shot 2020-04-01 at 9 32 28 AM

We reported this issue last week, but it is still in master branch so we have to revert it again in our release branch.

@dpgaspar If you have suggested fix, I can test it in airbnb environment.

@mistercrunch @robdiciuccio 

### ADDITIONAL INFORMATION

- [x] Has associated issue: #9329 
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by suddjian** [comment]
Can you point to where this issue was reported, for context?

**Comment by dpgaspar** [comment]
Having an hard time to reproduce the issue. Are user's getting this when coming from dashboards? can user's view the charts on the chart list?

Note: HTTP 404, means that the chart does not exist or it's being filtered by the already in-place filter

**Comment by dpgaspar** [comment]
I'm able to reproduce it the following way:
- Give users access to dashboards that contain charts they are able to access by having database access permission, published or favorite.
- Users are not able to view these charts on the charts list view, but they can viz them on the dashboard
- Users use "Explore Chart" on the dashboard, and then click "Edit properties" and get HTTP 404.

This is caused by user's having access to viz charts by having the database access permission, but the chart filter does not include the database access filter, just schema, datasource or all datasources:

here: https://github.com/apache/incubator-superset/blob/master/superset/charts/filters.py
and here: https://github.com/apache/incubator-superset/blob/master/superset/views/chart/filters.py

Can you confirm this reasoning?

Possible path forward could be to add the database access to this filter, and assume this is the new security filter in-place for charts

**Comment by graceguo-supercat** [comment]
The error is from chart view:  open edit chart property modal will see the Error message. (edit dashboard property works good no 404).

This error message is showing just for all charts.

**Comment by dpgaspar** [comment]
I don't mean the dashboard edit, I mean accessing the chart from the dashboard and then access "Edit chart property". Can you confirm?

**Comment by graceguo-supercat** [comment]
@dpgaspar I feel this issue may only happens in airbnb environment. So we will add configuration internally, but keep open source codebase as is.

**Comment by dpgaspar** [comment]
@graceguo-supercat sounds good, I'll be around for any further help on this you my need. Thks

**Pull request closed without merging**
