### PR TITLE
feat(dashboard): Add cross filter from context menu

### PR DESCRIPTION
**Pull request by kgabryje**
### SUMMARY
Enable selecting/deselecing cross-filter from chart's context menu.

Enabled charts: World Map, all Echarts, Pivot Table, Table

"Add cross-filter" context menu option will be visible, but disabled if:
- dashboard has cross-filtering disabled
- chart does not support cross-filtering
- clicked data point does not support cross-filtering (e.g. empty space on chart)

"Add cross-filter" context menu option will not be displayed if `DASHBOARD_CROSS_FILTERS` feature flag is disabled.

If user right-clicks on series that's not emitting a cross-filter, a "Add cross-filter" option will be displayed.
If user right-clicks on series that's currently emitting a cross-filter, a "Remove cross-filter" option will be displayed.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

https://user-images.githubusercontent.com/15073128/220665986-95da1b4e-9554-4e1e-ad84-6ce5ac0d71fc.mov

### TESTING INSTRUCTIONS
Test the cross filtering feature on all charts that support it (compatible charts listed above)

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by geido** [comment]
The divider should not appear if only one item is in the menu

Screenshot 2023-02-22 at 12 01 59

The context menu is appearing also when clicking on labels. I think we should not allow that. It is correctly ignoring it but I believe a better UX would be to just disable it for labels. Wdyt?

Screenshot 2023-02-22 at 12 06 41

**Comment by kgabryje** [comment]
> The divider should not appear if only one item is in the menu
> 
> Screenshot 2023-02-22 at 12 01 59

Nice catch!

> The context menu is appearing also when clicking on labels. I think we should not allow that. It is correctly ignoring it but I believe a better UX would be to just disable it for labels. Wdyt?
> 
> Screenshot 2023-02-22 at 12 06 41

Yeah you're right... Though it might be difficult to work around as the "fallback" context menu listener is attached to chart container, not the plugin itself. I'll see what I can do

**Comment by geido** [comment]
Everything looks good except that you can emit a cross filter from a table value. Once that is fixed I believe this is good to go!

**Comment by kgabryje** [comment]
> Everything looks good except that you can emit a cross filter from a table value. Once that is fixed I believe this is good to go!

Fixed!

**Review by geido — APPROVED** [review]

**Pull request merged**
