### PR TITLE
fix(dashboard): Race condition when setting activeTabs with nested tabs

### LINKED ISSUE #16972: [native filters] Filters displayed as out of scope for dashboard with nested tabs
#### How to reproduce the bug

1. Create a new dashboard with nested tabs like this layout:
Screen Shot 2021-10-04 at 9 00 26 PM

Tab1 has 1 row of markdown, and a few nested Tabs.
In tab "nested Tab1" and "nested Tab2", each has only 1 chart.

2. Add a few filter components:
- State Filter: Apply to **nested tab 2**
- Time Filter: Apply to **nested tab 1**  and **nested tab 2**

poia0jBbAf

3. Save dashboard
4. Go to dashboard list page, and visit the just created dashboard again: in nested tab 1, filter bar shows all filters out of scope.

lW7lFlQwOC

#### Note ####
1. the filter scope data stored in dashboard metadata, is correct,
2. if i switch a few tabs back and forth, the in-scope filters and out-of-scope filters will display correct,
3. But if the landing tab has nested tab, it always show all filters are out of scope.

### Environment

(please complete the following information):

Latest master
- any feature flags active: dashboard filter component is enabled.

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context
I label this bug as P1, it looks scary since most users will feel their filter scope is totally messed up when they first seeing this issue. But probably this is only a small React render issue. 

@michael-s-molina @kgabryje @junlincc

### PR DESCRIPTION
**Pull request by kgabryje**
### SUMMARY
Fixes #16972 
Active tabs were calculated in mount/update lifecycle events in Tabs components by taking current active tabs state and appending active tab key to it. That approach resulted in race condition when there are multiple Tabs components added to a dashboard - they were all operating on the same array and when 1 component finished its job, the rest were still operating on the now outdated array of active tabs. The result was overwriting the results calculated by other Tabs components.
In order to avoid that, I moved that logic into the Redux reducer, which is guaranteed to be synchronous. Now the Tabs only send current active key and previous active key as strings to Redux and the reducer handles calculating active tabs synchronously.
The described issue was the direct reason of the linked bug - the filters were out of scope, because `activeTabs` was not calculated correctly.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Before: see linked issue

After:
https://user-images.githubusercontent.com/15073128/136361545-77fa09ff-dffe-4832-b405-53af47d98727.mov

### TESTING INSTRUCTIONS
1. Create a dashboard with multiple separate Tabs components, including nested Tabs
2. Verify that `dashboardState.activeTabs` in Redux has correct value
3. Add some native filters with scopes set to different Tabs
4. Verify that in scope/out of scope feature works as expected

### ADDITIONAL INFORMATION

- [x] Has associated issue: fixes #16972 
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

CC @junlincc @graceguo-supercat

### CODE REVIEW

**Review by villebro — COMMENTED** [review]
Code changes LGTM - it can be tricky to create a test that consistently reproduces this using the full layout, but I'd be fine with a test that asserts that redux state looks correct when called in a similar fashion to when the bug was still there.

**Review by villebro — APPROVED** [review]
We discussed testing approaches here at length with @kgabryje , and concluded that in the absence of a proper native filters RTL test suite (a big task that warrants a PR of it's own) and the relative simplicity of the reducer in question, I feel we can merge this as-is as long as we start working on integration tests as a follow-up task.

**Comment by sadpandajoe** [comment]
🏷️ 2021.40

**Pull request merged**
