### PR TITLE
chore: Fix typo “Rest” to “Reset”

### PR DESCRIPTION
**Pull request by junlincc**
### SUMMARY
this PR is to fix small typo from 'onRestStateAndClose' to 'onResetStateAndClose' 🤦🏾‍♀️

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
NA
### TEST PLAN
NA

### ADDITIONAL INFORMATION
- [ ] Has associated issue: 
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by ktmud — APPROVED** [review]
WOW, congratulations on your first PR, @junlincc ! Is there anything you cannot do?

**Comment by Biinowny** [comment]
dklfjghf

**Comment by junlincc** [comment]
> Is there anything you cannot do?

thank you ktmud! i can never be a code genius like you. 😀 @ktmud

**Comment by villebro** [comment]
Flagging for 1.0 to avoid unnecessary cherry conflicts

**Pull request merged**
