### PR TITLE
fix(dashboard): Remove bar at bottom of dashboard edit sidebar

### PR DESCRIPTION
**Pull request by codyml**
### SUMMARY

This PR removes a bar that was appearing at the bottom of the dashboard edit sidebar.  It does some misc cleanup along the way:
- Removes `builder-sidepane.less`, which contains a few actively-used styles but is mostly unused styles, and moves the actively-used styles into the relevant component files
- Replaces use of `react-sticky` with  CSS `position: sticky` (which seems to now be [supported](https://caniuse.com/css-sticky) for all of the browsers we're targeting) for the sidebar
- Removes various styles and props that are now unnecessary because of above changes

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

Before:
Screen Shot 2022-10-13 at 8 21 07 PM

After:
localhost_9000_superset_dashboard_10__native_filters_key=7nf2YdCXSNoo89wKJp6bQ0tjrlAX2AYcEkPxtZDcKB7rOM5_3bFogSmpuKjZxj1o (1)

### TESTING INSTRUCTIONS

- Check that the bar is gone
- Check that the Edit sidebar otherwise looks identical
- Check that the Edit sidebar looks identical in standalone mode (add `standalone=1` to the end of the query string)

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by stephenLYZ — COMMENTED** [review]
Awesome work! I have found some issues:
1.  It looks like layout elements tab has incorrect width:

| master | current |
| - | - |
| image | image |

2. The shadows on the left do not behave the same as the current master, is this as expected?

| master | current |
| - | - |
| image | image |

3. It is wired that tab shakes when searching

current:

https://user-images.githubusercontent.com/11830681/195994334-3b7f79aa-70fd-4f36-a47d-25daa52e4e33.mov

master: 

https://user-images.githubusercontent.com/11830681/195994356-c26c9f02-1dd5-4dc8-a2f7-425866df121d.mov

**Comment by stephenLYZ** [comment]
It seems weird that the entire page shakes when searching charts. Maybe cause by re-rendering:

https://user-images.githubusercontent.com/11830681/197179866-d57255eb-5850-47b1-abd2-b1fe26319660.mov

**Comment by codyml** [comment]
> It seems weird that the entire page shakes when searching charts. Maybe cause by re-rendering:

@stephenLYZ Yikes that is strange, thanks for catching.  Will see if I can fix.

**Comment by codyml** [comment]
@stephenLYZ Was finally able to reproduce by making my screen very very large!  I couldn't figure out exactly what was causing it but I narrowed it down to something about the `ParentSize` helper component triggering refreshes.  I replaced it with an `AutoSizer` component that was already part of the `react-virtualized` library – does it look better on your end?

Before:

https://user-images.githubusercontent.com/13007381/198171112-8af07abe-0fa8-4c32-a2d5-75c4e428737a.mov

After:

https://user-images.githubusercontent.com/13007381/198171131-df688529-79fb-412b-9594-203a046aff03.mov

**Review by stephenLYZ — APPROVED** [review]
LGTM!  Thanks for this!

**Pull request merged**
