### PR TITLE
feat: Changing Dataset names

### PR DESCRIPTION
**Pull request by AAfghahi**
### SUMMARY
We are renaming many datasets in superset based on user feedback that some of the current datasets are confusing and hard to understand.

This should improve the overall experience that a new user has in superset. 
### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by eschutho — APPROVED** [review]
Looks great

**Comment by rosemarie-chiu** [comment]
🏷 2021.31

**Comment by AAfghahi** [comment]
@eschutho does this one need to be reversed?

**Comment by eschutho** [comment]
yes it does

**Pull request merged**
