### PR TITLE
Hanization

### PR DESCRIPTION
**Pull request by asdf2014**
Before we start, we may need to declare some hanization mappings, such as `Series`, `Metrics`, `Columns` etc. In addition, we need consider is it necessary to translate those professional words, for example, `Group By`, `Source`, `Target`, `Label` etc.

### CODE REVIEW

**Comment by asdf2014** [comment]
In my opinion,  `Metric` should be translated as `指标` rather than `度量`.

**Comment by mistercrunch** [comment]
@graceguo-supercat

**Comment by asdf2014** [comment]
I think `Filters` should be translated to `过滤` better than `筛选`.

**Comment by graceguo-supercat** [comment]
It looks good. Thanks for the localization work!
Do you want to complete all strings in Superset project?

**Comment by asdf2014** [comment]
@graceguo-supercat Sure. I will finish this job in this weekend.

**Comment by asdf2014** [comment]
Maybe we could organization localization work like [bitcoin](https://www.transifex.com/bitcoin/bitcoin/) dose.

**Pull request merged**
