### PR TITLE
Check for empty dataframes before processing

### PR DESCRIPTION
**Pull request by bryanck**
### CATEGORY

Choose one

- [X] Bug Fix
- [ ] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY

This is a small change to check for an empty dataframe before accessing it by column name for processing. This allows charts to display an empty results message instead of a cryptic error message.

I also added my company to the README, which I hope is OK.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

Before:
Screen Shot 2020-05-10 at 9 43 56 AM

After:
Screen Shot 2020-05-10 at 9 45 01 AM

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by john-bodley** [comment]
@villebro we have these empty DataFrame checks for a subset of visualizations right now. I’m not certain how this ties in with SIP-38 or whether any viz types really support no data, but it seems like we should probably short circuit the logic somewhere upstream to prevent every method requiring said check.

**Comment by bryanck** [comment]
I did try handling it upstream first, checking before the `get_data` call in `BaseViz`, but some visualizations, such as FilterBox, didn't work with that approach, so I felt it was better to leave it in the viz handler function, at least for now in 0.36.

**Comment by villebro** [comment]
@bryanck did you ensure that all changed viz' worked correctly with the new logic? I would be inclined to merge this, as the "No Results" notification is much more intuitive than the myriad exceptions that tend to surface otherwise on legacy viz plugins.

**Comment by bryanck** [comment]
Yes we've been running with this change for a while

**Comment by bryanck** [comment]
I can create a new PR for 0.37 if you want, I have that applied to our fork

**Comment by villebro** [comment]
@bryanck please do 👍 Also, can you update this PRto add your company to the appropriate section in `INTHEWILD.md`? It has been added since this PR was originally opened (will require a rebase).

**Comment by bryanck** [comment]
Sure, this is done, I have a new PR up at https://github.com/apache/incubator-superset/pull/10361 so I'll close this one

**Pull request closed without merging**
