### PR TITLE
Apply ASF licenses throughout the code base

### PR DESCRIPTION
**Pull request by mistercrunch**
Wrote this https://github.com/mistercrunch/rodent and applied it to Superset codebase.

To address #6481 

TODO: add a `rodent check` to fail CI if missing a license

### CODE REVIEW

**Comment by mistercrunch** [comment]
914 files is more than I would have thought.

This is ready for review now.

**Review by john-bodley — APPROVED** [review]

**Review by kristw — APPROVED** [review]

**Review by phoenix24 — APPROVED** [review]

**Comment by bolkedebruin** [comment]
@mistercrunch JavaScript fails :-(

**Comment by bolkedebruin** [comment]
I think you need to be more careful with applying this:

- I checked "superset/assets/vendor/parallel_coordinates/d3.parcoords.js" which is BSD-3 licensed and this applies the AL 2.0 header. 
- Also cal-heatmap has a MIT license. 

Maybe there are more? I'm not entirely familiar with the code base yet.

**Comment by mistercrunch** [comment]
Oh right, the `vendor/` folder is special.

**Comment by bolkedebruin** [comment]
@mistercrunch almost there! Can I help?

**Pull request merged**
