### PR TITLE
test: creates storybook and tests for Tooltip component

### PR DESCRIPTION
**Pull request by michael-s-molina**
### SUMMARY
- Adds tests for the `Tooltip` component and a storybook entry with controls.
- `TooltipWrapper` wasn't adding any functionality on top of `Tooltip` so I updated all components to reference `Tooltip` and removed `TooltipWrapper`.
- Moves `Tooltip` component to its own folder

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Screen Shot 2021-02-17 at 3 57 02 PM

### TEST PLAN
1 - Execute all tests
2 - All tests should pass

@geido @rusackas @yardz

Acceptance testing can be done using Storybook.

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by ktmud — APPROVED** [review]
LGTM

**Review by rusackas — APPROVED** [review]
This is awesome! Thanks for all the great work here!

**Comment by rusackas** [comment]
@junlincc Tempted to just merge this, since it's basically safer than ever, but LMK if you want to poke around at some of the tooltips in the UI for signoff.

**Comment by junlincc** [comment]
yea @rusackas @ktmud please do merge test PRs soon if the code look alright. thanks for the PR and reviewing!

**Pull request merged**
