### PR TITLE
fix: Use Home page in SPA

### PR DESCRIPTION
**Pull request by EugeneTorap**
### SUMMARY
Move Welcome (Home) page into SPA. Use `GenericLink` for Welcome page.
If `LOGO_TARGET_PATH` is None we use React `Link` for it otherwise we html `<a> `

### BEFORE

https://user-images.githubusercontent.com/29536522/183296582-397a95ee-99c7-431c-b7b8-8c974237058c.mov

### AFTER

https://user-images.githubusercontent.com/29536522/183296852-6539723b-b770-45df-a5a8-725004eeb2a3.mov

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by EugeneTorap** [comment]
Can we simplify Home page's path and use `/home` instead of `/superset/welcome`?
What do you think @michael-s-molina @kgabryje @stephenLYZ?

**Comment by EugeneTorap** [comment]
Who knows how to fix such error in `Menu.test.tsx`:
`Error: Uncaught [Error: Invariant failed: You should not use <Link> outside a <Router>]`

**Comment by kgabryje** [comment]
> Can we simplify Home page's path and use `/home` instead of `/superset/welcome`? What do you think @michael-s-molina @kgabryje @stephenLYZ?

I'd rather not do it now to be honest... Last time we did that it turned out to be more problematic than we anticipated

**Comment by kgabryje** [comment]
> Who knows how to fix such error in `Menu.test.tsx`: `Error: Uncaught [Error: Invariant failed: You should not use <Link> outside a <Router>]`

Just add `useRouter` to `render` options, like
```
render(<Menu {...mockedProps} />, {
    useRouter: true,
});
```

**Review by kgabryje — APPROVED** [review]
LGTM!

**Review by kgabryje — CHANGES_REQUESTED** [review]
image

 Menu is missing from sql lab

**Review by kgabryje — APPROVED** [review]
LGTM

**Pull request merged**
