### PR TITLE
fix: native filter truncation rerendering loop on hover

### PR DESCRIPTION
**Pull request by diegomedina248**
### SUMMARY
This error was detected on a particular dashboard, for a particular set of conditions and only in chrome.

The truncation, in this case, refers to the right content of the `SCOPE` row.
Screen Shot 2022-05-11 at 01 12 00

The `useTruncate` function computes the truncated elements by trying to fit one element at a time in the with of their container.
Problem is, by using this information to truncate the element, and add the `+X` next to it, we're changing the container size, thus triggering another pass at this function.
This, in 99.9% of the cases is fine, but, in very subtle conditions, it can change the truncated count back and forth, if:
* the size taken by the `+X` removes the space needed by the last visible element by 1
* the subtle size gain by the `+(X - 1)` tag makes enough room for the removed element to appear again.

In this dashboard, the change was between +10 and +11, which has a very different pixel difference, but enough to cause the re-rendering loop.

This PR ensures we only compute the truncated elements if their size changes, or if the size of the parent of the container changes.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
For the reasons specified above, and given that the dashboard has private data, no gif is available.
Suffice to say, no change should be visible, the popup and truncation should remain the same for every other use case.

### TESTING INSTRUCTIONS
Ensure that the native filters popup content displays correctly, and that the truncation still works as expected.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by villebro** [comment]
Thanks for looking into this @diegomedina248 ! I ran into this a few times when testing something unrelated, and wondered if I did something weird that caused it.

**Review by kgabryje — APPROVED** [review]
Awesome fix and even better explanation! LGTM

**Comment by sadpandajoe** [comment]
🏷️ preset:2022.19

**Pull request merged**
