### PR TITLE
try to unbreak the javascript build

### PR DESCRIPTION
**Pull request by xrmx**
Still fails but later. Haven't checked the mapbox visualization though.

Current errors:
```
ERROR in dashboard.f423afa6c51d3cee7061.entry.js from UglifyJs

Unexpected token: name (Coordinate) [dashboard.f423afa6c51d3cee7061.entry.js:139050,6]

ERROR in explore.a49024d98f20924ba2b6.entry.js from UglifyJs

Unexpected token: name (Coordinate) [explore.a49024d98f20924ba2b6.entry.js:137502,6]
```

### CODE REVIEW

**Comment by mistercrunch** [comment]
Yeah I got about this far too :(

From what I understand UglifyJS chokes on ES6 code. I'm going to try other things today too. Those libs have been a huge amount of problem, I spent 4+ hours on this and it's driving me completely insane.

**Comment by xrmx** [comment]
@mistercrunch something along these lines maybe? https://github.com/joeeames/WebpackFundamentalsCourse/issues/3#issuecomment-226959684

**Comment by xrmx** [comment]
@mistercrunch it builds locally, i haven't run it and my knowledge of webpack is close to null. Please give it a try :)

**Comment by mistercrunch** [comment]
Oh I was working on that here too:
https://github.com/apache/incubator-superset/pull/3179

**Comment by xrmx** [comment]
@mistercrunch yours look cleaner :)

**Comment by xrmx** [comment]
Closing in favour of #3179

**Pull request closed without merging**
