### PR TITLE
revert(#17570): fix dashboard editing for dashboards with non-ascii characters

### PR DESCRIPTION
**Pull request by serenajiang**
### SUMMARY

The bug: When a user saved a dashboard that contained a chart with non-ascii characters, the json_metadata became malformed, causing the dashboard to fail to load. The root cause is in #17570, which added `positions` into the json_metadata blob. Something went wrong in the json parsing which causes json_metadata to be truncated if the positions json contains emojis or other non-standard characters.

The root cause PR is pretty large, so we had trouble figuring out where this goes wrong. I suspect the fix forward is some combination of
* Fix json parsing to handle non-ascii characters correctly
* Validate that json_metadata is well-formed before writing it
* Don't write the `positions` json, since it's already contained by a different column

Opening this revert PR as a starting point. This PR reverts #17570 and the accompanying #17707.

### TESTING INSTRUCTIONS

to reproduce bug:
* make dashboard
* add chart with emoji in title
* save dashboard
* see error after save
* refresh and see error on load

to verify this fix:
* make dashboard
* add chart with emoji in title
* save dashboard
* verify dashboard saved
* refresh and view dashboard

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

@geido @etr2460 @graceguo-supercat @rusackas

### CODE REVIEW

**Review by graceguo-supercat — APPROVED** [review]
LGTM.

I think we need to revert related PR from master ASAP.  After our recent release, all the newly updated dashboards, their position_json are inserted into json_metadata. It's troublesome to clean this up.

**Comment by kgabryje** [comment]
@serenajiang I can't reproduce the issue with the steps that you shared on current master (07bbe84). Is there any other way to trigger the bug?

https://user-images.githubusercontent.com/15073128/146165307-da027133-b23e-4afd-b865-97775dfe3fc4.mov

**Comment by kgabryje** [comment]
Confirmed with @zhaoyongjie and @villebro that they can't repro either 🙁

**Comment by geido** [comment]
@serenajiang @graceguo-supercat as hard as I tried I could not reproduce either. Do you have any additional information to help with reproducing the problem?

Please watch the video below. If we can reproduce it a fix might be a more desirable way to solve this problem and it might be as quick.

https://user-images.githubusercontent.com/60598000/146207191-82a7a9ee-8cb0-407d-abd6-2ca3ef8ea43e.mp4

**Comment by graceguo-supercat** [comment]
- for simple dashboard, once you edit dashboard and save it, you will see position_json column is inserted into json_metadata column, this is pretty easy to reproduce
- for large dashboard: 

1. set `SUPERSET_DASHBOARD_POSITION_DATA_LIMIT = 16777215`
2. create a large dashboard with charts and tabs, add emojis in tabs
3. make dashboard position_json > data is > 65k
4. edit dashboard, or save_as

**Comment by geido** [comment]
Hello @graceguo-supercat Erik gave us a hint that the limit might be the problem not the non-ascii characters as you just correctly pointed out. I have released a PR that removes the positions from the metadata as they are unnecessarily saved there and tagged you there. Thank you 🙏

**Comment by serenajiang** [comment]
@geido @kgabryje  We initially thought the size was the problem too, but we realized that it was emojis from repro with small dashboard. More specific repro instructions:
1. create dashboard
2. add chart to dashboard and edit the chart title (in the dashboard) to contain an emoji, OR add a header with an emoji in it
3. save dashboard

Removing positions should fix this problem, since afaik, there aren't any other ways for emojis to get in. Thanks for the PR!

**Pull request closed without merging**
