### PR TITLE
[sqllab] run only the part of the query that is selected

### PR DESCRIPTION
**Pull request by mistercrunch**
screen shot 2016-10-28 at 6 25 54 pm
screen shot 2016-10-28 at 6 25 46 pm
Fixes https://github.com/airbnb/caravel/issues/1427

### CODE REVIEW

**Comment by bkyryliuk** [comment]
Lovely, looks good to me!
🚀 

Do you plan to support run async the selected text?

**Comment by mistercrunch** [comment]
Async also works with selected text, just the same as `Run Query`

**Comment by ascott** [comment]
i'm curious about the color change for the buttons. i think updating only the text in the button should be enough of a ui update so users know they can run just the selected query. @mistercrunch what was your thinking with changing the color as well?

**Comment by mistercrunch** [comment]
The warning color was to draw attention that 1-the feature exists, and 2-that it's essentially a different button at this point, with a different behavior. I though of having a brand new extra button "Run Selection" that would be disabled when not selected, but with potentially "Run Query" and "Run Async" already, that multiplies the buttons to 4 buttons (+"Run Selection Async").

I think changing the button text only is too subtle. We need something very clear and perhaps more discoverable, though as it is currently (with the color) I feel like a user would discover the feature quite quickly, most likely in its first heavy session of usage.

I've seen UI features that will have a temporary "flash" to draw attention that something has changed, away from the action trigger, and go back to its final state quickly. An example of that type of UX would be if you add a TableElement, we could make its background yellow, fading back to default color over 3-5 seconds.

**Comment by ascott** [comment]
i can see your point about making it more obvious, but i think if someone is selecting part of the query with the intent to run just the selected part, and then looks at the run query button and and it now says `run selected query`, that would be clear enough. seems like this functionality is also fairly common so a user probably has an idea about it before the select part of the query.

**Comment by mistercrunch** [comment]
The color change augments the chance of catching the user's eye for this feature's discovery. The label change by itself on a button is pretty subtle, it'd be easy not to notice it. Are you concerned that the color change makes it look to "alarming"?

**Comment by ascott** [comment]
yeah, it seems to send a difference message with the warning color.. i also think it's usage is just not consistent with what is expected. in any case, i don't think we should spend more cycles on this for now, if you feel strongly about making the color change, let's leave as is. 👌

**Comment by whoishu** [comment]
queryEditorSetSql action seems no longer effective

**Pull request merged**
