### PR TITLE
refactor : Change menu name and reorder items

### PR DESCRIPTION
**Pull request by maloun96**
### SUMMARY
https://trello.com/c/gDvXud8G/43-explorechange-menu-label-and-order
change label "Explore Chart" to "View Chart in Explore"
Reorder items

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
BEFORE
image
AFTER
image

### TEST PLAN
1) Log in
2) Go to any Dashboard with charts
3) Click "..." on the chart

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [x] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by maloun96** [comment]
@junlincc @rusackas

**Comment by junlincc** [comment]
some typos...please check ticket in trello again🙏 @maloun96 

View Chart in Explore
Share Chart
Maximize Chart
Download as Image
Export CSV

**Review by junlincc — COMMENTED** [review]
some typos...please check ticket in trello again🙏 @maloun96

View Chart in Explore
Share Chart
Maximize Chart
Download as Image
Export CSV

**Comment by zuzana-vej** [comment]
I like the new order, thanks @junlincc. cc: @graceguo-supercat @ktmud

**Comment by maloun96** [comment]
@junlincc check it now!

**Comment by ktmud** [comment]
Are we using Trello for task management now? Because the link is a private board.

**Comment by rusackas** [comment]
> Are we using Trello for task management now? Because the link is a private board.

That's just being used internally, to mirror Github issues and add color to them, or to track/prioritize little odds and ends that are not on Github. That link isn't really relevant in this context. @maloun96 you might want to just remove it ;)

**Review by ktmud — APPROVED** [review]
It seems the AFTER screenshot is not accurate. But I like the changes in the code.

Can we also have consistent casing for "Share chart" (vs "Share Chart")?

**Comment by junlincc** [comment]
@maloun96 Thanks for fixing the typo. 
**NEW AFTER**
Screen Shot 2020-12-11 at 7 01 35 PM

However, the instruction in Trello is below -  capitalizing each word 
View Chart in Explore
Share Chart
Maximize Chart
Download as Image
Export CSV

I scanned through most of the menuitem in Superset and the casing is a MESS across the product... 
is there a standard for capitalizing (or not capitalizing) each word in the menuitem? if not, we SHOULD have one  @mihir174 

Screen Shot 2020-12-11 at 7 17 03 PM
Screen Shot 2020-12-11 at 7 16 38 PM
Screen Shot 2020-12-11 at 7 17 08 PM
Screen Shot 2020-12-11 at 7 21 55 PM

**Comment by rusackas** [comment]
Merging, as this fixes the acute issue. I'll open a new PR that capitalizes a few things, and we can expand on various capitalization cleanup items in there, with the input of @mirhir174

**Pull request merged**
