### PR TITLE
[SqlLab] Filter out unavailable databases

### PR DESCRIPTION
**Pull request by dmigo**
Problem this PR solves:
One always can see the whole list of databases in sql lab. Even those he has no access to.

### CODE REVIEW

**Comment by mistercrunch** [comment]
Thanks for the PR!

**Comment by dmigo** [comment]
@mistercrunch glad to help. It's just I wasn't 100% sure about if it should be `database_access` or `datasource_access `.

**Comment by john-bodley** [comment]
@dmigo @mistercrunch we sense the logic in this PR is invalid as we have Gamma role users who have access to specific datasources associated with a database but not the database itself and thus these users are no-longer able to access any of their datasources within SQL Lab. 

Could we either revert this PR or update the filter logic so that the whitelist set of databases were cognizant of the datasources. For the later it seems additional unit tests should be written to ensure we have coverage of various configurations.

**Comment by mistercrunch** [comment]
I'm ok either way, ask me if you want me to revert.

**Comment by john-bodley** [comment]
@mistercrunch would you mind reverting? @dmigo would you mind updating the filter logic w/ tests in another PR.

**Comment by dmigo** [comment]
@john-bodley no, I don't mind. 
My idea behind this PR was to hide the databases one doesn't have access to.
I'll create one more PR later today.

**Pull request merged**
