### PR TITLE
fix: Change url & add check for active item in menu

### PR DESCRIPTION
**Pull request by maloun96**
### SUMMARY
Add underline for Saved Query menu.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Before
image
After
image

### TEST PLAN
Log In
Navigate to SQL Lab -> Saved Queries, observer SQL Lab does not have underline border

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API
- [x] Fix https://github.com/apache/incubator-superset/issues/11874

### CODE REVIEW

**Review by junlincc — COMMENTED** [review]
the issue here is that the underline is not showing up consistently, it should show or not show the cyan underline, when hovering all the tabs and menu. my suggestion is to remove the underline completely, which is currently only showing on SQL Lab editor.

**Comment by maloun96** [comment]
@junlincc done. Now underline is removed

**Comment by rusackas** [comment]
@junlincc this seems to be fixing a smaller point of a bigger regression. The global nav used to have various hover effects including a background color and a neat little animated/expanding underline. Any idea when that disappeared entirely?

**Comment by junlincc** [comment]
yea, antd tabs do offer underlines .... need to pull 0.37 to see how it used to look.

**Comment by rusackas** [comment]
There are probably a bunch of CSS selectors in Emotion styles that are going "unheard" since they're trying to apply styles to the old NavItem components rather than the new ones, if those got migrated to antD.

**Comment by junlincc** [comment]
Looks like the background color is still there but only on Data and SQL Lab tabs, which have the dropdown menu. only sql editor has the underline left. but even that, this behavior is not consistent.

**Review by rusackas — APPROVED** [review]
Ok, we have other UI pizzaz to bring back, but I think this is a step in the right direction.

**Pull request merged**
