### PR TITLE
docs(alerts and reports): Update ExecutorType class

### PR DESCRIPTION
**Pull request by mrmooon**
### SUMMARY

I was setting up `ALERT_REPORTS_EXECUTE_AS` following the [current documentation ](https://superset.apache.org/docs/installation/alerts-reports/#detailed-config) and realized that the `Enum` was renamed from `ReportScheduleExecutor` to `ExecutorType` and moved into `superset.tasks.types` in https://github.com/apache/superset/pull/22328 by @villebro.

I've just updated that bit of the docs to reflect those changes and the comments in the `config.py` file.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Screenshots from the [_Alerts and Reports_ docs](https://superset.apache.org/docs/installation/alerts-reports/#detailed-config).

#### Before
before

#### After
after

### TESTING INSTRUCTIONS

[Spin up the local docs site](https://github.com/apache/superset/blob/master/CONTRIBUTING.md#local-development)

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by villebro — APPROVED** [review]
Thanks for fixing this and apologies for the oversight, I thought I had updated all relevant parts 🙁

**Comment by mrmooon** [comment]
> Thanks for fixing this and apologies for the oversight, I thought I had updated all relevant parts 🙁

No worries! it was cool for taking a look at the codebase 🙂 (and the ping was just intended for your visibility)

**Comment by villebro** [comment]
> No worries! it was cool for taking a look at the codebase 🙂 (and the ping was just intended for your visibility)

Great! 🙂 Thanks for pinging me, I might have missed this otherwise 👍 Btw, I tried to make this feature as generic and customizable as possible, but let me know if it doesn't fit your use case so we can see if we can extend it further.

**Comment by mrmooon** [comment]
> Great! 🙂 Thanks for pinging me, I might have missed this otherwise 👍 Btw, I tried to make this feature as generic and customizable as possible, but let me know if it doesn't fit your use case so we can see if we can extend it further.

Thanks! Yup! It looks great tbh, we're testing it atm but so far it has worked flawlessly 🚀

**Comment by cristian-cevasco** [comment]
@mrmooon @villebro Hey, folks. Thanks for updating the doc. I'm reaching out to ask if you have had the chance to test it as I'm getting the following error when adding the parameters for `ALERT_REPORTS_EXECUTE_AS`:
```
ModuleNotFoundError: No module named 'superset.tasks.types'
```
Checking in the repo I see the class `ExecutorType` declared in `superset/superset/tasks/types.py` so it looks OK, but somehow the workers trying to fetch it is not able to find it. Any feedback would be very much appreciated, thank you for your time.

**Comment by mrmooon** [comment]
Hey @cristian-cevasco! This feature will be part of version `2.1.0` which doesn't have a stable release for now (the third RC is currently being discussed). I wonder if it could be related to that, could you confirm that you're using that version, please? 🤔

**Pull request merged**
