### PR TITLE
Add 'Percent of previous' to sunburst vis. Appease npm warnings for data tables and d3.layout.cloud

### PR DESCRIPTION
**Pull request by williaster**
Requested by Dan Frank, agree it's useful to know the % of total (what was there previously) as well as the % of previous step when doing path analysis.

@mistercrunch @michellethomas 

screen shot 2016-03-31 at 10 59 24 am
screen shot 2016-03-31 at 10 59 02 am

### CODE REVIEW

**Comment by mistercrunch** [comment]
what about "parent" instead of "previous"?

**Comment by williaster** [comment]
:+1: I called it parent in the code ... totally agree.

**Comment by mistercrunch** [comment]
Oh looks like you need to rebase...

**Comment by williaster** [comment]
done.

**Comment by mistercrunch** [comment]
:+1:

**Pull request merged**
