### PR TITLE
feat: Export Chart to .xml format

### PR DESCRIPTION
**Pull request by exemplary-citizen**
### SUMMARY
This PR allows you to export charts to an xml file in the same manner we currently are able to with json and csv.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
image

### TEST PLAN
Added tests for the chart api in a similar flavor to the existing csv export tests.

### ADDITIONAL INFORMATION
Fixes the XML part of #14415 
- [x] Has associated issue: #14415
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [x] Introduces new feature or API
- [ ] Removes existing feature or API

cc @srinify @junlincc

### CODE REVIEW

**Comment by michael-s-molina** [comment]
@exemplary-citizen Thanks for this PR. Can you resolve the conflicts?

@villebro Can you enable CI?

**Comment by exemplary-citizen** [comment]
@villebro Can you enable CI when you get a chance?

**Comment by exemplary-citizen** [comment]
I don't think the cypress failure is related to the changes in this PR. The bubble test that is failing does seem to have a history of instability #11630. Other than that, the rest of CI should come back green.

**Comment by villebro** [comment]
Is there some specific use case for adding XML support? Since the data that's exported is mostly tabular, it feels like CSV and JSON should be adequate for most use cases. The reason I'm hesitant to add it is adding clutter to the already crowded chart header..

**Comment by exemplary-citizen** [comment]
Yeah XML is definitely a very popular format especially for data exchange and interoperability. There are also a bunch of tools that provide functionality for migrating XML documents to tables or datasets including:

- R's popular `XML` for simple, shallow structures
- SAS maintains the `libname xml` engine to read and write XML documents to/from SAS datasets
- Excel maintains the `Workbooks.OpenXML` method
- MySQL maintains the `LOAD XML` to parse XML data to/from database tables
- MS Access' object library (not database engine) maintains the `Application.ImportXML` and `Application.ExportXML` to import XML documents to/from database tables.

To alleviate your concern of adding clutter we could move all three buttons to an export dropdown like so:
image

**Comment by exemplary-citizen** [comment]
@villebro totally understand your concerns with regards to maintenance burden and am happy to proceed in whichever direction you think is best. I do think you should address the folks in https://github.com/apache/superset/issues/14415 that issue regularly gets bumped. 

Let me know if you think we should close this PR.

**Comment by villebro** [comment]
@exemplary-citizen with the recent redesign of chart actions in #19446, this feature wouldn't add any more clutter to the UI, which is a good thing. And since this is appears to be something very many people are eagerly awaiting, I don't want to be the person who blocks this feature. Also, given that many will be using it, I assume there will be a shared interest to maintain it, too. So feel free to rebase this, and I'll be happy to review and get this merged 🙂 👍

**Comment by rusackas** [comment]
Hi @exemplary-citizen - echoing @villebro sentiment here that there would be a lot of interest here if this could be rebased and brought back up to speed. Let us know if you have any intent to do so (or not). Thanks!

**Comment by justinpark** [comment]
@exemplary-citizen could you rebase the branch and re-push the commit if you still work on this?

**Pull request closed without merging**
