### PR TITLE
refactor: Unify all json.(loads|dumps) usage to utils.json

### PR DESCRIPTION
**Pull request by eyalezer**
#### Second phase of the json migration to use the new utils.json module

After completing the initial phase of creating the utils.json module as mentioned in the following link: https://github.com/apache/superset/pull/28522, we are now moving on to the second phase. This phase involves consolidating all json usage and transitioning to the utilization of the newly created module.

During this phase:
- Refactored all instances where json was being used and updated the references to utilize the json utils module.
- Made necessary additions and fixes to the tests to ensure their compatibility with the changes made.

### CODE REVIEW

**Comment by eyalezer** [comment]
@mistercrunch - here's the second part of the refactor, as expected this is a huge PR: 232 files changed but at least now all json usage is unified to use the utils.json 😅

**Comment by mistercrunch** [comment]
OMG glad to see this, happy to help fast-merge this since it'll conflict with everything else otherwise. 

Oh as a follow up, or maybe something we may want to bundle here -> @betodealmeida mentioned that there's a fairly easy way for us to add a linting rule that prevents people from doing simple `import json`, and force going through the wrappers in `superset/utils/json.py`

**Comment by eyalezer** [comment]
i'll rebase it quickly so it won't catch up more conflicts...

regarding the linter, it's a great idea and it looks like it should be plausible by adding a custom mypy plugin for example... but there's more research needed to be done here.

**Comment by betodealmeida** [comment]
@eyalezer I have this PR out, it's a pylint rule: https://github.com/apache/superset/pull/26803

We could do something similar for `json`.

**Comment by eyalezer** [comment]
@betodealmeida - awesome, so it's even easier than i thought... i'll look into it now and test it

**Review by mistercrunch — APPROVED** [review]

**Comment by mistercrunch** [comment]
Amazing, this is a massive refactor that should make everything json-related much more manageable. Interestingly python's  standard lib json IS simplejson (see here https://stackoverflow.com/questions/712791/what-are-the-differences-between-json-and-simplejson-python-modules), but simplejson is typically ahead. Also having json all in one place allows us to consider things like https://pypi.org/project/ujson/ and do things like what triggered this refactor (improve utf-8 support + error handling) centrally.

**Comment by eyalezer** [comment]
It's interesting that you brought it up. After I finished refactoring all the json.(loads|dumps) to utilize the json module, one of the first things I did was to check if ujson actually provides any significant performance enhancements to superset. it seems to be functioning fine, but I must admit that I haven't thoroughly tested it to accurately measure the extent of its performance improvements. Nevertheless, if anyone is interested in giving it a try, I still have the branch available here: https://github.com/eyalezer/superset/tree/ujson.

**Comment by geido** [comment]
Hey @eyalezer this is great. If you haven't, feel free to join the [Apache Superset](https://join.slack.com/t/apache-superset/shared_invite/zt-2be0drwz8-bxPfkdz28ozzk1Iox29ufg) Slack. I'd be happy to help if you wish to contribute more to the project!

**Pull request merged**
