### PR TITLE
fix(hive): Update _latest_partition_from_df in HiveEngineSpec to work on tables with multiple indexes

### LINKED ISSUE #14301: [connector:hive] extra_table_metadata fail for Hive partitioned table
Endpoint **/superset/extra_table_metadata** will fail with 500  when using with **partitioned tables** for **Hive**.
User will receive an error message like screenshot in SQL Lab.

Callstack point to error:
AttributeError: 'DataFrame' object has no attribute 'ix'

### Expected results

No error should popup

### Actual results

500 on the endpoint with partitioned Hive table.

#### Screenshots

image

#### How to reproduce the bug

1. Go to SQL Lab
2. Click on a partitioned table with Hive Database

### Environment

(please complete the following information):

- superset version: `>1.1 (current master)`
- python version: `3.7`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by codenamelxl**
### SUMMARY
Fix #14301

**DataFrame.ix** is deprecated so I replaced it with **.iloc**.
Since Hive return partition in form ds={partition name}/ds={partition name} for table with multiple indexes, I also change the logic to make it work for this case.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
BEFORE:
image

AFTER:
No more error

### TEST PLAN
- Choose a Hive partitioned table by multiple indexes.
- Check if /superset/extra_table_metadata return correct result with latest value of indexes.
* I tested this in Spark Thrift Server but should also be similar in Hive.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by dpgaspar — COMMENTED** [review]
Can you add a test please

**Comment by codenamelxl** [comment]
@dpgaspar Test added.  Seems this time I need approval for workflow to run.

**Comment by codenamelxl** [comment]
> Can you add a test please

Test added. Please let me know if there is anything else I can do.

**Review by dpgaspar — COMMENTED** [review]
Looks good, but CI is failing with
```
black....................................................................Failed
- hook id: black
- files were modified by this hook

reformatted /home/runner/work/superset/superset/tests/db_engine_specs/hive_tests.py
All done! ✨ 🍰 ✨
1 file reformatted, 732 files left unchanged.
```

Use `pre-commit` for fix that automatically

**Comment by codenamelxl** [comment]
Thank you for the pointer. I have fixed formatting to pass black. Hope CI will green now.

**Comment by codenamelxl** [comment]
CI failing with:
`superset/models/dashboard.py:174:0: W0125: Using a conditional statement with a constant value (using-constant-test)`
seems not related to this PR.

**Comment by codenamelxl** [comment]
> CI failing with:
> `superset/models/dashboard.py:174:0: W0125: Using a conditional statement with a constant value (using-constant-test)`
> seems not related to this PR.

I rebased to master to try make CI green.

**Comment by codenamelxl** [comment]
@dpgaspar Sorry for direct tag.
Would you mind taking a look at this. I think the test failed is not related to this PR. 
Thank you.

**Comment by villebro** [comment]
@codenamelxl sorry for the delayed review, but I agree with the proposed change here. Would you mind rebasing this PR so we can get it merged?

**Review by villebro — APPROVED** [review]
LGTM, thanks for the improvement!

**Comment by codenamelxl** [comment]
Thank for the rebase. Sorry for the late reply.

**Pull request merged**
