### PR TITLE
fix(explore): highlight Run button correctly when query is stale

### LINKED ISSUE #15948: [explore][dnd] Run button doesn't appear in chart area when viz type or column value changes
When user changes viz type or uses drag and drop to add a column, "Run" button doesn't show up in chart area. It works for adhoc metrics and filters, but not for column type controls.

### Expected results
"Run" button always appears in chart area when data is dirty

### Actual results
"Run" doesn't appear when viz type or column type control (like groupby) changes

#### Screenshots

https://user-images.githubusercontent.com/15073128/127531715-11889a54-c623-4483-9a5e-d0ce5ecbd7a3.mov

#### How to reproduce the bug

1. Enable drag and drop
2. Create a chart
3. Change viz type - "run" button should appear but it doesn't
4. Drop column in a control that accepts columns, like groupby in table chart - "run" button should appear but it doesn't

### Environment

latest master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

CC @junlincc @jinghua-qa

### LINKED ISSUE #15973: [explore]RUN in chart area is missing + Run in panel is not highlighted on switching viz
### Expected results

when change chart type, run button should show and the "run" in data panel should be highlighted

### Actual results

when change chart type, run button not showed and the "run" in data panel  is not highlighted

#### Screenshots

https://user-images.githubusercontent.com/81597121/127630867-80b8c909-0b2e-4b5e-b3c6-eaf5f7d737eb.mov

#### How to reproduce the bug

1. open a chart
2. Click chart type and change to another chart 
3. See error

### Environment

(please complete the following information):

- superset version: `master`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by suddjian**
### SUMMARY

In the staleness logic, it was only looking at the changes in controls since the last render of the explore container, when actually it should look at changes since the last query.

This also fixes a number of other cases where changing the value of a control did not prompt running the query.

### AFTER

https://user-images.githubusercontent.com/1858430/127717685-2ae7b0ba-8681-4433-88b3-c7512164be63.mov

### TESTING INSTRUCTIONS

Open explore, change controls around, see run button light up.

### ADDITIONAL INFORMATION

- [x] Has associated issue: fixes #15973 fixes #15948
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by rusackas — APPROVED** [review]
LGTM

**Comment by jinghua-qa** [comment]
Can I test this PR with dd feature flag on? The previous reported issue is dd related

**Review by jinghua-qa — APPROVED** [review]
LGTM!

https://user-images.githubusercontent.com/81597121/127724113-76cacb1b-cb25-480e-99b0-2b3dbcf7cec0.mov

**Comment by villebro** [comment]
Awesome work!

**Pull request merged**
