### PR TITLE
chore: Improve Japanese translation

### PR DESCRIPTION
**Pull request by tesshy**
### SUMMARY

- Improve Japanese translation, focus on Dashboard view.
  - Some Japanese translations was not matched, so that we improve it with manual work

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [x] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by villebro — APPROVED** [review]
Thanks @tesshy so much for this! 🗾

**Comment by junlincc** [comment]
@tesshy really appreciate your contribution! would you mind getting all tests passed?

**Comment by tesshy** [comment]
@junlincc Yep, and we use this translation currently at ver.1.0

**Comment by villebro** [comment]
@tesshy would you mind rebasing the PR? It seems this might have been cut at a time when there was a bug in the codecov configuration in CI, and that's blocking me from merging the PR.

**Comment by tesshy** [comment]
@villebro sure, I'll rebase and test it.

**Comment by villebro** [comment]
Thanks so much @tesshy!

**Pull request merged**
