### PR TITLE
chore: drop deprecated 'pkg_resources' and 'imp' in favor of importlib

### LINKED ISSUE #23899: package 'pkg_resource' is deprecated in favor of importlib
The package `pkg_resource` is officially deprecated in favor of importlib: https://setuptools.pypa.io/en/latest/pkg_resources.html

> Use of pkg_resources is discouraged in favor of [importlib.resources](https://docs.python.org/3/library/importlib.html#module-importlib.resources), [importlib.metadata](https://docs.python.org/3/library/importlib.metadata.html), and their backports ([resources](https://pypi.org/project/importlib_resources), [metadata](https://pypi.org/project/importlib_metadata)). Please consider using those libraries instead of pkg_resources.

### PR DESCRIPTION
**Pull request by sebastianliebscher**
#### pkg_resources

The use of package `pkg_resources` is [deprecated in favor](https://setuptools.pypa.io/en/latest/pkg_resources.html) of `importlib`.
This PR makes changes according to the importlib [migration guide](https://importlib-resources.readthedocs.io/en/latest/migration.html).

Note: **This PR uses [importlib.resources.files](https://docs.python.org/3/library/importlib.resources.html#importlib.resources.files) which was introduced in Python 3.9. So Superset will be constrained to Python >=3.9.**

#### imp

This PR also drops [deprecated](https://docs.python.org/3/library/imp.html) imp in favor of importlib.

Resolves https://github.com/apache/superset/issues/23899

### TESTING INSTRUCTIONS
`./scripts/tests/run.sh`

### ADDITIONAL INFORMATION
- [x] Has associated issue: fixes https://github.com/apache/superset/issues/23899
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by EugeneTorap** [comment]
Hello @sebastianliebscher! Thank you for the contribution.
Can we also use `importlib` instead of `import imp # pylint: disable=deprecated-module` ?

> the imp module is deprecated in favour of importlib and slated for removal in Python 3.12

Also use `setuptools ` instead of `distutils` and `numpy.distutils` module

> The distutils package is deprecated and slated for removal in Python 3.12
`numpy.distutils` is deprecated since NumPy 1.23.0

**Comment by EugeneTorap** [comment]
Hi @sebastianliebscher! Do you have an account in superset slack?

**Comment by sebastianliebscher** [comment]
@EugeneTorap it seems the link to join Supersets Slack is no longer valid, at least for me. https://github.com/apache/superset/blob/master/README.md?plain=1#LL138C32-L138C65

**Comment by EugeneTorap** [comment]
@sebastianliebscher Use this one - https://join.slack.com/t/apache-superset/shared_invite/zt-1mh158vmv-y67mOpmxjJyOKmJTUmYGhw

**Comment by rusackas** [comment]
> @rusackas Can we fix the invite link?

Thanks for pointing this out. It's fixed now.

**Comment by sebastianliebscher** [comment]
@EugeneTorap This PR also drops imp in favor of importlib.

**Comment by sebastianliebscher** [comment]
Removing `distutils` is in another PR: https://github.com/apache/superset/pull/24001 @EugeneTorap

**Comment by sebastianliebscher** [comment]
I used an importlib function (.select for entrypoints) only available in Python 3.10, so this is still a draft. Maybe I figure out how to do this with Python 3.9.

**Comment by sebastianliebscher** [comment]
Superseded by https://github.com/apache/superset/pull/24514 and https://github.com/apache/superset/pull/24578. Great work @cwegener!

**Pull request closed without merging**
