### PR TITLE
fix: Validate jinja rendered query

### PR DESCRIPTION
**Pull request by geido**
### SUMMARY
The query wasn't validated with the rendered Jinja template. This fix passes the rendered query down to the validator.

### TESTING INSTRUCTIONS
1. Create a query in SQLlab using Jinja params for the schema
2. Restrict access to the schema
3. Verify that the user with the restricted access cannot query the schema when using Jinja params

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by dpgaspar — COMMENTED** [review]
add a test asserting the validation is now performed after the sql statement is templated

**Review by eschutho — APPROVED** [review]
LGTM!

**Review by jinghua-qa — APPROVED** [review]
Tested schema access deny with Jinja and it show correct error msg
Screen Shot 2023-02-17 at 9 53 04 AM

**Comment by eschutho** [comment]
I had to pull this PR out of 2.1.0 because of some integration errors. We can try to pull it into 2.1.1.

**Pull request merged**
