### PR TITLE
feat: Save datapanel state in local storage

### PR DESCRIPTION
**Pull request by kgabryje**
### SUMMARY
This PR implements persisting datapanel size  and open/close state in local storage. When user opens explore page again, state from local storage will be used; if local storage is empty, default values will be used (data panel closed, split sizes 90%/10%).

CC: @junlincc @villebro

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
https://user-images.githubusercontent.com/15073128/107207795-079a5b00-6a01-11eb-9c0f-f898a122b9e4.mov

### ADDITIONAL INFORMATION

- [x] Has associated issue: closes https://github.com/apache/superset/issues/12852
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by junlincc** [comment]
welcome back @kgabryje!!!thanks for opening the PR! we need to get you back on Slack too! 🎉 
This is a good step! not sure if we should store table tab and page in local storage as well? @vylc wdyt? 

@nikolagigic @pkdotson please help review! 

https://user-images.githubusercontent.com/67837651/107244717-2f7ac600-69e3-11eb-9b68-b9ff3bd1964c.mov

**Review by nikolagigic — APPROVED** [review]
LGTM

**Review by vylc — APPROVED** [review]
looks good!

**Review by pkdotson — APPROVED** [review]
LGTM!

**Review by rusackas — APPROVED** [review]
LGTM!

**Review by junlincc — APPROVED** [review]
approve as product sign-off ✅ Thanks for the PR! ♥️
we may wanna make tab and pagination sticky in the future, but may affect performance.

**Comment by rusackas** [comment]
@nikolagigic @ktmud I like that there's now a getter/setter for LocalStorage available to anything. We could use this in lots of other places (like the expanding/contracting of Explore sidebars, other collapsible things, etc). We could also extend that helper/util to fall back to Cookies if LocalStorage is not available. If there's any contention around LocalStorage or Cookies, this would also be a central place to set feature flags.

**Pull request merged**
