### PR TITLE
fix(cypress): wait for filterValues request

### PR DESCRIPTION
**Pull request by nytai**
### SUMMARY

Seeing a lot of cypress failures for `explore/AdhocFilters` test. 🤞 this makes it less flaky. 

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

N/A 
### TEST PLAN

ran the cypress check 3 times without failures... seems to be an improvement 

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by ktmud — APPROVED** [review]
LGTM! On a separate note, I'm actually seeing a lot of errors related to Dashboard CRUD view in my personal fork: https://dashboard.cypress.io/projects/ukwxzo/runs/440/failures The fork runs the exactly same code, it just records the runs to Cypress dashboard. Have you seen anything similar before?

**Comment by mistercrunch** [comment]
I'm seeing codecov download/uplaod step in cypress trigger :/ Let's get CI back on track!

popeye

**Comment by mistercrunch** [comment]
Screen Shot 2020-09-14 at 10 51 34 PM

**Comment by nytai** [comment]
@ktmud Most of the cypress ci failures I've been seeing have been in `AdhocFilters` test. Have you noticed flakiness in the dashboard CRUD views tests in this repo? Seems quite strange that it would be happening in your fork but not in this repo

**Comment by villebro** [comment]
Big thanks @nytai, I was wondering why my one-liner doc PR was failing miserably on CI 😄

**Comment by ktmud** [comment]
@nytai  Yeah, it's really strange that it only fails in my fork but it shouldn't really matter if it's not happening for everyone else.

Although I was still seeing `AdhocFilters` failing after rebasing to this fix: https://github.com/apache/incubator-superset/pull/10837/checks?check_run_id=1119508451

So I made another attempt to fix it: https://github.com/apache/incubator-superset/pull/10837/commits/4477fdd5a1ecdbc4eeaa8ceb8575d729bd2960c8

Based on my previous experience, there seems to be some flakiness related to `cy.get(...).within(...)` so I removed the `within` calls.

**Comment by nytai** [comment]
Yup.... also got a random failure for the `dashboard/list_view.test.ts` on https://github.com/apache/incubator-superset/pull/10892/checks?check_run_id=1119843982 seems there's still quite a bit of flakiness in the suite.

**Pull request merged**
