### PR TITLE
fix: sync package-lock.json

### PR DESCRIPTION
**Pull request by nytai**
### SUMMARY

It seems our package-lock.json has fallen out of sync with package.json. Most likely someone didn't commit the changes to this file.

### CODE REVIEW

**Comment by nytai** [comment]
codecov makes no sense

**Comment by mistercrunch** [comment]
merge conflict :(

**Review by etr2460 — COMMENTED** [review]
is this an actual issue? i remember seeing these resolved params bounce back and forth for a while with some other PRs i think?

note that master ci passed the Frontend checks, it was a mysql test that failed i think

**Comment by nytai** [comment]
hmm, it may be a discrepancy in npm versions or something. The changes are insignificant. I've been noticing changes in package-lock.json every time i run `npm install` but if I'm the only one seeing this then I'll continue to discard those changes.

**Comment by villebro** [comment]
I've been noticing the same, I believe it's an npm version thing where the convention changed recently changed and people are on different minors. Perhaps we should lint the lock file, too? 😄

**Pull request closed without merging**
