### PR TITLE
Add yarn.lock

### PR DESCRIPTION
**Pull request by timifasubaa**
I'm making some improvements to our Dockerfile to better take advantage of the cache. Having a yarn.lock file will make that possible. It is also recommended in the yarn documentation  ( https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/ last line). 
Why was it removed in the first place? Is it a good idea to have it here?
I made sure to pull the latest superset version and run yarn before including the yarn.lock file
@graceguo-supercat @john-bodley  @mistercrunch

### CODE REVIEW

**Review by graceguo-supercat — APPROVED** [review]
LGTM

**Comment by mistercrunch** [comment]
Do we need instructions on `CONTRIBUTING.md` related to this?

**Comment by timifasubaa** [comment]
@mistercrunch Sure. I'll be happy to add. The instructions would be something along the lines of updating the yarn.lock file whenever you add a new javascript dependency? Anything else you would want me to add?

**Comment by timifasubaa** [comment]
https://github.com/apache/incubator-superset/issues/4274

**Pull request merged**
