### PR TITLE
fix(Edit Chart): mixed time series chart: The secondary y-axis title is disguised/misplaced

### PR DESCRIPTION
**Pull request by webobite**
### SUMMARY

Fix(Edit Chart): mixed time series chart: The secondary y-axis title is disguised/misplaced

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

This fix is for the following issue raised: https://github.com/apache/superset/issues/18235
Pls feel free to share your feedback for the same.
**Before Change:** 
Scenario 1: 
Scenario 2: 
image

**After change :** 
As per the control change for `Y-Axis Title Position,` The y-axis title should be displayed to the Left or top.
As I can see It has a single control for Primary Y Axis Title Position control.
something like this: - 
I made the change on my local and was able to come up with these scenarios
Scenario 1 :
image
Scenario 2: 
image

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API
Thanks and Regard
Subham ([webobite](https://github.com/webobite))

### CODE REVIEW

**Comment by justinpark** [comment]
@webobite Thanks for the update. Since one control changes the both orientation, could you change the label "Left" to something generic term like "Side" instead?

**Comment by webobite** [comment]
Sure Let me check the same, For the Migration script Where to find the some heads-up docs for the same. @justinpark

**Comment by sfirke** [comment]
This is a great improvement, thank you @webobite !  Do you need guidance to make the changes requested by @justinpark ?

**Comment by geido** [comment]
Thanks. This was fixed here https://github.com/apache-superset/superset-ui/pull/1351

**Comment by eYbulani** [comment]
> Thanks. This was fixed here [apache-superset/superset-ui#1351](https://github.com/apache-superset/superset-ui/pull/1351)

It has fixed for only primary y axis title position, the secondary y axis position is still doesn't moves with the Y-Axis Title Position. Please merge these changes also, this will be helpful

**Pull request closed without merging**
