### PR TITLE
fix: making the new chart/dashboard buttons on the homepage work

### LINKED ISSUE #12346: [Home] +DASHBOARD and +CHART button don't work
ezgif-4-6d28580b6945

Expected behavior:
when users click +DASHBOARD, it takes users to empty dashboard edit mode
when users click +CHATR, it takes users to Create a new chart page

ezgif-4-e468e13b54d2

### PR DESCRIPTION
**Pull request by rusackas**
### SUMMARY

The code was previously using history.push, which wasn't working... window.location.assign works like a charm though!

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

n/a

### TEST PLAN

Tested locally, but others can/should/will verify

### ADDITIONAL INFORMATION

- [x] Has associated issue: Fixes #12346 
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by nytai** [comment]
Jinx! https://github.com/apache/superset/pull/12348

**Comment by rusackas** [comment]
> Jinx! #12348

Hah! That is one _beautiful_ PR you have there, if I may say so myself.

**Review by nytai — APPROVED** [review]
This because we're living in the confusing world where only half our app is in react router 😞

**Comment by rusackas** [comment]
> This because we're living in the confusing world where only half our app is in react router 😞

... just for now... it'll get better.

**Comment by junlincc** [comment]
impressive you both~ im pulling......

**Review by junlincc — APPROVED** [review]
ezgif-6-92f1b642d122

thank you both @rusackas @nytai !!

**Pull request merged**
