### PR TITLE
fix: added parser to parse request referer url for url_param (issue_id : 13315)

### LINKED ISSUE #13315: Unable to Use Jinja Context for "url_param"
### Expected results

It gives 'rangga' as the parameter of username in url

### Actual results

It returns None

#### Screenshots

image

#### How to reproduce the bug

0. Activate your jinja context in superset/docker/pythonpath_dev/superset_config.py by adding "ENABLE_TEMPLATE_PROCESSING" : True in dictionary of FEATURE_FLAGS
image

1. Go to sqllab
2. Edit your url and add '?username' argument
3. Reload the page
4. Write the query using jinja context of url_param and run the query

### Environment

(please complete the following information):

- superset version: 1.0.1 (docker version)
- python version: 3.7.9

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by celestialmechanic21**
### SUMMARY
I have added code to parse request's referer url to get query params for `url_param` function used is sql editor.
[Link to issue](https://github.com/apache/superset/issues/13315)

closes #13315 

### TEST PLAN

Added test case for change

### ADDITIONAL INFORMATION

- [x] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by junlincc** [comment]
@robdiciuccio 🙏

**Comment by robdiciuccio** [comment]
Thanks for opening a PR @celestialmechanic21! 

Rather than relying on the Referer header, it may make more sense to pass the query params directly on the XHR request, as this would be more explicit.

@villebro @dpgaspar @betodealmeida any additional context on this?

**Comment by maltoze** [comment]
Opened another pr to fix this. #15246

**Comment by villebro** [comment]
Closing as this has been superseded by another fix PR.

**Pull request closed without merging**
