### PR TITLE
fix(Explore): Adjust width of cell in Time-Series Table chart

### LINKED ISSUE #15957: Time Series Table Numbers are cut off
The numbers on the edges of a time series table sometimes may get cut off. It would seem like they should properly fit within the container size and not get cut off. Maybe a potential solution would be to alter the spacing between the graph and table text. 

Screen Shot 2021-07-29 at 2 09 47 PM

### PR DESCRIPTION
**Pull request by geido**
### SUMMARY
It adjusts the width of the cell in the Table to be just enough to show the full chart.

Fixes #15957

### BEFORE
Screen Shot 2021-08-05 at 17 59 12

### AFTER
Screen Shot 2021-08-05 at 17 57 30

### TESTING INSTRUCTIONS
1. Open a Time-Series Table chart in Explore
2. Configure the Time Series Columns with  type Sparkline
3. Run the query
4. Make sure the chart is appearing fully and no numbers are cut

### ADDITIONAL INFORMATION

- [x] Has associated issue: #15957
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by junlincc** [comment]
LGTM! Thanks for the fix! 
https://user-images.githubusercontent.com/67837651/128414433-f87fe5b3-0377-4e95-abe0-8fa95d89b698.mov

**Review by suddjian — APPROVED** [review]
LGTM

**Comment by rosemarie-chiu** [comment]
🏷 2021.31

**Pull request merged**
