### PR TITLE
chore: set up ruff as a new linter/formatter

### PR DESCRIPTION
**Pull request by mistercrunch**
### SUMMARY
Ruff is great, and it's fast. All the cool kids are using it. 

#edit -putting my latest comment as PR body:

This PR is meant as an experiment around whether it would make sense to add this package as part of the stack. I'll try and summarize my findings and recommendation after playing with it. 

relevant: https://docs.astral.sh/ruff/faq/

Early impression are:

#### on the positive:
- super fast and centralized in a comprehensive CLI (pretty much fully replaces pycln, pyupgrade, isort, black)
- simplifying the code quality stack quite a bit. Many of those tools themselves are adopting `ruff` (pylint uses in its repo for instance). There's fair amount of cognitive load in dealing with disjointed tools with their own cli, config and quirks.
- powerful / convenient features like `--add-no-qa` `--ignore-noqa` and `--fix`
- it's taking over the python code-quality world fast, federating everything in a nifty, comprehensive toolkit

#### on the negative:
- while it covers at lot, it's intricately incomplete, pylint is the less covered source where it cannot replace it fully at this time, for the others, it seems like ruff is "enough of a replacement" to justify rip & replace - here I'm thinking disabling duplicate rules with pylint might speed pylint sifnificantly
- I hit some infinite linting loops and deadends in some area, pushing me to disable black, isort and pyupgrade. Our codebase is large, and while ruff is 99% compatible with all this, 1% is still a significant thing
- this won't replace pylint as the coverage is still too low and pylint is powerful. I was thinking we may be able to disable rules in pylint that are covered and speed it up in the process

Overall I think the recommendation is likely to be "we should do this now" or "we should probably revisit in a little while", will update here once I form an opinion.

### CODE REVIEW

**Comment by villebro** [comment]
Wait what, black is no longer the new black? I took a look at ruff, pretty great perf and overall promises. But let's test this carefully, as even many mature linters fall apart on the Superset codebase..

**Comment by john-bodley** [comment]
It seems like perf is a big sell, 

> ⚡️ 10-100x faster than existing linters (like Flake8) and formatters (like Black)

however I think Black only takes a few seconds to runs and thus any speed up is irrelevant from a UX perspective in my mind. I've never once thought "you know the main problem with Black is that it's too slow".

@mistercrunch would you mind including some links as to why we should be adopting this over Black et al.? Sure some of the auto-formatting looks great—including being more opinionated about blank lines—however on the flip side the one import per line (with the addition of the `# noqa: F401` comment) seems—per the package name— a tad ruff.

**Review by hughhhh — APPROVED** [review]
+1 to @mistercrunch comments on upgrading to this package.

@john-bodley for formatting >99.9% compatible to black reading the release statements

> Optimized for adoption. Ruff’s formatter is designed as a drop-in replacement for Black. On Black-formatted Python projects, Ruff achieves >99.9% compatibility with Black, as measured by changed lines. When formatting the Django codebase, for example, Ruff and Black only differ on 34 out of 2,772 files. Focusing on compatibility enables projects to adopt the Ruff formatter with minimal disruption.
https://astral.sh/blog/the-ruff-formatter#

**Comment by mistercrunch** [comment]
This one will conflict with everything (touching 574 files), I'd love to merge quickly(!)

**Comment by mistercrunch** [comment]
Great resources here too -> https://docs.astral.sh/ruff/faq/

For those interested in the story behind the project -> https://www.youtube.com/watch?v=LCva0NOM2-o

**Review by betodealmeida — APPROVED** [review]
Let's do this!

**Comment by mistercrunch** [comment]
roadrunner-beep

**Comment by andy-clapson** [comment]
@mistercrunch did you try out `uv` ever? same folks and pretty wicked too.

**Comment by mistercrunch** [comment]
@andy-clapson first I hear of it, but OMG if this delivers on its promises THE FUTURE IS HERE. Oh is it the same dude!? Yes!

**Comment by mistercrunch** [comment]
For the record, I opened an issue asking about our use cases -> https://github.com/astral-sh/uv/issues/5487

**Comment by andy-clapson** [comment]
Yeah, we started using it a few months back and it's extremely fast.
`pip-compile-multi` is new to me, though - I'm less sure about that.

**Pull request merged**
