### PR TITLE
style: various little tweaks to home screen stylin'

### PR DESCRIPTION
**Pull request by rusackas**
### SUMMARY

Shadows were getting cut off... this PR adds a little more room for them, as we did with other cards. This also adds a little gutter room between sections, which is nice... and is now more consistent!

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

Before:
image

After:
image

### TEST PLAN

👀 visual sanity check.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [x] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by ktmud** [comment]
It seems the body and the welcome page have different background color.

**Comment by ktmud** [comment]
While we are at it, could we also adjust the margins of the empty state placeholders so that they are more or less vertically aligned in the middle?

**Comment by junlincc** [comment]
all good points.. how did we missed all these issues... @Mihir174 let us pay better attention to details at design/product sign off 🙏 thank you for point out! @ktmud

**Comment by rusackas** [comment]
> 
> 
> While we are at it, could we also adjust the margins of the empty state placeholders so that they are more or less vertically aligned in the middle?

Done (flexbox to the rescue, as always!):
image

**Comment by nytai** [comment]
just checked out this branch, also noticed a couple of things:

looks like a border-radius is needed on some of these new borders 
Screen Shot 2020-11-10 at 2 28 30 PM

long dashboard names seem to to cause variations in card size
Screen Shot 2020-11-10 at 2 28 39 PM

**Review by ktmud — APPROVED** [review]
Thanks for the quick fixes!

**Comment by rusackas** [comment]
> just checked out this branch, also noticed a couple of things:
> 
> looks like a border-radius is needed on some of these new borders
> Screen Shot 2020-11-10 at 2 28 30 PM
> 
> long dashboard names seem to to cause variations in card size
> Screen Shot 2020-11-10 at 2 28 39 PM

image

image

Card radii updated.

**Comment by rusackas** [comment]
> > just checked out this branch, also noticed a couple of things:
> > looks like a border-radius is needed on some of these new borders
> > Screen Shot 2020-11-10 at 2 28 30 PM
> > long dashboard names seem to to cause variations in card size
> > Screen Shot 2020-11-10 at 2 28 39 PM
> 
> image
> 
> image
> 
> Card radii updated.

Thumbnail was covering the border radius... overflow property fixes that too now:
image

**Comment by rusackas** [comment]
@nytai @ktmud Regarding Tai's layout issue, I think we need to take another look at the card layout... it's got a few other issues around responsiveness that I'm not stoked on. But that's a tougher game than these other easy wins. 

Any other small tweaky things, or shall we merge this batch o' fixes?

Thanks for the fresh eyes on this!

**Comment by nytai** [comment]
👍 thanks for fixing the border radii, your css-fu is strong. Totally ok with punting on the card layout stuff, it's not exactly an easy fix. I think we're also waiting for a design for smaller cards as the consensus is that there should be more information density in these views.

**Review by nytai — APPROVED** [review]

**Pull request merged**
