### PR TITLE
Use correct dialect for escaping functions.

### PR DESCRIPTION
**Pull request by steveniemitz**
Column functions are currently escaped with the
same dialect that is being used by Superset for its
metadata storage.  Instead the dialect of the target
table should be used when escaping column names.

### CODE REVIEW

**Comment by xrmx** [comment]
Does this fix any issue in particular?

**Comment by steveniemitz** [comment]
It fixes superset generating invalid SQL when the two dialects don't agree on quoting rules.

**Comment by mistercrunch** [comment]
Gotcha, it was using the metadata db's dialect. Thanks for the PR

**Comment by steveniemitz** [comment]
Thanks!  I'll probably have some more coming soon :)

**Pull request merged**
