### PR TITLE
Update messages.json

### PR DESCRIPTION
**Pull request by magicansk**

### CODE REVIEW

**Comment by xrmx** [comment]
Please don't open a new PR for each file you want to update. Especially if you are duplicating work already done.

**Comment by magicansk** [comment]
Hey, I'm not going to open PR for each update and it is not a duplicate work man. Just knew that there is a reference to translation!

**Comment by xrmx** [comment]
You already opened two PR when it should have been one at most :) and how is this not duplicate work of #3174 since you are touching the very same files?

**Comment by magicansk** [comment]
Well, I didn't notice that I commit the "very" same files as you said. For different files, there is the different part that has been translating. But I think what you wanna said is for Chinese translation part reference to the earlier PR.
for #3714 superset/connectors/druid/models.py 
for #3715  superset/translations/zh/LC_MESSAGES/messages.po
for #3716 superset/translations/zh/LC_MESSAGES/messages.json

**Pull request merged**
