### PR TITLE
refactor(Avatar): Migrate Avatar to Ant Design 5

### LINKED ISSUE #30726: Ant Design 5: Upgrade Avatar component
Please refer to SIP-139 https://github.com/apache/superset/issues/29268.

The `Avatar` component should be upgraded to Ant Design version 5.

Similar work has been completed [here](https://github.com/apache/superset/pulls?q=is%3Apr+label%3Afrontend%3Arefactor%3Aantd5+is%3Aclosed).

When upgrading the component to Ant Design 5, please ensure to include:

- Proper RTL test coverage if not present yet.
- A Storybook file (if not present) or all necessary changes.
- Include all relevant component options in the Storybook.
- Clean up unnecessary custom styles.

When opening a PR:
- Name your PR refactor({Component}): Upgrade {component} to Ant Design 5
- Add screenshots of BEFORE/AFTER in your PR.
- Update the [project tracker](https://github.com/apache/superset/discussions/29293) when your PR is merged.
- Make sure you or a committer has labeled your PR with [frontend:refactor:antd5](https://github.com/apache/superset/pulls?q=is%3Apr+label%3Afrontend%3Arefactor%3Aantd5+is%3Aclosed).

### PR DESCRIPTION
**Pull request by msyavuz**
### SUMMARY

Migrate Avatar to Ant Design 5 while maintaining visual consistency.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

Before:
avatar-before
After:
avatar-after

### TESTING INSTRUCTIONS

Test if there are visual changes in-app or storybook.

### ADDITIONAL INFORMATION

- [x] Has associated issue: Fixes #30726 
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by geido** [comment]
Thanks for the PR @msyavuz. I noticed that something is off when you have multiple avatars. The number is misaligned and hovering seems also to be broken (the arrow shows as a dark square). This is on Chrome. It does not happen on master.

Screenshot 2024-10-31 at 15 46 03

Screenshot 2024-10-31 at 15 46 13

**Comment by msyavuz** [comment]
@geido Issue was importing from `antd-v5/lib`. I fixed it but we should be careful with other components in the future as well.

**Review by geido — APPROVED** [review]
Thanks for this!

**Pull request merged**
