### PR TITLE
[formats] add better defaults for time + number formatting

### PR DESCRIPTION
**Pull request by williaster**
This PR is all about making better default for time + number formatting 🚀  It adds:

- a more concise multi-format tick formatter. Here is the before and after (and you can play with it in [this observable notebook](https://beta.observablehq.com/d/cb85a1708c711939)):
  image 1

- sets most default number formats to 1 decimal place instead of 3
- reduces the number of y-axis ticks (to ~5), there is no need for ~10+ that nvd3 sets by default
- rich tooltip => false by default, this makes tooltips look pretty bad, you can still hover over individual lines to see their values, or toggle on rich tooltips if you want them.

@mistercrunch @hughhhh @john-bodley @graceguo-supercat @michellethomas @fabianmenges

### CODE REVIEW

**Comment by williaster** [comment]
it looks like the verbose format is not always being used in the tooltip, will fix this / if you have tips ( ;) ) let me know

**Comment by williaster** [comment]
Tested this with a  bunch of production examples and fixed a bug where `undefined` for showing min/max resulted in `truthy` interpretation by nvd3. Here's an example, note verbose format in tooltips + reduced y-axis tick count.

**Comment by oxydash** [comment]
It would be nice to add quarters -Q1, Q2, Q3, Q4

**Comment by williaster** [comment]
@oxydash while I agree that'd be nice, it's not trivial:

1) this is only affecting defaults, not adding new format options (quarters seems specialized)
2) quarters would also require logic for defining the actual ticks, which d3 does automagically at the moment.

**Review by fabianmenges — APPROVED** [review]

**Pull request merged**
