### PR TITLE
fix: time comparision

### PR DESCRIPTION
**Pull request by zhaoyongjie**
### SUMMARY

fix time comparison, follow the [viz.py pattern](https://github.com/apache/superset/blob/5c63df522a6df73e58142a1b9db62155c6ec5cd4/superset/viz.py#L1480)

difference: original column - compared column
percentage: (original column - compared column) / compared column
radio: original column / compared column

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by villebro — APPROVED** [review]
Tested to work as expected when comparing legacy line chart to v2 line chart. Only one unrelated problem observed when testing with `GENERIC_CHART_AXES` set to true on SQLite (the temporal axis is string based, causing the time diff to fail). But this is not a blocker.

**Comment by john-bodley** [comment]
@villebro @zhaoyongjie this fixes a fairly major regression (https://github.com/apache/superset/pull/19116) in my opinion, i.e., we have users reporting incorrect results which triggers a SEV-0 at Airbnb given that the most egregious error for a BI tool is actually reporting misinformation which is far worse than no information and/or an error.

I was wondering whether Preset et al. were planning to do a post mortem (or similar) for this? The topic of post mortems might be a good topic to raise during the Superset Operational Model—Quality track.

**Comment by zhaoyongjie** [comment]
@john-bodley, sorry for introducing the regression, I will do a more comprehensive integration test of the query object and advanced analysis.

**Comment by john-bodley** [comment]
@zhaoyongjie out of interest were there no unit tests previously for testing the comparisons?

**Comment by zhaoyongjie** [comment]
@john-bodley there was [unit test](https://github.com/apache/superset/tree/master/tests/unit_tests/pandas_postprocessing) for time comparisons, but the query results depended on combination of multiple operators and QueryObject. Unfortunately, there was it. I will add these recently.

**Comment by villebro** [comment]
> villebro zhaoyongjie this fixes a fairly major regression (#19116) in my opinion, i.e., we have users reporting incorrect results which triggers a SEV-0 at Airbnb given that the most egregious error for a BI tool is actually reporting misinformation which is far worse than no information and/or an error.
> 
> I was wondering whether Preset et al. were planning to do a post mortem (or similar) for this? The topic of post mortems might be a good topic to raise during the Superset Operational Model—Quality track.

@john-bodley it would be great to get guidelines for what types of regressions require more formal post mortems. If we had these types of guidelines in place, it would be easy to take that into consideration during code review. For instance, anything that affects calculation logic requires sign off from more committers or similar.

Also, @zhaoyongjie raised a good point about the previous tests not being specific enough. I think if we strive to make as isolated tests as possible that test for "obvious" cases (in this case that a change is +100, not -100, and that a going from 100 to 200 is +100 % and not, say, +50 % due to using an incorrect denominator in the calculation), the risk for these types of flipped sign regressions would not occur as easily. I'm happy to jump on a call to discuss this or assist in formalizing guidelines for this so we avoid similar problems going forward.

**Pull request merged**
