### PR TITLE
Make the filter dropdown choices in the Filter Box cascading

### PR DESCRIPTION
**Pull request by emlittleworth**
When a user selects a filter in the Filter Box visualization, the following filter dropdowns will be filtered based on that selection. It does not currently take the Filter Box time filter into consideration. I had to pull the `FilterBox` component into it's own file in order to export it for testing.

Before:
before

After:
after

Related issues: #5269, #5043, #4421, #3015, #5534

### CODE REVIEW

**Comment by mistercrunch** [comment]
Sorry that this PR got ignored so far. It's great work but as you know there's ongoing work in redesigning filters as dashboard native components and if we want to deprecate filter box, we may want (but not necessarily have to) to keep it as simple as possible. 

@xtinec (working on filters)

**Comment by emlittleworth** [comment]
Yeah I definitely understand we probably don't want to introduce new functionality at the moment. I'll close this for now. @xtinec let me know if you want to chat about how it works if you decide to integrate cascading filter options!

**Comment by xtinec** [comment]
@emlittleworth love to chat about cascading filter options and incorporate it into the new design!

**Comment by srggrs** [comment]
@emlittleworth I'm interested to chat about it as well. How can we get in touch?

**Comment by ajones620** [comment]
@emlittleworth i'm also interested as well! are there any updates or is there any feedback i can contribute?

**Comment by jnthnvctr** [comment]
@xtinec  and @emlittleworth  - is this something that's still in progress?

**Comment by smic-datalabs-von** [comment]
Chiming in: Would definitely love this feature to be put up in Superset.

**Comment by t0nydean** [comment]
@emlittleworth or @xtinec  or @mistercrunch Did this feature or something similar ever get finished?

**Pull request closed without merging**
