### PR TITLE
fix: Unsupported Slack API calls

### PR DESCRIPTION
**Pull request by PuszekSE**
### SUMMARY
[Issue/29480 invalid slack operation](https://github.com/apache/superset/issues/29480)

I've used very naive approach of simply replacing method calls for 'files_upload', since the method using it has already been marked for deprecation inside Superset.

### TESTING INSTRUCTIONS

Setup Slack Token API-based notification using dashboard.
Actually send the notification, instead of receiving API deprecation response from Slack.

### ADDITIONAL INFORMATION
- [x] Has associated issue: fixes https://github.com/apache/superset/issues/29480
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by rusackas** [comment]
Thanks for the PR! I think @eschutho is working on the same thing... hopefully we're not duplicating efforts. I've added her as a reviewer.

**Comment by eschutho** [comment]
Hi, thanks @PuszekSE for the contribution! As @rusackas mentioned, I had a similar PR [here](https://github.com/apache/superset/pull/28783/files) but it turns out that the v2 api has a different schema, so I'm implementing another larger change based on the new flow [here](https://github.com/apache/superset/pull/29264). I'll close this PR and you can track (and comment) on the current one.

**Comment by PuszekSE** [comment]
Thank you for the feedback!

**Comment by rusackas** [comment]
> Thank you for the feedback!

Thank you for the PR! We appreciate this, and any other contribution you're willing to make to the project. Feel free to reach out on [slack](http://bit.ly/join-superset-slack) if you ever want to discuss other opportunities to do so!

**Pull request closed without merging**
