### PR TITLE
fix: check if guest user modified query

### PR DESCRIPTION
**Pull request by betodealmeida**
### SUMMARY

Improve the logic that checks if a guest user has tampered with the query context or form data, preventing them from requesting metrics different from the ones saved in the chart.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

Before:

Screenshot 2024-03-12 at 15-38-21 React App

After:

Screenshot 2024-03-12 at 15-35-44 React App

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by craig-rueda — APPROVED** [review]
LGTM

**Comment by michael-s-molina** [comment]
@betodealmeida Does this fix https://github.com/apache/superset/issues/27177?

**Comment by JurajBurian** [comment]
Hello @betodealmeida, 
@michael-s-molina, you closed #27177, but problem still exist.  We have embeded dashboards with rls and native filters. After latst commit, embedding is not working. Message is the same :
`superset_app          | superset.exceptions.SupersetSecurityException: Guest user cannot modify chart payload`

I patched manager.py on line 158  : 
```Python
    # sanity checks
    if form_data is None or stored_chart is None:
        return False #replaced from True
```
and it help a lot, but then I hit the wall with another problem :
```Log
superset_app          |   File "/app/superset/security/manager.py", line 178, in <setcomp>
superset_app          |     frozenset(metric.items()) if isinstance(metric, dict) else metric
superset_app          | TypeError: unhashable type: 'dict'
```
unfortunatelly I am not Python expert, but this problem looks as "type" problem. Strange is that exception happens only on tabs having some type of graphs, for example `mixed chart ` is affected , `heat map` or  `bar chart` works fine.

**Comment by enzo-dechaene** [comment]
Hello @michael-s-molina the problem is also on the 3.0

**Comment by betodealmeida** [comment]
```
superset_app          |   File "/app/superset/security/manager.py", line 178, in <setcomp>
superset_app          |     frozenset(metric.items()) if isinstance(metric, dict) else metric
superset_app          | TypeError: unhashable type: 'dict'
```

This error message is really weird, because we're explicitly checking if `metric` is a `dict`.

**Comment by betodealmeida** [comment]
https://github.com/apache/superset/issues/27177 should fix the RLS and mixed chart problems.

**Pull request merged**
