### PR TITLE
fix: fill NaN Values in cumsum function

### LINKED ISSUE #21093: Cumsum Creating Discontinuous Lines
#### How to reproduce the bug

1. Create a cumsum with multiple series where some series do not have all of the dates
2. Plot Smooth Line

### Expected results

I would expect that when there are gaps in the date data, that the superset cumsum function creates a continuous line filling with the last value rather than producing NAs.

### Actual results

Lines break due to NAs in table when one series has a data point and the others don't.

#### Screenshots

image

### Environment

- Chrome latest version
- superset version: 1.5.0

### PR DESCRIPTION
**Pull request by WulfH**
### SUMMARY

Fill NaN Values before applying the cumsum function, to make the resulting lines continues.
Fixes https://github.com/apache/superset/issues/21093

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by zhaoyongjie** [comment]
@WulfH Thanks for the contribution, but I think this vis would be retired in Superset 3.0.

**Comment by sfirke** [comment]
@zhaoyongjie can you say more?  See the linked bug issue, I believe this is affecting line charts (not legacy).

**Comment by zhaoyongjie** [comment]
@sfirke Thanks for informing me, the change in the PR should affect legacy line chart and Advanced Analytics in legacy charts. 

I think the same issue should resolve in new Advanced Analytics, the Resample section in AA should fill up zero/nan and so on.

If I misleading anything please ping me.

**Comment by JohnDietrich-Pepper** [comment]
Just a comment that no this really isn't a bug.  If the user wants continuous lines, they should use a IFNULL or similar to replace the 0.  Zero and null are not the same and making nulls zeros for cumulative sum in every case breaks scenarios like this one here https://github.com/apache/superset/issues/27245 when they really should remain null.

**Comment by rusackas** [comment]
For this, I think you just need to use Zero imputation along with. your cumsum. I'll close this, but let me know if I'm misinterpreting and we can most certainly revisit/reopen.

Pasted_Image_3_3_24__5_00 PM

**Pull request closed without merging**
