### PR TITLE
fix: Fix for updated cache dependency

### PR DESCRIPTION
**Pull request by craig-rueda**
### SUMMARY
We recently upgraded the Wekrkzeug library to 1.0 which removed support for cache backends. The resolution is to switch over to Flask-Caching instead.
 
@nytai

### CODE REVIEW

**Review by nytai — APPROVED** [review]
lgtm, would be nice if we could test this helm chart as part of CI

**Comment by nytai** [comment]
Looks like the upgrade PR already introduced cachelib, https://github.com/apache/incubator-superset/commit/b532c4609fb3d62fa1c3f5dcc62a15a4a5cce520#diff-6a3371457528722a734f3c51d9238c13R930, should we use that instead of adding another dependency?

**Comment by etr2460** [comment]
++ to what @nytai said, all the werkzeug deps were moved into cachelib, so we should probably use that one

**Comment by craig-rueda** [comment]
I didn't notice that you had already updated this. I actually looked at adding `cachelib` initially, but the project looks like it's fallen into disrepair (only one release back in 2018). Switching back over...

**Review by villebro — APPROVED** [review]

**Pull request merged**
