### PR TITLE
fix: downloadasimage for dashboard

### LINKED ISSUE #15536: [dashboard] - Download Image not working
Not able to Download Image when clicking "Download Image" on the dashboard. 

### Expected results

Image of the dashboard to be downloaded

### Actual results

Image not downloaded , and the meanu also gets struck

#### Screenshots
image
image

#### How to reproduce the bug

1. Go to any Dashboard on Superset
3. Scroll down to 'Download Image'
4. See error in Developer Tools

### Environment

(please complete the following information):
Running from Docker apache/superset:latest-dev
- superset version: `master`
- Python 3.7.9
   Flask 1.1.2
   Werkzeug 1.0.1
- node.js version: 14

### PR DESCRIPTION
**Pull request by pkdotson**
### SUMMARY
This pr fixes the download as image for dashboard. 

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

before 

https://user-images.githubusercontent.com/17326228/124843685-4e0bcb80-df47-11eb-9310-6f0b6ca4810c.mov

after

https://user-images.githubusercontent.com/17326228/124843281-7e9f3580-df46-11eb-8e65-2caaf7ed9ca0.mov

closes: https://github.com/apache/superset/issues/15536

### TESTING INSTRUCTIONS
Go to dashboard and click the download as image for the dashboard.

### ADDITIONAL INFORMATION

- [x ] Has associated issue: https://github.com/apache/superset/issues/15536
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by cosmo83** [comment]
Works for me

**Review by michael-s-molina — APPROVED** [review]

**Comment by junlincc** [comment]
Thank you @pkdotson and @michael-s-molina for the quick fix and review!

**Comment by henryyeh** [comment]
🏷️ 2021.25

**Comment by henryyeh** [comment]
🏷️ 2021.27

**Comment by rosemarie-chiu** [comment]
Verified this PR in master locally 👍🏻

**Pull request merged**
