### PR TITLE
Add new Chart shortcut function

### PR DESCRIPTION
**Pull request by zhaoyu89730105**
Add new Chart shortcut function
image

### CODE REVIEW

**Comment by kristw** [comment]
Hi @zhaoyu89730105, 

Could you describe in more detail what does this new icon do?

**Comment by zhaoyu89730105** [comment]
@kristw 

-  this new icon can quickly open a chart editing page.
- At present, there are many steps to open a new chart with the same data source on the chart editing page, so we need to speed up the shortcut key.

**Comment by kristw** [comment]
Thanks @zhaoyu89730105 . I now understand the problem better, but do not think placing this particular shortcut here is the right solution for longer term. 

- It is not obvious/intuitive what the icon does. 
- Will users also want to select new visualization type as well? 
- Would a `duplicate` button next to `run query` and `save` be better? 

Would you mind opening an issue describing the problem and we can discuss alternatives there, perhaps with some designers chiming in?

**Comment by mistercrunch** [comment]
The "Save As" option in the save modal accomplishes something similar.

From reading the code I'm guessing this "resets" the chart and sends you to the table view. I'm not sure whether that's super helpful.

**Pull request closed without merging**
