### PR TITLE
Make package.json cross platform

### PR DESCRIPTION
**Pull request by fzzylogic**
### CATEGORY

Choose one

- [ ] Bug Fix
- [x] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY
Make package.json cross platform (so besides Linux and Mac, it will work on Windows with cmd or powershell without modifications). Tested on Linux and Windows. Though webpack builds successfully on windows, the minified output is different.

Attempt at redemption after #8024 ^^

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### REVIEWERS
etr2460

### CODE REVIEW

**Review by etr2460 — CHANGES_REQUESTED** [review]
since you're adding a new dependency, you need to run `npm install` and commit the lockfile changes as well

**Comment by kristw** [comment]
Also, what about other commands other than `build`?

**Comment by etr2460** [comment]
> Also, what about other commands other than `build`?

It looks like build is the only command that sets an env variable, so i assume all the others work cross platform already

**Comment by fzzylogic** [comment]
Introduced "response": "" instead of "response": false in package-lock in some cases accidentally, resolved with last commit. @etr2460 thanks for the guidance, @kristw yes, cross-env only solves the env var problem, however i didn't test all the other commands on Windows. Thanks!

**Review by etr2460 — APPROVED** [review]
lgtm, thanks for this!

**Review by kristw — APPROVED** [review]

**Pull request merged**
