### PR TITLE
Fix merge_extra_filters

### LINKED ISSUE #4042: Table View: unsupported operand type(s) for +: 'NoneType' and 'str'
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

0.22.1

### Expected results

I would expect to see the table when the slice is included in a dashboard, any dashboard

### Actual results

Instead I have the following message:
``` 
unsupported operand type(s) for +: 'NoneType' and 'str'
```

### Steps to reproduce

I don't know what is so special about this table view. Other table views work perfectly fine, but for this one even when I change all the options (with group keys or without, with "Include Time" option or without, with sorting or without) nothing changes: the slice seems to work fine when editing, but inside a dashboard I get the error.

Stacktrace:
```
Dec 11 16:22:32  scl[15363]: Traceback (most recent call last):
Dec 11 16:22:32  scl[15363]: File "/home/superset-server/venvs/sss-superset-py3/lib/python3.5/site-packages/superset/views/core.py", line 1083, in explore_json
Dec 11 16:22:32  scl[15363]: force=request.args.get('force') == 'true')
Dec 11 16:22:32  scl[15363]: File "/home/superset-server/venvs/sss-superset-py3/lib/python3.5/site-packages/superset/viz.py", line 248, in get_payload
Dec 11 16:22:32  scl[15363]: cache_key = self.cache_key
Dec 11 16:22:32  scl[15363]: File "/home/superset-server/venvs/sss-superset-py3/lib/python3.5/site-packages/superset/viz.py", line 225, in cache_key
Dec 11 16:22:32  scl[15363]: merge_extra_filters(form_data)
Dec 11 16:22:32  scl[15363]: File "/home/superset-server/venvs/sss-superset-py3/lib/python3.5/site-packages/superset/utils.py", line 719, in merge_extra_filters
Dec 11 16:22:32  scl[15363]: existing_filters[get_filter_key(existing)] = existing['val']
Dec 11 16:22:32  scl[15363]: File "/home/superset-server/venvs/sss-superset-py3/lib/python3.5/site-packages/superset/utils.py", line 716, in get_filter_key
Dec 11 16:22:32  scl[15363]: return f['col'] + '__' + f['op']
Dec 11 16:22:32  scl[15363]: TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

### PR DESCRIPTION
**Pull request by nbonnotte**
Fix #4042

- [x] Write tests
- [x] Write fix

### CODE REVIEW

**Comment by fabianmenges** [comment]
I'm not super familiar with this code but do 'filter slices' still work after this change?

**Comment by nbonnotte** [comment]
@fabianmenges i don't know either, so just to be sure i'm changing the code to be more specific

**Comment by nbonnotte** [comment]
Ok, so now I don't see how it could alter any working feature

**Comment by Mogball** [comment]
@nbonnotte I'm not sure what filters with `None` as `col` are for (or if that is the result of another issue). Is there something particular about your dataset?

In any case I might change `return f['col'] + '__' + f['op']` to `return f['col'] if f['col'] else '__none' + '__' + f['op']` in case a filter with `None` as `col` shows up in both `filters` and `extra_filters`

**Comment by nbonnotte** [comment]
I don't think there is anything particular with my dataset / slice / dashboard. I don't know how this `None` appears, but I've tried to change the slice, recreate it, everything I could think of, to no avail.

I assume you mean
```
return (f['col'] if f['col'] else '__none') + '__' + f['op']
```
This seems to work as well with my dataset.

Should I make the change?

**Comment by mistercrunch** [comment]
The client should probably not generate `None` columns filters in the first place... It's probably not a bad thing for the backend to handle it regardless.

**Pull request merged**
