### PR TITLE
revert: "fix(sql lab): display the 'View Results' button consistently in the history tab on sync mode"

### PR DESCRIPTION
**Pull request by Gwitchr**
Reverts apache/superset#19362

### CODE REVIEW

**Comment by rusackas** [comment]
For added context, this PR is reverting the prior fix because it led to a new issue, where results from valid queries were not being displayed properly. To repro:

1) Run sql query with 100 rows limit
2) Check query history and observe that there is no "view result" button
3) Run the query again with different row limit, and see that the result button is now shown

**Comment by rusackas** [comment]
For added context, this PR is reverting the prior fix because it led to a new issue, where results from valid queries were not being displayed properly. To repro:

1) Run sql query with 100 rows limit
2) Check query history and observe that there is no "view result" button
3) Run the query again with different row limit, and see that the result button is now shown

**Review by rusackas — APPROVED** [review]
OK to revert... let's try to fix forward and solve the _original_ problem though.

**Comment by sadpandajoe** [comment]
🏷️  preset:2022.17

**Pull request merged**
