### PR TITLE
fix: tests errors and warnings - iteration 1 (#12212)

### PR DESCRIPTION
**Pull request by michael-s-molina**
### SUMMARY
Remove tests errors and warnings to improve results readability.

The following errors and warnings have been removed:

```
Warning: Invalid DOM property `autocomplete`. Did you mean `autoComplete`?

spec/javascripts/explore/components/SaveModal_spec.jsx
spec/javascripts/datasource/DatasourceModal_spec.jsx
spec/javascripts/sqllab/TabbedSqlEditors_spec.jsx
spec/javascripts/explore/components/ColorScheme_spec.jsx
spec/javascripts/explore/components/FilterBox_spec.jsx
spec/javascripts/views/CRUD/chart/ChartList_spec.jsx
src/views/CRUD/data/query/QueryList.test.tsx
spec/javascripts/views/CRUD/data/database/DatabaseList_spec.jsx
spec/javascripts/views/CRUD/alert/AlertReportModal_spec.jsx
spec/javascripts/components/TableSelector_spec.jsx
spec/javascripts/components/ListView/ListView_spec.jsx
spec/javascripts/dashboard/components/PropertiesModal_spec.jsx
spec/javascripts/views/CRUD/data/savedquery/SavedQueryList_spec.jsx
spec/javascripts/views/CRUD/csstemplates/CssTemplatesList_spec.jsx
spec/javascripts/views/CRUD/alert/AlertList_spec.jsx
spec/javascripts/views/CRUD/data/dataset/DatasetList_spec.jsx
spec/javascripts/views/CRUD/annotationlayers/AnnotationLayersList_spec.jsx
spec/javascripts/components/SupersetResourceSelect_spec.tsx
```

```
Warning: React does not recognize the `activeKey` prop on a DOM element. 
If you intentionally want it to appear in the DOM as a custom attribute, 
spell it as lowercase `activekey` instead. If you accidentally passed it from a parent component, 
remove it from the DOM element.

spec/javascripts/views/CRUD/dashboard/DashboardList_spec.jsx
spec/javascripts/views/CRUD/chart/ChartList_spec.jsx
src/views/CRUD/data/query/QueryList.test.tsx
spec/javascripts/views/CRUD/data/database/DatabaseList_spec.jsx
spec/javascripts/views/CRUD/welcome/SavedQueries_spec.tsx
spec/javascripts/views/CRUD/data/savedquery/SavedQueryList_spec.jsx
spec/javascripts/views/CRUD/csstemplates/CssTemplatesList_spec.jsx
spec/javascripts/views/CRUD/alert/AlertList_spec.jsx
spec/javascripts/views/CRUD/data/dataset/DatasetList_spec.jsx
spec/javascripts/views/CRUD/annotationlayers/AnnotationLayersList_spec.jsx
spec/javascripts/views/CRUD/annotation/AnnotationList_spec.jsx
spec/javascripts/views/CRUD/welcome/ActivityTable_spec.tsx
spec/javascripts/views/CRUD/welcome/DashboardTable_spec.tsx
spec/javascripts/views/CRUD/welcome/Welcome_spec.tsx
spec/javascripts/views/CRUD/welcome/ChartTable_spec.tsx
```

```
Warning: React does not recognize the `activeHref` prop on a DOM element. 
If you intentionally want it to appear in the DOM as a custom attribute, 
spell it as lowercase `activehref` instead. If you accidentally passed it from a parent component, 
remove it from the DOM element.

spec/javascripts/views/CRUD/dashboard/DashboardList_spec.jsx
spec/javascripts/views/CRUD/chart/ChartList_spec.jsx
src/views/CRUD/data/query/QueryList.test.tsx
spec/javascripts/views/CRUD/data/database/DatabaseList_spec.jsx
spec/javascripts/views/CRUD/welcome/SavedQueries_spec.tsx
spec/javascripts/views/CRUD/data/savedquery/SavedQueryList_spec.jsx
spec/javascripts/views/CRUD/csstemplates/CssTemplatesList_spec.jsx
spec/javascripts/views/CRUD/alert/AlertList_spec.jsx
spec/javascripts/views/CRUD/data/dataset/DatasetList_spec.jsx
spec/javascripts/views/CRUD/annotationlayers/AnnotationLayersList_spec.jsx
spec/javascripts/views/CRUD/annotation/AnnotationList_spec.jsx
spec/javascripts/views/CRUD/welcome/ActivityTable_spec.tsx
spec/javascripts/views/CRUD/welcome/DashboardTable_spec.tsx
spec/javascripts/views/CRUD/welcome/Welcome_spec.tsx
spec/javascripts/views/CRUD/welcome/ChartTable_spec.tsx
```

```
Warning: Each child in a list should have a unique "key" prop.

spec/javascripts/explore/components/AdhocFilterEditPopoverSimpleTabContent_spec.jsx
```

```
Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.

spec/javascripts/views/CRUD/welcome/DashboardTable_spec.tsx
spec/javascripts/views/CRUD/welcome/Welcome_spec.tsx
spec/javascripts/views/CRUD/welcome/ChartTable_spec.tsx
spec/javascripts/views/CRUD/welcome/EmptyState_spec.tsx
```

```
Warning: Failed prop type: You have provided a `open` prop to `Dropdown` 
without an `onToggle` handler prop. This will render a read-only field. 
If the field should be mutable use `defaultOpen`. Otherwise, set `onToggle`.

src/components/Menu/Menu.tsx
src/components/Menu/MenuObject.tsx
src/components/Menu/NewMenu.tsx
```

#12212 

@rusackas @junlincc @villebro 

### ADDITIONAL INFORMATION
- [x] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by junlincc** [comment]
thanks for the PRs @michael-s-molina! is there a test plan for them?

**Comment by michael-s-molina** [comment]
> thanks for the PRs @michael-s-molina! is there a test plan for them?

We just need to run the tests and verify that the errors and warnings are decreasing. Most of the changes are in spec files and the ones that change a component are covered by a test.

**Comment by ktmud** [comment]
Could you comment on each change on which errors/warnings they are supposed to solve if you still remember?

**Comment by michael-s-molina** [comment]
@ktmud I updated the PR description with the fixed errors and warnings. I'll do the same with the other PRs.

**Comment by ktmud** [comment]
Thanks so much!

**Review by ktmud — COMMENTED** [review]
LGTM with a couple of small nits.

**Review by ktmud — APPROVED** [review]

**Comment by michael-s-molina** [comment]
@ktmud Accepted suggested changes. I did a force push to preserve commit history.

**Pull request merged**
