### PR TITLE
[READY] [feature] Added dashboard read only with new Rho role

### PR DESCRIPTION
**Pull request by datinho**
I needed a user who could only access the read-only dashboards, so I've added a new built-in role Rho (&rho;) as logged user but less powerful than Gamma.
As Gamma user this role need a complementary role to have access to view the dashboards.

### CODE REVIEW

**Comment by datinho** [comment]
I've just modified the doc 'security.rst' but Travis CI returned a timeout during the step 'Creating a dashboard':

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated

If this status persists I'll try to commit again in order to activate te CI.

**Comment by datinho** [comment]
Hi all, 
I think a built-in read only role/user is missing and I've tried to be complaint with the new code review process.
I've re-based the dashboard-only-rho-user branch  to the master and I hope that PR cuold be merged soon.
Thanks in advance.

**Comment by mistercrunch** [comment]
We'll need unit tests making sure that a users with this role can access the things we except them to be able to access and not other things.

**Comment by datinho** [comment]
Hi @mistercrunch ,
I never did an unit test but I'll try. Just a tip, do I modify only the tests/security_tests.py or is there other files to handle?
Thanks in advance.

**Comment by mistercrunch** [comment]
https://github.com/apache/incubator-superset/blob/master/CONTRIBUTING.md#testing

**Comment by datinho** [comment]
I've added the unit test, someone can kindly give me a feedback please?

**Comment by datinho** [comment]
@hughhhh @kristw could you kindly check my PR?
Thanks.

**Comment by datinho** [comment]
@timifasubaa @mistercrunch 
I'm waiting a review from 3 months during I'm still work to avoid conflict.
Do you plan to review thi PR soon?
Thanks in advance.
CC: @kristw

**Comment by datinho** [comment]
@mistercrunch @timifasubaa 
could you kindly review this PR please?
Thanks in advance.

**Comment by kalimuthu123** [comment]
Not worked for me i added code in all 5 files

**Review by kalimuthu123 — APPROVED** [review]

**Review by kalimuthu123 — APPROVED** [review]
good

**Comment by blcksrx** [comment]
It's an interesting feature! why should be stopped? @mistercrunch

**Comment by blcksrx** [comment]
@datinho  Do you want to help you with this PR?

**Comment by datinho** [comment]
Hi,
unfortunately the PR was blocked a year ago, no feedback from reviewers.
I gave up but if you want you could branch the current repository and
apply/migrate the code, I hope that you'll be lucky.
Regards

Il giorno mar 21 lug 2020 alle ore 15:33 Hossein Torabi <
notifications@github.com> ha scritto:

**Comment by amitmiran137** [comment]
#10408

**Comment by junlincc** [comment]
Closing inactive PR in favor of #12680 @amitmiran137, thank you for your contribution! @datinho

**Pull request closed without merging**
