### PR TITLE
fix(maps): adds Crimea back to Ukraine 🇺🇦

### PR DESCRIPTION
**Pull request by rusackas**
### SUMMARY

Updates the Jupyter notebook to correct Natural Earth's data, and copy Crimea (back) onto Ukraine.

All references to Kiev are also now properly renamed to Kyiv

Czech Republic an Philippines Regions seem to be updated, as bycatch.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by villebro — APPROVED** [review]
Tested, LGTM!
image

**Comment by last-partizan** [comment]
Oh, thank you for this commit.

Btw, maybe also remove Crimea from Russia map?

**Comment by ZOY23** [comment]
Oh, thank you for this commit.

But you made a mistake, there are real boundaries in the screenshot.

**Comment by defteame** [comment]
@ZOY23 that's some cool fanfiction you have there (esp. Kherson lol), not sure how its related to real boundaries though?

**Comment by villebro** [comment]
@rusackas recently wrote a good blog post on how the Superset project manages the country maps, and what our policies are regarding contested areas. I kindly request users refrain from getting into this debate here - if anyone wants to contest our policies, you are welcome to post to our dev list, or join our in-person monthly town hall, to see if the wider community shares your views.

**Pull request merged**
