### PR TITLE
fix(wip): Changes to support presto impersionation with ldap

### PR DESCRIPTION
**Pull request by rijojoseph07**
### SUMMARY
Fix for issue https://github.com/apache/superset/issues/11359, https://github.com/apache/superset/issues/9406

When using LDAP authentication with presto/trino, the current behavior is just to modify the URL to replace the username which will result in an unauthorized exception. This PR will fix this by updating the connection argument with the effective user. 

### TEST PLAN
Step 1: Setup database connection to presto without credentials in URL.
Step 2: Provide admin(who can impersonate as any other user in presto) credentials in connection properties via extras  
```
"engine_params": {
           "connect_args":{
              "protocol": "https",
              "username":"<admin>",
              "password":"<admin_password>"
           }
}
```

Step 3: Enable impersonation for the database connection. 
Step 4: Log in with a different user and run the query via SQL lab and you will see the **principal user** as admin and **user** as the logged-in user in presto UI.

### ADDITIONAL INFORMATION

- [X] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by DRavikanth** [comment]
@rijojoseph07 Which release is this targeted for? I am having issues with Impersonation on SSv1.0.1

**Comment by rijojoseph07** [comment]
> @rijojoseph07 Which release is this targeted for? I am having issues with Impersonation on SSv1.0.1

@villebro Can you please help here?

**Comment by villebro** [comment]
@rijojoseph07 how can I help? This PR appears to be closed.

**Comment by rijojoseph07** [comment]
> @rijojoseph07 how can I help? This PR appears to be closed.

I meant if you have any details on the release date, can you please share it? @villebro

**Comment by rijojoseph07** [comment]
@DRavikanth was asking for a targeted release for this PR since he is facing issues with impersonation.

**Comment by villebro** [comment]
@rijojoseph07 AFAIK this PR isn't merged, so it's not in master or any upcoming release, either. If you wish to have this PR reviewed, please reopen it.

**Comment by rijojoseph07** [comment]
@villebro this was merged before.. I thinking removing WIP from PR header reopened this :|

**Comment by rijojoseph07** [comment]
> @rijojoseph07 AFAIK this PR isn't merged, so it's not in master or any upcoming release, either. If you wish to have this PR reviewed, please reopen it.

Sorry @villebro I got confused with this PR which was merged. https://github.com/apache/superset/pull/13214

**Comment by villebro** [comment]
Ok, now I understand; #13214 is included in the upcoming 1.1 version, so shouldn't be long now 🙂

**Comment by rijojoseph07** [comment]
> Ok, now I understand; #13214 is included in the upcoming 1.1 version, so shouldn't be long now 🙂

Thanks, @villebro. @DRavikanth FYI ^^

**Pull request closed without merging**
