### PR TITLE
add babel-polyfill

### PR DESCRIPTION
**Pull request by gschrader**
in order to add Object.assign and Array.includes support for older browsers (#1302)

### CODE REVIEW

**Comment by gschrader** [comment]
I'm not sure this is the best way to do this, it's a shame it has to be added to each entry point.

**Comment by ascott** [comment]
i would prefer to do this in `webpack.config.js`, adding `'babel-polyfill'` to the entry array
https://babeljs.io/docs/usage/polyfill/

```js
module.exports = {
   entry: ['babel-polyfill', './app/js']
};
```

**Comment by gschrader** [comment]
@ascott I'll try to do it that way, I'm a webpack newbie so I wasn't sure how that lined up with this structure:

```
  entry: {
    'css-theme': APP_DIR + '/javascripts/css-theme.js',
    dashboard: APP_DIR + '/javascripts/dashboard/Dashboard.jsx',
    explore: APP_DIR + '/javascripts/explore/explore.jsx',
    explorev2: APP_DIR + '/javascripts/explorev2/index.jsx',
    welcome: APP_DIR + '/javascripts/welcome.js',
    standalone: APP_DIR + '/javascripts/standalone.js',
    common: APP_DIR + '/javascripts/common.js',
    sqllab: APP_DIR + '/javascripts/SqlLab/index.jsx',
  },
```

I assume I just add the entry and then I'd have to add the built asset to the html template?

**Comment by ascott** [comment]
you would remove the `require('babel-polyfill');` line in the templates and add babel-polyfill to the entry arrays like this... 

```
entry: {
  'css-theme': ['babel-polyfill', APP_DIR + '/javascripts/css-theme.js'],
  ...
},
```

the entry object can take either strings to a single file or an array.

thanks for the pr!

**Comment by ascott** [comment]
@gschrader turns out i had a branch with this work started already so I opened a PR with the working implementation. https://github.com/airbnb/caravel/pull/1323

**Comment by gschrader** [comment]
@ascott great! I'll try your branch with the javafx browser.

**Pull request closed without merging**
