### PR TITLE
Add licenses to translations

### PR DESCRIPTION
**Pull request by bolkedebruin**

### CODE REVIEW

**Comment by bolkedebruin** [comment]
@mistercrunch @kristw

**Comment by mistercrunch** [comment]
LGTM

**Comment by bolkedebruin** [comment]
@mistercrunch done for now.

**Comment by bolkedebruin** [comment]
@mistercrunch @kristw can you merge?

**Comment by bolkedebruin** [comment]
@kristw @mistercrunch this finalizes all licenses (afaik) for a pure source release. Please merge ;-)

**Pull request merged**
