### PR TITLE
[dashboard v2] tests!

### PR DESCRIPTION
**Pull request by williaster**
This PR adds a ton of tests for the new dashboard app.

3rd time is the charm ;) Ended up in a weird git state so this cherry picks from #4993 

@graceguo-supercat

### CODE REVIEW

**Comment by williaster** [comment]
@graceguo-supercat merging this, unsure why the python3.6 builds are failing

**Comment by zkenstein** [comment]
Hi, is this possible to try this feature before release?

**Comment by williaster** [comment]
@zkenstein yes! you can pull the `apache-ssh/dashboard-builder` branch and test locally (#4528 is the relevant PR). 

we are stress testing over the next couple of weeks, please comment on that PR if you encounter issues/have feedback 👍

**Comment by zkenstein** [comment]
@williaster nice!

**Pull request merged**
