### PR TITLE
feat(explore): each control can define its own canDrop for dnd

### PR DESCRIPTION
**Pull request by kgabryje**
### SUMMARY
Allows defining `canDropValue` function in `mapStateToProps` of controls in control panel (in superset-ui).
That will allow us not only to use generic `canDrop` functions for columns or adhoc metrics, but also more advanced ones - like `can drop column "gender" in "Series" control only if "Breakdown" control doesn't already have this column added`.

It's a prerequisite for fixing issue https://github.com/apache/superset/issues/16071

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
No changes

### TESTING INSTRUCTIONS
0. Enable dnd
1. Verify that everything works as before

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

CC: @junlincc

### CODE REVIEW

**Comment by michael-s-molina** [comment]
@kgabryje I didn't understand why we need to create an additional function for this. `canDrop` receives a `DatasourcePanelDndItem` and this object contains a `value` prop of type `DndItemValue`. Can't we just check the value inside `canDrop`?

**Comment by kgabryje** [comment]
@michael-s-molina We can only check control's own value in `canDrop`. The point was to 1) allow checking values of other controls, so that for example user can add a value to control1 only if that value hasn't been added to control2. That can be done in `mapStateToProps` function in chart's control panel in superset-ui, and that's were `canDropValue` is supposed to be defined if needed. And 2) this allows us to define `canDrop` rules specific to a given control, which doesn't apply to all `DndColumnControl` type controls

**Comment by michael-s-molina** [comment]
@villebro What do you think? I'm still not sure if we need this extra prop.

**Comment by villebro** [comment]
I agree with Kamil's assessment and see this as improving decoupling. By adding this we can let both components decide about the things they have the best context on. Without it we face a situation where we would need to make control1 aware of logic that should be inside control2 and vice versa.

**Comment by michael-s-molina** [comment]
@villebro @kgabryje Understood. Can we add an `onDropValue` for consistency?

**Review by michael-s-molina — APPROVED** [review]
Thanks for the clarifications!

**Review by villebro — APPROVED** [review]

**Pull request merged**
