### PR TITLE
ci: use git submodules for  Chart Actions

### PR DESCRIPTION
**Pull request by jawabuu**
### SUMMARY

This adds chart actions submodules to allow chart actions to run.
Added because of implementation for using git submodules for (securely) using third party Github Actions (apache#12709)
Related to https://github.com/apache/superset/pull/14163 that has been accepted.

### ADDITIONAL INFORMATION

- [ X] Has associated issue: https://github.com/apache/superset/pull/14163
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API
@craig-rueda

### CODE REVIEW

**Comment by jawabuu** [comment]
@amitmiran137 @craig-rueda 
See chart linter in action
https://github.com/apache/superset/pull/14211/checks?check_run_id=2368816356
For some reason chart maintainer fails validation, should I change it?

**Comment by jawabuu** [comment]
Lint works great now. Should be OK to merge
https://github.com/apache/superset/pull/14211/checks?check_run_id=2368915717

**Comment by amitmiran137** [comment]
Again , the work your doing here is amazing!!

**Comment by craig-rueda** [comment]
Apache just approved the action added in #14163 . Closing this in favor of previous PR.

**Comment by craig-rueda** [comment]
After testing, I think this is a better solution, as it doesn't require additional approvals from Apache infra :)

**Review by craig-rueda — APPROVED** [review]

**Pull request merged**
