### PR TITLE
fix(translations): French translation (typo fixes)

### PR DESCRIPTION
**Pull request by xavier-GitHub76**
Hello,
it's my first commit.
I just corrected some typos.
Best regards

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by lyndsiWilliams — APPROVED** [review]
I was able to check these typos in Google Translate and they all look good, thanks for the fixes!
image

**Comment by rusackas** [comment]
Closing and re-opening to kick CI into gear 🤞

**Comment by rusackas** [comment]
Thanks for the contribution @xavier-GitHub76! Please reach out on Slack if you ever want to talk about working on additional PRs!

**Comment by xavier-GitHub76** [comment]
Hello,
the commit was merge but the translation is not present in superset V3
image

**Comment by xavier-GitHub76** [comment]
"Schedule a new email report" should be added to https://github.com/apache/superset/tree/3.0/superset/translations/fr/LC_MESSAGES
/messages.json
"Scheduled task executor not found" should be added to https://github.com/apache/superset/tree/3.0/superset/translations/fr/LC_MESSAGES
/messages.json

**Comment by xavier-GitHub76** [comment]
I update the LC_MESSAGES (https://github.com/apache/superset/pull/25873)

**Pull request merged**
