### PR TITLE
docs: Fix typo on line 967

### PR DESCRIPTION
**Pull request by ChristopherCFleming**
### SUMMARY
Changed "wakeup" to "wake up" on line 967.

### CODE REVIEW

**Comment by AAfghahi** [comment]
THis looks great, it looks like you don't have a package-lock.json. Could you add one? 

if your master is up to date you could do:
`git checkout master superset-frontend/package-lock.json` and push that up.

**Review by AAfghahi — APPROVED** [review]

**Comment by AAfghahi** [comment]
Wonderful! Let me know when its all green and I will merge :)

**Comment by ChristopherCFleming** [comment]
Okay. I used git checkout master superset-frontend/package-lock.json to retrieve the original file, then SKIP=check-added-large-files with this commit to disregard the file size check and push the file.

**Comment by AAfghahi** [comment]
oh wait can you add a summary?

**Review by AAfghahi — CHANGES_REQUESTED** [review]
Can you add a summary?

**Review by AAfghahi — APPROVED** [review]

**Pull request merged**
