### PR TITLE
feat(formatters): Add custom d3-time-format locale

### PR DESCRIPTION
**Pull request by matheusbsilva**
### SUMMARY

Adds a configuration option to change the default language of time related data on charts, including the option to translate months. This is related to issues: #3972 , https://github.com/apache/superset/issues/13442 and https://github.com/apache/superset/issues/17447.

During the implementation I had to change how the smart formatters were used across the application, because I had to ensure that they were instantiated with the right locale configuration. So instead of importing them directly, I got them through the TimeFormatterRegistry. I'm not sure if is the best option, let me know.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

Without time format configuration:
Captura de tela de 2023-06-01 09-49-00

With brazilian portuguese time format configuration:
Captura de tela de 2023-06-01 09-47-58

### TESTING INSTRUCTIONS

Add the `D3_TIME_FORMAT` with your locale configuration to `superset_config.py` following the definition expected by D3 ([docs](https://github.com/d3/d3-time-format/tree/main#locales)), for example, this is the definition for brazilian portuguese:

```py
D3_TIME_FORMAT = {
  "dateTime": "%A, %e de %B de %Y. %X",
  "date": "%d/%m/%Y",
  "time": "%H:%M:%S",
  "periods": ["AM", "PM"],
  "days": ["Domingo", "Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado"],
  "shortDays": ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"],
  "months": ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"],
  "shortMonths": ["Jan", "Fev", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set", "Out", "Nov", "Dez"]
}
```

### ADDITIONAL INFORMATION

- [X] Has associated issue:
- [ ] Required feature flags:
- [X] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [X] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by eschutho** [comment]
Also ccing @villebro since he is working on some other localization features.

**Comment by lf-floriandin** [comment]
Oh big fan of this!
Any updates on this?

**Comment by matheusbsilva** [comment]
Any updates on this review?

**Comment by Cmagno13** [comment]
Any updates on this review?

**Comment by cchristofr** [comment]
Many thanks for this PR.
I'm awaiting for this PR: To use Superset in France (public sector), this PR is mandatory. 
Do you have any idea when this PR will be merged in superset?

**Comment by cchristofr** [comment]
up

**Comment by matheusbsilva** [comment]
@eschutho I fixed the conflicts. If there is anything that I can do to help with the review, let me know :+1:

**Comment by ImmortalLotus** [comment]
any  updates on this one?

**Comment by rusackas** [comment]
There are a handful of linting errors to contend with still that are blocking this.

**Comment by rtotheb2000** [comment]
any updates on this one?

**Comment by rusackas** [comment]
Looks like this needs some linting AND a rebase at this point. If @matheusbsilva wants to follow through, that's awesome, but anyone else is also welcome to pick this up if they desire to.

**Comment by matheusbsilva** [comment]
Thansk for the reply @rusackas, I'll fix the linting errors soon.

**Comment by matheusbsilva** [comment]
@rusackas I've fixed the linting errors and checked all the linters locally, everything is fine.

**Comment by rusackas** [comment]
Running CI. Fingers crossed! 🤞

**Comment by matheusbsilva** [comment]
@rusackas I added more tests to fix the [coverage issue](https://github.com/apache/superset/actions/runs/8473845643/job/23367969262?pr=24263) reported in the last CI run.

**Comment by matheusbsilva** [comment]
@rusackas Is there anything else that I can do to help with the review?

**Review by rusackas — APPROVED** [review]
LGTM, but would love a second opinion from @kgabryje or @justinpark or @michael-s-molina or @villebro 

I know this PR will make a lot of people happy when it's merged, too!

**Comment by matheusbsilva** [comment]
up

**Comment by rusackas** [comment]
Running CI again - fingers crossed! Last chance, @kgabryje / @justinpark / @michael-s-molina / @villebro

**Comment by matheusbsilva** [comment]
@rusackas I fixed some linting errors caused by merge conflict.

**Comment by matheusbsilva** [comment]
up

**Comment by rusackas** [comment]
CI running again 🤞 . Feel free to DM me on [slack](http://bit.ly/join-superset-slack) as well if you need me to push buttons here again ;)

**Comment by BaraDiaw** [comment]
Hello, I've been using superset for 3 months. I want to change the language to french. I added the D3_TIME_FORMAT with my local configuration for superset_config.py but it still doesn't work. Could you help me again.
Capture d'écran 2024-06-07 122437

**Comment by cchristofr** [comment]
Hi
A PR is in progress for this.
See https://github.com/apache/superset/pull/24263

Christophe

**Comment by cchristofr** [comment]
oui, moi aussi.
Vous travaillez en France ?

**Comment by BaraDiaw** [comment]
Non, je travaille au Sénégal.

**Comment by cchristofr** [comment]
espérons que nous aurons bientôt une gestion multilingue correcte.
Actuellement, le choix FR n'agit que sur la traduction de l'interface mais
pas sur les textes (et formats) dans les graphiques.
Sinon, superset est un bon produit.

**Comment by rusackas** [comment]
Closing and re-opening due to a weird glitch with E2E tests.

**Review by sfirke — APPROVED** [review]
I can't speak to the code details but everything looked good to me and it's a great feature!

**Comment by Zhikharevi** [comment]
Sorry, could you help? I paste your code, but for some reason nothing changes

Снимок экрана 2024-08-12 в 14 58 17
Снимок экрана 2024-08-12 в 14 59 30

**Comment by Yisel-Ulloa** [comment]
Good morning. Do you know if there is already the possibility of translating the names of the boards, graphs and filters dynamically?

**Pull request merged**
