### PR TITLE
refactor(ChartData): move ChartDataResult enums to common

### PR DESCRIPTION
**Pull request by ofekisr**
### **Background** 
When we have worked on #16991 we wanted to test the new functionalities in concrete and accurate unittest.
All chartData flows and its components are too couple to superset so it is impossible to create unittests. 
The flows are not testable and so many components do not meet the very important principle SRP and the code became so dirty 

So I've started to refactor it (#17344 ) but many changes were added and it was hard to review so I decided to split those changes into small PRs so will be easier to follow 

this is the First PR
The next PR is #17400 

### PR description
Moving ChartDataResultType and ChartDataResultFormat from utils to common.
think about it those are not utils and used by many places so it more sense to be in common 

### test plans 
There are no logic change so new tests are not required

### CODE REVIEW

**Review by amitmiran137 — APPROVED** [review]
LGTM , simple move of 2 enums t

**Review by villebro — COMMENTED** [review]
Since these are called `ChartData*`, should we consider moving them to `superset/charts`? And if not, should these actually be renamed to correspond more to the classes in `superset/common`, so something like `Query*`?

**Comment by ofekisr** [comment]
> Since these are called `ChartData*`, should we consider moving them to `superset/charts`? And if not, should these actually be renamed to correspond more to the classes in `superset/common`, so something like `Query*`?

I agree with you but we should do it after we move all other components who use it to charts as well

in case we will understand that is not conceptually possible, we should change the enums names

**Comment by villebro** [comment]
I would prefer to start building towards the ultimate end state that we want to migrate towards rather than moving/refactoring the old code that we already know isn't optimal. For instance, if these class/type names don't make sense, I'd rather rename them now than move them, as moving doesn't really bring us any closer to the north star. And if we don't have a clear north star, let's rather spend some time discussing what that should be, so that we can gradually start introducing the new structures (along with comprehensive tests) that will eventually deprecate and totally remove the need for the old structures.

**Comment by ofekisr** [comment]
> I would prefer to start building towards the ultimate end state that we want to migrate towards rather than moving/refactoring the old code that we already know isn't optimal. For instance, if these class/type names don't make sense, I'd rather rename them now than move them, as moving doesn't really bring us any closer to the north star. And if we don't have a clear north star, let's rather spend some time discussing what that should be, so that we can gradually start introducing the new structures (along with comprehensive tests) that will eventually deprecate and totally remove the need for the old structures.

so open a new naming discussion... in my opinion should be a general name for querying superset something that starts with  SuperSet Query (SSQ) but note it can query a real datasource data but metadata and Supserset components as well

**Pull request merged**
