### PR TITLE
fix(filter-indicator): show filters handled by jinja as applied

### LINKED ISSUE #15209: Jinja Incompatible Filter Warnings
Warning signs appear when applying jinja filter. The functionality works but it would be nice visually if there weren't warnings appearing.
### Expected results

Jinja filter hopefully will eventually work without filter warnings appearing. 

### Actual results

https://www.youtube.com/watch?v=dE1QlhunWMs (skip to end to view warnings)

### PR DESCRIPTION
**Pull request by villebro**
### SUMMARY
Currently only legacy charts support identifying filters applied via jinja templates. However, this only supports the `filter_values` function, and is done using regex on the virtual table query. Therefore, filters applied via the `get_filters` function don't work on either v1 or legacy charts, as they aren't caught by the regex. In addition, this approach has the unlikely downside of false positives, if the regex would happen to match a parameter in the regular query, as it didn't check for opening/closing curly braces.

This PR replaces the regex-based identification method with a similar approach to how removed filters are currently identified. The applied filters are added to a list during template rendering, which is made available to the code that is using the template processor. This way the collection of applied filters is automated and happens during template evaluation.

The changes proposed here are backwards compatible, and will display filters correctly when the cache is updated (for reviewers remember to force refresh the chart if caching is enabled).

### BEFORE
On a dashboard with a virtual dataset referencing the `filter_values` jinja function, we can see that the ECharts plugin which uses the v1 chart data endpoint is unable to identify the applied filter value correctly due to the column referenced not being available in the dataset. Notice, however, the NVD3 line chart on the right which identifies the filter correctly due to the regex in `viz.py`:
image

### AFTER
Now applied filters are identified correctly both on legacy and v1 charts:
image
When applying a filter whose column isn't 1) available in the dataset 2) referenced in the jinja code, the filter is also correctly identified as being incompatible:
image

### TESTING INSTRUCTIONS
1. Enable the `ENABLE_TEMPLATE_PROCESSING` feature flag.
2. Create a virtual dataset with the following query: `select *, '{{ filter_values('gender', 'unset')[0] }}' as series from random_time_series`
3. Create a legacy and v1 chart referencing the new virtual dataset
4. Create a dashboard with both charts and add a native filter referencing the "gender" column on the "birth_names" dataset
5. Apply a filter, e.g. "boy"
6. See the indicators work on both the new and old chart

### ADDITIONAL INFORMATION
- [x] Has associated issue: closes #15209
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by zhaoyongjie — APPROVED** [review]
LGTM. this approach is better than before.

**Comment by xxcmp1977** [comment]
I'm using from_dttm and to_dttm in my dataset, standard date filter box.
Still can see 'Incompatible filters' yellow warning.

Should it work for from_dttm and to_dttm as well ?

**Comment by igor-lukyanov** [comment]
@villebro could you please help to figure out how to deal w/ 'Incompatible filters' message regarding time columns? 
I.e., {{ from_dttm }} and {{ to_dttm }}. Seems the fix does not cover them, does it? Thank you.

**Comment by alfredomagallon** [comment]
Hello, I am having the same issue with the yellow warning showing when I use {{ from_dttm }} and {{ to_dttm }} in the query.
Any workaround?
Thanks!

**Pull request merged**
