### PR TITLE
fix(explore): adhoc metric label and control value not consistent

### LINKED ISSUE #12367: [Explore] Metric control displayed value is not consistent with current query
#### How to reproduce the bug

1. Go to Explore view
2. open **METRIC** control, choose a different option. (in my screenshot, you will see my old option is `aws...net_cost`, new option is `aws...service_usage`).
3. Not clicking SAVE, just click CLOSE, since I do not want to change Metric anymore
4. open **METRIC** control again, you will see `aws_service_usage` is the chosen metric. actually it should still be `aws_net_cost` since i didn't submit the change.

yWgEshuIzb

### Environment

Latest master

cc @junlincc @zuzana-vej @ktmud

### PR DESCRIPTION
**Pull request by zhaoyongjie**
### SUMMARY
fix  #12367
Closes #12367
- adhoc metric control must reset state when close Popover

### TEST PLAN
add e2e in future

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by junlincc — COMMENTED** [review]
ezgif-3-a8dc7a5057fb

thanks for the PR! input should be cleared when mouse away as well.

**Comment by junlincc** [comment]
ezgif-7-4f780d702728

confirm this has been an issue for a looong time, not introduce by any recent refactoring work 
@zhaoyongjie let's not worry about the mouse away for now 

cc: @ktmud @kgabryje @villebro

**Review by junlincc — APPROVED** [review]

**Comment by zhaoyongjie** [comment]
@junlincc 
The Popover hide when the mouse leaves and click, Unable to change the state of a child component, this is old behavior.

refactor the adhoc metrics in the future, fix it again

**Comment by junlincc** [comment]
nooooo we need code review for this one @villebro need your help reverting. sorry about this 🤦🏾‍♀️

**Comment by zhaoyongjie** [comment]
sorry.....I was too eager. I can revert this commit If needed

**Comment by villebro** [comment]
Let's rather open a new fix PR if possible @zhaoyongjie

**Review by villebro — COMMENTED** [review]
LGTM

**Review by graceguo-supercat — COMMENTED** [review]
LGTM

**Pull request merged**
