### PR TITLE
feat: hide datasource legacy based on featureflag

### PR DESCRIPTION
**Pull request by hughhhh**
### SUMMARY

Hiding legacy datasource view based upon `react_crud_views` flag

#### Flag: False
Screen Shot 2020-10-22 at 8 18 34 PM

#### Flag: True
Screen Shot 2020-10-22 at 8 20 17 PM

### TEST PLAN

1. Goto superset/config.py file
1. Change `ENABLE_REACT_CRUD_VIEWS` to false
1. Check if use `Use Legacy Datasource Editor` btn is hidden in `DatasourceModal` view

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [X] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [X] Removes existing feature or API

### CODE REVIEW

**Comment by willbarrett** [comment]
@lilykuang would you mind giving this a look?

**Review by nytai — APPROVED** [review]
LGTM, but I'm curious what's the motivation for this? Is the idea to fully deprecate the old datasource editor. We have been getting quite a few bug reports on the new datasource editor, are we certain the new datasource editor is at 100% feature parity?

**Review by lilykuang — APPROVED** [review]

**Comment by willbarrett** [comment]
LGTM once green

**Comment by nytai** [comment]
retriggering CI, since https://github.com/apache/incubator-superset/pull/11433 merged

**Pull request merged**
