### PR TITLE
feat(viz): export csv with frontend  the same name

### PR DESCRIPTION
**Pull request by chuancyzhang**
The column names displayed on the report are inconsistent with the column names of the actual exported csv file, which can sometimes cause confusion. Therefore, I hope to add a feature to make the column names displayed on the report consistent with the column names of the exported csv file.

### SUMMARY
Use verbose_map to help the column names of csv export to be consistent with the front-end display

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
BEFORE
image

AFTER 
image

### ADDITIONAL INFORMATION

- [] Has associated issue:
- [] Changes UI
- [] Requires DB Migration.
- [] Confirm DB Migration upgrade and downgrade tested.
- [x] Introduces new feature or API
- [] Removes existing feature or API

### CODE REVIEW

**Comment by willbarrett** [comment]
This seems reasonable to me, but I'd love for @villebro to give it a look as he's much more familiar with this code than I am.

**Comment by villebro** [comment]
This need has come up a few times before, see e.g. #7795. I vote for exports (not only CSV but also JSON) to always use the verbose name, as I believe it's what the users will usually expect.

**Review by villebro — COMMENTED** [review]
This need has come up a few times before, see e.g. #7795. I vote for exports (not only CSV but also JSON) to always use the verbose name, as I believe it's what the users will usually expect.

**Comment by chuancyzhang** [comment]
> This need has come up a few times before, see e.g. #7795. I vote for exports (not only CSV but also JSON) to always use the verbose name, as I believe it's what the users will usually expect.

**Comment by chuancyzhang** [comment]
> This need has come up a few times before, see e.g. #7795. I vote for exports (not only CSV but also JSON) to always use the verbose name, as I believe it's what the users will usually expect.

+1

**Comment by opus-42** [comment]
Hello @chuancyzhang. Thank you for your merge request, this is much needed for the end users.
I would suggest the following update to your merge request:
- Using the `df.rename` function from pandas would do the jobs rather than an inline for loop
- You could as well include metrics and "Time" because the issue does also exist in the same way for metric names.

**Comment by Ibby-B** [comment]
@chuancyzhang , is this change in limbo, would be very useful to get this merged

**Pull request closed without merging**
