### PR TITLE
docs: add VkusVill and TechAudit to users list

### PR DESCRIPTION
**Pull request by ETselikov**

### CODE REVIEW

**Comment by ETselikov** [comment]
@mistercrunch Hi! Can you please review and possibly merge this PR?

**Review by villebro — CHANGES_REQUESTED** [review]
Please place these in the correct alphabetical order, thanks!

**Review by villebro — APPROVED** [review]
LGTM, thanks for the contribution! 🚀

**Comment by ETselikov** [comment]
@villebro Thanks a lot!

**Comment by mistercrunch** [comment]
Glad to have you on board!

**Pull request merged**
