### PR TITLE
[WiP] rename project from Caravel to Superset

### PR DESCRIPTION
**Pull request by mistercrunch**

### CODE REVIEW

**Comment by ascott** [comment]
add new wordmark

screenshot 2016-11-09 16 13 21

**Comment by martinffx** [comment]
why the name change again? Panoramix -> Caravel -> Superset

**Comment by burdiyan** [comment]
Any reasons to change the name again?

**Comment by maver1ck** [comment]
@burdiyan 
Same question here.

**Comment by mistercrunch** [comment]
We think that `Superset` is a superior name to `Caravel`, people can spell it upon hearing it and make an easier logical link from the name to the product. It just "sticks" more and feels right. We have cool ideas for logo and iconography, and this time the whole team is rallying behind the name. We also didn't like the fact that `Caravel` is linked to the colonization theme, which can be associated with dark historical events (which I didn't think about initially, but couldn't "unsee" it once it was brought up). 

It's also a new beginning where Airbnb is doubling down on the project with a dedicated team of 4-5 people, and an ambitious increase in scope, now including SQL Lab and the will to expose the building blocks as a library of composable React components that can be used in analytical applications easily.

**Comment by bkyryliuk** [comment]
@ceilingcat - 
```
pip uninstall caravel
pip install superset
superset init
superset db upgrade
superset runserver ...
```
should do it.

**Pull request merged**
