### PR TITLE
Show only Slices and Dashboards users have access to

### PR DESCRIPTION
**Pull request by mistercrunch**
@michellethomas @williaster 
- Materialized the perm associated to the slice in the slice model to make queries faster when listing Dashboards and Slices.
- Also added Many to many owners for slices and dashboards, should eventually define who can alter the objects, looking for the proper hook in FAB

### CODE REVIEW

**Comment by x4base** [comment]
@mistercrunch 
So right now whether a user can access a dashboard is determined by whether the role has the datasource access. It has nothing to do with whether the user is the owner of the slice or dashboard. Am I correct? Thanks

**Comment by mistercrunch** [comment]
`Admin` and `Alpha` have access to all datasources, `Gamma` user need and extra role with specific datasource access to list and access dashboard and slices

**Comment by mistercrunch** [comment]
I'm planning on making it such that only object owners can alter dashboards and slices. This PR added the possibility to add many owners to a dashboard or slice, but that is not taken into account yet. I opened issues to ask the Flask AppBuilder project on advice on how to implement that

**Comment by x4base** [comment]
So in your plan it is only for the access control of editing dashboards/slices, right? Do you think it is good to have the view access control on whether a user can see a certain dashboard/slice, maybe like #357 ? Is it in any of your plans?

**Comment by MrMauricioLeite** [comment]
Hi @x4base, I guess that @mistercrunch is going to finish the edit permissions first and them extend for view permissions once we have the edit fixed.

But that sure is needed to deploy here at our company too so I'm keeping this issue on my bookmarks.

**Comment by hamidmahmoodnbs** [comment]
can anybody confirm that has this issue been fixed or not? https://github.com/apache/incubator-superset/issues/1434

**Comment by pbr0ck3r** [comment]
@hamidmahmoodnbs seems like the slices/dashboard/schema filtering works. But the databases themselves are not filtered based on roles/permissions. On load of the SQL editor all databases are returned. Even if you have a role such as `database access on x.[id:5]` you get that database and all of the others. Instead of only getting x. Seems like a security issue to me.

**Comment by pbr0ck3r** [comment]
@mistercrunch databases are not being filtered at all. Every user is returned all databases. Even if they only have a role such as `database access x.[id:5]` they still get all databases.

**Pull request merged**
