### PR TITLE
feat: Set datasource panel open by default on Explore view

### PR DESCRIPTION
**Pull request by kgabryje**
### SUMMARY
Datasource panel is open by default when user enters Explore view

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
image

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [x] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

CC: @ktmud @junlincc

### CODE REVIEW

**Comment by ktmud** [comment]
Should this state be persistent?

**Comment by kgabryje** [comment]
> Should this state be persistent?

I'm not aware of such requirement. @junlincc What do you think?

**Comment by zhaoyongjie** [comment]
can provide the client to save this status?

**Comment by junlincc** [comment]
> > Should this state be persistent?
> 
> I'm not aware of such requirement. @junlincc What do you think?

the data panel should be collapsible at this intermediate stage, we should make it persistent when both drag and drop control panel and panel width resizing are available this year.

**Review by ktmud — APPROVED** [review]
LGTM

**Review by junlincc — APPROVED** [review]
LGTM. 

ezgif-4-8e5c2d90686c


@kgabryje let's get [Fixed width for dataset panel ](https://github.com/apache/incubator-superset/pull/12221)test done as well soon to have a perfect data panel. thanks for the enhancement!

**Pull request merged**
