### PR TITLE
[WIP] Persist SQL Lab state in the backend

### PR DESCRIPTION
**Pull request by betodealmeida**
### CATEGORY

Choose one

- [ ] Bug Fix
- [ ] Enhancement (new features, refinement)
- [X] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY

This PR implements [SIP-23](https://github.com/apache/incubator-superset/issues/7748), moving the persistence of SQL Lab state from the browser's `localStorage` to the backend.

Currently, the redux store in `localStorage` has the following structure:

```javascript
sqlLab: {
  activeSouthPaneTab: "Results",
  alerts: [],
  databases: {...},
  offline: false,
  queries: {...},
  queriesLastUpdate: 1565918142000,
  queryEditors: [...],
  tabHistory: [...],
  tables: [...],
}
```

With this PR, when loading SQL Lab the following keys are loaded from the DB:

- `databases`
- `queries`
- `queryEditors` (from the new tables `tab_state_view` and the `table_schema`)
- `tables` (from the new table `table_schema`)

As the user interacts with SQL Lab, changes to `queryEditors`, `tables` and `queries` are synced to the backend automatically. This includes the SQL being written, the table schemas being displayed (expanded or not), the database/schema selected, the active tab, etc.

For queries, as soon as a new tab is open we create a row in the `query` table to store the query, even if it hasn't run. This and the syncing of `queryEditors` and `tables` is done through new custom views created in this PR, `/tabstateview/` and `/tableschemaview/`.

For results, I changed the backend so that sync queries are also stored in the results backend if one is configured. This allows us to fetch the results when a tab is loaded, without having to store them in the database, since they can be large.

#### Migration

This PR requires a DB migration to set up the initial tables, `tab_state` and `table_schema`. When a user first visits SQL Lab after this migration, the state of the following keys will be a **combination** of the backend (nothing, initially) and their `localStorage`:

- `queryEditors`
- `tables`
- `tabHistory`

When `<TabbedSqlEditors>` mounts, it will identify objects in these keys that come from `localStorage`, and migrate them to the backend with a custom action `migrateLocalStorage`. Once one of these objects has been migrated successfully, it is removed from `localStorage`, so that the migration doesn't have to be atomic.

Once everything has been migrated, the `redux` key in `localStorage` is removed.

#### Concurrent access from multiple browser tabs

It's a non-goal in this PR to handle users working on the same query editor from multiple tabs. The current behavior remains: the last update is persisted.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

There are no visible changes.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [X] Requires DB Migration.
- [X] Confirm DB Migration upgrade and downgrade tested.
- [X] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by graceguo-supercat** [comment]
Thanks for the implementation. Can you describe the new architecture a little bit, like when and where to store query, what is flow look like when user interact with multiple tabs and browsers?

**Comment by betodealmeida** [comment]
@graceguo-supercat:

> Thanks for the implementation. Can you describe the new architecture a little bit, like:
> when and where to store sql lab state,
> which state data is persist and which are not,
> what is flow look like when user interact with multiple tabs and browsers?

Everything is synced to the backend, including query, tales (and if expanded or not), data preview, results (fetched from the backend), tab title, active tab, selected DB, etc. All changes are stored asynchronously, and the sync of the SQL query itself is done with debouncing.

For multiple tabs and browsers, the old experience remains: the last edit wins. I think we should improve that experience, but the goal for this PR is to move state management to the backend, without changing ay extra functionality.

**Comment by graceguo-supercat** [comment]
Hi @betodealmeida In the new implementation, do you store actual query results in table? when query results are huge, it will be a problem for storage. and when user refresh browser, do they download query results again and again?

**Comment by betodealmeida** [comment]
@graceguo-supercat 

> Hi @betodealmeida In the new implementation, do you store actual query results in table? when query results are huge, it will be a problem for storage. and when user refreshing browser, do they download query results again?

No, I changed the backend so that sync queries are also stored in the results backend (if it's configured), similar to async queries. Then when we load the tab we load the results from the results backend.

**Comment by betodealmeida** [comment]
Recreating this on https://github.com/apache/incubator-superset/pull/8060

**Pull request closed without merging**
