### PR TITLE
[bugfix] EventFlow does not display

### PR DESCRIPTION
**Pull request by jnishiyama**
Fixes issue introduced by the commit linked below.

https://github.com/apache/incubator-superset/commit/5282f39026be01f5f40b3aea8c51cbcc3b254895#diff-c95adaa458ba2159723bc3d2c4e3181c

### CODE REVIEW

**Comment by kristw** [comment]
Thank you for reporting the bug, but it would be better to fix to address the underlying issue why `loadTransformProps`, which provides lazy-loading of the same function, does not work correctly. 

Could you try to change how `SuperChart` handle `transformProps` coming back from lazy-loading on line 87 in `SuperChart.jsx`?

```js
const transformProps = loaded.transformProps.default || loaded.transformProps;
```

**Comment by jnishiyama** [comment]
@kristw Before I make the change, what is the benefit of the lazy-load here? This strategy is only taken in Mapbox and EventFlow chart plugins, and it isn't clear to me why (I'm very new to the repo). If there is a benefit, then why not apply to all the chart plugins? If there is no benefit, then why not just be consistent in the method of loading the transformProps?

**Comment by kristw** [comment]
Mapbox and eventflow import external lib in transformProps that are not used anywhere else while the other transformProps are plain js. So it will be better not to include these deps in main bundle and only load them when they are used. The plain js transformprops are tiny and has more benefits to be included in bundle than lazy load tiny file.

**Comment by jnishiyama** [comment]
Ok, understood, will commit the changes soon.

**Review by kristw — APPROVED** [review]

**Pull request merged**
