### PR TITLE
Removing empty filters from explore url

### PR DESCRIPTION
**Pull request by michellethomas**
We've been having issues with urls that are too long. This is one quick solution where getExploreUrl removes any filters where the value is empty. These seem to be getting added from the dashboard filters, but I don't believe they are needed.

This will mean that even if an empty filter is set, it won't get saved to the slice. Is there any reason someone would need to set an empty filter?

I tested creating and saving a slice with an empty filter. The filter does not get saved with the slice. On a dashboard a filter works with that slice.

### CODE REVIEW

**Comment by graceguo-supercat** [comment]
LGTM

**Comment by michellethomas** [comment]
@mistercrunch thoughts on this?

**Comment by mistercrunch** [comment]
I think this helps but ultimately should be handled at the source where the `FilterControl` should not post empty filters. Meaning that the FilterControl internal state might have incomplete filters (say from the moment the user hits `+`, until they set the value), but probably should not communicate back the incomplete filters to the redux state until the filter is set properly. While filters are incomplete/invalid they could show a bit of red.

Once its fixed at the source we could have a DB migration to clean the saved slices with empty filters.

All of this may not be super hi-pri though.

**Comment by michellethomas** [comment]
Thanks @mistercrunch, I looked into removing blank filters from the `addFilter` function in Dashboard.jsx. I'll add that in once @graceguo-supercat gets her Dashboard refactor in.

When I was testing it seems there was still a problem where getExploreUrl was getting called with an old version of `preselect_filters` in superset.js (and was adding empty filters as a result). I'll look into that after the Dashboard refactor.

So it seems like I'll close this PR and solve this problem in followup prs unless anyone objects.

**Comment by mistercrunch** [comment]
No objections on my side

**Pull request closed without merging**
