### PR TITLE
fix: Jumpiness of datasource modal

### LINKED ISSUE #12469: [explore]chart save modal scroll and dropdown
https://user-images.githubusercontent.com/67837651/104363247-c5493100-54c9-11eb-9b6f-ded5f033985c.mp4

related to https://github.com/apache/superset/issues/12310(fixed issues in dashboard) 

obviously this behavior is global in Superset. addressing in one modal is not enough

@adam-stasiak pls give a round of audit in the product and look for all areas that are being affected, and list those in comment. 🙏

### LINKED ISSUE #12503: [Explore]modal jumpiness is back, added scroll bar outside the modal
We recently fixed the height and added a scrollbar to the list to prevent jumpiness when user type in search, with plan having Warning, Search and Header sticky in the modal.  

In latest master, the jumpiness is back, and the page is added scroll bar outside the modal. 

https://user-images.githubusercontent.com/67837651/104509449-8a64fd00-559e-11eb-9966-a3f11ed871f4.mov]

https://user-images.githubusercontent.com/67837651/104510604-4246da00-55a0-11eb-9c49-6736959187f3.mov

related to: https://github.com/apache/superset/pull/12471/files 

Expected behavior of this modal:
1. Warning, Search and Header sticky on top
2. Scroll on table body inside the modal
3. Modal fixed height and width 

@geido will implement the changes back with. 

@eschutho please help test PR throughout before/after merging 🙏

### PR DESCRIPTION
**Pull request by geido**
### SUMMARY

Partially fixes #12503

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

BEFORE:

https://user-images.githubusercontent.com/60598000/104509562-210adb80-55ea-11eb-8344-d9d753eb0d89.mp4

AFTER:

https://user-images.githubusercontent.com/60598000/104509580-26682600-55ea-11eb-92f6-efe86d1192ac.mp4

### TEST PLAN
1. Open the datasource modal in Explore
2. Make sure the modal has a fixed height and jumpiness is removed

### ADDITIONAL INFORMATION

- [x] Has associated issue: #12503
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by geido** [comment]
@junlincc

**Comment by adam-stasiak** [comment]
I see that modal for changing dataset is now very small and has additional line paris_iris_mapping and multiformat_time_series:

https://user-images.githubusercontent.com/25153919/104512482-94aee780-55ee-11eb-9012-8e3c9afd071e.mov

**Comment by geido** [comment]
@adam-stasiak I will increase the height a bit. The other issue you are mentioning seems unrelated.

**Comment by adam-stasiak** [comment]
Thank you - I compared other issue place on master and did not observe this. I did not spot any other issues.

**Comment by geido** [comment]
Hello @adam-stasiak. What I have found out is that the footer of the Modal was showing even though it was not supposed to. The problem wasn't visible on master as the footer went all the way down, but it becomes visible by reducing the height. I have fixed that issue and also increased the height as you suggested. Please have a look


https://user-images.githubusercontent.com/60598000/104572859-7e3b7700-5654-11eb-9d63-68a040d940ce.mp4

**Comment by junlincc** [comment]
@geido i looked at this PR, it does not solved the drop down issue in the Save Modal,
and does not include all the other requests in #12503 

The jumpiness is resolved though. not ready for merging.

**Comment by ktmud** [comment]
Is this a stop-gap fix? Because the dataset modal isn't implemented as described in #12503 .

Only the table body should be scrollable. We should replace the table with the same implementation as in the table viz or Data preview on the Explore page.

**Comment by geido** [comment]
Hello @ktmud. I believe the issue you are referring to is this #12488 and it's in progress in a separate PR.

**Comment by ktmud** [comment]
#12503  also described how the scroll area should look like.

**Comment by junlincc** [comment]
Thanks for updating the title and description. after removing the code that attempts to fix the dropdown issue globally, this PR should be ready for testing again - jumpiness in Change dataset modal. @geido

**Comment by geido** [comment]
I think I am now seeing the issue. I am not confident anymore to apply the fix globally to the modals as we might end up in scenarios like the one depicted here https://github.com/apache/superset/pull/11770#issuecomment-741438519. I am only including the fix to the jumpiness in this PR as of now. 

For the "Save" modal issue specifically, this #12522 should be preferred even though it is not a global fix. 

As for the sticky components described in #12488  and #12503 I'll be providing them in a separate PR asap.

@junlincc @ktmud

**Comment by ktmud** [comment]
Thank you for the diligent work, @geido ! Yes, I agree it's better to address the jumpiness and scrollable areas in separate PRs.

**Comment by junlincc** [comment]
oh well, between jumpiness and the regression I introduced ... i chose the jumpiness 🤦🏾‍♀️
let's wait for the other PR that address the sticky issue first.

**Comment by geido** [comment]
Let's open a PR addressing the modal issues as discussed. I am closing this one.

**Pull request closed without merging**
