### PR TITLE
attributions section

### PR DESCRIPTION
**Pull request by rusackas**
### CATEGORY

Choose one

- [ ] Bug Fix
- [ ] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [x] Documentation

### SUMMARY

Two fonts in use are under the SIL Open Font license. This PR explicitly names them in the Readme, just to make certain we meet ASF requirements for transparency. 

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### REVIEWERS
@mistercrunch let me know if this seems like a reasonable place in the Readme to wedge it in. I figured it should be near the bottom, but keeping the "Who uses Apache Superset" section at the very end seemed like a good idea :)

### CODE REVIEW

**Review by etr2460 — COMMENTED** [review]
any reason not to have an ATTRIBUTIONS.md file instead of adding it to the README? This file is already pretty big and I think we should be factoring things out of it (like making an INTHEWILD.md for companies that use superset) rather than adding more to it

**Comment by rusackas** [comment]
> any reason not to have an ATTRIBUTIONS.md file instead of adding it to the README? This file is already pretty big and I think we should be factoring things out of it (like making an INTHEWILD.md for companies that use superset) rather than adding more to it

Agreed it's already pretty big, and I'd hoped not to put it in here (thinking the License.txt file might be sufficient), but ASF requires it to be "prominent" and suggests the ReadMe:

Pasted_Image_3_9_20__11_17_AM

**Comment by etr2460** [comment]
:/ Could we clarify what's acceptable with one of our mentors? Maybe we could link out to an ATTRIBUTIONS file from the README too?

**Comment by rusackas** [comment]
@justinmclean Not sure if you're able to jump in here with an opinion... would a link from `README.md` to a (new) `ATTRIBUTIONS.md` file containing attributions for SIL Open Font Licensed binaries satisfy the "appropriate and prominent label" requirement of the Appropriately Labeled Condition?

**Comment by justinmclean** [comment]
For Category B you need to add teh licensing information to LICENSE and that should cover it. Only putting something an attribution.md is not really an prominent label IMO, but it's OK if it's in LICENSE and somewhere else.

**Comment by mistercrunch** [comment]
Oh @justinmclean , so we don't need this?  For context we already have it in LICENSE.txt here https://github.com/apache/incubator-superset/blob/master/LICENSE.txt#L211-L216

But the text here (https://www.apache.org/legal/resolved.html#appropriately-labelled-condition) seemed to say that we needed something more prominent (like README.md)

**Comment by justinmclean** [comment]
Hi,
‘
Feel free to ask on legal or incubator list but IMO LICENSE is good enough in this case.

Thanks,
Justin

**Comment by rusackas** [comment]
Thanks for the input @justinmclean, we appreciate it. We'll close this PR and let LICENSE.txt do the work for us, then. :)

**Pull request closed without merging**
