### PR TITLE
Make Table Columns & Metrics Bulk-actionable

### PR DESCRIPTION
**Pull request by alanmcruickshank**
Adds the DeleteMixin to both the sqlalchemy table column view and the SQL metric view to allow mass column management. Very useful for removing large numbers of auto-generated fields.

### CODE REVIEW

**Comment by rhunwicks** [comment]
@alanmcruickshank @mistercrunch I'm not certain (because I am not a JavaScript developer), but I think I have a problem caused by this on my instance where attempting to delete Metrics gives an error like:

```
        Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/views.py", line 574, in action_post
    return action.func(items)
  File "/usr/src/app/superset/views/base.py", line 284, in muldelete
    self._delete(item.id)
AttributeError: 'NoneType' object has no attribute 'id'
```

If I look at the network requests issued by the browser, I can see:

`POST http://localhost:8000/tablecolumninlineview/action_post 500`

I.e. the browser is posting to `tablecolumninlineview` even though the Metrics tab is the one selected.

I can see that selecting the Delete option from the Actions drop down is running:

```
onclick="return modelActions.execute_multiple('muldelete','Delete all Really?');"
```

But I can't see how it work's out which model it is using.

It should be easy to test on your instance(s) just by looking at the network requests the browser is issuing and working out if they apply to the correct model in all cases.

**Comment by rhunwicks** [comment]
Note that if there are actuallys Column for the same Table that have the same pk as the Metrics you are deleting, then I think it will delete those instead and return successfully.

**Comment by alanmcruickshank** [comment]
@rhunwicks Looking at the request it sends, it's not currently dangerous - i.e. it won't delete Tables with the same pk (it's passing through a variable with the wrong name to do that - hence the error).

You are however completely right that this isn't working as intended. Thanks for reporting!

I'll take a look at it this week.

**Comment by rhunwicks** [comment]
@alanmcruickshank on my setup I think it is deleting Columns that have the same pk as the Metric you are trying to delete, rather than the Table. It's not very likely, but I think it is dangerous - because I noticed it when I tried to delete all the Metrics and found that I had delete all the columns for the Table instead.

**Comment by alanmcruickshank** [comment]
@rhunwicks Right you are - I've just been digging into why this happens.

The issue we've got is tied in with FAB. On clicking the apply actions button it submits a hidden form called `#action_form`, and in this case there are several of those to choose from. One for `TableColumnInlineView` and one for `SqlMetricInlineView`. Depending on which form you're on it might pick the wrong one.

I've added a pull request to roll this back for now. I'll also raise an issue with FAB to see if we can get this fixed.

**Pull request merged**
