### PR TITLE
[fix] Use HTTPS, not HTTP wherever practical

### PR DESCRIPTION
**Pull request by hajdbo**

### CODE REVIEW

**Comment by kristw** [comment]
`package-lock.json` is auto-generated by `npm`. Your changes will be overridden next time we change dependency. I would suggest removing it from this PR.

**Comment by hajdbo** [comment]
> `package-lock.json` is auto-generated by `npm`. Your changes will be overridden next time we change dependency. I would suggest removing it from this PR.

Done, thanks for the tip.

**Comment by mistercrunch** [comment]
Did you test that all the altered links work? Some static/doc website still don't support https sometimes...

**Comment by hajdbo** [comment]
> Did you test that all the altered links work? Some static/doc website still don't support https sometimes...

I tested all, manually. I did not change the http links when the website did not accept https. I also did not change the Apache http links, even though apache.org supports https, because the official licence text still points to the http:// address

**Pull request merged**
