### PR TITLE
fix(ar-modal): updateNotificationSettings not updating state

### PR DESCRIPTION
**Pull request by fisjac**
### SUMMARY

When changing the recipients list for an existing notification method, the state is not being changed properly. This change addresses this by reinstating missing code that was lost in a previous PR.
### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

image

image

### ADDITIONAL INFORMATION

- [x] Has associated issue: https://github.com/apache/superset/issues/28149#issuecomment-2100612644
- [x] Required feature flags: ALERT_REPORTS
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by sfirke — COMMENTED** [review]
I can't speak to the code itself sorry but the bug is real and it's addressing the right part of the codebase.  Thanks @fisjac !

**Comment by alexkyurtev** [comment]
Hello , when do you expect the PR to be merged ?

**Review by dpgaspar — APPROVED** [review]
can you add a unit test for `updateNotificationSetting`

**Review by mistercrunch — APPROVED** [review]
Rush-merging since this needs to make an imminent cut.

**Comment by alexkyurtev** [comment]
Hello , I suppose that the changes are live now ? Or ?

**Comment by sfirke** [comment]
These changes would be live on master branch (you could run the nightly, unstable build image `apache/superset:latest` to verify) but did not make it into 4.0.1.  They will be present in 4.0.2 and 4.1.0.

**Comment by Nick-ATOR** [comment]
Is there any way to directly implement this fix in a K8s deployment?

**Comment by sfirke** [comment]
If a community member wanted to take the 4.0.1 release, cherry-pick this PR onto it, and package it up for the world, that might be widely useful. I hope 4.0.2 and 4.1.0 come out soon but in the meantime someone could run with that.

**Pull request merged**
