### PR TITLE
Expanding section on contributing to docs

### PR DESCRIPTION
**Pull request by dylburger**
Expanded on documentation section, running through an example of committing a change to the docs end-to-end and describing the process for adding static assets

### CODE REVIEW

**Comment by mistercrunch** [comment]
img

**Comment by xrmx** [comment]
This is great but why do we mention mysql-connector there?

**Comment by dylburger** [comment]
@xrmx when I was installing dependencies from dev-reqs.txt, `mysqlclient` required mysql-connector. Instead of directing users to install the sphinx dependencies alone, I thought I'd just have users install mysql-connector and install _all_ required dependencies.

I can understand how this can be confusing for users interested in hacking on the docs alone. I could create a `docs-reqs.txt` file with these requirements:

    sphinx
    sphinx-rtd-theme
    sphinxcontrib.youtube

and direct users to install that subset, if you think that makes more sense?

**Comment by xrmx** [comment]
Yeah, but for the same reason you should have done the same for postgres as there's psycopg2 on that list too :)

Creating a requirements for the docs would make a lot of sense to me, bonus points if you add `-r docs-reqs.txt` in dev-reqs.it instead of duplicating the sphinx packages.

**Comment by dylburger** [comment]
@xrmx agreed this makes sense. I had no idea about the -r <file> option for chaining requirements from multiple files - awesome!

Fixed this [here](https://github.com/airbnb/superset/pull/2049)

**Pull request merged**
