### PR TITLE
fix(celery): Reset DB connection pools for forked worker processes

### LINKED ISSUE #9860: Celery task execution failing due to "PGRES_TUPLES_OK" DB error.
Hi,
I am using superset 0.36 version, have scheduled 30 chart email jobs for every 30 minutes. There are some times getting an error "DatabaseError('(psycopg2.DatabaseError) error with status PGRES_TUPLES_OK and no message from the libpq')" like this. I am using celery component with Redis db. Using flower to monitor schedule jobs providing you screenshot below for reference. Please suggest any idea's here.
Thanks mates.

Versions:
celery==4.4.2
flower==0.9.4
redis==3.5.0
Python==3.7

Screenshot:
image

### Expected results

what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### LINKED ISSUE #10530: celery SQLAlchemy errors in celery tasks that use sqlalchemy pools
While running multiple `alert.run_query` celery tasks, some tasks fail with a `sqlalchemy.exc.NoSuchColumnError` error here https://github.com/apache/incubator-superset/blob/ece91928a9339190163c0bc72b96e51217a90d1e/superset/tasks/schedules.py#L544 on the first few iterations of the celery beat schedule after its initialization. These errors eventually stop occurring if the celery worker and the beat schedule are left to run for a few iterations without stopping.  Tests have shown that the errors stop occurring on average after around 2 iterations of the beat schedule.

### Expected results

Alerting celery tasks run without error

### Actual results

```
Traceback (most recent call last):
  File "/srv/yaps/mounts/superset/superset_build/bbe899d629f9d61e5d2a8ffdccbcc57724a557ea-e230e418e5960bc45d735cb21d806661/celery.runfiles/__main__/thirdparty/superset_python3/pip/celery/celery-cpython-38/lib/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/srv/yaps/mounts/superset/superset_build/bbe899d629f9d61e5d2a8ffdccbcc57724a557ea-e230e418e5960bc45d735cb21d806661/celery.runfiles/__main__/thirdparty/superset_python3/superset-cpython-38/lib/superset/app.py", line 115, in __call__
    return task_base.__call__(self, *args, **kwargs)
  File "/srv/yaps/mounts/superset/superset_build/bbe899d629f9d61e5d2a8ffdccbcc57724a557ea-e230e418e5960bc45d735cb21d806661/celery.runfiles/__main__/thirdparty/superset_python3/pip/celery/celery-cpython-38/lib/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/srv/yaps/mounts/superset/superset_build/bbe899d629f9d61e5d2a8ffdccbcc57724a557ea-e230e418e5960bc45d735cb21d806661/celery.runfiles/__main__/thirdparty/superset_python3/superset-cpython-38/lib/superset/tasks/schedules.py", line 562, in schedule_alert_query
    if run_alert_query(
  File "/srv/yaps/mounts/superset/superset_build/bbe899d629f9d61e5d2a8ffdccbcc57724a557ea-e230e418e5960bc45d735cb21d806661/celery.runfiles/__main__/thirdparty/superset_python3/superset-cpython-38/lib/superset/tasks/schedules.py", line 672, in run_alert_query
    deliver_alert(alert_id)
  File "/srv/yaps/mounts/superset/superset_build/bbe899d629f9d61e5d2a8ffdccbcc57724a557ea-e230e418e5960bc45d735cb21d806661/celery.runfiles/__main__/thirdparty/superset_python3/superset-cpython-38/lib/superset/tasks/schedules.py", line 579, in deliver_alert
    alert = scoped_session.query(Alert).get(alert_id)
  File "/srv/yaps/mounts/superset/superset_build/bbe899d629f9d61e5d2a8ffdccbcc57724a557ea-e230e418e5960bc45d735cb21d806661/celery.runfiles/__main__/pip/SQLAlchemy/SQLAlchemy-cpython-38/lib/sqlalchemy/orm/query.py", line 1021, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "/srv/yaps/mounts/superset/superset_build/bbe899d629f9d61e5d2a8ffdccbcc57724a557ea-e230e418e5960bc45d735cb21d806661/celery.runfiles/__main__/pip/SQLAlchemy/SQLAlchemy-cpython-38/lib/sqlalchemy/orm/query.py", line 1138, in _get_impl
    return db_load_fn(self, primary_key_identity)
  File "/srv/yaps/mounts/superset/superset_build/bbe899d629f9d61e5d2a8ffdccbcc57724a557ea-e230e418e5960bc45d735cb21d806661/celery.runfiles/__main__/pip/SQLAlchemy/SQLAlchemy-cpython-38/lib/sqlalchemy/orm/loading.py", line 287, in load_on_pk_identity
    return q.one()
  File "/srv/yaps/mounts/superset/superset_build/bbe899d629f9d61e5d2a8ffdccbcc57724a557ea-e230e418e5960bc45d735cb21d806661/celery.runfiles/__main__/pip/SQLAlchemy/SQLAlchemy-cpython-38/lib/sqlalchemy/orm/query.py", line 3458, in one
    ret = self.one_or_none()
  File "/srv/yaps/mounts/superset/superset_build/bbe899d629f9d61e5d2a8ffdccbcc57724a557ea-e230e418e5960bc45d735cb21d806661/celery.runfiles/__main__/pip/SQLAlchemy/SQLAlchemy-cpython-38/lib/sqlalchemy/orm/query.py", line 3427, in one_or_none
    ret = list(self)
  File "/srv/yaps/mounts/superset/superset_build/bbe899d629f9d61e5d2a8ffdccbcc57724a557ea-e230e418e5960bc45d735cb21d806661/celery.runfiles/__main__/pip/SQLAlchemy/SQLAlchemy-cpython-38/lib/sqlalchemy/orm/loading.py", line 101, in instances
    cursor.close()
  File "/srv/yaps/mounts/superset/superset_build/bbe899d629f9d61e5d2a8ffdccbcc57724a557ea-e230e418e5960bc45d735cb21d806661/celery.runfiles/__main__/pip/SQLAlchemy/SQLAlchemy-cpython-38/lib/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/srv/yaps/mounts/superset/superset_build/bbe899d629f9d61e5d2a8ffdccbcc57724a557ea-e230e418e5960bc45d735cb21d806661/celery.runfiles/__main__/pip/SQLAlchemy/SQLAlchemy-cpython-38/lib/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/srv/yaps/mounts/superset/superset_build/bbe899d629f9d61e5d2a8ffdccbcc57724a557ea-e230e418e5960bc45d735cb21d806661/celery.runfiles/__main__/pip/SQLAlchemy/SQLAlchemy-cpython-38/lib/sqlalchemy/orm/loading.py", line 81, in instances
    rows = [proc(row) for row in fetch]
  File "/srv/yaps/mounts/superset/superset_build/bbe899d629f9d61e5d2a8ffdccbcc57724a557ea-e230e418e5960bc45d735cb21d806661/celery.runfiles/__main__/pip/SQLAlchemy/SQLAlchemy-cpython-38/lib/sqlalchemy/orm/loading.py", line 81, in <listcomp>
    rows = [proc(row) for row in fetch]
  File "/srv/yaps/mounts/superset/superset_build/bbe899d629f9d61e5d2a8ffdccbcc57724a557ea-e230e418e5960bc45d735cb21d806661/celery.runfiles/__main__/pip/SQLAlchemy/SQLAlchemy-cpython-38/lib/sqlalchemy/orm/loading.py", line 525, in _instance
    tuple([row[column] for column in pk_cols]),
  File "/srv/yaps/mounts/superset/superset_build/bbe899d629f9d61e5d2a8ffdccbcc57724a557ea-e230e418e5960bc45d735cb21d806661/celery.runfiles/__main__/pip/SQLAlchemy/SQLAlchemy-cpython-38/lib/sqlalchemy/orm/loading.py", line 525, in <listcomp>
    tuple([row[column] for column in pk_cols]),
  File "/srv/yaps/mounts/superset/superset_build/bbe899d629f9d61e5d2a8ffdccbcc57724a557ea-e230e418e5960bc45d735cb21d806661/celery.runfiles/__main__/pip/SQLAlchemy/SQLAlchemy-cpython-38/lib/sqlalchemy/engine/result.py", line 681, in _key_fallback
    util.raise_(
  File "/srv/yaps/mounts/superset/superset_build/bbe899d629f9d61e5d2a8ffdccbcc57724a557ea-e230e418e5960bc45d735cb21d806661/celery.runfiles/__main__/pip/SQLAlchemy/SQLAlchemy-cpython-38/lib/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
sqlalchemy.exc.NoSuchColumnError: "Could not locate column in row for column 'alerts.id'"
```

#### How to reproduce the bug

1. install geckodriver
2. set up config.py to enable alerting
```python
ENABLE_ALERTS = True
FEATURE_FLAGS = {"THUMBNAILS": True}

THUMBNAIL_SELENIUM_USER = "Admin"
celery_alerting = {'alerts.schedule_check': {
        'task': 'alerts.schedule_check',
        'schedule': crontab(minute='*/1'),
    }}
CeleryConfig.CELERYBEAT_SCHEDULE.update(celery_alerting)
CELERY_CONFIG = CeleryConfig
```
3. Go to Manage -> Alerts
4. Create a few alerts (~6) that will run at the same time
5. Start a celery worker and celery beat
6. See error in celery worker
### Environment

- superset version: 0.37
- python version: 3.7.7

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### LINKED ISSUE #12913: [async] error: component not found for job <id>
We are sporadically seeing the error 'component not found for job <id>' in the dev console when loading dashboards with Global Async turned on. The charts never loads. When searching through the network requests, we can see that the api request to async_event does in fact return the correct job and we can follow the result_url in that api response to the data of the missing chart. It does not make a call to the explore_json/data api for that chart. 

Just a shot in the dark: My thoughts are possibly a race condition between loading of the ui components and the return of the api response? It seems to always be the first charts that return from async_result api (and usually in a separate request from the others that do end up loading)

### Expected results

Charts to load properly

### Actual results

Chart never loads, and error 'component not found for job <id>' warning in console. 

#### Screenshots
Screen Shot 2021-02-03 at 12 12 58 AM

Screen Shot 2021-02-03 at 12 13 51 AM

#### How to reproduce the bug

1. Turn on Global Async
2. Create dashboard/charts
3. load dashboard
4. reload dashboard after cache
5. may need to refresh a couple of times and wait for a chart to continuously have the spinning loader / the error in the console show up. it is very sporadic

### Environment

(please complete the following information):

- superset version:  master 9fa52d3
- python version: 3.8
- node.js version: 12

postgres backend
redis cache storage
redis async storage

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by robdiciuccio**
### SUMMARY

Adds a listener for the `worker_process_init` Celery [signal](https://docs.celeryproject.org/en/4.4.2/userguide/signals.html#worker-process-init) that disposes of and resets the SQLAlchemy connection pool being passed to the forked process.

Resolves the intermittent `sqlalchemy.exc.NoSuchColumnError` reported in #10530 and #12766 and the following error reported in #9860:
```
sqlalchemy.exc.DatabaseError: (psycopg2.DatabaseError) error with status PGRES_TUPLES_OK and no message from the libpq
```

This fix is primarily related to the default `prefork` Celery execution pool, but was also tested with the following pool invocations:

```
celery worker --app=superset.tasks.celery_app:app -Ofair -l INFO
```
```
celery worker --app=superset.tasks.celery_app:app --pool=threads -c 12 -l INFO
```
```
celery worker --app=superset.tasks.celery_app:app --pool=gevent -c 12 -l INFO
```

This configuration was tested with [async queries](https://github.com/apache/superset/pull/11499) enabled to place load on the celery workers, in both standalone and Docker-based workflows.

This PR also includes a fix for a client-side race condition in loading charts asynchronously (fixes #12913).

References:
https://docs.sqlalchemy.org/en/13/core/connections.html#engine-disposal
https://www.yangster.ca/post/not-the-same-pre-fork-worker-model/

### TEST PLAN
Asynchronous tasks should run without `sqlalchemy.exc.NoSuchColumnError` when celery is run in `prefork` mode.  See #10530 and #12766 for reproducability.

### ADDITIONAL INFORMATION

- [x] Has associated issue: Fixes #9860, #10530, #12766 and #12913
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by craig-rueda — APPROVED** [review]
LGTM

**Review by dpgaspar — APPROVED** [review]
Nice! but does this happen even when using null pool on the workers? or do you think there's still uses of QueuePool create by flask-sqlalchemy at the worker level?

**Comment by robdiciuccio** [comment]
@dpgaspar the `app.db` instance doesn't appear to use the null pool with the metadata database. I know we're using that elsewhere to get around this forking issue, which I'm planning on reviewing after this fix is merged.

**Comment by dpgaspar** [comment]
> @dpgaspar the `app.db` instance doesn't appear to use the null pool with the metadata database. I know we're using that elsewhere to get around this forking issue, which I'm planning on reviewing after this fix is merged.

workers when accessing the metadata db should use: https://github.com/apache/superset/blob/master/superset/utils/celery.py#L33

Let's talk about this?

**Comment by robdiciuccio** [comment]
Talked with @dpgaspar and we agree this is a good first step, and more DB connection pool investigation is required. Merging.

**Pull request merged**
