### PR TITLE
feat(viz): export csv with verbose_name

### PR DESCRIPTION
**Pull request by chuancyzhang**
The column names displayed on the report are inconsistent with the column names of the actual exported csv file, which can sometimes cause confusion. Therefore, I hope to add a feature to make the column names displayed on the report consistent with the column names of the exported csv file.

### SUMMARY
Use verbose_map to help the column names of csv export to be consistent with the front-end display. 
Because of the revision of the Superset interface, this PR is changed. #10760 

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
BEFORE
image

AFTER
image

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [x] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by zhaoyongjie** [comment]
Hi @chuancyzhang , code looks good to me, Could you fix the code style?

**Comment by chuancyzhang** [comment]
> Hi @chuancyzhang , code looks good to me, Could you fix the code style? Thanks for your contribution!

OK

**Comment by zhaoyongjie** [comment]
What do you think about this change? @villebro

**Comment by villebro** [comment]
@zhaoyongjie I personally agree with this change, but I wonder if this is considered a breaking change. Ping @etr2460 @john-bodley , any thoughts on this?

**Review by villebro — APPROVED** [review]
This request has come up multiple times in the past and I agree that this is probably expected behavior, but would prefer to get more opinions on this before hitting merge.

**Review by zhaoyongjie — APPROVED** [review]
I also approve of the change.

**Comment by kamalkeshavani-aiinside** [comment]
> This request has come up multiple times in the past and I agree that this is probably expected behavior, but would prefer to get more opinions on this before hitting merge.

If there is a concern that this will change the current behavior and can be considered as a breaking change. We can add a checkbox in the control panel(disabled by default) to 'Use Labels in Export CSV'. This will allow users to get this feature without changing the current behavior, as we agree that this feature is needed for sure.

**Comment by villebro** [comment]
@kamalkeshavani-aiinside this needs a rebase. I think we can merge this as-is, as adding yet another checkbox will just add clutter IMO.

**Comment by zhaoyongjie** [comment]
Hi @chuancyzhang , a friendly notice, this PR need to rebase master. Thanks!

**Comment by chuancyzhang** [comment]
> Hi @chuancyzhang , a friendly notice, this PR need to rebase master. Thanks!

done

**Comment by zhaoyongjie** [comment]
> > Hi @chuancyzhang , a friendly notice, this PR need to rebase master. Thanks!
> 
> done

There are conflicts as well.

image

**Comment by chuancyzhang** [comment]
> > > Hi @chuancyzhang , a friendly notice, this PR need to rebase master. Thanks!
> > 
> > 
> > done
> 
> There are conflicts as well.
> 
> image

ok

**Comment by chuancyzhang** [comment]
Please refer to PR #17657 .This PR, my rebase failed. @zhaoyongjie @villebro

**Comment by zhaoyongjie** [comment]
> Please refer to PR #17657 .This PR, my rebase failed. @zhaoyongjie @villebro

I think you don't need to a lot of changes to this PR. please double check.

image

**Comment by chuancyzhang** [comment]
> > Please refer to PR #17657 .This PR, my rebase failed. @zhaoyongjie @villebro
> 
> I think you don't need to a lot of changes to this PR. please double check.
> 
> image

I thought the wrong way at the time, which caused patch-3 to fail to rebase, which resulted in so many changes.

**Comment by zhaoyongjie** [comment]
> > > Please refer to PR #17657 .This PR, my rebase failed. @zhaoyongjie @villebro
> > 
> > 
> > I think you don't need to a lot of changes to this PR. please double check.
> > image
> 
> I thought the wrong way at the time, which caused patch-3 to fail to rebase, which resulted in so many changes.

Yep, there are a couple of changes recently in the codebase. The `get_data` method has moved into `query_context_processor.py`. I think you can cherry-pick original change into that.

If you have any question, please ping me.

**Comment by chuancyzhang** [comment]
> > > > Please refer to PR #17657 .This PR, my rebase failed. @zhaoyongjie @villebro
> > > 
> > > 
> > > I think you don't need to a lot of changes to this PR. please double check.
> > > image
> > 
> > 
> > I thought the wrong way at the time, which caused patch-3 to fail to rebase, which resulted in so many changes.
> 
> Yep, there are a couple of changes recently in the codebase. The `get_data` method has moved into `query_context_processor.py`. I think you can cherry-pick original change into that.
> 
> If you have any questions, please ping me.

I reopened a PR  #17657  again, you can look at this

**Comment by zhaoyongjie** [comment]
> > > > > Please refer to PR #17657 .This PR, my rebase failed. @zhaoyongjie @villebro
> > > > 
> > > > 
> > > > I think you don't need to a lot of changes to this PR. please double check.
> > > > image
> > > 
> > > 
> > > I thought the wrong way at the time, which caused patch-3 to fail to rebase, which resulted in so many changes.
> > 
> > 
> > Yep, there are a couple of changes recently in the codebase. The `get_data` method has moved into `query_context_processor.py`. I think you can cherry-pick original change into that.
> > If you have any questions, please ping me.
> 
> I reopened a PR #17657 again, you can look at this

Thanks! Do you mind I close this PR, then we can link new PR to this.

**Comment by chuancyzhang** [comment]
> > > > > > Please refer to PR #17657 .This PR, my rebase failed. @zhaoyongjie @villebro
> > > > > 
> > > > > 
> > > > > I think you don't need to a lot of changes to this PR. please double check.
> > > > > image
> > > > 
> > > > 
> > > > I thought the wrong way at the time, which caused patch-3 to fail to rebase, which resulted in so many changes.
> > > 
> > > 
> > > Yep, there are a couple of changes recently in the codebase. The `get_data` method has moved into `query_context_processor.py`. I think you can cherry-pick original change into that.
> > > If you have any questions, please ping me.
> > 
> > 
> > I reopened a PR #17657 again, you can look at this
> 
> Thanks! Do you mind I close this PR, then we can link new PR to this.

no problem. thanks for you help.

**Pull request closed without merging**
