### PR TITLE
add dashboard permission

### PR DESCRIPTION
**Pull request by ujhujuh**
grant permission to each dashboard manually.

### CODE REVIEW

**Comment by mistercrunch** [comment]
This has some complex-ish implications and we need to discuss internally whether we want to add this new dimension in the security matrix. For instance what happens now if the person has access to the dashboard but not to the underlying table(s)?

**Comment by xrmx** [comment]
@mistercrunch it would fail, which is backward compatible with current permissions. 
The only annoying and incompatible change is that with the patch one that has access to a datasource has no more automatic access to dashboards that use that datasource.

**Comment by acorso522** [comment]
Any updates on this front? The ability to restrict users to only specific dashboards is extremely useful.

**Comment by yamyamyuo** [comment]
Authorization based on datasource is more complicated when more users in superset. Think about this scenario. It is more convenient for superset admins to grant marketing dashboards permissions to marketing team members.

**Pull request closed without merging**
