### PR TITLE
feat(dashboard): Enables pivot table download option at dashboard level

### PR DESCRIPTION
**Pull request by adimyth**
### SUMMARY
Enables `Export to .Pivoted CSV` option for pivot tables at the dashboard level. This option is already available at the chart level but was missing at the dashboard level.

#### Before
Dashboard Download Options Before

#### After
Dashboard Download Options After

Note: The `Export to .Pivoted CSV` option is now available at the dashboard level.

#### Screen Recording

https://github.com/apache/superset/assets/26377913/9bb6d0b8-3830-4345-8365-eb4fed116181

### TESTING INSTRUCTIONS
1. Create a sample dataset. Refer to this [sample dataset](https://gist.github.com/adimyth/fe7ea16dedbd337e6873846f92275edb) that I had created for testing.
2. Create a pivot table from the dataset. Refer attached screenshot above for reference.
3. Add the pivot table to a dashboard.
4. Click on the `Download` option in the dashboard and check if the `Export to .Pivoted CSV` option is available.
5. Click on the `Export to .Pivoted CSV` option and check if the file is downloaded in the `.pivoted.csv` format.
6. Open the downloaded file and check if the data is displayed correctly. For the sample dataset, the data should be displayed as shown below:

Output Pivot Table

The pivot table was created as -
1. `Columns` - `color`
2. `Rows` - `region`
3. `Metrics` - `COUNT(*)`

As per this the downloaded data is as expected.

### ADDITIONAL INFORMATION
- [x] Has associated issue:
- [ ] Required feature flags:
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

Massive thanks to @theshivthakur for contributing to this. The credit goes to him!!

### CODE REVIEW

**Comment by rusackas** [comment]
> @sfirke Ephemeral environment creation is currently limited to committers.

@sfirke this just means you need to make your ASF affiliation public... it's a super weird workflow... just slack me sometime so I can show ya on zoom.

**Review by sfirke — APPROVED** [review]
Tested out in the ephemeral and confirmed that this functions as intended.  Code looks clean and straightforward to me.

**Comment by sfirke** [comment]
Thanks @theshivthakur and @adimyth for the contribution!  This is a nice fix to an annoying limitation.

**Pull request merged**
