### PR TITLE
fix: Chart series limit doesn't work for some databases

### LINKED ISSUE #25073: Chart Series Limit doesn't work for Clickhouse datasets
The chart series limit setting doesn't work for Clickhouse datasets.
The generated SQL doesn't contain a limit subquery.

#### How to reproduce the bug

1. Use a clickhouse db
2. Create a chart with a dimension 
3. Add a series limit 
4. Note how the series aren't limited in the generated SQL

### Expected results

The generated query to use the series limit.

### Actual results

The generated query doesn't use the series limit.

#### Screenshots

image

### Environment

- browser type and version: Firefox 102.14.0esr
- superset version: docker latest-dev     (using docker-compose-non-dev.yml)
- python version: Python 3.9.17
- any feature flags active:      FEATURE_FLAGS = {"ALERT_REPORTS": True, "HORIZONTAL_FILTER_BAR": True, "DRILL_TO_DETAIL": True, "DRILL_BY": True}

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by KSPT-taylorjohn**
Fix for series limit subquery creation for databases that mutate labels.
Fixes #25073

### ADDITIONAL INFORMATION

- [X] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by KSPT-taylorjohn** [comment]
Please review @villebro

**Review by villebro — APPROVED** [review]
Nice, thanks for adding that limit subquery alias! LGTM and tested to work as expected.

**Comment by villebro** [comment]
@KSPT-taylorjohn there's a lint issue:
```patch
diff --git a/superset/models/helpers.py b/superset/models/helpers.py
index 810de46372..6ae1e4d0a0 100644
--- a/superset/models/helpers.py
+++ b/superset/models/helpers.py
@@ -102,7 +102,6 @@ SERIES_LIMIT_SUBQ_ALIAS = "series_limit"
 ADVANCED_DATA_TYPES = config["ADVANCED_DATA_TYPES"]


-
 def validate_adhoc_subquery(
     sql: str,
     database_id: int,
@@ -1470,7 +1469,7 @@ class ExploreMixin:  # pylint: disable=too-many-public-methods
             db_engine_spec.make_label_compatible(column)
             for column in utils.get_column_names(
                 columns=series_columns or [],
-           )
+            )
         ]
         # deprecated, to be removed in 2.0
         if is_timeseries and timeseries_limit:
```

**Comment by KSPT-taylorjohn** [comment]
@villebro Sorry I have fixed that.

**Comment by villebro** [comment]
@eschutho @michael-s-molina this PR would be great to get into the next patch release of 3.0 and 2.1 (if we're still doing one more for 2.1)

**Comment by eschutho** [comment]
Thanks! I just tagged it for 2.1.2 as well.

**Comment by villebro** [comment]
FYI @genzgd if someone complains about series limits not working in Superset using Clickhouse Connect

**Comment by michael-s-molina** [comment]
> @eschutho @michael-s-molina this PR would be great to get into the next patch release of 3.0 and 2.1 (if we're still doing one more for 2.1)

I'll cherry-pick it for 3.0 given that we're still working on RC4.

**Pull request merged**
