### PR TITLE
refactor: migrate ExploreResultsButton component to FC & tsx

### PR DESCRIPTION
**Pull request by EugeneTorap**
### SUMMARY
Migrated ExploreResultsButton to TypeScript to apply direction outlined in #18100 .

### ADDITIONAL INFORMATION

- [x] Has associated issue: #18100
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by EugeneTorap** [comment]
@ad-m @AAfghahi `renderInvalidColumnMessage`, `renderTimeoutWarning`, `buildVizOptions` are not used anywhere

**Comment by ad-m** [comment]
> @ad-m @AAfghahi `renderInvalidColumnMessage`, `renderTimeoutWarning`, `buildVizOptions` are not used anywhere. Should I remove them?

I do not feel entitled to judge the issue of style in this project (I have too little experience in the project), but due tagging, I will express my opinion: dead code should be removed from the codebase, and besides, it is probably removed from bundles provided to the user by the Webpack.

**Comment by AAfghahi** [comment]
Hello! We can set up a test environment to see if it affects the functionality of the component, if it does not then we should remove them, I agree.

**Comment by ad-m** [comment]
@EugeneTorap you have some linting errors on CI. You might wanna install `pre-commit` to avoid committing code like that. Just `pre-commit install` in the project directory to setup Git hooks. In addition, `pre-commit` speed-up linting code thanks to linting only changed files.

**Comment by AAfghahi** [comment]
Oh I think this is already happening here: https://github.com/apache/superset/pull/17987

**Comment by EugeneTorap** [comment]
@AAfghahi This #17987 PR only converts code to FC and there's no typescript

**Comment by EugeneTorap** [comment]
@lyndsiWilliams Can you help me to fix `ExploreResultsButton.test.jsx` and also convert this test to typescript?

**Comment by lyndsiWilliams** [comment]
> @lyndsiWilliams Can you help me to fix `ExploreResultsButton.test.jsx` and also convert this test to typescript?

Hey @EugeneTorap! What error are you getting when you run the test?

  As far as conversion: My conversion method for JS to TS in these tests is to change the file to `.tsx` then fix all the errors, making sure to reuse any pre-existing types in the codebase. Are you running into a specific error in your conversion? We’re also trying to convert all of our Enzyme tests to React testing library. If you’re interested, you could take the TS/RTL conversion to a new PR for this test and I’d be delighted to give you some pointers.

**Comment by EugeneTorap** [comment]
@lyndsiWilliams 
image

> Error: useTheme() could not find a ThemeContext. The <ThemeProvider/> component is likely missing from the app.

**Comment by lyndsiWilliams** [comment]
> @lyndsiWilliams image
> 
> > Error: useTheme() could not find a ThemeContext. The  component is likely missing from the app.

You'll need to wrap each render in a `<ThemeProvider />`, as seen here in [ExploreActionButtons.test.jsx](https://github.com/apache/superset/blob/master/superset-frontend/src/explore/components/ExploreActionButtons.test.jsx#L63-L65). Upon further inspection, this test will need to be converted to RTL since this is a functional component now. The Enzyme tests are set up to test class function-only behavior like props, so these will now be broken. We've got some handy helper functions set up for our RTL tests in the [spec/helpers file](https://github.com/apache/superset/blob/master/superset-frontend/spec/helpers/testing-library.tsx) that will provide the theme (and other handy things if needed) for you.

**Comment by EugeneTorap** [comment]
@geido @AAfghahi @lyndsiWilliams Can you review the PR again.
And I think we can close #17987

**Review by geido — APPROVED** [review]
I am tentatively approving this PR but it would be great to move the tests to RTL if possible. I am fine with doing that in a separate PR as long as we don't lose track of those. Thank you

**Review by AAfghahi — APPROVED** [review]

**Pull request merged**
