### PR TITLE
Importing validators module from superset-ui

### PR DESCRIPTION
**Pull request by rusackas**
### CATEGORY

Choose one

- [ ] Bug Fix
- [ ] Enhancement (new features, refinement)
- [x] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY

Changes the reliance in Viz plugin controls from a local validators file to the (newer) module imported from `@superset-ui/validator`

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### REVIEWERS
@kristw

### CODE REVIEW

**Comment by rusackas** [comment]
@kristw I'm having a hard time figuring out why I can't get cypress to live through a run... does anything jump out at you here?

**Comment by kristw** [comment]
> import { legacyValidateInteger, legacyValidateNumber, validateNonEmpty } from '@superset-ui/validator';
> There is a non-legacy `validateInteger` and `validateNumber` which has the logical behavior, but will break superset because it seems to expect the wrong output from the legacy functions at the moment.

You should use `legacyValidateInteger` and `legacyValidateNumber`.

https://github.com/apache-superset/superset-ui/pull/322

I'll move these note into the package `README`

**Comment by rusackas** [comment]
> > import { legacyValidateInteger, legacyValidateNumber, validateNonEmpty } from '@superset-ui/validator';
> > There is a non-legacy `validateInteger` and `validateNumber` which has the logical behavior, but will break superset because it seems to expect the wrong output from the legacy functions at the moment.
> 
> You should use `legacyValidateInteger` and `legacyValidateNumber`.
> 
> [apache-superset/superset-ui#322](https://github.com/apache-superset/superset-ui/pull/322)
> 
> I'll move these note into the package `README`

Ahhh, thanks. Didn't catch the intent. I'll see about unifying those, as I don't love the idea of moving forward with "legacy" things in a refactor project, but it seems CI is green, yay!

If you don't mind giving this a review, that'd be wonderful.

Thanks,

-e-

**Review by kristw — APPROVED** [review]

**Review by kristw — CHANGES_REQUESTED** [review]
Sorry. I notice two `package-lock.json`. Please remove the one in root.

**Comment by kristw** [comment]
> Ahhh, thanks. Didn't catch the intent. I'll see about unifying those, as I don't love the idea of moving forward with "legacy" things in a refactor project, but it seems CI is green, yay!

Agree. I tried to think of clean way to do the migration while discourage people from using the illogical method in more places. We should sweep and get rid of them at some point.

**Comment by rusackas** [comment]
> Sorry. I notice two `package-lock.json`. Please remove the one in root.

Good eyes! Removed, and re-Travis-ing.

**Review by kristw — APPROVED** [review]

**Pull request merged**
