### PR TITLE
feat(viz picker): Remove some tags, refactor Recommended section

### PR DESCRIPTION
**Pull request by kgabryje**
### SUMMARY
Implements changes from discussion https://github.com/apache/superset/discussions/27557

1. Remove the Recommended tags section and move the charts in "Popular" to a "Featured" section underneath All Charts, "Featured" is selected by default
2. Remove the following tags:
- Aesthetic
- Coordinates
- Deprecated
- Description
- Discrete
- Experimental
- Vertical
3. Bar Chart (legacy) : Remove Popular/Featured tag from Bar Chart (legacy)
4. Collapse Tags section by default

Also, refactored the svg icons used in viz picker (ballot, category, tags) as their viewboxes were weird, which resulted in additional css used to make them look good

CC @yousoph 

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Before:

image

After:

image

### TESTING INSTRUCTIONS
Open the viz picker, verify that Recommended section is gone and Featured contains all charts with "Popular" tag, verify that everything looks good

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by michael-s-molina — APPROVED** [review]
Thank you for the improvement @kgabryje!

My only non-blocking comment would be to replace the Featured icon with a ⭐ 

Screenshot 2024-03-28 at 08 25 28

**Comment by kgabryje** [comment]
> My only non-blocking comment would be to replace the Featured icon with a ⭐

@yousoph @kasiazjc wdyt?

**Comment by kasiazjc** [comment]
> > My only non-blocking comment would be to replace the Featured icon with a ⭐
> 
> @yousoph @kasiazjc wdyt?

@michael-s-molina also thought about ⭐️ at first, but we already use it for "favorites", so wanted to avoid duplicates. Sadly ant-d doesnt have the best choice for icons, but the other contenders (besides pin) would be: 
image
or just 
image
 Thoughts @kgabryje @michael-s-molina ?

**Comment by kgabryje** [comment]
The first one looks good!

**Comment by michael-s-molina** [comment]
@kasiazjc The first one works. There's also:

Screenshot 2024-04-02 at 13 18 00
Screenshot 2024-04-02 at 13 19 22

I'll let you make the call 😉

**Comment by kasiazjc** [comment]
> @kasiazjc The first one works. There's also:
> 
> Screenshot 2024-04-02 at 13 18 00 Screenshot 2024-04-02 at 13 19 22
> I'll let you make the call 😉

Actually I think fire works well 🔥
Cc: @kgabryje

**Comment by kgabryje** [comment]
image

@kasiazjc @michael-s-molina Looks pretty good 🙂

**Comment by michael-s-molina** [comment]
Thank you! 🔥

**Pull request merged**
