### PR TITLE
fix(sqllab): misplaced limit warning alert

### PR DESCRIPTION
**Pull request by justinpark**
### SUMMARY
Hotfix for #25288

This commit fixes the displaced limit warning alert in the query result.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

|After|Before|
|--|--|
|Screenshot 2023-09-14 at 11 14 24 AM|Notification_Center|

### TESTING INSTRUCTIONS
1. Go to sql, run query without selecting the limit or set limit in query
2. Run query
3. Observe the the result section
4. See the yellow banner is to the right side of the query

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by jinghua-qa** [comment]
I tested in the ephemeral, the original banner issue is fixed, however i noticed that when i try to change dropdown limit to returning larger rows, seems like there is a error yellow banner about no stored result found, and then it will take couple seconds for the result to load. 
  
Screen Shot 2023-09-18 at 9 41 31 AM

Screen Shot 2023-09-18 at 9 41 47 AM

**Comment by justinpark** [comment]
@jinghua-qa I push a commit to fix the issue. could you rebuild ephemeral env and test again?

> I tested in the ephemeral, the original banner issue is fixed, however i noticed that when i try to change dropdown limit to returning larger rows, seems like there is a error yellow banner about no stored result found, and then it will take couple seconds for the result to load.
> 
> Screen Shot 2023-09-18 at 9 41 47 AM
>  Screen.Recording.2023-09-18.at.9.54.45.AM.mov

**Comment by jinghua-qa** [comment]
Tested the ephemeral env looks like the issue i found is fixed. LGTM!

**Review by Antonio-RiveroMartnez — APPROVED** [review]
lgtm

**Pull request merged**
