### PR TITLE
Fix migration for make creator owners

### PR DESCRIPTION
**Pull request by ShengyaoQian**

### CODE REVIEW

**Comment by ShengyaoQian** [comment]
To fix a migration error mentioned by @the-dcruz in https://github.com/airbnb/caravel/pull/1078

**Comment by the-dcruz** [comment]
@ShengyaoQian Thanks for taking a look at this and sorry, I missed those replies on my comment.

I just ran this with an old db and it seems to work fine.

**Comment by ShengyaoQian** [comment]
@mistercrunch

**Comment by ShengyaoQian** [comment]
@mistercrunch can this change be taken in? Can you take a look? 🙏 🙏 🙏

**Comment by ShengyaoQian** [comment]
@mistercrunch

**Comment by mistercrunch** [comment]
Thanks for the PR!

**Pull request merged**
