### PR TITLE
chore(translations): Arabic translations

### PR DESCRIPTION
**Pull request by abdilra7eem**
### SUMMARY

Arabic Translation for Apache Superset.
We strived for completeness and formatting correctness. Further proofreading is needed, but it's outside the scope of this PR.

### TESTING INSTRUCTIONS

```
❯ cd superset/translations/ar/LC_MESSAGES
❯ msgfmt -v messages.po
3820 translated messages, 3 fuzzy translations, 1 untranslated message.
```

### ADDITIONAL INFORMATION
- [ ] Has associated issue: https://github.com/apache/superset/issues/25258 (more work is still needed for RTL text direction support. This is only the translation.
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by OmarIthawi** [comment]
@rusackas @michael-s-molina Thanks for triaging this pull request. This pull request is ready for review and merge.

Please enable the test run.

BTW, do we need to compile and add the Arabic frontend json file to git?

**Comment by mistercrunch** [comment]
Somehow conflicting with something, happy to semi-blindly merge if/when conflicts are resolved

**Comment by OmarIthawi** [comment]
Thanks @mistercrunch.

@abdilra7eem I think the conflicts happened due to https://github.com/apache/superset/pull/29782.

Would you mind rebasing and fixing those conflicts?

@mistercrunch will merge once you give us green-light.

**Comment by mistercrunch** [comment]
For easier merge you may want to run `./scripts/translations/babel_update.sh` prior to rebasing. Recently I added `--no-location` which should facilitate much easier merge as the `.po` files are now stripped of references which used to make merging/rebasing really difficult.

So
```
./scripts/translations/babel_update.sh
git pull --rebase {your_main_fork_remote} master
```

Hopefully things go smoothly.

**Comment by OmarIthawi** [comment]
Thanks @abdilra7eem. 

Done @mistercrunch.

**Comment by mistercrunch** [comment]
Hey I pulled your branch and still see as though you didn't run the newer version of `./scripts/translations/babel_update.sh` which includes the  `--no-location` flag. You can see it in your local branch it looks like this:

Screenshot 2024-08-07 at 1 42 51 PM

But if you can run the **latest version** of `./scripts/translations/babel_update.sh`, there shouldn't be all these [purple in my screenshot] comments referencing where that msgid lives. See how these comments aren't there in the `master` branch of the file you are changing -> https://github.com/apache/superset/blob/master/superset/translations/ar/LC_MESSAGES/messages.po

**Comment by OmarIthawi** [comment]
@abdilra7eem would you mind following @mistercrunch instructions?

**Comment by OmarIthawi** [comment]
Thanks @abdilra7eem for the update. @mistercrunch it's now ready for merge. Could you please triage it before there are conflicts with master?

**Review by mistercrunch — APPROVED** [review]
Amazing, can't really review the content but we're grateful to get Arabic translations!

**Comment by OmarIthawi** [comment]
Thank you @mistercrunch and everyone for your review and help!

Congrats @abdilra7eem for your first contribution here!

**Pull request merged**
