### PR TITLE
test: Tests and dedicated dir for Explore TextControl component

### PR DESCRIPTION
**Pull request by geido**
### SUMMARY
Move the TextControl component to a dedicated directory and adds the tests

### TEST PLAN
All tests should pass

### CODE REVIEW

**Comment by geido** [comment]
@junlincc @rusackas

**Review by pkdotson — APPROVED** [review]
LGTM!

**Review by michael-s-molina — APPROVED** [review]
LGTM

**Comment by junlincc** [comment]
@rusackas ready to merge?

**Pull request merged**
