### PR TITLE
update all python version in the Dockerfile to 3.7

### PR DESCRIPTION
**Pull request by cyw233**
### SUMMARY

I found there were 2 lines that still had 3.6 in the Dockerfile. So I changed them to 3.7
### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by villebro** [comment]
I did some more searching, and found 3.6 also being mentioned in `docs/installation.rst`. We should probably update the reference to `ubuntu-20.04` which ships with Python 3.8 by default, as it's the current LTS version.

**Comment by cyw233** [comment]
Yeah I did some research on Ubuntu 20.04. It by default has Python 3.8 along with Python 2.7. So I guess I will first change the description to: 
"**Ubuntu 20.04** If you have python3.8 installed alongside with python2.7, as is default on Ubuntu 20.04 LTS, run this command also:"

Then I will change "python3.6-dev" to "python3.7-dev". So the install command will be changed to
`sudo apt-get install build-essential libssl-dev libffi-dev python3.7-dev python-pip libsasl2-dev libldap2-dev`

Is there anything else I need to change? Cheers!

**Comment by villebro** [comment]
Actually it's simpler than that, `ubuntu-20.04` ships with 3.8 only, no 2.7. So I think this can be rephrased as
> Ubuntu 20.04, the following command will ensure that the required dependencies are installed:
`sudo apt-get install build-essential libssl-dev libffi-dev python3-dev python-pip libsasl2-dev libldap2-dev`

**Comment by cyw233** [comment]
Change made. Please check.

**Review by villebro — APPROVED** [review]
LGTM, thanks for the fix!

**Pull request merged**
