### PR TITLE
fix(drillby): Enable DrillBy in charts w/o filters (dimensions)

### LINKED ISSUE #27940: Drill by is disabled for Timeseries and Mixed Timeseries charts without dimensions
### Bug description

Any Timeseries or Mixed Timeseries chart that does not have dimensions configured has context menu item "Drill by" disabled. Yet, "Drill by" would also be most useful to explore anomalies in these types of charts.

### How to reproduce the bug

1. Open any dashboard with dimensionless Timeseries or Mixed Timeseries charts
2. Right click on a data point in one of those charts
3. "Drill by" is not selectable

### Screenshots/recordings

Below chart shows two metrics w/o dimensions.

image

### Superset version

master / latest-dev

### Python version

3.10

### Node version

18 or greater

### Browser

Chrome

### Additional context

_No response_

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### PR DESCRIPTION
**Pull request by sowo**
### SUMMARY
This fix resolves #27940 by enabling "Drll by" for Timeseries and Mixed Timeseries charts that do not have dimensions configured.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Before:
Screenshot from 2024-04-08 15-30-47

After

image

image

### TESTING INSTRUCTIONS
Open any dashboard that includes either Timeseries or Mixed Timeseries charts without dimensions and right-click on any data point in those charts. The "Drill by" should be available and open the modal for the selected dimension.

### ADDITIONAL INFORMATION
- [X] Has associated issue:
- [ ] Required feature flags:
- [X] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by rusackas** [comment]
Thanks @sowo this looks promising! Curious what you see left to do here, but we look forward to reviewing it when it's ready. So far, the code looks good to me!

**Comment by sowo** [comment]
Hi,

Thanks for the response.

I found an issue when clicking on the breadcrumbs. Some index misalignment
after filtering out the empty initial filter. Should be fixed soon.

Best,
Wolfgang

**Comment by rusackas** [comment]
Maybe if @sfirke's hypothesis is right, we'll get lucky and this will help with https://github.com/apache/superset/issues/25334 as well... but maybe not. Just something to test when the ephemeral env spins up.

**Comment by sowo** [comment]
Seems the breadcrumbs and drillByConfigs need to be in sync to make breadcrumb navigation work. So rather than filtering out the first breadcrumb item when it is empty (for charts without dimensions), I decided to just hide the first breadcrumb. This is somewhat ugly as it leaves the separator (/) visible. 

image


Let me know if anyone has a better idea on how to non-intrusively fix this.

**Review by kgabryje — APPROVED** [review]
Thanks for the contribution @sowo! The code looks good to me. Feature wise, I think it would be great if we could have a drill filter based on X axis group, but that needs to be thought through first, so I'm fine with going with your change for now 🙂

**Comment by rusackas** [comment]
Hmm... closing/reopening to see if that kicks CI into gear.

**Comment by sowo** [comment]
@kgabryje initially, I used the X axis value plus the selected dimension for the drill by chart. But this created a time series chart with just one bar broken down by the selected dimension. For this to really be useful, the chart type would need to be changed - e.g. pie chart. Is there any plan to make the chart type selectable as one drills down?

Thanks

**Comment by sfirke** [comment]
> Maybe if @sfirke's hypothesis is right, we'll get lucky and this will help with #25334 as well... but maybe not. Just something to test when the ephemeral env spins up.

Alas this did not, just confirmed while testing 4.0.1rc1 which contains this PR.  This fix works through and is great!

**Comment by neeagl** [comment]
@sowo thanks for the fix. In the screenshot you show the barchart but in the text, you've mentioned time-series. can you please confirm? 
As per #25334 , it still looks to not fix it with barchart but I'm curious if i can use the time-series to do the same job (or any other recommendation will be very welcome).

**Pull request merged**
