### PR TITLE
feat: SIP-34 explore save modal

### PR DESCRIPTION
**Pull request by mistercrunch**
Getting the explore save modal closer to SIP-34

RFC: SIP-34 doesn't really offer the "Create a new dashboard and add this chart into it" option and I wanted to preserve that. I did it with a checkbox + leaving the select empty, but unclear what the best way would be.

## After (updated to latest commit)
Screen Shot 2020-07-22 at 2 23 15 PM

## Before
Screen Shot 2020-07-16 at 10 50 24 PM

## SIP-34
Screen Shot 2020-07-16 at 10 49 23 PM

### CODE REVIEW

**Comment by Steejay** [comment]
@mistercrunch see north star design for _add  chart to new dashboard_

For the After image: The text field under radio buttons would benefit by adding a title so that its clear what the field is for. See SIP-34 screenshot you posted.

Screen Shot 2020-07-17 at 7 50 44 AM

**Comment by mistercrunch** [comment]
@Steejay , I decided to use the "CreatableSelect" component feature from react-select to avoid having to build the select box.
Screen Shot 2020-07-18 at 4 47 53 PM

I also improved the e2e cypress tests quite a bit, fixed and re-enabled tests that had been disabled.

**Comment by rusackas** [comment]
> @Steejay , I decided to use the "CreatableSelect" component feature from react-select to avoid having to build the select box.
> Screen Shot 2020-07-18 at 4 47 53 PM
> 
> Screen Shot 2020-07-18 at 4 51 03 PM
> 
> I also improved the e2e cypress tests quite a bit, fixed and re-enabled tests that had been disabled.

The more I look at this the more I'm agonizing over the `🔘 Save (overwrite) 🔘 Save As` choice.

Could it just be:
```
Save as:
[SomeChartame         ]
⚠️ Warning: This will overwrite the current *SomeChartame* chart
```
^ Just displaying an overwrite warning, rather than forcing a choice?

**Comment by ktmud** [comment]
> 
> ```
> Save as:
> [SomeChartame         ]
> ⚠️ Warning: This will overwrite the current *SomeChartame* chart
> ```
> 
> ^ Just displaying an overwrite warning, rather than forcing a choice?

I don't think this works as two charts can have the same title. Sometimes users just want to save a new copy of a chart and play with it.

I also feel `CreatableSelect` is not quite clear as the original radio buttons. Maybe keep it as is before we implement the SIP-34 design?

**Comment by mistercrunch** [comment]
@ktmud I don't have data to back this up, but the "save AND create a new dashboard" is not super common, it's still very much possible and discoverable IMHO. I think the previous modal looks awful and is super confusing.

I'd hate to shelf this because it's not 100% SIP-34. This PR also re-enables/improves many unit tests and removes a lot of unneeded complexity.

@ktmud  if the concern is the "create dashboard" is not discoverable enough, I can think of ways to improve that, like bolding the words "Create" and "Select" in the placeholder of the dashboard dropdown

**Comment by mistercrunch** [comment]
Proposing two options:
Screen Shot 2020-07-21 at 10 03 20 AM
Screen Shot 2020-07-21 at 10 02 44 AM

**Comment by Steejay** [comment]
I prefer option 1. All caps is a little too aggressive/dominating. Additionally, the header should read "Save Chart" not "Save A Chart". Can we add the title "Chart Name*" above the text field as well?

see comments in https://github.com/apache/incubator-superset/pull/10355#issuecomment-660151394

**Comment by mistercrunch** [comment]
Latest:
Screen Shot 2020-07-21 at 11 33 58 AM

**Comment by mistercrunch** [comment]
@ktmud I'd love your blessing on this, but I think this is solid mergeable progress and a good checkpoint in the right direction

**Comment by mistercrunch** [comment]
Latest, with the new control-label
Screen Shot 2020-07-22 at 2 23 15 PM

**Comment by ktmud** [comment]
This design is definitely much cleaner than the existing layout. I'm OK with merging as is but would love to see the new iteration soon. A placeholder text still doesn't look as discoverable as the inline input in SIP-34 or the radio buttons in old design.

Another problem with current `CreatableSelect` is that it blocks users from creating a new dashboard with the same name as some existing dashboards.

**Comment by rusackas** [comment]
Impacts #8976

**Pull request merged**
