### PR TITLE
feat(explore): improve UI in the control panel

### PR DESCRIPTION
**Pull request by stephenLYZ**
### SUMMARY

This PR improves the styling of the control panel:
- change headers to match metrics&columns section
- attache line dividers to the top of the section header
- change the headers that can be found in the random sections, change them to the 12px and lighter gray color.
- spacing between the label and input should be always 4px
- spacing between different objects in the control panel (for example between the two controls, control and section title etc) should always be 16px

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

|  before  | after  |
|  ----  | ----  |
| image  | image |
| image  | image |
| image | image |

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by kasiazjc** [comment]
@stephenLYZ thanks for all of the improvements! Looks much cleaner :) 

Something weird is happening with the tooltips for controls though - they show up for calculated columns, but not for the normal columns - there is like half of the dot showing on the right of the fields, so I guess the hovering over not only controls, but also fields now triggers something that hides under the chart section? Attaching the video. 


https://user-images.githubusercontent.com/36897697/164021757-390a09a9-dfbe-47c0-9ba8-4a7b4614922e.mov

**Comment by kgabryje** [comment]
1. Should we decrease the spacing between subsequent checkboxes? @kasiazjc 
2. I think in the design the checkbox texts are black, not gray

image

**Comment by kasiazjc** [comment]
> 1. Should we decrease the spacing between subsequent checkboxes? @kasiazjc
> 2. I think in the design the checkbox texts are black, not gray
> 
> image

That's a good catch, the controls actually have #666666 color. 

I think the spacings are looking good - especially if all of those are selected it's less overwhelming.

**Review by kgabryje — CHANGES_REQUESTED** [review]
Request changes - details in comments

**Comment by stephenLYZ** [comment]
@kgabryje Got it. Thanks for explanation. Pushed new changes here.

**Review by kgabryje — APPROVED** [review]
Looks fantastic! Thank you for the improvements. I approved, but let's wait for @kasiazjc stamp before merging

**Comment by kasiazjc** [comment]
Looks great! Thank you @stephenLYZ :)

**Pull request merged**
