### PR TITLE
chore(explore): make adhoc columns available without UX BETA ff

### PR DESCRIPTION
**Pull request by kgabryje**
### SUMMARY
The feature introduced in https://github.com/apache/superset/pull/17379 was available only with UX BETA feature flag enabled. Since we received positive feedback from the users who tried the feature out, it's time to make it available to everyone!
This PR removes the dependency on UX BETA feature flag. To learn more about the feature, check out the linked PR 

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
image

### TESTING INSTRUCTIONS
0. Disable UX_BETA feature flag and enable drag and drop feature flag
1. Create a chart 
2. Verify that adhoc columns feature is available and works as described in https://github.com/apache/superset/pull/17379

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

CC @rusackas  @jinghua-qa @rosemarie-chiu

### CODE REVIEW

**Review by villebro — APPROVED** [review]
LGTM 🚀

**Comment by jinghua-qa** [comment]
I am not able to see adhoc columns feature in groupby in the test env, do i need to enable dnd and dnd hybrid FF?

https://user-images.githubusercontent.com/81597121/148110742-013a358f-02b5-4414-bcd4-9f9a9345aeb7.mov

**Comment by kgabryje** [comment]
> I am not able to see adhoc columns feature in groupby in the test env, do i need to enable dnd and dnd hybrid FF?
> 
>  Screen.Recording.2022-01-04.at.11.03.54.AM.mov

Yes, DnD is a requirement, sorry for not putting that information in PR description. Let me update

**Comment by jinghua-qa** [comment]
/testenv up FEATURE_ENABLE_EXPLORE_DRAG_AND_DROP=true FEATURE_ENABLE_DND_WITH_CLICK_UX=true

**Comment by jinghua-qa** [comment]
LGTM

**Review by jinghua-qa — APPROVED** [review]
LGTM

**Review by rusackas — APPROVED** [review]

**Pull request merged**
