### PR TITLE
chore: bump pivot table plugin - new metric title mapping

### PR DESCRIPTION
**Pull request by rusackas**
### SUMMARY

Bumps the Pivot Table V2 plugin to include [this](https://github.com/apache-superset/superset-ui/pull/1132) change

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

See linked PR for screenshots:
https://github.com/apache-superset/superset-ui/pull/1132

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by kgabryje** [comment]
We can close this PR, the superset-ui packages have been bumped to 0.17.52 in a different PR

**Comment by junlincc** [comment]
@kgabryje @villebro which one?

> We can close this PR, the superset-ui packages have been bumped to 0.17.52 in a different PR

**Comment by kgabryje** [comment]
@junlincc https://github.com/apache/superset/pull/14661

**Pull request closed without merging**
