### PR TITLE
chore(de-translation): update German translations (based on master) (#17441)

### LINKED ISSUE #17441: German translations missing or wrong
Currently, many German translations are missing or wrong.

I'm planning to provide a PR contributing PO/JSON files for the `de` locale. Mimicking the good practice of @audour who reported likewise for the French locale in #16550, this issues report serves as announcement so other contributors do not duplicate efforts (or report if they are already working on the same), like #16550 did for the French locale.

However, before requesting a PR, I have some questions regarding this contribution:

- I planed to work on the master branch, while #16868 is based on 1.3.0 version. What do you prefer?
- #16868 did not include an updated `pot` file. I did not check yet, but I assume it's up-to-date for 1.3.0.(?). In case I'd submit a PR for master: should it contain the updated `pot` file and all `po`/`json`files for all locales or just the `de` locale I'm working on?
- There a couple of messages, which are not localized yet (e.g. `View all`, `Viewed` in the CRUD welcome tables, `See all` in `EmptyState.tsx`, `settings` in the `MenuRight.tsx`. For those, I'd provide a preceding PR, if I base my contributions on `master`.

### PR DESCRIPTION
**Pull request by hbruch**
### SUMMARY
This PR updates the .pot file as described in https://github.com/apache/superset/blob/master/CONTRIBUTING.md#extracting-new-strings-for-translation and updates German translations.

~~This PR is marked WIP as I want to reread all translations once again .~~

### TESTING INSTRUCTIONS
Would be great, if a German speaker could review, at least 
* if we agree on important, recurring keywords.
* to suggest translations for the few remaining fuzzy messages

### ADDITIONAL INFORMATION
- [X] Has associated issue: Fixes #17441
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by villebro** [comment]
Thanks so much for the contribution @hbruch ! 🇩🇪 Unless nobody else steps up I can give it a quick review (my German is not fluent but I might spot a typo)

**Comment by villebro** [comment]
@hbruch feel free to remove the draft and WIP label once you feel this is ready for review.

**Comment by hbruch** [comment]
I re-checked the translations and modified some. Should be ready for review now.

**Comment by hbruch** [comment]
@villebro just noticed, that `*.ts` files are not extract, as the suffix is missing in `babel.cfg`. I'd suggest to open another PR after this one is merged, WDYT?

**Comment by villebro** [comment]
> @villebro just noticed, that `*.ts` files are not extracted, as the `ts` suffix is missing in `babel.cfg`. I'd suggest to open another PR after this one is merged, WDYT?

😱 Great catch! Yes, by all means do open a new PR for that. Let me do a quick review, and if this looks good let's merge this.

**Comment by villebro** [comment]
@hbruch while reviewing your PR I found some broken translation strings that I've fixed in this PR: https://github.com/apache/superset/pull/17501 If you have the time please feel free to review.

**Review by villebro — APPROVED** [review]
LGTM

**Comment by villebro** [comment]
@hbruch are you ok with me merging this, or do you want to rebase to pull in #17501 ? I'd personally prefer to merge this as-is and then do a follow-up once the `ts` translation fix is also in place.

**Comment by hbruch** [comment]
Ok. So you'll merge this PR, I'll submit a PR adding `ts` and updated `pot` and afterwards another PR adding the German translations only? Would be fine for me.

**Comment by villebro** [comment]
> Ok. So you'll merge this PR, I'll submit a PR adding `ts` and updated `pot` and afterwards another PR adding the German translations only? Would be fine for me.

Exactly! I'll merge now, thanks for the quick response!

**Pull request merged**
