### PR TITLE
fix(tox): Address issue with generative environment variables

### PR DESCRIPTION
**Pull request by john-bodley**
### SUMMARY

The way the SQLite environment variables were specified were incorrect meaning that the `SUPERSET__SQLALCHEMY_DATABASE_URI` and `SUPERSET__SQLALCHEMY_EXAMPLES_URI` environment variables never adhered to the specified environment.

#### BEFORE

```
$ tox -e py310-mysql --showconfig | grep SUPERSET__SQLALCHEMY
  SUPERSET__SQLALCHEMY_DATABASE_URI=sqlite:///<redacted>/superset/.tox/py310-mysql/tmp/superset.db
  SUPERSET__SQLALCHEMY_EXAMPLES_URI=sqlite:///<redacted>/superset/.tox/py310-mysql/tmp/examples.db
```

```
$ tox -e py310-sqlite --showconfig | grep SUPERSET__SQLALCHEMY
  SUPERSET__SQLALCHEMY_DATABASE_URI=sqlite:///<redacted>/superset/.tox/py310-sqlite/tmp/superset.db
  SUPERSET__SQLALCHEMY_EXAMPLES_URI=sqlite:///<redacted>/superset/.tox/py310-sqlite/tmp/examples.db
```

#### AFTER 

```
$ tox -e py310-mysql --showconfig | grep SUPERSET__SQLALCHEMY
  SUPERSET__SQLALCHEMY_DATABASE_URI=mysql://mysqluser:mysqluserpassword@localhost/superset?charset=utf8
```

```
$ tox -e py310-sqlite --showconfig | grep SUPERSET__SQLALCHEMY
  SUPERSET__SQLALCHEMY_DATABASE_URI=sqlite:///<redacted>/superset/.tox/py310-sqlite/tmp/superset.db
  SUPERSET__SQLALCHEMY_EXAMPLES_URI=sqlite:///<redacted>/superset/.tox/py310-sqlite/tmp/examples.db
```

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by mistercrunch — APPROVED** [review]
LGTM

**Comment by mistercrunch** [comment]
Hey @john-bodley taking a side-topic here, but wondering what you think of `tox` as part of our devex stack. I noticed it isn't used for CI anymore in favor of GHA, but has the merit to run locally - though personally I have issue running the test suites using it when I tried.

Wondering if we'd consider either dropping support for it or whether we should be using it in CI for consistency (?)

**Comment by john-bodley** [comment]
@mistercrunch it seems like [act](https://github.com/nektos/act) would be the way to go. Consistency is key.

The fragmentation between local and remote CI is not great. Personally I’ve wasted numerous hours/days due to inconsistencies when trying to test locally versus remote.

**Comment by mistercrunch** [comment]
Totally agreed, I love the idea of moving to `act` and removing `tox`. I'll see if I can make it work easily out of the box today. If so it'd be a matter of:
- wiping `tox` and everything tox-related
- documenting how to use `act`

Hoping it works out of the box. I'll open a DRAFT PR to track progress

**Pull request merged**
