### PR TITLE
Fixed Histogram visualization bug. 

### PR DESCRIPTION
**Pull request by kuckjwi0928**
### CATEGORY

- [x] Bug Fix
- [ ] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY
Modified type mismatch bug in histogram visualization.

### TEST PLAN
- Go to histogram chart.
- Check if the histogram chart is functioning normally.

### ADDITIONAL INFORMATION

- [x] Has associated issue: Fixes https://github.com/apache/incubator-superset/issues/8028
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### REVIEWERS
@mistercrunch

### CODE REVIEW

**Comment by villebro** [comment]
@kuckjwi0928 LGTM, but please run black on the PR to fix the CI error.

**Comment by kuckjwi0928** [comment]
> @kuckjwi0928 LGTM, but please run black on the PR to fix the CI error.

Fixed it!

**Comment by ali-bahjati** [comment]
It seems that it failed because of execution time limit. I guess it's ok to merge this PR.

**Comment by villebro** [comment]
I restarted CI, let's merge once it completes if all is ok.

**Comment by villebro** [comment]
Note: while this was later reverted in master after `superset-ui*` was bumped to `0.12`, this fix is needed in `0.34` which is still on `0.11`.

**Comment by kuckjwi0928** [comment]
@villebro 
I will soon open a PR that has solved this problem properly.

related issue : https://github.com/apache/incubator-superset/issues/8266

**Pull request merged**
