### PR TITLE
Fix ExtDeprecationWarning (#2137)

### PR DESCRIPTION
**Pull request by asdf2014**
Fix ExtDeprecationWarning (#2137)

### CODE REVIEW

**Comment by asdf2014** [comment]
Why re-check the code, i just amend the commit message for adding the issues code?

**Comment by mistercrunch** [comment]
I'm fine turning off these warnings. They're coming from the libs we use and therefore they need to fix those. Since our deps are pinned it shouldn't be an issue.

**Comment by asdf2014** [comment]
Yeah, it is.

**Comment by uptonking** [comment]
@asdf2014 @mistercrunch   before I merge this commit, superset works fine.. after this commit, I got an error.
```
Traceback (most recent call last):
  File "/usr/bin/superset", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/root/Documents/repos/supersetx/superset/bin/superset", line 8, in <module>
    from flask.exthook import ExtDeprecationWarning
ImportError: cannot import name ExtDeprecationWarning
```

my env is Pyhton2.7, when I look for  `ExtDeprecationWarning` in  `path/to/site-packages/flask/exthook.py, it doesn't exist.
any advice?

**Comment by asdf2014** [comment]
Hi, @uptonking . I use python 2.7.12 and it works for me. Could you run `pip freeze` command in your venv, show those requirements in comment?

**Comment by uptonking** [comment]
@asdf2014  my pip freeze show flask 0.10 exists.  Locate the  `path/to/site-packages/flask/exthook.py`, the file exists, but `ExtDeprecationWarning` can't be found.  Could you please have a look at your `exthook.py`?
```
alabaster==0.7.9
alembic==0.8.9
amqp==1.4.9
aniso8601==1.1.0
ansible==2.2.1.0
anyjson==0.3.3
appnope==0.1.0
Babel==2.3.4
backports-abc==0.5
backports.shutil-get-terminal-size==1.0.0
backports.ssl-match-hostname==3.5.0.1
Beaker==1.5.4
beautifulsoup4==4.5.1
billiard==3.3.0.23
bleach==1.5.0
blinker==1.3
blivet==0.61.15.59
boto3==1.4.4
botocore==1.5.8
Brlapi==0.6.0
cached-property==1.3.0
celery==3.1.23
certifi==2016.9.26
cffi==1.6.0
chardet==2.2.1
click==6.6
codeclimate-test-reporter==0.2.0
colorama==0.3.7
configobj==4.7.2
configparser==3.5.0
configshell-fb==1.1.18
contextlib2==0.5.4
coverage==4.0.3
coveralls==1.1
cryptography==1.5.3
cupshelpers==1.0
custodia==0.1.0
decorator==4.0.10
demo==0.1
di==0.3
Django==1.7
django-htmlmin==0.10.0
dnspython==1.12.0
docker-compose==1.9.0
docker-py==1.10.6
docker-pycreds==0.2.1
dockerpty==0.4.1
docopt==0.6.2
docutils==0.13.1
entrypoints==0.2.2
enum34==1.1.6
ethtool==0.8
extras==1.0.0
firstboot==19.5
fixtures==3.0.0
flake8==3.3.0
** Flask==0.10 **
Flask-AppBuilder==1.8.1
Flask-Babel==0.11.1
Flask-Bootstrap==3.2.0.2
Flask-Cache==0.13.1
Flask-Login==0.2.11
Flask-Migrate==1.5.1
Flask-OAuthlib==0.9.2
Flask-OpenID==1.2.5
Flask-Script==2.0.5
Flask-SQLAlchemy==2.0
Flask-SSLify==0.1.5
Flask-Testing==0.5.0
Flask-WTF==0.14.2
freeipa==2.0.0a0
fros==1.0
funcsigs==1.0.2
functools32==3.2.3.post2
funcy==1.7.1
future==0.16.0
futures==3.0.5
GDAL==1.10.1
gssapi==1.2.0
gunicorn==19.6.0
honcho==0.5.0
html5lib==0.9999999
httplib2==0.9.2
humanize==0.5.1
idna==2.0
imagesize==0.7.1
iniparse==0.4
initial-setup==0.3.9.36
iotop==0.6
ipaclient==4.4.0
ipaddr==2.1.9
ipaddress==1.0.17
ipalib==4.4.0
ipaplatform==4.4.0
ipapython==4.4.0
IPy==0.75
ipykernel==4.5.2
ipython==5.1.0
ipython-genutils==0.1.0
ipywidgets==5.2.2
itsdangerous==0.24
javapackages==1.0.0
Jinja2==2.8.1
jmespath==0.9.1
jsonpointer==1.9
jsonschema==2.5.1
jupyter==1.0.0
jupyter-client==4.4.0
jupyter-console==5.0.0
jupyter-core==4.2.1
jwcrypto==0.2.1
kdcproxy==0.3.2
kerberos==1.1
kitchen==1.1.1
kmod==0.1
kombu==3.0.37
langtable==0.0.31
limits==1.2.1
linecache2==1.0.0
lvm===2.02.166-2-RHEL7.-2016-11-16-
lxml==3.2.1
M2Crypto==0.21.1
Magic-file-extensions==0.2
Mako==0.8.1
MapProxy==1.9.0
Markdown==2.6.6
MarkupSafe==0.23
matplotlib==1.2.0
mccabe==0.6.1
meld3==1.0.2
mistune==0.7.3
mock==1.0.1
MySQL-python==1.2.5
mysqlclient==1.3.9
nbconvert==5.0.0
nbformat==4.2.0
netaddr==0.7.5
netifaces==0.10.4
nose==1.3.7
notebook==4.3.1
ntplib==0.3.2
numpy==1.11.3
oauthlib==2.0.1
olefile==0.44
openlmi==0.5.0
os-testr==0.8.0
OWSLib==0.9.0
pandas==0.18.1
pandocfilters==1.4.1
paramiko==2.0.0
parsedatetime==2.0
passlib==1.6.2
Paste==1.7.5.1
pathlib2==2.1.0
pbr==1.10.0
pcp==1.0
peewee==2.6.1
perf==0.1
pexpect==4.2.1
pickleshare==0.7.4
Pillow==2.5.1
pipreqs==0.4.6
ply==3.4
policycoreutils-default-encoding==0.1
prompt-toolkit==1.0.9
protobuf==3.1.0.post1
psycopg2==2.6.2
ptyprocess==0.5.1
pyasn1==0.1.9
pycodestyle==2.3.1
pycparser==2.14
pycrypto==2.6.1
pycups==1.9.63
pycurl==7.19.0
pydruid==0.3.1
pyflakes==1.5.0
Pygments==2.1.3
pygobject==3.14.0
pygpgme==0.3
PyHive==0.2.1
pyinotify==0.9.4
pykickstart==1.99.66.10
pyliblzma==0.5.3
pymongo==3.2.1
pyOpenSSL==0.13.1
pyparsing==2.0.3
pyparted==3.9
pyrsistent==0.11.13
pysaml2==2.4.0
pysmbc==1.0.13
PySocks==1.5.7
pystache==0.5.4
python-augeas==0.5.0
python-dateutil==2.5.3
python-dmidecode==3.10.13
python-editor==1.0.3
python-keyczar==0.71rc0
python-ldap==2.4.15
python-meh==0.25.2
python-memcached==1.48
python-mimeparse==1.6.0
python-nss==0.16.0
python-openid==2.2.5
python-subunit==1.2.0
python-yubico==1.2.3
pytz==2016.10
pyudev==0.15
pyusb==1.0.0b1
pywbem==0.7.0
pyxattr==0.5.1
PyYAML==3.12
pyzmq==16.0.2
qrcode==5.0.1
qtconsole==4.2.1
raven==5.27.1
redis==2.10.5
repoze.who==2.3
requests==2.10.0
requests-oauthlib==0.7.0
RestrictedPython==3.6.0
rtslib-fb==2.1.57
s3transfer==0.1.10
sasl==0.2.1
scandir==1.4
scdate==1.10.6
selenium==3.0.2
semver==2.2.1
seobject==0.1
sepolicy==1.1
setproctitle==1.1.9
setroubleshoot==1.1
shadowsocks==2.8.2
simplegeneric==0.8.1
simplejson==3.8.2
singledispatch==3.4.0.3
six==1.10.0
slip==0.4.0
slip.dbus==0.4.0
snowballstemmer==1.2.1
speaklater==1.3
Sphinx==1.5.2
sphinx-intl==0.9.9
sphinx-rtd-theme==0.1.9
sphinxcontrib.youtube==0.1.2
SQLAlchemy==1.0.13
SQLAlchemy-Utils==0.32.7
sqlparse==0.1.19
SSSDConfig==1.14.0
statsd==2.1.2
-e git+https://github.com/uptonking/supersetx.git@f2bf3160583533bd0dc5004f248f81251aa8c57e#egg=superset
supervisor==3.3.1
targetcli-fb===2.1.fb41
targetd==0.7
Tempita==0.5.1
tensorflow==0.12.1
terminado==0.6
testpath==0.3
testrepository==0.0.20
testtools==2.2.0
texttable==0.8.7
thrift==0.9.3
thrift-sasl==0.2.1
tornado==4.4.2
traceback2==1.4.0
traitlets==4.3.1
unittest2==1.1.0
urlgrabber==3.10
urllib3==1.15.1
urwid==1.1.1
vboxapi==1.0
virtualenv==15.1.0
wcwidth==0.1.7
WebOb==1.7.1
websocket-client==0.40.0
Werkzeug==0.11.10
widgetsnbextension==1.2.6
wtf-peewee==0.2.3
WTForms==2.1
xlrd==0.9.3
XlsxWriter==0.9.3
yarg==0.1.9
yum-langpacks==0.4.2
yum-metadata-parser==1.1.4
zope.interface==4.3.3
```

**Comment by asdf2014** [comment]
I think you should reinstall the `Flask`.
pip freeze | grep Flask
```
Flask==0.12
Flask-AppBuilder==1.8.1
Flask-Babel==0.11.1
Flask-Cache==0.13.1
Flask-Login==0.2.11
Flask-Migrate==1.5.1
Flask-OpenID==1.2.5
Flask-Script==2.0.5
Flask-SQLAlchemy==2.0
Flask-Testing==0.5.0
Flask-WTF==0.14.2
```
The requirement `** Flask==0.10 **` does not look good...

**Comment by asdf2014** [comment]
image
@uptonking

**Comment by uptonking** [comment]
@asdf2014 thanks. superset nice again :+1:

**Comment by asdf2014** [comment]
Congratulations! And u r welcome :D

**Pull request merged**
