### PR TITLE
feat: add chart description in info tooltip

### PR DESCRIPTION
**Pull request by stephenLYZ**
### SUMMARY

Add info tooltip for chart description in the chart list.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

image

### ADDITIONAL INFORMATION

- [x] Has associated issue: #17204 
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by geido** [comment]
@stephenLYZ I think there is still some adjustment to do. If you look at the screenshot you will notice that the text cuts a little bit vertically

Screen Shot 2021-11-09 at 17 44 24

**Comment by stephenLYZ** [comment]
@geido Oh yes! The text will crop when using `overflow: hidden` with `lineheight:1`. I just fixed it.
image

**Review by geido — APPROVED** [review]
LGTM

**Pull request merged**
