### PR TITLE
refactor(TestChartApi):  move chart data api tests into TestChartDataApi

### PR DESCRIPTION
**Pull request by ofekisr**
## **Background** 
When we have worked on #16991 we wanted to test the new functionalities in concrete and accurate unittest.
All chartData flows and its components are too couple to superset so it is impossible to create unittests. 
The flows are not testable and so many components do not meet the very important principle SRP and the code became so dirty 

So I've started to refactor it (#17344 ) but many changes were added and it was hard to review so I decided to split those changes into small PRs so will be easier to follow 

This is the fourth PR in a sequence of PRs to meet these
The Next PR is #17425 

## PR description
In #17400, ChartData endpoints were moved to a new view, so the tests should move too. 

What else?
1. Improve tests setup - it doesn't sense each test will do the same setup instead in one place, 
2. improve get_query_contexe setup - it doesn't sense that each test will force call the database over and over. so now it will call the DB once and create a query context template. Then each test will copy the query context template. 
4. Advance another one step further into using pytest without unittest coupling 
5. improve test cases names so it will be clear what the test is done and expected. 

### Test plans 
should we test the tests? :) 

## Previous PRs
1. #17399
2. #17400 
3. #17405

### CODE REVIEW

**Comment by junlincc** [comment]
Thanks for the contribution! @ofekisr  Looping domain experts in to review your PR. since it's an XXL one with high risk, we may take awhile to get through the review. Please stay tuned. 

cc @craig-rueda @betodealmeida @villebro

**Comment by ofekisr** [comment]
> Thanks for the contribution! @ofekisr  Looping domain experts in to review your PR. since it's an XXL one with high risk, we may take awhile to get through the review. Please stay tuned. 
> 
> cc @craig-rueda @betodealmeida @villebro 

Note, It containes the commit of previous pr

**Comment by junlincc** [comment]
https://github.com/apache/superset/pull/17344 this one right?

**Comment by ofekisr** [comment]
> Thanks for the contribution! @ofekisr Looping domain experts in to review your PR. since it's an XXL one with high risk, we may take awhile to get through the review. Please stay tuned.
> 
> cc @craig-rueda @betodealmeida @villebro

 I sync the branch from master so now it contains only 3 files

**Comment by junlincc** [comment]
@ofekisr could you list the product area that will be affected by your PR, and do a simple audit what's the test coverage look like in those area?

**Comment by amitmiran137** [comment]
Product area is not affected bc no code changes to the product only to tests
The focus is separate chart/data tests from the rest of the chart domain tests and to properlu name those existing tests with meaningful names

**Comment by amitmiran137** [comment]
Product area is not affected bc no code changes to the product only to tests
The focus is separate chart/data tests from the rest of the chart domain tests and to properlu name those existing tests with meaningful names

**Comment by ofekisr** [comment]
mapping from the old test name (chartApiTest) to the new name in ChartDataApiTest

test_chart_data_simple --> test_with_valid_qc__data_is_returned
test_chart_data_get_no_query_context --> test_get_data_when_query_context_is_null
test_chart_data_get === test_chart_data_get
test_chart_data_applied_time_extras === test_chart_data_applied_time_extras
test_chart_data_limit_offset --> test_with_row_limit_and_offset__row_limit_and_offset_were_applied
test_chart_data_default_row_limit --> test_without_row_limit__row_count_as_default_row_limit
test_chart_data_sql_max_row_limit --> test_with_row_limit_bigger_then_sql_max_row__rowcount_as_sql_max_row
test_chart_data_sample_default_limit --> test_as_samples_without_row_limit__row_count_as_default_samples_row_limit
test_chart_data_sample_custom_limit --> test_with_row_limit_as_samples__rowcount_as_row_limit
test_chart_data_sql_max_row_sample_limit --> test_as_samples_with_row_limit_bigger_then_sql_max_row__rowcount_as_sql_max_row
test_chart_data_incorrect_result_type --> test_with_incorrect_result_type__400
test_chart_data_incorrect_result_format --> test_with_incorrect_result_format__400
test_chart_data_invalid_form_data --> test_with_invalid_payload__400
test_chart_data_query_result_type --> test_with_query_result_type__200
test_chart_data_csv_result_format --> test_with_csv_result_format
test_chart_data_csv_result_format_permission_denined --> test_with_csv_result_format_when_actor_not_permitted_for_csv__403
test_chart_data_mixed_case_filter_op --> test_with_in_op_filter__data_is_returned
test_chart_data_dttm_filter === test_chart_data_dttm_filter
test_chart_data_prophet === test_chart_data_prophet
test_chart_data_query_missing_filter --> test_with_query_result_type_and_non_existent_filter__filter_omitted
test_chart_data_no_data --> test_with_filter_suppose_to_return_empty_data__no_data_returned
test_chart_data_incorrect_request --> test_with_invalid_where_parameter__400
test_chart_data_with_invalid_datasource --> test_with_invalid_datasource__400
test_chart_data_with_invalid_enum_value --> test_with_invalid_time_range_endpoints_enum_value__400
test_query_exec_not_allowed --> test_with_not_permitted_actor__401
test_chart_data_jinja_filter_request --> test_when_where_parameter_is_template_and_query_result_type__query_is_templated
test_chart_data_async === test_chart_data_async
test_chart_data_async_cached_sync_response === test_chart_data_async_cached_sync_response
test_chart_data_async_results_type === test_chart_data_async_results_type
test_chart_data_async_invalid_token === test_chart_data_async_invalid_token
test_chart_data_cache === test_chart_data_cache
test_chart_data_cache_run_failed === test_chart_data_cache_run_failed
test_chart_data_cache_no_login === test_chart_data_cache_no_login
test_chart_data_cache_key_error === test_chart_data_cache_key_error
test_chart_data_annotations --> test_with_annotations_layers__annotations_data_returned
test_chart_data_rowcount === test_chart_data_rowcount
test_chart_data_timegrains --> test_with_timegrains_and_columns_result_types
test_chart_data_series_limit --> test_with_series_limit

**Review by amitmiran137 — APPROVED** [review]
Reviewed that entire 2 suites of tests move and renaming and all test remain as the original.
Some boiler plate code was moved to setup 
LGTM!

**Comment by villebro** [comment]
This was a nice improvement and provides for a much better chart API development experience!

**Pull request merged**
