### PR TITLE
fix: Revert "chore: Bump @svgr/webpack to 5.5.0"

### PR DESCRIPTION
**Pull request by rusackas**
Reverts apache/superset#15349

This upgrade was causing other dependency issues. We still need to address it, but want to unblock things for now. 

More PRs/discussion around this upgrade, and others, coming soon...

### CODE REVIEW

**Review by kgabryje — APPROVED** [review]

**Comment by graceguo-supercat** [comment]
thank you @rusackas!

**Review by graceguo-supercat — APPROVED** [review]
LGTM

**Comment by graceguo-supercat** [comment]
ping @rusackas could you resolve conflicts and merge this PR? thanks!

**Comment by rusackas** [comment]
Ugly rebase... will open a new revert. Sorry, thought this was merged.

**Pull request closed without merging**
