### PR TITLE
fix(logs): increase json field for logs table

### PR DESCRIPTION
**Pull request by cnabro**
### SUMMARY
- Increase json field for logs table. (Text to MediumText)
- When insert logs while imports a specific dashboard, An error occured.
```
(MySQLdb._exceptions.DataError) (1406, "Data too long for column 'json' at row 1")
[SQL: INSERT INTO logs (`action`, user_id, dashboard_id, slice_id, json, dttm, duration_ms, referrer) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('copy_dash', '1', 9, 0, '{"path": "/superset/copy_dash/9/", "data": "{\\"certified_by\\":\\"\\",\\"certification_details\\":\\"\\",\\"css\\":\\"\\",\\"dashboard_title\\":\\"G ... (171666 characters truncated) ... BS\\"}},\\"filter_scopes\\":\\"{}\\"}", "url_rule": "/superset/copy_dash/<int:dashboard_id>/", "object_ref": "Superset.copy_dash", "dashboard_id": 9}', datetime.datetime(2023, 8, 7, 6, 50, 6, 897685), 6474, '[http://__/superset/dashboard/9/?native_filters_key=A27QtFLKT95Qdd0X-h4KkTLZTBhOslCg0Jshcisx4A8FM71hI_Ae6pBdTc4ac94f')](http://__/superset/dashboard/9/?native_filters_key=A27QtFLKT95Qdd0X-h4KkTLZTBhOslCg0Jshcisx4A8FM71hI_Ae6pBdTc4ac94f%27))]
```

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
```
0769ef90fddd -> 2e826adca42c (head), Fix schema for log
ee179a490af9 -> 0769ef90fddd, Fix schema perm for datasets
e0f6f91c2055 -> ee179a490af9, deckgl-path-width-units
bf646a0c1501 -> e0f6f91c2055, create_user_favorite_table
a23c6f8b1280 -> bf646a0c1501, json_metadata
```

### TESTING INSTRUCTIONS
```sql
ALTER TABLE logs MODIFY json MEDIUMTEXT;
Query OK, 556821 rows affected (5.10 sec)
```
- Estimate 100000 rows updated per 1 sec

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [x] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [x] Migration is atomic, supports rollback & is backwards-compatible
  - [x] Confirm DB migration upgrade and downgrade tested
  - [x] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by craig-rueda — APPROVED** [review]
LGTM

**Comment by john-bodley** [comment]
@cnabro thanks for the change. Would you mind also authoring a follow up PR which adds a line record to `UPDATING.md` which states that downtime is likely required in order to run this migration? A DDL operation (which locks the table) on the heavily used `logs` table will likely result in the service being inoperable.

**Comment by cnabro** [comment]
@john-bodley Thank you. I'd added some notices in this PR (https://github.com/apache/superset/pull/24923).
And I'd added descriptions for estimated times for this migration.

**Comment by cnabro** [comment]
@john-bodley Ok. I'll give you another PR 😀

**Pull request merged**
