### PR TITLE
[ui] update logo, favicon, and new primary color

### PR DESCRIPTION
**Pull request by ascott**
screenshot 2016-12-06 21 11 39

screenshot 2016-12-06 21 11 10

screenshot 2016-12-06 13 30 42

plz review @airbnb/superset-reviewers

### CODE REVIEW

**Comment by mistercrunch** [comment]
neat! though the logo/text in the navbar looks a little low compared to the menu items

**Comment by ascott** [comment]
good point @mistercrunch. discussing/adjusting with eli on this now.

**Comment by bkyryliuk** [comment]
lovely !

**Comment by mistercrunch** [comment]
The current pngs look fuzzy on my retina screen. We need more resolution to get the images as crisp as possible. Are retina screen like 4x the resolution?

**Comment by ascott** [comment]
retina is 2x, which i am using in the header image. you pulled the branch down or the screenshots here look fuzzy?

**Comment by vera-liu** [comment]
this looks so much better than neon blue! 👏

**Comment by mistercrunch** [comment]
I'm anxious to see this in my branch, merging!

**Comment by ascott** [comment]
updated the alignment of the logo and nav items and updated the screenshots. PTAL @mistercrunch @elibrumbaugh!

**Pull request merged**
