### PR TITLE
chore(de-translations): Add and fix German translations

### PR DESCRIPTION
**Pull request by hbruch**
### SUMMARY
This PR adds missing and improves some German translations, based on current `POT` file.
 
### TESTING INSTRUCTIONS
1. Enable German translations by adding `"de": {"flag": "de", "name": "Deutsch"},` to the enabled `LANGUAGES` (I'd eve suggest to add this now per default, as it should be fully translated)
2. start superset
3. Switch to German translations and check, if all messages are translated and meaningful

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by hbruch** [comment]
@villebro the failing test again seems to be a flaky test, or is there anything I can do about it?

**Comment by villebro** [comment]
Thanks again @hbruch - I restarted CI and will babysit until it passes

**Review by villebro — APPROVED** [review]
LGTM!

**Comment by villebro** [comment]
Vielen dank @hbruch !

**Pull request merged**
