### PR TITLE
Granularity datetime formatting workaround

### PR DESCRIPTION
**Pull request by gbrian**
Workaround for:
https://github.com/airbnb/caravel/issues/266
https://github.com/airbnb/caravel/issues/185

### CODE REVIEW

**Comment by mistercrunch** [comment]
I'm not sure what happened but the PR looks busted...

**Comment by mistercrunch** [comment]
Your PRs are picking up a bunch of commits that should not be in there. Please read about how to Github, the common flows are well documented.

**Comment by pablocabana** [comment]
This PR was denied, right? Are you guys planning another fix for this?

**Comment by gbrian** [comment]
New PR created. Sorry for the error. https://github.com/airbnb/caravel/pull/332

**Pull request closed without merging**
