### PR TITLE
fix(dashboard): Make the View Chart In Explore menu option a link

### PR DESCRIPTION
**Pull request by suddjian**
### SUMMARY

This is more accessible and allows opening the link in a new tab/window, or in the current one based on user preference.
I also made sure that filters from the dashboard come through in Explore.

### TESTING INSTRUCTIONS

In any dashboard, under a chart's context menu, click the link to View Chart In Explore.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by rosemarie-chiu — APPROVED** [review]
I like it! Good middle ground for user want to open new tabs and for those who don't!

QA Product visual test approved. 
CleanShot 2021-07-13 at 16 10 13

**Review by junlincc — COMMENTED** [review]
Product sign-off 

@suddjian I LOVE IT. THANK YOU! how hard it is to implement the solution to Superset overall? meaning giving an option to open menu items in different tab. Just curious, not priority.

**Comment by suddjian** [comment]
> how hard it is to implement the solution to Superset overall? meaning giving an option to open menu items in different tab. Just curious, not priority.

I would implement these on a case-by-case basis. Most of the time it probably isn't a huge change.

**Comment by jinghua-qa** [comment]
nice to have an option to open in a separate tab!

**Review by michael-s-molina — APPROVED** [review]
LGTM. Thanks for organizing the props and adding docs to the URL functions.

**Review by rusackas — APPROVED** [review]
Awesomesauce.

**Comment by rusackas** [comment]
@graceguo-supercat @etr2460 @john-bodley Just wanted to make sure this is OK for y'all. Ping us if it needs further discussion, but this seems very flexible, so users can command-click like any other conventional website link.

**Comment by ktmud** [comment]
@rusackas I like the improvements on accessibility and we should do more of this on all links and buttons!

However, for this specific link, I still feel opening in the same tab is a worse _default_ experience than opening in a new tab when navigating back to the dashboard means reloading the whole page from scratch.... It'd be much smoother is the Explore page is also part of the SPA and navigating back to dashboard won't lose its previous state.

**Comment by graceguo-supercat** [comment]
@rusackas This is the only button in whole Superset app that has `command-click`? How could user be aware of it?

**Comment by nytai** [comment]
@graceguo-supercat any html `<a>` attr has this `command + click` behavior

**Comment by rosemarie-chiu** [comment]
🏷 2021.27

**Pull request merged**
