### PR TITLE
fix: pass correct report_format

### PR DESCRIPTION
**Pull request by eschutho**
### SUMMARY
We were passing "TEXT" for all report_types and it was breaking dashboards which require a PNG report type. The result was that we were receiving emails with no image for dashboards. 

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
before: 
Screenshot_8_17_21__5_20_PM
after:
All_Mail__26_636_messages__19_366_unread_

### TESTING INSTRUCTIONS
create a report from a dashboard page and verify that the email has a png image in it. 
unit tests are currently in review in a separate pr. Will update them to add this functionality.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by eschutho** [comment]
@betodealmeida if this looks good to you and passes CI, feel free to merge if you need it.

**Review by betodealmeida — APPROVED** [review]
Awesome!

**Comment by stevenuray** [comment]
🏷️ 2021.31.10

**Comment by stevenuray** [comment]
🏷️ 2021.31

**Pull request merged**
