### PR TITLE
Allow users to view dashboards they own

### PR DESCRIPTION
**Pull request by jeffreythewang**
This change allows users to see the dashboards they own listed in the dashboard list. Previously, users could only see dashboards in the list if the dashboard contained at least 1 chart that they have access to. This means that a user cannot find their dashboard in the list if they create an empty dashboard (either by mistake, or as a blank template to start adding charts).

For the case where they are the owner of a dashboard, but all of the charts in their dashboard are not accessible (which can only happen if an additional owner adds an inaccessible chart to the dashboard), they will see a dashboard with a bunch of charts with permission errors. I think this is okay, as it is the same behavior as when a user has access to some but not all charts in a dashboard. Feel free to comment otherwise, and I can add an additional check for this to be applied to empty dashboards only.

### CODE REVIEW

**Comment by timifasubaa** [comment]
LGTM

**Comment by timifasubaa** [comment]
Fixes https://github.com/apache/incubator-superset/issues/4352

**Comment by jeffreythewang** [comment]
Tagging issue https://github.com/apache/incubator-superset/issues/911 on here as well as it could be related.

It seems like users have a similar issue beyond a Dashboard context. I did not realize it was possible to create a datasource/table without having access to the underlying database/schema of that datasource/table. Even with this change, they may still have that issue, as this change only solves the case of not being able to see an empty / inaccessible dashboard in the dashboard list. I do not think this fixes the issues mentioned above, unless other parts of the code have changed since then.

**Comment by timifasubaa** [comment]
Ah, I see. I misread Dashboard as Datasource.

**Comment by jeffreythewang** [comment]
Any updates on this?

**Comment by timifasubaa** [comment]
I don't have merge privileges but this LGTM.

**Comment by john-bodley** [comment]
@jeffreythewang isn't the current logic that a user is able to see the dashboard if the have access to _at least_ one of the underlying slices (as opposed to _all_), per this logic:
```
query = query.filter(
    Dash.id.in_(
        db.session.query(Dash.id)
        .distinct()
        .join(Dash.slices)
        .filter(Slice.id.in_(slice_ids_qry)),
     ),
)
```
My understanding is this query returns the distinct dashboard IDs which are represented by _any_ (per the `IN condition) of the sanctioned slices. I wonder whether this is being confused with https://github.com/apache/incubator-superset/issues/4737.

**Comment by jeffreythewang** [comment]
@john-bodley Yes that is the current logic. This change mainly addresses the case where a Dashboard is empty, as the user will not be able to see it since they do not have access to any slices in the Dashboard (because there are no slices in the Dashboard).

With this change, if the Dashboard contains zero slices, but you are the owner of that Dashboard, you will still be able to view it in the Dashboard list. This happens when a user wants to start by creating an empty dashboard, and then adding slices to it. It's not a common use case, but it happens sometimes.

**Comment by john-bodley** [comment]
@jeffreythewang I agree with your logic regarding empty dashboards which this PR resolves, but I think your original comment
> For the case where they are the owner of a dashboard, but their dashboard has charts they do not have access to (which can only happen if an additional owner adds an inaccessible chart to the dashboard)

is not correct according to the current logic. Maybe it would be good to updated the PR title and description to better reflect the change. Also I wonder whether a unit test would be valuable here.

**Comment by jeffreythewang** [comment]
Ah I see. Yeah that comment was written before https://github.com/apache/incubator-superset/pull/4405 was merged. I've updated it now.

I'll add a unit test.

**Comment by john-bodley** [comment]
Thanks @jeffreythewang

**Comment by john-bodley** [comment]
Note this filter is also used when you try to add a slice to an existing dashboard and thus if you create an empty dashboard you'll now be able to add a slice to it.

**Comment by jeffreythewang** [comment]
@john-bodley just an update - I've added a unit test

**Review by john-bodley — APPROVED** [review]

**Pull request merged**
