### PR TITLE
feat: Add error pages

### PR DESCRIPTION
**Pull request by samtfm**
### SUMMARY
Adds custom 404 and 500 error pages as static html

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
404 Screen Shot
500 Screen Shot

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by dpgaspar** [comment]
nit: @samtfm can you add to the description on the PR, that this is just a placeholder, since they are not actually going to get rendered

**Comment by etr2460** [comment]
Hi @samtfm, thanks for the contribution! I'm wondering if you could speak a bit about the architecture approach you chose here.

Most of the frontend assets in Superset are rendered using React, and those that don't we're quickly trying to replace (like the HTML templates that flask renders). Why was the decision made to use raw HTML and CSS for these pages instead of making use of the shared React components and React render logic already available in the app?

**Comment by willbarrett** [comment]
Hi @etr2460 the goal from Preset's side is to add static error pages that can be rendered directly from a web server (such as nginx) without relying on the rest of the systems. We thought they might be nice to contribute back to the community for others who have the same need. Happy to make that more obvious however it would be most useful.

**Comment by etr2460** [comment]
Thanks for the context @willbarrett! Adding this to the PR summary would definitely be helpful (especially since they're not used anywhere in code, and therefore might get deleted as unused code in the future without that documentation).

Also, for this use case, I wonder if the CSS (and even images with base64) should be embedded within the html files to prevent further dependencies.

**Comment by willbarrett** [comment]
Yes, I think that's a good idea @etr2460 - a little duplication would make them easier to deploy. If we find we need more than two, it might be possible to create a simple static page generator to spit them out, but I think we should wait for a request for a 3rd error page before going down that path.

**Comment by willbarrett** [comment]
Perhaps we can add a README to the `static-pages` folder to explain the presence of these HTML files.

**Comment by samtfm** [comment]
Thanks all. Copying the css into the two files sounds good. I'd also propose I move the referenced image files into this static-pages directory.

I'm a little wary of the legibility of embedding images as base64 if these aren't going to be auto-generated, but I suppose I could still include the source files in the same folder, and include the steps for updating the html in the README.

**Comment by ktmud** [comment]
Maybe you can take advantage of the [html-webpack-plugin](https://webpack.js.org/plugins/html-webpack-plugin/) to build a static error pages with all styles and images embedded?

I'm also wondering whether it makes sense to let Python/Jinja render 404 and 403 first, and only fallback to a static 500 page in Nginx if the Python render fails. So you can do more advanced stuff with these error pages like having global navs and render more customized error messages, etc

**Comment by samtfm** [comment]
@ktmud thank you for the suggestion! I've refactored this using html-webpack-plugin to render these html files directly to the distribution folder.
I'm leaving the css hard coded into each html file for now, because fully embedding it from a separate file would require _even more_ complications to the webpack config, and I think this is fine enough for now with just these two pages.

(package-lock.json got updated in a big way that I didn't intend, I am currently looking into how to tell npm to add a package without doing this lockfileVersion update)

**Comment by ktmud** [comment]
@samtfm Did you use `npm 7`? We recently upgrade `lockfileversion 2` but you need to use `npm 7`: https://github.com/apache/superset/pull/13100

**Review by willbarrett — APPROVED** [review]
LGTM once rebased.

**Pull request merged**
