### PR TITLE
fix(helm): fixing helm chart dependency

### PR DESCRIPTION
**Pull request by ochalover**
Fixing https://github.com/apache/superset/issues/31613
### SUMMARY

+ adding ocr paths for both charts.
+ I am not sure if I should update chart version to the latest as well cause this chart on main branch has CVE issues.

### TESTING INSTRUCTIONS

Ran helm dependency build to generate new locks.
```Update Complete. ⎈Happy Helming!⎈
Saving 2 charts
Downloading postgresql from repo oci://registry-1.docker.io/bitnamicharts
Pulled: registry-1.docker.io/bitnamicharts/postgresql:12.1.6
Digest: sha256:640c97bc5971fccdd1be6b2c7b399da8858fa83a0cae9ff5ab3dca53a17d1c56
Downloading redis from repo oci://registry-1.docker.io/bitnamicharts
Pulled: registry-1.docker.io/bitnamicharts/redis:17.9.4
Digest: sha256:e20bf7d76f2df0182ff7dd89b19708a80e721450efad891eab314ea892639f78
Deleting outdated charts

```

### ADDITIONAL INFORMATION

- [X ] Has associated issue:
- [ X] Required feature flags:
- [X ] Changes UI
- [ X] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [X ] Migration is atomic, supports rollback & is backwards-compatible
  - [ X] Confirm DB migration upgrade and downgrade tested
  - [X ] Runtime estimates and downtime expectations provided
- [ X] Introduces new feature or API
- [X ] Removes existing feature or API

### CODE REVIEW

**Comment by ochalover** [comment]
I am not sure if this is related or not? Is it ok to fix initialbootupscript? It is giving psycog2 error cause new docker image is lacking that.

**Review by villebro — APPROVED** [review]
LGTM, thanks for the fix!

**Comment by villebro** [comment]
@ochalover please check #31627. Feel free to make the same changes in this PR to avoid having to wait for my PR to get merged first.

**Comment by ochalover** [comment]
closing this as changes are migrated to @villebros fork

**Pull request closed without merging**
