### PR TITLE
[dashboard v2] ui + ux fixes

### PR DESCRIPTION
**Pull request by williaster**
This PR fixes a lot of UI/UX issues for the [new dashboard](https://github.com/apache/incubator-superset/pull/4528) for release.

- iterates on row/column visual hierarchy:
  - rows and columns are always shown with dashed grey outlines
  - on row/column hover, drop shadows are replaced with dashed blue outlines
  - adds dashed blue outlines to header + chart + markdown components
  
- adds empty drop targets at the top + bottom of `<Tab />` + `<DashboardGrid />` components which increase the size of the drop mouse target zone so that you can more easily drop at the edges of these components (shown as red below)
  empty-droptargets
- adds more compressed loading gif and updates **all** references to `loading.gif` throughout the app to `<Loading />` so there is one source of truth
- makes heading style dropdown options match styles + fix hover/selected styles 
  
- removes padding from markdown components when focused/editing to maximize editing space
  
- adds a slight red drop shadow to the cached data indicator to make it pop more
  
- adds a mostly-transparent background to dragging slices which enables seeing the drop indicator more clearly
  screen shot 2018-06-15 at 1 16 02 am

- fixes a bug where the `moveComponent` action didn't trigger a `hasUnsavedChanges=true` update
- corrects dashboard load logging to account for first mount

@graceguo-supercat @elibrumbaugh

a couple more things to finish 

**TODO**
- [x] verify logging fix
- [x] fix sidebar double scroll issue
- [x] ctrl+z/+y key listeners, with visual feedback indicator
- [x] update loader gif to gray
- [x] make header sticky
- [x] fix top-level tabs css (broken after sticky header)
- [x] add better auto-resize functionality on component move

### CODE REVIEW

**Comment by elibrumbaugh** [comment]
Amazing work Chris!

> adds empty drop targets at the top + bottom of <Tab /> + <DashboardGrid /> components which increase the size of the drop mouse target zone so that you can more easily drop at the edges of these components (shown as red below)

Is that shown as red is that to illustrate the target zone for the gif?

**Comment by williaster** [comment]
yes, red was added purely to visualize it in the gif/doesn't appear in actual UI.

**Comment by graceguo-supercat** [comment]
@john-bodley do you have any backend task that monitor if `img` tag has `class=loading`? i think this PR will remove `class=loading`

**Comment by john-bodley** [comment]
Thanks @graceguo-supersetcat for mentioing that. We use this internally for determining when the screen capture should happen.

**Comment by williaster** [comment]
that shouldn't matter I think because https://github.com/apache/incubator-superset/pull/5208/files#diff-a31afeea7dd66f1cc1fdec4675a70212L14

**Review by graceguo-supercat — APPROVED** [review]
LGTM

**Pull request merged**
