### PR TITLE
fix(cypress): flake cypress test case

### PR DESCRIPTION
**Pull request by zhaoyongjie**
### SUMMARY

Currently, the master branch has been blocked by a flake test from cypress. This PR fixes it.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

N/A

### TESTING INSTRUCTIONS

Cypress guaranteed

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by villebro — APPROVED** [review]
LGTM, also seeing this one flake in one of my PRs - I'm curious if you know how this has been passing if the row counts have been off? I assume we haven't done any changes lately that would have affected these assertions..

**Comment by kgabryje** [comment]
We don't set an absolute time filter, but a relative one - minus 40 years. The year has changed 4 days ago and we've cut out 1 result.

**Comment by villebro** [comment]
Lol, I look forward to redoing this in January 2023 😆

**Comment by kgabryje** [comment]
Let's merge this PR, but I hope we can fix this properly becuase it's ridiculous 😆

**Pull request merged**
