### PR TITLE
Add fix for pyodbc+mssql

### PR DESCRIPTION
**Pull request by chinhngt**
* Handle Row object returned by pyodbc/msodbc
* Add tests

### CODE REVIEW

**Comment by chinhngt** [comment]
@marcusianlevine Can you help to take a look? This should fix several issues reported earlier like:

https://github.com/apache/incubator-superset/issues/3934
https://github.com/apache/incubator-superset/issues/4210
https://github.com/apache/incubator-superset/issues/4211
https://github.com/apache/incubator-superset/issues/3075

**Comment by xrmx** [comment]
@chinhngt you missed to write what is the problem you are fixing. I suppose one between the tuple or the iterator breaks something else later in the chain. Or maybe both? I don't know the code but maybe it's the caller that must be fixed as an iterator may be a good idea to save memory.

**Comment by chinhngt** [comment]
@xrmx Currently when using Superset with pyodbc, the data pyodbc execute returns is in the form of [pyodbc.Row, pyodbc.Row, ...] instead of [(tuple), (tuple), ...] so SupersetDataFrame throws exception on wrong shape. This change converts pyodbc.Row object to regular list before passing to SupersetDataFrame. I think BigQuery (BQEngineSpec in db_engine_specs.py) is doing similar thing :)

**Comment by xrmx** [comment]
@chinhngt thanks for the explanation. So you have to prepare data that pandas can digest for a DataFrame.
It looks like pyodbc always use Row classes as it implements the DB API, wouldn't it better to poke at the connection uri instead of looking at the data?

**Comment by chinhngt** [comment]
@xrmx I don't see sqla uri is available within db_engine_specs. Any hint?

**Comment by chinhngt** [comment]
@xrmx Yes, it works for both Azure SQL and Azure Datawarehouse for me.

**Comment by bolkedebruin** [comment]
@mistercrunch as this PR was not rebased against master the license check did not kick in on the PR. It does have a new file and therefore master now fails building. To solve this have a PR with a license header on an *existing* file ;-)

**Pull request merged**
