### PR TITLE
Gantt Chart visualization

### PR DESCRIPTION
**Pull request by boorad**
Here's my cut at a Gantt chart visualization.   There are some new components in there, to map column values to styles/colors for the chart.  This should be useful for #4035.

### CODE REVIEW

**Comment by mistercrunch** [comment]
I pulled the branch and reloaded the examples, but the example chart failed to load properly. Looks like control name mismatch between the example and the actual new controls. After finding the `tasks` table and picking the right fields and colors it started looking good.

I also like the new `StyleMappingControl`, I can see reusing this in other places. 

Few usability recommendations before I get into the code:
* we should use a palette and attribute colors to statuses for the ones that user have not provided a color mapping yet (checkout function `getColorFromScheme`)
* the status should be in the tooltip
* there's an epoch-looking number in the tooltip, let's remove it or use something more human readable
* hovering the boxes drop the border
* visually things look different than the nvd3, anything that would make it look more align would be best, maybe reusing some of the nvd3 css classes in the axis svg?

**Comment by xeijin** [comment]
@boorad were you able to make further progress on this? Very keen to see it per #4035 😄

**Comment by boorad** [comment]
@xeijin no, I've been busy.  The changes don't seem too hard, but I'm going to have even less time coming up.   :(

I'll see what I can do next week.

**Comment by sebastianwindeck** [comment]
@boorad  the feature you proposed is pretty useful. Could you give a hint what to add or do to push this chart type to superset.

**Comment by sebastianwindeck** [comment]
@boorad ... Are you still on this pull request. I'd like to implement this solution in superset, too. Could you add some notes to tell me where to proceed. Best :)

**Comment by nvlong198** [comment]
hope Gantt Chart reopen

**Comment by Codes-Lab** [comment]
I also hope for the reopening of the Gantt chart.

**Comment by mmospanenko** [comment]
any updates?

**Comment by Stefan781** [comment]
Would be great to have a Gantt chart option. I am not sure if the current PR is still usable after so many years. There is a [Gantt chart example with ECharts](https://echarts.apache.org/examples/en/editor.html?c=custom-gantt-flight) but it is a custom chart and it might be substantially involved to integrate. If somebody wishes to implement a Gantt chart into Superset they might find the resource useful.

**Comment by redanium** [comment]
With help of cursor and some tweakings I got something working ((based on the columns you see))
Image

**Comment by mistercrunch** [comment]
@redanium, are you thinking about contributing this back? Happy to help reviewing the PR.

**Comment by redanium** [comment]
@mistercrunch it's a pleasure .  I just need to fix some stuff.

**Todo  :**
-  Generic `ControlSetRows` for any _**dataset**_ with different columns names (**I need some help**)
- Locale based on Supabase locale
- ColorScheme

**Pull request closed without merging**
