### PR TITLE
[WIP] Add dual-axis line chart to viz

### PR DESCRIPTION
**Pull request by vera-liu**
Feature request: [https://github.com/airbnb/superset/issues/738](url)

Done:
 - Added a new viz using two y axis for multi-chart in nvd3
 - Options in control panel to set metric and axis format for two y axis

screen shot 2017-01-05 at 5 05 37 pm

Todo:
 - add more controls to dual-axis line chart, such as separate sql queries for two y axis, showLegend, y-log etc.

needs-review @ascott @mistercrunch @bkyryliuk

### CODE REVIEW

**Comment by ascott** [comment]
this is looking good! could we add tests?

also, we should think about how we are adding vis's and how there is duplication between the front end and backend for field type declarations. would be nice to solve that, but not necessarily a blocker for this PR.

**Comment by yileic** [comment]
Hi, it seems the x axis time is not correct. Is this in progress and will be merged soon?

**Comment by mistercrunch** [comment]
Please fix the landscape/codeclimate issues. A new example `Slice` in `superset/data/__init__.py` would be nice to showcase this feature with an example and would automatically get picked up for backend tests and provide coverage.

I did not dig deep into the derivative class of `BaseViz` but it seemed like there was some copy-paste from other NVD3 timeseries classes. If there's lots of common logic it should be handled in a parent class, but that may be complex and obfuscating. I could take a deeper look if necessary.

**Comment by ascott** [comment]
agreed, adding an example would be great. LGTM once an example is added.

**Comment by yileic** [comment]
Hi, I think there are two problems existing:
1. x-axis not displaying correct time
2. when the two y axises are using different formats, the tool tip will only use one format for the two lines (the left y axis's format)

They seem to be problems of the nvd3 library. How do you plan to deal with those problems?
Thank you very much!

**Pull request merged**
