### PR TITLE
[Build] moves prettier check to separate script

### PR DESCRIPTION
**Pull request by nytai**
### CATEGORY

Choose one

- [ ] Bug Fix
- [ ] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [x] Build / Development Environment
- [ ] Documentation

### SUMMARY

I added the prettier check script a while back to check formatting in css files. It doesn't need to be part of the regular lint check as it delays running eslint and makes passing flags more complicated. However it does need to run on CI to ensure no unformatted css files slip through (eslint isn't checking style files). 

### TEST PLAN

- CI passes and checks js/ts and style files.
### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by etr2460 — COMMENTED** [review]
Should we make sure this is part of the pre-commit hook?

**Review by craig-rueda — APPROVED** [review]

**Comment by nytai** [comment]
@etr2460 we have a pre-commit hook?

**Comment by nytai** [comment]
the only thing I found is https://github.com/apache/incubator-superset/blob/master/.pre-commit-config.yaml and that looks like it only includes python checks. Is there another one concerned with npm checks? Or should we consider adding npm checks here?

**Comment by etr2460** [comment]
I think you could use https://github.com/pre-commit/mirrors-eslint?

**Comment by etr2460** [comment]
But to be clear, my comment isn't blocking this PR

**Comment by ktmud** [comment]
Can we not have pre-commit hooks? It slows things down and not really pleasant to use. Most IDEs, if properly configured, would already warn these errors. 

Redash guys actually removed it from their repo: https://github.com/getredash/redash/pull/4435

**Pull request merged**
