### PR TITLE
fix(dashboard): padding between rows within tabs

### PR DESCRIPTION
**Pull request by gbusch**
### SUMMARY
There should be padding between rows in a dashboard. Before, this did not work when the rows where within tabs. This is fixed here.
See this issue: #20303 

### BEFORE SCREENSHOT
Screenshot 2022-06-13 at 22 57 58

### AFTER SCREENSHOT
Screenshot 2022-06-13 at 22 56 44

### TESTING INSTRUCTIONS
* Insert two charts into a new dashboard
* Add a filter. When hovering over a filter, the selection box shows some space between the plots
* When you move the charts into tabs, there is no space between plots any more (see first screenshot)
* AFTER APPLYING CHANGES FROM PR:
* Now there is also some space when the charts are within tabs (see second screenshot).

### CODE REVIEW

**Comment by gbusch** [comment]
@stephenLYZ merged master and run format

**Comment by stephenLYZ** [comment]
@gbusch Can you resolve the conflict so we are trying to get it?

**Comment by gbusch** [comment]
I think I messed this one up because I did not understand the pipelines at that time...
Probably it is easier to open a new - clean - PR: #21323  and close this one.

**Pull request closed without merging**
