### PR TITLE
chore: bump superset-ui

### PR DESCRIPTION
**Pull request by etr2460**
### SUMMARY
Pulls in changes from myself and @villebro 

Includes:
- https://github.com/apache-superset/superset-ui/commit/124b3446a2ca239a7f79e451562f776352951663
- https://github.com/apache-superset/superset-ui/commit/46728e8f0c40961f80ba2f093a1cf2248cd49eb1
- https://github.com/apache-superset/superset-ui/commit/db3bd2664ad568be7e1291f760a412c641b1698a
- https://github.com/apache-superset/superset-ui/commit/1368fdc37aed0dea4b0419785c5afa102dc56674

### TEST PLAN
CI

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

to: @villebro @ktmud @graceguo-supercat

### CODE REVIEW

**Comment by ktmud** [comment]
Mind adding links to related PRs or GitHub branch compare view?

**Review by ktmud — APPROVED** [review]

**Comment by etr2460** [comment]
@ktmud, it looks like the cypress failure is legit. `Should not load mathjs when not needed` is failing, could that be caused by superset-ui changes?

Maybe @villebro knows why this might happen too?

**Comment by villebro** [comment]
@etr2460 `mathjs` has been added as a dependency to the `plugin-chart-echarts` package to parse the formula annotation layers (it's called by `transformProps.ts`). I'm unsure why the `legacy-preset-chart-nvd3` plugin package is able to avoid loading it, as it uses `mathjs` in much the same fashion. But if this is not avoidable in the future, I suggest removing the test.

**Comment by ktmud** [comment]
I'm updating the superset-ui packages in another PR. Let's see if the test still fails.

**Comment by etr2460** [comment]
Was implemented by another PR, closing

**Pull request closed without merging**
