### PR TITLE
chore: Select component refactoring - MetricControl - Iteration 5

### PR DESCRIPTION
**Pull request by geido**
### SUMMARY
It replaces the react-select Select component with the Antdesign one in the MetricControl component.

### BEFORE

https://user-images.githubusercontent.com/60598000/130652776-e0bdd02d-8aba-4525-95ae-3a7d4fcb1806.mp4

### AFTER

https://user-images.githubusercontent.com/60598000/130655498-d2edfd4b-dbd6-4283-9230-e1c9344b44d5.mp4

### TESTING INSTRUCTIONS
1. Open Explore
2. Add all different types of Metrics

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by michael-s-molina — APPROVED** [review]
Code LGTM. We can improve it by supplying human readable  `aria-labels`.

**Review by michael-s-molina — APPROVED** [review]
LGTM

**Review by pkdotson — APPROVED** [review]
LGTM! Thanks for the changes!

**Pull request merged**
