### PR TITLE
docs: Fix typo in installing from scratch

### PR DESCRIPTION
**Pull request by philipqnguyen**
Change "insode" to "inside".

Note:
Original PR was here https://github.com/apache/incubator-superset/pull/10985, but the CI seemed to continually be stuck even after multiple retries. So I'm trying again with a new PR and a new commit.

### CODE REVIEW

**Review by nytai — APPROVED** [review]

**Comment by nytai** [comment]
I'm still very confused about what's going on here, for some reason not all the checks are running

**Comment by philipqnguyen** [comment]
Ya, I'm at a loss as well @nytai. I guess you could make your own PR with this change separately to see if that works?

**Comment by nytai** [comment]
Yeah I'll open a PR, this probably isn't worth spending more time on

**Comment by nytai** [comment]
Ah, looks like the same thing happened on my PR. Looks like it's this filter here https://github.com/preset-io/incubator-superset/blob/master/.github/workflows/superset-python.yml#L9

**Pull request merged**
