### PR TITLE
chore: Bump FAB to 3.4.0

### PR DESCRIPTION
**Pull request by kamalkeshavani-aiinside**
### SUMMARY

Bumping FAB to latest 3.4.0
Changes:
- dpgaspar/Flask-AppBuilder#1735 [Daniel Vaz Gaspar]
- dpgaspar/Flask-AppBuilder#1733 [Ke Zhu]
- dpgaspar/Flask-AppBuilder#1728 [Daniel Vaz Gaspar]
- dpgaspar/Flask-AppBuilder#1707 [Daniel Vaz Gaspar]

### CODE REVIEW

**Review by dpgaspar — APPROVED** [review]
LGTM, Thank you!

**Comment by kamalkeshavani-aiinside** [comment]
@junlincc Please tag this for v1.4

**Review by villebro — APPROVED** [review]

**Comment by villebro** [comment]
@kamalkeshavani-aiinside FYI I updated the description to link to the PRs on the FAB GH repo (now the numbered tags were pointing to issues on this repo)

**Comment by usamaB** [comment]
I tried the 1.4.0rc1 but the login/logout flow hasn't been fixed. I'm unable to logout. It just automatically logs in and brings me to the welcome screen. And the login flow is incorrect as well. If you have a single provider it doesn't show login UI but takes directly to enter email/pass UI(google in my case).

**Comment by dpgaspar** [comment]
@usamaB  with FAB 3.3.0 that behaviour is expected, have you rebuilt your container with this commit included?

**Pull request merged**
