### PR TITLE
chore(explore): Set Drag&Drop feature flags to True by default

### PR DESCRIPTION
**Pull request by kgabryje**
### SUMMARY
Flip `ENABLE_EXPLORE_DRAG_AND_DROP` and `ENABLE_DND_WITH_CLICK_UX` feature flags to `True` by default. This will enable the drag and drop controls in the chart control panels in Explore pages.
Related PRs: https://github.com/apache/superset/pulls?q=is%3Apr+is%3Aclosed+drag+and+drop+in%3Atitle%2Cbody+

### ADDITIONAL INFORMATION

- [ ] Has associated issue: https://github.com/apache/superset/issues/18901
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

https://app.shortcut.com/preset/story/39407/flip-dnd-feature-flags-2-0

### CODE REVIEW

**Review by michael-s-molina — APPROVED** [review]
LGTM. We just need to fix the tests that expect these flags to be false.

**Comment by john-bodley** [comment]
@kgabryje would you mind also adding a line item to `UPDATING.md` so institutions are aware of the change?

**Comment by ktmud** [comment]
I'm not sure if we should include links to an internal issue tracking tool in the PR... it feels exclusive when someone not from your org cannot open the link.

**Comment by kgabryje** [comment]
> @kgabryje would you mind also adding a line item to `UPDATING.md` so institutions are aware of the change?

Thanks for the reminder John! https://github.com/apache/superset/pull/19108

**Comment by kgabryje** [comment]
> I'm not sure if we should include links to an internal issue tracking tool in the PR... it feels exclusive when someone not from your org cannot open the link.

Agreed, let's drop that habit. Cross-linking issues in Github and Shortcut was supposed to help tracking them, but I don't think it's actually been useful. CC @rusackas

**Pull request merged**
