### PR TITLE
7366: Added requirements-fill.txt file having mandatory & optional pa…

### PR DESCRIPTION
**Pull request by abhioncbr**
7366: Added requirements-fill.txt file having mandatory & optional packages along with databases packages.

### CATEGORY

Choose one

- [ ] Bug Fix
- [x] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY
Added requirements-full.txt file with all required, optional and database packages. It's related to issue 7366

### TEST PLAN
Pip freeze should have same dependent packages using requirements-full.txt

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by villebro** [comment]
Perhaps the supplemental requirements could be in a separate file, e.g. `requirements-optional.txt` or similar? This would avoid having the same requirement defined in two places, which will be difficult to maintain.

**Comment by mistercrunch** [comment]
Is this for docker? Wouldn't people no want all the junk in their image, and add a layer on top with just what they need/want? Your extra layer would add something like `RUN pip install superset[hive]` (leveraging the `extras_require` ideally)

I was also wondering how this file was generated, it appears to be `pip-compile` but the command at the top got removed(?). Anyhow it should be reproducible so that every time `setup.py` changes, there's a clear process to follow to pip-compile and pin things.

There's a hack to get the `extras_require` in there. https://github.com/jazzband/pip-tools/issues/331

We could have a collection of `requirements.in` files that contain just `-e .` and another that's like `requirements-hive.in` that has `-e .[hive]`, and so on, for each entry in `extras_requires`. Put all of these in a `requirements/` folder as it starts to get messy in the root. Also a small shell script to re-generate all these files... Might be overkill though.

**Comment by abhioncbr** [comment]
Thanks, @villebro & @mistercrunch for sharing the feedback.

@mistercrunch, yes I wanted to have such a feature for docker. I can understand with a slim docker image reasoning, and people can install required packages on top of it, but over the time I realized that users/people don't want to put much effort in enhancing docker image. My intent of starting a Superset docker image repo is to have one image which can be leveraged for learning/exploration as well as putting the same into the production system. Recently, realized new releases of Superset is getting slimmer(which is good), for example, Flower package is optional now, and I have to install explicitly in later versions of docker image which makes much harder to manage DockerFile. Hence, I want all the packages i.e, mandatory & optional ones in Superset codebase so that it would be easier to install(not for me, for other guys too). Does it make sense?

Yes, the checked-in file created manually, and I like the idea which you proposed for managing the requirements. Several 'requirements.in' files in the 'requirement' folder with the output text files. I will make the changes as per suggestion. Thanks.

**Comment by abhioncbr** [comment]
@mistercrunch @villebro please review.

**Comment by mistercrunch** [comment]
Shouldn't the output files be checked in as well?

**Comment by abhioncbr** [comment]
Yes, It should be. I have generated files but packages version for almost all of the package are different from the version present in the requirements.txt, and that's why I skipped it. You want me to put that too?

**Comment by abhioncbr** [comment]
Added generated files i.e. requirements-presto.txt, requirements-hive.txt & requirements-gsheets.txt.

**Comment by abhioncbr** [comment]
The last travis build failed because of license-check step however I can see PR `.rat-excludes` file have exclusion entries for it.

**Comment by mistercrunch** [comment]
One question here is whether there's a way to **ONLY** store the "extras" as opposed to base Superset deps + the extras...

**Comment by lrosenman** [comment]
Can we build a requirements.txt for LDAP as well as gunicorn's use of gevent?

**Comment by abhioncbr** [comment]
@mistercrunch wasn't able to find ONLY option.

**Comment by abhioncbr** [comment]
It's weird that build is passing in my repo https://travis-ci.org/abhioncbr/incubator-superset/builds/534304617

**Comment by mistercrunch** [comment]
To solve the problem of installing the extras also installing the base libs, how about, in a new `gen_requirements.py` we:
* parse the `extra_requires` and generate the `requirements-{extra}.in`
* run pip-tools for each one of them

One thing is you may not be able to import setup.py for different reasons. If that's the case, we could store in `requirements/extras.yaml` the list that would be used by both `setup.py` and `gen_requirements.py`.

**Comment by abhioncbr** [comment]
@mistercrunch not very much sure that above-suggested changes. I would be thinking, It's good to merge the changes and create a new ticket for the above suggestions, as this PR is long pending.

**Pull request closed without merging**
