### PR TITLE
Fix for showing datasources with same name but with different clusters

### LINKED ISSUE #1989: Adding multiple Druid clusters with same names for the data sources only shows one set of data sources
### Superset version
0.6.10

### Expected results
We configured two superset clusters, one for staging and one for prod. They both have data sources named messages, enrollment, status. We would expect to see data sources for both the staging and production clusters come up for messages, enrollment, and status, so a total of 6.

### Actual results
We are only seeing data sources coming up for our production cluster, not staging. So, only a total of 3 data sources.

### Steps to reproduce
1) Login to Superset
2) Add two data clusters with the same data source names
3) Refresh Druid metadata
4) Only able to see data source names for production cluster.

Also, we added a data source called "test" on staging, and it did show up.

How do we get around this issue?

### PR DESCRIPTION
**Pull request by ankurp**
Fixes #1989

### CODE REVIEW

**Comment by bkyryliuk** [comment]
@ankurp  could u add a alembic migration and fix the tests ?

**Comment by ankurp** [comment]
@bkyryliuk Updating.

**Comment by ankurp** [comment]
@bkyryliuk I am having a hard time trying to create a migration that can remove the unique constraint on datasource_name. Can you or someone help me out as I cannot remove the constraint because the constraint does not have a name.

**Comment by mistercrunch** [comment]
@ankurp check out `utils.generic_find_constraint_name` and how it's used in other migrations, we've had this problem before and that was part of the solution. You can also find where the original constraint was created and remove it. That makes sure that people upgrading from a fresh db won't have to create / delete it.

**Comment by mistercrunch** [comment]
Closing old PRs with broken build or merge conflict, feel free to re-open once merge conflicts are sorted out.

**Pull request closed without merging**
