### PR TITLE
chore(gha): bump ubuntu to latest fresh release

### PR DESCRIPTION
**Pull request by mistercrunch**
Title. Simple bump as 24.04 just came out

### CODE REVIEW

**Review by rusackas — APPROVED** [review]

**Review by villebro — APPROVED** [review]

**Comment by rusackas** [comment]
The same E2E test is failing repeatedly, but I haven't seen it fail on other PRs, which is... strange.

**Comment by mistercrunch** [comment]
It's weird how flakiness is random across the board but sometimes consistently failing on a specific PR. This one has probably 4-5 failures straight

**Comment by rusackas** [comment]
Restarting the failing e2e test since it sure seems unrelated. This is what it was, for the record, in case it happens again:

image

**Comment by mistercrunch** [comment]
Yeah I tried my luck like 5+ times, at this point I feel like leaving that one step in previous ubuntu and moving on with our lives.

**Comment by mistercrunch** [comment]
Ok there's that one lingering e2e GHA that I left on the previous version of Ubuntu, hoping to repeat the pattern I'm establishing in https://github.com/apache/superset/pull/31490 on e2e later on, hopefully will get rid of this odd case in Docker/Debian

**Pull request merged**
