### PR TITLE
[clarity/consistency] rename /explorev2/ -> /explore/

### PR DESCRIPTION
**Pull request by ascott**
since we only have 1 version of the explore app/page, let's rename `explorev2 -> explore` for clarity.

@mistercrunch @graceguo-supercat @ddol

### CODE REVIEW

**Comment by mistercrunch** [comment]
I think you may need to write a database migration script for the URL shortner and/or a redirect endpoint for the old `explorev2`.

**Comment by ascott** [comment]
@mistercrunch added a redirect here https://github.com/airbnb/superset/pull/2802/files#diff-ac978615a4f22c4fad4d01f39e1d4595R990

**Comment by mistercrunch** [comment]
LGTM

**Comment by ascott** [comment]
codeclimate is complaining about a missing file extension, but i can't figure out why only this one, and why i can't mark as fixed. 

screenshot 2017-05-24 14 57 52

**Comment by ascott** [comment]
code climate is not happy for reason mentioned above, but merging anyway.

**Pull request merged**
