### PR TITLE
Fix typos & Add athena description

### PR DESCRIPTION
**Pull request by yoonian**
Just added short information about Athena JDBC driver to give help selecting which Athena driver.

### CODE REVIEW

**Comment by mistercrunch** [comment]
I think you branched while `master` was broken, mind rebasing?

**Comment by mistercrunch** [comment]
@yoonian you can rebase now, the build on master is fixed

**Comment by yoonian** [comment]
@mistercrunch yes, it was rebased.

**Comment by mistercrunch** [comment]
Please reopen so I can merged

**Comment by yoonian** [comment]
Okay

**Pull request closed without merging**
