### PR TITLE
[big number] set start_y_axis_at_zero default to false

### PR DESCRIPTION
**Pull request by mistercrunch**
To stick with the previous behavior and get the trend line to show the
trend by default.

@kristw @williaster

### CODE REVIEW

**Comment by williaster** [comment]
Hmm, @kristw and @conglei and I discussed this because some users were upset about changing their old charts.

I think we aligned on starting at 0 as still being the best default, so I think we don't want to push this. We thought a better solution for keeping current users happy would be migrating existing slices to have the default, so that they don't change, but then all future charts will require consciously changing it to not start at 0. krist/conglei any other thoughts?

**Comment by kristw** [comment]
@williaster Actually only one person has that feedback. No other complaints since.

**Comment by williaster** [comment]
👍 even more support for not making this change?

**Comment by mistercrunch** [comment]
Just thought things looked very very flat after this change, I helped a user mass-update their charts to show some trends as they used to. I think that the Y axis being relatively short makes things look even flatter. Personally I'm thinking of this much like a spark line.

I'll rally with the majority though.

**Comment by conglei** [comment]
> We thought a better solution for keeping current users happy would be migrating existing slices to have the default, so that they don't change, but then all future charts will require consciously changing it to not start at 0. krist/conglei any other thoughts?

I do like this option: keeping the current users consistent experience while all future charts will have default to start at 0.   But to do this, we seems to have to do a data migration?

**Pull request closed without merging**
