### PR TITLE
feat(alert report tabs): adding feature flag

### PR DESCRIPTION
**Pull request by fisjac**
### SUMMARY

Adds a feature flag for implementing a new feature enabling the user to select which tab of the dashboard the user would like to send as an alert or report.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [x] Required feature flags: ALERT_REPORT_TABS
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by eschutho — APPROVED** [review]

**Review by michael-s-molina — CHANGES_REQUESTED** [review]
I left a comment about the feature flag. If needed, we also need to update `FEATURE_FLAGS`.md.

**Comment by fisjac** [comment]
@michael-s-molina could you clarify what you mean. It seems we have a couple options here:
1. build the feature flag and merge in. This would enable building smaller PRs to build out the feature, but possibly creates and unused feature flag if the feature isn't merged.
2. Build the feature as a separate branch and merge in together alongside the feature flag, creating a large PR.

We can go either way, but it would seem smaller PRs will be much easier to implement/review.

**Comment by rusackas** [comment]
Hey @fisjac - I think @michael-s-molina means that you just need to add an entry to [this file](https://github.com/apache/superset/blob/master/RESOURCES/FEATURE_FLAGS.md). Presumably under the "In Development" section. Note that if the feature flag gets added and then removed in-between minor versions (i.e. before Superset 4.1 is cut) you can just take it right out when you're done with development. If the flag gets released, removing it would constitute a breaking change, so we could remove it in ~6 months as part of Superset 5.0.

**Comment by michael-s-molina** [comment]
Hi @fisjac. Both options are valid but if you opt for the feature flag (useful if multiple developers), you need to update the `FEATURE_FLAGS.md` file.

**Review by michael-s-molina — APPROVED** [review]

**Review by rusackas — APPROVED** [review]

**Pull request merged**
