### PR TITLE
Pass extra configuration keys for feature flags

### PR DESCRIPTION
**Pull request by betodealmeida**
This PR extends the feature flag functionality by allowing users to pass extra keys as configuration.

@mistercrunch, @xtinec should we add a dummy `KEYS_CONF` to `config.py`?

### CODE REVIEW

**Comment by mistercrunch** [comment]
Can I merge https://github.com/apache/incubator-superset/pull/6808 first?

**Comment by betodealmeida** [comment]
@mistercrunch sure, go ahead!

**Comment by mistercrunch** [comment]
I'd like to make the feature conf dynamic too, much like the feature flags.

One thing to note here is that the feature flag and feature conf could be one and only thing. I'm not sure how other feature flag frameworks do this. I don't have a strong opinion on how it should be other than it should be possible to make this dynamic and we should follow standards. Now I wish I knew more about how Gatekeeper worked :)

**Comment by betodealmeida** [comment]
@mistercrunch cool, I'll update it after your PR. I think the function approach should allow us to reproduce GKs:

```python
def GET_FEATURE_FLAGS_FUNC(feature_flags_dict):
    if (
        is_admin(g.user) or
        is_data_scientist(g.user) or 
        g.user.id % 10 == 0
    ):
        feature_flags_dict['some_feature'] = True
    return feature_flags_dict
```

My first implementation of this extended the feature flag from a boolean to a dict, but @xtinec suggested separating them. I also have no strong opinions on one vs. the other approach.

**Comment by betodealmeida** [comment]
@mistercrunch this is ready for review.

**Comment by mistercrunch** [comment]
I finally took the time to do a bit more research. I had heard "LaunchDarkly" is an up-and-coming feature flag as a service company. I hear you, originally I also thought "really?!", but thinking about things like Gatekeeper and multi-language support and AB testing I thought "hmm well yeah probably makes sense"

Here's the way they to it (cmd-f to `multivariate`)
 https://docs.launchdarkly.com/docs/creating-a-feature-flag

They just have one namespace of features, and the feature can be boolean, but also other types, including nested/JSON.

**Comment by betodealmeida** [comment]
@mistercrunch I liked the idea, and I've actually did that for lightweight pipelines. :)

Closing this.

**Pull request closed without merging**
