### PR TITLE
chore: change dropdown icons from horizontal to vertical

### PR DESCRIPTION
**Pull request by pkdotson**
### SUMMARY
This pr changes the dropdown icons from horizontal to vertical for homepage cards, and datasource editor dropdown.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

https://user-images.githubusercontent.com/17326228/127712617-07f334f5-7d4b-4407-af99-01eb6e0cabff.mov

### TESTING INSTRUCTIONS
Go to homepage and listviews, and explore to checkout new icon

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by michael-s-molina** [comment]
@pkdotson I think we should use an icon with less space between the dots to make it shorter. Like the one on Google Drive:

Screen Shot 2021-07-30 at 9 43 50 AM

**Comment by junlincc** [comment]
> @pkdotson I think we should use an icon with less space between the dots to make it shorter. Like the one on Google Drive:

+1, the spacing of the icon doesn't look right. do we have the icon @michael-s-molina suggested handy somewhere? 

Reasons for change - menu that opens vertically should be represented by a vertical "three dots" icon versus using a horizontal icon to indicate opening a horizontal menu

**Review by rusackas — APPROVED** [review]
LGTM! Thanks for the cleanup!

**Pull request merged**
