### PR TITLE
refactor: move enums to the beginning of utils/core.py

### PR DESCRIPTION
**Pull request by ktmud**
### SUMMARY

Move the enums in `utils.core` to the beginning of the file and sort them in alphabetical order.

In general, enums should be placed at the beginning of each file because they are constants and wouldn't depend on anything else, while on the other hand, subsequent functions in the same file may need to use them.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

N/A

### TEST PLAN

CI

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by villebro — COMMENTED** [review]
Would now be a good time to move these to a separate file, like `superset/types.py`? I would also consolidate the aliases from `superset/typing.py` into the new file, as that name clashes with the builtin `typing`.

**Comment by ktmud** [comment]
> Would now be a good time to move these to a separate file, like `superset/types.py`? I would also consolidate the aliases from `superset/typing.py` into the new file, as that name clashes with the builtin `typing`.

Do we consider enums part of typing? I thought they are constants as well.

Was debating internally whether to move them into `superset.constants`, but kind of also feel for less general enums, they should probably be put locally into each submodule. It's a hard choice, so I went with the easiest and smallest change...

Either way, we should definitely find ways to break up the thousand-LOC `core.py` files.

Could you clarify how does `superset.typing` clashes with the builtin module?

**Comment by villebro** [comment]
> > Would now be a good time to move these to a separate file, like `superset/types.py`? I would also consolidate the aliases from `superset/typing.py` into the new file, as that name clashes with the builtin `typing`.
> 
> Do we consider enums part of typing? I thought they are constants as well.

Hmm, I've always thought of enums as being types, and strictly speaking they are in Python, anyway:
```python
>>> from enum import Enum
>>> class MyEnum(Enum):
...     ABC = 1
...
>>> abc = MyEnum.ABC
>>> type(abc)
<enum 'MyEnum'>
```
But if the general convention is to call them constants I'm fine with that, too. 

> Was debating internally whether to move them into `superset.constants`, but kind of also feel for less general enums, they should probably be put locally into each submodule. It's a hard choice, so I went with the easiest and smallest change...
>
> Either way, we should definitely find ways to break up `core.py` files that have thousands of lines of code.

I agree, the specific types should probably be put in the correct submodule, as right now `utils/core.py` is really bloated with these. But that can be saved for a later PR.

> Could you clarify how does `superset.typing` clash with the builtin `typing`?

I've seen quite a few reports where `import x from typing` is picking up `superset.typing`. Here's a recent example: https://github.com/apache/incubator-superset/issues/11925 . This once happened to me, too, but not sure what was causing it, probably something with an incorrect `PYTHONPATH`.

**Comment by ktmud** [comment]
@villebro then is this PR good for merge as is or do you want me to move the enums to `typing`?

**Review by villebro — APPROVED** [review]

**Pull request merged**
