### PR TITLE
Change the size of the column datasource_name in datasource creation …

### PR DESCRIPTION
**Pull request by ludzzz**
…table to fix a Sql server specific issue.
The impact should be very low, No reason of side effect or Regression.

### CODE REVIEW

**Comment by mistercrunch** [comment]
You need to change it here too:
https://github.com/airbnb/caravel/blob/master/caravel/models.py#L852

**Comment by gyzmau** [comment]
Oh yes, definitely. I missed this one, sorry. I am changing it.

**Comment by gyzmau** [comment]
Changed done

**Comment by mistercrunch** [comment]
Thanks for taking the time!

**Comment by gyzmau** [comment]
You are welcome. Glad if it can help.

**Comment by gyzmau** [comment]
To follow up. I got an issue previously about the metrics i didn't take it in account at this time.
Its seems there is another discrepancy on foreign key.
`
sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42000', "[42000] [M
icrosoft][SQL Server Native Client 11.0][SQL Server]Column 'datasources.datasour
ce_name' is not the same length or scale as referencing column 'metrics.datasour
ce_name' in foreign key 'FK__metrics__datasou__693CA210'. Columns participating
in a foreign key relationship must be defined with the same length and scale. (1
753) (SQLExecDirectW); [42000] [Microsoft][SQL Server Native Client 11.0][SQL Se
rver]Could not create constraint. See previous errors. (1750)") [SQL: u'\nCREATE
 TABLE metrics (\n\tid INTEGER NOT NULL IDENTITY(1,1), \n\tmetric_name VARCHAR(5
12) NULL, \n\tverbose_name VARCHAR(1024) NULL, \n\tmetric_type VARCHAR(32) NULL,
 \n\tdatasource_name VARCHAR(250) NULL, \n\tjson VARCHAR(max) NULL, \n\tdescript
ion VARCHAR(max) NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(datasource_name) RE
FERENCES datasources (datasource_name), \n\tFOREIGN KEY(datasource_name) REFEREN
CES datasources (datasource_name)\n)\n\n']
`
I Just started an install from scratch. 
Before to make another PR. I will go through all the process and check all the foreign keys.
Sorry I dunno why i didn't see it the first time.
I was too eager to make it work.

**Pull request merged**
