### PR TITLE
fix: Revert "fix(sqllab): reinstate "Force trino client async execution" (#25680)

### PR DESCRIPTION
**Pull request by michael-s-molina**
### SUMMARY
This reverts commit 4e94fc4cff9e7dff2ddd7c176b647bdb19b9b1e2.

We have many users reporting queries being stuck for hours and never returning. Preset is also facing the same problem according to this [comment](https://github.com/apache/superset/pull/25680#issuecomment-1799263589) from @sadpandajoe. 

We're still not able to pinpoint the exact problem but we can confirm that reverting the original commit fixes the issue.

@villebro @giftig @sadpandajoe @john-bodley @justinpark 

### TESTING INSTRUCTIONS
CI.

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by michael-s-molina** [comment]
@justinpark @sadpandajoe Please add any comments regarding your investigations that might help the author to fix the issue.

**Comment by sadpandajoe** [comment]
@betodealmeida may have a better idea with the investigation

**Comment by betodealmeida** [comment]
See https://github.com/apache/superset/pull/25897

**Comment by justinpark** [comment]
Verified https://github.com/apache/superset/pull/25897 fixes the trino multiple statement stuck issue.

**Comment by michael-s-molina** [comment]
Closing in favor of https://github.com/apache/superset/pull/25897

**Pull request closed without merging**
