### PR TITLE
Adding YAML Import-Export for Datasources to CLI

### PR DESCRIPTION
**Pull request by fabianmenges**
# Summary
Adding YAML import and export for datasources, which includes (SqlAlchemy) Databases and Druid Clusters to the Superset CLI. 

## Description
I added the core of the Import/Export logic to the `ImportMixin` mix-in class. It heavily relies on SqlAlchemy to determine the schema of the YAML and the relationship of objects. Specifically it uses unique constraints to identify and update existing elements. This required me to add unique constraints to existing tables, but I'm pretty confident that this should not cause major issues with existing installations since I added them in the "spirit" of the current design. 

In addition to the SqlAlchemy relationships the main object hierarchy needs to be defined by configuring the `export_parent` and `export_children` attributes appropriately (documented in code).

The unit test covers only basic importing exporting  (it was liftet from the existing pickle import/export) and should probably be extended to cover more edge cases.

You can export databases, druid clusters, tables, datasources from the UI:
screen shot 2017-11-16 at 6 52 46 pm

 
## Possible Future Projects/Improvements
-  Add YAML import/export for Slices and Dashboards. 
- Adding support to import/export individual database / tables / metrics, etc.  as root element of a YAML  file.
- Support of importing multiple YAML files at the same time
- Support to split exports into smaller files
- It would also be nice to use the YAML import for the example datasets. 
- Adding YAML import to the Web UI and/or API 

Re-created #2993 This PR was getting too old for travis.
Context: https://groups.google.com/forum/#!topic/airbnb_superset/GeWZs42_NyA

### CODE REVIEW

**Comment by mistercrunch** [comment]
Looks like travis isn't kicking in, any idea why? I noticed that before only on your PRs, bad luck or something related to your workflow?

**Comment by fabianmenges** [comment]
Apparently travis says 'abuse detected'. I'm contacting travis support and CC you.

**Comment by mistercrunch** [comment]
In the meantime you can probably branch off your branch, amend the commit with a different commit message to get a different SHA, and open a new PR off of it referencing this one. Might work...

**Comment by fabianmenges** [comment]
Finally got picked up by Travis.

**Comment by yamyamyuo** [comment]
Hi @mistercrunch , I am very interested in this feature 
> Possible Future Projects/Improvements: Add YAML import/export for Slices.
is there any plans for that?

**Comment by mistercrunch** [comment]
@yamyamyuo note that it's possible to do most of this using the ORM directly. Could be good to have a code generation feature as an export. Exporting would generate code that uses the ORM to create the slice and/or dashboard.

Check out this file for an example of how we generate the examples:
https://github.com/apache/incubator-superset/blob/master/superset/data/__init__.py#L79

Note that of course this isn't a public API, and we won't provide guarantees around forward compatibility, though it shouldn't change much.

**Pull request merged**
