### PR TITLE
New viz: box plot

### PR DESCRIPTION
**Pull request by andrewhn**
Hi,

This PR implements an NVD3 box plot (shown below). I added an example slice so it's picked up in the tests.

There is one custom option for box plots for the user to select the whisker calculation method (options are currently Tukey or quartiles +- 1.5*IQR, min/max, 2nd/98th percentile, or 9th/91st percentiles, although easy to add more).

I wasn't sure how to add an image in the gallery, so that's not in this PR, apologies.

I also wasn't 100% on how the `color` function is supposed to work (it seems to recurse through attributes which are lists). For the box plot data structure required by NVD3 to work, I had to add a null check in the color function as the 'outliers' attribute only contains data. Consequently all outliers are all colored black, although I don't think this is a problem.

image

### CODE REVIEW

**Comment by mistercrunch** [comment]
This looks amazing! I can take care of the image later (I just added a feature that shows the thumbnail in the viz_type dropdown in the explroe view (https://github.com/airbnb/caravel/pull/313)). It's as simple as creating a 1024*1024 png and dropping it in `caravel/assets/images/viz_thumbnails`, with a name that matches the name of the viz_type. For the gallery there's an extra entry in `docs/gallery.rst`

So the javascript linter is aggressive and breaks the build. You can run `npm run lint` locally or look at the travis logs for the details. It also looks like landscape.io (python linter) isn't triggering anymore, I'm not sure what's up with it. I'll look into it.

**Comment by andrewhn** [comment]
Ah, I did not do that. Just pushed changes to make the linters happy. Hopefully all good now

**Comment by mistercrunch** [comment]
This is great! Picture the diversity of the visualization Caravel will be able to offer if only a few of us can contribute new visualizations on a regular basis.

Also I would love feedback and thoughts on how to improve the framework, and make it easier to add new visualizations. For instance we were thinking about moving the form controls on the javascript side, and using React to wrap the components.

**Comment by philippfrenzel** [comment]
great

**Pull request merged**
