### PR TITLE
feat: add France's regions to country map visualization

### PR DESCRIPTION
**Pull request by dmeaux**
### SUMMARY
France's Regions have been added as a selection to the Country Map visualization. The geometries were taken from IGN's (France's National Geographic Institute) BD TOPO (R) administrative layer, and the ISO 3166-02 codes for the regions were added as an attribute.

### BEFORE/AFTER SCREENSHOTS
**France's Departments:**
france_departments

**France's Regions:**
france_regions

### ADDITIONAL INFORMATION
- [x] Has associated issue: #25673
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by villebro — APPROVED** [review]
LGTM, thanks for adding the regional granularity!

**Comment by qleroy** [comment]
@dmeaux Does it work on your system ?

The file france_regions.geojson appear to be huge compared to the other ones (12 MB).

It does not display correctly

france regions broken

But it can confirm it displays correctly with matplotlib, using the Country Map GEOJSON Generator notebook.

What could be the problem ?

**Comment by dmeaux** [comment]
Yes, It does. The geometries are much more detailed than the other layers.


David

***************************************************************

DAVID MEAUX


________________________________

**Comment by dmeaux** [comment]
@qleroy
Yeah, usually geojson is in WGS84 with longitude and latitude as the X/Y coordinates, but you can embed projected data as well. 

Check out this line at the top of the file: 
`"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:EPSG::2154" } }
This refers to the **C**oordinate **R**eference **S**ystem, which in this case is EPSG:2154, or Lambert 93.

I will reproject the data to WGS 84 and simplify the geometries to decrease the file size and then recommit the file. This should fix the issues you're seeing.

**Comment by qleroy** [comment]
thank you @dmeaux 

maybe d3 does not take the coordinates system into account I don't know.

I was considering including also DOM/TOM with cartiflette
https://observablehq.com/@linogaliana/cartiflette-demo?collection=@linogaliana/cartiflette

**Comment by qleroy** [comment]
I double checked,
indeed france_regions.geojson is the only file exceeding the bounds

According to [d3 docs](https://d3js.org/d3-geo/path#path_projection) and referring to the [plugin CountryMap.js](https://github.com/apache/superset/blob/dfc614bdc3c8daaf21eb8a0d1259901399af7dd8/superset-frontend/plugins/legacy-plugin-chart-country-map/src/CountryMap.js#L74), all *.geojson files are expected to be projected with the default projection.

All geojson files are in the urn:ogc:def:crs:OGC:1.3:CRS84 projection except for france_regions.geojson !

So that is why it cannot by displayed properly in Superset with the plugin code as is.

```bash
for f in $(ls superset/superset-frontend/plugins/legacy-chart-country-map/src/countries)
do
echo $f
jq '.crs' $f
done
```
```
france_regions.json urn:ogc:def:crs:OGC:1.3:CRS84

{
  "type": "name",
  "properties": {
    "name": "urn:ogc:def:crs:EPSG::2154"
  }
}

...

france.geojson
{
  "type": "name",
  "properties": {
    "name": "urn:ogc:def:crs:OGC:1.3:CRS84"
  }
}
...
```

```python
france_regionsgeojson
         minx       miny       maxx       maxy
0    428145.7  6137101.2   848021.3  6439668.0
1    476864.7  6584220.1   709599.9  6872271.0
2    342953.8  6788980.8   612865.2  6998209.9
3    311617.1  6193024.1   669901.0  6679340.2
4    728354.5  6710828.6  1082838.3  7009414.0
5    799585.9  6214487.5  1077719.3  6453457.6
6    626126.3  6338318.9  1027292.6  6633794.6
7    688333.0  6562601.2  1011638.9  6811153.5
8    276123.7  6582709.1   545050.0  6834664.4
9    583916.5  6859783.5   790288.4  7110478.8
10    99040.0  6704161.1   400665.5  6886001.0
11  1156227.0  6046546.3  1242440.3  6235448.1
12   586421.7  6780020.5   741205.6  6905411.1
```

**Comment by xavier-GitHub76** [comment]
Hello,

I use superset 3.1.1 but I have the same issue :
image

Best resgards

**Pull request merged**
